### ISSUE TITLE
Use separate namespace for runPython doing internal stuff

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1000]
pyodide needs to import packages for various internal purposes. Currently these packages pollute the global namespace. #922 demonstrates a mixture of two problems: one is a confusion between `pyodide_py` and `pyodide_js` (see #992). The other problem is this namespace pollution.

Pending merge of #923, we can use custom namespaces. I think we should make a separate namespace for internal use and a separate entrypoint `runPythonInternal` which does `eval_code(code, internal_namespace)` and then use this in initialization and for stuff like `invalidate_caches`.

**Comment by hoodmane** [comment]
I now think we should separate the `ns` argument of `eval_code` into `locals` and `globals`, and then internally to `pyodide.js` use `eval_code` with `locals` as a temporary empty dictionary.

**Comment by rth** [comment]
I think this can be closed?

**Comment by hoodmane** [comment]
Closed by #1195.
