### ISSUE TITLE
Bug: pyproxies need to be refcounted

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1049]
Thanks to @mgreminger (see his original report in #1006).
```javascript
pyodide.runPython('a=lambda x: 2*x');
ref1 = pyodide.runPython('a');
ref2 = pyodide.runPython('a');
console.log('first try:', ref2(10)); // prints 20
ref1.destroy();
console.log('second try:', ref2(20)); // results in Error: Object has already been destroyed
```

**Comment by mgreminger** [comment]
Thanks, @hoodmane. After thinking about this more, there's potentially another issue going on in addition to reference counting. I realized that `a` is still in scope on the Python side in my example so `a` will have a ref count of at least 1 (ideally 2 after ref1 is destroyed). So the second potential issue is what `.destroy()` is doing with objects that still have a ref count > 0 on the Python side. My understanding was that `.destroy()` was just decrementing the ref count on the Python side to allow the Python GC to do it's work, but there's something more going on here. To truly test what I was intending, I would of had to call `del a` from the Python side before trying to access `ref2` for the second time.

**Comment by hoodmane** [comment]
@mgreminger I think you are missing the point here. Yes `destroy` does `Py_DECREF` the wrapped `PyObject*`. But the more important thing it does is disable the pyproxy. The pyproxy is disabled regardless of what the new Python refcount is after `Py_DECREF`. If we just stopped caching the pyproxies and generated a new pyproxy every time, this bug would be resolved. I don't even think we would leak much more memory. The caching of the pyproxies is wrong, because it behaves as if the pyproxy were immutable but destroy mutates it.

As you can see from the fact that the error occurs without `del a` or invoking the Python garbage collector, python GC is unrelated to this bug.

**Comment by mgreminger** [comment]
@hoodmane, thanks for the clarification. Yes, totally agree that there are two different issues here.
