### ISSUE TITLE
FeatureRequest : a API to add or remove file or package into wasm.FS

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [pyodide/pyodide#1054]
like #972 

similar, can we have a offical API to load and unload a python file(string) or some file(string) ( or like a package dir) to become a python package ?

i think this can help to create some polyfill to replace some feature with js helper that origin python have but pyodide not have , like some polyfill in js.

example, we can manual implement some lost feature like thread or asyncio or other in js side , and make a polyfill(wrapper) package into pyodide to let some package can work without the lost feature part.

i tried the [960](https://github.com/iodide-project/pyodide/issues/960#issuecomment-751425156) , and i find that manually do it are too complex for a person that dont have deep understanding in python like me .

**Comment by dalcde** [comment]
You can also use emscritpen's file_packager.py to create a javascript file that loads the file. This is what we do to load our python packages.

**Comment by Lyoko-Jeremie** [comment]
oh my god ~  `file_packager.py` is a sooooooo ugly file. it's mix py and js.

**Comment by Lyoko-Jeremie** [comment]
and the FS api that emscritpen provide are so unstable. it work or not work no one known why and why not.

now i try to make a js wrapper to it to let it work more robustness . Robust like a Boost.Filesystem API .

**Comment by Lyoko-Jeremie** [comment]
and BTW: in dev a new polyfill, write-debug-changeCode-compile-debug-change loop are unacceptable .

after a new polyfill dev complete, we can simple pack it and load it by `micropip` like normal.

so , this API are work more for dev time.

**Comment by oneearedrabbit** [comment]
@Lyoko-Jeremie I hate to be this guy (I'm not even a modarator), but this tone is merely acceptable. This is an open source project. You don't like it -- you contribute. While I feel that you're disappointed please be constructive, i.e. identify a problem and suggest improvements.

**Comment by hoodmane** [comment]
There's a lot of room for improvement for sure. One thing you can do is upload every change to your package to pypi as a new minor version. With twine this can be completely automated, and gives a pretty quick update cycle.

**Comment by Lyoko-Jeremie** [comment]
@oneearedrabbit Oh, i'm very sorry for my words and deeds .  I sincerely apologize to you ~~

---

I'm only try to do my best on what i can do. 

now i dont known how to compile the C++/Python Code to WASM.  
In more detail , thanks to the @hoodmane say , now i can do for this project is that , use this project in a real production and find more and more issue to help it grow .

i known the `Rome was not built in a day` , so , now i'm do my hard work on this project , like learn how the WASM FS is work, how the WASM compile is work, and find more issue on this to help later people .

now this project have small document (sorry i think it dont have aa real ducument).
i hope if some one later using this project , who can simple search on google or on the issue area , then he can find the trap now i step into, and where is the way he can climb out of the trap .

---

the same thing i do on many open source project, include the [Angular #16047](https://github.com/angular/angular/issues/16047) issue that no more than 10 people are face in the world .

some times i can help contribute it, some times i dont known how to do it, but i will try to make some hack way to bypass the trap, some times i only can make a issue , but i dont have any ability to fix it, so, the best i can do is make a issue and hope soome other HERO can Complete it .

---

**I hope everyone in the world can realize that others may not be as good as themselves.**

**Comment by Lyoko-Jeremie** [comment]
in just 5 hours, i write follow 3 function to replace the WAMS.FS 's function .

the `accessPath` function can access a path , the similar funtion i not find in the WAMS.FS .

the `mkdir` function can recursion create dir , and will not throw a unreadable error like the `WAMS.FS.mkdir` work .


```ts

type FileNodeType = { contents: { [key: string]: any } };
const normalPath = async (p: string) => {
    let _p = p.replace(/[\\/]/, '/');
    if (_p.length > 1 && _p.endsWith('/')) {
        _p = _p.substr(0, _p.length - 1);
    }
    return _p;
};
const accessPath = async (FS: any, p: string): Promise<undefined | [FileNodeType, string]> => {
    if (p === '') {
        return undefined;
    }
    let pl = p.split(/[\\/]/);
    if (pl[0] === '') {
        pl.shift();
    }
    pl = pl.filter(T => T !== '');
    if (pl.length > 0) {
        const ra = (d: FileNodeType, pl: string[], pn: string): undefined | [FileNodeType, string] => {
            if (!d || !d.contents) {
                return undefined;
            }
            if (pl.length === 0) {
                return [d, pn];
            }
            const dd = d.contents[pl[0]];
            const pd = pl.shift();
            return ra(dd, pl, pn + '/' + pd);
        };
        if (FS && FS.root) {
            if (p === '/' || p === '\\') {
                return [FS.root, '/'];
            }
            return ra(FS.root, pl, '');
        }
    }
    return [FS || FS.root, '/'];
};
const mkdir = async (FS: any, p: string, mode?: number): Promise<undefined | FileNodeType> => {
    if (p === '') {
        return undefined;
    }
    const _p = await normalPath(p);
    const testP = await accessPath(FS, _p);
    if (testP && testP[1] === _p) {
        return testP[0];
    }
    let pl = p.split(/[\\/]/);
    pl = pl.filter(T => T !== '');

    let ppp = '';
    for (let i = 0; i !== pl.length; ++i) {
        const p = pl[i];
        ppp = ppp + '/' + p;
        const n = await accessPath(FS, ppp);
        if (!n || !n[0]) {
            // console.log(FS.mkdir(ppp, mode));
            FS.mkdir(ppp, mode);
        }
    }
    const n = await accessPath(FS, p);
    if (!n || !n[0]) {
        return undefined;
    }
    return n[0];
};

```

_all the async/await key word can be remove._

**Comment by Lyoko-Jeremie** [comment]
i use follow code to add a file into the WASM.FS, seems like not work.

![2021-01-06 16_35_03-Window](https://user-images.githubusercontent.com/6566869/103747143-2cd02e00-503d-11eb-90f0-ad7964bda8ab.png)

and i can see the `contents` type not same as other, and all the data are `0` .

```ts


                    const s = FS.open('/lib/python3.8/site-packages/zzzzz/__index__.py', 'w+');
                    const stringS = `

print ('hello world zzzzz')

def loadImports(list: typing.List[str]):
    pass


def printString():
    print ('hello world zzzzz')
    pass

`;
                    const str2ab = (str: string) => {
                        var buf = new ArrayBuffer(str.length * 2); // 2 bytes for each char
                        var bufView = new Uint16Array(buf);
                        for (var i = 0, strLen = str.length; i < strLen; i++) {
                            bufView[i] = str.charCodeAt(i);
                        }
                        return buf;
                    };
                    const ua = str2ab(stringS);
                    FS.write(s, ua, 0, ua.byteLength);
                    FS.close(s);


```


the result:

![2021-01-06 16_32_42-Window](https://user-images.githubusercontent.com/6566869/103746937-d662ef80-503c-11eb-9836-71d1aceb00d2.png)

other normal file:

![2021-01-06 16_33_32-Window](https://user-images.githubusercontent.com/6566869/103747045-feeae980-503c-11eb-834b-1c7d3f900d43.png)


where am i wrong ?

**Comment by hoodmane** [comment]
Closed, insufficient interest in implementing this for now. If you want to do this, you can always use Python file IO.
