### ISSUE TITLE
It's hard to figure out where things are defined

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1079]
Currently any function on `pyodide_js` can be defined either in `pyodide.js` or in any of the `*_init` functions in `core`, or it could be a python function wrapped in a pyproxy and copied in either of the above places onto `pyodide`.

Similarly, functions on `pyodide_py` can be defined either in `pyodide` or in `core` or can be wrappers of `js` functions.

I don't think this is difficult to fix.

**Comment by rth** [comment]
More work could always be done on this, but I think you improved the situation considerably.
