### ISSUE TITLE
build/script with library=False should not additionally run setup.py install

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1086]
I think that if `build/script` is provided with `library=False`, it should not additionally run `setup.py install` internally. So that when we address #819,
```
build:
   script:
       python setup.py install
```
would be more or less equivalent to the current default build. Otherwise this would run setup twice. I misunderstood what https://github.com/iodide-project/pyodide/pull/1070 does.

Though this allows for https://github.com/iodide-project/pyodide/pull/1076 to work, so maybe we don't need to address it right now.

**Comment by ryanking13** [comment]
Closing as resolved.
