### ISSUE TITLE
Support for kwargs between python and js

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1122]
We should support using kwargs to call python functions from javascript and vice-versa. This would have made #1121 obvious.

**Comment by hoodmane** [comment]
See also: #261

**Comment by rth** [comment]
Should we close this one, are there remaining points?

**Comment by hoodmane** [comment]
We still don't support using key word arguments when calling Python from Javascript. I think what we should do is add a method to `PyProxy`:
```js
pyfunc.callKwargs(arg1, arg2, {kwarg1 : val1, kwarg2 : val2})
```
