### ISSUE TITLE
attempting to construct out-of-bounds TypedArray on ArrayBuffer

### ISSUE THREAD

**Issue by JackChen20200818** [pyodide/pyodide#1134]
Hello everyone, I've recently found a problem when converting python numpy ndarray to JS. After runPython with :

>   pyodide.runPython(`
>       arr=np.arange(1920*1080*3)
>   `);

on the JS side, I loaded the "arr" from python:

>   let arr = pyodide.pyimport('arr');

and I got the following error in Firefox browser console:

> Uncaught (in promise) RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer
> _hiwire_int32array https://localhost/wasm/pyodide.asm.js:8
>     __pyimport https://localhost/wasm/pyodide.asm.js:8
>     pyimport https://localhost/wasm/pyodide.asm.js:8
>     <anonymous> http://localhost:7000/:57
>     promise callback* http://localhost:7000/:23
>     promise callback* http://localhost:7000/:21

（The pyodide version is v0.16.1 ）Any suggestions or hints are appretiated.

**Comment by hoodmane** [comment]
Thanks for the report! I will investigate. (Would you mind editing your post to use markdown code blocks?)

**Comment by hoodmane** [comment]
Well this behaves differently in the master version `https://pyodide-cdn2.iodide.io/dev/full/console.html` than in the `https://pyodide-cdn2.iodide.io/0.16.1full/console.html`. In `0.16.1` it immediately throws that error. In the master version, after a very long time it copies all 25 megabytes of data into a new `Array`. Probably not what you wanted either.

**Comment by hoodmane** [comment]
In this case because the array is 1d pyodide should be able to just use `HEAP32.slice(addr_of_buffer/4, addr_of_buffer/4 + 1920*1080*3)` which would be very fast. You can see how this would go with the following hack:
```javascript
await pyodide.runPythonAsync(`import numpy as np; arr=np.arange(1920*1080*3)`);
search_num = 6132423;
addr_of_buffer = pyodide._module.HEAP32.findIndex(x => x===search_num) - search_num;
buffer = pyodide._module.HEAP32.slice(addr_of_buffer, addr_of_buffer + 1920*1080*3)
pyodide.runPython("arr[0] = 7; arr[1] = 8; arr[2] = 9");
buffer2 = pyodide._module.HEAP32.slice(addr_of_buffer, addr_of_buffer + 1920*1080*3)
buffer[0] // 0
buffer2[0] // 7
```

Pyodide could also just return a `pyproxy` object.

**Comment by hoodmane** [comment]
Currently it looks like the conversion code will work correctly if you could make a 2d array that is `1 x 1920*1080*3`.

**Comment by hoodmane** [comment]
Nope that still doesn't work:
```
pyodide.runPython("arr = np.ones([1,1920*1080*3])");
res = pyodide.pyimport("arr");
```
shows exactly the same behavior as your original example...

**Comment by JackChen20200818** [comment]
> In this case because the array is 1d pyodide should be able to just use `HEAP32.subarray(addr_of_buffer/4, addr_of_buffer/4 + 1920*1080*3)` which would be very fast. You can see how this would go with the following hack:
> 
> ```js
> await pyodide.runPythonAsync(`import numpy as np; arr=np.arange(1920*1080*3)`);
> search_num = 6132423;
> addr_of_buffer = pyodide._module.HEAP32.findIndex(x => x===search_num) - search_num;
> buffer = pyodide._module.HEAP32.subarray(addr_of_buffer, addr_of_buffer + 1920*1080*3)
> buffer[0] // ==> 0
> pyodide.runPython("arr[0] = 7; arr[1] = 8; arr[2] = 9");
> buffer2[0] // ==> 7
> ```
> 
> Pyodide could also just return a `pyproxy` object.

Thanks for your comments but I wonder what's the meaning of maigc number 6132423? Is there any documents on the usage of pyproxy, and on how to calculate the address of a numpy n-dim array?

**Comment by hoodmane** [comment]
To be clear the code I wrote there is sort of a crazy hack: the array contains all numbers in the range from 0 to 6220800. What this code does is it scans across the wasm heap until it finds an instance of the number `6132423` which is chosen to be both big, less than `6220800` and not particularly special. This is in hopes that it does not occur somewhere in the wasm heap before the array we're looking for. Once we find that number, then we assume that we're in the range and that `0` was `6132423` positions ago.

**Comment by rth** [comment]
The initial example no longer fails,
```
pyodide.runPython(arr=np.arange(1920*1080*3));
let x = pyodide.globals.get('arr');
```
and appears to work as expected. Also see https://pyodide.org/en/latest/usage/api/js-api.html#PyProxy.getBuffer
