### ISSUE TITLE
Is impossible to convert py file to wasm file?

### ISSUE THREAD

**Issue by HuangHai1997** [pyodide/pyodide#1182]
# This is my example file:

    def test_func(x: int, y: int) -> int:
        import pandas as pd
        s = pd.Series([1, x, 3, y, 5])
        print(s)
        return x * y
    test_func(10,20)

I used cython to convert that to .c file. With help of gcc/clang, it works.
But if i change gcc/clang to emcc, it does not work.
So how can I convert my py file to a pure wasm file?
Thanks a lot.

**Comment by rth** [comment]
> I used cython to convert that to .c file. With help of gcc/clang, it works.

You can convert your .py file to .c files and a compiled module, but it will still not be standalone and require the Python interpreter to run (since you use pandas and generally Python objects).

> So how can I convert my py file to a pure wasm file?

Identically, you can take your py file compile it with Cython to produce a .c and then compile that with emscripten which will produce a wasm file. This can be done for instance as part of the pyodide build system, if you [add a new package to pyodide](https://pyodide.readthedocs.io/en/latest/development/new-packages.html). This will similarly require  the Python interpreter to run, which in this case is included in pyodide.

**Comment by HuangHai1997** [comment]
> > I used cython to convert that to .c file. With help of gcc/clang, it works.
> 
> You can convert your .py file to .c files and a compiled module, but it will still not be standalone and require the Python interpreter to run (since you use pandas and generally Python objects).
> 
> > So how can I convert my py file to a pure wasm file?
> 
> Identically, you can take your py file compile it with Cython to produce a .c and then compile that with emscripten which will produce a wasm file. This can be done for instance as part of the pyodide build system, if you [add a new package to pyodide](https://pyodide.readthedocs.io/en/latest/development/new-packages.html). This will similarly require the Python interpreter to run, which in this case is included in pyodide.

Thanks. I convert my .py file to .wasm successfully.But I wanna to use it within non-browser environment.
I can’t run it either wasmer-python or the wasmtime-py within sandbox.

```
error: failed to run `a.wasm`
╰─> 1: Error while importing "env"."PyModuleDef_Init": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })
```

**Comment by ehfd** [comment]
#916
This repository is meant to supply a Python and Cython interpreter that runs inside the browser independently. I am going to experiment with Cython and add some docs on how people can protect .py code using Cython before this month finishes.

Wasmer is meant to import .wasm packages as an extension into Python.

To answer your question, there is no feasible way in Python to compile everything into a portable .wasm package, nor Python was ever meant to do this. Nuitka is a well-known compiler for Python files but even they have an incomplete feature set. PyInstaller and PyOxidizer simply packs a Python interpreter and source code. If you really need to compile your code to .wasm, check other compiled languages.

**Comment by hoodmane** [comment]
Closed as answered by @ehfd.
