### ISSUE TITLE
Performance issues in buffer conversions from javascript to python 

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1203]
since in my case from time to time in python I have to aquire arrays returned from JS methods,  i.e.,  a huge image array returned by some method of opencv.js which is now lacked in python packages.  The cost of automatic copying the array data from JavaScript to Python is too much, and can't be beared in some realtime computation cases.

_Originally posted by @daoxian in https://github.com/iodide-project/pyodide/issues/1192#issuecomment-774496411_

**Comment by hoodmane** [comment]
@daoxian If you wouldn't you mind posting a small code example, it would be helpful.

**Comment by daoxian** [comment]
> @daoxian If you wouldn't you mind posting a small code example, it would be helpful.

Sure. 

In python, I want to resize a image in opencv. Currently no opencv present in pyodide package , so I have to call opencv.js which residents in JS:

>             print(im_patch.size, im_patch.shape)  # m_patch is an numpy ndarray stands for an image
>             im_patch_bytes = im_patch.tobytes()   # conver to bytes in order to avoid mem copy when converting to JS arg of resize_img()
>             scaled_img_raw = js.g_tracker.resize_img(im_patch_bytes, (im_patch.shape[0], im_patch.shape[1]), (model_sz, model_sz))
>             im_patch = np.asarray(scaled_img_raw, dtype=np.uint8).reshape(model_sz, model_sz, 3)


In  JavaScript class method:
>   resize_img (img_bytes /* auto converted to Uint8ClampedArray already */, from_shape, to_shape) {
>     const img=cv.matFromArray(from_shape[0], from_shape[1], cv.CV_8UC3, img_bytes);    
>     const scaledImg = new cv.Mat();
>     cv.resize(img, scaledImg, new cv.Size(to_shape[1], to_shape[0]), 0, 0, cv.INTER_NEAREST);
>     return new Uint8ClampedArray(scaledImg.data); 
>   }

As to why I don't use Pillow to resize an image is due to its poor performance.

**Comment by daoxian** [comment]
The case is that I'll migrate an `Object Tracking Algorithm` written in python to JavaScript so as to run it in the browser. It's a realtime tracking algorithm. With the input of a streaming of images, it should process every image and run as fast as possible.

**Comment by hoodmane** [comment]
Thanks! This is a very interesting example.

In your particular use case there is a way to fix the performance. I think roughly the following should work:
```javascript
function alloc_matrix_3d(shape0, shape1, shape2){
   let num_bytes = shape0*shape1*shape2;
   let ptr = pyodide._module._SDL_malloc(num_bytes);
   let bytes = pyodie._module.HEAP8.subarray(ptr, ptr + num_bytes);
   return [ptr, cv.matFromArray(from_shape[0], from_shape[1], cv.CV_8UC3, bytes)];
}

function free_ptr(ptr){
   pyodide._module._SDL_free(ptr);
}

function resize_img (img_bytes /* auto converted to Uint8ClampedArray already */, from_shape, to_shape) {
   const img=cv.matFromArray(from_shape[0], from_shape[1], cv.CV_8UC3, img_bytes);
   const [ptr, scaledImg] = alloc_matrix_3d(to_shape[1], to_shape[0], cv.CV_8UC3);
   // Somehow you need to remember to free_ptr later, otherwise you'll leak this memory
   cv.resize(img, scaledImg, new cv.Size(to_shape[1], to_shape[0]), 0, 0, cv.INTER_NEAREST);
   return new Uint8ClampedArray(scaledImg.data);
}
```

**Comment by hoodmane** [comment]
The performance issue happens in the following code starting on [jsproxy.c line 173](https://github.com/iodide-project/pyodide/blob/master/src/core/jsproxy.c#L713):

```C
static int
JsBuffer_GetBuffer(PyObject* obj, Py_buffer* view, int flags)
{
  bool success = false;
  JsBuffer* self = (JsBuffer*)obj;
  view->obj = NULL;

  void* ptr;
  if (hiwire_is_on_wasm_heap(JsProxy_REF(self))) {
    // This is fast (no copy)
    ptr = (void*)hiwire_get_byteOffset(JsProxy_REF(self));
  } else {
    // Copy the data onto wasm_heap =(
    ptr = PyBytes_AsString(self->bytes);
    FAIL_IF_NULL(ptr);
    hiwire_copy_to_ptr(JsProxy_REF(self), ptr);
  }
```
So the trick is to pass an object that `is_on_wasm_heap` already.

**Comment by daoxian** [comment]
> Thanks! This is a very interesting example.
> 
> In your particular use case there is a way to fix the performance. I think roughly the following should work:
> 
> ```js
> function alloc_matrix_3d(shape0, shape1, shape2){
>    let num_bytes = shape0*shape1*shape2;
>    let ptr = pyodide._module._PyMem_Malloc(num_bytes);
>    let bytes = pyodie._module.HEAP8.subarray(ptr, ptr + num_bytes);
>    return [ptr, cv.matFromArray(from_shape[0], from_shape[1], cv.CV_8UC3, bytes)];
> }
> 
> function free_ptr(ptr){
>    pyodide._module._PyMem_Free(ptr);
> }
> 
> function resize_img (img_bytes /* auto converted to Uint8ClampedArray already */, from_shape, to_shape) {
>    const img=cv.matFromArray(from_shape[0], from_shape[1], cv.CV_8UC3, img_bytes);
>    // Somehow you need to remember to free_ptr later, otherwise you'll leak this memory
>    const [ptr, scaledImg] = alloc_matrix_3d(to_shape[1], to_shape[0], cv.CV_8UC3);
>    cv.resize(img, scaledImg, new cv.Size(to_shape[1], to_shape[0]), 0, 0, cv.INTER_NEAREST);
>    return new Uint8ClampedArray(scaledImg.data);
> }
> ```

It looks so amazing!  I'll check it out, thanks!

**Comment by hoodmane** [comment]
I think we should make a public API to allocate / free on the pyodide heap. This is not the only performance issue in buffer conversions, but at least in this case where you are already explicitly allocating the memory it's really unfortunate to allocate it in the wrong place and then perform an extra copy because there's no API to allocate in the right place.

Thanks a lot for your reports, these conversations are very helpful. Is your code publicly available somewhere? I'd be interested to look at it.

**Comment by daoxian** [comment]
> Thanks a lot for your reports, these conversations are very helpful. Is your code publicly available somewhere? I'd be interested to look at it.

The original python codes are taken from here:  [https://github.com/STVIR/pysot/blob/2f98bfb6f7b56e4a4263c7024a3a3a7143d630ac/pysot/tracker/base_tracker.py#L88]

while the JS codes are not yet permitted to be published.

It's late night, I'll contact you in the daytime.
