### ISSUE TITLE
Migrate pyodide to a separate GitHub organization

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1217]
Following  the discussion with @wlach @mdboom @bcolloran a few months ago it might be a good idea to move pyodide to a separate Github organization. There is now a fairly active group of pyodide contributors and users which is hopeful for the project sustainability.  In some of the blogs or comments I saw online there is still some confusion about the interaction between pyodide and iodide. 

Next release is going to be [quite large](https://github.com/iodide-project/pyodide/blob/master/docs/project/changelog.md) and among other things will include a simple webloop for asyncio https://github.com/iodide-project/pyodide/pull/1158  and  updates to the latest version of emscripten with the upstream LLVM backend (https://github.com/iodide-project/pyodide/pull/1102) which also fixed number of scipy related issues (starting from its size https://github.com/iodide-project/pyodide/issues/240#issuecomment-775384365).  So this might be a good time for this migration.

Below is the proposed plan for the migration. Please comment if you have any suggestions or concerns.

### Before the migration

- [x] create a pyodide core team at https://github.com/pyodide
- [x] formalize the project governance on how decisions are taken for accepting PRs and approving new maintainers. https://github.com/iodide-project/pyodide/pull/1229
- [x] expand a bit the project history in https://pyodide.readthedocs.io/en/latest/project/about.html  https://github.com/iodide-project/pyodide/pull/1342
- [x] get admin rights for the readthedocs account https://readthedocs.org/projects/pyodide/ . @mdboom could you please add me (`rth`) and I'll add other maintainers.

### The migration

 - [x] move the pyodide repo to https://github.com/pyodide

### After the migration

 - [x] Change all links in the documentation
 - [ ] for the next release push docker images to https://hub.docker.com/orgs/pyodide
 - [x] this might also be a good occasion to switch the documentation to https://pyodide.org ~~(or some similar subdomain)~~. We have that domain. https://github.com/iodide-project/pyodide/issues/1243
 - [ ] (non critical) Ideally, we would also need some other solution for serving HTML files and in particular `console.html` which cannot be served by JsDelivr. `https://pyodide-cdn2.iodide.io` needs to be working for backward compatibility and as it's used by iodide, but maybe we could just serve console.html with Github pages in the future. https://github.com/pyodide/pyodide/issues/1380
 - [ ] write an announcement post

cc @dalcde @phorward @hoodmane  @casatir

**Comment by wlach** [comment]
Big 👍 from me on this.

**Comment by mdboom** [comment]
:+1: from me as well.  Just added you as an admin to the RTD project.

**Comment by casatir** [comment]
Thanks @rth to formalize this.

> there is still some confusion about the interaction between pyodide and iodide

Totally agree. It will clarify the fact that Pyodide will continue on its own and is actively maintained.

> but maybe we could just serve console.html with Github pages in the future.

+1 for this.

**Comment by dalcde** [comment]
How will this affect our CI quotas?

**Comment by rth** [comment]
> How will this affect our CI quotas?

That's a very good question. There are several scenarios there.

**Scenario 1**

We switch to the default CirleCI OSS plan which offers 400k credits per month (~ 670 CI hours / month with the default Medium Linux container). Given that 1 CI runs takes <1.5  hours in total that would correspond to 15 CI runs per day for both PRs and master. I think we are below that currently?

However, the issue there is that we will only get 4 parallel jobs (while we have access to 200 currently). This might be mitigated somewhat by enabling CircleCI on forks as you are currently doing, I guess, but it's not ideal.

**Scenario 2**

If it's possible that we continue benefiting from the current "mozilla’s Custom Performance plan" for CircleCI under the new org, while acknowledging Mozilla's support in some way. 

@mdboom @wlach Do you think this is something that might be possible?

The only limitation currently is that we are still limited to Medium Linux containers with 2CPU while a number of CI jobs (tests with pytest-xdist, to some extent package building) scales quite well with the number of CPU, so having for instance 4CPU containers would make parts of the CI almost twice faster at similar CircleCI credits cost.

**Scenario 3**

If 2 doesn't work, we could still apply to get more resources/parallel jobs with CircleCI from https://circleci.com/pricing/

> If you are building a bigger open source project and would like the flexibility of our new plans, [let us know](https://circleci.com/talk-to-us/?source-button=Request%20early%20access%20-%20Open%20Source%20usage%20plan) how we can help you! 

Or alternatively try to shift some of the load to other CI providers, though personally I prefer CircleCI pipelines design to Azure Pipelines or GH Actions for instance.

**Comment by daoxian** [comment]
Agree! Hope we'll have a clean new version, including fine-tuned memory management (don't copy between Python &n JS unless necessary, ways to avoid memory leaking,... etc) and clear documents.

**Comment by phorward** [comment]
I'm sure this will boost Pyodide to new dimensions! Big :+1: from me as well!
Thanks @rth for all your efforts in making this happen.

**Comment by phorward** [comment]
Should we only enable for "Squash merge" in the new repository? 
![image](https://user-images.githubusercontent.com/16870072/108000370-090fe880-6fea-11eb-8ea2-14cd79b07d1e.png)

**Comment by rth** [comment]
> Should we only enable for "Squash merge" in the new repository?

Good idea, settings changed. It's going to be this same repo that's moved there.

**Comment by rth** [comment]
Closing as resolved. The remaining points have dedicated issues that would done for the 0.17 release.
