### ISSUE TITLE
Creating python packages in js

### ISSUE THREAD

**Issue by sanatankc** [pyodide/pyodide#1220]
Forgive me if this seems too trivial however I couldn't find how to do this. Given that pyodide can access js interface, this seems possible but I can't seem to figure out how to do this.

Basically all I want to do this is write a module name suppose 'A' in Javascript and I should  be able to import it from python like this 'import A'. Is this possible?

**Comment by hoodmane** [comment]
This functionality is available in the development version (but not in the most recent release):
https://pyodide.readthedocs.io/en/latest/usage/api-reference.html#pyodide.registerJsModule
