### ISSUE TITLE
Soundness issues in buffer conversions code

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1221]
Currently if one converts a 1d ndarray from Python ==> javascript, `_python2js_shareable_buffer_recursive` produces a `TypedArray` object that shares memory with the `ndarray` but without associating the lifetime of the `TypedArray` with the backing memory in any way, so the memory is borrowed. If the Python object is later garbage collected, then the memory backing this `TypedArray` will be freed, but without any warning to someone who stored the `TypedArray`. The memory may then be reallocated to something else, potentially leading to memory corruption. If the `TypedArray` is reimported into Python it yields a Python `memoryview` which also points to the same borrowed memory.

I think the only reason this doesn't happen more often is that we leak a lot of memory and people don't use the buffer conversions that much.

I think in the case that the user attempts to import a `TypedArray` on the Wasm heap into python, we should actually throw an error because that memory has been malloc'd and it may eventually be freed but we have no way of knowing when it is freed. I think we need some extra Javascript type which is a `TypedArray` referencing owned memory with a `release` method to let go of the memory when it is done. If the memory has a static lifetime then the `release` method can be a no-op. Then this pair `(TypedArray, release)` can be safely imported into Python as a Buffer with a `bf_release` implementation that calls the `release` function. 

This obviously will require a more carefully designed API, but the current system simply does not work.

See PR #1215 which partially addresses this. @daoxian

**Comment by hoodmane** [comment]
Example:
```python
pyodide.runPython("x = b'123'");
a = pyodide.pyimport("x"); // a ==> Uint8ClampedArray(3) [49, 50, 51]
pyodide.runPython("del x");
a // ==> Uint8ClampedArray(3) [64, 0, 0]
```

**Comment by daoxian** [comment]
Roger that and thanks a lot.

**Comment by daoxian** [comment]
Some extra comments: In most cases this API (pyodide.getRawBuffer) works well.  When an numpy ndarray is NOT contingious after some complicated ops, the raw buffer may possibly become  unrecognizable by `cv.matFromArray()`, which will cause a "array is too long" exception.  The resolution is to make the numpy ndarray contingious again by `numpy.ascontingiousarray()`  before passing it as a argument to that opencv method.  And another not-so-efficient way is to convert it into bytes before passing into JS.  However, the issue has nothing to do with the  API.

**Comment by hoodmane** [comment]
For instance if you say: `myslice = myarray[::2]`, does `cv.matFromArray` have a problem with it already?

**Comment by daoxian** [comment]
> For instance if you say: `myslice = myarray[::2]`, does `cv.matFromArray` have a problem with it already?

No, after your above op, myslice.flags.C_CONTIGUOUS is still True.

My case is:
```
import numpy as np
a=np.ones(6220800, dtype=np.uint8).reshape(1080,1920,3)
b=a[100:300, 500:800, :]
print(b.flags, b.shape, b.strides)
c=np.ascontiguousarray(b)
print(c.flags, c.shape, c.strides)
```
b is not contiguous and b.strides[0] is not the expected 1*3*300, but a wierd 5760.
After ascontiguousarray,  c is now a normal ndarray.
In JS, if we pass b.buffer to cv.matFromArray, an exception will be thrown.

**Comment by daoxian** [comment]
> For instance if you say: `myslice = myarray[::2]`, does `cv.matFromArray` have a problem with it already?

after your above op, the flags.c_contiguous is still True though the strides changed.  In this case, cv.matFromArray will be successful if we don't care about the underlying data.

**Comment by daoxian** [comment]
@hoodmane  Is  the getRawBuffer() API in Chrome browser any different from that in Firefox? I found a performance lag in Chrome.   In Firefox it takes 1ms to run the API, but 10~50 ms in Chome. 

python the caller:  
`            
            scaled_img_raw = js.g_tracker.resize_img(im_patch, (model_sz, model_sz))
`
JS the callee:
`
  resize_img (img_pyproxy, to_shape) {
    console.log('img_pyproxy=', img_pyproxy, to_shape);
    const {buffer, shape, strides, release} = img_pyproxy.getRawBuffer('u8');
    console.log('get raw buffer ok');
    const img = cv.matFromArray(shape[0], shape[1], cv.CV_8UC3, buffer);   
    const scaledImg = new cv.Mat();
    cv.resize(img, scaledImg, new cv.Size(to_shape[1], to_shape[0]), 0, 0, cv.INTER_NEAREST);
    img_pyproxy.destroy();
    release();
    return new Uint8ClampedArray(scaledImg.data);
  }
`

Sample output for Firefox:
```

19:19:51.232 img_pyproxy= Proxy { <target>: target(), <handler>: {…} } Array [ 287, 287 ]
19:19:51.233 get raw buffer ok
```

Sample output for Chrome:
```
19:25:01.462 img_pyproxy= Proxy {$$: {…}, toString: ƒ, destroy: ƒ, apply: ƒ, shallowCopyToJavascript: ƒ, …} (2) [287, 287]
19:25:01.488 get raw buffer ok
```

**Comment by hoodmane** [comment]
> after your above op, the flags.c_contiguous is still True though the strides changed. 

No it's not:

```python
>>> a = np.arange(24).reshape([8,3])
>>> b =a[::2]
>>> av = memoryview(a)
>>> bv = memoryview(b)
>>> av.c_contiguous 
True
>>> bv.c_contiguous 
False
```

The definition of `_IsCContiguous` in `cpython/Objects/abstract.c` is:

```C
    sd = view->itemsize;
    for (i=view->ndim-1; i>=0; i--) {
        dim = view->shape[i];
        if (dim > 1 && view->strides[i] != sd) {
            return 0;
        }
        sd *= dim;
    }
    return 1;
```

**Comment by hoodmane** [comment]
>  Is the getRawBuffer() API in Chrome browser any different from that in Firefox? I found a performance lag in Chrome. In Firefox it takes 1ms to run the API, but 10~50 ms in Chome.

No clue why you're seeing this. Will try to reproduce.

**Comment by daoxian** [comment]
> > after your above op, the flags.c_contiguous is still True though the strides changed.
> 
> No it's not:
> 
> ```python
> >>> a = np.arange(24).reshape([8,3])
> >>> b =a[::2]
> >>> av = memoryview(a)
> >>> bv = memoryview(b)
> >>> av.c_contiguous 
> True
> >>> bv.c_contiguous 
> False
> ```
> 
> The definition of `_IsCContiguous` in `cpython/Objects/abstract.c` is:
> 
> ```c
>     sd = view->itemsize;
>     for (i=view->ndim-1; i>=0; i--) {
>         dim = view->shape[i];
>         if (dim > 1 && view->strides[i] != sd) {
>             return 0;
>         }
>         sd *= dim;
>     }
>     return 1;
> ```

It's not definite, try this:
```
d=np.arange(30, dtype=np.uint8).reshape(2,5,3)
b=a[::2]

```

**Comment by daoxian** [comment]
> > Is the getRawBuffer() API in Chrome browser any different from that in Firefox? I found a performance lag in Chrome. In Firefox it takes 1ms to run the API, but 10~50 ms in Chome.
> 
> No clue why you're seeing this. Will try to reproduce.

Thanks.
Chrome ver: 88.0.4324.150
FireFox ver:  85.0.2

**Comment by daoxian** [comment]
> > Is the getRawBuffer() API in Chrome browser any different from that in Firefox? I found a performance lag in Chrome. In Firefox it takes 1ms to run the API, but 10~50 ms in Chome.
> 
> No clue why you're seeing this. Will try to reproduce.

Have you reproduced the issue yet?

**Comment by daoxian** [comment]
@hoodmane I found a bug in you proxy-buffer-procs branch:  
src/core/pyproxy.c, line 667:

>   if(window.BigInt64Array)

will break the web worker's rule (cannot access window in web worker) and throws exception. You could fix it before PR merge.

**Comment by hoodmane** [comment]
@daoxian Thanks for pointing this out. Could you put comments about improvements to specific PRs on the PR you're talking about?

It should say 
```javascript
if(globalThis.BigInt64Array)
```
