### ISSUE TITLE
Include plotly in pyodide

### ISSUE THREAD

**Issue by dmondev** [pyodide/pyodide#1267]
This is an issue to suggest adding plotly to your list of python packages included in the default pyodide distribution.

Thanks,

**Comment by rth** [comment]
Plotly is a pure python package, so you should be able to [install it with micropip](https://pyodide.readthedocs.io/en/latest/usage/loading-packages.html#micropip).

**Comment by dmondev** [comment]
Hi @rth , thanks for the quick response, and sorry I didn't put enough detail in my request.

The reason why I would like to have plotly included by default in pyodide is because I'm planning to deploy it in a restricted environment, where I won't be able to use micropip.

I'm tried to generate "my own distribution" of pyodide by building from source, but encountered a couple of issues due to the following packages being downloaded from ftp (Again, restrictions on my environment).

```
libxml2
bzip2
```
I ended up changing the make files for libxml2 and cpython to replace those with http:// versions, and was at least able to run a make with only plotly, by using
```
PYODIDE_PACKAGES="plotly"
```

I'm going to try simply adding the generated package to a released version from pyodide to see if it works.

**Comment by dmondev** [comment]
This worked for me, although I had to manually update the package.json to include plotly and dependencies.

> Hi @rth , thanks for the quick response, and sorry I didn't put enough detail in my request.
> 
> The reason why I would like to have plotly included by default in pyodide is because I'm planning to deploy it in a restricted environment, where I won't be able to use micropip.
> 
> I'm tried to generate "my own distribution" of pyodide by building from source, but encountered a couple of issues due to the following packages being downloaded from ftp (Again, restrictions on my environment).
> 
> ```
> libxml2
> bzip2
> ```
> 
> I ended up changing the make files for libxml2 and cpython to replace those with http:// versions, and was at least able to run a make with only plotly, by using
> 
> ```
> PYODIDE_PACKAGES="plotly"
> ```
> 
> I'm going to try simply adding the generated package to a released version from pyodide to see if it works.

**Comment by dalcde** [comment]
You can instruct micropip to load a .whl file from any url, not
necessarily from pypi. Would it suffice to serve the .whl file locally?

**Comment by dmondev** [comment]
> You can instruct micropip to load a .whl file from any url, not necessarily from pypi. Would it suffice to serve the .whl file locally?

Yes, but the current version doesn't support relative urls. I believe there is a fix already for that, but is not yet released.

**Comment by leopsidom** [comment]
I'm getting following error when trying to install `plotly` via `micropip.install('plotly')`:

> pyodide.asm.js:8 Uncaught (in promise) Couldn't find a pure Python 3 wheel for 'retrying >= 1.3.3'

I'm using pyodide 0.16.1. Do I need to use `0.17` to make this work ?

**Comment by rth** [comment]
No you need to ask https://github.com/rholder/retrying maintainers to upload a [wheel to PyPi](https://pypi.org/project/retrying/#files). micropip will only work with pure python wheels not `.tar.gz`. 

As a temporary workaround you can also make the wheel yourself and load it from some custom URL before loading plotly. Generally though we need to encourage maintainers to upload wheels for pure python packages.

**Comment by jmsmdy** [comment]
I've already submitted a pull request for plotly to remove the 'retrying' dependency and replace it with 'tenacity' (which has a pure python wheel). It should be available in the upcoming 4.15.0 release. https://github.com/plotly/plotly.py/pull/2911

If you cannot wait until then next release (should be soon), I also have a version here that I built a wheel for and put in the test pypi repo with the 'retrying' dependency removed:
https://test.pypi.org/project/plotly-jmsmdy/

I had issues with CORS when trying to load it directly using that url vin pyodide, but there is a workaround: 

`micropip.install('https://cors-anywhere.herokuapp.com/' + 'https://test-files.pythonhosted.org/packages/81/65/17b03a5b25a0496a6ef27cc3ecc15a8137f9e3a990518ee78b65aa8835c1/plotly_jmsmdy-4.12.1-py2.py3-none-any.whl')`

**Comment by leopsidom** [comment]
This is awesome. I'm getting this error:

> pyodide.asm.js:8 Uncaught (in promise) File is not a zip file

When running micropip install on pyodide 0.16.1. Are you using 0.17 or 0.16.1 ?

**Comment by jmsmdy** [comment]
The "File is not a zip file" warning means that micropip was not able to successfully pull the package from the remote location. You can check the Network tab of Developer Tools to see in more detail what the problem is (e.g., you have a 403 error).

I think I last used this on a 0.15.x version of pyodide. It seems to work here (which is using an older version of pyodide: https://alpha.iodide.io/notebooks/300/

`%%py

import micropip

%% py

micropip.install('https://cors-anywhere.herokuapp.com/' + 'https://test-files.pythonhosted.org/packages/81/65/17b03a5b25a0496a6ef27cc3ecc15a8137f9e3a990518ee78b65aa8835c1/plotly_jmsmdy-4.12.1-py2.py3-none-any.whl')

%%py 

import plotly`

I'm not sure what the issue is in your case, it may just be a difference in the way micropip is pulling packages, or some change in CORS policy. But if you download the wheel and install it locally, it should work fine.

**Comment by leopsidom** [comment]
Thanks, cors-anywhere app fixed the 403 corsdemo error. But getting another 400 error now.  I think it's because I'm running micropip from chrome extension, which lacks the origin header in the request:

> Missing required request header. Must specify one of: origin,x-requested-with

**Comment by dmondev** [comment]
I was able to successfully integrate plotly generating the package via bin/pyodide mkpkg.
Had to generate packages for both plotly and retrying, but it works. 
Please let me know if there's interest for this, I'd be happy to create a pull request.

**Comment by hoodmane** [comment]
Based on this thread, I would say that there is sufficient interest. I guess the main question is how soon plotly is likely to make  a new release with @jsmsmdy's PR. Perhaps we should ask about that first.

**Comment by dmondev** [comment]
I think @jmsmdy proposal is needed if we want to install plotly via micropip. 
To add plotly to the pyodide standard distribution, generating the package and dependency via bin/pyodide mkpkg works, so no wheels needed.

I'm not sure what is the policy for adding new packages to pyodide standard vs via micropip only, though. 
I'd like to understand that, I could create a separate discussion for that.

**Comment by hoodmane** [comment]
> I'm not sure what is the policy for adding new packages to pyodide standard vs via micropip only, though.

I don't know what the policy is either.

> I could create a separate discussion.

Please do.
