### ISSUE TITLE
DOCS Which packages can be loaded with "loadPackage"?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1268]
I think the docs currently don't give a very good explanation of the behavior of loadPackage. It would be good to (1) accurately explain which packages can be loaded with `loadPackage` and (2) have a name for packages that can be loaded. In `loading-packages` it says it loads:

> packages built with pyodide

> packages included in the official pyodide repository

In the API docs for `loadPackage` we say: 

> Load a package or a list of packages over the network.

"Packages built with Pyodide" is the most accurate, but none of these descriptions is particularly precise. Currently no mention of the role of `languagePluginUrl`. In fact as far as I can tell, the function of `languagePluginUrl` isn't really explained in the docs.

Anyone have any suggestions for the terminology for packages which can be loaded with `loadPackage`? It's tempting to say "installed packages" or something like that...

**Comment by rth** [comment]
Maybe, "packages built with pyodide that are available at `languagePluginUrl` location"?

**Comment by rth** [comment]
I think this was improved since, including in https://github.com/pyodide/pyodide/pull/3064
