### ISSUE TITLE
Wrong value after JS TypedArray translated into python memoryview 

### ISSUE THREAD

**Issue by daoxian** [pyodide/pyodide#1277]
I've got a problem whena JS Uint8Array passed into python  in web worker:
![image](https://user-images.githubusercontent.com/34263430/108949813-0ecb9500-76a0-11eb-9e70-52a78f0ad8b0.png)

it says "memoryvew: a bytes-like object is required, not '' ".  

The corresponing python code goes here:

>     def init(self, img, height, width, bbox, cfg_layout):
>         print('enter init...')
>         img = np.asarray(img, dtype=np.uint8).reshape(height, width, 3)

JS code does not release or set null any variable of img before call the python init() method.  This does not  alway occur. It sometimes occurs after the Chrome browser's memory occupation exceeds 5G bytes (total 64G mem in my machine).  Has anyone ever met this kind of issue before?

**Comment by hoodmane** [comment]
Code path was completely changed by #1322, so it probably doesn't happen anymore. If you have similar problems in the future please open a new issue.
