### ISSUE TITLE
pandas fails to load in Chrome

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#128]
Currently pandas package fails to load in Chrome and the [corresponding import tests are skipped](https://github.com/iodide-project/pyodide/blob/9736ef1d8ff9dc756657aa2f78753346ce26c258/test/test_common.py#L30).

(Opening an issue to track that situation)

**Comment by machow** [comment]
Hey, just wanted to follow-up on this issue. I noticed that pandas seems to work for with the (example on iodide)[https://extremely-alpha.iodide.io/notebooks/222/]. It appears it's using the most current (0.7.0) release of pyodide.

However, when I build this repo via docker, or use the tar.gz of pyodide 0.7.0 in releases I can't seem to use pandas. Any idea whether this issue has been resolved, and what my be allowing it to work on iodide, but not the zipped release?

**Comment by rth** [comment]
Closing as resolved.
