### ISSUE TITLE
Build orjson for pyodide

### ISSUE THREAD

**Issue by jmsmdy** [pyodide/pyodide#1282]
The project [orjson](https://github.com/ijl/orjson) offers significantly faster JSON encoding of objects than other Python packages (40x faster than the json package in many instances), with direct encoding of numpy arrays built in. 

It would be nice if orjson could be built for pyodide. It is written in Rust, so that may be an issue.

**Comment by dalcde** [comment]
The Rust-C interop story when compiling to webassembly isn't very good.
I've looked into this a few months ago and it go too far; iirc they use
a different C ABI.

**Comment by spicy-sauce** [comment]
What's the status with this one? Not sure if it was handled or not as I'm getting:
ValueError: Can't find a pure Python 3 wheel for 'orjson<4.0.0,>=3.8.7'.

Thanks

**Comment by hoodmane** [comment]
It's probably straight forward. I'll look into it.

What's the difference between orjson and ujson? As I understand they are both rust json libs?

**Comment by spicy-sauce** [comment]
Yes, both orjson and ujson are Rust libraries for working with JSON data, but they have some differences in terms of their features, performance, and use cases.

**Features** 
orjson is a fast JSON serialization library that focuses on providing the best performance possible, but it does not provide all the features that some other JSON libraries offer, such as support for custom serialization or deserialization behavior. On the other hand, ujson is a more feature-rich JSON library that provides options for customizing serialization and deserialization behavior, including support for custom data types, but it may not be as optimized for performance as orjson.

**Performance**
orjson is known for its extremely fast serialization and deserialization performance, making it one of the fastest JSON libraries available in Rust. It uses a combination of optimized algorithms and low-level Rust optimizations to achieve its performance. ujson also offers good performance, but it may not be as fast as orjson in some cases.

**Use cases**
orjson is primarily designed for use cases where high-performance JSON serialization and deserialization are critical, such as in performance-sensitive applications or systems that require processing large amounts of JSON data with minimal overhead. ujson, on the other hand, may be more suitable for use cases that require a balance between performance and features, and where customization of serialization and deserialization behavior is desired.

Also see:
https://pythonspeed.com/articles/faster-json-library/

**Comment by hoodmane** [comment]
Well it builds first try no problem.

**Comment by spicy-sauce** [comment]
Does it mean that you should pack it and place under packages?

**Comment by spicy-sauce** [comment]
Can you please share the current status of this one? Thanks!

**Comment by spicy-sauce** [comment]
@hoodmane, is it just adding a new package here with a corresponding `meta.yaml` file?
https://github.com/pyodide/pyodide/tree/main/packages

If so, I can try and push such a PR.

**Comment by hoodmane** [comment]
Yeah. You can use the Pyodide cli:
```
pyodide skeleton pypi orjson
```
will generate the appropriate files. Then you need to add `test_orjson.py`.

**Comment by ryanking13** [comment]
Closing as resolved via #4036
