### ISSUE TITLE
Build only micropip with default PYODIDE_PACKAGES

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1295]
Currently when a user or contributor downloads pyodide and runs make they end up with the full build which can take a while and with packages they might not need.  This situation is going to get worse as more packages are added.

I propose to,
 -  by default set `PYODIDE_PACKAGES='micropip'` so only it is built, forcing users to explicitly specify packages they need in addition.
 - add an option `PYODIDE_PACKAGES='*'` to build everything.

WDYT?

**Comment by phorward** [comment]
@rth thanks for this proposal, I totally agree with you. For most cases I'm using `make minimal` as build target.

Generally, a fellow and I are currently focusing on building a *nano*-build command for Pyodide to end up with the tiniest working Pyodide which is possible (without support for any native-code packages) but with the full JavaScript integration. We're currently at 4,4 MB for a version which is suitable for our needs. This also heavily relates to #646, and I will update there when we have a fine and solid solution.

**Comment by rth** [comment]
> We're currently at 4,4 MB for a version which is suitable for our needs. We're currently at 4,4 MB for a version which is suitable for our needs.

Great, looking forward to it :)

**Comment by hoodmane** [comment]
Once in a while when I forget to `export PYODIDE_PACKAGES="micropip"` or `make minimal` or `make debug` I come back and it's building all the packages and I have to quit and `make minimal` to get it to output `packages.json`. Would be nice to have `make minimal` by default.

I think instead of just micropip it might be a good idea to by default include the other packages used in the core test suite: pyparsing, pytz, packaging, and kiwisolver.

**Comment by rth** [comment]
I agree that the core test suite should pass with the default build. Another way to get there though is to reduce number of packages it needs, by removing the dependency on at least one or two of the current requirements. As far as I remember the only reason we need so many is to load packages that depend on one another. Maybe we could mock or do isolated unit tests for some of those.

**Comment by rth** [comment]
>  Maybe we could mock or do isolated unit tests for some of those.

Just looked into it and it doesn't look simple.

So maybe we should go with that full list as the default.

**Comment by dmondev** [comment]
Would it make sense to even split the repo, moving the packages outside of the core project, similar to what projects with plugins/extensions do ?

This could be done as well as separate npm packages, with their only lifecycle, and potentially maintainers.

```
@pyodide/numpy
@pyodide/pandas
@someotherorg/my-super-duper-package
```

**Comment by rth** [comment]
> Would it make sense to even split the repo, moving the packages outside of the core project, similar to what projects with plugins/extensions do ?

Yes, that's something that would make sense in the long term, but I think we would require significant work on our build system and it's better to discuss that in a separate issue.

**Comment by yxdragon** [comment]
@hoodmane hi, do you think It would be faster loaded if "I build with numpy" than "build only micropip then install numpy"?

**Comment by hoodmane** [comment]
I'm not sure what you mean.
