### ISSUE TITLE
Top level await in console.html

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1307]
Would be nice to have. Any thoughts @casatir?

**Comment by casatir** [comment]
Nice. It should not be too difficult if we manage to use `code_eval_async` under the hood in `console.html`. I can submit a PR in that way if you want.

**Comment by hoodmane** [comment]
Yeah that would be great. (I don't see how to do it myself.)

**Comment by hoodmane** [comment]
Closed by #1459.
