### ISSUE TITLE
Micropip doesn't add cookie in the GET request

### ISSUE THREAD

**Issue by 124bit** [pyodide/pyodide#1317]
Like "withCredentials=true" in axios. However, maybe it is not a bug but a feature request.

**Comment by 124bit** [comment]
It happened during CORSE

**Comment by rth** [comment]
Could you provide more details on your use case and what you are trying to achieve? 

We are using  [XMLHttpRequest for making get requests](https://github.com/iodide-project/pyodide/blob/958724101a9cd6a1181feadcec811f26153ff828/packages/micropip/micropip/micropip.py#L38) so I imagine setting there [`withCredentials` to `true`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) could be a solution?

We could add a `with_credentials=False` parameter to `micropip.install`. A PR would be welcome.

**Comment by 124bit** [comment]
The usecase is when you try to get whl from other domain/port and it is available just in case you are authenticated, therefore you need to pass cookies with the request.
I think the proposed solution is good.
Sorry, I can’t do PR(

**Comment by amitsaha** [comment]
I will take a stab at this

**Comment by rth** [comment]
Resolved by @amitsaha in #2458, thanks!
