### ISSUE TITLE
out of memory reloading page

### ISSUE THREAD

**Issue by ahnkle** [pyodide/pyodide#1333]
I have been playing with pyodide 16.1 in firefox 86. I have a slightly modified version of 
https://pyodide.org/en/latest/usage/quickstart.html#complete-example

after reloading a tab some number of times, i start getting out

    wasm streaming compile failed: out of memory pyodide.asm.js:8:28851
    falling back to ArrayBuffer instantiation pyodide.asm.js:8:28897
    failed to asynchronously prepare wasm: out of memory pyodide.asm.js:8:28433
    out of memory pyodide.asm.js:8:3329614
    out of memory pyodide.asm.js:8:3329624

**Comment by rth** [comment]
Yes, I have seen this as well. It looks like objects [are not garbage collected](https://stackoverflow.com/questions/11286451/browser-refresh-does-not-do-garbage-collection/11286542#11286542) when a tab is reloaded multiple times in a browser. There are also a few Firefox bugs about it (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1141242).

So far the workaround is to create a new tab (and make sure we use as little memory as possible). Not sure if there is anything else we could do about it on our side.

**Comment by dalcde** [comment]
I tend to close the tab then re-open with Ctrl-Shift-Tab.

**Comment by ahnkle** [comment]
Thats fine. Just making sure I wasn't doing something weird/unkind to pyodide.

I noticed this: https://stackoverflow.com/a/46288544/1166895 which might help when developing; forcing a garbage collect.

I will test with Chrome.

**Comment by hoodmane** [comment]
Closed as answered.
