### ISSUE TITLE
Use hypothesis in the core test suite

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1337]
I think it would make sense to use [hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html) for some tests in the core test suite, rather than writing test parametrization explicitly with pytest. Particularly things like, 
- building arbitrary nested objects for type conversion
- arbitrary string generators including edge cases with unicode etc

It's particularly helpful for checking some conservation properties: e.g. any nested object using some subset of types should be preserved after a py -> js -> py conversion. Writing a hypothesis generator for such types / objects would likely be useful to find falsifying examples.

The downside of hypothesis is that it can generate a large amount of test cases, so it should only be used with the `selenium` fixture (not `selenium_standalone`)

cc @hoodmane

**Comment by hoodmane** [comment]
Looks pretty cool!

**Comment by hoodmane** [comment]
> it can generate a large amount of test cases, so it should only be used with the `selenium` fixture 

The hypothesis docs say that the fixture is run only once per batch of generated tests:

> each fixture will run once for the whole function, not once per example

https://hypothesis.readthedocs.io/en/latest/supported.html?highlight=fixture#testing-frameworks

**Comment by rth** [comment]
We are already doing this, closing as fixed.
