### ISSUE TITLE
Error: out of executable memory in function at index iOS v13 

### ISSUE THREAD

**Issue by krmanik** [pyodide/pyodide#1361]
I have created web app from Anki which create flashcards for learning. 
Pyodide v0.16.1
http://infinyte7.github.io/image-occlusion-in-browser/pwa/index.html

https://github.com/infinyte7/image-occlusion-in-browser

Earlier I think it seems to work on all iOS v13 and above phone. But now I get following errors on iPhone 11 Pro Max v13.0 and similar errors on other iOS v13 phones.

![error](https://user-images.githubusercontent.com/12841290/111999011-85509b00-8b57-11eb-877a-c6fb30cef909.PNG)

How can I solve these issues if I custom build pyodide locally for [this](https://github.com/infinyte7/image-occlusion-in-browser) project only to avoid memory errors?

<img src="https://user-images.githubusercontent.com/12841290/111999949-74ecf000-8b58-11eb-80b5-5c8cdd940525.PNG" height=400></img>

Errors on Pyodide dev version
https://infinyte7.github.io/image-occlusion-in-browser/dev/

![dev](https://user-images.githubusercontent.com/12841290/112002490-e6c63900-8b5a-11eb-9ac7-9e5e1a41a99d.PNG)

I have created a list of  [Supported Devices](https://github.com/infinyte7/image-occlusion-in-browser/blob/master/Supported%20Devices.md) which may be helpful.

Thanks

**Comment by rth** [comment]
Regarding the pyodide 0.16.1 version see https://github.com/emscripten-core/emscripten/issues/8121 and https://github.com/emscripten-core/emscripten/issues/8121 It looks like an issue in WebKit.

For the dev version, if you click on the link in the exception can you see which line raises the exception exactly?

**Comment by infinyte7** [comment]
I clicked on the link and view this then pretty-print.

On iPhone 11 Pro v13

![12](https://user-images.githubusercontent.com/12841290/112049605-d2019980-8b8a-11eb-8941-761cc1b6f471.PNG)

pretty-print
![22](https://user-images.githubusercontent.com/12841290/112049611-d3cb5d00-8b8a-11eb-80ce-c334b552db75.PNG)

**Comment by rth** [comment]
Currently, the minimum supported version is Safari v14, and this was also for a Pyodide version from some time ago. The WASM support in Safari has been steadily improving. If you still encounter problems with iPhone please open a new issue (or comment here if it's the same error). Thanks:
