### ISSUE TITLE
CMake errors when trying to add OpenCV package

### ISSUE THREAD

**Issue by victorChekhovoy** [pyodide/pyodide#1373]
I was trying to add the OpenCV package and ran into some strange CMake errors. Here's the meta.yaml file:

![meta-yaml](https://user-images.githubusercontent.com/27730335/112564480-57629500-8da9-11eb-85c2-c75f79ec76fe.png)

When I tried building, I got an error from CMake that it couldn't properly determine the "bitness of target platform:"

![bitness](https://user-images.githubusercontent.com/27730335/112565115-7f062d00-8daa-11eb-8ede-aae52103c1c2.png)

I also tried compiling opencv from source in the same docker instance but outside of pyodide and didn't have any issues. I added the following line to /src/packages/.artifacts/lib/python/scikit-build-0.11.1-py3.8.egg/skbuild/setuptools_wrap.py. It sets the size of a void pointer to 8 bits, so that CMake doesn't have to check the value.

![setuptools](https://user-images.githubusercontent.com/27730335/112566662-6a776400-8dad-11eb-9e4f-246704b488d1.png)

This seems to have fixed the issue, but now I get another error - when CMake runs tests to determine if the system is little endian or big endian, it can't find a 16-bit unsigned integer. 

![endiad](https://user-images.githubusercontent.com/27730335/112567428-d4dcd400-8dae-11eb-8fdc-d36d72eed2e5.png)

In either case, I could compile opencv individually so there must be an error in pyodide's handling of the package. How can I fix that?

**Comment by hoodmane** [comment]
> It sets the size of a void pointer to 8 bits

WASM is 32 bit little endian. Shouldn't you tell it that a void pointer is 32 bits?

**Comment by victorChekhovoy** [comment]
> WASM is 32 bit little endian. Shouldn't you tell it that a void pointer is 32 bits?

Good point, I changed the value to 4. Unfortunately, I couldn't find how to set the endianness of the system from the command line, so CMake has to perform those tests and the error still occurs. After doing some research, I think that the TestBigEndian error is caused by an earlier error with importing numpy:

![numpy_error](https://user-images.githubusercontent.com/27730335/112694560-95ff5a80-8e50-11eb-9c02-3c8138172950.png)

This error, in turn, happens because CMake tries to use Python 2 to build opencv. Adding command line arguments that instruct it to use Python 3 and set the default python executable to a Python 3 executable doesn't work. Since none of these errors happen when I build opencv outside of pyodide, there must be some error in the way pyodide builds the packages.
