### ISSUE TITLE
Update the REPL URL to not use iodide.io

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1380]
Currently the REPL is accessible at https://pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html

As part of #1217 , we should also move away from the iodide.io domain, as that  adds to the confusion. cc @teonbrooks 

Fist we need to decide what subdomain to host it on. Maybe `repl.pyodide.org/v0.17.0a2/full/console.html` or possibly something more generic as `packages.pyodide.org` since other HTML files could be served from there in the future https://github.com/iodide-project/pyodide/issues/977 ? 

Second we need to decide how to technically implement it.
 1. We can upload those files separately to Github pages or Netlify. However this has to be done for each for each version and kept in sync with the packages deployed to S3/JsDelivr.
 2. Alternatively we could find a way to serve those files from S3 since they are already there (which was done for pyodide-cdn2.iodide.io). However the challenge there that we need to only serve .html files and not all the other assets (which should go through JsDelivr exclusively). I haven't seen of a simple solution to do that yet. I guess it could be done with some AWS Lambda functions but that would require some work/maintenance effort.

So overall maybe we should go with GH pages.  Any suggestions for the domain name?

**Comment by teonbrooks** [comment]
`repl.pyodide.org` sounds cool. it would be nice if its index.html resolves to the latest version, and that you can access previous builds with the more verbose url. just my 2c

**Comment by teonbrooks** [comment]
for me, i would think that if I were to go to `packages.pyodide.org` i would be getting an index page of all the available packages

**Comment by hoodmane** [comment]
I agree that repl.pyodide.org should point to the latest stable repl.

**Comment by rth** [comment]
In the end in https://github.com/pyodide/pyodide/pull/1445 I went with deploying console.html as part of the docs, as it already has versioned URLs and we already have a deployment mechanism there, so it was easiest to setup.

If that's merged, after the release the console would be available as https://pyodide.org/en/stable/console.html
