### ISSUE TITLE
CI issues after GH org migration

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1389]
For a discussion of CI related issues following the migration to the pyodide GH org, previously discussed in https://github.com/pyodide/pyodide/pull/1383 and in particular https://github.com/pyodide/pyodide/pull/1383#issuecomment-809187564

**Comment by rth** [comment]
Right now we only have 4 concurent jobs which leads to PRs pending CI with more than a sumultaneously updated branches/PRs.

**Comment by dalcde** [comment]
If contributors set up CircleCI on their own branches then it could help with the queuing

**Comment by hoodmane** [comment]
Is it possible you could use this page:
https://app.circleci.com/settings/plan/github/pyodide/share
to share or transfer the iodide-project plan with pyodide?

**Comment by rth** [comment]
No I don't have permissions to access that page on the previous org.

Anyway, I suspect iodide was on a paid plan, and Mozilla ends up receiving invoices for it. So we need explicit approval.

I also think queuing will get better once we fix CI issues, which at least in webworkers were symptomatic of actual issues/deadlocks as far as I can tell. Currently CI takes long, in part due to waiting for tests that time out after 30s. https://github.com/pyodide/pyodide/pull/1404 should help there.

But setting it up for our forks can indeed also help. Currently we are burning through CI credits fast,
![image](https://user-images.githubusercontent.com/630936/113346146-c30daa80-9333-11eb-8a9b-fa34361820f7.png)
(with a total of 400k credits per month). I don't even understand how we could have spent 32 CPU hours for CI in 1 day. Probably timeouts and retrying build which take forever without ccache on a new fork.

**Comment by hoodmane** [comment]
I set it up on my fork earlier today but I've already used "10,186 of 2,500 credits". It seems to be running anyways, I don't know what their policy is when you go over.

**Comment by rth** [comment]
You normally get [400k per month](https://circleci.com/open-source/) that counter is not accurate. Though I'm not sure if they sum up credits for forks somehow..

**Comment by rth** [comment]
To give an update on this, unfortunately we won't be able to get Mozilla support for CI. 

In the near term, I think it should be manageable with the 3 of us running Circle CI on forks. Currently for latest commit on master, there were still 2 test failures for Firefox packages and 4 test failures for Chrome packages. And Chrome core still occasionally fails to initialize selenium. Generally though the situation improved since this issue opened.

I feel most of the issue was from the fact that free CI seems to be a bit slower (57 min for a full build packages vs ~40min previously) and we were hitting time outs. Tests are much slower though (16min for Firefox now, vs ~6min previously) and I wonder if we are hitting some limits there. 

One part of the solution might be to also stop building everything for each commit with https://github.com/pyodide/pyodide/pull/1262 (which still needs some work) which is a waste of resources in any case. I'll try to also open a ticket with CircleCI to see if there is something we are missing.

**Comment by rth** [comment]
We now see consistent failures in both browsers,
```
FAILED test_webworker.py::runwebworker_different_package_name[chrome] - selen...
FAILED test_webworker.py::runwebworker_no_imports[chrome] - selenium.common.e...
FAILED test_webworker.py::runwebworker_micropip[chrome] - selenium.common.exc...
```
We may have introduced a regression there.

**Comment by hoodmane** [comment]
Ugh I hate it when these webworker tests have real failures, they fail so much normally that it's really hard to tell.

**Comment by hoodmane** [comment]
Opened PR #1553.

**Comment by hoodmane** [comment]
I think #1718 resolved this.

**Comment by rth** [comment]
The CI situation is still not fully satisfactory, but yes I think we can close this.
