### ISSUE TITLE
Package scikit-learn

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#139]
Opening an issue to see what would be necessary to package scikit-learn in the future.

The prerequisites are,
 - [x] (partial) packaging of scipy (cf https://github.com/iodide-project/pyodide/issues/72)
   In particular the following modules are imported,
   `scipy.{special,sparse,io,special,stats,ndimage,ndimage,optimize,interpolate}`
 - [x] package [joblib](https://joblib.readthedocs.io/en/latest/): scikit-learn vendors joblib, but it would probably be better to package it independently. Most parallel computation capability of `joblib.Parallel` will probably not be supported (as it used multiprocessing+mmap of numpy arrays, or threading), and could probably be just replaced by "dummy" function that runs with `n_jobs=1`. `joblib.Memory` would still need to be packaged though.

then 
 - [x] package scikit-learn
 - [ ] run the test suite

**Comment by mdboom** [comment]
Makes sense.  This is a pretty key package.  #72 is somewhat related to this.

**Comment by mdboom** [comment]
Also see #75 for my initial stab at Scipy, and a possible way to deal with Fortran.

**Comment by mdboom** [comment]
Of related note: porting R to webassembly will also require solving the Fortran problem...

**Comment by rth** [comment]
The test suite results for scikit-learn are available in [sklearn-test-suite.txt](https://github.com/iodide-project/pyodide/files/2555126/sklearn-test-suite.txt), it's somewhat mixed. Looks like mostly either pass or segfault due when calling some LAPACK functions. So in order or priorities we have,
 - [ ] Segfaults when calling LAPACK functions via scipy. This happens for around 90 test files / 168 which is quite a lot. This doesn't necessarily mean that the corresponding modules are unusables, but it means that at least one of the solvers in that module segfaults (typically estimators have multiple solvers). The traceback looks often like,
    ```
    get/env[prop]@http://127.0.0.1:57399/pyodide.asm.js:8:6936
    byn$fpcast-emu$_dlu_c_@http://127.0.0.1:57399/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[2086]:0x39e4cc
    _f2py_rout__flinalg_dlu_c@http://127.0.0.1:57399/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[139]:0x158cc
    byn$fpcast-emu$_f2py_rout__flinalg_dlu_c@http://127.0.0.1:57399/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[2087]:0x39e4df
    _fortran_call@http://127.0.0.1:57399/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[148]:0x18a45
    byn$fpcast-emu$_fortran_call@http://127.0.0.1:57399/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[2098]:0x39e5d2
   @http://127.0.0.1:57399/pyodide.asm.wasm:wasm-function[810]:0x106fdb
   @http://127.0.0.1:57399/pyodide.asm.wasm:wasm-function[2722]:0x280cde
   @http://127.0.0.1:57399/pyodide.asm.wasm:wasm-function[2717]:0x2794e5
   @http://127.0.0.1:57399/pyodide.asm.wasm:wasm-function[15619]:0x7125b6
   ```
   so it seems to be due to f2py and possibly some function pointer cast emulation. This needs further investigation. It is strange though as e.g. `scipy.linalg.inv` is tested in the scipy PR and work fine.
- [ ] Missing modules in tests `mmap`, `multiprocessing` etc. Those are not used in the core package just in tests, and I'm not sure it's worth patching it.
- [ ] Failures of the form,
   ```
   TypeError: __init__() got an unexpected keyword argument 'prefer'
   ```
   (around 114 failed tests): these are due to out use of vendored joblib 0.11, and should be fixed once the patch from https://github.com/scikit-learn/scikit-learn/pull/12350 is applied.
 - [ ] Tests for `sklearn.datasets` that needs downloads are skipped because downloading needs sockets which won't work.
 - [ ] A few genuine failures that need further investigation.

The first is more concerning, and definitely needs fixing. Still I think it might be worthwhile to merge both PRs and address this subequently.

@tiwariayush this may give you a better idea what currently works and what doesn't in the latest scikit-learn build.

**Comment by rth** [comment]
Closing as resolves. The remaining points are mostly scipy related issues #549
