### ISSUE TITLE
Change dependencies from ftp to http

### ISSUE THREAD

**Issue by dmondev** [pyodide/pyodide#1395]
## Detailed Description

Change the source from which pyodide fetches dependencies from ftp to http to build the "minimal" pyodide package.

## Context

I'm building pyodide from sources in a very restricted environment, and I'm unable to download dependencies via ftp. 
By changing it to http I would be able to build it locally, and more easily try changes/fixes not yet released.
This enhancement request doesn't delve into all of the packages available in pyodide, but only the minimal build.

## Possible Implementation
bzip2, libxml2, libxslt have alternative source locations with http address. The implementation is simple changing the already available constants pointing to sources in http locations.

**Comment by rth** [comment]
Would you like to make a PR?

**Comment by dmondev** [comment]
> Would you like to make a PR?

I'm working on it !!

**Comment by rth** [comment]
Resolved in https://github.com/pyodide/pyodide/pull/1400
