### ISSUE TITLE
loadPyodide is not defined

### ISSUE THREAD

**Issue by daoxian** [pyodide/pyodide#1416]
According to the manual: https://pyodide.org/en/latest/usage/quickstart.html

```
<!DOCTYPE html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        await loadPyodide({
          indexURL : "https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/"
        });
        console.log(pyodide.runPython(`
            import sys
            sys.version
        `));
        console.log(pyodide.runPython(`print(1 + 2)`));
      }
      main();
    </script>
  </body>
</html>
```

It doesn't work.
![image](https://user-images.githubusercontent.com/34263430/113382939-55a25e00-93b5-11eb-8a12-2293a68b118d.png)
What's the problem? @rth @hoodmane

**Comment by hoodmane** [comment]
`loadPyodide` doesn't exist yet in version `0.17.0a2`, to get it use the master version https://cdn.jsdelivr.net/pyodide/dev/full/.

**Comment by hoodmane** [comment]
@rth We really ought to make a more prominent link to the latest stable docs.

**Comment by hoodmane** [comment]
I guess it'd be nice if https://pyodide.org/en/0.16.1/ and https://pyodide.org/en/0.17.0a2/ were valid links, and maybe pyodide.org should better redirect to the docs for v0.16.1.

**Comment by daoxian** [comment]
> `loadPyodide` doesn't exist yet in version `0.17.0a2`, to get it use the master version https://cdn.jsdelivr.net/pyodide/dev/full/.

No, it doesn't work either.
```
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        await loadPyodide({
          indexURL : "https://cdn.jsdelivr.net/pyodide/dev/full/"
        });
        console.log(pyodide.runPython(`
            import sys
            sys.version
        `));
        console.log(pyodide.runPython(`print(1 + 2)`));
      }
      main();
    </script>
  </body>
</html>

```
![image](https://user-images.githubusercontent.com/34263430/113385582-fe06f100-93ba-11eb-81ae-2f5f25a50848.png)

**Comment by hoodmane** [comment]
Right, master is deployed to the cdn as `pyodide/dev` whenever the CI tests succeed. Since the migration to a separate org in 8ac788c424da3e466d67d742633b4beaf5c78642 the CI never succeeds, and so it still points to the commit before that fd88a18ca373b6edad2be0ceb54e1760e092220e whereas `loadPyodide` was added after in commit 150c1f6b45e7bfec0e16c1088713a142435d8679.

**Comment by daoxian** [comment]
Run with v0.17.0a2， original

**Comment by rth** [comment]
> I guess it'd be nice if pyodide.org/en/0.16.1 and pyodide.org/en/0.17.0a2 were valid links

They are now I changed the documentation links in the readme in https://github.com/pyodide/pyodide/pull/1417 to point to 0.17.0a2  documentation temporarairly.

>  and maybe pyodide.org should better redirect to the docs for v0.16.1.

Yes, pyodide.org/en/stable tracks the last stable release and I think we should make the redirect from pyodide.org to it once 0.17.0 is out. At present pointing users to 0.16.1 is not helpful IMO were too many changes since.

**Comment by rth** [comment]
BTW, @hoodmane if you create a ReadTheDocs account and give me the username I can add you as a maintainer to https://readthedocs.org/projects/pyodide/

**Comment by josephrocca** [comment]
@rth @hoodmane the docs currently have this URL: https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.js and it has the same "loadPyodide is not defined" error. Changing to https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js solves it. Is there something I can do to help correct the docs? I imagine there are quite a few people getting stuck on this.

**Comment by hoodmane** [comment]
@rth I got hoodmane at readthedocs too.

@josephrocca Our current plan is to release 0.17.0 on the 22nd, so I think it's okay to just leave it inconsistent until then? In the future, we should probably try to link the stable docs and make sure that stable docs link stable Pyodide and master docs link master Pyodide.

**Comment by lzell** [comment]
I'm encountering this error as well.

> we should probably try to link the stable docs
Are the stable docs those that are found at https://github.com/pyodide/pyodide/tree/master/docs/usage ? Do I need to view them on a particular git branch?

I'm attempting to work through the getting started guide. After encountering the error that daoxian ran into, I applied the fix that josephrocca mentioned. However, I am now seeing `ReferenceError: _createPyodideModule is not defined`. Please let me know if there is a version of the getting started guide at docs/usage that I should be following. Thanks!

**Comment by hoodmane** [comment]
@lzell I'm sorry about this, we clearly need to make sure this is resolved soon. What you should do is follow the guide in the docs but every time it says `"https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/"` put instead `"https://cdn.jsdelivr.net/pyodide/dev/full/"`. Nothing else should need to change. 

The text is based on additions that were made after v0.17.0a2 but it says to use v0.17.0a2. This is what is causing the trouble I think.

**Comment by rth** [comment]
This should be resolved in https://github.com/pyodide/pyodide/pull/1479

You can either need to use,
 - https://pyodide.org/en/0.17.0a2/ documentation for the latest release. Which should have consistent CDN URls in the docs, as far as I can tell.
 - or https://pyodide.org/en/latest/ the development version, but indeed by changing the CDN URLs to `"https://cdn.jsdelivr.net/pyodide/dev/full/"` (which will be fixed once https://github.com/pyodide/pyodide/pull/1479 is merged)

**Comment by lzell** [comment]
Confirmed that following the latest instructions in `quickstart.md` worked for me, thank you!

**Comment by mturoci** [comment]
Getting the `loadPyodide is not defined` in `0.20.0`, changing to `dev` resolves the problem, but is not that great of a solution.

Was following the latest docs quickstart.
