### ISSUE TITLE
[Doc] Clicking on stable returns 404

### ISSUE THREAD

**Issue by politinsa** [pyodide/pyodide#1428]
When clicking on "stable" on the readthedoc panel from most page on https://pyodide.org/en/0.17.0a2/ raises a HTTP 404.
We can only see the latest doc.

Of course there is no stable version as v1 is not out yet but it looks like like "latest" in unstable/dev.

![image](https://user-images.githubusercontent.com/28572226/113489863-f896cd00-94c6-11eb-9b7c-6cec1f98d345.png)

**Comment by rth** [comment]
Thanks for reporting it @politinsa ! Yes, `stable` currently point to 0.16.1 and we had a change in a number of URL paths since. It should be fixed once 0.17.0 is released (and becomes served under the "stable" tag)

**Comment by rth** [comment]
This should now be resolved with 0.17.0
