### ISSUE TITLE
List of out of date packages

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1464]
The following pure Python packages with patches are out of date
* astropy v3.2.3 ==> 4.2.1
* joblib 0.11 ==> 1.0.1
* mpmath 1.1.0 ==> 1.2.1 
* numcodecs 0.7.2 ==> 0.7.3 
* ~pytest 3.6.3 ==> 6.2.3~ Updated by #1719.
* python-sat 0.1.6.dev6 ==> 0.1.7.dev1
* scikit-image 0.15.0 ==> 0.18.1   : *blocked by scipy*
* setuptools 40.0.0 ==> 56.0.0
* zarr 2.6.1 ==> 2.7.0

Following mixed packages are out of date:
* numpy 1.17.5 ==> 1.20.2
* libxml 4.4.1 ==> 4.6.3
* pillow 8.0.1 ==> 8.2.0
* pandas 1.0.5 ==> 1.2.4
* matplotlib 3.3.3 ==> 3.4.1
* scipy 0.17.1 ==> 1.6.2  : #1293
* scikit-learn 0.22.2 ==> 0.24.1   : *blocked by scipy*

**Comment by teonbrooks** [comment]
`mne` is out of date as well but I've been thinking about whether it's necessary to keep it in the package list since it is a pure python package. 
I'm using pyodide in an Electron app and it's been convenient having `mne` bundled with the zip but I was thinking it might be useful to download the pypi wheel, and install it via micropip (I need the app to be able to run without internet so I can't load `mne` on the fly). It would help reduce the number of extraneous packages. 
just to confirm, can you load wheels locally? if so, would all i need to do is load pyodide in JS and do `micropip.install('./path/to/mne/mne_something.whl')`?

**Comment by hoodmane** [comment]
mne will be updated to 0.22.1 in #1460.

> just to confirm, can you load wheels locally?

I believe that this works and we intend to support it. But if it turns out that it doesn't work for some reason, please open an issue. =)

**Comment by teonbrooks** [comment]
ok cool :) I think I will wait til after the release to propose removing it. at the moment, it's harmless. just curious, is there a guiding principle to what gets added/removed to pyodide internal package manager? I assume requested non-pure py packages. this all might change if we worked to get conda(-forge) to make a wasm build target :)

**Comment by hoodmane** [comment]
> is there a guiding principle to what gets added/removed to pyodide internal package manager? I assume requested non-pure py packages

Yeah I think the policy is something like: we won't take anything that has a pure Python wheel on pypi. 

If it is pure Python and has no wheel, please make a reasonable effort to get the maintainers of the package to add a wheel, if that doesn't work in a reasonable amount of time then we can add the package until the wheel gets added. See the case with plotly / retrying in #1267.

If it is not pure Python, then we get into a cost/benefit analysis of build time and maintenance effort vs usefulness / interest.

I suppose I should make a PR to write this down in the docs.

See also: https://github.com/pyodide/pyodide/discussions/1397

**Comment by hoodmane** [comment]
I also want to combine `micropip` and `loadPackage` and rework things to make it matter less whether a package is loaded from a wheel or not. Currently the API is a bit hard to use and makes it a breaking change to remove a pure Python package. See #1470.

**Comment by hoodmane** [comment]
@teonbrooks mne raises an error on import: `ValueError: LAPACK function dgesvd could not be found` 
since version 0.19.0. No update for mne I guess.

**Comment by rth** [comment]
> mne raises an error on import: ValueError: LAPACK function dgesvd could not be found
since version 0.19.0. No update for mne I guess.

Thanks for checking. So it also needs a newer scipy.

**Comment by teonbrooks** [comment]
@hoodmane interesting. just read on mne's readme that it requires scipy >= 1.1.0. I have 1.4.1 on my local machine and it works with mne

**Comment by hoodmane** [comment]
Closed as outdated. We currently down to 8 out of date packages after #2085.
