### ISSUE TITLE
Plans for loadPackage / micropip.install

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1470]
I think we should update `loadPackage` to require that if it loads a file from `http://some_website/pyodide_packages/blah.js` or `./blah.js` or whatever, there must be a `packages.json` in the same directory. Then we can load the version info (and dependencies) from the `packages.json`. This will allow us to fix the remaining package loading bugs. (If you load a package with `loadPackage`, then `micropip` won't know about it and may install a different version over it in the future, `micropip` isn't aware of the `loadPackage` dependency resolution, `loadPackage` can't do dependency resolution unless the package is loaded from `indexURL`.)

Then at that point, I think we can add extra logic into `loadPackage` so that it can load and call into micropip if need be. Then we can support installing wheels and packages from pypi using `loadPackage` and remove references to micropip from the docs, encouraging people to use `loadPackage` instead. For use from Python we can add `pyodide.load_package` which as just an alias to `loadPackage`.

I think that removing the mental overhead of figuring out the difference between `loadPackage` and `micropip` will help beginners out a lot.

_Originally posted by @hoodmane in https://github.com/pyodide/pyodide/issues/1469#issuecomment-819286731_

**Comment by oeway** [comment]
I find it confusing that we cannot do `micropip.install("numpy")` in the console: https://pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html, is that related to the plan here?

**Comment by hoodmane** [comment]
This bug was also fixed in #1457 / #1463.

But my goal is to get rid of all confusions about the differences between `micropip` vs `loadPackage` by merging them completely.

**Comment by teonbrooks** [comment]
I like this proposal. I have definitely run into the problem of loading different versions of the same package, one listed in pyodide, the other being a pure python that can be loaded with micropip. it would enforce that pyodide listed package that version precedence. It would also clarify the process too: load package(s) first, import them after

**Comment by rth** [comment]
> But my goal is to get rid of all confusions about the differences between micropip vs loadPackage by merging them completely.

I agree moving in that direction would make sense, and making it more user friendly would be good. I'm not sure however that we can completely smooth the difference between these two sources.

Major differences are,
 - In loadPackage, we can do full dependency resolution for available packages. With micropip we can't. Metadata from the PyPi JSON API is not fully reliable and sometimes you have download the package to discover its dependencies.
 - In loadPackage we have the the mapping between imports and package names, in micropip we don't. Also generally I'm not sure it's a good idea security wise to try to load arbitrary packages from PyPi based on imports in user code as we currently do with loadPackage.

Also I would say there are also two really different use cases,
 - **applications**, the list of dependencies is fixed and known in advance. It doesn't really make sense to try to do dependency resolution live. It's both time consuming and there is a high likelihood that something breaks with the change of packages on PyPi.  Here I would rather see generating a lock file (as NPM or Poetry do) before deployment of the app. And ideally re-use existing tooling. Dependency resolution of packages from PyPi is a hard problem https://github.com/pypa/pip/issues/9187#issuecomment-736171959 https://python-poetry.org/docs/faq/#why-is-the-dependency-resolution-process-slow   There is some potential for optimizing packages at this step as well.
 - **interactive usage** we can do our best effort, kind of what we have been doing so far, but I imagine there will still be challenges when merging our dependency tree with that of PyPi.

**Comment by hoodmane** [comment]
> I'm not sure however that we can completely smooth the difference between these two sources.

I am not sure either, I do not understand the design constraints all that well yet. I am sure we can do better than what we currently have if we think carefully about it though.

> two really different use cases,
> * applications,
> * interactive usage

A third use case I'm worried about is "just getting started": in general people want to first get something working and then worry about the best way to organize stuff like package loading for their application after their main logic works. This is slightly similar to the "interactive usage" use case.

**Comment by hoodmane** [comment]
> Dependency resolution of packages from PyPi is a hard problem

I think the simplest formulation of dependency resolution is NP-hard, whereas it's most desirable for the runtime to be more like linear or quadratic in the total number of packages involved. In order to guarantee fast run time, dependency resolution algorithms have to fail in complicated cases and force the package authors to add hints.

**Comment by hoodmane** [comment]
> I think the simplest formulation of dependency resolution is NP-hard

On further reflection, dependency resolution is [SAT](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem).

**Comment by alexmojaki** [comment]
Being able to do everything through loadPackage would be great. I'm using `loadPackagesFromImports` and it's working perfectly. Users can just write `import foo` and it automatically tries to install and import foo. If anything goes wrong, even a network error, they get a ModuleNotFoundError. But obviously this only actually installs packages built for pyodide. What's the easiest way to automatically use micropip.install when needed? I can't see how to even tell when it's needed - do I need to use error callbacks from loadPackage?

**Comment by hoodmane** [comment]
> What's the easiest way to automatically use `micropip.install` when needed?

I think the best approach is to always use `micropip.install`. It will use `loadPackage` when appropriate.

**Comment by alexmojaki** [comment]
Thanks, that helped. So does this look like sensible usage? https://github.com/alexmojaki/futurecoder/commit/4f7e66823b34b2f9fd853241d002ccba984bca04

You can test it at https://futurecoder.io/course/#ide

I'm confused now, what's the advantage of loadPackage over micropip.install?

**Comment by rth** [comment]
> Thanks, that helped. So does this look like sensible usage? alexmojaki/futurecoder@4f7e668

Yes, as long as you are aware that this will not always work because for many PyPi packages the import name is different from the package name (e.g. `pip install beautifulsoup4` / `import bs4`). We only include this mapping for packages included in Pyodide, such database for all PyPi does not exist as far as I know.

>  what's the advantage of loadPackage over micropip.install?

Well for one thing, you can reliably use loadPackages in combination with `pyodide.find_imports` / `_import_name_to_package_name` unlike with micropip. In any case that's the function that we use to load packages built for Pyodide (micropip doesn't have that functionality, and uses loadPackages). Whether it should be part of the public API is debatable.

**Comment by rth** [comment]
> I think the best approach is to always use micropip.install. It will use loadPackage when appropriate.

yes, I think the best would be to keep loadPackage  as a more internal API for people who for instance care about size and don't want to install micropip. Otherwise always use micopip.

A first step in that direction, could be to add `with_micropip=True` option to loadPyodide, so that we can have examples that directly use micropip without having to first load it explicitly with loadPackage.

**Comment by hoodmane** [comment]
Closed in favor of #2045.
