### ISSUE TITLE
Cmake errors when adding dlib

### ISSUE THREAD

**Issue by viktorChekhovoi** [pyodide/pyodide#1475]
I tried adding the dlib library and got a cmake error that I wasn't able to resolve:

`target_compile_features The compiler feature "cxx_rvalue_references" is not`
 `known to CXX compiler`

`  "GNU"`

`  version 8.3.0.`
`Call Stack (most recent call first):`
`  /src/packages/dlib/build/dlib-19.22.0/dlib/CMakeLists.txt:869 (enable_cpp11_for_target)`

This error seems to occur mostly for MacOS users but I was using the Docker container provided. The solutions suggested here: https://github.com/davisking/dlib/issues/2061 also don't work because the  use_cpp_11.cmake file is remade after the 'make' command. 

I also was able to install dlib with pip in the Docker container, not using the 'make' command. Since that worked with no errors, there has to be something wrong with the way pyodide handles c++ libraries. I attached the full output containing the error message in a test file below. 

[tmp.txt](https://github.com/pyodide/pyodide/files/6320733/tmp.txt)

**Comment by hoodmane** [comment]
Thanks for the report. Hopefully someone can investigate this after the v0.17 release.

**Comment by mgreminger** [comment]
@victorChekhovoy, I ran into a similar issue when creating the package for nlopt (also C++).  emscripten doesn't support C++11 features by default so the `-std=c++11` flag needs to be added to the `cxxflags` option in the `meta.yaml` file if you haven't done this already. See the relevant [line in the `meta.yaml`](https://github.com/pyodide/pyodide/blob/2b54f453fa217b6a59fab303bdf515b786a00e0a/packages/nlopt/meta.yaml#L19) file for the nlopt package.
