### ISSUE TITLE
[BUG] REPL printing error

### ISSUE THREAD

**Issue by teonbrooks** [pyodide/pyodide#1490]
There seems to be a printing error with the console. However, it seems to update itself after another execution.

To recreate:
![Screenshot 2021-04-19 at 10-27-06 https pyodide org](https://user-images.githubusercontent.com/1578674/115253250-323c1a80-a0fa-11eb-992b-fd906964c3d5.png)

Then:
![Screenshot 2021-04-19 at 10-28-59 https pyodide org](https://user-images.githubusercontent.com/1578674/115253257-3405de00-a0fa-11eb-9ddf-36a02d091acc.png)

**Comment by hoodmane** [comment]
Thanks for the report! I have seen this before but I am not being able to reproduce it right now. It's possible that this was fixed in #1480.

**Comment by hoodmane** [comment]
Which browser did you test this on?

**Comment by hoodmane** [comment]
Okay confirmed I can reproduce this on commit 62829f45dbc2a57aed0a4ac5adb612827591d93a directly before #1480 but not on #1480.
