### ISSUE TITLE
DOC: missing api reference entries on the latest docs

### ISSUE THREAD

**Issue by jtpio** [pyodide/pyodide#1506]
Looks like some api reference entries are missing in the `latest` version of the docs:

![image](https://user-images.githubusercontent.com/591645/115433593-08711980-a208-11eb-88e1-41ff877f3310.png)

While they seem to be available for `0.17.0a2`:

![image](https://user-images.githubusercontent.com/591645/115433519-f2fbef80-a207-11eb-8b08-c39dca3cee80.png)

For example the interactive console: https://pyodide.org/en/0.17.0a2/usage/python-api/pyodide.console.InteractiveConsole.html

It could be because there are now several categories like "JavaScript API" and "Python API"?

**Comment by rth** [comment]
Thanks for the report!
It's due to switching from an explicit list of functions to module auto-summary in https://github.com/pyodide/pyodide/pull/1354 . I think we could revert that change.

**Comment by hoodmane** [comment]
I wonder whether we could manually maintain a list and then assert that the manual list is equal to the autodocsumm list. There are problems with both ways: automatic collection can miss stuff, but also it's easy to forget to add things manually. But perhaps if we do both and then assert that they match, we can get the best of both worlds?

**Comment by hoodmane** [comment]
In this case the actual problem is that we don't list `InteractiveConsole` in `pyodide.__all__`.

**Comment by rth** [comment]
> In this case the actual problem is that we don't list InteractiveConsole in pyodide.__all__.

But that's correct it shouldn't be there I think. It should be under `pyodide.console.__all__` as it is now.

> automatic collection can miss stuff, but also it's easy to forget to add things manually.

Yeah, we could probably add some check, but for v0.17 the easy fix is likely to do it manually. It's more complex if one has to check not just `pyodide.__all__` but a tree of modules.

**Comment by hoodmane** [comment]
I'll open a PR for this in a minute.

**Comment by hoodmane** [comment]
> But that's correct it shouldn't be there I think. It should be under `pyodide.console.__all__` as it is now.

Right I was mistaken.

**Comment by hoodmane** [comment]
> the easy fix is likely to do it manually.

Annoying issue with this sphinx stuff is that every tool produces visually different output. It ought to be easy to switch between manual and automatic without changing visual appearance too much.

**Comment by hoodmane** [comment]
Closed by #1511, thanks a lot for your help with the docs @jtpio.
