### ISSUE TITLE
InteractiveConsole API is not ready for public use

### ISSUE THREAD

**Issue by jtpio** [pyodide/pyodide#1516]
Trying to subclass the `InteractiveConsole` from `pyodide.console`, it looks like the signature of the `runcode` method might be misleading.

With `0.17.0a2`, the parameter `code` would be pass to the parent for execution and be taken into account:

https://github.com/pyodide/pyodide/blob/afb522ed59a08dc7edd0ae7935ec2999d55ed544/src/pyodide-py/pyodide/console.py#L228

With the latest (fetching from https://pyodide-cdn2.iodide.io/dev/full/pyodide.js), it doesn't seem to be the case anymore with the `code` parameter being ignored:

https://github.com/pyodide/pyodide/blob/60100c8fc66d3acffdca79e6ff3f1d4dd2200a09/src/pyodide-py/pyodide/console.py#L212-L225

Maybe the  `runcode` method could simply be replaced by the following?

```python
def runcode(self, code):
    self.run_complete = ensure_future(
        self.load_packages_and_run(self.run_complete, code)
    )
```

**Comment by rth** [comment]
Thanks for the report ! The signature is not consistent indeed. This change was introduced in https://github.com/pyodide/pyodide/pull/1459  cc @hoodmane

**Comment by rth** [comment]
> Maybe the runcode method could simply be replaced by the following?

That should have been the fix, I think, but this currently leads to test failures because of the way runcode interacts with `push` and `runsource` methods (sometimes via the parent class). Need to investigate more.

**Comment by hoodmane** [comment]
Thanks for another great docs report @jtpio.

I'm sorry about this, I forgot that `InteractiveConsole` is public, in my head `InteractiveConsole` was a `console.html` implementation detail (this also caused #1506).

> Maybe the runcode method could simply be replaced by the following?

Problem is that `eval_code` applies a source-level AST transform. It cannot accept a code object. However, we actually split the source into two different pieces and compile them separately, so it cannot produce a single code object.

I am going to go back to "modify ast to store into a single global variable and run with eval" like I originally had. That would prevent problems like this.

I suppose I could use `_n` to store the result and just leave it there like Jupyter does.

**Comment by rth** [comment]
Thanks! It would be good to add a test for runcode, I started to write one something like,

<details>

```
diff --git a/src/tests/test_console.py b/src/tests/test_console.py
index 2ea4c8d..0cc34dd 100644
--- a/src/tests/test_console.py
+++ b/src/tests/test_console.py
@@ -247,6 +247,25 @@ def test_completion(selenium, safe_selenium_sys_redi
         8,
     ]
 
+def test_interactive_console_runcode(selenium, safe_selenium_sys_redirec
+    selenium.run(
+        """
+        import sys
+        from pyodide.console import InteractiveConsole
+
+        result = None
+
+        def display(value):
+            global result
+            result = value
+
+        shell = InteractiveConsole()
+        shell.display = display
+        """
+    )
+    selenium.run("shell.runcode('1+1')")
+    assert selenium.run("result") == 2
+
```

</details>

**Comment by hoodmane** [comment]
> runcode('1+1')

`runcode` wants a code object, something like `compile('1+1', 'my-file', 'eval')`.

**Comment by hoodmane** [comment]
I should really start using those details panes to post tracebacks.

**Comment by hoodmane** [comment]
@rth What is the standard Python way to document Python fields?
```
def __init__(self):
	self.whatever = "I think people will care about this but it doesn't show up in API docs"`

**Comment by rth** [comment]
That's would be under the "Attributes" section for the class docstring https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring

**Comment by casatir** [comment]
> runcode wants a code object, something like compile('1+1', 'my-file', 'eval').

Is that sure?

[runcode](https://github.com/python/cpython/blob/master/Lib/code.py#L90) seems to call `exec` on `code` variable. But `exec() arg 1 must be a string, bytes or code object`.

**Comment by hoodmane** [comment]
Oh huh.

**Comment by hoodmane** [comment]
This code is not currently appropriate for public use. I am mostly done reworking it but it's a large diff and will need review. I will mark this as not ready yet in the docs. We can make 0.17.1 with just this when the PR gets through review.

**Comment by rth** [comment]
Thanks for the confirmation. Sounds good to me.

**Comment by jtpio** [comment]
Thanks all for looking into it!

**Comment by rth** [comment]
Should be resolved by https://github.com/pyodide/pyodide/pull/1635
