### ISSUE TITLE
Can't call loadPackage from Python

### ISSUE THREAD

**Issue by casatir** [pyodide/pyodide#1517]
```python
pyodide.runPython("import js ; js.pyodide.loadPackage(['numpy'])")
```
gives an error:

`Skipping unknown package '['numpy']'`

This is because `loadPackage` does not check for `PyProxy` input.

Doing

``` javascript
window.loadPackage = async function (packages) {
    if( pyodide.isPyProxy(packages) ) packages = packages.toJs();
    return await pyodide.loadPackage(packages);
};
```

then calling this `js.loadPackage` from Python seems to fix this issue. (I did not take care for extra parameters in `loadPackage` in this example)

I can submit a PR if needed.

**Comment by hoodmane** [comment]
Thanks!

> I can submit a PR if needed.

That would be very helpful.

Make sure to destroy the `PyProxy` after converting it `toJs`:
```js
if(pyodide.isPyProxy(packages)){
   let temp;
   try {
      temp = packages.toJs();
   } finally {
      packages.destroy();
   }
   packages = temp;
}
```
(This memory management is gross I know, I have a plan to make it better in the next release.)

**Comment by casatir** [comment]
Thanks @hoodman.

I have noticed to destroy the PyProxy. This is really well documented indeed!

My fix was too quick, I just wanted to let you know about it and the easy fix to let you decide if it has to go in the 0.17.0 release.

> (This memory management is gross I know, I have a plan to make it better in the next release.)

If this is the price to pay to avoid (or minimize) leaks, I'm OK with it! Thanks!

**Comment by hoodmane** [comment]
> I have noticed to destroy the PyProxy. This is really well documented indeed!

=D I tried to make it impossible to miss!
