### ISSUE TITLE
Prebuilt docker image is missing

### ISSUE THREAD

**Issue by dmondev** [pyodide/pyodide#1528]
I believe this is due to the iodide to Pyodide rename.

pyodide/pyodide:0.17.0 is not available in docker hub.

```
~/dev/git/pyodide$ ./run_docker --pre-built
Unable to find image 'pyodide/pyodide:0.17.0' locally
docker: Error response from daemon: pull access denied for pyodide/pyodide, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'
```

**Comment by rth** [comment]
Yes, forgot to update it yesterday. Working on it. Thanks for reporting this @dmondev !

**Comment by rth** [comment]
The image is now available at https://hub.docker.com/repository/docker/pyodide/pyodide, so `https://hub.docker.com/repository/docker/pyodide/pyodide` should work.

**Comment by dmondev** [comment]
Just tested, looks good !

Thanks, @rth !

**Comment by kasbah** [comment]
Looks like it's missing again for 0.21.0
