### ISSUE TITLE
Schedule for next release

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1536]
Why don't we pick a tentative dates for the 0.18.0 release and then target a 0.18.0beta release for two weeks ahead of 0.18.0?

Last release was four months, I think 3 -- 4 months between releases is pretty standard? So how about we say August 23rd, so then the beta would be for August 9th, and the "planned schedule reassessment, push back release if needed" date would be July 19th. 

Also, what day of the week do we want the release on? Those are Mondays. Maybe we'd want Thursday again?

@rth

**Comment by rth** [comment]
Good idea. I think we will likely have plenty of things to release even after 3 months, so how about,

 - 0.18.0 release: Thursday July 22nd
 - 0.18.0b1: 2 weeks before: July 8

and we can always push it to later if necessary?

**Comment by hoodmane** [comment]
Let's also mark June 24th as the date to decide whether to push the release and to add milestones to open PRs.

**Comment by hoodmane** [comment]
Maybe we should try to release 0.18.0b1 on July 8th in any case, if we have to delay the schedule we can do a 0.18.0b2 on July 22nd instead.

**Comment by ryanking13** [comment]
I think this issue can be closed. We may open a new one for the next release(v0.19.0).
