### ISSUE TITLE
Adding geopandas?

### ISSUE THREAD

**Issue by deeplook** [pyodide/pyodide#1569]
Is it thinkable to include geopandas? Or is that too heavily depending on C/C++ packages?

**Comment by rth** [comment]
We can try to include it. It does have [a number of dependencies](https://github.com/conda-forge/geopandas-feedstock/blob/master/recipe/meta.yaml#L23) which would also need to be packaged, and as far as I remember GIS related tools tend to be complex to package.

More generally we need to switch to a build setup where all packages are not re-built for each commit, as that takes a long time (even with ccache) and is not really necessary.

**Comment by yxdragon** [comment]
geo pandas depandents on gdal, it is very heavy.  a light solution is geopandas + shapely + pyproj.
could shapely and pyproj be web assambly?

**Comment by yxdragon** [comment]
geo pandas depandents on gdal, it is very heavy.  a light solution is geopandas + shapely + pyproj.
could shapely and pyproj be web assambly?

**Comment by deeplook** [comment]
Yes, shapely would be a must. Pyproj and fiona seem like hard dependencies, too.

**Comment by rth** [comment]
For shapely, adding ctypes support (https://github.com/pyodide/pyodide/issues/728) is a blocker.

For pyproj and fiona someone would need to try to [create the corresponding pyodide package](https://pyodide.org/en/stable/development/new-packages.html#mkpkg) and see if there are any issues.

**Comment by yxdragon** [comment]
I think the biggest trouble gdal, It is hard to be installed even on native python, and gdal is not pythonic.
pyproj is a cython project, I think it could be web assambly.

geopandas is a dataframe with a geometry columns and a crs.
georaster is a image with a crs and a affine matrix.

So if it is difficult to support gdal and fiona, I think we can give up them. I can try to build a light repo. just need (numpy, pandas shapely, pyproj), and some light or pure python lib for io, such as (h5py, netCDF for raster, pyshp, simplekml for vector)

**shapely is important, not only in geography**
I think there are 3 base struct in scientific calculation：
1. array or (series, image, table...) > numpy, scipy, pandas, optional: [skimage, opencv...]
2. vector or (cloudpoints, polygon, mesh) > shapely, pymesh [open3d, pcl ...]
3. graph or (tree, network) > scipy.sparse, networkx

**Comment by mattficke** [comment]
>For shapely, adding ctypes support (#728) is a blocker.

Looks like this was added in https://github.com/pyodide/pyodide/pull/1656. Do you know if there are other blockers for shapely here?

**Comment by hoodmane** [comment]
The next issue for shapely is to port libgeos:
https://trac.osgeo.org/geos/

**Comment by hoodmane** [comment]
Asked about this on emscripten https://github.com/emscripten-core/emscripten/issues/15276

**Comment by leouieda** [comment]
Perhaps this can help shed some light on GDAL and other hard to package libs: https://github.com/bugra9/gdal3.js

**Comment by raybellwaves** [comment]
created a separate issue for adding fiona which is a geopandas dependency: https://github.com/pyodide/pyodide/issues/3091

**Comment by rth** [comment]
Recently @jorisvandenbossche mentioned that it might be possible to build geopandas without some of the hard to build dependencies (at the cost of reduced functionality).  Currently, we have shapely available but not fiona & GDAL. Any suggestions on this, Joris? Unless I misunderstood  you :)

Any way to load GeoJSON without fiona? Or at least it feels more useful to try to build pyarrow https://github.com/pyodide/pyodide/issues/2933 and use the parquet backend in geopandas rather than spending time to build GDAL.

**Comment by jorisvandenbossche** [comment]
That's correct, you can use geopandas with only shapely and pyproj installed. We currently still list `fiona` (and thus GDAL) as an install requirement in setup.py, but if you force to install without fiona, it will work fine (on conda-forge, we already have a geopandas-base package that does not depend on fiona, long term we will probably drop fiona as a dependency for the python package as well). 
The only thing you can't use are the `read_file`/`to_file` functions. But you can load geojson using the `GeoDataFrame.from_features` if you pass it the dict from `json.loads`

**Comment by jorisvandenbossche** [comment]
So if shapely and pyproj are already available (and pandas), and since geopandas is a pure python package (that can be installed without specific effort?), it should actually already work, I think?

**Comment by rth** [comment]
Hah, yes, indeed it works with the [REPL](https://pyodide.org/en/stable/console.html)!
```py
>>> import micropip
>>> await micropip.install(['pandas', 'shapely', 'pyproj'])
>>> await micropip.install('geopandas', deps=False)
>>> import geopandas
>>> geopandas.__version__
'0.11.1'
```
though I haven't tried using it further.

**Comment by rth** [comment]
Opened a follow up usability issue for GeoJSON in this case in  https://github.com/geopandas/geopandas/issues/2548

**Comment by rth** [comment]
So installing from PyPI works, but the package size is a bit large (1MB compressed), and uncompressed:
```
du -sh geopandas/*
4,0K    geopandas/__init__.py
8,0K    geopandas/_compat.py
4,0K    geopandas/_config.py
4,0K    geopandas/_decorator.py
28K     geopandas/_vectorized.py
4,0K    geopandas/_version.py
48K     geopandas/array.py
116K    geopandas/base.py
4,0K    geopandas/conftest.py
976K    geopandas/datasets
36K     geopandas/explore.py
92K     geopandas/geodataframe.py
48K     geopandas/geoseries.py
64K     geopandas/io
36K     geopandas/plotting.py
32K     geopandas/sindex.py
12K     geopandas/testing.py
468K    geopandas/tests
128K    geopandas/tools
```
So packaging it in Pyodide to vendor tests and possibly later datasets https://github.com/pyodide/pyodide/issues/3092 would still be useful.

**Comment by deeplook** [comment]
Awesome, thanks so much!! ❤️
