### ISSUE TITLE
does blas available in pyodide's numpy?

### ISSUE THREAD

**Issue by yxdragon** [pyodide/pyodide#1574]
I try to use [Planer](https://github.com/Image-Py/planer) in pyodide. which is a cnn framework based on pure numpy.
But I found the pyodide runs 50-500 times slower than the native. I test many operation on both pyodide and native.
the most different is np.dot:

```python
arr = np.zeros((1024,1024), dtype=np.float32)
start = time()
np.dot(arr, arr)
print(time()-start, 'sumcost')
```

pyodide: 3s, native: 0.005s
So I think the pyodide run without blas.

Is there any plan about supporting blas?

**Comment by rth** [comment]
Yes, we are currently not explicitly using a BLAS in numpy. We could use the Netlib BLAS which is built in Pyodide but when no BLAS is specified as far as I can tell CBLAS would already be used, which is equivalent..

See https://github.com/pyodide/pyodide/issues/227 for a discussion on using a high performance BLAS. Closing as a duplicate, please don't hesitate to comment there.

> I try to use Planer in pyodide

Just curious what made you try Pyodide as opposed to exporting to ONNX and using ONNX.js for that use case?

**Comment by yxdragon** [comment]
*Just curious what made you try Pyodide as opposed to exporting to ONNX and using ONNX.js for that use case?*
first of all, I am not very aware of web (js/node/html...) I just use one of my repo (planer) as a demo to try pyodide.
Thanks for your advice, and after brosing onnx.js, I think planer‘s meaning is: a cnn models need pre-after processing, for onnx.js, we need do pre-processing in python, then run net in js, and do after-processing in python. But for planer, we can wrap the pre-net-after as one function, and call it through pyodide.
(planer support numpy/cupy, So planer need a blas for numpy, and is it possible to implement a cupy with webgl?)

*We could use the Netlib BLAS which is built in Pyodide*
how to use it?
