### ISSUE TITLE
include netcdf4 and h5py

### ISSUE THREAD

**Issue by yxdragon** [pyodide/pyodide#1582]
hdf and netcdf is two important format in geography and meteorology, request include it in pyodide.

**Comment by rth** [comment]
> yes, zarr is more modern.
but for geography and meteorology, history data is very important, and most of history data is in hdf and netcdf.

Happy to include those, but someone would need to do the work on packaging them.

> another question about hdf/netcdf/zarr. When we read it from native, the reader hold a pointer to the file. And read data we need just in time. But in pyodide, a web environment, is the "just in time read" possible? I worry about browser would load the whole file as memory stream when we upload the file. (hdf/nc/zarr file may be very large)

Well if you need only a small slices of the dataset you would need to,
 - on the client: make an HTTP request indicating in some way the slice you want
 - on the server: either dynamically serve the appropriate slice for a given request, or have some per-determined chunking on your dataset. Or correctly respond to [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests)
 
In any case some work is necessary on your part: if you were previously doing just in time loads from disk you would need to translate that with Web APIs.

**Comment by ax3l** [comment]
For HDF5: #1799

**Comment by bmaranville** [comment]
@ax3l and I worked together and h5py is introduced in PR #2411 which is passing all the tests and almost ready to go!

**Comment by agriyakhetarpal** [comment]
Both `netcdf4` (#3910) and `h5py` (#2411, linked against a WASM build for `libhdf5`) have been available with Pyodide for a few releases by now, so I'll close this issue; please don't hesitate to let us know in case you face any troubles with Pyodide or with either of the packages in particular! :)
