### ISSUE TITLE
Notebook pyodide-asyncio-custom-loop-demo fails (should be marked as outdated)

### ISSUE THREAD

**Issue by pchanial** [pyodide/pyodide#1586]
Just to let you know, the notebook https://alpha.iodide.io/notebooks/6670/ showing an example of event loop policy fails with firefox & chromium:

    p.then(print)
    Exception('error')

Given all the work that occurred on asyncio in 0.17, and the browser event loop being readily available, I guess this notebook is outdated, but it would be nice to have a warning.

**Comment by rth** [comment]
Sorry the Iodide project is no longer actively maintained (https://github.com/iodide-project/iodide) and is in any case a separate project from pyodide. So I'm going to close this issue.

Don't hesitate to open other issues if you encounter difficulties with Pyodide.

Also see  https://pyodide.org/en/stable/project/related-projects.html#notebook-environments-ides-and-repls for other Pyodide based notebook environments.
