### ISSUE TITLE
Use leading $ to distinguish shadowed PyProxy methods

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1589]
I am thinking again of the problem of a Python class with a method that gets shadowed by a PyProxy method. For example:
```js
let t = pyodide.runPython(`
class Test:
   def destroy(self):
      print("destroy!")
Test()
`);
t.destroy(); // should this destroy the PyProxy or call `Test.destroy`?
```
`$` is legal in Javascript identifiers but not in Python identifiers. So I think we should use a trailing `$` for one of these and no trailing `$` for the other:
```js
t.destroy$(); // prints "destroy!"
t.destroy();  // destroys proxy
```
Or maybe the reverse? Or maybe:
```js
t.destroy$py(); // prints "destroy!"
t.destroy$js();  // destroys proxy
```
not sure what the best option here is, but I think using `$` is a sound approach.

**Comment by stefnotch** [comment]
For completeness sake, some more options would be
- Prefixing every PyProxy method with a `$`, like `t.$destroy()` or `t.$clone()`
- Using symbols like `t[PyProxy.destroy]()` 
- Using static methods `PyProxy.destroy(t)`, which could use symbols under the hood

**Comment by rth** [comment]
Thanks for opening this issue. I think I would have a preference for `t.$destroy` (or to a lesser extent `t.destroy$`).

> Or maybe the reverse?

One one side it would be more logical to do,
 - all class methods without $
 - PyProxy methods with $

however that would break backward compatibility and result in code with lots of $ which can be confusing visually.

So maybe let's go with, current methods as is + `$` methods to access shadowed class methods, as you proposed.

**Comment by hoodmane** [comment]
From the point of view of the type definitions, the Typescript type checker will have a very hard time if we use the Python object when there is a name collision. For this reason, I think the best bet is for e.g., `destroy` to always refer to the method that destroys the object and `$destroy` to refer to a Python field named `destroy`.

Otherwise, either the Typescript types will be wrong or unacceptably more complicated. For example typescript will think that `destroy` is a method `(void) => void` and get upset when you try to pass it parameters even though the Python function being called may well expects parameters. You could make a bunch special of types "PyProxy but the destroy method has been shadowed" but it will be a nightmare to write and to use. On the other hand, if `destroy` always means the method that deletes the proxy, everything works great.

**Comment by hoodmane** [comment]
Incidentally, I have no clear idea how to do this for `JsProxy` -- as far as I know there is no character that is valid in Python identifiers but not in Javascript ones. Python also doesn't have anything like `Symbol`s. This should probably be a separate issue though.

**Comment by stefnotch** [comment]
Regarding doing this for `JsProxy`, would a static method work? As in
```
a = some jsproxy instance
JsProxy.destroy(a);
```

**Comment by hoodmane** [comment]
I think we would need something like:
```py
JsProxy.jslookup(a, "new")()
```
or
```py
a.js_lookup("new")
```

Looking at [the list of methods in the JsProxy API](https://pyodide.org/en/stable/usage/api/python-api.html#pyodide.JsProxy), this is currently not likely to be a problem:
`then` and `catch` are common names of Javascript methods, but they just access the corresponding Javascript methods.
`assign` and `assign_to` only appear on a JsProxy of a TypedArray which shouldn't have these methods itself.
`new` could be a problem?
`object_entries`, `object_keys`, `object_values`, and `to_py` are present everywhere but have underscores so aren't likely to cause trouble.
So I don't think this is super urgent.
