### ISSUE TITLE
ipywidgets support (or any object with _repr_html_)

### ISSUE THREAD

**Issue by andfanilo** [pyodide/pyodide#1598]
Hello! Wanted to first say I'm very impressed by Pyodide, it really shows how promising WebAssembly and Python-in-browser is!  

I've been reading the docs and issues a bit (especially the [Matplotlib html5 canvas](https://github.com/pyodide/pyodide/pull/1579) and [Comlink draft](https://github.com/pyodide/pyodide/pull/1535)) but I did not find an immediate answer to the following: 
* how would one theoretically integrate a ipywidget slider in the page, where changing the slider value would change the associated Python variable, 
* or the simpler example of displaying any Python object with a HTML `_repr_html_` where interaction on the JS side would not change any Python value, like displaying a [SHAP](https://shap.readthedocs.io/en/latest/index.html) interactive plot. I guess the Comlink and syncio experiments try to address this though?
     * I say simpler because I think, maybe, for ipywidgets we'll need to build a custom pipeline over their [comm model](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html) to have the view over the browser and the model in a separate web worker. Honestly I don't have enough experience with low-level ipywidgets nor Pyodide/WebAssembly to have an opinion on this

Do you have an opinion/roadmap on how to build this and challenges that may occur? Links to any docs/draft PR I have missed are appreciated too :)

In any cases I'll be following your progress closely!

Have a nice day,
Fanilo :balloon:

**Comment by hoodmane** [comment]
Maybe @jtpio could help with this? His jupyterlite project probably has a solution to this.

https://github.com/jtpio/jupyterlite

**Comment by jtpio** [comment]
Yes this is something we're planning to add to `jupyterlite` at some point.

It might require using a modified (patched or forked) version of `ipywidgets` to get the comms to work. But it should technically be possible.

Currently tracked in https://github.com/jtpio/jupyterlite/issues/18.

**Comment by andfanilo** [comment]
Thanks @jtpio, I'll be definitely following this! The custom Comms is especially interesting, as I'm also looking into linking ipywidgets to Streamlit without too much monkeypatching of comms.

@hoodmane feel free to close this issue if you consider this a duplicate. For the `_repr_html_` it looks like you'll arrive to a documented solution in the coming months and maybe it's tracked somewhere else.

**Comment by jtpio** [comment]
Quick heads-up that many Jupyter Widgets now work in JupyterLite.

You can check them out live on https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html using the example notebooks.

**Comment by andfanilo** [comment]
Thanks, will look into it :+1:
