### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by gabrielfreire** [pyodide/pyodide#160]
Hi guys, is there a way to check for the environment before having window called in this line ?

https://github.com/iodide-project/pyodide/blob/9ee69d1811d9caf4c7f3fdc57ee9e0711bc34061/src/hiwire.c#L112

this gives me an `window is not defined` error in Nodejs, when i replace this for:
```javascript
return Module.hiwire_new_value(jsname); 
```

it works just fine.

would it be possible to have something like:
```c
EM_JS(int, hiwire_get_global, (int idname), {
  var jsname = UTF8ToString(idname);
  return ENVIRONMENT_IS_NODE ? Module.hiwire_new_value(jsname) : Module.hiwire_new_value(window[jsname]);
});
```

i'm not sure what, where or how this change would impact, but it could fix

**Comment by gabrielfreire** [comment]
> Somewhere during initialization in pyodide.js, you would have pyodide.global = ENVIRONMENT_IS_NODE ? global : window. Then the code above becomes Module.global[jsname].

Yes, i like this solution

**Comment by gabrielfreire** [comment]
This is what i did

- Before loading `pyodide.asm.wasm` using `pyodide.asm.js`.
```javascript
// set a global for the node environment
Module['global'] = process;
```

inside `pyodide.asm.js` i changed `hiwire_get_global` return to be like this
```javascript
return Module.hiwire_new_value(Module.global[jsname])
```

and it worked ok.
should i make a PR for this change ?

**Comment by gabrielfreire** [comment]
well, i added here https://github.com/iodide-project/pyodide/pull/183

**Comment by rth** [comment]
Closing as resolved. Node is now supported.
