### ISSUE TITLE
RFC Improve PyProxy lifetime management when calling Javascript functions from Python

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1607]
## Proposal

PyProxy arguments to a Javascript function should be automatically destroyed when the function is done. PyProxies returned from Javascript functions should be destroyed after the function call is finished. 

An implementation is present here: https://github.com/pyodide/pyodide/pull/1573

## Justification

When writing C Python extensions, the lifetime of Python objects must be managed manually. The CPython API has the following rules:
1. Arguments to a C function are borrowed from the caller. The function can use them in the body of the function, but if it wants to persist them it must manually increment the reference count.
2. The callee takes ownership of the return value. If the C function wants to maintain ownership of the return value in some other way, it must manually increment the reference count.

These rules are good because the typical case is that functions do not persist their arguments they only use them in the function body, and the typical case is that the ownership of the returned value is transferred to the caller. My proposal is to take these rules from CPython and apply them also in Pyodide. Because Javascript is a higher level language than C, it is possible to add extra tuning to these rules to make things more convenient.

## Asynchronous functions

Currently it is possible to retrieve the original promise that an asynchronous Javascript function returns. Because of this, we cannot automatically destroy the return value (doing so would cause surprises when people try to use the promise). This leads to some limitations when using asynchronous functions. 

I think the best solution is as follows: If a Javascript function called from Python returns a Promise, we wrap that Promise in a Future which destroys the result PyProxy when done. If the Future is passed into Javascript, we don't unwrap it into the original promise, we wrap the future in a new promise. This way, a new PyProxy can be created for the result and no surprising errors occur. This will require extra memory management for the Future in this case but it will allow the common use cases to work well.

## Backwards Incompatibility

This will require changes to existing code to bring it into compliance. However, I think most code that doesn't leak memory won't need to be changed much. The effect of these changes is to make some simple code that used to be leaky not be leaky. Other simple code that used to be leaky will now result in an error. The new errors caused can be designed to explain the problem reasonably accurately.

No changes to unrelated Pyodide code were required by this, the only test that needed to be changed was one that asserted that we were leaking memory. So I don't suspect that it will be an arduous process to adapt existing code.

## Current situation
Currently there is no way to avoid leaking `d` in the following function:
```js
function newDict(){
	let d = pyodide.globals.get("dict")();
    return d;
}
```
On return to Python, the PyProxy `d` gets automatically unwrapped into a dictionary, so from Python there is no way to destroy `d`. But the function itself cannot destroy it because it would then be unable to return it.

There are tools to avoid leaking arguments, but they aren't all that convenient:
```js
function myJsFunc(a, b){
   try {
      // do stuff
   } finally {
      a.destroy();
      b.destroy();
   }
}
```
or if we want to do the handling from the Python side:
```py
a_proxy = create_proxy(a)
b_proxy = create_proxy(b)
try:
	myJsFunc(a, b, c)
finally:
	a.destroy()
	b.destroy()
```

## Examples of new behavior
Under this proposal, the following function would not leak `d`:
```js
function f(x){
	return x.length;
}
pyodide.runPython(`
   d = { 1 : 2, 3 : 7}
   from js import f
   f(d)
`);
```
If a Javascript function specifically wishes to persist the argument, it must use `clone`:
```js
window.setGlobal = function(x){
   if(pyodide.isPyProxy(window.myGlobal)){
      window.myGlobal.destroy();
   }
   if(pyodide.isPyProxy(x)){
     x = x.clone(); // clone isn't currently necessary
   }
   window.myGlobal = x; 
}
pyodide.runPython(`
   from js import setGlobal
   setGlobal(2)
   setGlobal({})
   setGlobal([])
`);
```
It's also possible for the caller to use `create_proxy`:
```
pyodide.runPython(`
	from js import addEventListener
    from pyodide import create_proxy
	proxy = create_proxy(click_handler)
    addEventListener("click", proxy)
	# ... later
    removeEventListener("click", proxy)
    proxy.destroy()
`);
```
If the user fails to do this, an exception will be raised saying:`This borrowed proxy was automatically destroyed at the end of a function call. ...`

The transfer return rule makes it possible to create a new Python object in a Javascript function and return it to Python without a leak:
```js
function newDict(){
	let d = pyodide.globals.get("dict")();
    return d;
}
pyodide.runPython(`
	from js import newDict
    d = newDict() # currently leaks d, wouldn't under proposal.
`);
```
It's okay for functions to return an argument without doing anything special:
```
function f(x){
	return x;
}
pyodide.runPython(`
   d = { 1 : 2, 3 : 7}
   from js import f
   d2 = f(d) # with proposed change will not leak d
   assert d2 is d
`);
```
If the argument has been created with `create_proxy` it will be destroyed:
```
function f(x){
	return x;
}
pyodide.runPython(`
   d = [1,2,3]
   proxy = create_proxy(d)
   d2 = f(proxy) # destroys proxy
   assert d is d2
`);
```
It is possible to avoid this by cloning the returned value:
```
function f(x){
	return x.clone();
}
pyodide.runPython(`
   d = [1,2,3]
   d2 = f(d) # no leak
   proxy = create_proxy(d)
   d3 = f(proxy) # doesn't destroy proxy
   assert d is d2 is d3
`);
```

**Comment by rth** [comment]
Thanks a lot for writing this RFC @hoodmane ! I changed the title a bit to be shorter. Would you mind writing a short announcement email on the mailing list? If not I can do it.  

From a memory management perspective this would be a great improvement. As  discussed https://github.com/pyodide/pyodide/pull/1573, aside from user functions that can be updated, a major question/concern is whether this would impact the compatibility between Python and JS ecosystems for third party functions that work now (with memory leaks), would error with this proposal and would be impractical to rewrite.
