### ISSUE TITLE
RFC Improve lifetime management for PyProxy attributes

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1617]
## Proposal

When you look up an attribute on a PyProxy, if the value of the attribute is another PyProxy then the lifetime of the attribute should be bound to the lifetime of the original object. When all PyProxies that are clones of the original PyProxy are destroyed, all such "borrowed" proxies should be destroyed as well. 

An implementation is present here: #1636

## Justification

It is currently quite annoying to avoid leaking PyProxies when making nested attribute access or method call. If we make a call like: 
```js
let result = proxy.field.method();
```
this will generate a temporary `PyProxy` for `pyproxy.field` and another temporary for `proxy.field.method` then leak both of these. To avoid the leaks, we currently need to say:
```js
let proxy_field = proxy.field;
let proxy_field_method = proxy_field.method;
proxy_field.destroy();
let result;
try {
   result = proxy_field_method();
} finally {
   proxy_field_method.destroy();
}
```
which converts the original single line into 9 lines. The point of this proposal is to make the short code work without leaking memory. As an added advantage, we can avoid creating temporary Python bound methods and improve speed for repeated lookups.

## Dictionary lookups are unchanged

To be clear, this proposal has no effect on dictionary lookups or more generally on the return values from method calls. Methods still return proxies that are owned by the caller. So 
```js
let d = pyodide.runPython({1 : { 1 : 2}});
let e = d.get(1);
d.destroy();
// lifetime of e is not bound to d
let x = e.get(1); // 2
e.destroy();
```
will work as before. The following will still be leaky:
```js
d.get(1).get(1)
```

## Backwards Incompatibility

If before you used code like
```js
let a = proxy.a;
proxy.destroy();
// use a
```
now `a` is borrowed from `proxy` and is destroyed when `proxy` is destroyed. With this proposal you would have to use `clone()`:
```js
let a = proxy.a.clone();
proxy.destroy();
```
An indicative error message can be chosen for when people do this incorrectly.

**Comment by rth** [comment]
Thanks for the proposal! Yes, looking at https://github.com/pyodide/pyodide/pull/1616 the current approach is clearly not ideal.

> now a is borrowed from proxy and is destroyed when proxy is destroyed.

I agree that that this makes more sense overall. The fact that if you destroy the proxy you need to explicitly copy objects you want to continue using is fairly logical. So +1 for this proposal.

**Comment by rth** [comment]
I shared this RFC [on twitter](https://twitter.com/pyodide/status/1412747361462460416) yesterday  (in addition to the mailing list announcement earlier). Given lack of objections I think we can consider it approved. Thanks @hoodmane !

**Comment by rth** [comment]
@hoodmane Should we close this as resolved, are there other things to do?

**Comment by hoodmane** [comment]
Yeah we implemented this.
