### ISSUE TITLE
Cannot find the pyodide.asm.data in version 17.0

### ISSUE THREAD

**Issue by Monder87** [pyodide/pyodide#1624]
I am currently trying to implement pyodide inside a chrome extension, the problem is that google no longer wants code coming from url, everything has to be saved locally, so I am forced to insert all the library files inside the extension. 
The problem is that I can't find https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.data.js, if I try with https://cdn.jsdelivr.net/pyodide/ v0.17.0 / full / pyodide.asm.data makes me download the wasm instead. 

It only happens for version 0.17 as 0.16 has it all. 
Seems to apply only to date, as pyodide.js, pyodide.asm.js and pyodide.asm.wasm are available. Without date I have an error and therefore I'm blocked, can someone help me? 

thank you

**Comment by rth** [comment]
Hah, that's indeed confusing. The downloaded file is indeed `pyodide.asm.data` it's just that the browser apparently renames it to .wasm because it is served with the WASM content type.

To avoid the renaming you can use for instance wget. Here are the sha256 checksums of those files to be sure,
```
sha256sum pyodide.asm.*
a1b629b9ded99c534a4963c1c86bba92d4e699922fe021831fc5cdba89d33799  /tmp/pyodide.asm.data
dee59896cb512c03a8a675d89072162d8d1b80c6f91a9104c5fa32639a65b9ab  /tmp/pyodide.asm.wasm
```

You can also download the full archive of packages from [Github releases](https://github.com/pyodide/pyodide/releases/tag/0.17.0).

Closing as answered, but don't hesitate to comment if you have other questions.

**Comment by rth** [comment]
> so I am forced to insert all the library files inside the extension.

If you want sharing your experience in including Pyodide in a browser extension I would be interested hearing it (maybe in a separate issue). In particular, whether it would pass their security scan given that it's essentially binary files that cannot be easily inspected.

**Comment by Monder87** [comment]
Thank you for the quick response, sure i will be happy share all my strategies, also cause i am using webpack so make the things little more hard, asap i make it run without issues i will post it here

**Comment by Monder87** [comment]
i just implemented the files and i got this error, can you help me understand possible cause? thank you in advance

webworker.js:35 Uncaught (in promise) PythonError:   File "<string>", line 2
    def temp(Module):
    ^
IndentationError: unexpected indent

    at new_error (pyodide.asm.js:7454)
    at wrap_exception (pyodide.asm.wasm:0x1a6c94)
    at pythonexc2js (pyodide.asm.wasm:0x1a6de5)
    at Object.Module._pythonexc2js (pyodide.asm.js:38912)
    at Object.Module.runPythonSimple (pyodide.js:611)
    at globalThis.loadPyodide (pyodide.js:869)
    at async loadPyodideAndPackages (webworker.js:10)

**Comment by rth** [comment]
It errors here https://github.com/pyodide/pyodide/blob/6168c4b674b457c652778394d9958644b3bdef02/src/js/pyodide.js#L227 

Are you processing that file with webpack in a way that breaks indentation?

**Comment by Monder87** [comment]
no i put it in public folder and i export it as it is without bundle the code for pyodide.js.

![Screen Shot 2021-06-04 at 7 31 42 PM](https://user-images.githubusercontent.com/46753496/120795026-8779a180-c56b-11eb-902c-7a19db83e0d0.png)

**Comment by rth** [comment]
Not sure what's happening then. Worse case scenario you could always try to rewrite those python lines in as a 1 line string with appropriate space indentation and `\n` to make sure it's not coming from the indentations in that file.

**Comment by Monder87** [comment]
yeah indeed was an indent error, prob cause i copied the file manually, anyway all work perfectly! i just run the first python inside a background script in a chrome extension, i will be glad to share how i organized a chrome extension running react + webpack + pyodide ( packed in the extension for google policy ) to run a very modern chrome extension with python inside to leverage ML algorithms. asap i ll finished and i publish with google i ll share a post or something meanwhile who need help just type here, even this is closed  i think i m the first implementing it in a browser extension so i m happy to share
