### ISSUE TITLE
install opencv-python with micropip error

### ISSUE THREAD

**Issue by Monder87** [pyodide/pyodide#1627]
I am recently working on a project that use ML and this library is truly a game changer for project in js... Any luck to have opencv-python included in the list of the python libraries?  thank you in advance

**Comment by Monder87** [comment]
meanwhile i tried to import the wheel of opencv-python  with this: 

```
pyodide.runPythonAsync(`
 import micropip
 await micropip.install('https://files.pythonhosted.org/packages/cf/e1/784c7092d391617ba808d1389f09c8ab2339bd1ab3c6ca117834c2a20914/opencv_python-4.0.1.23-cp27-cp27m-manylinux1_i686.whl')
`);
import cv2 as cv
```

but i got :

```
ImportError: Could not load dynamic lib: /lib/python3.8/site-packages/cv2/cv2.so
RuntimeError: abort(Assertion failed: need to see wasm magic number). Build with -s ASSERTIONS=1 for more info.
```

are not this valid wheel files to use ?

https://pypi.org/project/opencv-python/4.0.1.23/#files

thank you in advance

**Comment by daoxian** [comment]
You may use opencv.js invoked from Python side.
