### ISSUE TITLE
pillow jpg encoder error

### ISSUE THREAD

**Issue by yxdragon** [pyodide/pyodide#1632]
I try use PIL read/write in bmp, png, jpg, tif. jpg not work:
![image](https://user-images.githubusercontent.com/24822467/121064842-a6da2e00-c7fa-11eb-9d8b-0a1d11388816.png)

**Comment by rth** [comment]
Thanks for the report. Could you please provide a minimal code example?

**Comment by yxdragon** [comment]
![image](https://user-images.githubusercontent.com/24822467/121077859-beb9ae00-c80a-11eb-944d-d33d841e2366.png)

I just try in the online console:
```python
from imageio import imread, imsave
import numpy as np
img = np.zeros((5,5), dtype=np.uint8)
imsave('./img.jpg', img)
imread('./img.jpg')
```

and imsave raise a error, and I had also tried read a online jpg file, and imread do not work too.

**Comment by yxdragon** [comment]
'heic' and 'webp' are modern web image format, is it possible to add 'pyheif' and 'webp' packages?

**Comment by rth** [comment]
Looks like an issue with type translations. I can reproduce in Firefox. The exeception happens on [this line](https://github.com/imageio/imageio/blob/23cdcf5e62aceb1a32ee37e529eb731612b98298/imageio/core/functions.py#L305) 

Though I don't understand
 - why that value is a attempted to be translated to BigInt, given that it's smaller than `MAX_SAFE_INTEGER`. 
 - shy the translation happens in the first place given that everything is in Python as far as I can tell

Maybe @hoodmane would have some ideas.

Repeating the error message in plain text so it can be found by search,
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
TypeError: can't convert 23069936 to BigInt
Look in the browser console for more details.
```

> 'heic' and 'webp' are modern web image format, is it possible to add 'pyheif' and 'webp' packages?

Yes, please open a separate issue about it.

**Comment by hoodmane** [comment]
The error is happening inside emscripten glue code. It will be necessary to
track down where in the C source code for append_data the error is being
triggered. It's a confusing message --- it sure looks like that number
should be fine to convert to bigint!
