### ISSUE TITLE
No module named 'lib2to3'

### ISSUE THREAD

**Issue by karthiknadig** [pyodide/pyodide#1640]
```
>>> import yapf
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.8/site-packages/yapf/__init__.py", line 35, in <module>
    from lib2to3.pgen2 import tokenize
ModuleNotFoundError: No module named 'lib2to3'
```

`lib2to3` should be in the standard lib.

**Comment by rth** [comment]
lib2to3 is deprecated since Python 3.10 https://docs.python.org/3/library/2to3.html#module-lib2to3 (see also https://bugs.python.org/issue40360). It's also 1MB in size so it don't think we would want to include it by default in Pyodide. Currently it's removed.

You can however package it as a separate package in a wheel and load it with micropip. Closing but don't hesitate to comment.

**Comment by rth** [comment]
Upstream issue https://github.com/google/yapf/issues/448

**Comment by rth** [comment]
To answer @brettcannon's comment in  https://github.com/pyodide/pyodide/issues/1712#issuecomment-881637287 if this is really a blocker for you, we could consider adding it unvendored from the stdlib, so it could be loaded with `pyodide.loadPackage`. Similarly to what was for distutils (https://github.com/pyodide/pyodide/pull/1543) but maybe not loaded by default. Though in the end I wonder if it wouldn't be simpler to upload it as a separate package to PyPi and load it from there with micropip.

**Comment by brettcannon** [comment]
I don't think this would be a blocker for us, it was more about us asking "why". At worst we would integrate with any code we shipped in-box to care of the missing dependency.

**Comment by tejashapani79** [comment]
> ```
> >>> import yapf
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/lib/python3.8/site-packages/yapf/__init__.py", line 35, in <module>
>     from lib2to3.pgen2 import tokenize
> ModuleNotFoundError: No module named 'lib2to3'
> ```
> 
> `lib2to3` should be in the standard lib.

run this command : sudo apt install 2to3
