### ISSUE TITLE
Memory leak using Node FS API

### ISSUE THREAD

**Issue by blakjak44** [pyodide/pyodide#1643]
We are working on an Electron app that uses a Python server to send image data to the client. After discovering Pyodide, we decided to try running our Python API via Pyodide so that we can just load the data directly from the browser. We know that Pyodide cannot directly access the local filesystem but since we are working in Electron, we can access the Node FS API. 

Our Python API is a single class that wraps the underlying io stream and has several methods that read from that io stream. We were able to successfully run the API inside Pyodide by replacing the `open()` method with a shim that wraps the Node FS API. 

Our problem is that we are running into a `MemoryError` after X number of calls to read from the Python API. I know the docs state that we should be destroying any proxies that have been created when done with them to avoid memory leaks, but I'm a little confused as to the difference between a JSProxy created through `pyodide.create_proxy(bytes(100))` and `pyodide.to_js(bytes(100))`. The former is not accepted by Node's `fs.readSync()`, while the latter is accepted but does not provide a `destroy()` method. Since there is no option to destroy the JS buffer proxy, I just cache the buffer proxy and reuse it for all read calls (which I hoped would prevent any memory leak). 

Here are a few snippets that should illustrate the general workflow. The method calls have been simplified as much as possible:

Python API:
```python
import fs
import pyodide

class FSopen:
    def __init__(self, filename):
        self.filename = filename
        self._fh = fs.openSync(filename)
        self._buffer = memoryview(bytearray(1000))
        self._js_buffer = pyodide.to_js(self._buffer)

    def read(self, size):
        fs.readSync(self._fh, self._js_buffer, size)
        return bytes(self._js_buffer[:size])
```

JS
```javascript
// pyodide initialization

const fileProxy = pyodide.runPython(`FSopen(${filename})`)
const dataProxy = fileProxy.read(1000)
const data = dataProxy.getBuffer().data
dataProxy.destroy()
```

I would have assumed that if I reuse the same JS buffer proxy then there wouldn't be any new memory allocations on successive read calls. Are we doing something obviously wrong or does this look like a bug?

**Comment by hoodmane** [comment]
I don't think what you are doing is quite right (though I would certainly not go so far as to call it "obviously wrong").

You probably will want to use the `getBuffer` API in your FSopen class. I think the following would be better:
```
import fs
import pyodide

class FSopen:
    def __init__(self, filename):
        self.filename = filename
        self._fh = fs.openSync(filename)
        self._buffer = bytearray(1000)
        self._jsproxy_buffer = pyodide.create_proxy(self._buffer)
        self._js_buffer = self._js_buffer_proxy.getBuffer()
		self._jsproxy_buffer.destroy()

    def __del__(self):
		self._js_buffer.release()

    def read(self, size):
        fs.readSync(self._fh, self._js_buffer.data, size)
        return bytes(self._buffer[:size])
```
Your JS code also looks leaky, in general using `PyProxy` is very fraught though I am hoping to change this in v0.18 (see #1607 & #1617). 

Here's a version that should be completely not leaky:
```js
const fileProxy = pyodide.runPython(`FSopen(${filename})`)
const fileProxy_read = fileProxy.read;
const dataProxy = fileProxy_read(1000);
const dataBuffer = dataProxy.getBuffer(); // Need to hold onto dataBuffer so we can release it
const data = dataBuffer.data;
dataProxy.destroy()
// Do stuff
// Free things when you are done!
dataBuffer.release();
fileProxy_read.destroy(); // I know this is gross I'm sorry!
fileProxy.destroy(); 
```

**Comment by blakjak44** [comment]
@hoodmane Ah, I should have read the docs better. I didn't realize I had to use the `getBuffer` call to reference the same memory as the underlying Python buffer. Also didn't occur to me that the `dataBuffer.release` call on the JS side was necessary to free up the allocated memory in the WASM heap. 

Thanks for the help! That did the trick.
