### ISSUE TITLE
Request: bump `decorator` package version

### ISSUE THREAD

**Issue by gzuidhof** [pyodide/pyodide#1644]
Hi Pyodide maintainers :)

I'm writing up an example that uses `networkx` and `matplotlib`.  [It turns out that `networkx` drawing is broken with `decorator` package version 5.0.6](https://stackoverflow.com/questions/66922359/unexpected-error-while-drawing-networkx-graph) (exactly the one installed in Pyodide). Could we bump the version to a later version? The current latest is `5.0.9`.

From what I can tell this package [doesn't require any custom patches](https://github.com/pyodide/pyodide/blob/main/packages/decorator/meta.yaml).

**Comment by rth** [comment]
Hi @gzuidhof ,

Yes, sure. Would you like to make a PR? Meanwhile you should be able to overwrite it with micropip I think.

**Comment by gzuidhof** [comment]
It has since been bumped (6 days ago), closing this issue :)
