### ISSUE TITLE
ImageData.new in python not work

### ISSUE THREAD

**Issue by patrickyyang** [pyodide/pyodide#1652]
I got an error when I run following code in pyodide, Can someone give me some help?

%% py
import numpy as np
from js import ImageData
data = np.ones( (10,10,3), dtype=np.int16 )
data.tobytes()
im = ImageData.new(data.tobytes(), 10, 10)
im

PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 270, in run_async
    coro = eval(mod, self.globals, self.locals)
  File "<exec>", line 5, in <module>
JsException: PythonError: JsException: TypeError: Failed to construct 'ImageData': cannot convert to dictionary.

**Comment by hoodmane** [comment]
The problem is that `ImageData` expects a `Uint8ClampedArray` not a PyProxy. Also, `ImageData` expects four color channels not three, and each channel must be a single byte.
```py
import numpy as np
from js import ImageData
data = np.ones( (10,10,4), dtype=np.int8 )
bytes_proxy = create_proxy(data.tobytes())
bytes_buffer = bytes_proxy.getBuffer("u8clamped")
im = ImageData.new(bytes_buffer.data , 10, 10)
bytes_buffer.release()
bytes_proxy.destroy()
```
Perhaps we should make a utility function to do this.

**Comment by patrickyyang** [comment]
> The problem is that `ImageData` expects a `Uint8ClampedArray` not a PyProxy. Also, `ImageData` expects four color channels not three, and each channel must be a single byte.
> 
> ```python
> import numpy as np
> from js import ImageData
> data = np.ones( (10,10,4), dtype=np.int8 )
> bytes_proxy = create_proxy(data.tobytes())
> bytes_buffer = bytes_proxy.getBuffer("u8clamped")
> im = ImageData.new(bytes_buffer.data , 10, 10)
> bytes_buffer.release()
> bytes_proxy.destroy()
> ```
> 
> Perhaps we should make a utility function to do this.

I use version 0.17.0,  run following code in my own iodide page
```
%% py
import numpy as np
from pyodide import create_proxy
from js import ImageData
data = np.ones( (10,10,4), dtype=np.int8 )
bytes_proxy = create_proxy(data.tobytes())
bytes_buffer = bytes_proxy.getBuffer("u8clamped")
im = ImageData.new(bytes_buffer.data , 10, 10)
bytes_buffer.release()
bytes_proxy.destroy()
```
I got errors
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 270, in run_async
    coro = eval(mod, self.globals, self.locals)
  File "<exec>", line 6, in <module>
AttributeError: getBuffer
```
Is the version mismatch ? and the apis between versions changed quickly ? I'm new to pyodide.

**Comment by hoodmane** [comment]
This code should work in 0.17.0. For instance, it works on the console: https://pyodide-cdn2.iodide.io/v0.17.0/full/console.html

Can you give a minimal example?

**Comment by patrickyyang** [comment]
Yes， It works in 0.17.0. Thank very much, I use the wrong version 0.17.0a2,
