### ISSUE TITLE
Citing Pyodide

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1661]
I think, it would be good to have a way to cite Pyodide in scientific papers. Currently Pyodide is [mentioned in a dozen articles](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=pyodide&btnG=) but without a proper citation, since it doesn't exist.

This would be good both to acknowledge work of maintainers and contributors, particularly those associated with academic institutions. Also for any kind of future funding requests/grants, if there is any, citations is still the standard impact metric with public institutions.

I see two (non mutually exclusive) ways of addressing this,
 - The easiest would be to generate a DOI reference with Zenodo (https://guides.github.com/activities/citable-code/) for instance for the last release
 - We could also write a short paper for some open-access journal, but that's more time consuming.

cc @hoodmane, @dalcde , @joemarshall, @casatir

**Comment by casatir** [comment]
That's a good idea! I vote for the DOI reference. The paper could come with the 1.0 version?

**Comment by teonbrooks** [comment]
Journal of Open Source Software is potentially a good option for this

**Comment by rth** [comment]
The Zenodo DOI is created in https://doi.org/10.5281/zenodo.5135072 . We can indeed write a paper in the future, but for now I think we can close this. Documentation was updated in #1763
