### ISSUE TITLE
[question] Compile Python to a WASM binary

### ISSUE THREAD

**Issue by pranav-bhatt** [pyodide/pyodide#1671]
Since you can run python code using pyodide.runPython(), I was wondering if there was a way to just compile python to a WASM binary outside the browser.

**Comment by hoodmane** [comment]
People have had success using Pyodide in node and deno. In the future we'd like to support this better but for now it requires a bit of adventurousness. We need a LOT of Javascript glue, so it wouldn't ever run as a "pure" wasm module (we can only run on the target `wasm32-unknown-emscripten` not on `wasm32-unknown-unknown`).

**Comment by pranav-bhatt** [comment]
Thanks for the quick response! I think until GC and JIT are properly integrated, this might be the case for a while. Hope that's figured out soon 🤞🏼

**Comment by hoodmane** [comment]
> Hope that's figured out soon 🤞🏼

I would guess some time between 2025 and 2030 for this.
