### ISSUE TITLE
Why the static functions should makeTrunk for calling from pyodide ?

### ISSUE THREAD

**Issue by patrickyyang** [pyodide/pyodide#1676]
I'm porting pygame to pyodide, and I encounter an exception when passing html event to SDL. Like this:
![image](https://user-images.githubusercontent.com/2425235/123937633-f3afbf80-d9c8-11eb-89ad-61b340c21064.png)

I found that the function gets by wasmTable.get(callbackfunc) is a trunk function like this:
```
(func (;43468;) (type 0) (param i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64) (result i64)
    local.get 0
    i32.wrap_i64
    local.get 1
    i32.wrap_i64
    local.get 2
    i32.wrap_i64
    local.get 3
    i32.wrap_i64
    local.get 4
    i32.wrap_i64
    call 16604
    i64.const 0)
```
call 16604 is the original function registered as an event handler.
Then I found that pyodide patch the Binaryen code, and makeThunk for all static functions.
Why pyodide need to export all static functions ? It seems not reasonable.

**Comment by hoodmane** [comment]
Static functions can be called from anywhere via a function pointer. They can be called from a different linked wasm module or from Javascript. If we don't export the static function and someone takes a function pointer, it wouldn't be possible to call it because `call_indirect` goes through the `wasmTable` export list.

**Comment by hoodmane** [comment]
If you need the reasonable function and not the `byn$fpcast-emu$` version, you can use `wasmTable.get(dyncallInvokeMap[func] || func)` from `EM_JS` or `EM_ASM`.

**Comment by patrickyyang** [comment]
Thank you very much! It works!
