### ISSUE TITLE
Linux makefile compile error

### ISSUE THREAD

**Issue by jpedrick** [pyodide/pyodide#1687]
I'm unable to get pyodide to compile on linux. I get the following error:

```
cat src/core/pyproxy.c | emcc -E -C -P -imacros src/core/pyproxy.c -O2 -g -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -I/home/jpedrick/Development/jslicer/pyodide/cpython/installs/python-3.9.5/include/python3.9 - >> src/js/pyproxy.gen.js
<stdin>:3:10: fatal error: 'error_handling.h' file not found
#include "error_handling.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
emcc: error: '/home/jpedrick/Development/jslicer/pyodide/emsdk/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home/jpedrick/Development/jslicer/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -E -C -P -imacros src/core/pyproxy.c -O2 -g -fPIC -Wall -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -I/home/jpedrick/Development/jslicer/pyodide/cpython/installs/python-3.9.5/include/python3.9 -' failed (1)
make: *** [Makefile:106: src/js/pyproxy.gen.js] Error 1
```

I've tried editing the makefile to run this:
```
emcc -E -C -P -imacros src/core/pyproxy.c -O2 -g -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types \
-I/home/jpedrick/Development/jslicer/pyodide/cpython/installs/python-3.9.5/include/python3.9 src/core/pyproxy.c >> src/js/pyproxy.gen.js
```

Which succeeds, but then I get TS errors from pyproxy.gen.js:

```
./tools/dependency-check.sh
npx typescript src/js/pyodide.js \
	--lib ES2018 --allowJs \
	--declaration --emitDeclarationOnly \
	--outDir build
npx: installed 1 in 1.507s
src/js/pyproxy.gen.js(141,1): error TS1128: Declaration or statement expected.
src/js/pyproxy.gen.js(141,23): error TS1005: ';' expected.
src/js/pyproxy.gen.js(141,39): error TS1003: Identifier expected.
src/js/pyproxy.gen.js(141,53): error TS1109: Expression expected.
src/js/pyproxy.gen.js(141,54): error TS1109: Expression expected.
src/js/pyproxy.gen.js(141,55): error TS1005: ')' expected.
src/js/pyproxy.gen.js(141,56): error TS1005: ':' expected.
src/js/pyproxy.gen.js(141,57): error TS1136: Property assignment expected.
src/js/pyproxy.gen.js(141,59): error TS1003: Identifier expected.
src/js/pyproxy.gen.js(141,79): error TS1003: Identifier expected.
src/js/pyproxy.gen.js(141,95): error TS1109: Expression expected.
src/js/pyproxy.gen.js(141,96): error TS1109: Expression expected.
src/js/pyproxy.gen.js(141,97): error TS1005: ')' expected.
src/js/pyproxy.gen.js(141,98): error TS1005: ':' expected.

```

**Comment by hoodmane** [comment]
Maybe try adding `-Isrc/core/`?

**Comment by anyahelene** [comment]
Did you find a solution to this?

**Comment by hoodmane** [comment]
@anyahelene Are you seeing the same problem?

**Comment by anyahelene** [comment]
Yes, but only when building on Ubuntu; I just tried running the build in Docker, and now it works. I probably just had a slightly wrong version of a dependency or something.

(Looks like (when adding `-Isrc/core/` to avoid the `error_handling.h` error) `src/js/pyproxy.gen.js` ends up filled with C code rather than JavaScript, which then causes the other compile error. But it's not that much of an issue when it's easy enough to build with `run_docker`)

**Comment by phorward** [comment]
I think this can be closed then.

**Comment by brianmingus2** [comment]
I am not sure why someone mentioned that I am not a volunteer. In any case, when I do volunteer on software projects, the same standards of quality must be maintained. Ticketing systems are the central point of on-going success. Please don't close tickets if the ticket isn't fixed but must be fixed.

I propose we ask Mozilla for an 8-core build box to attempt to compile all 300,000+ Python packages for Pyodide on an on-going basis. If we need help with that, we could ask the Pyodide inventor for help. CDNJS will accept us if jsDelivr isn't interested. I am sure we can find a sponsor for a single build box for such an important project. 

I was unable to replicate a successful build using WSL2. Can you post your `~/.bash_history` file?

This project is 90% of the way to success. After the build system is polished and we've got all packages that already work prepared, all we have to do is wait for browsers to get faster, CPUs to get faster, and to fix 1-off bugs in various packages that have strange CPython requirements.

- Brian
