### ISSUE TITLE
The script tools/buildf2c does not work anymore

### ISSUE THREAD

**Issue by cugni** [pyodide/pyodide#1694]
Hi there!
I'm trying to learn about this great project (amazing work!), but I have a little problem during the installation when executing the command **sudo ./tools/buildf2c** as described in the [documentation ](https://pyodide.org/en/stable/development/building-from-sources.html).

It seems the URL http://netlib.sandia.gov/cgi-bin/netlib/netlibfiles.tar?filename=netlib/f2c is no longer valid, and it returns 404. I had a hard time finding an alternative link, and the only solution I have found was to download the full f2c page like this. 

```bash
wget -r -p -k https://www.netlib.org/f2c/
mv www.netlib.org/f2c f2c
rm -r www.netlib.org
```
I'm sure there's a better way, but that's what I found. Any suggestion?

**Comment by hoodmane** [comment]
Maybe use `https://www.netlib.org/f2c/src.tgz`? It seems like that is probably the same thing as the original link. If this works for you, a PR to update `tools/buildf2c` would be welcome.

**Comment by rth** [comment]
+1. Alternatively `conda install -c conda-forge f2c` should also workwithout needing to compile anything, at least on x86_64.

**Comment by cugni** [comment]
For some weird reason, https://www.netlib.org/f2c/src.tgz is a tar containing only the subdirectory src 🤷🏻‍♂️ and it misses other files like libf2c.zip. 
As an alternative, we can use ```conda install -c conda-forge f2c``` as @rth  suggested and replace the whole ```buildf2c``` script. It might be drastic, but it is probably easier to maintain than relying on netlibg.org. 
What do you prefer? In both cases, I can do a PR fixing it.

**Comment by rth** [comment]
I would be +1 to replace that whole section by a conda install. The advantage is that it should be mostly cross-plaform https://github.com/pyodide/pyodide/pull/830#pullrequestreview-546619206 So if you could confirm that it works on MacOS that would be great.

**Comment by cugni** [comment]
```conda install -c conda-forge f2c``` works for me, with MacOS 11.4 and an M1 silicon chip, it uses an x86_64 binary but it seems working fine with Rosetta. 
If so, I can still make a PR updating the documentation and removing the build2f script.

**Comment by rth** [comment]
Closing as fixed then.
