### ISSUE TITLE
Dev version: Cannot read property 'loadPackage' of undefined

### ISSUE THREAD

**Issue by oeway** [pyodide/pyodide#1705]
It looks like the dev version doesn't expose the `pyodide` object after calling `loadPyodide` (in web-worker):
```js
importScripts('https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js');
await loadPyodide({ indexURL : 'https://cdn.jsdelivr.net/pyodide/dev/full/' });
await self.pyodide.loadPackage(['micropip']);
```
And the error is: `Cannot read property 'loadPackage' of undefined`.

If I switch to `v0.17.0`, then the same code works.

**Comment by hoodmane** [comment]
We changed it so that `loadPyodide` returns the `pyodide` namespace rather than defining it directly. We are trying to move away from global variables.

**Comment by hoodmane** [comment]
Try saying:
```js
self.pyodide = await loadPyodide({ indexURL : 'https://cdn.jsdelivr.net/pyodide/dev/full/' });
```

**Comment by oeway** [comment]
> Try saying:
> 
> ```js
> self.pyodide = await loadPyodide({ indexURL : 'https://cdn.jsdelivr.net/pyodide/dev/full/' });
> ```

Works! Thanks! It's great that we are moving away from global variables!
