### ISSUE TITLE
Create a pyodide extension for Sphinx

### ISSUE THREAD

**Issue by choldgraf** [pyodide/pyodide#1713]
I think that Pyodide could be an excellent way to show off functionality of many tools and workflows in the Scientific Python ecosystem. One of the barriers to doing this is that each author must figure out the proper way to load the Pyodide JS on their own.

A pattern that I've found useful in the Jupyter Book project is to provide a thin wrapper around a JS package via a Sphinx extension. For example, [the sphinx-thebe package](https://sphinx-thebe.readthedocs.io/) is a relatively light wrapper around [the `thebe.js` package](https://thebe.readthedocs.io), and loads the proper JS on pages with code cells to make them "executable" when people click a button.

If something similar existed for Pyodide, this could be a great way to bring the package into the Sphinx ecosystem with minimal energy barrier for authors. (it would also be a great way to bring Pyodide into the Jupyter Book ecosystem 🙃).

Just thought I'd share this pattern and voice my enthusiasm for something like this, in case others thought it was a good idea!

**Comment by jtpio** [comment]
xref https://github.com/jupyterlite/jupyterlite/issues/149 which sounds similar

**Comment by rth** [comment]
We are also very much interested in this. Also something that could allow running sphinx-gallery examples would be great https://github.com/pyodide/pyodide/issues/44

Beyond the implementation, another thing that's not necessarily obvious is how to make the dev version of the package available to this sphinx extension (e.g. when running the build with ReadTheDocs as one of the deployment methods),
 - if the package is pure Python, it means the wheel would need to be generated as part of sphinx build and put into the static sphinx folder. That's doable but maybe a bit unexpected by the user.
 - if the package has C extensions, right now it would be non trivial and time consuming to build it at each DOC deployment. We clearly need to improve that situation.

cc @astrojuanlu

**Comment by astrojuanlu** [comment]
Thanks for the ping @rth. For the record I agree with @choldgraf that having a Sphinx extension would be great. However, I don't fully understand the packaging problems @rth mentions. When you say "the dev version of the package", do you mean pyodide itself, or something else? On the other hand, what makes Read the Docs special?

**Comment by rth** [comment]
> When you say "the dev version of the package", do you mean pyodide itself, or something else?

To give a concrete example let's say you are using this plugin with pandas. When  building docs for pandas 1.3.0 one would need that version of pandas that runs in Pyodide. Pyodide may package some version of pandas (or the package in question) but maybe not exactly the right one. So it would have to be built. Which currently should be doable for pure python packages (by generating a wheel) but would be much harder for packages with C extensions (need to use the Pyodide build setup).

> what makes Read the Docs special?

It was more an example of an environment were it would likely be difficult/not possible to use the current Pyodide build system with Docker images. Not that it makes sense to have such long running builds to deploy docs anyway. Just to say that our build approach would also need to be improved for this use case.

**Comment by abitrolly** [comment]
An extension that can handle the basic scenario without pandas plugins would already be a huge win.

**Comment by psychemedia** [comment]
The https://github.com/jupyterlite/jupyterlite-sphinx/ extension _"provides utilities for embedding [JupyterLite](https://jupyterlite.readthedocs.io/) in your documentation"_. This includes the ability to embed an executable RetroLab style notebook in a Sphinx book page ([example](https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/retrolite.html)).

**Comment by agriyakhetarpal** [comment]
https://github.com/jupyterlite/jupyterlite-sphinx has indeed been developed for this purpose and is fairly actively maintained; we can close this 🎉 While the problem of "dev" versions of packages hasn't been fully figured out yet, we do have methods of shipping additional Pyodide wheels with JupyterLite and several packages being able to build WASM wheels out-of-tree in their own CI, so we can consider that problem as "solved" in some ways.
