### ISSUE TITLE
The --port/-p option to run_docker has no effect

### ISSUE THREAD

**Issue by eulertour** [pyodide/pyodide#1722]
Passing `-p` or `--port` to the run_docker script has no effect and looking at the script, the variable configuring the exposed port isn't used.
https://github.com/pyodide/pyodide/blob/1b74f97d2178aed83b8895c207526ffe5172ee4e/run_docker#L90

**Comment by hoodmane** [comment]
Looks like I dropped it in 6fb385bc8c2d05cd38c7b0fb07a76b7932ba1e8f.
https://github.com/pyodide/pyodide/commit/6fb385bc8c2d05cd38c7b0fb07a76b7932ba1e8f#diff-88c1d955d248a000838d97d01d75dfa01a639b97bb22276a61611ada7aa14ddfL95

You could open a PR to put it back in.
