### ISSUE TITLE
Add docs for using Pyodide from Node

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1725]
We would need to add some docs on how to use Pyodide with Node. For now probably the usage would involve,
 - npm installing Pyodide
 - downloading the archive of packages
 - pointing to the folder with packages when loading Pyodide

Then we can see if some caching https://github.com/pyodide/pyodide/issues/14#issuecomment-875116949 could making it into this release.

@hoodmane Can we decide under which name we are going to upload the npm package https://github.com/pyodide/pyodide/discussions/1403#discussioncomment-972302 ?

**Comment by keverw** [comment]
Yeah, I was here looking how to use with Node! That would be nice! I'm taking a class for college where we use Python in the fall while I've already have experience with programming and a huge fan of TypeScript/Node ecosystem so being able to use Python code in my Node/React projects be nice! I know Python has a huge module ecosystem too, so sounds like the best of both worlds!

**Comment by hoodmane** [comment]
I'm good with putting it at `pyodide`. It seems that a lot of packages have the main package at `some_name` and side modules at `@some_name/submodule`.

**Comment by rth** [comment]
Let's do that then.
