### ISSUE TITLE
Using TypeScript in the JS library

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1729]
In https://github.com/pyodide/pyodide/pull/1728/files#r673686098 @stefnotch mentioned,

> I wonder if someday it would be worthwhile to use Typescript. Currently, this doesn't get recognized by Visual Studio Code.

+1 for Typescript from me. Right now the iteration cycle of build core, bundle js, run selenium tests is quite slow. 

It would certainly have made refactoring in https://github.com/pyodide/pyodide/pull/1700 easier I think. We have few JS tests (independent of the main selenium test suite). It's also difficult to add them, because there is a lot of dependencies between the JS/C/Python modules (we should try to reduce dependencies, maybe use more mocking in JS tests, but it's not obvious). Right now, for instance if during refactoring package loading gets broken somehow, all you get is an ImportError in selenium tests which is not really helpful.

So if we could detect at least the most obvious issues with Typescript when bundling the JS that would be useful I think. It's also what was done in https://github.com/pyodide/pyodide/pull/792.

Maybe something we could experiment for 0.19.0

**Comment by bollwyvl** [comment]
Another nice part of this, as would pertain to `packages.json`: it's quite straightforward to generate JSON Schema from TypeScript typings and vice versa, whichever direction makes sense. I'm personally in favor of checked-in JSON as the source of truth, but _also_ checking in generated, `prettier`ed `.d.ts` files can be very nice for observing the impact of a schema change.

**Comment by hoodmane** [comment]
I've been planning to work on this, just haven't gotten around to it yet. The current system is clearly not sufficient.

**Comment by hoodmane** [comment]
Closed by #2133. (We still don't have a schema for `packages.json`, I will open that as a separate issue.)
