### ISSUE TITLE
ModuleNotFoundError: No module named 'ctypes'

### ISSUE THREAD

**Issue by dynamicwebpaige** [pyodide/pyodide#1735]
Greetings, folks! 👋 

Was testing out some of the features in `pandas` with JupyterLite / Pyodide, and ran into the following issue when attempting to use `pd.read_clipboard()`. Importing the library works as expected, just with a gnarly warning about not being able to import the `lzma` module.

Are there any known workarounds for this?

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-861af318b71b> in <module>
----> 1 df = pd.read_clipboard()

/lib/python3.8/site-packages/pandas/io/clipboards.py in read_clipboard(sep, **kwargs)
     33         raise NotImplementedError("reading from clipboard only supports utf-8 encoding")
     34 
---> 35     from pandas.io.clipboard import clipboard_get
     36     from pandas.io.parsers import read_csv
     37 

/lib/python3.8/site-packages/pandas/io/clipboard/__init__.py in <module>
     44 
     45 import contextlib
---> 46 import ctypes
     47 from ctypes import c_size_t, c_wchar, c_wchar_p, get_errno, sizeof
     48 import os

ModuleNotFoundError: No module named 'ctypes'
```

**Comment by hoodmane** [comment]
The ctypes issue is fixed on the development branch: #728. You can use the development copy of the code for this.

However, `pd.read_clipboard()` is not going to work even so. It now raises the following error:
```py
pandas.io.clipboard.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
```
Pandas feature detects the system here:
https://github.com/pandas-dev/pandas/blob/9c0a1ebec6028d98e47c5664fd2cad173bfd9c21/pandas/io/clipboard/__init__.py#L505
and there is no support for Emscripten.

One could implement support on top of the [clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) API, but here there are a few hurdles: 
* browser support for the clipboard API is inconsistent (synchronous read from the clipboard is only supported in Safari, asynchronous read from clipboard is supported by Safari and Chrome but not Firefox). 
* accepting that Firefox support is missing, to get chrome support you must use async clipboard read. The `pd.read_clipboard` is a synchronous API, so we need support for blocking on asynchronous calls (see #1503).

**Comment by hoodmane** [comment]
See also: https://caniuse.com/?search=clipboard

**Comment by agriyakhetarpal** [comment]
Hi @dynamicwebpaige, I think we can close this – since #1656 has been a part of Pyodide since version 0.18.0a1 and later. Thanks for filing the issue! Please feel free to ask us in case there are more things to ask for.
