### ISSUE TITLE
Release 0.18

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1738]
An issue to track what's left to do on the 0.18 release. I updated https://github.com/pyodide/pyodide/milestone/5

I think we are are close to getting there. Personally I'd like to merge https://github.com/pyodide/pyodide/pull/1700 for the alpha release, and it would probably be good to get https://github.com/pyodide/pyodide/pull/1733 there as well.

Otherwise for https://github.com/pyodide/pyodide/pull/1573 I'll be mostly offline the next 3 days, and since it still needs a review that would mean delaying the alpha or postponing it to the 0.19 release I think (unless we find someone else to review it).  If we go with the second option and we don't create this 0.17.0a2 release today @hoodmane feel free to tag the alpha release in the next few days (or I can do it Tuesday).

So assuming we make the alpha in the coming days, that would likely mean the final 0.18.0 release beginning of August.

**Comment by hoodmane** [comment]
I think it's fine to hold #1573 over for 0.19.0. It is a significant change to the execution model, better not to rush review. I should probably at least merge main on these PRs we're holding over for a long time, there is some risk that I just forget what they are supposed to be doing.

**Comment by hoodmane** [comment]
I'm going to be traveling in the next couple of days too. Let's try to get an 0.18.0 alpha out today.

**Comment by hoodmane** [comment]
I do have one more feature that I would like to get into 0.18.0 which is a resolution of #1529. I have an implementation, working on adding tests, will open a PR soon.

**Comment by rth** [comment]
Sounds good.

**Comment by hoodmane** [comment]
I think I successfully released 0.18.0a1.

**Comment by rth** [comment]
Great, thanks @hoodmane!

**Comment by rth** [comment]
How about a final release on August 3rd @hoodmane ? Personally I'll have more time for Pyodide next week.

Also could you please add me (`ryurchak`) as a co-maintainer to https://www.npmjs.com/package/pyodide I'd like to look into what's necessary for pushing the alpha release.

**Comment by hoodmane** [comment]
August 3rd sounds good.

**Comment by phorward** [comment]
Nice to hear, guys! 👍

**Comment by leopsidom** [comment]
I'm seeing requests for more regular releases being discussed here: https://github.com/pyodide/pyodide/issues/1727. I know we're pretty close to the official release date, but just wondering if there will be another alpha release to include recent bug fixes to be shipped with 0.18.0 so we can test it out. Currently I'm trying to test on `a1` but blocked on a few issues (some already had a fix but not shipped with `a1`). I'm not quite clear about the releasing effort, so not sure if this makes sense.

**Comment by hoodmane** [comment]
Perhaps the best solution would be to release an a2 as soon as #1764 is fixed and then plan to release 0.18.0 a week from the a2 release unless more issues arise.

**Comment by leopsidom** [comment]
> Perhaps the best solution would be to release an a2 as soon as #1764 is fixed and then plan to release 0.18.0 a week from the a2 release unless more issues arise.

+1 This sounds good to me.

**Comment by rth** [comment]
Thanks for testing this pre-release @leopsidom !

> Perhaps the best solution would be to release an a2 as soon as #1764 is fixed and then plan to release 0.18.0 a week from the a2 

I think I would still prefer to release 0.18.0 as planned on Tuesday, because as long as it's not done we can't merge any of the new features. Then if need be we can always make bug fix releases 0.18.1, 0.18.2 etc from the 0.18.X branch. Delaying the release with another pre-release is really for the case where we are not confident in new changes (which is not the case here, I think), otherwise for the occasional bug that's what bug fix releases are for..

Once the issues you reported are fixed, you will also be able to test it with the dev CDN url (replace version by `dev`).

**Comment by hoodmane** [comment]
I am happy to go with what @rth says; he certainly knows better than I do.

**Comment by leopsidom** [comment]
> Then if need be we can always make bug fix releases 0.18.1, 0.18.2 etc from the 0.18.X branch.

This sounds good. Thanks for clarifying. I'm okay to move forward with `dev` and switched to 0.18.0 once it's released.

**Comment by hoodmane** [comment]
@rth Should I go ahead with this?

**Comment by rth** [comment]
The only thing that I'm a bit concerned about is that if users start to seriously use Pyodide in Node, they will continually re-download the same packages from PyPi / CDN which is not very nice for those CDN providers. There is a PR to add local caching in Node in https://github.com/pyodide/pyodide/pull/1776 but I still needs to spend some time tomorrow debugging the remaining issues. On one side it's not ideal to add a feature that wasn't in the alpha, on the other the current Node support without caching might be a bit suboptimal.

What do you think? I'm open to both going ahead with the release and waiting a day or so to finish that PR.

**Comment by rth** [comment]
Missed the notification about the release PR. So then it's fine, thanks for tagging 0.18.0 :)

**Comment by hoodmane** [comment]
Perhaps we can do `0.18.1` for that. But we still need to release the node package v0.18.0, the pyodide-build v0.18.0, and the docker prebuilt image v0.18.0

**Comment by rth** [comment]
Yes, looking into it now.

**Comment by rth** [comment]
> But we still need to release the node package v0.18.0, the pyodide-build v0.18.0, and the docker prebuilt image v0.18.0

Done

**Comment by hoodmane** [comment]
@rth Should this be closed as finished?
