### ISSUE TITLE
installing umap-learn in Pyodide on ObservableHQ

### ISSUE THREAD

**Issue by cornhundred** [pyodide/pyodide#1739]
Hi, I am having trouble installing and importing umap-learn in Pyodide. The link is to an ObservableHQ notebook 

https://observablehq.com/@cornhundred/pyodide-umap

The code in the notebook is:

```
umap = {
  
// install umap-learn
py`
import micropip
micropip.install(['umap-learn==0.5.1'])
import umap
`
  
var umap = py`
import umap
umap`


return umap
}
```

and the error is 

```
umap = PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 270, in run_async
    coro = eval(mod, self.globals, self.locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'umap'
```

**Comment by rth** [comment]
`micropip.install` is async so you either need to `await` it (or just wait a bit) before trying to use the installed modules. In this case it wouldn't work anyway because it would produce,
```
ValueError: Couldn't find a pure Python 3 wheel for 'umap-learn==0.5.1'
```
which is in addition currently blocked by numba not being supported (https://github.com/pyodide/pyodide/issues/621)

**Comment by cornhundred** [comment]
Thanks @rth for the help. Let me know if you want me to close the issue otherwise I can leave it open until #621 is resolved and potentially allows installation of umap-learn.

**Comment by rth** [comment]
Yes, let's close this issue while it's blocked by https://github.com/pyodide/pyodide/issues/621 in any case. umap-learn is a pure Python package, so once,
 - https://github.com/pyodide/pyodide/issues/621 is resolved
 - and the authors upload a wheel on PyPi

it should be installable with micropip.
