### ISSUE TITLE
Mailing List Phishing?

### ISSUE THREAD

**Issue by jmsmdy** [pyodide/pyodide#1754]
Someone appears to be using the pyodide mailing list for spam / phishing. Not sure if there is a way to avoid this, but figured I'd raise an issue.

Recent examples:

![Screenshot_20210727-231113](https://user-images.githubusercontent.com/47697814/127273641-48c5db01-3ec4-42ed-958f-acf7261e2260.png)

![Screenshot_20210727-231140](https://user-images.githubusercontent.com/47697814/127273653-41c7500c-f246-4def-acfd-9aa18adf2aee.png)

**Comment by hoodmane** [comment]
Probably we should accept posts only by specific approval.

**Comment by hoodmane** [comment]
Okay I set the mailing list to require explicit approval of messages. We can whitelist anyone who posts real content. I think we want to keep most conversation in issue trackers anyways.

**Comment by rth** [comment]
It's unfortunate that the spam filter doesn't seem to be working well. I already did require moderation for senders outside of the mailing list earlier but they apparently sign up. Moderation for everyone should help indeed.
