### ISSUE TITLE
Gzip encoding issue with jedi in v0.18.0a1

### ISSUE THREAD

**Issue by leopsidom** [pyodide/pyodide#1764]
It seems I can't load jedi package with v0.18.0a1. Steps to reproduce:

```
pyodide = await loadPyodide({ indexURL: "https://cdn.jsdelivr.net/pyodide/v0.18.0a1/full" })
await pyodide.loadPackage(['jedi'])
```

I'm getting this error with `loadPackage`:

> Couldn't load package from URL https://cdn.jsdelivr.net/pyodide/v0.18.0a1/full/jedi.js SyntaxError: illegal character U+001F

**Comment by rth** [comment]
Thanks for the report. It's an encoding problem. `jeudi.js` returns a gzip encoded stream while plain text is expected. 

This might have something to do with the fact that currently we deploy gzip encoded assets and let the CDN decode them. But then the `ContentEncoding` headers look correct, both in S3
```bash
$ aws s3api head-object  --bucket <pyodide-bucket> --key v0.18.0a1/full/jedi.js
{
    "AcceptRanges": "bytes",
    "LastModified": "Sun, 25 Jul 2021 00:35:41 GMT",
    "ContentLength": 38993,
    [..]
    "CacheControl": "max-age=30758400, immutable, public",
    "ContentEncoding": "gzip",
    "ContentType": "application/javascript",
    "Metadata": {}
}
```
and in the HTTP headers returned by the CDN.

Also I don't understand why this fails for `jedi.js` and works for other packages. 
I can also reproduce with the dev deployment. I'll need to investigate more.

**Comment by rth** [comment]
OK the issue is that we are for some reason deploying a twice gzip compressed file. So this line https://github.com/pyodide/pyodide/blob/5264b687df7433b8cff244c0ddb20a2efa1013ad/.circleci/config.yml#L255 doesn't work as expected.

**Comment by leopsidom** [comment]
> fails for jedi.js and works for other packages

Yep this sounds correct. I can see pandas being loaded correctly.

**Comment by rth** [comment]
This should be fixed with the latest dev deployment. See for instance the [dev REPL](https://pyodide.org/en/latest/console.html).

**Comment by leopsidom** [comment]
Thanks. Tested in `dev`, I think it's working now.
