### ISSUE TITLE
Pyodide blog posts

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1766]
I think it would be nice to be able to post blog posts about Pyodide somewhere, both for release highlights for more detailed discussions about new features. 

For the last release we did [release highlights](https://pyodide.org/en/stable/project/release-notes/v0.17.0.html#release-notes) as part of the documentation and that works for this use-case. However documentation would be less suitable for more focused and less formal discussions about some features.

There are multiple possibilities,
 1. using some third party platform with a custom domain name. For instance https://blog.jupyter.org/ does this with Medium. This requires a paid subscription I think.  I'm not really fond of Medium but maybe that's the simplest solution.  There might be also some alternative newer platforms for technical blog posts. 
 2. Using static site generator (e.g. [pelican](https://github.com/getpelican/pelican) or [Jekyll](https://github.com/jekyll/jekyll)) and deploy it with Github Pages or Netlify. It's slightly more work to setup, and in particular to chose a reasonably looking theme. 

Both could probably work.

Again there is no pressure to post anything there, but it would be good to have a place to do it, if we decide that we want to.

**Comment by gzuidhof** [comment]
I would propose to use [hugo](https://gohugo.io/) as a static site generator for simplicity sake (it's a single binary instead of a Python/Ruby/JS lib with a bunch of dependencies), and to host it on Github Pages (let's not rely on Medium).

Alternatively we could consider [Docusaurus](https://docusaurus.io/) (it's really plug and play in my experience and it's standard theme looks good). Here's an [example](https://sunderjs.com/blog) of a rather empty blog for one of my projects.

**Comment by rth** [comment]
Thanks for the input! Hugo is certainly a possibility as well. In my limited experience of static site generators, as soon as you need to do something a bit customized the implementation language does have an impact. At least that was my experience with Jekyll which made me switch to pelican. At the time I didn't chose hugo as I wasn't keen on having to deal with Go as well. But maybe that's not a concern for basic blogging sites. And it's true that it would likely have a larger choice of themes and plugins being more popular. How was your experience with it?

**Comment by gzuidhof** [comment]
Hugo has the benefit that you don't end up writing Go (you should never compile hugo yourself, you just download a binary), any customization comes from the theme or your own config. I would propose to pick a theme from their website and not customize it too much. Hugo can sometimes definitely be a bit too powerful for its own good, but if you stick with a pre-built theme that shouldn't be an issue.

Hugo makes it pretty simple to inline some custom code if you want, I was able to embed starboard notebooks fairly simply (see example [blog post with embedded notebooks](https://guido.io/posts/testing-notebooks/) as example).

So if you want to embed interactive examples, you would use something like this inline in your markdown blog post content:

```html
<!-- has to be included once, this loads the js file for the starboard-embed element -->
{{< starboardwrap >}}

{{< starboardembed >}}
# %% [python]
import matplotlib.pyplot as plt

plt.plot([1,2,3,4,5]);
plt.show();
{{< /starboardembed >}}
```

I'm sure that any static site generator will be able to do something similar. In hugo it's about [6 lines of shortcodes](https://github.com/gzuidhof/gzuidhof.github.io/tree/master/guido.io/layouts/shortcodes)

**Comment by rth** [comment]
That sounds very nice indeed!

**Comment by rth** [comment]
Any thoughts on this @hoodmane ?

**Comment by madhur-tandon** [comment]
May I suggest https://balajis.com/set-up-a-paid-newsletter-at-your-own-domain/ 
One can even use Ghost Pro for a 3-click process instead.

**Comment by rth** [comment]
Thanks everyone for feedback! In the end I went with Hugo deployed via Netlify: https://github.com/pyodide/pyodide-blog/pull/1 Using a static site generator (as opposed to a platform) gives us a bit more control over what we can do with it, confidence that content is not going to be paywalled in the future (e.g. Medium) and would allow review and iteration on posts using Github.
