### ISSUE TITLE
Building pyodide: patches for emsdk/emscripten not applicable

### ISSUE THREAD

**Issue by gzuidhof** [pyodide/pyodide#1769]
I gathered the guts to build Pyodide on my Mac from scratch, it looks like everything builds as it should, the only issue is the patch in `emsdk/patches/fix_emscripten_dylink.patch` which get applied to `/emsdk/emsdk/upstream/emscripten/tools/shared.py`. 

The second patch in that file 

```
diff --git a/emsdk/upstream/emscripten/tools/shared.py b/emsdk/upstream/emscripten/tools/shared.py
index 74666ee..3d5657b 100644
--- a/emsdk/upstream/emscripten/tools/shared.py
+++ b/emsdk/upstream/emscripten/tools/shared.py
@@ -844,7 +844,7 @@ class JS(object):
       else:
         return 'Module["dynCall_%s"](%s)' % (sig, args)
     else:
-      return 'wasmTable.get(%s)(%s)' % (args[0], ','.join(args[1:]))
+        return 'dynCall("%s",%s,[%s])' %(sig,args[0],','.join(args[1:]))
 
   @staticmethod
   def make_invoke(sig, named=True):
```

does not match the [file in version 2.0.16](https://github.com/emscripten-core/emscripten/blob/2.0.16/tools/shared.py#L732-L744), the patch replaces line 844, whereas it should be around line 744 (if I'm reading the diff correctly).

I have attempted a fix by forcing emsdk to be the same version (by adding `cd emsdk && git fetch --all --tags && git checkout tags/$(PYODIDE_EMSCRIPTEN_VERSION)` to the make file), but that didn't make a difference.

It's probably just me missing something obvious, and ideas what I'm doing wrong?

**Comment by hoodmane** [comment]
The line numbers are not exactly right. If you look at `build-core` it shows that a bunch of hunks are applied at small offsets:
```sh
patching file emsdk/upstream/emscripten/emcc.py
patching file emsdk/upstream/emscripten/src/library.js
Hunk #1 succeeded at 3502 (offset -247 lines).
patching file emsdk/upstream/emscripten/src/runtime_init_table.js
patching file emsdk/upstream/emscripten/tools/shared.py
Hunk #1 succeeded at 741 (offset -103 lines).
patching file emsdk/upstream/emscripten/src/library_dylink.js
Hunk #2 succeeded at 821 (offset 57 lines).
Hunk #3 succeeded at 864 (offset 57 lines).
patching file emsdk/binaryen/src/passes/FuncCastEmulation.cpp
Hunk #1 succeeded at 171 (offset 1 line).
```

**Comment by gzuidhof** [comment]
I see, this is the issue I'm running into (it can't find the file to patch):

```
$ cat patches/*.patch | patch -p1
patching file emsdk/upstream/emscripten/emcc.py
missing header for unified diff at line 39 of patch
can't find file to patch at input line 39
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.17.1
|
|diff --git a/emsdk/upstream/emscripten/src/library.js b/emsdk/upstream/emscripten/src/library.js
|index 2990646..517fc33 100644
--------------------------
File to patch: 
```
I get prompted for the file to patch

**Comment by rth** [comment]
Probably the patch tool is not exactly the same. Looks like  it works with warning on Linux when the line do not match exacly but fails on Mac. What's the output of,
```
patch --version
```
? For me it's `GNU patch 2.7.6`

**Comment by gzuidhof** [comment]
Ah, let me try to switch to GNU patch. Here's mine:

```
$ patch --version
patch 2.5.8
Copyright (C) 1988 Larry Wall
Copyright (C) 2002 Free Software Foundation, Inc.

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

written by Larry Wall and Paul Eggert
```

**Comment by rth** [comment]
patch 2.5.8 was released [12 years ago](http://git.savannah.gnu.org/cgit/patch.git/refs/tags), so imagine you would need a newer version. You can install 2.7.6 on Mac from [conda-forge](https://anaconda.org/conda-forge/patch) I think,
```
conda install -c conda-forge patch
```

**Comment by gzuidhof** [comment]
It is what Tim Cook decided to ship with my OS.. Anyway here's the steps I used to fix it:

```
brew install gpatch
sudo cp /usr/local/opt/gpatch/bin/patch /usr/local/bin/patch
```

Thank you for the help!
