### ISSUE TITLE
Convert (JPEG) PIL image to NumPy array

### ISSUE THREAD

**Issue by boisgera** [pyodide/pyodide#1781]
Hi everyone!

I am having issues with the PIL Image to NumPy array conversion when the original image comes from a JPEG file. The code

    from PIL import Image
    import numpy as np
    
    image = Image.open("image.jpg")
    array = np.array(image)

generates an array whose shape is `()` and dtype is `object`, instead of something like `(480, 640, 3)` and `dtype('uint8')`.

The complete executable example is available here: https://starboard.gg/nb/ntZSsIp

Any idea what the issue could be?

Cheers,

SB

**Comment by boisgera** [comment]
Seems that the same issue occurs with [the Grace Hopper example code from Matplotlib](https://matplotlib.org/stable/gallery/images_contours_and_fields/image_demo.html):

    import matplotlib.pyplot as plt
    import matplotlib.cbook as cbook
    with cbook.get_sample_data('grace_hopper.jpg') as image_file:
        image = plt.imread(image_file)

    fig, ax = plt.subplots()
    ax.imshow(image)
    ax.axis('off')  # clear x-axis and y-axis
    fig.show()

**Comment by hoodmane** [comment]
Well `"__array_interface__" in image` returns `True` but `image.__array_interface__` throws an error:
```
PythonError Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 276, in run_async
    res = eval(last_expr, self.globals, self.locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/site-packages/PIL/Image.py", line 689, in __array_interface__
    new["data"] = self.tobytes()
  File "/lib/python3.8/site-packages/PIL/Image.py", line 731, in tobytes
    self.load()
  File "/lib/python3.8/site-packages/PIL/ImageFile.py", line 259, in load
    raise OSError(
OSError: image file is truncated (53071 bytes not processed)
```

**Comment by hoodmane** [comment]
Something seems to be going mysteriously wrong inside the Jpeg decoder.

**Comment by boisgera** [comment]
> Something seems to be going mysteriously wrong inside the Jpeg decoder.

Yes, I checked that the same process applied to a PNG file works as expected.
