### ISSUE TITLE
16.0.0 are no longer available in jsdeliver

### ISSUE THREAD

**Issue by cedric05** [pyodide/pyodide#1782]
below release `https://cdn.jsdelivr.net/pyodide/v0.16.0/full/pyodide.js` is no longer available. 
i don't see them in npmjs.com.

what is the easiest way to get those files, we are `0.16.0` and upgrading to `0.17.0` (has some api changes, also it is also no longer available in npmjs.com) 

should i plan copy or host above packages from this release onwards? 

------
fyi, we are now trying to migrate to `0.18.0`+

**Comment by cedric05** [comment]
@hoodmane @mdboom 

i tried downloading these https://github.com/pyodide/pyodide/releases/download/0.17.0/pyodide-build-0.17.0.tar.bz2

i'm not completely sure which files are required for basic python installation (it is whooping 170MB). which files do i need to just load basic python running in browser? (so that we will host them our own)

**Comment by cedric05** [comment]
closing this as 0.16.1 (0.16.0 is not) is available.

**Comment by jimaek** [comment]
https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js This is the legacy format that stopped getting updated years ago.

The new and auto-updated format that pulls from NPM is this https://cdn.jsdelivr.net/npm/pyodide/
Or if you pull directly from Github https://cdn.jsdelivr.net/gh/pyodide/pyodide@0.16.0/

**Comment by rth** [comment]
Wait @jimaek even for custom CDN endpoints? We are not deploying to NPM nor Github, but to an S3 which is then mirrored by JsDelivr..

@cedric05 Yes, that is normal 0.16.0 does not exist as indicated in the release notes https://github.com/pyodide/pyodide/releases/tag/0.16.0 Please use 0.16.1 instead.

Not to be confused with https://www.jsdelivr.com/package/npm/pyodide which is the NPM package for Pyodide available only since 0.18.0. This is completely unrelated to Python packages built with Pyodide available via https://cdn.jsdelivr.net/pyodide/v0.18.0/full/

**Comment by rth** [comment]
>  which files do i need to just load basic python running in browser? (so that we will host them our own)

See the files that are loaded by the [REPL](https://pyodide.org/en/stable/console.html) (using dev tools).

**Comment by jimaek** [comment]
Indeed, sorry about that :) I just saw a trivial mistake most people make and wanted to help.

Yes in your case you have a custom endpoint and the same rules dont apply there.

**Comment by rth** [comment]
That works. Also thanks for supporting Pyodide with JsDelivr @jimaek  !

**Comment by cedric05** [comment]
i were able to migrate to 18.0.0 (latest yet). issue has been resolved.
but i still think old versions should be available in npm (not just jsdeliver)

**Comment by rth** [comment]
> but i still think old versions should be available in npm (not just jsdeliver)

There was no npm Pyodide package release prior to 0.18.0 so there is nothing to make available there.
