### ISSUE TITLE
fetch -- json displays as [Object Object] while text displays correctly [0.18.0]

### ISSUE THREAD

**Issue by leopsidom** [pyodide/pyodide#1783]
Trying to run fetch in the REPL, it seems `.json` and `.text` are displaying inconsistently:

```
>>> from js import fetch
>>> todo = await fetch('https://jsonplaceholder.typicode.com/todos/1')
>>> await todo.text()
'{\n  "userId": 1,\n  "id": 1,\n  "title": "delectus aut autem",\n  "completed": false\n}'
>>> todo = await fetch('https://jsonplaceholder.typicode.com/todos/1')
>>> await todo.json()
[object Object]
```

Is this expected or an issue ?

Edit:

Hmm it seems if I do: 

```
from js import JSON
JSON.stringify(await todo.json())
```

It displays correctly as:
> '{"userId":1,"id":1,"title":"delectus aut autem","completed":false}'

**Comment by leopsidom** [comment]
Okay I think I understand the reason. It's because `await todo.json()` returns a JsProxy, and `repr` of `JsProxy` is   `[object Object]`. Wonder if it makes sense to have a best effort conversion here: https://github.com/pyodide/pyodide/blob/a4aa23a04099bb472110e127ceda70b3d58897e9/src/py/_pyodide/console.py#L474

**Comment by hoodmane** [comment]
It is pretty hard because the result of `await todo.json()` is just some random Javascript object. It is unfortunate that `toString` does such a lousy job for these but it's not at all clear whether we can do better in general (or if we should try). If you have a suggestion that works decently in practice we could potentially use it in our `console.html`.

**Comment by leopsidom** [comment]
Maybe we can automatically detect if an object is `JxProxy` and then convert it to python object if it is ? I'm seeing pyodide has a `toPy` API but it seems it's not accessible in python. When I did `from pyodide import toPy`, it says cannot import. Is it possible to expose the API to python ? I think in this way, it will be at least be possible for people to convert the object to python if they wanted to. Not sure if there are any limitations on this though.

**Comment by hoodmane** [comment]
In Python, `to_py` is a method on `JsProxy`: 
https://pyodide.org/en/stable/usage/api/python-api.html#pyodide.JsProxy.to_py

**Comment by leopsidom** [comment]
Wow, nice. Not aware of that. I need to read more about the documentation :)
