### ISSUE TITLE
setInterruptBuffer is undefined [0.18.0]

### ISSUE THREAD

**Issue by leopsidom** [pyodide/pyodide#1795]
The `setInterruptBuffer` API seems to be undefined in 0.18.0.

Reproduce step:
1. go to REPL: https://pyodide.org/en/stable/console.html
2. open browser console, and type `pyodide.setInterruptBuffer`

It returns undefined.

The API is available on 0.17.0: https://pyodide.org/en/0.17.0/console.html

```
pyodide.setInterruptBuffer
ƒ (buffer){Module.interrupt_buffer=buffer;if(buffer){_PyPyodide_SetPyodideCallback($0)}else{_PyPyodide_SetPyodideCallback(0)}}
```

**Comment by hoodmane** [comment]
Indeed, thanks. It is a bootstrap / initialization order issue. I guess we should update the test to use the public entrypoint too.

**Comment by leopsidom** [comment]
Thanks. Do you know if there will be a patch release (e.g. 0.18.1) to fix the issue ?

**Comment by alexmojaki** [comment]
Just want to add what @hoodmane told me elsewhere that I didn't know: `pyodide._module.setInterruptBuffer` works. Happy to now be using 0.18!

**Comment by leopsidom** [comment]
Wow, great to know that. Thanks @alexmojaki for the comment.

**Comment by hoodmane** [comment]
> Do you know if there will be a patch release (e.g. 0.18.1) to fix the issue?

Since you both are interested in it, it seems like it would make sense to make a patch release for this.
