### ISSUE TITLE
How can I get the HEAP address (ptr) of a python variable?

### ISSUE THREAD

**Issue by daoxian** [pyodide/pyodide#1802]
in python:
a = 'hello'

in Javascript, I want something like:
let ptr = pyodide._module.__PyMem_FindSymbol_('a');

Is this possible?

**Comment by hoodmane** [comment]
The easiest way is `id(a)` in python. If you have a pyproxy e.g., from `let
proxy = pyodide.globals.get("a")` then you can do `proxy.$$.ptr` though
this could change without warning in future versions.

**Comment by hoodmane** [comment]
Closed as answered.
