### ISSUE TITLE
warning: your installed python is incomplete

### ISSUE THREAD

**Issue by pnsvk** [pyodide/pyodide#1821]
My heart-felt thanks to the project / effort / contributors as a whole.. 

Would like to bring to your notice that I keep seeing this warning message in dev-console (chrome), specifically when attempted to load pandas.

Can you please let me know the side-effects of this warning ? I haven't experienced any, for real so far.

Warning message: 
`lib/python3.9/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.`

![B46F3893-D306-4F91-B747-110D18D3E4E1_1_105_c](https://user-images.githubusercontent.com/30823233/132520085-db25114d-21db-46d7-bb13-9eb6cd74ec03.jpeg)

**Comment by rth** [comment]
Short answer you won't be able to `pd.read_csv` files with `.xz` (and maybe `.lzma`?) compression without the lzma module which we currently don't include. We could add it if anyone needs it and it doesn't increase the size too much.

 Aside from that it has no other side effects as far as pandas is concerned, I think. Opened https://github.com/pandas-dev/pandas/issues/43461 to remove that warning.

**Comment by pnsvk** [comment]
Thanks a lot @rth for the response AND for raising it with pandas-dev.. As of now, the only way I can contribute back is, find for issues with the project and report as I hit.
Don't know how to express, but loved this project to the core.

**Comment by rth** [comment]
That's already very helpful! Thanks for the encouragement @pnsvk !

**Comment by ifuchs** [comment]
Any chance that lzma could be added so that pandas could read .csv files?

**Comment by hoodmane** [comment]
Ideally lzma support would get added upstream: https://github.com/emscripten-core/emscripten/issues/8984.

**Comment by rth** [comment]
> Any chance that lzma could be added so that pandas could read .csv files?

You don't need lzma to read .csv files. It's just an unnecessary warning in pandas, fixed in https://github.com/pandas-dev/pandas/pull/43495. We should backport that (or wait for the 1.4.0 release). Unless you are reading .csv.xz or .csv.lzma?

**Comment by ryanking13** [comment]
lzma module is now supported with (`pyodide.loadPackage('lzma')`). Closing as resolved.
