### ISSUE TITLE
Is it possible to update scipy?

### ISSUE THREAD

**Issue by SebastianJHM** [pyodide/pyodide#1836]
Hi pyodide team.
I'm working with Scipy in pyodide and I need funcionalities of the current version. I don't know if is possible update the scipy version.

**Comment by rth** [comment]
It's possible and is on the roadmap, it's just not simple and very time consuming. Don't hesitate to comment in https://github.com/pyodide/pyodide/issues/549 and https://github.com/pyodide/pyodide/pull/1293#issuecomment-863011857
