### ISSUE TITLE
Release Python code as pypi package

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1839]
In [this discussion](https://github.com/pyodide/pyodide/discussions/1833#discussioncomment-1335038) @grimmer0125 identified the issue that `JsProxy` cannot be used as a type label: static type analysis tools won't be able to suggest autocompletions and mypy etc can't typecheck the file. We already went to the trouble to make it possible to import pyodide in native Python, but we need some way to install it for the type analysis software. I think the best solution is to the Python code in `src/py` as a pypi package.

**Comment by grimmer0125** [comment]
I just recently noticed this, `stub` https://www.python.org/dev/peps/pep-0484/#stub-files and not sure if it is another solution or not. I have no experience with it and just pass this info. [Mypy's stub section](https://mypy.readthedocs.io/en/stable/stubs.html)

**Comment by rth** [comment]
Yes, this would also be necessary to pass host micropip tests in https://github.com/pyodide/micropip/pull/3.

How should we call this package on PyPi: `pyodide-core-py` ?

**Comment by rth** [comment]
Actually another important reason we need this package on PyPi, and for it to be runnable in host as much as possible is notebooks. If someone uses any functionality  (e.g. pyfetch) from this package in say JupyterLite, then download the notebook and try to run it locally, it will fail unless they are also able to pip install this package.

> How should we call this package on PyPi: pyodide-core-py ?

Any objections?

**Comment by hoodmane** [comment]
Well, it's not a great name, but I guess it gets the point across.

**Comment by rth** [comment]
I share the sentiment. It's just that `pyodide-core` is technically also the FFI, and the JS package. 

Maybe actually `pyodide-py` would be better?

**Comment by hoodmane** [comment]
Yeah let's go with `pyodide-py` maybe. That also isn't fantastic but I think it has a nice enough ring to it. 

At some point we could try to change the docs to call it `pyodide-py` more often, since we still have the confusion between `pyodide` the Python module accessible from JavaScript as `pyodide.pyodide_py` and `pyodide` the Javascript object importable from Python as `pyodide_js`.

**Comment by rth** [comment]
I uploaded [`pyodide-py`](https://pypi.org/project/pyodide-py/) to PyPi some month ago, as we needed it in micropip. We still need to auto-deploy it in CI.
