### ISSUE TITLE
Template for issue reporting ?

### ISSUE THREAD

**Issue by sylvain-ri** [pyodide/pyodide#1844]
In contributions, [Bugs & Issues](https://pyodide.org/en/stable/development/contributing.html#bugs-issues):
"We provide a template to give you a guide for how to file optimally. "

There is a guide from github that we can use here: 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by hoodmane** [comment]
I guess there are some options listed here:
https://github.com/stevemao/github-issue-templates

**Comment by sylvain-ri** [comment]
Only someone with elevated permissions can change the issue template I guess ?

**Comment by hoodmane** [comment]
For what it's worth, I don't see an "issue template" button in the settings menu either. We need a file called e.g., `.github/ISSUE_TEMPLATE/bug-report.md`. I think you could add that file and open a PR. Here are some examples in the wild:
https://github.com/search?q=in%3Apath+.github%2FISSUE_TEMPLATE&type=Code

**Comment by rth** [comment]
> Only someone with elevated permissions can change the issue template I guess ?

I think you can configure all that with a `.github/ISSUE_TEMPLATE/config.yml` file, if you add it in a PR. Here is an [example of a repo](https://github.com/scikit-learn/scikit-learn/blob/main/.github/ISSUE_TEMPLATE/config.yml) that uses it. Then we could indeed add a `bug-report.md` template.

**Comment by hoodmane** [comment]
We probably want a different template for bug reports about the build system (where operating system / whether or not the person is using Docker is very important) vs about the runtime (where the most important thing is what browser version they are using).
