### ISSUE TITLE
strange: somehow passing a PyProxy of bytes as a ArrayBuffer argument of an third-party JS decoder function work without toJs/getBuffer

### ISSUE THREAD

**Issue by grimmer0125** [pyodide/pyodide#1869]
This issue was introduced in https://github.com/pyodide/pyodide/issues/1853#issuecomment-926777416, 

Another trial: pass `bytes` as the ArrayBuffer argument of this JS function in Python. It works, too.

The strange behavior seems that it will automatically do implicit conversation from `bytes/PyProxy` to `ArrayBuffer` inside the JS function of the below code snippet.

```js
// called in Python for decoding medical files for 1st rendering.  pass Python bytes object 
function js_decoder(bytes: ArrayBuffer) {
  // Actually it will be PyProxy for this case

  // it requires a ArrayBuffer but passing PyProxy works !! No toJs/ getBuffer
  const decoded  = decoder.decode(bytes)  // jpeg third party lossless decoder function
}
```

I use the latest Pyodide on CDN to test: https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js

## How to reproduce

The code is here: https://github.com/grimmer0125/embedded-pydicom-react-viewer/blob/test_memory_leak_and_strange_decode_function_accept_pyproxy_work/src/jpegDecoder.ts#L9 

`decoder.decode` is not written by me and is from a 3party library. It should accept ArrayBuffer but get `PyProxy` and work. The following similar decoding function has the same strange phenomenon.

Python caller part is https://github.com/grimmer0125/embedded-pydicom-react-viewer/blob/test_memory_leak_and_strange_decode_function_accept_pyproxy_work/python/dicom_parser.py#L196

To test them, just 
```
- git clone git@github.com:grimmer0125/embedded-pydicom-react-viewer.git
- git submodule update --init --recursive
- git checkout test_memory_leak_and_strange_decode_function_accept_pyproxy_work
- yarn install 
- yarn start (it may take a while for 1st time since I add WebAssembly JPEG decoder)
```
The testing file: [dicom.zip](https://github.com/pyodide/pyodide/files/7254231/dicom.zip). Unzip it and drag `JPGLosslessP14SV1_1s_1f_8b for issue2` to view. 

If they are too complicated (e.g. the source code is a mass), please tell me and I may find some time to make a simplified demo code.

**third party decode function**: https://github.com/rii-mango/JPEGLosslessDecoderJS/blob/master/src/decoder.js#L116

**Comment by hoodmane** [comment]
What is happening is that inside `jpeg.lossless.DataStream` they say `new Uint8Array(buffer)`.
https://github.com/rii-mango/JPEGLosslessDecoderJS/blob/78fe90c7cae985b1a394a66f99c81633144bb867/src/data-stream.js#L42

The `PyProxy` you are passing is iterable because bytes is iterable. So `Uint8Array` will iterate over it and use it to make a `Uint8Array`. This gives the expected result but is very slow.

The following is way more efficient:
```js
function js_decoder(bytes: PyProxy) {
  const buf = bytes.getBuffer();
  const data = buf.data;
  const decoded  = decoder.decode(data, data.byteOffset, data.byteLength);  
  buf.release();
  return decoded;
}
```

**Comment by hoodmane** [comment]
I am going to close this as answered. Thanks for your feedback @grimmer0125!
