### ISSUE TITLE
./node_modules/pyodide/load-pyodide.js Module not found: Can't resolve 'fs/promises'., pyodide npm 0.18.2

### ISSUE THREAD

**Issue by grimmer0125** [pyodide/pyodide#1875]
I create a [create react app](https://github.com/facebook/create-react-app) project, and `yarn add pyodide` to test `pyodide` import function. It will throw the error message when using `yarn start` (as long as I add `await import` that line) , the result is `Failed to compile.` The below is the added code on the bootstrap project.  

node: v15.14.0
yarn: 1.22.10
ref repo: https://github.com/grimmer0125/test_pyodide_npm/blob/master/src/App.js

```
async function test() {
  let pyodide_pkg = await import("pyodide/pyodide.js"); 
}

function App() {
  useEffect(() => {
    async function init() {
      await test()
    }
    init();
  }, []);
```

**Comment by grimmer0125** [comment]
Duplicated with #1863

**Comment by rth** [comment]
@grimmer0125 Should we close this issue now?

**Comment by grimmer0125** [comment]
Yes, I'm going to close this issue. I have tested #1900 on another famous front-end framework, [angular](https://angular.io/) and it works too.

**Comment by TatyanaVl** [comment]
I get this issue as well and its not clear how the issue was solved.
