### ISSUE TITLE
Memory error while using pandas sort values 

### ISSUE THREAD

**Issue by NishiPhalke** [pyodide/pyodide#1879]
I have a large pandas dataframe ( of 997703521 bytes) with 1190321 rows and 100 rows and I am trying sort it by 2 of columns ( x = x.sort_values(by=['CHR', 'BP'])) But I am getting memory error **MemoryError: Unable to allocate array with shape (1190321,) and data type int64** while sorting in pyodide wasm. 

numpy array creation with large number of rows/cols also fails.
![image](https://user-images.githubusercontent.com/30417924/136457197-25df4fc4-7551-4525-9507-7801a0306ab2.png)

Is there any size limit of pandas dataframe that can be handled in pyodide ?

**Comment by leopsidom** [comment]
There's definitely a memory in webassembly. Since it uses 32 bit pointer, the largest memory it can use is 4GB. https://v8.dev/blog/4gb-wasm-memory
