### ISSUE TITLE
RFC Find a Fiscal Sponsor for Pyodide

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1916]
As a follow up to https://github.com/pyodide/pyodide/issues/1217 I think it might be a good idea to find a non profit organization that could act as a fiscal sponsor for Pyodide. Below are non profits  that I see frequently used to host open source projects in this space, 
-  [NumFocus](https://numfocus.org/) (most of the scientific Python packages) : [application process](https://numfocus.org/projects-overview)
-  more recently [Open Collective](https://opencollective.com/) (platform) and in particular the [Open Source Collective](https://www.oscollective.org/) (lots of popular packages, e.g. webpack, babel, PyPy, Chrome, NixOS etc): [application process](https://opencollective.com/opensource/apply)

(Maybe there are others you would recommend?)

The general idea is the non profit in question gives the project an existence in the legal sense. In particular, it typically
 - allows to receive donations (https://github.com/pyodide/pyodide/issues/576) and apply for grants 
 - it usually takes some fees out of those (around 10 - 15 %) and in exchange provides services for promoting the project, raising more funding and legal advice if needed.

In particular, we are starting to consider to organize in person sprints on Pyodide in 2022, and having an independent budget for those would be useful. Also we have some small expenses for the domain name and AWS S3 infrastructure that are currently paid by me / my company (Symerio) which is fine for foreseeable future, but for long term sustainability having a separate budget wouldn't hurt.
BTW I think we got rejected from getting AWS credits in the past, in part because one can only apply as an individual/company since Pyodide has currently no legal existence otherwise. 

Of course that would raise the question how decisions are made to spend those hypothetical funds. I think the [governance](https://pyodide.org/en/stable/project/governance.html#decision-making-process) already provides a general framework, but we can also amend it to more explicitly say that those decisions are made by vote of core developers.

So the question is WDYT about applying to a non profit that would fiscally sponsor us? And if yes, which one?

I think the Numfocus is good, but their applications process is more strict (next deadline January 15, decisions on February 29) and they are also more associated with scientific computing. They provide significant help with writing grants as well.

Open Collective also looks good, as far as I can tell it's much easier and faster to setup (see application links above). I also like that everything is very transparent. For instance, for [PyPy you can see the current state of their budget](https://opencollective.com/pypy), funds they receive and how it's being spent. Also there are many Fiscal Hosts on the platform the  Open Collective provides, so if we are unhappy with OSC we can always change. Also because they manage so many projects, I think everything should be a bit more automated (less paperwork), no periodic meetings to attend, but in exchange the services they provide are less personalized.

Overall I would be +1 for the Open Source Collective as application looks simpler, and because Pyodide use cases are wider than scientific software. Their terms are [here](https://docs.google.com/document/u/1/d/e/2PACX-1vQbiyK2Fe0jLdh4vb9BfHY4bJ1LCo4Qvy0jg9P29ZkiC8y_vKJ_1fNgIbV0p6UdvbcT8Ql1gVto8bf9/pub) and need careful reading. Broadly it doesn't look very different from NumFocus terms as far as I know.

@pyodide/core @pyodide/community-members

**Comment by ryanking13** [comment]
I believe having a fiscal sponsor will be good for the project's sustainability.

> Pyodide use cases are wider than scientific software.

I agree with this.

**Comment by hoodmane** [comment]
I read through the open collective legal agreement and some of their docs and they look quite reasonable to me. Plus it seems like we would be in pretty good company there -- certainly lots of projects that are (in my opinion) more important that Pyodide are in the list.

**Comment by rth** [comment]
Thanks  everyone for the feedback!

So I went ahead and created an account with OSC, and after a few clicks it looks like it's live: https://opencollective.com/pyodide . I really though that they would at least ask us to sign something, but apparently not. There is just a form with ToC and automatic validation based on Github integration.
@mdboom @hoodmane  You should have received an invite.

We can also probably apply to [Github Sponsors](https://github.com/sponsorsà) and [connect it to OSC](https://docs.opencollective.com/help/collectives/osc-verification/github-sponsors) while we are at it.

**Comment by rth** [comment]
> We can also probably apply to Github Sponsors and connect it to OSC while we are at it.

I made the request to enable it  yesterday, following the above linked guide, mostly copy pasting information we have on the OSC profile.  It's a bit nicer for people who donate since it shows on their GH profile. You can edit that profile on https://github.com/sponsors/pyodide/dashboard but it only works for org owners. Hood I also added you  as an org owner, so it should work for you as well.

**Comment by rth** [comment]
Also the draft of the announcement blog post for joining OSC is in https://github.com/pyodide/pyodide-blog/pull/6
