### ISSUE TITLE
Run in React Native?

### ISSUE THREAD

**Issue by gkaissis** [pyodide/pyodide#1919]
Pyodide would be a great way to run python in mobile apps. However, when going the npm way, one runs into the fs/promises issue from #1875. Loading via CDN in a WebView cannot possibly be the best way to do this. Is there a recommended way to get Pyodide running in react-native (expo)?
Thanks!

**Comment by ryanking13** [comment]
For now, I think loading via CDN is a possible option.
Hopefully, we are expecting fs/promises issue will be resolved via #1900 before long.
