### ISSUE TITLE
Use larger CircleCI resource classes for chrome tests?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1928]
It looks like CircleCI has made Medium+ and Large resource classes available on free plans (their docs are currently inconsistent on this though). Maybe if we increased the size of the chrome tests then the tests would fail less frequently.

**Comment by rth** [comment]
That's a really good news! Tried it in #1929 and it works up to Large resource class indeed. 

For instance when building packages, we get from 32min currently to 23min with a Large resource class, since build is relatively well parallelized. Hopefully this would also help Chrome failures..
