### ISSUE TITLE
Add some environment variable in `pyodide_build/buildpkg.py:run_script`

### ISSUE THREAD

**Issue by hzhangxyz** [pyodide/pyodide#1957]
such as `SITEPACKAGES`, `PKGDIR` which already set in "post", these variables are helpful to write build scripts.

I am compiling a pybind11 based library, so besides `SITEPACKAGES`, I need:
- `PYTHON_MODULE_EXTENSION=.cpython-39.so`
- `PYTHON_INCLUDE_DIRS=$PYODIDE_BASE/cpython/installs/python-3.9.5/include/python3.9`

---

Or is there any other method to obtains such values?

**Comment by rth** [comment]
It does sound like `PYTHON_INCLUDE_DIRS` at least would very useful, so +1 for a PR to pass it the the package build setup. Though I'm not sure if this could be an issue for other Cmake based builds.

For `PYTHON_MODULE_EXTENSION` I'm less sure, maybe you could  specify that directly in the package build config?
