### ISSUE TITLE
Examine unsupported / untested syscalls

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#196]
Following the issue encountered in https://github.com/iodide-project/pyodide/issues/192 for `utimensat`, this is a more systematic analysis of system calls that may be unsupported or untested in emscripten.

Opened a related issue in https://github.com/kripken/emscripten/issues/7194
The general methodology consists in,
 - looking at `src/library_syscall.js` in emscripten and list any system calls, that are marked as "untested" in comments, that explicitly raise an error, or have other comments suggesting that the implementation is not functioning.
 - most of the ones related to the file-system can also be found in TODO list in comments at the end of [system/lib/fetch/asmfs.cpp](https://github.com/kripken/emscripten/blob/incoming/system/lib/fetch/asmfs.cpp).

we then look at the intersection of the obtained list to with the the list of flags in `pyconfig.h`, and check whether the there are indeed no tests for the segfault in question.

Below is are resulting system calls, that are either untested in emscripten or explicitly raise an error, and are used in CPython.

## Syscalls that can be disabled in pyconfig.h

Below system calls are currently enabled in `pyconfig.h`,

 - [openat](https://linux.die.net/man/2/openat)
    cpython: used in for `os.open` when disabled [open](https://linux.die.net/man/2/open) syscall is used instead
 - [mkdirat](https://linux.die.net/man/2/mkdirat)
     cpython: used in for `os.mkdir`
     when disabled [mkdir](https://linux.die.net/man/2/mkdir) syscall is used instead
 - Generally most FS related syscalls that end with `at`, including `fchownat`,
   `renameat`, `linkat`, `symlinkat`, `readlinkat`, `fchmodat`, `faccessat`
   `utimensat`.

   An exception is `unlinkat` that is tested in emscripten, because it was added by @mdboom in https://github.com/kripken/emscripten/pull/6466 :)

 - [dup3](https://linux.die.net/man/2/openat)
    cpython: used in os.dup2. If not available dup2 syscall is used. This actually may explain
    issues we saw with `os.dup2` in https://github.com/iodide-project/pyodide/pull/95#issuecomment-417063144
 - [preadv](https://linux.die.net/man/2/preadv) and [pwritev](https://linux.die.net/man/2/pwritev)
    cpython: used in `os.preadv` and `os.pwritev` (new in Python 3.7)
 - [pipe2](https://linux.die.net/man/2/pipe2),  [setitimer](https://linux.die.net/man/2/setitimer), [nice](https://linux.die.net/man/2/nice)
    emscripten: explicitly marked as unsupported feature in `src/library_syscall.js`
    cpython: used in `os.pipe2`
 -  wait4 (explicitly aborts with "cannot wait on child processes"), wait3, waitid, waitpid (I imagine)
 

## Syscalls that can't be disabled in pyconfig.h

 - [getrusage](https://linux.die.net/man/2/getrusage)
    possibly returns arbitrary data (emscripten comment says "fake some values")
    used by `resource.getrusage`. Used in CPython tests, and CPython `test_resource` passes.
 - [ugetrlimit](https://linux.die.net/man/2/ugetrlimit)
    possibly returns arbitrary data

A possible solution could be to disable some of these in `pyconfig.h` (hopefully it wont affect functionality too much).

**Comment by rth** [comment]
BTW, this can also have a positive effect on the test suite. For instance if we disable `HAVE_PIPE2` at compile time, `os.pipe2` will not be available, the [corresponding tests](https://github.com/python/cpython/blob/3d18b50a12e639e018d49d7b85663164d60bfd2b/Lib/test/test_posix.py#L844) in `test_posix` will be skipped, and so this file has a higher chance of passing as a whole (currently [it crashes](https://github.com/iodide-project/pyodide/blob/master/test/python_tests.txt#L364)).

Also as a side note, the above analysis was done with the dev branch of emscripten and a few things may have changed there with respect to the 1.38.10 tag we are currently using.

**Comment by mdboom** [comment]
This is awesome.  Thanks for the detailed investigation.

I agree as a guiding principle, it's always better to get a Python exception than to crash the wasm environment with an abort or something.

As a process here, perhaps:

1) Add #undefs for all the things pyconfig.h already has that are missing in emscripten
2) Run all the tests currently marked as "crash" and see what changes -- if something goes from a crash to a Python exception, that's progress, and maybe give it a new label in `python_tests.txt`.

**Comment by rth** [comment]
Working on it, I agree with the proposed process.

I'm really excited about this ! (also about learning more about syscalls..)

Since these are configure checks, theoretically there could be a system where some of this functionality is not available (even if, due to a miscommunication with muscl/emscripten we are "cheating" a bit by disabling them manually). So when a Python package fails due to one of the missing syscalls (and e.g. the existence of the corresponding `os` function), one could argue (or at least try to) that that this is a legitimate CPython use-case and that a fix should be applied on the package.

I used to complain about this (https://github.com/scikit-learn/scikit-learn/issues/7526#issuecomment-250429381) but from this side of things, such versatility is very nice!

**Comment by rth** [comment]
Closing as this work should happen upstream in CPython now.

cc @tiran in case there was anything useful in the original description. It's probably fairly outdated though.
