### ISSUE TITLE
compile error, wasm-ld complain unknown argument

### ISSUE THREAD

**Issue by hzhangxyz** [pyodide/pyodide#1963]
## 🐛 Bug

Compile error: 
```
wasm-ld: error: unknown argument: --sort-common
wasm-ld: error: unknown argument: --as-needed
wasm-ld: error: unknown argument: --sort-common
wasm-ld: error: unknown argument: --as-needed
```

### To Reproduce

make the project

### Expected behavior

make succesful

### Environment

- Commit hash of Pyodide git repository: (f58d9c1)
- Build environment: arch linux

I compile with command:
```
PYODIDE_JOBS=5 PYODIDE_PACKAGES="micropip,numpy" PATH=$PATH:$PWD/../f2c/src make
```

### Additional context

make call many things I don't know about, but the last, the error is raised by `wasm-ldd`,
`wasm-ldd` is called by `emcc` which arguments contains:
```
-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
 -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

It seems when pyodide run setup.py, it import my system's config, while in my system
```
/usr/lib/python3.9/_sysconfigdata__linux_x86_64-linux-gnu.py
```
have a line:
```
 'LDSHARED': 'gcc -pthread -shared '
             '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now '
             '-fno-semantic-interposition '
             '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now',
```

Is there any former mistake happened? the `emcc` argument should not contains parameter from my system's config?
Or I need to change my system's config to be compatible with wasm tool chain?

**Comment by hzhangxyz** [comment]
Maybe `pywasmcross.py:handle_command` need to dealing with these wasm unknown argument?

**Comment by rth** [comment]
On Linux if you don't want to deal with this, the easiest is to use Docker (cf [build instructions](https://pyodide.org/en/latest/development/building-from-sources.html) updated today).

> Maybe pywasmcross.py:handle_command need to dealing with these wasm unknown argument?

Otherwise I'm not sure why Arch config  adds those, but yes we can ignore them in `handle_command`. A PR would be welcome. Also if you find build instructions need improvement, please let us know.

**Comment by ryanking13** [comment]
> Otherwise I'm not sure why Arch config adds those, but yes we can ignore them in `handle_command`.

It looks like Arch Linux uses [makepkg.conf](https://wiki.archlinux.org/title/makepkg) to add build configurations, and it has `--sort-common` and `--as-needed` for default option.
