### ISSUE TITLE
Add micropip.list

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1967]
It would be nice to add `micropip.list` function to list all installed packages and their versions, by analogy with the `pip list` command.

The output could be a list like object of dictionaries (or data class objects) with the following fields,
```py
    name: str
    version : str
    path : Path
```
and a `__repr__`  method to display this nicely (except for maybe the path). Actually, tt could be either,
 1. a custom list like object with a `__repr__` containing standard dict objects
 2. a standard list with dataclasses that each has a custom `__repr__` method

or some mixture of the two. Option 2 would likely be easiest to use/implement IMO.

**Comment by ryanking13** [comment]
Should the output of this API include js packages that are listed in `packages.json`? I think so if we are going to merge `micropip` and `pyodide.loadPackage`

**Comment by rth** [comment]
Yes, I was thinking we could support both, and indicate the source in a separate column.
```
# Name        Version                   Source
package_1     0.2.2                     pypi
package_2     1.3.1                     pyodide
package_3     0.1.4                     <some-custom-url.whl>
```
This is what `conda list` is doing for instance by listing both pip and conda install packages.

Not 100% sure yet what would be the best output type to both have this repr and a usable container object with the results though.

**Comment by rth** [comment]
> I think so if we are going to merge micropip and pyodide.loadPackage

Answered in https://github.com/pyodide/pyodide/issues/1470#issuecomment-970079464
