### ISSUE TITLE
Why `--memory-init-file 0`?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1972]
We've had `--memory-init-file 0` since the third commit:
https://github.com/pyodide/pyodide/blob/191ca2c7bd4ba6a05ba87f5427e89ea3ef5bdddc/Makefile#L14

[The emscripten docs about this flag](https://emscripten.org/docs/tools_reference/emcc.html#emcc-memory-init-file) say "Emit a separate memory initialization file in binary format. This is more efficient than storing it as text inside JavaScript but does mean you have another file to publish. The binary file will also be loaded asynchronously, which means main() will not be called until the file is downloaded and applied; you cannot call any C functions until it arrives."

We already have to wait on the file system data in `pyodide.asm.data` so it seems like it might be harmless to also have to download a memory init file.

**Comment by rth** [comment]
I think the docs (that you link) say that it has no effect for WASM. Also, this [line](https://github.com/emscripten-core/emscripten/blob/6736c2b1ec3d4f1aa489af8945efe9bbe7c803b6/tests/common.py#L379) will always return False for WASM as far as I can tell. So I think we can remove it.

**Comment by phorward** [comment]
Give it a try!
