### ISSUE TITLE
Building a Python package that uses Rust

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#1973]
## 🚀 Feature
Tooling and/or docs to support building Python packages that contain Rust code.

### Motivation
I was in the process of (attempting to) create a JS/wasm build of [Hugging Face Tokenizers](https://github.com/huggingface/tokenizers/) when I realised that it might just be easier/better for my use case to load it with Pyodide (especially since I might want to use Python packages that depend upon Tokenizers. The [docs show](https://github.com/pyodide/pyodide/blob/main/docs/development/new-packages.md) how to build a Python package that uses C (with emscripten), but not Rust.

Rust has great, simple wasm build support via [`wasm-pack`](https://github.com/rustwasm/wasm-pack). After annotating the Rust functions/modules that you want to export (and installing wasm pack with `cargo install wasm-pack`) it's just a single `wasm-pack build --target=web --out-dir=wasm` to get the wasm and glue files. [Here's a hello world tutorial](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm).

So I'm wondering: Is this feasible now with the right configuration, or is there some extra work on the Pyodide dev tooling to get this working? If it's not possible with the current tooling, what might be the steps required to make it possible?

Thanks!

**Comment by rth** [comment]
Thanks for proposing it! There was an earlier analysis of feasibility in https://github.com/pyodide/pyodide/issues/1282#issuecomment-785459008 and it doesn't look very promising. 

Maybe a start could be trying to build a very simple PyO3 Python library. Related https://github.com/PyO3/pyo3/issues/1522

Even if the end we manage to compile that library say for RustPython using the wasm-pack, you end up with a Python extension built for a different Python interpreter and the compatibility story there is not very good.

**Comment by hoodmane** [comment]
I wonder if it could be possible to convince Rust to emit llvm ir and then use emcc to do the backend compilation and linkage. Rust also has a wasm32-emscripten target but it's apparently pretty broken.

**Comment by josephrocca** [comment]
@hoodmane @rth Thanks for your tips! Having looked into this, it seems to be a bit over my head at my current level of knowledge. That said, it would be great if I could make a dent in at least part of the problem.

My understanding is that if we get a simple Python+Rust library compiled with PyO3 (with the Rust converted to wasm), then we'll be able to swap out Python with Pyodide? But from reading some of those Github issues sounds like PyO3 may create different interfaces compared to what Pyodide expects? Would someone be able to list the rough high-level problems that would likely need to be solved here?

Question: Since it should be pretty easy to compile the Rust code to wasm (+ js glue) with wasm pack (at least, going by my past experiences with wasm pack), I was wondering whether it would be possible to then import that JS module into Python/Pyodide in such a way that Pyodide essentially sees that JS module as it would the PyO3 Python module? Or would there be "interface" issues due to diferences in the way wasm pack and PyO3 generate glue code?

> I wonder if it could be possible to convince Rust to emit llvm ir

[The answer here](https://stackoverflow.com/questions/39004513/how-to-emit-llvm-ir-from-cargo) says you can emit llvm-ir with `cargo rustc -- --emit=llvm-ir`

**Comment by hoodmane** [comment]
>  it seems to be a bit over my head at my current level of knowledge

One of the fun parts of Pyodide is that a lot of it is over our heads, at least until we figure it out =)

> Maybe a start could be trying to build a very simple PyO3 Python library.

I think perhaps even better might be if we could write a trivial rust extension without using PyO3. I just tried to do this for a while, but I keep getting errors at import time.

**Comment by hoodmane** [comment]
Here's my partial work on this:
https://github.com/hoodmane/minimal-rust-pyton-ext/blob/master/src/lib.rs
You can build with `cargo build` and then use
`cp target/debug/libpython_min_test.so mymod.cpython-39-x86_64-linux-gnu.so` 
then can try to `import mymod` but there are errors.

Anyways, if we can get a module like this to work, then we could try to compile it to work with Pyodide.
