### ISSUE TITLE
'ci/circleci: test-js' test seems to fail unrelated to any changes

### ISSUE THREAD

**Issue by DerThorsten** [pyodide/pyodide#1978]
the 'ci/circleci: test-js' test seems to fail unrelated to any changes
```
../../build/pyproxy.gen.d.ts:249:27
  ✖  249:27  Cannot find name bool.  
  ✖  250:25  Cannot find name bool.  
```
I see two PRs failing this test even though the changes are unrelated:
https://app.circleci.com/pipelines/github/pyodide/pyodide/3181/workflows/f0d34ca0-1319-4888-99bf-bd467b15320f/jobs/33621
https://app.circleci.com/pipelines/github/ryanking13/pyodide/34/workflows/affba5ae-ab35-4ef5-8af6-a2cd32f0a228/jobs/490

**Comment by rth** [comment]
Thanks @DerThorsten ! Yes, it got worse now on main after https://github.com/pyodide/pyodide/pull/1975 with,
```
  index.test-d.ts:64:57
  ✖   64:57   Parameter x implicitly has an any type.  
  ✖   68:7    Parameter x implicitly has an any type.  
  ✖   69:7    Parameter x implicitly has an any type.  

  ../../build/load-pyodide.d.ts:23:82
  ✖   23:82   Cannot find name LogFn.                  
  ✖   23:105  Cannot find name LogFn.                  

  ../../build/pyproxy.gen.d.ts:249:27
  ✖  249:27   Cannot find name bool.                   
  ✖  250:25   Cannot find name bool.                   
```

this is an issue with types defined in JS docstrings of those files (and is certainly unrelated to PR).
