### ISSUE TITLE
Bug in web worker example with concurrent Promises

### ISSUE THREAD

**Issue by eagleoflqj** [pyodide/pyodide#1996]
## 📚 Documentation

[The worker API](https://pyodide.org/en/stable/usage/webworker.html#the-worker-api) has a bug when `asyncRun` is called concurrently. Function `run` modifies `pyodideWorker.onmessage`, so only the last `Promise` could be resolved and wrongly get the first finished result.
```html
<html>
<head>
  <script src="https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pyodide.js"></script>
</head>
<body>
  <script type="module">
    import { asyncRun } from "/py-worker.js";

    async function main() {
      const promise1 = asyncRun('1', {});
      const promise2 = asyncRun('2', {});
      const r2 = await promise2;
      console.log(r2);
      const r1 = await promise1;
      console.log(r1);
    }

    main();
  </script>
</body>
</html>
```
The output should be `Object { results: 2 }` and `Object { results: 1 }`
However in my Firefox, the output is `Object { results: 1 }`.

**Comment by rth** [comment]
Thanks @eagleoflqj ! That certainly looks wrong. A PR with a fix would be very welcome.
