### ISSUE TITLE
Issues building pyodide on Ubuntu 21.10

### ISSUE THREAD

**Issue by wlach** [pyodide/pyodide#2006]
## 🐛 Bug

Running `make` on Ubuntu 21.10, I get the following error:

```
gmake[4]: Leaving directory '/home/wlach/src/pyodide/emsdk/emsdk/ccache/git-emscripten_64bit/build_emscripten_64'
[ 85%] Built target ccache
[ 85%] Building CXX object unittest/CMakeFiles/unittest.dir/test_Config.cpp.o
[ 86%] Building CXX object unittest/CMakeFiles/unittest.dir/test_Counters.cpp.o
[ 87%] Building CXX object unittest/CMakeFiles/unittest.dir/test_Depfile.cpp.o
[ 89%] Building CXX object unittest/CMakeFiles/unittest.dir/test_FormatNonstdStringView.cpp.o
[ 89%] Building CXX object unittest/CMakeFiles/unittest.dir/test_Hash.cpp.o
[ 90%] Building CXX object unittest/CMakeFiles/unittest.dir/test_Lockfile.cpp.o
In file included from ../../src/unittest/main.cpp:27:
../../src/src/third_party/doctest.h:4189:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4189 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
gmake[4]: *** [unittest/CMakeFiles/unittest.dir/build.make:95: unittest/CMakeFiles/unittest.dir/main.cpp.o] Error 1
```

It appears the problem has to do with the doctest.h file included in the version of ccache used to build emscripten (`./emsdk/emsdk/ccache/git-emscripten_64bit/src/src/third_party/doctest.h`). This issue seems to have been fixed upstream (https://github.com/onqtam/doctest/issues/473), though does not seem to have made its way into the version of ccache used by emscripten (https://github.com/juj/ccache/tree/emscripten)

**Comment by wlach** [comment]
I think I've fixed this problem in a fork, but might be best to wait to see if upstream (which is also a fork) accepts my PR before doing anything here

**Comment by rth** [comment]
Thanks for looking into it! The dependence on a non-maintained cache fork is not ideal: it's not strictly necessary, but it does make the build faster.

**Comment by weiji14** [comment]
I'm getting the exact same `doctest.h:4189:47: error: size of array ‘altStackMem’` error on Ubuntu 22.04, is there a workaround for this at the moment?

**Comment by Real-Gecko** [comment]
Same on Arch Linux

**Comment by Himself65** [comment]
The reason is `SIGSTKSZ` is no longer constant on Linux

```
* Add _SC_MINSIGSTKSZ and _SC_SIGSTKSZ.  When _DYNAMIC_STACK_SIZE_SOURCE
  or _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ are no longer
  constant on Linux.  MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ)
  and SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ).  This supports
  dynamic sized register sets for modern architectural features like
  Arm SVE.
```

Refs: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

so I think one workaround is to downgrade the GNU library

**Comment by Himself65** [comment]
workaround:
```bash
sudo apt install gcc-10 g++-10
export CC=gcc-10
export CXX=g++-10
make
```
