### ISSUE TITLE
exception in asyncio.wait_for()

### ISSUE THREAD

**Issue by mogenson** [pyodide/pyodide#2011]
## 🐛 Bug

Waiting for an awaitable using `asyncio.wait_for()` prints exceptions to the browser's console:

```
pyodide.asm.js:14 Exception in callback None()
pyodide.asm.js:14 handle: <Handle cancelled>
```

This happens whether the awaitable finishes before the timeout or not. `asyncio.wait_for()` appears to still function as intended, but this makes applications that use `asyncio.wait_for()` frequently very spammy.

### To Reproduce

In [Pyodide console application](https://pyodide.org/en/stable/console.html), enter the following:

```
import asyncio
await asyncio.wait_for(asyncio.sleep(1), 2)
```

### Expected behavior

No exceptions are raised and no output is printed to the console.

### Environment

- Pyodide Version: 0.18.1 from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/
- Browser version: Chrome 96.0.4664.55
- Any other relevant information:

**Comment by hoodmane** [comment]
Thanks for the report! This is probably a bug in our event loop.
