### ISSUE TITLE
CI build-packages timeouts without ccache

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2013]
It looks like CircleCI introduced a 1 hour timeout, or maybe it's due to us switching to a `Large` CI instance for the `build-packages`  job. 

In any case, this job would now timeout with an empty ccache cache, since it takes longer, including for new contributors e.g. https://github.com/pyodide/pyodide/pull/2010 .

I think the solution is to reduce the number of packages we build for each commit (which would be good for CI times in general), only keeping the most difficult to build &  popular ones . Tests should work well in that case after https://github.com/pyodide/pyodide/pull/1981

Then for,
 - tags
 -  if the commit message contains some pattern, for instance `[build all]`
 
build all packages.

**Comment by ryanking13** [comment]
For a short term solution, maybe we could rely more on Github Actions that looks like having less limitations on public repositories.

**Comment by rth** [comment]
The issue is that would mean re-designing all our deploy process to GH Actions which is a non-negligible amount of work. Another issue with GH actions is that we still can't restart individual jobs if there is a non-deterministic failure.

**Comment by ryanking13** [comment]
> The issue is that would mean re-designing all our deploy process to GH Actions which is a non-negligible amount of work.

Yes. Rewriting a CI process would not be a easy process. I may said it too lightly.
