### ISSUE TITLE
Make command skips most packages in the 'packages' directory

### ISSUE THREAD

**Issue by victorChekhovoy** [pyodide/pyodide#2024]
## 🐛 Bug

When running the make command from a docker container (root or non-root), only 8 packages are built: pyparsing, Markupsafe, distutils, regex, pytz, packaging, micropip, Jinja2.

### To Reproduce

./run_docker
make (inside the docker)

### Expected behavior

All packages in the directory should be built

### Environment
 
- Commit hash of Pyodide git repository: 24271d1af7309a516fcdb8217f836dbd9c9d3e64
- Build environment<!--(e.g. Ubuntu 18.04, pyodide/pyodide-env:19 docker)- ->: pyodide/pyodide-env:19 docker

**Comment by hoodmane** [comment]
This is the intended behavior. To make all packages, say `PYODIDE_PACKAGES="*" make`.

**Comment by victorChekhovoy** [comment]
Thank you!

**Comment by hoodmane** [comment]
You are welcome! To clarify, the default only builds the packages used in the test suite. We are definitely hoping to improve the discoverability of this stuff, we know it's confusing.
