### ISSUE TITLE
RFC Plans for Pyodide package loading system

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2045]
# Plans for Pyodide Package Loading system

This supersedes #1470. #1940 is also related.

## Different ways to do dependency resolution
In #1470, I asked the question: how do we explain the difference between `pyodide.loadPackage` and `micropip.install`? Furthermore the point was raised in #1940 that added yet another way to install packages on top of the existing two would add to existing confusion about the two existing package loading methods.

I now have a good explanation for what the distinction should be:
1. `pyodide.unpackArchive` does no dependency resolution. It can be used to load a wheel which may just be missing its dependencies. This is good for when users want to do manual dependency resolution.
2. `pyodide.loadPackage` does static dependency resolution. It only can load packages that we thought we might want to load ahead of time. It already has precomputed which dependency tree it plans to load so there's no need to go mucking about with complicated wheel operations.
3. `micropip` is for dynamic dependency resolution. This should only be used to load packages we didn't know ahead of time we would need. It should not be used in apps that always use the same set of packages. Good for a REPL or any place where you are evaluating arbitrary user code.

### New `pyodide_build` entrypoints to update `packages.json`

We should be able to add packages to `packages.json` in some simple way. We could do dependency resolution for packages with suitable wheels available on PyPi and add entries to `packages.json` pointing at the appropriate pypi wheels. We should be able to generate these from a requirements file.

## Switching to wheels
In #2027 I have rewritten the Pyodide package management system to build and load wheels. This will increase compatibility between `pyodide.loadPackage` and `micropip.install`. In principle, `pyodide.loadPackage` can be used to load other archives in addition to wheels. In the future, I am hoping not to use the Emscripten file_packager format for anything except the Python standard library which we need before we can start using `shutil`. Once `shutil` works, the rest can be done with normal archive formats.

### Remove support for loading from urls
In order to get a clean distinction between the purposes of our different package loading methods, we should remove loading urls with `pyodide.loadPackage`. We have no way to do any dependency resolution on them. We will have `pyodide.unpackArchive` or a related API for loading packages without dependency resolution. Instead, `loadPackage` will only be able to load named packages that appear in `packages.json`.

### Add support for loading wheels from pypi or other locations

Since `pyodide.loadPackage` loads wheels now, there is no reason it can't load compatible wheels from PyPi. The appropriate URL should be precomputed when we create `packages.json`.

### Logging levels

Currently we call `messageCallback` or `errorCallback` on strings to give info about the progress of `pyodide.loadPackage`.
Instead of accepting callbacks, I think it would be more appropriate to only log to the console, but accept a logging level, perhaps chosen between "info", "error", and "none".

### Add a return value

We should return a list of successfully loaded packages and a list of errors. Something like:
```js
{success : ["pytz", "pyparsing"], failed : { "numpy" : "Not found" }}
````

**Comment by ryanking13** [comment]
Thanks for organizing this, I mostly like the proposal.

So the recommended ways of using those APIs are:

- __In REPL (like jupyter)__: use `micropip.install` to install packages dynamically.
- __On production apps using Pyodide__: list all packages in `packages.json`, then use `pyodide.loadPackage` at the startup which will install (download and extract) those packages (maybe in the background for the performance).
  - For python codes that are not packaged, download them through `pyodide.unpackArchive`.

Am I understanding correctly?

**Comment by bollwyvl** [comment]
> Switching to wheels

very exciting. Hopefully there is some future where there is a tool that:

- handles binary build issues
- support `data_files`
- generates reproducible builds

again, i pine for `emscripten-32` conda packages, but don't have the time to really dig into what that would take to bootstrap.

> ways to do dependency resolution

On `jupyterlite`, we've had requests for pre-installing packages, and it would be indeed be useful. For example, if a given site was the documentation for a particular package, we'd love to give the site owner a way ensure that package-under-documentation was installed on kernel launch. 

Or hook %pip install` to save stuff to notebook metadata, and re-install it when it got reloaded. So if the output of `micropip.list` that could feed into `loadpackage`, grabbing everything in parallel, that would feel great.

However, we might still wait and execute all these things in "user space" to get better error reporting when things go wrong (because they can always go wrong)... 

> update packages.json

It's probably my conda thinking showing, but anywhere a list of packages is configured, I think it is important to be able to provide lists of files. So `indexUrl` could accept one or more URLs. This can substantially reduce the amount of rework a site owner.

> a return value

semi-related, having the return value be an exact listing (e.g. with versions, or all the way to urls with sha fragments) of what was installed which could be saved and handed back to an install method (or a `packages.json` builder) would be fabulous.

Again, not because conda is viable at this time, but because the workflow is sound, this can be achieved with:
- `conda list --explicit` to get the URLs
- download the urls, preserving their "subir" (e.g. `./noarch`, `./linux-64`)
- `conda index` on the folder
- host that

This leaves an installable snapshot which can just be used by all the standard tooling.

**Comment by hoodmane** [comment]
Thanks for the feedback @bollwyvl.

> So if the output of `micropip.list` that could feed into `loadpackage`, grabbing everything in parallel, that would feel great.

Yeah I think you asked for this before and I still have this in mind. I even implemented this on a branch, but it's waiting on other stuff.

> I think it is important to be able to provide lists of files. So `indexUrl` could accept one or more URLs.

Yup, sounds good. We just have to double check there are no conflicts.

> having the return value be an exact listing (e.g. with versions, or all the way to urls with sha fragments) of what was installed which could be saved and handed back to an install method (or a packages.json builder) would be fabulous.

I think it might be most appropriate to add another api for this. I think returning simpler status info from `loadPackage` is more sensible: for the "list" or "freeze" method, you really want to see info about _all_ installed packages. For the result to loadPackage you want to see if the current batch succeeded, what list of things were installed, what errors occurred.

**Comment by mahmoud** [comment]
Hey! Just catching up on [the roadmap](https://pyodide.org/en/stable/project/roadmap.html) and had a question/comment that seems to fit here:

**Might it be possible to load a prebaked virtualenv in the future?** 

I see a command which creates the env in #2976, but if I have pre-resolved all my packages, might it be better to have them packaged as a single archive to cut down on network requests?

For context, I maintain a little SPA built on PyScript. I was hoping that a move to Pyodide might get me the control necessary to speed up loads via prebaking the dependencies. Here's the URL in case that's any help: https://yak.party/glompad/

Thanks for all your great work!

**Comment by hoodmane** [comment]
If you want to speed up the loading time, I recommend using `micropip.freeze()` after the dependencies are loaded. This will write out a `repodata.json` file. You should serve this file with your bundle and pass it as the `lockFileURL`: https://pyodide.org/en/stable/usage/api/js-api.html#globalThis.loadPyodide
Then `pyodide.loadPackage` will only make requests to download the wheels themselves and won't make any extra requests for package metadata etc.

**Comment by mahmoud** [comment]
Good to know! I'm actually serving my own wheels here, prepulled with `pip download`. I see the requests are already happening all in parallel (feel free to confirm in the network inspector), so I think it's about as good as it's going to get with that approach. :)

I still suspect a prebaked venv would offer additional benefits, esp if it could be fetched in parallel to the runtime itself.

**Comment by hoodmane** [comment]
Well if you aren't satisfied with that, what about just zipping site-packages? Then you can fetch it yourself and use `pyodide.unpackArchive` to install it when the runtime is ready.

**Comment by hoodmane** [comment]
Or perhaps tar is the best format and you can allow the server / browser to manage compression / decompression.

**Comment by mahmoud** [comment]
Yep! That's what I'm considering, figured I'd point out that it seems like a common enough case (even for a really basic app, I'm already at 10+ packages). If there was a convenience function for accepting a complete site-packages, or even a snippet in the docs, that'd be great!

**Comment by ryanking13** [comment]
I think [pyodide-pack](https://github.com/pyodide/pyodide-pack) is designed for that purpose. Though it hasn't been actively developed lately.

**Comment by hoodmane** [comment]
I'm going to close this issue as completed for now since most of the things discussed here are either done or not planned. We should open new issues for any remaining action items.

**Comment by philips** [comment]
The docs still reference this bug: https://pyodide.org/en/stable/usage/loading-custom-python-code.html
