### ISSUE TITLE
Measure available memory in WASM environement

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#205]
There was a preliminary (unsuccessful) attempt to measure the available memory in https://github.com/iodide-project/pyodide/pull/165. As suggested by @mdboom ,

> Something that might work better would be something that works inside the Javascript environment, like perfomance.memory (Chrome only, unfortunately). You can also get the size of the Wasm heap using Module.HEAPU8.byteLength (but that doesn't tell you how much of it is used). I haven't tried this, but it looks like malloc_stats and mallinfo are available to us in emscripten. That should tell us how much free memory we have on the Wasm side. To be accurate, you probably need to use both (the Wasm and JS sides) -- that's fine if that's Chrome-only at least as a rough guide.

There is a relevant example in emscripten [`tests/mallinfo.cpp`](https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/mallinfo.cpp) that it might be sufficient to adapt. 

Also since the file-system is in memory, there maybe be a link with free/occupied file system space (not sure). For the record, `os.statvfs` which can be used to obtain used disk space, in Pyodide produces arbitrary output because of [the way `statfs` is implemented in emscripten](https://github.com/kripken/emscripten/blob/22fff84490047a1e741187afe3d76855e9db9d4d/src/library_syscall.js#L1118), I think.

**Comment by rth** [comment]
Closing as likely out of date.

**Comment by hoodmane** [comment]
I was just wondering how to do this recently. I haven't found anything that actually reports the amount of allocated memory. But I think if the linear memory expands quite a lot, then the majority of the memory is probably allocated so measuring the size might be a good proxy in that case?

**Comment by rth** [comment]
> But I think if the linear memory expands quite a lot, then the majority of the memory is probably allocated so measuring the size might be a good proxy in that case?

Good idea. With the default value of [`MEMORY_GROWTH_GEOMETRIC_STEP`](https://emscripten.org/docs/tools_reference/settings_reference.html?highlight=environment#memory-growth-geometric-step) it sounds like worst case scanario once the memory started to grow is a 20% error, so probably around 10% error (over-estimated) on average.

**Comment by hoodmane** [comment]
I guess the big limitation of this is that it can only measure peak memory usage.
