### ISSUE TITLE
0.19 release

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2057]
Opening an issue to track the 0.19 release.

I think we are fairly ready to make the 0.19.0 release. Ideally, the following would be nice to do before the 0.19 alpha release (but not critical),
 - update browser versions used for testing https://github.com/pyodide/pyodide/pull/1952 
 - which should hopefully unblock emscripten update https://github.com/pyodide/pyodide/pull/2035
 - run the update `meta.yaml` script for all pure python packages 

For instance, maybe we could plan to have a
 - A release candidate 0.19.0rc0: 2021/12/22 or 23  -> to make it easier still use the main branch up to the final release
 - A final release 0.19.0: 2021/12/30
 
?

cc @hoodmane

**Comment by rth** [comment]
> These APIs can benefit many users, so I think it would be great to update documentation of using those APIs before releasing 0.19.

Yes, definitely. Thanks for mentioning it @ryanking13 !

**Comment by rth** [comment]
The 0.19.0a1 was released by @hoodmane yesterday, but we probably still address some of the above topics before the release, and certainly the documentation.

**Comment by rth** [comment]
I think we are good to go for the 0.19.0 release. The only remaining thing is to write a short blog post with major highlights from this release. If you has bandwidth @hoodmane @ryanking13 feel free to start it, otherwise I can look into it tomorrow.

**Comment by hoodmane** [comment]
Okay, I will try to get to it.

**Comment by hoodmane** [comment]
Maybe I will update the roadmap a bit too.

**Comment by hoodmane** [comment]
Okay I made a very rough sketch of some release notes:
https://github.com/pyodide/pyodide-blog/pull/18
