### ISSUE TITLE
SymPy Beta

### ISSUE THREAD

**Issue by eagleoflqj** [pyodide/pyodide#2075]
Could [SymPy Beta](https://github.com/eagleoflqj/sympy_beta) be added to related project list? It's a fork of [SymPy Gamma](https://github.com/sympy/sympy_gamma). Django backend is replaced by Pyodide.

**Comment by rth** [comment]
Yes, definitely, please open a PR to add it to https://github.com/pyodide/pyodide/blob/main/docs/project/related-projects.md

Very nice project!
