### ISSUE TITLE
Pandas plot error in 0.19.0a1

### ISSUE THREAD

**Issue by leopsidom** [pyodide/pyodide#2089]
## 🐛 Bug

When trying to plot with pandas in the latest console, we get the following error:

> ModuleNotFoundError: No module named 'pkg_resources'

### To Reproduce

Try the following in the latest console: https://pyodide.org/en/latest/console.html

```
import pandas as pd
import matplotlib
df=pd.DataFrame({'x': [1,1,1,2,2,2], 'y': [1,1,2,2,3,4]})
df.plot(kind='bar')
```

while this works fine in the stable version: https://pyodide.org/en/stable/console.html

### Expected behavior

The above code should not give an error

### Environment

- Pyodide Version: 0.19.0a1
- Browser version: Chrome  96.0.4664.110
- Any other relevant information:

### Additional context

This is likely due to a bug in the pandas version pyodide upgraded to. And this commit might have fixed it: https://github.com/pandas-dev/pandas/pull/42410/files

**Comment by hoodmane** [comment]
Thanks @leopsidom! The issue is that this version of `pandas` depends on `setuptools` but we forgot to include that dependency.

**Comment by leopsidom** [comment]
Thanks for the quick fix @hoodmane. I think maybe we could use the chance to upgrade pandas from 1.3.4 to 1.3.5 as well: https://pypi.org/project/pandas/1.3.5/#files. It will be cool if there's a mechanism to automatically pick up the patch version upgrade in pyodide.

**Comment by hoodmane** [comment]
> we could use the chance to upgrade pandas from 1.3.4 to 1.3.5 as well

Sure, done.

> It will be cool if there's a mechanism to automatically pick up the patch version upgrade in pyodide.

Well we have `mkpkg --update` which helps a lot but could certainly be better. I am hoping to do more work on the build system for 0.20. Keeping up with package updates is getting easier since we have significantly reduced the number of patches.
