### ISSUE TITLE
micropip.list() is not a thing that exists.

### ISSUE THREAD

**Issue by S10MC2015** [pyodide/pyodide#2092]
## 📚 Documentation

https://pyodide.org/en/latest/usage/api/micropip-api.html#micropip.list

![image](https://user-images.githubusercontent.com/30575036/148768275-c103b8c2-5f0f-48a1-94f5-86913165594d.png)

**Comment by ryanking13** [comment]
Thank you for the report! Which version of the Pyodide are you using?

`micropip.list()` will be added at version `0.19.0`, and current stable version of Pyodide is `0.18.1`, so `micropip.list()` won't be exist if you are using the stable version.

**Comment by rth** [comment]
To add more details to the above response, `latest` documentation corresponds to the `main` dev branch. While stable docs is https://pyodide.org/en/stable/usage/api/micropip-api.html and doesn't have that function.

> micropip.list() will be added at version 0.19.0

The release will happen in a couple of days, but you can already use it now with the 0.19.0a1 pre-release.

Closing as answered, but don't hesitate to comment further.

**Comment by S10MC2015** [comment]
Ah, sorry. Thanks for the help.
