### ISSUE TITLE
Handle packages that are not built with setuptools

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2096]
## 🚀 Feature

Handle Python package builds that use other tools like `meson`, `flit`, etc instead of `setuptools` for their builds.

### Motivation

The development branch of Scipy can be built with meson. `typing-extensions` is built using `flit` not using `setuptools`. `distlib` is built using itself via a bootstrap process. We currently assume that every package is built with setuptools, but this is increasingly not always the case.

**Comment by ryanking13** [comment]
We now support packages with other build systems including meson.
