### ISSUE TITLE
CI Pre-build docker image not deploying on tags

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2101]
There was an issue with deploying the pre-build docker image during last release,
https://github.com/pyodide/pyodide/runs/4768642291
```
error: invalid tag "pyodide/pyodide:": invalid reference format
Error: buildx failed with: error: invalid tag "pyodide/pyodide:": invalid reference format
```
which is an indication that in
https://github.com/pyodide/pyodide/blob/main/.github/workflows/prebuilt_docker_image.yml#L36
`github.event.inputs.version` needs to be replaced by the tag value. I couldn't test this part, because it requires creating a tag in the repo (and I haven't managed to make GH Actions to work in a fork).

cc @ehfd

**Comment by ryanking13** [comment]
Docker images can be updated often (whenever we update Dockerfile or requirements.txt), so I think using git tag value is not a good way.

I think we better figure out why `github.event.inputs.version` was empty. It should be a srting that be manually set when running the workflow.

**Comment by rth** [comment]
So the `pyodide-env` docker image can indeed be updated any time and has a manual trigger (that part works).
For the `pyodide` docker image with pre-build packages we usually only update it on releases, as it gives a reference point for people who don't want to spend time building from sources. In which case building it only on tags makes sense IMO.  One of the ideas of this is to reduce the number of manual actions needed for the release. 

> I think we better figure out why github.event.inputs.version was empty

Well, I think because it's indeed the manual trigger input, while we are not using it for releases.

**Comment by ryanking13** [comment]
> For the `pyodide` docker image with pre-build packages we usually only update it on releases, as it gives a reference point for people who don't want to spend time building from sources. In which case building it only on tags makes sense IMO. One of the ideas of this is to reduce the number of manual actions needed for the release.

Oops. Sorry, I misunderstood. I was thinking of `pyodide-env` docker image.

**Comment by ehfd** [comment]
> which is an indication that in
> https://github.com/pyodide/pyodide/blob/main/.github/workflows/prebuilt_docker_image.yml#L36
> `github.event.inputs.version` needs to be replaced by the tag value. I couldn't test this part, because it requires creating a tag in the repo (and I haven't managed to make GH Actions to work in a fork).

It's a bit complicated than what I previously expected.
https://github.community/t/how-to-get-just-the-tag-name/16241
This is the solution.

**Comment by rth** [comment]
Thanks @ehfd, if you can make a PR that would be perfect ! We will test it for the future 0.19.1 release :)

For now, I'll trigger the pre-built image build manually for 0.19.0 in an upstream branch.

**Comment by ehfd** [comment]
OK, I'll leave https://github.com/pyodide/pyodide/blob/main/.github/workflows/docker_image.yml alone since that's manual trigger anyways.
