### ISSUE TITLE
Bug with SciPy.stats.mannwhitneyu

### ISSUE THREAD

**Issue by anchit-sadana** [pyodide/pyodide#2143]
## 🐛 Bug
If I try to run scipy.stats.mannwhitneyu, the script gives me a ```Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.The cause of the fatal error was: RuntimeError: null function or function signature mismatch
Look in the browser console for more details.``` on the REPL.
### To Reproduce

Run in browser REPL
```
import numpy as np
import scipy.stats as stats 
stats.mannwhitneyu(np.random.rand(10), np.random.rand(10))
```
### Expected behavior
The stat test runs successfully and returns a MannwhitneyuResult object with a test statistic  and a pvalue
### Environment

- Pyodide Version:  0.19.0
- Browser version:97.0.4692.99
- Any other relevant information: I tried doing this in the REPL after it was failing in a script on a website 

### Additional context

I think some other tests in scipy.stats may also be broken 
<img width="1422" alt="Screen Shot 2022-01-28 at 3 40 36 PM" src="https://user-images.githubusercontent.com/70300199/151636079-0624145c-e673-4899-84c6-821d68e5fa3c.png">

**Comment by ryanking13** [comment]
Thanks for the report! This issue has been fixed with #2109. It is not released yet, but you can test it with the [latest console](https://pyodide.org/en/latest/console.html).
