### ISSUE TITLE
Smaller Prelude for use as a embedded scripting language

### ISSUE THREAD

**Issue by clinuxrulz** [pyodide/pyodide#2155]
## 🚀 Feature

Smaller Prelude for use as embedded scripting language. Currently pyodide-build-0.19.0.tar.bz2 uncompressed is over 300Mb.

### Motivation

You have developed a web-app and you want to allow your users to create plugins or extend functionality for your app using Python. And you only want to expose a core set of functions to python that interact with your app. That is you want to sandbox the user provided scripts.

### Pitch

Additionally supply stripped down versions of pyodide-build-0.19.0.tar.bz2, or even supply instructions in the documentation on which files are not necessary inside pyodide-build-0.19.0.tar.bz2 for a minimalistic prelude.

**Comment by hoodmane** [comment]
As an absolute minimum, you need to include the following files:

| File         | Size    | 
|--------------|-----------|
| pyodide.js | 29.5 kb |
|packages.json | 15.6 kb |
|pyodide_py.tar | 100 kb | 
|pyodide.asm.js | 1.90 mb | 
|pyodide.asm.data | 5.07 mb | 
|pyodide.asm.wasm | 9.06 mb |
|distutils.js	| 19 kb | 
|distutils.data | 503 kb|

This is a total of around 17 megabytes, or around 7 megabytes compressed.

**Comment by clinuxrulz** [comment]
@hoodmane Thank you very much!

**Comment by clinuxrulz** [comment]
What about sandboxing? So the script can not get a hold of the session state and cookies for security reasons.

**Comment by clinuxrulz** [comment]
Actually don't worry about that last one. Wrapping script execution in a web worker will do the trick for sandboxing.

**Comment by hoodmane** [comment]
For sandboxing you can pass a `globals` argument to `loadPyodide`.

**Comment by clinuxrulz** [comment]
Thanks again

**Comment by phorward** [comment]
Hello @clinuxrulz, maybe you might use the [get-pyodide.py script](https://github.com/viur-framework/flare/blob/main/tools/get-pyodide.py) from Flare for getting a custom, smaller Pyodide prelude from the CDN-served distro. Feel free for chaning the file lists there.
