### ISSUE TITLE
Include type definitions in Pyodide npm package

### ISSUE THREAD

**Issue by reminjp** [pyodide/pyodide#2161]
## 🚀 Feature

Pyodide's JavaScript API is implemented in TypeScript, but the [npm package](https://www.npmjs.com/package/pyodide) doesn't contain any type definitions. How about including type definitions in the npm package? 

### Motivation

If a package doesn't have type definitions, it is hard to use.

### Pitch

I want to import type definitions from Pyodide npm package.

### Alternatives

Write type definitions in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

### Additional context

**Current (0.19.0) `pyodide` in `node_modules`**
<img width="306" alt="image" src="https://user-images.githubusercontent.com/9990535/153580134-1e6c51fe-a85f-4990-8410-4dda639f134d.png">
[`index.d.ts`](https://github.com/pyodide/pyodide/blob/main/src/js/index.d.ts) is almost empty.

**Comment by hoodmane** [comment]
I am interested in working on this for the next release. @rth and I don't really know that much about typescript (or how typescript projects are usually organized), so help from someone who knows more would probably speed things up. After #2133, the situation should be a lot better.

**Comment by rdrgn** [comment]
I just realized that #2133 hasn't been released yet! Thank you to all the developers. It may be too late, but I want to help if there is anything I can do.

**Comment by hoodmane** [comment]
I think there are a lot of improvements that could be made, some of which are not very difficult. If you could start by trying out the type definitions and reporting the problems you have that would be great. There are still a lot of things typed as any which could be typed more specifically. It would be great to add a schema for `packages.json`. 

In the long term it would be cool to add types for some python objects (see #2162) but this is a more involved project.
