### ISSUE TITLE
Add wrapt

### ISSUE THREAD

**Issue by henryiii** [pyodide/pyodide#2164]
## 🐍 Package Request

- wrapt / latest :
- https://pypi.org/project/wrapt/ :
- Package Dependencies that needs to be resolved first: None.

Note that https://github.com/GrahamDumpleton/wrapt/blob/develop/setup.py tries to disable pure Python extensions on some platforms, I'd probably try building them first before letting them be disabled, as I'm pretty sure they are easy to compile.

See https://github.com/GrahamDumpleton/wrapt/issues/206

**Comment by hoodmane** [comment]
At a glance I would bet this is easy.

**Comment by hoodmane** [comment]
The setup.py logic decides to build the C extensions in our case so we don't need to do anything extra.
