### ISSUE TITLE
Update to Python 3.10

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2190]
Python 3.10 was released on October 04, 2021 so 4 months later packages had a chance to release Py3.10 compatible releases (or will soon ) and we can probably update to 3.10 as well.

Also, see analysis in https://github.com/pyodide/pyodide/issues/978#issuecomment-1043335232

**Comment by henryiii** [comment]
Tiny related question: what is the minimum version of Python for the code in Pyodide? Assuming it is currently 3.9, would you mind a PR that updated to at least 3.7+ and added `from __future__ import annotations` and related typing syntax simplification?

**Comment by hoodmane** [comment]
> would you mind a PR that updated to at least 3.7+ and added from `__future__ import annotations` and related typing syntax simplification?

I am not sure exactly what you mean. We made no attempt to maintain compatibility with Python < 3.9 and I think we use some new-in-3.9 C APIs in `src/core/jsproxy.c` as part of the dynamic subclass generation code. If you have some simplification in mind that restricts our Python version to a recent one, we are happy to accept it.

**Comment by rth** [comment]
> Assuming it is currently 3.9, would you mind a PR that updated to at least 3.7+

You mean with pyupgrade? Yes, sure. The minimal version is indeed 3.9+ . It's specified for the build in https://github.com/pyodide/pyodide/blob/main/pyodide-build/setup.cfg#L21 but we should bump that to 3.9

> and added from __future__ import annotations and related typing syntax simplification

Feel free to open a PR to propose it. Personally, I don't really get the practical impact of PEP 563: it's already possible to forward reference classes by quoting their names, and I imagine the computational cost for non delayed annotations evaluation would be negligible in our application. Unless I'm missing something. Otherwise yes, +1 for better typing in Python.

**Comment by ryanking13** [comment]
We've updated our Python veresion to 3.10, which will be included in in v0.20.0 (#2225), closing.
