### ISSUE TITLE
Web3 / DeFi / Crypto / Privacy / GameFi

### ISSUE THREAD

**Issue by psytron** [pyodide/pyodide#2199]
Seems to me Pyodide would quickly absorb a lot of community from Web3 / DeFi / Crypto / Privacy / GameFi , but most of these libraries don't work in Pyodide because of missing cryptography.  To meet this demand there is movement towards porting existing Python data science tools to JavaScript. Is there a practical or future facing solution to this?

**Comment by rth** [comment]
I proposed the way forward for adding the cryptography package in https://github.com/pyodide/pyodide/issues/761#issuecomment-1046618945 which indeed has a number of applications. Don't hesitate to comment there.
