### ISSUE TITLE
Request for including `multiprocessing.pool.Pool`

### ISSUE THREAD

**Issue by exKAZUu** [pyodide/pyodide#2210]
To use `flake8` APIs, I've tried the following code

```
import micropip
await micropip.install('flake8')
from flake8.api import legacy as flake8
```

but the following error is shown due to missing `multiprocessing.pool.Pool`.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.9/site-packages/flake8/api/legacy.py", line 12, in <module>
    from flake8.main import application as app
  File "/lib/python3.9/site-packages/flake8/main/application.py", line 15, in <module>
    from flake8 import checker
  File "/lib/python3.9/site-packages/flake8/checker.py", line 661, in <module>
    ) -> Optional[multiprocessing.pool.Pool]:
AttributeError: 'NoneType' object has no attribute 'pool'
```

Could you add `multiprocessing.pool.Pool` in addition to `multiprocessing.Pool` ?

Note: I've also reported on https://github.com/PyCQA/flake8/issues/1562

**Comment by ryanking13** [comment]
The Pyodide side solution would be monkey-patching `_multiprocessing` module.
Note that Pyodide cannot create a process so the functionalities of multiprocessing won't work.

```python
>>> import sys
>>> sys.modules['_multiprocessing'] = object
>>> from multiprocessing.pool import ThreadPool
```

See: https://github.com/pyodide/pyodide/issues/1603#issuecomment-850794345

**Comment by exKAZUu** [comment]
Thank you so much! monkey-patch is enough for working `flake8` (and similar libraries).
