### ISSUE TITLE
Tiny issue in MWE for new packages

### ISSUE THREAD

**Issue by gabrielfougeron** [pyodide/pyodide#2211]
Hi,

I think there is a tiny typo in the MWE for a meta.yaml file at https://pyodide.org/en/stable/development/new-packages.html .

A key reads: `sha265: <sha256>` , and it should probably be:  `sha256: <sha256>` .

Tiny error as I said, but better no one loses any sweat over it (as I just have ^^)

**Comment by ryanking13** [comment]
Ohh.. nice catch, thanks @gabrielfougeron! Are you interested in making a PR to fix it?

**Comment by gabrielfougeron** [comment]
Hi,

I think I just did ==> #2213 . Please tell me if I've done aything wrong  / what I've done wrong. It's my first time contributing to any kind of open source project.
