### ISSUE TITLE
Error building pillow

### ISSUE THREAD

**Issue by gabrielfougeron** [pyodide/pyodide#2212]
Hi,

I get the following error building pillow in wsl2 : 
`
OSError: [Errno 39] Directory not empty: '/mnt/c/Downloads/pyodide-main/packages/pillow/build/Pillow-9.0.0' -> '/mnt/c/Downloads/pyodide-main/packages/pillow/build/pillow-9.0.0'    
`

**Comment by gabrielfougeron** [comment]
Thanks for your extremely fast answer. Leaving the wsl2 is not really an option for me right now, I'll try to move out of '/mnt' as you suggested!

**Comment by hoodmane** [comment]
> Leaving the wsl2 is not really an option for me right now

I generally found that wsl2 works quite well as long as you are not in `/mnt`. It's just slow.

**Comment by gabrielfougeron** [comment]
OMMMMGGGG !! this is so much quicker thank you !! :-)
