### ISSUE TITLE
PKG add lazy-object-proxy

### ISSUE THREAD

**Issue by mrMoonpenguin** [pyodide/pyodide#2222]
## 🐍 Package Request

- Package Name and Version : lazy-object-proxy / latest
- Package URL : https://pypi.org/project/lazy-object-proxy/

Needed to get PyLint running.

**Comment by hoodmane** [comment]
Looks like an easy task. It's a pure Python package.

**Comment by ryanking13** [comment]
> Looks like a simple task. It's a pure Python package.

No, it looks like [it contains some C codes](https://github.com/ionelmc/python-lazy-object-proxy/search?l=c).

**Comment by hoodmane** [comment]
Ah yeah. In any case using `mkpkg lazy-object-proxy` and replacing the dashes with underscores in the import name it seems to build successfully, import successfully, and pass a couple of tests I selected arbitrarily from the test suite.

**Comment by mrMoonpenguin** [comment]
Quite new to this, so am not following exactly. So, I understand running `pyodide-build mkpkg lazy-object-proxy` to create the `meta.yaml` file, but am not sure what exactly you mean with replacing the dashes with underscores in the import name...

**Comment by hoodmane** [comment]
The generated meta.yaml file has a part r looks as follows:
```yaml
test:
  imports:
    - lazy-object-proxy
```
It should be `lazy_object_proxy` instead of `lazy-object-proxy` but no other changes are needed to the automatically generated file.

**Comment by mrMoonpenguin** [comment]
Oh, I see, thanks!

Interestingly enough this is enough to get PyLint to (somewhat) work in Pyodide.
