### ISSUE TITLE
is there any way to register a python model?

### ISSUE THREAD

**Issue by yxdragon** [pyodide/pyodide#2244]
I need scipy.ndimage to do some processing. for scipy need a long time to load. So I wrote [npimage](https://[github.com](https://github.com/Image-Py/npimage)/Image-Py/npimage), implement some method in scipy.ndimage with pure numpy.

now the question is:
the repo require scipy is a third-part package in pypi, I do not want to modify and republic it. So is there any way to register a python model? may be in this way:
```python
import npimage as ndimage
register_package('scipy.ndimage', npimage)

# import the third-part package, then link the registed npimage.
```

I see we can register a js model, So can I register a python model?

another question: is there any way make micropip force update? It seems that I need to clean browser's cache.

**Comment by hoodmane** [comment]
I think you can just do the same thing you would in normal Python:
```py
import sys
import scipy
sys.modules["scipy.ndimage"] = npimage
```

**Comment by rth** [comment]
The above answer should work indeed, closing. Please comment if it doesn't.
