### ISSUE TITLE
I want to mirror the numpy in my own cdn.

### ISSUE THREAD

**Issue by yxdragon** [pyodide/pyodide#2250]
I want to mirror the depend lib on my own cdn (to speed up the loading). for example, numpy.
how can I build a numpy.whl and use "micropip.install('xxxx.whl')"
I look for the numpy package source : https://github.com/pyodide/pyodide/blob/main/packages/numpy/meta.yaml
there is a zip url, and some patches. How to make the whl?

**Comment by hoodmane** [comment]
From root directory run `PYTHONPATH=pyodide-build python -m pyodide_build buildpkg packages/numpy/meta.yaml`. The wheel will be in `packages/numpy/dist`.

Also, is there a reason you can't just download the wheel from our cdn and place it into yours?

**Comment by yxdragon** [comment]
Do I need compiler to build the whl? where can I download your whl? I just find https://files.pythonhosted.org/packages/fb/48/b0708ebd7718a8933f0d3937513ef8ef2f4f04529f1f66ca86d873043921/numpy-1.21.4.zip in the yaml.

**Comment by hoodmane** [comment]
The wheels are only on the development branch, #2027 will be included in pyodide v0.20. In v0.19 you need a pair of files, `numpy.js` and `numpy.data` available here:
https://cdn.jsdelivr.net/pyodide/v0.19.1/full/numpy.js
https://cdn.jsdelivr.net/pyodide/v0.19.1/full/numpy.data

**Comment by yxdragon** [comment]
if you could look into this and let us know that'd be great =)

I do the test:
```html
 async function main(params) {
                log('Start!')
                pyodide = await loadPyodide({
                    indexURL: "https://cdn.jsdelivr.net/pyodide/v0.19.1/full/",
                });

                log('Install micropip!')
                await pyodide.loadPackage("micropip");

                await pyodide.runPythonAsync(`
                    import micropip
                    from js import log
                    log('Install numpy!')
                    await micropip.install(['numpy', 'planer', 'planer_zoo'])

                    log('Import numpy!')
                    from pyodide import to_js
                    import numpy as np
                    from time import time
                    import os, zipfile
                    import planer
                    from planer_zoo.ocr import paddleocr
                    
                    log('Download model!')
```

the result is:
load Pyodide: 3s
load Micropip: 1s
Install Numpy: 10s
import Numpy: 0

what does micro pip do? just download? or do some other thing such as unzip?
I think move numpy.whl on native cdn would works. and I would have a try.

but how can I install numpy from the js and data url you give me?

**Comment by hoodmane** [comment]
> but how can I install numpy from the js and data url you give me?

In v0.19, with `pyodide.loadPackage("https://cdn.jsdelivr.net/pyodide/v0.19.1/full/numpy.js");`.

**Comment by yxdragon** [comment]
```python
async function main(params) {
                log('Start!')
                pyodide = await loadPyodide({
                    indexURL: "https://cdn.jsdelivr.net/pyodide/v0.19.1/full/",
                });

                // pyodide.registerJsModule('adapter', {'runner': runner});
                log('Install micropip!')
                await pyodide.loadPackage("micropip");

                await pyodide.loadPackage("https://cdn.jsdelivr.net/pyodide/v0.19.1/full/numpy.js")

                await pyodide.runPythonAsync(`
                    import micropip
                    from js import log
                    log('Install numpy!')
```

but the program crush in pyodide.loadPackage("https://cdn.jsdelivr.net/pyodide/v0.19.1/full/numpy.js")

Is there any wrong in my code? Sorry, it is maybe a foolish question. I am aware of python, but not js.

**Comment by yxdragon** [comment]
I had try native cdn. but it does not reduce the cost (and the data file is not very large). So I think micro pip do more than download.

do you have other advice to up speed the loading?

**Comment by hoodmane** [comment]
`micropip` also does dependency resolution. You can load wheel files with `pyodide.unpackArchive`. I'd recommend something like:
```js
let promises = [fetch("planer_wheel.whl"), fetch("planer_zoo.whl")].map(p => p.then(res => res.arrayBuffer()));
await pyodide.loadPackage("numpy");
let results = await Promise.all(promises);
for(let result of results){
	pyodide.unpackBuffer(result);
}
```

**Comment by yxdragon** [comment]
planer is my cnn framework, just need numpy
and planer_zoo is planer's model zoo, just need planer.
planer and planerzoo are light package, less than 10k.

**Comment by rth** [comment]
> So I want to try some cdn in china native.

FYI JSdelivr, which we use, [already uses QUANTIL CDN](https://www.jsdelivr.com/network) in China which has lots of points of presence. But a different CDN is certainly worth trying.

**Comment by yxdragon** [comment]
@rth I had tried. but it does not reduce the cost. for numpy.data is only 7M, so the main cost is not downloading.
I want initial page (on phone) in 5 second, but now, pyodide and numpy need 15 second. (scipy need about 1 minute, but I can remove the dependence)

**Comment by rth** [comment]
Yes the bottleneck for init is WASM compilation time not file load time itself, particularly for packages with lots of C extensions (e.g. numpy, scipy etc).

Closing in favor of https://github.com/pyodide/pyodide/issues/2288. Don't hesitate the open there.
