### ISSUE TITLE
What's "document.create_proxy"?

### ISSUE THREAD

**Issue by s4i** [pyodide/pyodide#2261]
## 📚 Documentation

https://github.com/pyodide/pyodide/blob/4f8b0a03447531a416944ee24beee63f6a8ebc4f/docs/usage/type-conversions.md?plain=1#L440

**Comment by hoodmane** [comment]
That's a typo, should be `pyodide.create_proxy`. `document` is the js document object so it will have the normal attributes the dom document has.

**Comment by hoodmane** [comment]
Thanks for pointing it out!

**Comment by s4i** [comment]
I understand.
