### ISSUE TITLE
Minimal examples?

### ISSUE THREAD

**Issue by akloster** [pyodide/pyodide#228]
I'm interested in experimenting with using pyodide for actual web applications. It's not quite clear to me how to load pyiodide and run Python code. Or how to cut down on the standard library etc to save a little on size. I know that a Python-in-Wasm solution will clock in at a couple of Mb per Page/App but maybe a little can be gained here and there.

**Comment by akloster** [comment]
I've made some progress. I created a simple Flask app to serve the static files. Next problem is to serve the actual application code. Under the current setup it would be a bit impractical to build it as a python package, so I am building a vfs archive of the code, which can be rebuilt upon changes.

The basic idea is to let the Python code manage the state of a React application. I'm also looking into how to use the async/await syntax to interface with asynchronous javascript APIs. At first I thought I could leverage asyncio for this, but I think it will look a bit different. The goal is not so much to port existing asyncio code to the wasm runtime, but rather to offer a unique API for use in wasm applications.

**Comment by rth** [comment]
> Under the current setup it would be a bit impractical to build it as a python package, so I am building a vfs archive of the code, which can be rebuilt upon changes.

It is impractical to build it as a standalone python you don't want to repeatedly run the pyodide build when developing your application? I'm not very familiar with VFS, how do you mount a volume with the code? It might be worthwhile documenting that for other users.. 

Regarding async, yeah asyncio is not currently supported: https://github.com/iodide-project/pyodide/issues/97 might be somewhat related, and @mdboom investigated some of it in https://github.com/iodide-project/pyodide/pull/187 ...

**Comment by mdboom** [comment]
For async, the default implementation of asyncio in Python uses `select`, which the browser environment does not (will not?) have.  I think it's theoretically possible to write your own mainloop for the Python interpreter using, perhaps, `setTimeout` instead.  But I haven't spent much time looking at that.

Promises in Javascript work really well in Python, however, thought obviously the syntax isn't as nice.  You can achieve a lot of the same goals that way, though.

**Comment by akloster** [comment]
I used the basic file_packager script to bundle a couple of py files together and then import them on the page. The alternative would be to make a python package and somehow use the package compilation process.

For async/await, yes, I think I will be hacking something together with Promises and setTimeout and XMLHTTPRequests and the like.

**Comment by mdboom** [comment]
If you can put a wheel on PyPI, there is experimental support for `pip` installing packages.  Just need to get this across the finish line: #147

**Comment by akloster** [comment]
After some further research I think BrowserFS would be a good way to go. If I can get the HTTPRequest Filesystem to overlay my Python modules on the root filesystem, that would be ideal, because I don't need any emscripten toolchain to refresh the code.

I haven't figured out yet how to use BrowserFS with Pyodide.

**Comment by mdboom** [comment]
emscripten already provides an in-browser filesystem abstraction of its own, so I'm not sure BrowserFS will play well with it.

You could write a Python script that downloads a zip file and expands it into the filesystem, though.  That's basically what the `micropip` implementation in #147 does.  Look at the `fetch_url` function to get the data and `extract_wheel` function to expand it into the filesystem.  The rest of the complication there is just dealing with PyPI.  If you're just extracting a known zipfile from a known url, things should be much easier.

**Comment by akloster** [comment]
Hm, downloading a zipfile and extracting/importing that should work. But I'm getting an exception (without a name or value) from this code:
```python
with open("test.txt", "wt") as f:
    f.write("hello word")
```

Chrome complains with this:

```
pyodide.asm.js:8 Uncaught (in promise) Error: No exception type or value
    at _hiwire_throw_error (pyodide.asm.js:8)
    at :5000/wasm-function[359]:1585
    at :5000/wasm-function[348]:135
    at Object.__pyimport (pyodide.asm.js:8)
    at Object.pyimport (pyodide.asm.js:8)
    at languagePluginLoader.then ((index):21)
```

**Comment by basvandertol** [comment]
@akloster @mdboom 
See #613 for a minimal example on using BrowserFS with pyodide

**Comment by hoodmane** [comment]
@rth maybe close this in favor of #1498?
