### ISSUE TITLE
CI Use Github Actions more

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2280]
We are currently using two CI services: CircleCI and Github Actions.

- CircleCI: docker-based build test and full test suites.
- Github Actions: for non-docker-based build test and linting.

Though CircleCI worked quite well for our purpose, we've also experienced some problems in using CircleCI. (e.g. limited job running time and resources, mysterious hangs, unstable build time)

The main blocker of adopting GHA was that it doesn't support partial re-runs for failed jobs, but recently (yesterday) Github announced that [they now support partial re-runs](https://github.blog/2022-03-16-save-time-partial-re-runs-github-actions/). So I think it's time to consider using GHA more for our project.

For a start, I think we can let CircleCI as is and run more jobs in GHA for a parallel with different build/test settings. For example, docker-based / non-docker-based build (same as we are doing now) and selenium / playwright testing. And if we find that one of the services is more stable and useful, we can migrate one into the other.

WDYT?

**Comment by hoodmane** [comment]
One other thing I like about CircleCI is the test failure summary for example:
https://app.circleci.com/pipelines/github/hoodmane/pyodide?branch=multiple-load2&filter=all
Is there any way to give junitxml to gha and make it produce summaries like that?

**Comment by ryanking13** [comment]
> One other thing I like about CircleCI is the test failure summary for example: https://app.circleci.com/pipelines/github/hoodmane/pyodide?branch=multiple-load2&filter=all Is there any way to give junitxml to gha and make it produce summaries like that?

It seems like there is third-party action which does [similar thing for GHA](https://github.com/marketplace/actions/publish-unit-test-results), but we will need some trial and errors.

**Comment by hoodmane** [comment]
Sounds good. What about rerun with ssh? Is there anything like that?

**Comment by ryanking13** [comment]
> Sounds good. What about rerun with ssh? Is there anything like that?

I guess [this action](https://github.com/marketplace/actions/debugging-with-tmate) will do the job?

**Comment by hoodmane** [comment]
Cool =)

**Comment by hoodmane** [comment]
Another setting that I like that we have with circleci is that it will trigger on my branches even if I haven't opened a PR. Presumably this is also possible to set up with github actions?

**Comment by ryanking13** [comment]
> Another setting that I like that we have with circleci is that it will trigger on my branches even if I haven't opened a PR. Presumably this is also possible to set up with github actions?

Yes, of course. For now we are running github actions [only when it's pushed / pull requested to the main branch](https://github.com/pyodide/pyodide/blob/59ace09c11032bd85e4c40636428b06212f61d0d/.github/workflows/main.yml#L4-L7), but we can modify that.

**Comment by hoodmane** [comment]
Another missing feature: your fantastic recent work on the docker images allows me to build a docker image against firefox beta like:
```sh
docker build . --build-arg FIREFOX_VERSION="99.0b5"
```
How can I control which firefox version github actions is using? I guess this is probably a feature that would need adding. Does `runs-on: ubuntu-latest` just bring a version of firefox along with it?

**Comment by ryanking13** [comment]
> I guess this is probably a feature that would need adding. Does `runs-on: ubuntu-latest` just bring a version of firefox along with it?

Yeah, as you said, it looks like we are not explicitly downloading specific versions of browser binaries for Github Actions. We should add that feature.

**Comment by hoodmane** [comment]
Some more comments:
1. On main branch, we should always run jobs to completion even if there is another commit to main before it completes.
2. Ideally, we should move the pypi deploy to circleci or make it a manual trigger. It isn't ideal to do a partial deploy as a result of a test failure.
3. It would be good to add the npm deploy to CD too since it's pretty simple

A bit off topic for this thread, @rth I think we should switch to deploying the build directory to npm instead of the `src/js` directory. I think ideally the files in `src/js` would be private...
