### ISSUE TITLE
Dart/Flutter web support

### ISSUE THREAD

**Issue by caniko** [pyodide/pyodide#2298]
### Motivation
Use package such as pandas and numpy on the web inside Flutter apps.

### Pitch
Python is quite general purpose, but my usecase is to quickly and efficiently read and serialize large data files such as xlsx, hdf, paquet inside Flutter. I am, currently, a lone developer using Python is therefore the best option.

### Alternatives
Native packages such as [df](https://pub.dev/packages/df), but these are quite limited.

### Concerns
Is it possible to read files through a web browser with the Pyodide runtime?

### Additional context
The interaction between pyodide and flutter will also need to be documented.

**Comment by ryanking13** [comment]
Thanks for the suggestion, @caniko. It looks like Dart has JavaScript interoperability, so Pyodide may work in Dart too without large modification. However, AFAIK there is no Dart developer among Pyodide core devs, so we won't be able to verify it in the near future. If you are interested in supporting Pyodide in Dart, please go ahead and share us your work.

**Comment by agriyakhetarpal** [comment]
I think this use case is now supported by [the Flet project](https://github.com/flet-dev/flet#powered-by-flutter), which uses Pyodide for the web browser side of things.
