### ISSUE TITLE
[Discussion] Deprecation policy

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2303]
Recently, we are updating our JS/Python APIs often, which results in deprecating several APIs. So I think it would be great to have some explicit deprecation policy.

Since we are in 0-based versioning, we have some free space to make breaking changes without considering backward compatibility too much. Still, having an explicit deprecation policy can help Pyodide users but also Pyodide devs, as we don't have to say "when should this API be removed?" every time.

Regarding our release cycle of around 3~4 months, I think (unless it's a critical change) **two minor version updates** between deprecation and removal would be reasonable so that we can notify users about the removal at least 6 months ago.

WDYT?

**Comment by hoodmane** [comment]
Two versions seems good for now, maybe we can increase it in the future. If you want to add something to the docs about this, that would be fantastic. Once the policy is documented, it would be good to have a system for creating runtime deprecation warnings. Annoyingly we'd probably need separate stuff for Python and Javascript APIs. 

> Since we are in 0-based versioning

I think we should be thinking about Pyodide v1.0, maybe I'll open another issue for that.

**Comment by rth** [comment]
> two minor version updates between deprecation and removal

+1 as well.
