### ISSUE TITLE
Potential FS regression in 0.20.0a1

### ISSUE THREAD

**Issue by bollwyvl** [pyodide/pyodide#2312]
## 🐛 Bug

Hooray `0.20.0a1`!

Some FS methods that work with 0.19.x _sometimes_ throw errors in the console:

---

```py
import pyodide_js
FS = pyodide_js.FS
FS.mkdir("/tmp/foo")
```

Can create:

```js
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function <lambda> at 0x31a9448>"
    at _getPtr (pyproxy.gen.ts:237:11)
    at PyProxyClass.apply (pyproxy.gen.ts:1140:32)
    at Object.apply (pyproxy.gen.ts:1017:18)
    at doCallback (pyodide.asm.js:14:336214)
    at done (pyodide.asm.js:14:336368)
```
---

```py
FS.mount(FS.filesystems.IDBFS, {}, "/home/pyodide_user/work")
FS.syncfs(True, lambda err: print(err))
```

can create

```js
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function <lambda> at 0x37d7db0>"
    at _getPtr (pyproxy.gen.ts:237:11)
    at PyProxyClass.apply (pyproxy.gen.ts:1140:32)
    at Object.apply (pyproxy.gen.ts:1017:18)
    at doCallback (pyodide.asm.js:14:336214)
    at done (pyodide.asm.js:14:336368)
    at Object.reconcile (pyodide.asm.js:14:306057)
    at pyodide.asm.js:14:302028
    at IDBRequest.index.openKeyCursor.onsuccess (pyodide.asm.js:14:303840)
```

### To Reproduce

- Try commands from [this notebook](https://github.com/jupyterlite/jupyterlite/blob/main/examples/pyolite/emscripten-filesystem.ipynb)

### Environment

- Pyodide Version:  0.20.0a1
- Browser version: Chromium 99.0.4844.82 snap, Mozilla Firefox 98.0.1
- Any other relevant information: inside jupyterlite

### Additional context

- downstream
  - issue: https://github.com/jupyterlite/jupyterlite/issues/577
  - WIP PR: https://github.com/jupyterlite/jupyterlite/pull/578
  - docs preview: https://jupyterlite--578.org.readthedocs.build/en/578/_static/lab/index.html?path=pyolite/emscripten-filesystem.ipynb

**Comment by hoodmane** [comment]
Thanks @bollwyvl! I will look into it.

> sometimes throw errors

How frequently? Any other info about what sort of sometimes?

**Comment by hoodmane** [comment]
Okay I can reproduce this.

**Comment by hoodmane** [comment]
I take it back I haven't reproduced it.

**Comment by bollwyvl** [comment]
Thanks for the speedy response. 

> what sort of sometimes

it seems like :
- The basic stuff only seems to throw  the error if I run everyhting really fast right after starting. (e.g. _Restart and Run All_)
- for the sync stuff, "basically always" though maybe i've seen it work once or twice
  - it does seem to actually _do_ the thing (put stuff into/out of indexedb), but the sync dance is kinda... complicated

> haven't reproduced it.

I think the docs site (last link in description) will be the easiest place to observe my _specific_ issue... once it builds. I'll iterate on it a bit... but can also dust off my memory of how to update pyodide tests and add a sync one (if i hadn't already)...

**Comment by hoodmane** [comment]
> `FS.syncfs(True, lambda err: print(err))`

So for callbacks, we will keep the callback alive until 1. the function returns and 2. if the function returns a promise, until that promise resolves. This doesn't really work that well with old async Javascript code that takes a callback as an argument and calls the callback when it's done, and most Emscripten APIs are written like that. Ideally, one would create a wrapper function:
```js
function syncPyodideFs(x){
	let resolve, reject;
	let result = new Promise((res, rej) => {resolve = res; reject = rej;});
	FS.syncfs(true, (x) => x === undefined ? res() : rej(x);
	return result;
}
```
or would use `create_once_proxy`:
```js
from pyodide import create_once_proxy
FS.syncfs(True, create_once_proxy(cb))
```

**Comment by bollwyvl** [comment]
Indeed, on the `sync` one, if i `pyodide.to_js` the lambda, it works.

**Comment by bollwyvl** [comment]
> create_once_proxy

that's sharp, thanks.

**Comment by bollwyvl** [comment]
> create_once_proxy

for others: it's `create_once_callable`, and have updated the linked notebook... thanks again!
