### ISSUE TITLE
ctypes patch breaks ctypes's in_dll() method

### ISSUE THREAD

**Issue by tiran** [pyodide/pyodide#2330]
## 🐛 Bug

I think that the ctypes patch https://github.com/pyodide/pyodide/blob/main/cpython/patches/0006-Don-t-dereference-function-pointer.patch is incorrect and unnecessary. It breaks the ``in_dll`` method of ctypes primitives. The ``CDataType_in_dll()`` function does not return a function pointer. It returns a global variable.

### To Reproduce

The problem can be reproduced easily in the interactive REPL at https://pyodide.org/en/stable/console.html and ``PyAPI_DATA(int) Py_OptimizeFlag;``.

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.9.5 (default, Feb 22 2022 14:12:02) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes, sys
>>> sys.flags.optimize
0
>>> ctypes.c_int.in_dll(ctypes.pythonapi, "Py_OptimizeFlag")
c_long(3223484)
```
### Expected behavior

The correct output is ``c_long(0)``.

```
Python 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes, sys
>>> sys.flags.optimize
0
>>> ctypes.c_int.in_dll(ctypes.pythonapi, "Py_OptimizeFlag")
c_int(0)
```

### Environment

- Pyodide Version: Python 3.9.5 (default, Feb 22 2022 14:12:02) on WebAssembly VM
- Browser version: Firefox
### Additional context

I can also reproduce the issue with upstream CPython 3.11 (latest head):

without patch:

```
$ node --experimental-wasm-threads --experimental-wasm-bulk-memory cpython/builddir/emscripten-node/python.js -c 'import ctypes; print(ctypes.c_int.in_dll(ctypes.pythonapi, "Py_OptimizeFlag"))'
c_long(0)
$ node ... python.js -O -c ...
c_long(1)
$ node ... python.js -OO -c ...
c_long(2)
```

With the ctypes patch:

```
$ node --experimental-wasm-threads --experimental-wasm-bulk-memory cpython/builddir/emscripten-node/python.js -c 'import ctypes; print(ctypes.c_int.in_dll(ctypes.pythonapi, "Py_OptimizeFlag"))'
c_long(3762604)
```

**Comment by hoodmane** [comment]
Indeed this seems true. I wonder why I added that patch in the first place then. I would have sworn that it fixed a crash when I was working on ctypes, but it was probably always wrong.
