### ISSUE TITLE
v0.20.0 release

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2336]
We need to merge #2333, #2334, and #2335 first and preferably I should finish and merge #2320.

The upgrade to Python 3.10 seems to have been a significant speed boost: about 15% on Firefox and 22% on Chrome. We should produce json benchmarks too though so we don't have to keep parsing them.

**Comment by ryanking13** [comment]
It would be great if we can fix an issue on deploying prebuilt docker image in Github actions before release. It has been broken since v0.19 (https://github.com/pyodide/pyodide/issues/2163#issuecomment-1048663940)

**Comment by ryanking13** [comment]
> It would be great if we can fix an issue on deploying prebuilt docker image in Github actions before release. It has been broken since v0.19 ([#2163 (comment)](https://github.com/pyodide/pyodide/issues/2163#issuecomment-1048663940))

I was able to run this action successfully on my fork. Maybe at v0.19 release, it was just flaky.
Anyway, I opened a PR that disables log clipping, so if it fails again, we will be possible to investigate the full log.

**Comment by hoodmane** [comment]
> We should produce json benchmarks too though so we don't have to keep parsing them.

Never mind, @ryanking13 already did that.

**Comment by hoodmane** [comment]
Okay, lets try to merge #2361 and #2370 and then we make the release after that. I think it's fine to do a manual deploy of the prebuilt docker image again. I think we should try to get the release out. We can release alphas just for the purpose of testing the prebuilt docker deploy when we get that working.

**Comment by rth** [comment]
We should re-organize the changelog a bit as well. I can do that tomorrow.

**Comment by rth** [comment]
Thanks for managing the release @hoodmane !

BTW, the pre-built docker image also deployed correctly.
