### ISSUE TITLE
0.20.0a1: import scipy fails 

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2338]
As reported by @mateuszcshark in 0.20.0a1 importing scipy fails,

```
>>> import scipy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/scipy/__init__.py", line 164, in <module>
    loadDynamicLibrary('/lib/python3.10/site-packages/scipy/linalg/_flapack.so')
JsException: Error: /lib/python3.10/site-packages/scipy/linalg/_flapack.so: file not found, and synchronous loading of external 
files is not available
```
I can also confirm with Firefox on main.

Likely related to latest changes in pre-loading so files cc @hoodmane . Though I don't understand why it worked in tests then.

**Comment by ryanking13** [comment]
I can reproduce it with Chrome.

Interestingly, I have the same error when I test it in our Pyodide console. But it doesn't happen when I do the same thing in the browser devtools console.

```py
# Pyodide console
>>> import pyodide_js
>>> await pyodide_js.loadPackage("scipy")
>>> import scipy
# Exception
```

```js
// Browser devtools console
await pyodide.loadPackage("scipy")
pyodide.runPython("import scipy")
// works
```

**Comment by rth** [comment]
Resolved in https://github.com/pyodide/pyodide/pull/2348
