### ISSUE TITLE
Track origin of unpacked files

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2340]
Previously, with .js/.data files generated by emscripten, we had  absolute paths for all files extracted in the virtual file system included in the .js file. This was not ideal size-wise, however, it allowed us to determine without ambiguity which file came from which package.

Now we are using .whl/.zip/.tar with relative paths which are extracted into some folder defined in the code. This makes it harder to determine afterward where the file came from (e.g. for size optimization of the original archive).

So, if there are no objections, I would like to add a non public attribute, for instance, `pyodide._extractedArchives` which would store the mapping of archive name -> extract_dir. In particular for installed packages and pyodide_py.tar. It's a bit harder to do this for unpackArchive in general since it doesn't take the archive name as input.

**Comment by hoodmane** [comment]
Could maybe feature gate it behind some private runtime flag.
