### ISSUE TITLE
npm package should not include .ts files

### ISSUE THREAD

**Issue by mneil** [pyodide/pyodide#2393]
## 🐛 Bug

I just did an `npm i pyodide` wanting to use this as [part of a projec](https://github.com/3p3r/cdk-web) for packaging AWS Lambda packages to support the Python Lambda Functions. I've been testing out pyodide and brython to see which one makes more sense. I am really liking pyodide. Up to now I've been including the file from a cdn and it's gone fine. However, the package on npm includes all of the typescript files.

An npm package should include type definitions (.d.ts) files for typescript and javascript users for type definitions. The rest of the code, however, should all be javascript. When you publish .ts files I have to now configure whatever build system I'm using (webpack) to support typescript and to explicitly hand transpiling the code. This is not the common way to distribute a package on npm.

In addition there is no main file defined in package.json. I am unsure what the main file is that I should include in order to get the full source. 
 

### To Reproduce

`npm i pyodide`

### Expected behavior

When I installed this I expected:

 - Javascript file or files
 - A single file defined as the main so that my requires or imports know what file to use when I request pyodide
 - The asm.js file for executing the pyodide application compiled with emscripten
 - The compiled python wasm that will be executed
 
 I believe all of these files should be included. This will make integration into other packages much easier.

### Environment

- Pyodide Version 0.20.0

### Additional context

I am happy to work on this if you agree. Hopefully I didn't misinterpret the point of the package on npm.

I have recently been using esbuild which is written in go and distributes a wasm for bundling. That code is successfully on the develop branch of cdk-web https://github.com/3p3r/cdk-web/tree/develop. I am comparing my experience dealing with the package distributed on npm for esbuild-wasm  vs. my experience with pyodide.

**Comment by hoodmane** [comment]
Yeah, I agree that we are publishing the wrong stuff. It should be a simple fix: instead of publishing our Javascript source directory which is useless, we should publish the built files (especially because the directory `src/js` gets processed both by emscripten and rollup). Nobody here knows how to use node all that much so we haven't fixed it.

**Comment by hoodmane** [comment]
For the record, to get something that actually works right now:
1. Download and unpack https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2
2. you can `import  {loadPyodide} from "pyodide.mjs"` or `let {loadPyodide} = require("pyodide.js")`. The former is probably better, the latter defines `loadPyodide` and `_createPyodideModule` as global variables.

**Comment by hoodmane** [comment]
After some exploration, it seems that what will work is to copy `package.json` into the `dist` folder, `cd` into the `dist` folder and then run `npm publish`. `npm` doesn't seem to have any progress indicator but it successfully uploads all 160mb. I published v0.20.0 here:
https://www.npmjs.com/package/hoodmane-pyodide
After a very long download time it... doesn't work very well.

Some issues:
1. we guess the wrong `indexURL`
2. Emscripten uses `require` which causes "require is not defined" when we load the es6 module

**Comment by EricCrosson** [comment]
I'm not either :sweat_smile: I'm seeing 

```
"type": "module"
```

> [source](https://stackoverflow.com/a/68558580)

but googling is suspiciously quiet on this. I was reading [this article](https://nickb.dev/blog/leveraging-rust-to-bundle-node-native-modules-and-wasm-into-an-isomorphic-npm-package) just yesterday that also uses the `module` technique :crossed_fingers:

**Comment by mneil** [comment]
Ok, I can help with this as I'm primarily a node / js user but have also used only python for several years. Typically, with typescript, you'd run `npx tsc` to build. And your tsconfig will have all the settings. You may need multiple tsconfig for different encryptions like testing, etc...

The built js, package.json, and any wasm files need to be included in that dist folder. Then cd into dist and publish. I can open a pr to resolve some of that and you let me know if I miss anything.

**Comment by hoodmane** [comment]
Also, our distribution is very large (200mb) but only 15mb is needed to run the interpreter and the rest are packages. It might be good to eventually add some way to split things up a bit so people don't have to download so much stuff if they won't use it.

**Comment by hoodmane** [comment]
Okay, so roughly `cp package.json $DIST_DIR && cd $DIST_DIR && npm publish`?

**Comment by hoodmane** [comment]
> I'm not either :sweat_smile: I'm seeing 
>
> ```
> "type": "module"
> ```

Some experimentation shows that `"type" : "module"` causes an error if you try to `require` anything from the package.

**Comment by hoodmane** [comment]
Okay, after some trial and error, hoodmane-pyodide@0.20.0-g seems to work correctly. I used this branch:
https://github.com/pyodide/pyodide/pull/2394
Both `test.mjs`:
```js
import { loadPyodide } from "hoodmane-pyodide/pyodide.mjs";

async function main(){
    let pyodide = await loadPyodide();
    pyodide.runPython("print(1+1)");
}
main();
```
and `test.js`:
```js
let {loadPyodide} = require("hoodmane-pyodide");

async function main(){
    let pyodide = await loadPyodide();
    pyodide.runPython("print(1+1)");
}
main();
```
work as expected. It seems like we only get one entrypoint, we can choose whether the commonjs or the es6 entrypoint is preferred, the other has to be imported like `"hoodmane-pyodide/pyodide.mjs"`.

**Comment by mneil** [comment]
I believe what you want is to use exports in the package.json to define what file to use depending on the module definition (common vs. esm).

https://www.the-guild.dev/blog/support-nodejs-esm

#package.json
```js
{
  "main": "pyodide.js",
  "exports": {
    "require": "pyodide.js",
    "import": "pyodide.mjs"
  }
}
```

The module and exports are not official sections yet. However, node looks at the exports field since v12 LTS. Module is used for bundlers like webpack - maybe rollup also looks at modules but I'm not as familiar with it.

**Comment by mneil** [comment]
@rth the package @hoodmane published recently as a test contains roughly 18mb on disk and contains everything I understand is needed to execute pyodide. The wasm binary, pyodide js, asm.js, and web workers. Anything the user installs later via pyodide install or micropip should continue to work as it does currently (pull from pypi or pyodide cdn).

One option could be to run a postinstall script that downloads larger files after the install from a CDN. However, some security focused organizations like to disable post install scripts which could make onboarding pyodide slightly harder. However, the onus is on those users to handle the post install themselves if they choose to disable it. 

I personally think 18mb is large but not massive for an npm packages total footprint. A typical react app is going to pull more than that down when you look at the size of all transient dependencies.

**Comment by rth** [comment]
Sounds good that, I read the discussion too fast :)

**Comment by alexmojaki** [comment]
Just ran into this while trying to use the pyodide npm package as a dependency in my own package (https://github.com/alexmojaki/pyodide-worker-runner/issues/8).

> Nobody here knows how to use node all that much so we haven't fixed it.

My intended environment is a browser, but I can't even run a webpack build. After fighting with configuration a bit, I hit an impasse because the `.ts` files say things like `import ... from "./api.js"` and of course there's no `api.js`, only `api.ts`.

> Also, our distribution is very large (200mb) but only 15mb is needed to run the interpreter and the rest are packages. It might be good to eventually add some way to split things up a bit so people don't have to download so much stuff if they won't use it.

Ultimately I'd like to use the Pyodide npm package for the type declarations and to use `loadPyodide` to skip the extra network request of an initial `importScripts`. But I don't want to download the full distribution or serve it myself, I still want to set `indexURL` to the CDN.

**Comment by alexmojaki** [comment]
BTW, the final package can still include the .ts source files *in addition* to the built .js files. This can be used for source maps, by the IDE, or just informally to look at source code in `node_modules` without having to come to github.

**Comment by hoodmane** [comment]
> the final package can still include the .ts source files in addition to the built .js files

I think there's some risk of confusion between `pyodide.ts` and `pyodide.js`? If you say 
```ts
import { loadPackage } from "./pyodide";
```
in a typescript file, won't it use `pyodide.ts` instead of `pyodide.js`?


> used for source maps

I think we are including source maps.

**Comment by hoodmane** [comment]
> I can't even run a webpack build ... After fighting with configuration a bit, I hit an impasse because the `.ts` files say things like `import ... from "./api.js"` and of course there's no `api.js`, only `api.ts`.

Well probably we should fix that too. It would be helpful if anyone who is better at node/webpack/typescript could contribute to #2397. Currently our mocha tests don't even run and I haven't figured out why. #2394 improves the situation a bit. 

Maybe we should deploy a release (maybe `0.20.1a1`?) with #2394 so people can test out the changes and help us fix any further problems.
