### ISSUE TITLE
In pyodide 0.20.0, pyodide.d.ts only exports `loadPyodide`

### ISSUE THREAD

**Issue by wch** [pyodide/pyodide#2395]
With pyodide 0.19.0 (installed from the release tarball), the pyodide.d.ts file exported many types, including `PyProxy`, `PyProxyCallable`, and `loadPyodide`. As of 0.20.0, that file only exports `loadPyodide`. Is that intentional? Some of those types were useful for some TypeScript code I've been working on. 

In a similar vein, there previously were a few other .d.ts files included in the distrubution, like api.d.ts and pyproxy.gen.d.ts, but those files are no longer there. It wasn't clear to me exactly what the structure/purpose of these .d.ts files was, but I did make use of some of them.

**Comment by hoodmane** [comment]
Thanks for the report! 

We want to be exporting those other types. We can include them again in 0.20.1. We don't want the other files like api.d.ts, everything should be in the one file pyodide.d.ts The problem is we don't really know how to use typescript.

**Comment by hoodmane** [comment]
In `pyodide.ts` we say `export { ...,  PyProxyCallable, ... } from "./pyproxy.gen"`. `pyodide.d.ts` contains `type PyProxyCallable = ...` but then it doesn't export it. I wonder why.

**Comment by hoodmane** [comment]
Okay, if I run `tsc` it creates the old situation of many `.d.ts` files, but we really want them bundled together so that people don't end up relying on internal details of our project structure.

**Comment by hoodmane** [comment]
dts-bundle-generator seems to work correctly.

**Comment by wch** [comment]
Great, thanks for the quick attention!

**Comment by hoodmane** [comment]
@wch we don't currently have much information about if people are using the types and how. In areas where we have a strong sense of the right design, we can just do what we think is right. In areas where we are less sure, it's hard to know whether stuff is correctly designed / useful to people until we accidentally break it and they complain. Any feedback is helpful!

**Comment by wch** [comment]
I can't say I have a great idea of what the overall type design should look like, but here are some examples adapted from the code I'm working on.

The casting is sometimes awkward. In some cases, it seems necessary (because TS doesn't know what the Python code will return), but in other cases, it seems like it shouldn't be necessary.

Getting the python `repr` function so that it can be called from JS. I needed to tell it that `pyodide.globals` has a `.get()` method by casting to `PyProxyWithGet`. (In this case, it seems like we can know that ahead of time.)

```ts
repr = (pyodide.globals as PyProxyWithGet).get("repr") as unknown as (x: any) => string;
```

Similarly, setting a value: I wanted to make the JS pyodide object available on the Python side, and I had to tell it that `pyodide.globals` has a `.set()` method:

```ts
(pyodide.globals as PyProxyWithSet).set("js_pyodide", pyodide);
```



Here, `pyconsole` is a reference to a Python object. I'm trying to get a JS handle to a Python function; that function takes a string and returns an iterable object:

```ts
tabComplete = pyconsole.complete.copy() as unknown as (x: string) => PyProxyIterable;
```

Regarding types and `loadPyodide`: The code uses `loadPyodide.inProgress`, but `inProgress` is not declared as a property on `loadPyodide` in `pyodide.d.ts`. So I'm doing something like this:

```ts
import {
  loadPyodide as loadPyodide_orig,
} from "./pyodide/pyodide";

declare global {
  var loadPyodide: typeof loadPyodide_orig & { inProgress: boolean };
}
``` 

It would be nice if we didn't have to do that hack to make TS know about `loadPyodide.inProgress`.

**Comment by hoodmane** [comment]
Well `inProgress` we probably should have made private, it will be removed in the next release #2391. 

Indeed `globals` should be typed as `PyProxy & PyProxyWithGet & PyProxyWithSet & PyProxyWithHas` (and perhaps we should define `PyProxyDict` or `PyProxyMutableMapping` as a shorthand for this). That's a quick fix.

There's definitely a lot that can be done in this regard -- I've explored the possibility of modifying mypy's `stubgen.py` to generate typescript types, but it's not high enough value for the effort at this point given how few people are working on Pyodide. 
https://github.com/python/mypy/blob/master/mypy/stubgen.py
