### ISSUE TITLE
 REPL give wrong output when it contains double bracket `[[ ]]`

### ISSUE THREAD

**Issue by chaoqing** [pyodide/pyodide#2399]
## 🐛 Bug

I think because of this [feature](https://github.com/jcubic/jquery.terminal/issues/508#issue-463182053). The Pyodide [REPL](https://pyodide.org/en/stable/console.html) can not work correctly with input and output contains raw bracket string `[[ ]]`.

I solved the output part by replacing `]]` with `]&#93;` in the output of [repr_shorten](https://github.com/pyodide/pyodide/blob/93dc922f46e38f98bd30c3850c7bd094b1933163/src/py/pyodide/console.py#L477) but not sure how to handle the input case. Maybe we need upstream `jquery.terminal` to provide an option to turn off the feature.

### To Reproduce

Try input command `print('[[x]]')` or `print('[[1]]')`.

### Expected behavior

The output should be `[[x]]` but an `NameError: name 'x' is not defined` triggered.

### Environment

- Pyodide Version: Any
- Browser version: Any

**Comment by ryanking13** [comment]
Thanks for the report @chaoqing! Yes, I can reproduce and confirm that this is a bug.
