### ISSUE TITLE
RFC Provide a way to download packages for Node

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2402]
## 🚀 Feature

From the discussion (https://github.com/pyodide/pyodide/pull/2394#discussion_r851565711), it would be good to provide an official way to download Pyodide packages into the local filesystem for Node users, so that they don't need to manually download it from e.g. Github release.

Example: `pyodide install` (`npx pyodide install`)

For a reference, other npm packages that need to download external binaries do:

- [puppeteer](https://github.com/puppeteer/puppeteer): has a [install script](https://github.com/puppeteer/puppeteer/blob/2b45027d256f85f21a0c824183696b237e00ad33/package.json#L29) which downloads Chromium browser binary when doing `npm install puppeteer`.

- [playwright](https://github.com/microsoft/playwright): has a command `playwright install` to download browser binaries (and ffmpeg).

**Comment by rth** [comment]
I previously opened a similar issue in https://github.com/pyodide/pyodide-cli/issues/3 as that is now a better repo for it. So I'm going to close this one, and copy-paste the above proposal there.
