### ISSUE TITLE
Add micropip install no_deps option

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2412]
It would be useful to add the option `no_deps=False` to `micropip.install` to disable dependency resolution. This can be useful in cases where 
 - the dependency resolution doesn't work as expected (in particular with custom wheels https://github.com/pyodide/pyodide/issues/2408)
 - generally to be able to force install a set of packages, for instance ignoring requirements that should have been optional in an arbitrary PyPi package.

The no_deps name is by analogy with `pip install --no-deps`, though maybe `deps=True` would also work, although being not very explicit.

**Comment by hoodmane** [comment]
We might also want to expose this without `micropip`. Like why not just `pyodide.loadPackage("some_wheel.whl")`? From a loading perspective it is a bit sad to do:
1. load Pyodide + distutils
2. Once all of that is finished, load micropip
3. Once that is finished load wheel

Without `micropip` we don't have `packaging` which we'd want to use to analyze the wheel metadata. Maybe we could record any wheels loaded with have `micropip` analyze the already loaded wheels when it is first imported since that metadata will be lying around in the file system even if we don't know how to read it easily without `packaging`.

**Comment by rth** [comment]
Yes, particularly now that all packages are wheels we might want to merge together micropip.install, and pyodide.loadPackage somehow.  Though I like that micropip is a somewhat independent Python package and not included inside core pyodide.

**Comment by hoodmane** [comment]
Yeah I still don't think we should merge `micropip` with `loadPackage`. I think I've said this a bunch but we should add `micropip.freeze()` that creates a new `packages.json` with the currently loaded packages, and then if you use that `packages.json` on a subsequent load then you won't need micropip at all. This way people who only need a fixed set of dependencies from PyPI can resolve those dependencies once and in their deployed app they don't need to wait for micropip's slower dynamic resolution strategy. As you say, this is related but different than the current topic.

Also worth noting that it is possible to do a no-deps install for a pure Python wheel as follows:
```js
const wheel_promise = fetch("blah.whl").then(x => x.arrayBuffer());
const pyodide = await loadPyodide();
const buffer = await wheel_promise;
pyodide.unpackArchive(buffer, "whl");
pyodide.runPython(`
import blah
# ...
`);
```
This is the best possible option in the sense that the wheel can be downloaded concurrently with the rest of Pyodide. Currently `micropip` won't know that `blah` is installed. 

One option would be to make micropip actually look at the `.dist-info` directories like real pip. Then it would know about wheels installed by whatever means.

**Comment by rth** [comment]
>  One option would be to make micropip actually look at the .dist-info directories like real pip. Then it would know about wheels installed by whatever means.

Agreed. Looking at those instead of having our own system to keep track of state seems like a good idea.

**Comment by ryanking13** [comment]
> > One option would be to make micropip actually look at the .dist-info directories like real pip. Then it would know about wheels installed by whatever means.
> 
> Agreed. Looking at those instead of having our own system to keep track of state seems like a good idea.

+1 to it.
