### ISSUE TITLE
pyodide.pyimport example wrong

### ISSUE THREAD

**Issue by loosak** [pyodide/pyodide#2421]
## 📚 Documentation

Hello,
in  https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.pyimport
example: 
```
let sysmodule = pyodide.pyimport("sys");
let recursionLimit = sys.getrecursionlimit();
```
seems to be wrong, correct one:
```
let sysmodule = pyodide.pyimport("sys");
let recursionLimit = sysmodule.getrecursionlimit();
```

Thanks!
-->

**Comment by rth** [comment]
Yes, thanks! Would you like to make a PR to fix it?

**Comment by ricardoprins** [comment]
I believe this can be closed now.

**Comment by ryanking13** [comment]
Yes, thanks @loosak and @ricardoprins!
