### ISSUE TITLE
dependency-check.sh doesn't check for cmake

### ISSUE THREAD

**Issue by mdboom** [pyodide/pyodide#2422]
## 🐛 Bug

cmake is a requirement to build emsdk.  We could help new contributors by checking for this in dependency-check.sh

### To Reproduce

Build a clean checkout of pyodide on a (for example) Debian with only build-essentials installed.

### Expected behavior

An error about missing cmake with instructions to install it.

**Comment by rth** [comment]
Thanks for the report! Indeed.
