### ISSUE TITLE
REPL not showing anything (on latest)

### ISSUE THREAD

**Issue by pllim** [pyodide/pyodide#2428]
At https://pyodide.org/en/stable/usage/quickstart.html#try-it-online , it says:

*Try Pyodide in a [REPL](https://pyodide.org/en/latest/console.html) directly in your browser (no installation needed).*

So, I copy-pasted https://pyodide.org/en/latest/console.html on the browser and expected some notebook cell-like looking thingies to show up. But the page was blank.

On the browser dev console, it says:

<img width="401" alt="Screenshot 2022-04-30 222323" src="https://user-images.githubusercontent.com/2090236/166132149-4648c86e-9f5a-4b9a-a2ac-7a7bebd4407c.png">

Did I miss something? Thanks!

**Comment by hoodmane** [comment]
Try the stable version:
https://pyodide.org/en/stable/console.html
Something went wrong with the deployment of the main branch on the most recent commit. I'm not sure what happened.

**Comment by pllim** [comment]
Thanks for the quick response! `stable` seems to work after the initial load time overhead. Happily surprised to see `astropy` included! 😸 

<img width="532" alt="Screenshot 2022-04-30 224112" src="https://user-images.githubusercontent.com/2090236/166132495-70a40ecb-482f-4800-b152-bf3055f0ba78.png">

**Comment by ryanking13** [comment]
Thanks for the report! It seems like our latest console is working again. So closing as resolved. I'm also not sure which happened during the deployment. We can revisit this when it happens again.
