### ISSUE TITLE
Verify checksums of Pyodide packages

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2431]
A subset of https://github.com/pyodide/pyodide/issues/1881. 

To improve security it would be good to verify checksums of packages built by Pyodide when we are installing them.

This would involve,

1. [x] including a `sha256` key to package.json e.g.
        ```json
        packages": {
            "asciitree": {
                  "name": "asciitree", 
                  "version": "0.3.3", 
                  "file_name": "asciitree-0.3.3-py3-none-any.whl",
                  "sha256": "<sha256>"
                  ...
        ```
        which is generated in  [generate_packages_json](https://github.com/pyodide/pyodide/blob/3f9ae2ed1e1aee688251af86a4dc23d3d867740c/pyodide-build/pyodide_build/buildall.py#L433)
        
3. [ ] verify this checksum when installing it in [pyodide.loadPackage](https://github.com/pyodide/pyodide/blob/263309102d8158d82d051d0f3d4bbf7a4505c52a/src/pyodide.js#L288)

**Comment by mger** [comment]
I will take a stab at this for the sprint.

**Comment by rth** [comment]
Thanks for your work @mger! For the second part, actually, [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) already has `integrity` parameter which can be used to validate sha256. So it would be just a matter of passing this parameter with the right value when fetching the file.

**Comment by amitsaha** [comment]
@mger are you planning to continue the work on this? Else i will jump in.

**Comment by mger** [comment]
@amitsaha Feel free to jump in. I had to fly back from PyCon today, and I am not sure when I'll be able to get around to the second part.

**Comment by amitsaha** [comment]
Sounds good, I will resume the work then.

**Comment by amitsaha** [comment]
Couple of things:

- Should we add a checksum verification for `pyodide.js`?
- Also, as mentioned in the PR, the node-fetch module doesn't support integrity, but 17.5 has added `fetch()` as experimental. I guess i should create a separate issue for this.

**Comment by rth** [comment]
Closing as resolved. Thanks again @amitsaha !
