### ISSUE TITLE
CI Automate release process more

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2438]
We have automated most of the release process:

- Publishing `pyodide_build` to PyPI.
- Deploying build results to CDN.
- Push prebuilt docker image.

But there exist a few more things that need to be automated to prevent human errors.

- Replacing version names (CDN links) in the documentation: we can probably use [sphinx substitution syntax](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html).
- Publishing Pyodide JS package to NPM: we should add this to our CI jobs.

**Comment by hoodmane** [comment]
Also replacing version numbers in other places (`pyproject.toml`, `__init__.py`, ...)

**Comment by rth** [comment]
Yes, it would be great.

> Publishing pyodide_build to PyPI.

BTW, it looks like https://pypi.org/project/pyodide-build/ wasn't deployed for 0.20.0

**Comment by ryanking13** [comment]
> BTW, it looks like https://pypi.org/project/pyodide-build/ wasn't deployed for 0.20.0

Yeah right, we forgot to rename the pyodide_build version and published `0.20.0.dev0`.

**Comment by andreysmelter** [comment]
I am going to try to take this first issue first part during PyCon sprints: 
* Replacing version names (CDN links) in the documentation: we can probably use [sphinx substitution syntax](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html).

**Comment by ryanking13** [comment]
Closing as resolved via #2460, #2587 and #2776.
