### ISSUE TITLE
Enable precommit-ci?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2446]
@henryiii was recommending that we enable precommit-ci. This would save us from hassling people to run precommit for formatting, like in #2445. I am in favor of it. @rth @ryanking13 what do you think?

**Comment by rth** [comment]
Sound good

**Comment by hoodmane** [comment]
Okay I enabled it.

**Comment by ryanking13** [comment]
There was a little concern about permission for this. https://github.com/pyodide/pyodide/pull/2177#issuecomment-1040013907

**Comment by henryiii** [comment]
It should not be able to write to protected branches unless it is given admin access permission, which it is not. I have _not_ verified this is true, however.

**Comment by rth** [comment]
OK I added extra restrictions on the GH end on who can push to protected branches, so that should help anyway
![image](https://user-images.githubusercontent.com/630936/166403312-ff29b641-c270-4d96-81d3-dc1145309df6.png)
