### ISSUE TITLE
`static_assert failed` error during build

### ISSUE THREAD

**Issue by wlach** [pyodide/pyodide#2448]
## 🐛 Bug

Run `make` in either docker or stock Ubuntu 22.04, get this error:

```
libtool: compile:  /src/emsdk/emsdk/upstream/emscripten/emcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -O3 -fPIC -Wall -fexceptions -c src/wasm32/ffi.c -o src/wasm32/ffi.o
src/wasm32/ffi.c:112:1: error: static_assert failed due to requirement '8 == __alignof(max_align_t)' "max_align_t must be 8"
_Static_assert(MAX_ALIGN == __alignof__(max_align_t), "max_align_t must be 8");
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

File appears to be `./cpython/build/libffi/src/wasm32/ffi.c`

### Environment

- Pyodide Version: `80a650cc33790278601a52253858cfa40c647232`

### Additional context

It looks like this assert was added in response to this issue https://github.com/emscripten-core/emscripten/issues/10072 -- seems like it might be an LLVM issue? Unclear why we're seeing it.

**Comment by rth** [comment]
Hmm, yes, it's not very clear. That emscripten issue was fixed in emscripten 2.0.26 and we are using 2.0.27 so it should have been resolved.

**Comment by wlach** [comment]
Looks like assertion was actually added by @hoodmane here: https://github.com/hoodmane/libffi-emscripten/pull/12/files#diff-10f009086c245c6d831949e6a5b2aee5c1091934c0d04719dba3e9b6ccd00c58R112

Perhaps they have some insight as to what might have happened?

**Comment by hoodmane** [comment]
Hi @wlach. If the stack isn't aligned to `MAX_ALIGN` before calling into a wasm function, it invokes undefined behavior. Both Emscripten and Pyodide are sloppy about this. Whether anything goes wrong depends on the function called. The libffi test suite catches the problems.

We don't have a good way to get `alignof` into Javascript directly, so we have to `#define` a guess for the alignment and then use a static assert. I guess another possibility would be:
```
EMSCRIPTEN_KEEPALIVE int max_align = __alignof__(max_align_t)
```
and then load it via `Module._max_align` from the Javascript. This probably JITs just as fast. But I don't know why you aren't getting `__alignof__(max_align_t)` equal to 8...

**Comment by wlach** [comment]
Figured it out. This was my fault: I had an out-of-date `.emscripten` file lying around.

**Comment by gracicot** [comment]
@wlach What was the content if the `.emscripten` and why did it caused this problem? I'm facing the same issue while packaging emscripten 3.1.12 for nixos and I would love to fix it.

**Comment by wlach** [comment]
> @wlach What was the content if the `.emscripten` and why did it caused this problem? I'm facing the same issue while packaging emscripten 3.1.12 for nixos and I would love to fix it.

Sorry, I don't remember. 😢
