### ISSUE TITLE
MKG Update sqlite

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2469]
We update Python packages regularly, but it looks like we forgot to keep C dependencies up to date. In particular, as was reported by someone trying pyscript, the sqlite version we ship is outdated by 2 years.

Someone would need to bump the version in https://github.com/pyodide/pyodide/blob/eb8afb00c2c139f83bda7630ead98523d1ac0248/cpython/Makefile#L22

This is a good first issue.

**Comment by amitsaha** [comment]
I will look at this one.

**Comment by rth** [comment]
Fixed in #2477
