### ISSUE TITLE
SyntaxError: unmatched ']' in numpy.random.rand

### ISSUE THREAD

**Issue by Ruibin-Liu** [pyodide/pyodide#2485]
### To Reproduce
Try to use the function in the REPL [console](https://pyodide.org/en/stable/console.html).
```
import numpy as np
np.random.rand(3, 2)
```

### Expected behavior
Return a numpy array to the console.

### Environment

- Pyodide Version: stable
- Browser version: Chromium 99.0.4844.84 
- Any other relevant information:

**Comment by hoodmane** [comment]
Thanks for the report! Can you add the traceback?

**Comment by Ruibin-Liu** [comment]
Not sure about the traceback in console, but here is the code and output:
```
>>> import numpy as np
>>> np.random.rand(3, 2)
array()
  File "<console>", line 1
    0.84857963, 0.72689237],
                          ^
SyntaxError: unmatched ']'
([0.25494842, 0.16927424],)
... 
 
```

**Comment by rth** [comment]
Thanks, I can reproduce. It's a regression between 0.19.1 and 0.20.0 that appears to be due to https://github.com/pyodide/pyodide/commit/a69fb1bbb798db0d8d257ed72dfc374bc25267f6

**Comment by ryanking13** [comment]
I think #2399 is the reason.
