### ISSUE TITLE
Borrowed Proxy was automatically destroyed

### ISSUE THREAD

**Issue by Killklli** [pyodide/pyodide#2498]
## 🐛 Bug

Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function generate_seed at 0x15edb78>"

### To Reproduce

https://github.com/2dos/DK64-Randomizer/blob/dev/ui/bindings.py

### Expected behavior

On 0.18.1 it would automatically bind the function to the button, but all latest versions fail.

### Environment

- Pyodide Version:
>=0.19.0
- Browser version:
Any
- Any other relevant information:

**Comment by rth** [comment]
Closing as expected behavior, please comment if you still encounter issues. Though yeah this was a breaking change in 0.19,

![image](https://user-images.githubusercontent.com/630936/166983388-169f3b19-8006-4d83-8512-eff246e40f28.png)
