### ISSUE TITLE
Support seaborn

### ISSUE THREAD

**Issue by NourEldin-Osama** [pyodide/pyodide#2500]
## 🐍 Package Request

- Package Name and Version : seaborn 0.11.2
- Package URL : https://pypi.org/project/seaborn/
- Package Dependencies that needs to be resolved first: numpy, scipy, matplotlib, pandas

**Comment by hoodmane** [comment]
I believe that seaborn already works, you can install it with micropip:
```js
await pyodide.loadPackage("micropip");
const micropip = pyodide.pyimport("micropip");
await micropip.install("seaborn");
```
and then you can use it. There are some caveats with interactive plots that come from matplotlib limitations. But for static figures it should all work fine.

**Comment by NourEldin-Osama** [comment]
> I believe that seaborn already works, you can install it with micropip:
> 
> ```js
> await pyodide.loadPackage("micropip");
> const micropip = pyodide.pyimport("micropip");
> await micropip.install("seaborn");
> ```
> 
> and then you can use it. There are some caveats with interactive plots that come from matplotlib limitations. But for static figures it should all work fine.

Thanks
