### ISSUE TITLE
Online console output is wrong when using `input()`

### ISSUE THREAD

**Issue by dragoncoder047** [pyodide/pyodide#2505]
## 🐛 Bug with online console

Stdout when using `input()` in online console is wrong.

### To Reproduce

Go to https://pyodide.org/en/stable/console.html and enter `input('foo bar: ')`. After entering `barbaz` in the prompt box:

```pycon
>>> input('foo bar: ')
foo bar: 'barbaz'
>>>
```

### Expected behavior

No prompt box, and:

```pycon
>>> input('foo bar: ')
foo bar: barbaz
'barbaz'
>>>
```

### Environment

- Pyodide Version: `Python 3.10.2 (main, Apr  9 2022 20:52:01)`. Latest release was `0.20.1a1`.
- Browser version: Chrome 96.0.4664.111 64 bit (on chromebook) *I don't think this is relevant, though.*

This issue may be related to #1898 at least with the prompt box. However, the stdin callback (in `loadPyodide`) could be fixed to echo the input back to the terminal.

**Comment by hoodmane** [comment]
For now, this being broken is kind of the expected behavior. Getting `input()` to work requires nontrivial setup, for an example repl with working input see here:
https://github.com/hoodmane/worker-pyodide-console

Perhaps we should add a section of the docs giving limitations of the repl. Ideally someone downstream would make a really good repl... 
@rth what do you think about this?

**Comment by dragoncoder047** [comment]
I'll leave the fixing the prompt box to you guys since I know nothing about Emscripten and webassembly. But the solution I was thinking of was something like this: (of the Javascript on the console page)

```diff
 async function main() {
-  globalThis.pyodide = await loadPyodide();
+  globalThis.pyodide = await loadPyodide({
+    stdin: x => {
+      term.echo(x, {newline: false});
+      return prompt(x);
+    }
+  });
   let namespace = pyodide.globals.get("dict")();
```

This will fix *half* of it. As for the other half, I'll leave it to you guys...

**Comment by hoodmane** [comment]
You want to open a PR with that @dragoncoder047?

**Comment by ryanking13** [comment]
I'll close this for now, as I think there are not many things we can do unless we solve the blocking issue in the main thread.
Thanks, @dragoncoder047 for the improvement in the REPL.
