### ISSUE TITLE
Isn't working without javascript

### ISSUE THREAD

**Issue by maratsalmanov1** [pyodide/pyodide#2508]
**The whole project is useless without javascript enabled.**

Pyodide terminal emulator (https://pyodide.org/en/stable/console.html) **isn't working with javascript disabled**

Steps to reproduce: 

1. Open any Chromium-based browser dev tools
2. Press Control+Shift+P to open the Command Menu.
3. Start typing javascript, select Disable JavaScript, and then press Enter to run the command.
4. Refresh the page

**Comment by maratsalmanov1** [comment]
I don't want to depend on javascript to make my code working in browser

**Comment by hoodmane** [comment]
> The whole project is useless without javascript enabled.

This is true, but impossible to fix. The APIs to load a wasm module into the browser are implemented in... Javascript. If Javascript is disabled, so is wasm.

**Comment by maratsalmanov1** [comment]
> The APIs to load a wasm module into the browser are implemented in... Javascript.
Then how can we fix the current wasm implementation in all major browsers to make it work without it?

**Comment by rth** [comment]
> Then how can we fix the current wasm implementation in all major browsers to make it work without it?

We can't. A lot of things are implemented in Javascript in Emscripten which makes what we do in Pyodide possible. It won't work without Javascript. Sorry, closing as "won't fix".
