### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by Jainu-s** [pyodide/pyodide#2522]
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 1, in ModuleNotFoundError: No module named 'numpy' )

I cannot import pandas. How to install it?

**Comment by ryanking13** [comment]
Pandas is already included in Pyodide. When building Pyodide, you must specify packages to be built

```
PYODIDE_PACKAGES="pandas" make
```

**Comment by Jainu-s** [comment]
> Pandas is already included in Pyodide. When building Pyodide, you must specify packages to be built
> 
> ```
> PYODIDE_PACKAGES="pandas" make
> ```

can you please show how the syntax for PYODIDE_PACKAGES="pandas"?

**Comment by ryanking13** [comment]
Are you building Pyodide by yourself or just using a CDN URL to download Pyodide?

If you are building Pyodide by yourself, please [follow the build instruction document](https://pyodide.org/en/stable/development/building-from-sources.html#). If not, please tell us how we can reproduce your error.

**Comment by hoodmane** [comment]
Are we sure the problem here isn't a missing `pyodide.loadPackage("pandas")`?

**Comment by Kugeleis** [comment]
same here, loading pyscript from CDN; having
```
<py-env>
	- pandas
</py-env>
```
in my header results in `File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 5, in ModuleNotFoundError: No module named 'pandas' )`

**Comment by ryanking13** [comment]
> same here, loading pyscript from CDN; having
> 
> ```
> <py-env>
> 	- pandas
> </py-env>
> ```
> 
> in my header results in `File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 5, in ModuleNotFoundError: No module named 'pandas' )`

Could you give us a fully reproducible code? I think it is more like a pyscript issue, but we can have a look anyways.

**Comment by Kugeleis** [comment]
here is my stripped down html (not using pandas yet)
```html:
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title>Pyscript Test</title>
		<link rel="stylesheet" href="nerdle-styles.css">
		<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
		<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
	</head>

	<body>
		<div class="headingcontainer">
			<h1>Hallo Welt</h1>
			<h3>mit pyscript</h3>
		</div>
		<py-env>
			- pandas
		</py-env>
		<py-script>
			from pandas import Series,DataFrame
			print("Hallo Welt.")
		</py-script>
	</body>

</html>
```

**Comment by rth** [comment]
Closing as resolved, but please comment if you still encounter issues.

**Comment by georgefrederick** [comment]
> here is my stripped down html (not using pandas yet)
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> 
> 	<head>
> 		<meta charset="UTF-8">
> 		<title>Pyscript Test</title>
> 		<link rel="stylesheet" href="nerdle-styles.css">
> 		<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
> 		<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
> 	</head>
> 
> 	<body>
> 		<div class="headingcontainer">
> 			<h1>Hallo Welt</h1>
> 			<h3>mit pyscript</h3>
> 		</div>
> 		<py-env>
> 			- pandas
> 		</py-env>
> 		<py-script>
> 			from pandas import Series,DataFrame
> 			print("Hallo Welt.")
> 		</py-script>
> 	</body>
> 
> </html>
> ```

Did the sub of tabs  solve the exception? still getting the same exception even after subbing the tubs, same code snippet as quoted.

**Comment by ADI711** [comment]
I am currently facing the same issue as above and i have tried removing any whitespaces or tabs.
the only difference is i have placed the <pye-env> tag inside the head tag and i still get the same error.
![image](https://user-images.githubusercontent.com/42679100/230744676-ef6885cb-deca-4287-bf2e-bad4337ba9e0.png)
![image](https://user-images.githubusercontent.com/42679100/230744687-908e104a-ee6c-4653-8958-16805a8559a9.png)
 can anyone assist me on this please?

**Comment by hoodmane** [comment]
@ADI711 you seem to be using PyScript. Why not ask about it in one of the pyscript channels rather than here?

**Comment by ADI711** [comment]
can you guide me to that channel.
also the above thread is the same as mine?

**Comment by hoodmane** [comment]
The pyscript repository is here: https://github.com/pyscript/pyscript/
