### ISSUE TITLE
`JsException(PythonError: JsException: Error: Object has already been destroyed The object was of type "coroutine" and had repr "" )`

### ISSUE THREAD

**Issue by donno2048** [pyodide/pyodide#2523]
## 🐛 Bug

`JsException(PythonError: JsException: Error: Object has already been destroyed The object was of type "coroutine" and had repr "" )`

### To Reproduce

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
        <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
        <py-script>
async def main():
    pass
main()
        </py-script>
    </head>
</html>
```

### Expected behavior

Not to throw an error

### Additional context

This worked until now, I have no idea what had changed

**Comment by hoodmane** [comment]
Looks to me like a pyscript bug. If not a pyscript bug, it would require further minimization to remove the pyscript since it's opaque to me where the problem comes from. One thing that would help would be to include the traceback.

Maybe try `await main()` though?

**Comment by donno2048** [comment]
> Maybe try `await main()` though?

In the base level? `await` is only allowed inside a function...

**Comment by hoodmane** [comment]
If python code is compiled with the compiler flag `PyCF_ALLOW_TOP_LEVEL_AWAIT` then you can use top level await. This was added in python 3.8

**Comment by donno2048** [comment]
> If python code is compiled with the compiler flag `PyCF_ALLOW_TOP_LEVEL_AWAIT` then you can use top level await. This was added in python 3.8

Used it and it solved the problem...

**Comment by hoodmane** [comment]
Okay closing as resolved.

**Comment by codewithawr** [comment]
what do you mean compiler flag plz explain

**Comment by hoodmane** [comment]
https://docs.python.org/3/library/ast.html#ast-compiler-flags

**Comment by codewithawr** [comment]
i got it but how can i add to pyscript

**Comment by codewithawr** [comment]
Thanks but it solves by `import asyncio` in my code

**Comment by hoodmane** [comment]
pyscript has a janky thing where it switches to using top level await if `asyncio` occurs in the code string. So even a line of code with just the string `"asyncio"` would make it work. Maybe they should use `await` and or `async` to trigger this instead...
