### ISSUE TITLE
A bundler for Python packages

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2529]
This was a GSOC project idea, but since it wasn't accepted this year, I started hacking on it during the sprint with some very helpful pointers from @hoodmane .

The first version is in https://github.com/rth/pyodide-pack , there are still [a few bugs](https://github.com/rth/pyodide-pack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) to fix, and things to improve.

The conclusions from this exploration so far,
 1. It is possible to reduce the package size somewhat, particularly for pure python packages. For instance, a simple example with sympy is 2x smaller and loads almost 2x faster.
 2. For packages with C extensions, most of the size is in so files, so reducing the number of Python files doesn't help that much (as long as most .so files are also included). 
 3. It's quite easy to benchmark different steps of the load with this. For packages with C extensions, the bottleneck is by far loading dynamic libraries once they are in the file system (#2288). So it would be worth spending more time on optimizing load time of those .so files as @wlach has been doing.
 4. It would be nice to be able to do this with the standard library but this would need https://github.com/pyodide/pyodide/pull/2521 (thanks @hoodmane ), support some callback to load arbitrary code before pyodide stdlib init, and ability to change the URL for the stdlib. Also using more dynamically linked modules in the stdlib would help. Then later support packages installed via micropip.
 5. In the end because of top-level imports the gains in size are not huge, and would likely require some kind of code rewrite in packages to become more interesting (https://github.com/rth/pyodide-pack/issues/5)
 6. As a contributor, it feels so much nicer just use Python and JS to write code and not have to deal with the build system. We should really do something so people can contribute to the Python/JS packages and micropip without having to setup a compiler or use make.

Overall what I would be interested in,
 - your general feedback about the approach if you have any. (The code was written a bit fast, so it could use more refactoring.)
 - once it's a bit more stable, I would like to move this repo under the pyodide org, unless there are no objections to it?
 - if anyone has ideas about what would be a better name for it https://github.com/rth/pyodide-pack/issues/6 please comment there.

**Comment by ryanking13** [comment]
> 3\. It's quite easy to benchmark different steps of the load with this. For packages with C extensions, the bottleneck is by far loading dynamic libraries once they are in the file system ([Reduce WASM browser compilation time #2288](https://github.com/pyodide/pyodide/issues/2288)). So it would be worth spending more time on optimizing load time of those .so files as @wlach has been doing.

Benchmark looks really cool! I was misunderstanding the package load bottleneck...

> once it's a bit more stable, I would like to move this repo under the pyodide org, unless there are no objections to it?

I have no objection.

**Comment by rth** [comment]
OK, I transferred the repo to https://github.com/pyodide/pyodide-pack . It works experimentally, but still needs more work in particular for stdlib bundling to be more useful. Closing this issue, in favor of more specific issues on the subject.
