### ISSUE TITLE
toJS wrong when a dict contains multiple same dict

### ISSUE THREAD

**Issue by eagleoflqj** [pyodide/pyodide#2530]
### To Reproduce

```js
d = pyodide.runPython('d={0: {1: 2}}; d[1]=d[0]; d').toJs({dict_converter: Object.fromEntries}) 
```
### Expected behavior

`d[0] === d[1]`, and changing `d[0]` will also change `d[1]`.
### Actual behavior
`d[0]` is an Object but `d[1]` becomes an Array.
### Environment

- Pyodide Version:0.20.0
- Browser version:Firefox 100.0, Chromium 101.0.4951.54
- Any other relevant information:

### Additional context

It's not serious for my usecase. I can just write `d[1]=d[0].copy()`. It's just confusing to get an Array before I realize I should copy the dict.

**Comment by hoodmane** [comment]
Thanks for the report @eagleoflqj!

**Comment by hoodmane** [comment]
Looking at the code, the bug is obvious but the fix is rather less obvious...
