### ISSUE TITLE
Doesn't work in Safari on iOS 15.4.1 (SyntaxError)

### ISSUE THREAD

**Issue by ivanistheone** [pyodide/pyodide#2539]
## 🐛 Bug

I tried the [pyodide repl](https://pyodide.org/en/stable/console.html) using `from sympy import cot` and got a traceback:
![IMG_1304](https://user-images.githubusercontent.com/163966/167445442-0b44bd9a-b9b8-492d-a7b8-4d413bf41946.PNG)

I did a separate test `from sympy import solve` and that works fine. So it seems to be some specific code paths that are not compatible.

### To Reproduce

1. Go to [pyodide repl](https://pyodide.org/en/stable/console.html) 
2.  enter `from sympy import cot`

### Expected behavior

No errors.

### Context

I'm running iOS 15.4.1 on a iPhone SE 2nd gen.

**Comment by rth** [comment]
Thanks for the report! So far. I can't reproduce it in 
 - Safari 13, IOS 15.2  on Iphone 13
 - Safari 13 pro, IOS  15. 3 on Iphone 13 Pro
on Browserstack where this import works fine.

They don't have IPhone SE 2nd gen with the right IOS version.

Because it works for Safari in the  expected version of IOS, I wonder if it's due to Phone SE having little RAM (3GB). The error is certainly strange, but it's not the first time that pyodide would fail in some way on low RAM environment. Particularly that you get the same error in Opera (Chrome based), so it's not IOS related.

**Comment by ivanistheone** [comment]
So I wanted to test you hypothesis about RAM   (of which the phone has [3GB](https://www.gsmarena.com/apple_iphone_se_(2020)-10170.php)) using the Safari Web Developer tools (connected via USB to desktop).

Unfortunately the dev tools crashes when I try to log memory usage over time...

On thing that's interesting though... when the USB cable is connected Safari was able to run `from sympy import cot` fine. As soon as I disconnect the cable, then it starts to crash again...

WTF?  Maybe when in "remote debugging mode" there is something about how memory is managed?

**Comment by rth** [comment]
Well, we did encounter browser bugs in the past that only happened with Web Dev tools closed, and weren't reproducible when it was open. Because opening dev tools apparently changes options for WASM compilation in the browser and the code path is not exactly the same. So yes, it's fun to debug.

**Comment by eagleoflqj** [comment]
I have an iPhone 11 and an iPhone 13. My [SymPy Beta](https://github.com/eagleoflqj/sympy_beta) also become unusable after I upgrading to iOS 15.4.1. Tested both Safari and Firefox.
Someone [mentioned](https://news.ycombinator.com/item?id=30682343) there seem a wasm issue with that version of webkit.

**Comment by ivanistheone** [comment]
Yesterday I tried SymPy repl on a recent iPhone 13 and it didn't work on either Safari or Chrome:

![Chrome on iPhone 13 fails](https://user-images.githubusercontent.com/163966/167919689-9b29d603-5a44-4f0d-ba8d-eb0fdddcd671.png) ![Safari on iPhone 13 fails](https://user-images.githubusercontent.com/163966/167919703-23bc2720-02b4-4d51-83f4-5b9631f7a647.png)

Same error... sorry I didn't think to test the pyodide repl, but I'm guessing it will also fail (i.e. there is nothing specific to the JupyterLite wrapper, but an underlying pyodide issue on current iOS).

**Comment by eagleoflqj** [comment]
> And so you get the same error as above in Firefox?

Firefox and Safari sometimes get the same invalid syntax error at https://sympy-beta.vercel.app/terminal, sometimes don't. They both sometimes get stuck when executing https://github.com/eagleoflqj/sympy_beta/blob/a9e762ad46f1b501a1ae585c618d6191d1aaa79d/public/worker.js#L31-L48 but sometimes don't. It's just random and unstable.

**Comment by eagleoflqj** [comment]
It seems upgrading to iOS 15.5 fixes all issues for me. If you can confirm it stable, I think we can then close it.

**Comment by ivanistheone** [comment]
Confirm on iPhone SE iOS 5.5 the command `from sympy import cot` now works on Safari (and Opera since it runs on the same undelying js engine).

Closing.

Yey... JavaScript *eating the world* is back on schedule!

**Comment by hoodmane** [comment]
Thanks again for reporting it.
