### ISSUE TITLE
scikit-learn / 1.1.0

### ISSUE THREAD

**Issue by torshind** [pyodide/pyodide#2571]
## 🐍 Package Update

- Package Name and Version : scikit-learn / 1.1.0
- Package URL : https://files.pythonhosted.org/packages/8b/99/b1ec652f2d60a13871a3053f312f9d78977be57e420f2a49d52ba503f1f4/scikit-learn-1.1.0.tar.gz
- Package Dependencies that needs to be resolved first: numpy, scipy, joblib, threadpoolctl

**Comment by hoodmane** [comment]
Well we already have scikit-learn. Maybe you want it updated?

**Comment by torshind** [comment]
Sure, I had forgotten to edit the title of the template.

**Comment by torshind** [comment]
Thanks a lot!
