### ISSUE TITLE
Adding gpiozero

### ISSUE THREAD

**Issue by sentairanger** [pyodide/pyodide#2573]
I don't know if this would be possible but I would like to control GPIO pins using PyScript on the Pi

## 🐍 Package Request

- Package Name and Version: gpiozero/1.6.2
- Package URL : https://files.pythonhosted.org/packages/86/e1/88d1fde5ce042a12e231ff032ae1aace89670ad15497672b28a6eb5699e9/gpiozero-1.6.2.tar.gz
- Package Dependencies that needs to be resolved first:
colorzero

**Comment by ryanking13** [comment]
Since `gpiozero` is a pure Python package, you can install it with `micropip`.

```py
import micropip
await micropip.install("gpiozero")
```

However, I don't think it will be useful because you can't access phisical devices (`/dev`) in the browser...

**Comment by sentairanger** [comment]
> Since `gpiozero` is a pure Python package, you can install it with `micropip`.
> 
> ```python
> import micropip
> await micropip.install("gpiozero")
> ```
> 
> However, I don't think it will be useful because you can't access phisical devices (`/dev`) in the browser...

I was able to at least get far to identifying the pin factory by also adding pigpio but since that requires a remote connection it won't connect to any remote pi. I'm closing this as you were correct but it was still fun to try.
