### ISSUE TITLE
Fail pyodide_build if used with wrong Python version?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2600]
## 🚀 Feature

In #2599, someone tried to use `pyodide_build` with Python 3.8, which is doomed to fail. We might consider checking the version in `__main__.py` and preemptively failing if someone uses the wrong Python version.

**Comment by hoodmane** [comment]
And a different user hit the same problem in #2602.

**Comment by rth** [comment]
Should be fixed in https://github.com/pyodide/pyodide/pull/2604 assuming they installed pyodide_build, which looks like they did.
