### ISSUE TITLE
Custom package build doc is out of date

### ISSUE THREAD

**Issue by rebornix** [pyodide/pyodide#2602]
The guidance for building custom packages https://pyodide.org/en/stable/development/new-packages.html is out of date and following it leads to errors currently

With Python 3.8.5, I kept getting errors

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rebornix/.local/lib/python3.8/site-packages/pyodide_build/__main__.py", line 5, in <module>
    from . import buildall, buildpkg, create_xbuildenv, install_xbuildenv, mkpkg, serve
  File "/home/rebornix/.local/lib/python3.8/site-packages/pyodide_build/buildall.py", line 21, in <module>
    from . import common
  File "/home/rebornix/.local/lib/python3.8/site-packages/pyodide_build/common.py", line 10, in <module>
    from packaging.utils import parse_wheel_filename
ImportError: cannot import name 'parse_wheel_filename' from 'packaging.utils' (/home/rebornix/.local/lib/python3.8/site-packages/packaging/utils.py)
```

However with Python 3.9, I started to get errors

```
Traceback (most recent call last):
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\site-packages\pyodide_build\__main__.py", line 5, in <module>
    from . import buildall, buildpkg, create_xbuildenv, install_xbuildenv, mkpkg, serve
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\site-packages\pyodide_build\buildall.py", line 21, in <module>
    from . import common
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\site-packages\pyodide_build\common.py", line 12, in <module>
    from .io import parse_package_config
  File "C:\Users\rebor\AppData\Local\Programs\Python\Python39\lib\site-packages\pyodide_build\io.py", line 192, in <module>
    config: dict[str, Any], file_path: Path | str | None = None
```

**Comment by hoodmane** [comment]
You have to use python 3.10 and you need an up to date version of the packaging package. It's recommended to use the pyodide docker image to build packages because probably a lot of other things are different between your local environment and the one expected by pyodide_build.

**Comment by rth** [comment]
@rebornix We can certainly add a section on this in the docs. More worded as "if you use VSCore & Docker then this might make it easier" though I still don't really get the use case for it. In the current setup, the source dir is mounted in docker, so you would edit it on your local system. The only thing that needs run in docker is `PYODIDE_PACKAGES=<some_list> make` currently, so in that context I'm not sure that spending time on the extension setup etc. is really worth it (but maybe I'm missing the expected VSCode workflow).

**Comment by rebornix** [comment]
@bamurtaugh thanks for helping out! 

> In this Pyodide scenario where a user must edit code locally outside of the container, the user would get a lesser experience if they don't have the same tools installed locally, i.e. if a user doesn't have Python

This means the most to me, for issues like https://github.com/pyodide/pyodide/issues/2599, https://github.com/pyodide/pyodide/issues/2600 and this one, we would need Python 3.10 to build pyodide and packages, the recommendations from these issues are using docker container. While at the same time, we would need Python 3.10 for developing Pyodide too (otherwise we will get the same warnings for missing `parse_wheel_filename` if my default Python env on local system is 3.8), that means I would need the same env as the docker container to ensure it's consistent. Dev container will bring my editor (VS Code) into the docker container.

**Comment by ryanking13** [comment]
Thanks for opening the discussion @rebornix and @bamurtaugh!

I am one of the Pyodide core devs and I use Github Codespaces for developing Pyodide. I have used Github Codespaces from its beta release, so I know it is very powerful to use `devcontainer.json` + Remote containers extension or Github Codespaces, especially for projects that require complicated setup like Pyodide.

However, I'm not sure if we want to make the docker environment our "default" build environment. Currently, we are recommending a Docker-based build because there are some issues in building Pyodide in various environments like #2006, #590 while maintainers don't have bandwidths to cover all build environments. But we plan to gradually make the build preparation setup easier so that people can easily build Pyodide (or a single package for Pyodide) without the docker image.

Anyway as a VSCode + Github Codespaces user, personally I am OK with adding (and doing some maintenance work on) devcontainer.json.

**Comment by bamurtaugh** [comment]
Thanks for the feedback @ryanking13! If you'd like another set of eyes on a devcontainer.json, please feel free to let me know, happy to review and share with other folks too.

**Comment by rth** [comment]
I see your points +1 to add it if there are people motivated enough to maintain it :)

**Comment by ryanking13** [comment]
We do have devcontainer configurations now, and minimum required python version is also specified in pyodide-build. Closing as resolved.
