### ISSUE TITLE
open_url not working?

### ISSUE THREAD

**Issue by johann-petrak** [pyodide/pyodide#2659]
I am starting a Firefox browser (version 100.0.2) on Ubuntu linux 22.04, using a new profile/

Navigating to https://pyodide.org/en/stable/console.html showing banner:
```
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, Apr  9 2022 20:52:01) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
```

In the console I run and get an unexpected exception:

```
>>> import pyodide
>>> pyodide.http.open_url("https://www.w3.org/Protocols/HTTP/")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 41, in open_url
    req.send(None)
JsException: NetworkError: A network error occurred.
``` 

Another attempt:
```
>>> url = "https://www.ofai.at/about"
>>> with open_url(url) as infp:
...     text = infp.read()
... 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 41, in open_url
    req.send(None)
  File "https://pyodide.org/en/stable/console.html", line 1, in XMLHttpRequest.prototype.send<
JsException: NetworkError: A network error occurred.
```

**Comment by rth** [comment]
Yes, if you open the JS console you would see the following error,
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource 
at https://www.w3.org/Protocols/HTTP/. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```
So the server needs to configure CORS headers correctly, otherwise it won't work.

It's a very common issue we should probably,
 - mention it in the docstring https://pyodide.org/en/stable/usage/api/python-api.html#pyodide.open_url (BTW we have a duplicate `pyodide.open_url` and `pyodide.http.open_url` and we should remove the first one from the docs)
 - maybe catch and rewrite the exception to mention this possibility.

**Comment by ryanking13** [comment]
> * maybe catch and rewrite the exception to mention this possibility.

yes, probably we should provide an error message similar to what we are doing in micropip.

https://github.com/pyodide/pyodide/blob/fdb0a3581d3cc541312569bd06b52906da4d3592/packages/micropip/src/micropip/_micropip.py#L95-L100

**Comment by johann-petrak** [comment]
I do not know much about the details of the HTTP protocol, but if my browser can access and fetch that page, why can't the pyodide code running another window of the same browser? All browsers I tried will fetch and show that site, and when i use Python code e.g.

```
import requests
req=requests.get("https://www.w3.org/Protocols/HTTP/")
print(req.text)
```
that works too, so why should it correct for `open_url` to produce an error?

**Comment by rth** [comment]
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is a browser security feature aiming to restrict which other resources can be loaded on a given web page (origin). In terms of CORS the website where you are running is pyodide.org (which is where the console is), not your local address. It's not specific to Pyodide, the same would happen when those links are fetched in javascript. On the other side, Pyodide can fetch those resources in Node.js without issues, as it doesn't have this limitation specific to the browser.

> I literally tried a dozen URLs now and NONE of them worked, all showing the same error message in the browser console.
What is the use of open_url if it does not work at all? 

Most of the URLs that you tried did not work because they are not resources that are intended to be shared between pages. For instance, website admins likely explicitly don't want anyone to be able to load https://www.w3.org/Help/ on any other page than that one. On the other side things, like PyPi packages, datasets, often images etc are shared resources and will have correct CORS headers  to allow access from a different origin. If not, you can request it from the website admins.

**Comment by loosak** [comment]
For your  testing purposes you can run Chrome without CORS with `--disable-web-security` (more in mdns link from @rth). I  tested  your link https://www.ofai.at/about with `pyodide.open_url` and it works.

**Comment by johann-petrak** [comment]
Thank you! I guess this completely out of my control then - I wanted to use pyodide for a zero-installation tutorial and playground for a library which is a lot about fetching arbitrary HTML pages and processing them. For this, I have to limit the tutorial to pages where I can make sure that CORS limitation is not active.

**Comment by ryanking13** [comment]
> I guess this completely out of my control then

One possible option is to use the CORS proxy server (e.g. https://corsproxy.github.io/).

**Comment by johann-petrak** [comment]
Thanks @ryanking13 but sadly this does NOT work with pyodide `open_url`, apparently, I just tested a bunch of URLs.

On the contrary, even the rare URL which does work with pyodide `open_url` before, does produce a network error when prepending `https://crossorigin.me/`. Maybe this is because of what the crossorigin site says: 

```
The [CORS specification](https://www.w3.org/TR/cors/) requires all CORS requests to include an Origin header in every request, so crossorigin.me will respond to requests that do not include it with
Origin: header is required
```

`open_url` does not allow to modify the request I think, so I believe it is not possible to satisfy that requirement of the crossorigin proxy to circumvent the problem?

**Comment by hoodmane** [comment]
Well the implementation of `open_url` is really simple:
https://github.com/pyodide/pyodide/blob/main/src/py/pyodide/http.py#L22
```py
from js import XMLHttpRequest
from io import StringIO
def open_url(url: str) -> StringIO:
    """Fetches a given URL synchronously.
    The download of binary files is not supported. To download binary
    files use :func:`pyodide.http.pyfetch` which is asynchronous.
    Parameters
    ----------
    url : str
       URL to fetch
    Returns
    -------
    io.StringIO
        the contents of the URL.
    """

    req = XMLHttpRequest.new()
    req.open("GET", url, False)
    req.send(None)
    return StringIO(req.response)
```
so you could add [`req.setRequestHeader("Origin", "whatever)`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader):

```py
def my_open_url(url):
    req = XMLHttpRequest.new()
    req.open("GET", url, False)
    req.setRequestHeader("Origin", "whatever)
    req.send(None)
    return StringIO(req.response)
```
We could consider updating `open_url` to be a bit more flexible.

**Comment by ryanking13** [comment]
> On the contrary, even the rare URL which does work with pyodide `open_url` before, does produce a network error when prepending `https://crossorigin.me/`

It seems like `crossorigin.me` service is currently dead. Probably you should find some other services or run your own proxy server.

> so you could add [`req.setRequestHeader("Origin", "whatever)`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader):

Well I think this is not true. `origin` header is automatically set by the browser and the user cannot modify it.

**Comment by johann-petrak** [comment]
As an afterthought, it may be useful to add information about this limitation to the FAQ and/or the `open_url`  docstring to make it easier for people like me to not consider this a bug? :)

**Comment by johann-petrak** [comment]
Sorry, I have another related question: I installed the pyodide release on my computer and served it from there (http://localhost:8000), so I assumed, that it should be no problem to use `open_url`  to load files which are also served by that server as obviously everything should come from the same origin.

However, `open_url("http://localhost:8000/console.html")` again filed with a network error and a message about a blocked cross-origin request on the console. Unfortunately the console message does not show any details.

Why does THAT not work?

**Comment by hoodmane** [comment]
I'm surprised you are getting so many of these errors. If I go to `localhost:8000/console.html` and use `open_url("http://localhost:8000/console.html")` it works fine...

**Comment by johann-petrak** [comment]
Sorry I think that was probably my mistake, I retried on another computer and it works there. I probably had a typo or something. 
I retried deliberately mistyping the port number (8001 instead of 8000) on that other computer and when I look at the console, it shows the same error message as for CORS problems: "Cross-origin Request Blocked....".  So it did not occur to me that this was actually a 404 caused by a typo. But I understand that it is also a CORS problem as the URL with the other port number is a different source. 

Please excuse the spam!
