### ISSUE TITLE
Permissions issue when running in the Docker image

### ISSUE THREAD

**Issue by jobovy** [pyodide/pyodide#2674]
## 🐛 Bug

I'm trying to build `pyodide` and some packages using the Docker image, but get tons of 
```
ccache: error: Failed to create directory //.ccache/tmp: Permission denied
```
errors when not running `make` as root. Running as root does work. According to the docs, this should work I think and I can't find any other issue about this.

### To Reproduce

```
./run_docker
```
and then
```
make
```
inside the container.

### Expected behavior

No permissions issues and a working build!

### Environment

This is using the current `main` branch. I'm using a new docker installation on CentOS 7.

- Commit hash: 587a73fa14e1ffceec5380d884214f9d36d45be1
- Build environment: CentOS Linux release 7.9.2009 (Core)

### Additional context

Running
```
./run_docker --root
```
works fine.

**Comment by hoodmane** [comment]
I think it's a problem with the $HOME environment variable. It's value should be `/src/docker_home` and that's where the ccache directory should be created.

**Comment by jobovy** [comment]
Yes, $HOME is now just set to /. I think this happens because the user isn't correctly added (it's also not added to the `sudo` users). And I think that happens because line 130 here wrong
https://github.com/pyodide/pyodide/blob/0283a39629980824f98b5bb4e78b5f5a395f1fbe/run_docker#L129-L133
I think it should be
```
groupadd --gid '$USER_GID' '$USER_NAME'; \
```
According to `useradd`'s documentation, the flag for setting the home directory is also just ``--home``, not ``--home-dir``. With that, `echo $HOME` gives the right result in the container.

I can submit a fix.

**Comment by hoodmane** [comment]
> I can submit a fix.

Please do. I'm a bit confused why this is working for us but not for you though.

**Comment by jobovy** [comment]
Yeah, that's confusing to me too and why I searched the Issues for a long time, because surely this must be a problem for everybody else... I do remember that when I did some `pyodide` work a few months ago, I also just had to run as `root`, and that was on a Mac, so it doesn't seem specific to my current setup?

**Comment by hoodmane** [comment]
Well I will try out your branch soon and as long as it seems to work I will merge it. I don't understand this stuff very well so we're operating on a "seems to work" basis here.
