### ISSUE TITLE
API Better organisation of the `pyodide` Python package

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2689]
The `pyodide` Python package namespace is getting rather cluttered. It includes a mix of a bit random things, for instance,
 - functions related to the FFI: `create_proxy`, `to_js`, `create_once_callable`, `JsProxy`, ...
 - functions related to running code: `CodeRunner`, `run_js`
 - wrappers of JS functions: add_event_listener, `set_interval`, `open_url`, `pyfetch`
 - various util functions:  `find_imports`, `repr_shorten`
 - exceptions: JsException

and the situation is only going to get worse with time.
 
While it makes sense to keep some of these objects at the top level, others should be IMO moved to submodules. Right now the feeling I get when opening [the API docs page](https://pyodide.org/en/latest/usage/api/python-api.html) is that it's a bit messy and without much logic as to what things one can expect to find in this package.

So I would propose to,
 - [ ] more carefully review functions / classes present in this package and decide what should be moved to submodules (I'll comment more about it later)
 - [ ] create a documentation page per submodule. For example, in CPython [`http`](https://docs.python.org/3/library/http.html) API docs starts by linking to submodules (http.client, etc) which have separate documentation pages, before listing the objects it contains. I think we should do something similar. Now we have everything listed on the main page (e.g. `Console`) and others have no easily accessible  documentation (e.g. `pyfetch`) 
 - [ ] move functions to their respective submodules. When necessary allow a top-level import but with a FutureWarning stating that this will stop working, say in 2 releases. There is a balance to find to avoid too many warnings as that would be annoying for users.

Particularly for newly added functions `set_interval`, etc it's important to do this before the next release.

**Comment by hoodmane** [comment]
I propose an `eval` submodule for CodeRunner, eval_code, etc, an `ffi` submodule for the ffi related stuff, and a `browser` submodule for the setTimeout wrappers.
