### ISSUE TITLE
Faster `./run_docker --pre-built` setup

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#2705]
It takes quite a while to run (several mins), and unless I'm mistaken it should be possible to run it during creation of the pre-built Docker image?

Note that if I don't run `make` before trying to run `python -m pyodide_build buildpkg meta.yaml`, then I get this:
```
ERROR: bash command failed
    source /src/emsdk/emsdk/emsdk_env.sh
```
So I'm assuming that `make` must be executed before trying to build packages.

**Comment by josephrocca** [comment]
I realised while writing [this](https://github.com/pyodide/pyodide/pull/2704#discussion_r896381622) that the Docker image doesn't have access to the Pyodide repo, so it can't pre-`make` stuff. Hmm.

**Comment by ryanking13** [comment]
https://github.com/pyodide/pyodide/blob/8d30ebdf136c3626a94193b47a04ccc263549cf9/Dockerfile-prebuilt#L14

Hmm, we definitely run `make` when we make a prebuilt image. I'm not sure why that error happens. Could you check emsdk directory inside the prebuilt docker image?

**Comment by ryanking13** [comment]
Okay... the problem is that we copy all build results into `/src/pyodide` of prebuilt docker image. But when we use `./run-docker --pre-built` we bind local source-tree to `/src` so `/src/pyodide` is gone. We have to fix `./run_docker --pre-built` behavior...

**Comment by josephrocca** [comment]
@ryanking13 Could Pyodide be built at e.g. `/pyodide` instead? Or is there a better solution that we could implement here?

Another potential improvement to the process of building a package would be to make it so a `git clone` isn't required either. Currently that's needed to get the `./run_docker --pre-built` command. Ideally it would just be a one-line `docker run` command and then you can immediately run `mkpkg` and `buildpkg`. Is that possible?

**Comment by ryanking13** [comment]
> Another potential improvement to the process of building a package would be to make it so a `git clone` isn't required either. Currently that's needed to get the `./run_docker --pre-built` command. Ideally it would just be a one-line `docker run` command and then you can immediately run `mkpkg` and `buildpkg`. Is that possible?

Yeah, I think that is a better idea, as we don't want to bind the host source tree when using a pre-built docker image. I'm not sure what would be the best way to use a pre-built docker image though.

I think the ideal way of using a pre-built docker image in the future would be something like this:

```
pyodide-build mkpkg <some-pkg>
docker run -v <some-pkg-dir>:/pkg-dir.. pyodide/pyodide:0.20.0 pyodide-build buildpkg /pkg-dir/meta.yaml
```

But I guess we will have to improve out-of-tree build beforehand (https://github.com/pyodide/pyodide/pull/2550#issuecomment-1128110513).

**Comment by josephrocca** [comment]
@hoodmane Wondering if you have a concrete plan/idea for [this](https://github.com/pyodide/pyodide/pull/2550#issuecomment-1128110513)? Sounds like this can move forward after @rth's #2132 is merged?

Current situation makes it hard to create a minimal replication of a bug in the Pyodide build tools because each iteration takes >5mins (due to long `make` step).

**Comment by ryanking13** [comment]
> Current situation makes it hard to create a minimal replication of a bug in the Pyodide build tools because each iteration takes >5mins (due to long `make` step).

Once you set up build environments by running `make`. I think you can skip the setup parts and jump into the package build step by running `python -m pyodide_build buildpkg meta.yaml`.

**Comment by josephrocca** [comment]
Ah so I really only need to re-run `pip install ./pyodide-build` after e.g. editing `buildpkg.py` or `pypabuild.py`, etc. when trying to debug Pyodide build tooling? That makes sense!

Still, it would be great if it were possible to launch the docker image in a freshly cloned Pyodide repo and immediately use `buildpgk`/etc. I wonder if it's possible to have the `make` build artifacts cached somewhere within the docker image, and `make` just uses them if the content hashes match, or something like that? Sounds kind of messy, and not sure if something like that would be viable. Might be worth waiting for out-of-tree build stuff like you said.

**Comment by ryanking13** [comment]
> Ah so I really only need to re-run `pip install ./pyodide-build` after e.g. editing `buildpkg.py` or `pypabuild.py`, etc. when trying to debug Pyodide build tooling? That makes sense!

You don't even have to re-run `pip install ./pyodide-build` because do editable install during `make` (this behavior might change in the future though.)

https://github.com/pyodide/pyodide/blob/8e8ccffddc669aad0b982798d93f0f10f8d11a78/packages/Makefile#L17-L18

> Still, it would be great if it were possible to launch the docker image in a freshly cloned Pyodide repo and immediately use `buildpgk`/etc.

Yeah, I also think that would be awesome. I believe the usage of the pre-built docker image can be improved, but it is somewhat broken for now...

**Comment by ryanking13** [comment]
`--pre-built` is not supported anymore. When buliding a package, we recommend [building packages out-of-tree](https://pyodide.org/en/stable/development/building-and-testing-packages.html).
