### ISSUE TITLE
Ability to run script within Pyodide build environment within `build.script` or another `build` sub-property in `meta.yaml`

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#2726]
As discussed [here](https://github.com/pyodide/pyodide/issues/2198#issuecomment-1153100002) it'd be useful to have a way to run `build.script` inside the Pyodide build environment. One way to do this would be to have a `build.pre` and `build.pre-env`. The `build.script` property could be kept specifically for library packages (i.e. when `built.library:true`) and could maybe even throw an error if `built.library` is not `true`.

One disadvantage of this approach is that there may be situations where you'd want to have `build.pre` run before `build.pre-env`, and other situations where you'd want the opposite. Might it be possible to have a special command that can be used in `build.script` that would activate the Pyodide build environment, and another command to deactivate it? That would give a lot more freedom, but I don't know enough about the build process to know if it's practical.

Anyway, I figured that I'd create an issue to track this eventual improvement.

**Comment by josephrocca** [comment]
This is being worked on by hoodmade here: #2734

**Comment by agriyakhetarpal** [comment]
I think this can be closed, as the linked PR #2734 has been merged since, and several packages' recipes are using this feature, too.
