### ISSUE TITLE
Micropip should be able to install wheels from the file system

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2731]
## 🚀 Feature

Micropip should be able to install a wheel which is in the emscripten file system from a path.

### Motivation

In node (and some day maybe in chrome), we can mount the local file system into the Emscripten file system. It would be useful to install these, for instance when testing whether a wheel was built correctly.

**Comment by jtpio** [comment]
Posting here for visibility.

The latest JupyterLite release adds support for accessing files from the Python (Pyodide-based) kernel: 

- https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b9
- https://github.com/jupyterlite/jupyterlite/pull/655

While the mounting logic is a bit specific to JupyterLite / JupyterLab and enabled via a `ServiceWorker`, making `micropip` able to install packages from a local path would still be useful.

For example one could upload a wheel (or ship it as part of the default content) and install it with:

```py
import micropip
await micropip.install('./snowballstemmer-2.2.0-py2.py3-none-any.whl')
```

![image](https://user-images.githubusercontent.com/591645/174308580-85a6303a-ad42-46da-84cc-725ddeaebe94.png)

**Comment by hoodmane** [comment]
Maybe it can be `micropip.install_file`? `install_from_filesystem`?

**Comment by jtpio** [comment]
Probably from a user point of view keeping the same `micropip.install()` would be more convenient? (like regular `pip`)

**Comment by hoodmane** [comment]
We currently interpret `micropip.install("a/b/c.whl")` as a relative URL, so there is no syntax space for that. Unless you want to do `micropip.install(from_path="a/b/c.whl")`?

**Comment by bollwyvl** [comment]
What about intercepting `file://` before fetch as meaning _file in the WASM machine_? I'd think pyodide itself could not be usefully loaded when "hosted" from `file://` because `.json`, much less `.wasm`, would not be served properly. Further no _other_ protocol would be able to resolve it.

**Comment by hoodmane** [comment]
What about relative paths though?

**Comment by bollwyvl** [comment]
Well, URIs don't _necessarily_ have to start with `<protocol>:/`: there's certainly precedent for non-slashed paths, e.g. python's [sqlite3]() module, which inherit's [sqlite's implementation](https://www.sqlite.org/uri.html):

```py
# Open a database in read-only mode.
con = sqlite3.connect("file:template.db?mode=ro", uri=True)
```

So, with the default settings, `file:some-package.whl` could be interpreted the same as `file:/home/pyodide/some-package.whl`.

**Comment by rth** [comment]
> What about intercepting file:// before fetch as meaning file in the WASM machine?

The problem is that when run in Node.js, `file://`  [means host file system](https://nodejs.org/api/fs.html#file-url-paths). Though for Python `file://` would probably still mean the whatever FS Python is installed in. We would want to keep a consistent behavior in the browser and Node. Maybe `memfs://` at least as far as micropip is concerned?

**Comment by fire17** [comment]
hey guys! awesome to see this being on the table so recently
got here while searching for a way to use my own packages in pyscript
for example i've got a package called xo-gd, which i want to use, but i cant seem to import it

seems like this is a requested feature not yet available seemlessly,
does anyone know of a way for me to do this? do i need to build pyodide myself with this package? or should i just copy all the python files from my package locally ? (it's already all on pip, so i thought it should be straight-forward)

any info would be appreciated! thx & have a good one!

**Comment by rth** [comment]
@fire17 Would you mind opening a separate issue about it? It's a bit orthogonal to the current discussion. The general documentation for adding a package can be found [here](https://pyodide.org/en/stable/development/new-packages.html). Looking at the xo-gd description, it looks like a lof of the functionality it exposes will not be supported in the browser (let's discuss the details in a separate issue).

**Comment by rth** [comment]
> micropip.install(from_path= [..] we can figure out the details a bit later.

Maybe someone should try to do a draft implementation. I suspect that having two inputs would make the implementation less straightforward as currently we just pass a list of requirements everywhere. Also, it's not very common in Python to have multiple and mutually exclusive input arguments, that's probably the reason for the URL file prefix, instead of doing `urlopen(from_http=None, from_https=None, from_ftp=None, etc)`.

For some things, we can figure out the details later, but micropip.install is likely one of the most frequently used functions by end users. So it would be good to agree on a public API and implement it, so we can avoid API breakages or deprecations for this (unless we can finish iterating on it before the next release).

**Comment by hoodmane** [comment]
Well what about going with @bollwyvl's suggestion. We could set it up so that `file://` makes a fetch request but `file:some/path` can goes to the local file system.

**Comment by hoodmane** [comment]
Or maybe `emfs:some/path`. I don't care for `memfs` because it is possible to mount other file systems e.g., `nodefs` and then it's a bit confusing. But they are all the Emscripten file system.

**Comment by bollwyvl** [comment]
"emfs:" is concise yet distinctive. The unslashed-is-relative seems
reasonable as well.

I do still like the idea being able to  (re)register of new protocol
handlers that can handle both wheels and warehouse-like API responses...
But "wheels on the disk" seems like a fine place to start.

**Comment by rth** [comment]
OK, let's go with `emfs:`.

Actually I wasn't aware that,
> - The // after the file: denotes that either a hostname or the literal term localhost will follow,[[2]](https://en.wikipedia.org/wiki/File_URI_scheme#cite_note-2) although this part may be omitted entirely, or may contain an empty hostname.[[3]](https://en.wikipedia.org/wiki/File_URI_scheme#cite_note-3)
>-  file://path (i.e. two slashes, without a hostname) is never correct, but is often used

https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by hoodmane** [comment]
Thanks everyone for the discussion!
