### ISSUE TITLE
pyfetch TypeError: pyfetch() takes 1 positional argument but 4 were given

### ISSUE THREAD

**Issue by coinmaster4you** [pyodide/pyodide#2739]
## 🐛 Bug

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "", line 26, in main File "", line 7, in request File "/home/pyodide/py.py", line 8, in fetch_GRAPHQL fetch = await pyfetch(url,methode, headers, body) TypeError: pyfetch() takes 1 positional argument but 4 were given )

### To Reproduce

`await pyfetch(url,methode, headers, body)`

### Expected behavior
async http.pyfetch(url: str, **kwargs) → [pyodide.http.FetchResponse](https://pyodide.org/en/stable/usage/api/python-api.html?highlight=pyfetch#pyodide.http.FetchResponse)

### Environment
pyscript
- Pyodide Version: unknown
- Browser version: 102.0.5005.115
- Any other relevant information:

**Comment by ryanking13** [comment]
pyfetch only takes keyword arguments.

Try:

```
await pyfetch(url, method=method, headers=headers, body=body)
```

**Comment by rth** [comment]
Indeed the function [documentation is here](https://pyodide.org/en/stable/usage/api/python-api.html?highlight=pyfetch#pyodide.http.pyfetch) and it doesn't allow passing those as positional arguments.

Closing as "won't fix", sorry.
