### ISSUE TITLE
Release v0.21.0a1

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#2740]
We added Pyodide to the maturin and setuptools-rust CI but they are currently using nightly Pyodide which is a bit awkward. There's a lot in the changelog so we should think about making a release soon in any case.

**Comment by ryanking13** [comment]
Yes, it is slightly faster than our previous release cycle but I think we have enough changes and new packages to make a release.

**Comment by rth** [comment]
+1 We should probably start tagging for 0.21.0 things we want merged/fixed before the release.

**Comment by hoodmane** [comment]
There's still a handful of things I'd like to put in, maybe release a1 this week, a2 next week, and the main release in two weeks. Or slower. We'll see what happens.
