### ISSUE TITLE
Pyodide crashes when loaded in a Jest Unittest.

### ISSUE THREAD

**Issue by msebas** [pyodide/pyodide#2764]
## 🐛 Bug

I tried to write unittests for some code utilizing pyodide and vue. I did run into a whole set of errors until I failed to resolve `TextEncoder is not defined` while trying to load pyodide.

Summary:
* pyodide with `node` works like a charm.
* jest only starts with node option `--experimental-vm-modules`
* with jest `indexURL` has to be defined, otherwise the result is a `Error: Cannot find module '.../pyodide-test/node_modules/src/js/pyodide.asm.js' from 'node_modules/pyodide/pyodide.js'`
* `pyodide.asm.js` crashes with `Error: thrown: bad input to processPackageDataError:` unless modified (see 'To Reproduce')
* (currently unresolved) pyodide crashes with `ReferenceError: TextEncoder is not defined`

If anyone could hint me how to resolve the current showstopper I am ready to look into any followup issue (even if I am not sure if I could resolve it).

### To Reproduce

Enable vue testing with jest via
```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest'
}
```

Modify `pyodide.asm.js` by disabling 
`assert(arrayBuffer instanceof ArrayBuffer, "bad input to processPackageData");` in `function processPackageData(arrayBuffer)`, because the `arrayBuffer instanceof ArrayBuffer` is `false` even if `arrayBuffer.constructor.name == "ArrayBuffer"` is `true` (or one could change the assertion to work in this case, but the file is auto-generated anyway...).

Insert you local path in the code below as `indexURL`

```
describe('pyodide', () => {
    let pyodide = null;
    beforeAll(async () => {
        let pyodide_pkg = await require("pyodide/pyodide.js");
        pyodide = await pyodide_pkg.loadPyodide({
            indexURL: "/this/is/your/path/to/the/local/project/node_modules/pyodide/",
        })
    })
    it('can load', () => {
        expect(pyodide).not.toBe(null)
    });
})
```

run `node --experimental-vm-modules node_modules/jest/bin/jest.js`

### Expected behavior

Test successful.

### Observed behavior

Test fails with error message 
```
TextEncoder is not defined
ReferenceError: TextEncoder is not defined
    at createStdinWrapper (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/src/js/module.ts:63:19)
    at /home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/src/js/module.ts:54:22
    at callRuntimeCallbacks (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:9796:25)
    at preRun (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:6586:17)
    at run (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:56432:17)
    at runCaller (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:56385:33)
    at removeRunDependency (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:6664:25)
    at receiveInstance (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:6762:21)
    at receiveInstantiationResult (/home/sebastian/workspace/pyodide_bug/pyodide-test/node_modules/pyodide/pyodide.asm.js:6768:21)
```

### Environment

node: v16.13.1
pyodide: 0.20.1-alpha.2

`package.json`:
```
{
  "name": "pyodide-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test": "jest",
    "offline": "node src/offline.js"
  },
  "dependencies": {
    "@vue/cli-plugin-unit-jest": "^5.0.4",
    "@vue/test-utils": "^2.0.0",
    "core-js": "^3.6.5",
    "pyodide": "^0.20.1-alpha.2",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.13",
    "@vue/cli-plugin-eslint": "~4.5.13",
    "@vue/cli-service": "~4.5.13",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/vue3-jest": "^27.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

### Additional context

Nice piece of software.

I made a test repository in https://github.com/msebas/pyodide-test to simplify reproducing the problem above.

**Comment by hoodmane** [comment]
Looks like there is a solution here:
https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest

**Comment by msebas** [comment]
Hello and thanks. 

Seems like this does resolve the problem. Now the test finishes without issues.

Kind regards

**Comment by msebas** [comment]
I made a mistake. The error does NOT occur with the given setup. I edited the setup and made a test repository in https://github.com/msebas/pyodide-test to simplify reproduction. 

The problem does only occur if jest is configured to use 
```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest'
}
```

I do not know if this is something that should work, but from my point of view this reopens the problem itself.

**Comment by hoodmane** [comment]
> with jest indexURL has to be defined, otherwise the result is a Error: Cannot find module '.../pyodide-test/node_modules/src/js/pyodide.asm.js' from 'node_modules/pyodide/pyodide.js'

As a quick fix for this, I recommend `rm node_modules/pyodide/*.map`.
