### ISSUE TITLE
ctypes c_longlong, c_longdouble crash: wasm function signature contains illegal type

### ISSUE THREAD

**Issue by tiran** [pyodide/pyodide#2766]
## 🐛 Bug

I'm testing ``libffi-emscripten`` with Python upstream main. Any tests related to ``c_longdouble``, ``c_longlong``, and ``c_ulonglong`` is crashing the runtime environment. Did you see the crash on 3.10?

```
test_longlong_callbacks (test.test_ctypes.test_as_parameter.AsParamPropertyWrapperTestCase.test_longlong_callbacks) ...
 exiting due to exception: TypeError: wasm function signature contains illegal type,TypeError: wasm function signature contains illegal type
    at ffi_call (/python-wasm/cpython/builddir/emscripten-node/python.js:1726:4321)
    at _ctypes_callproc (<anonymous>:wasm-function[4575]:0x2f8d83)
    at PyCFuncPtr_call (<anonymous>:wasm-function[4492]:0x2f23ff)
    at _PyObject_MakeTpCall (<anonymous>:wasm-function[864]:0x19bf53)
    at PyObject_Vectorcall (<anonymous>:wasm-function[872]:0x19c619)
    at _PyEval_EvalFrameDefault (<anonymous>:wasm-function[3274]:0x283e06)
    at _PyEval_Vector (<anonymous>:wasm-function[3275]:0x288167)
    at _PyFunction_Vectorcall (<anonymous>:wasm-function[878]:0x19ca3c)
    at method_vectorcall (<anonymous>:wasm-function[925]:0x19ea14)
    at _PyVectorcall_Call (<anonymous>:wasm-function[871]:0x19c4eb)

```

### To Reproduce

- Build libffi-emscripten tag 2022-04-03
- ``cp .libs/libffi.a /emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/``
- ``cp include/*.h /emsdk/upstream/emscripten/cache/sysroot/include/``
- Create ``Modules/Setup.local``

```
CTYPES_FLAGS=-DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1 -lffi
_ctypes _ctypes/_ctypes.c _ctypes/callbacks.c _ctypes/callproc.c _ctypes/cfield.c _ctypes/stgdict.c $(CTYPES_FLAGS)
```

- Build Python with:

```
CONFIG_SITE=../../Tools/wasm/config.site-wasm32-emscripten \
  emconfigure ../../configure -C \
    --host=wasm32-unknown-emscripten \
    --build=$(../../config.guess) \
    --with-emscripten-target=node \
    --enable-wasm-dynamic-linking=yes \
    --with-build-python=$(pwd)/../build/python
```
- run tests with ``node python.js -m test test_ctypes``

### Environment

- EMSDK 3.1.12
- CPython main branch
- libffi-emscripten 2022-04-03

**Comment by tiran** [comment]
Error occurs in python.js, function ``function ffi_call(cif,fn,rvalue,avalue)`` in the instruction ``var result = wasmTable.get(fn).apply(null, args)``. I'm using v14.18.2 from emsdk 3.1.12.

**Comment by hoodmane** [comment]
> Any tests related to `c_longdouble`, `c_longlong`, and `c_ulonglong` is crashing the runtime environment.

Are these all types that have size >= 64 bits?

**Comment by tiran** [comment]
Good instincts! The tests are passing with Node v16.14.0 and crashing with v14.18.2

**Comment by tiran** [comment]
That solves the problem with NodeJS 14 but now fails with NodeJS 16:

```
$ node --experimental-wasm-bigint python.js -m test test_ctypes
node: bad option: --experimental-wasm-bigint
```

**Comment by tiran** [comment]
YW!

https://github.com/python/cpython/pull/94142 addresses the issues in CPython 3.11 and main.
