### ISSUE TITLE
Truthiness of HTMLElement

### ISSUE THREAD

**Issue by Korijn** [pyodide/pyodide#2802]
## 🐛 Bug

Inconsistency in Python wrappers:

```py
>>> import js
>>> el = js.document.createElement("select")
>>> bool(el)
False
```

```js
el = document.createElement("select")
!!el
true
```

### Expected behavior

True! :)

### Environment

- Pyodide Version: 0.20.0
- Browser version: Chrome 102.0.5005.115

### Additional context

I was trying this in pyscript.

**Comment by hoodmane** [comment]
The false comes from the fact that `el.size === 0`:
https://github.com/pyodide/pyodide/blob/main/src/core/hiwire.c?#L727
There's a helpful comment: `// I think things with a size are all container types.` I guess that's not true.

**Comment by hoodmane** [comment]
So it's only false for `select` elements:
```py
bool(document.createElement("div")) # True
bool(document.createElement("a")) # True
bool(document.createElement("select")) # False
```
