### ISSUE TITLE
Install libraries following the protocol of emscripten ports.

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2805]
## Proposed refactoring or deprecation

We have two types of libraries that are used in the build:

1. Library ports that are officially provided by Emscripten (e.g. libjpeg, libpng, freetype, sdl)
2. Libraries that we build ourselves (e.g. libwebp, ffmpeg, openssl, libxml, sqlite3)

I think it would be great if we can install all libraries following the protocol of how emscripten installs its port. I think we can [write a port script](https://github.com/emscripten-core/emscripten/tree/main/tools/ports) and let emscripten ([embuilder](https://github.com/emscripten-core/emscripten/blob/main/embuilder.py)) deal with it.

### Motivation

If it works properly, we can take advantage of the features that emscripten provides. For example, emscripten automatically injects [cflags](https://github.com/emscripten-core/emscripten/blob/e91ea21531264f12e38a681485887212315ba08c/emcc.py#L784) and [pkg config path](https://github.com/emscripten-core/emscripten/blob/e91ea21531264f12e38a681485887212315ba08c/tools/building.py#L153-L154), so we don't have to use e.g. `WASM_LIBRARY_DIR`.

Also, I think it would be helpful for situations like #2555 in which some libraries (ssl, sqlite3) are required in both CPython and package build.

Maybe we can also have chances to upstream the library ports that we built.

**Comment by rth** [comment]
> If it works properly,

What would be the workflow if  something doesn't work as expected: do we patch embuilder or there is enough flexibility to do this in the port script?

I see the appeal of this in the sense that it would allow us share packages setups with emscripten. So far though there aren't that many packages there, and it would basically make two build systems we would have to support.

So I agree that the current situation with cpython/Makefile is far from ideal. The way I saw it is that we would eventually move those to `meta.yaml` definitions, though that would also require moving cpython to be a package and I'm not quite sure how to achieve this. 

I'm not opposed to using ports more, but it would need to discuss more what would be implications of this, in terms of management of dependencies, how it would integrate into our build system, and how users would know whether use ports or meta.yaml format. 

Also ideally in the medium term, I think we should move package definitions to a separate repo, once the build system is more stable, so we can decouple package deployment from pyodide releases. There also I'm not sure what would be the implication of using ports.

**Comment by ryanking13** [comment]
> > There also I'm not sure what would be the implication of using ports.
> 
> > but we would need to discuss more what would be implications of this,
> 
> I think using ports can help us manage build dependencies, which eventually can help us separate packages into repositories.
> 
> For now, we are not separating run-time and build-time dependencies, but when we make #2132 working, we don't need to know about runtime dependencies during the build. Since most build-time dependencies are libraries except for special cases like numpy, I think it may be possible to build most of the Python packages without knowing other packages.

For example, I think the out-of-tree build that Hood is working on (#2811) can be more easier, because the Emscripten will automatically inject most of library include/lib paths.

**Comment by rth** [comment]
My concern is how we would present this to the users.

> If it is a static library, we can recommend users write a port. meta.yaml format for libraries will be still available. For a shared library, it would be more complicated than static libraries, because we need to pack them together into the distribution.

Our instructions for building a new package are already quite complex, and saying you have to use a completely different format depending on whether it's a static or a dynamic library IMO would make it worse. Also, I quickly searched for some of the functions used in ports https://github.com/pyodide/pyodide/pull/2806/files#diff-c5ad5907f4770f937efd94f8883d114f865c8493a7cfb50ec9bc5dfe3750ec3bR15 (e.g. fetch_project, clear_project_build, install_headers) and as far as I can tell they are not documented (short of reading emscripten code). 

So sorry I'm -1 for using ports as public API for building packages.

On the other hand, it's just Python code. Can't we put those build configurations in `packages/meta.yaml` have a  flag to tag  them as a static library,  build them without dependency resolution from `cpython/Makefile` and call emscripten python API if need be to make include/lib paths management easier?

**Comment by ryanking13** [comment]
> Our instructions for building a new package are already quite complex, and saying you have to use a completely different format depending on whether it's a static or a dynamic library IMO would make it worse. Also, I quickly searched for some of the functions used in ports https://github.com/pyodide/pyodide/pull/2806/files#diff-c5ad5907f4770f937efd94f8883d114f865c8493a7cfb50ec9bc5dfe3750ec3bR15 (e.g. fetch_project, clear_project_build, install_headers) and as far as I can tell they are not documented (short of reading emscripten code).
> 
> So sorry I'm -1 for using ports as public API for building packages.

Okay, I understand your concern. I also think it would make our build system more complicated.

> On the other hand, it's just Python code. Can't we put those build configurations in `packages/meta.yaml` have a flag to tag them as a static library, build them without dependency resolution from `cpython/Makefile` and call emscripten python API if need be to make include/lib paths management easier?

Yes, I think it is possible. I think it is a bit complicated to do that in our current build system because for now we build CPython first and build packages later. Maybe #1977 can make this easier... I am working on it very slowly.
