### ISSUE TITLE
Running make using pre-built docker fails

### ISSUE THREAD

**Issue by afbarbaro** [pyodide/pyodide#2808]
## 🐛 Bug

Running `make` fails with this error, using the provided Docker image (pre-built):

```
./tools/dependency-check.sh
date +"[%F %T] Building emsdk..."
[2022-06-29 15:08:11] Building emsdk...
make -C emsdk
make[1]: Entering directory '/src/emsdk'
if [ -d emsdk ]; then rm -rf emsdk; fi
git clone --depth 1 https://github.com/emscripten-core/emsdk.git
Cloning into 'emsdk'...
error: chmod on /src/emsdk/emsdk/.git/config.lock failed: Operation not permitted
fatal: could not set 'remote.origin.url' to 'https://github.com/emscripten-core/emsdk.git'
make[1]: *** [Makefile:8: emsdk/.complete] Error 128
make[1]: Leaving directory '/src/emsdk'
make: *** [Makefile:232: emsdk/emsdk/.complete] Error 2
```

### To Reproduce

```
./run_docker --pre-built
make
```

### Expected behavior
No errors should occur

### Environment

- Pyodide Version latest (0.21.0a2) - main branch

**Comment by afbarbaro** [comment]
My goal was to create a package for `bokeh` and I'm following the instructions here: https://pyodide.org/en/latest/development/new-packages.html#building-a-python-package

Even with the above error, I was able to run `pip install ./pyodide-build` and `python -m pyodide_build mkpkg bokeh` and the `meta.yaml` seems to have been properly created.

I wonder if the instructions are not correct and one does not need to run `make` when using the prebuilt image? 🤔

**Comment by hoodmane** [comment]
Try `sudo make -C emsdk`?

> one does not need to run make when using the prebuilt image?

You don't ever need to run `make` to run `mkpkg`. In the prebuilt image you might not need to run `make` even to build the actual package. I never use the prebuilt docker image so I'm not really sure.

**Comment by rth** [comment]
Bokeh has a pure Python wheel on PyPi, so normally you don't need to package it.
```
>>> import micropip
>>> await micropip.install('bokeh')
>>> import bokeh
```
should work.

**Comment by afbarbaro** [comment]
The approach given by @rth in [this comment](https://github.com/pyodide/pyodide/issues/2808#issuecomment-1170219710) works well. Also, I found out `bokeh` is already included in the `pyodide` distribution on `npm`.  Thanks for the help!
