### ISSUE TITLE
Opt out of dynamic linking and enable threads?

### ISSUE THREAD

**Issue by allsey87** [pyodide/pyodide#2839]
## 🚀 Feature

As I understand, pthreads + dynamic linking is buggy in Emscripten. This is at least true for the 2.x.x series of Emscripten, but may no longer be the case in the 3.1.x series of Emscripten (which looks like it will be used in the upcoming 0.21.0 release of Pyodide). I am indifferent to dynamic linking, but I would like an option to opt out of it if it means getting pthread support in return.

### Motivation

For some applications, it is not possible to work around threading and the cost of linking everything statically (wasm download and compilation time) is a reasonable price to pay.

### Pitch

If it is still not possible to enable both dynamic linking and pthreads in the 3.1.x series of Emscripten, I would like to add an option to opt out of dynamic linking (which would allow for pthread support via Emscripten).

### Additional context

Related issues, questions and PRs:
- #237
- #796
- #2223

**Comment by joemarshall** [comment]
I don't think this makes sense - the amount of work to create a statically linked pyodide would be quite a lot, and the download would be really biggety big unless you skimped on packages.  

I think it would be less work to move over to latest emscripten first and then build with threads and dynamic linking. I did a little playing with it but ran out of time, doing emsdk update at the same time as threads was too much changing.

**Comment by hoodmane** [comment]
Yeah we can't turn off dynamic linking. Of course you're free to modify the build system to use static linking and threads if you can figure out how but we won't work on it. We aren't far off from latest Emscripten though and probably there are no major changes needed to move up to tip of tree see #2827 which moves to latest stable: there are issues with opencv and xgboost but nothing else.

**Comment by allsey87** [comment]
> Yeah we can't turn off dynamic linking. Of course you're free to modify the build system to use static linking and threads if you can figure out how but we won't work on it.

Having gone through the code in this project and Emscripten over the past couple of days, I definitely see where you are coming from. I will close this issue since it seems like dynamic linking and threads could well be usable together as of the 0.21.0 release.
