### ISSUE TITLE
pyodide.mjs missing from jsdelivr cdn?

### ISSUE THREAD

**Issue by joemarshall** [pyodide/pyodide#2846]
I might be being stupid here, but I can't get the mjs to download from the main pyodide jsdelivr even for recent versions? 

It works on the old cdn (e.g. https://pyodide-cdn2.iodide.io/v0.20.0/full/pyodide.mjs ) but I can't get it to work otherwise.

I can obviously host it myself, but I'd rather not. Is there something I need to do to point this at to make it work with jsdelivr?

**Comment by rth** [comment]
We probably need to add it to the list of whitelisted extensions served by jsdelivr, I'll ask them if it can be added.

**Comment by rth** [comment]
@MartinKolarik Could it be possible to whitelist the .mjs extension for the pyodide CDN endpoint in JsDelivr?

**Comment by joemarshall** [comment]
Brilliant, thanks ever so much.
