### ISSUE TITLE
The docs about using pyodide on node.js are wrong

### ISSUE THREAD

**Issue by antocuni** [pyodide/pyodide#2849]
## 📚 Documentation

In particular, I'm referring to these instructions: https://pyodide.org/en/stable/usage/index.html#node-js 

To be honest, I don't know whether they are actually wrong or just unclear, but from the point of view of someone with Python experience but 0 knowledge of the JS world/tools, I didn't manage to run pyodide under node.

The doc says to `npm install pyodide`:
```
homer tmp $ mkdir /tmp/pyodide-experiment
homer tmp $ cd /tmp/pyodide-experiment/
homer pyodide-experiment $ npm install pyodide
npm WARN saveError ENOENT: no such file or directory, open '/tmp/pyodide-experiment/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/pyodide-experiment/package.json'
npm WARN pyodide-experiment No description
npm WARN pyodide-experiment No repository field.
npm WARN pyodide-experiment No README data
npm WARN pyodide-experiment No license field.

+ pyodide@0.20.0
added 6 packages from 5 contributors and audited 6 packages in 2.928s
found 0 vulnerabilities
```

Then it says "Download and extract Pyodide packages from [GitHub releases](https://github.com/pyodide/pyodide/releases)", but it doesn't specify *where* to download. I assume it's in the current directory?

```
homer pyodide-experiment $ wget -q https://github.com/pyodide/pyodide/releases/download/0.20.0/pyodide-build-0.20.0.tar.bz2
homer pyodide-experiment $ tar xf pyodide-build-0.20.0.tar.bz2 
homer pyodide-experiment $ ls -ld pyodide
drwxr-xr-x 3 antocuni antocuni 12288 apr 10 00:10 pyodide/
```

Then I tried to copy&paste the example inside a REPL:
```
homer pyodide-experiment $ node --experimental-repl-await
Welcome to Node.js v12.18.1.
Type ".help" for more information.
> let pyodide_pkg = await import("pyodide/pyodide.js");
(node:1035940) ExperimentalWarning: The ESM module loader is experimental.
Uncaught:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/pyodide-experiment/node_modules/pyodide/pyodide.js' imported from /tmp/pyodide-experiment/repl
    at finalizeResolution (internal/modules/esm/resolve.js:284:11)
    at packageResolve (internal/modules/esm/resolve.js:615:14)
    at moduleResolve (internal/modules/esm/resolve.js:662:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:755:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at Loader.import (internal/modules/esm/loader.js:178:28)
    at importModuleDynamically (repl.js:373:45)
    at importModuleDynamicallyWrapper (internal/vm/module.js:432:21)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:37:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Then I tried to move the `pyodide` directory which was in the tarball inside `node_modules/pyodide`, but no luck:

```
homer pyodide-experiment $ mv pyodide node_modules/pyodide/
homer pyodide-experiment $ node --experimental-repl-await
> let pyodide_pkg = await import("pyodide/pyodide.js");
[...]
  code: 'ERR_MODULE_NOT_FOUND'
```

Then I tried to move the *content* of the pyodide directory into `node_modules/pyodide`:
```
homer pyodide-experiment $ mv node_modules/pyodide/pyodide/* node_modules/pyodide/
homer pyodide-experiment $ node --experimental-repl-await
Welcome to Node.js v12.18.1.
Type ".help" for more information.
> let pyodide_pkg = await import("pyodide/pyodide.js");
(node:1036517) ExperimentalWarning: The ESM module loader is experimental.
undefined
```

PROGRESS! But then it fails shortly after:
```
> let pyodide = await pyodide_pkg.loadPyodide();
Uncaught TypeError: pyodide_pkg.loadPyodide is not a function
    at repl:1:50
> pyodide_pkg
[Module] {  }
```

Then I gave up.

**Comment by antocuni** [comment]
Still doesn't work:
```
homer x $ npm install pyodide
npm WARN saveError ENOENT: no such file or directory, open '/tmp/pyodide-experiment/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/tmp/pyodide-experiment/package.json'
npm WARN pyodide-experiment No description
npm WARN pyodide-experiment No repository field.
npm WARN pyodide-experiment No README data
npm WARN pyodide-experiment No license field.

+ pyodide@0.20.0
updated 1 package and audited 9 packages in 1.248s
found 0 vulnerabilities

homer x $ node
Welcome to Node.js v12.18.1.
Type ".help" for more information.
> const { loadPyodide } = require("pyodide")//
Uncaught Error: Cannot find module 'pyodide'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
> 
```

**Comment by hoodmane** [comment]
Ah yes okay. We have made improvements to this in the alpha Pyodide. Try `npm i pyodide@next` and **then** it should work to import it. But also you need a newer version of node than v12. It would be best to use latest stable node v18, though both v14 and v16 can work with some adjustments.

**Comment by hoodmane** [comment]
I guess we really should have made a v0.20.1 release with the node fixes. We released 0.20.1a1 but never actually released `0.20.1` which would fix node installation.

**Comment by antocuni** [comment]
Ah ok, I see.
I will try to make a PR which improves the docs with these info, thank you

Il gio 7 lug 2022, 20:52 Hood Chatham ***@***.***> ha scritto:

**Comment by hoodmane** [comment]
A bit more information:
1. To use Pyodide with node versions 14 or 16, you need to also install node-fetch e.g. `npm i node-fetch`
2. To use Pyodide with node version 14 you need to pass `--experimental-wasm-bigint`. This flag is not documented in `node --help`. Also, if you pass `--experimental-wasm-bigint` to node >14 it is an error.

**Comment by rth** [comment]
Yes, the documentation clearly needs updating there, thanks! Besides the link you mentioned another place that is currently outdated is https://github.com/pyodide/pyodide/tree/main/src/js readme which is what gets uploaded to npm.

**Comment by hoodmane** [comment]
Currently we upload from dist so that README isn't ending up on npm anymore. If we want it included we should copy it into dist before the node deploy and also add it to the package.json files list:
https://github.com/pyodide/pyodide/blob/c05b76273b76be18f9ed5745e2ff06e9dfdc4135/src/js/package.json#L59

**Comment by rth** [comment]
Opened https://github.com/pyodide/pyodide/issues/2855 about that.
