### ISSUE TITLE
Wrong folder specified in Building Custom Package instructions

### ISSUE THREAD

**Issue by viblo** [pyodide/pyodide#2853]
## 📚 Documentation

Was trying to build a custom package (pymunk) following the guide at https://pyodide.org/en/latest/development/new-packages.html

Under https://pyodide.org/en/latest/development/new-packages.html#building-the-package-and-investigating-issues the text says you should run `pyodide_build buildall` from the `packages/<package-name>` folder. However, when I did so I got an error about meta.yml not found. Instead I think it should be run from the src folder, just as the other commands. When I did so everything worked as expected.

**Comment by hoodmane** [comment]
Presumably at some point it used to say to use `buildpkg` there instead of `buildall`.

**Comment by viblo** [comment]
Ill make a PR, just wanted to verify that I understood it correctly first. Today is the first time Ive tried to do anything with Pyodide :)
