### ISSUE TITLE
TST Run only one test runtime env at a time

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2876]
Currently, we select the test runtime environment via the pytest `-k` flag, with by default all runtime environments being run. We probably never want to run in all runtimes with a single command.

I think it would be better to add a pytest custom argument, `--runtime` (default to node) with the following options,
 - node
 - firefox
 - chrome
 - safari (later)
 - host # skip all selenium fixtures

**Comment by jobovy** [comment]
When I've been working on things like #2865, I found it useful to be able to just run all the tests for a given package before pushing, to make sure that all tests pass in all runtime environments. And when people eventually use the test runner to test how their own packages run in `pyodide`, easily running tests under all runtimes might also be useful? So perhaps having an option `--runtime=all` or allow, for example, `--runtime=node,firefox,chrome` would be good?

**Comment by ryanking13** [comment]
Done in https://github.com/pyodide/pytest-pyodide/pull/9
