### ISSUE TITLE
A single Pyodide CLI entry-point

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2879]
So currently we have the `pyodide` CLI entry point (defined in pyodide-build)  and the `pyodide-build` entry point (also defined in pyodide-build). I think ideally we want a single `pyodide` CLI entry point with multiple subcommands (possibly nested). 

We don't need to fix this now (related to https://github.com/pyodide/pyodide/issues/2741), but IMO before the 0.21 release,
 - we need to have a clear vision of how this is going to evolve and which CLI we are going to keep in the end
 - where this main CLI entrypoint needs to be defined. The problem of defining the main `pyodide` entry point in `pyodide-build` means that we can't use it for other things (e.g. testing). So maybe it would be better to have a standalone `pyodide-cli` package defining the entry point (outside of the mono-repo, and pyodide-build would depend on it), and then other packages can register sub-commands there.

**Comment by ryanking13** [comment]
> I think ideally we want a single `pyodide` CLI entry point with multiple subcommands (possibly nested).

Yes, that would be ideal. Actually, #1977 was about this topic I think.

> * So maybe it would be better to have a standalone `pyodide-cli` package defining the entry point

https://github.com/ryanking13/pyodide/pull/14 is a WIP job that I am working on for #1977. It adds a `pyodide-cli` package which can be used for a [single entry point for Pyodide](https://github.com/ryanking13/pyodide/runs/7243933919?check_suite_focus=true#step:7:93).

> which CLI we are going to keep in the end

Basically, I think `pyodide-cli` needs to be a replacement for `make` and `pyodide-build`. So in the end, `pyodide-build` CLI can be removed IMO.

**Comment by rth** [comment]
Yeah, https://github.com/pyodide/pyodide/issues/1977 is the more general discussion about this (which we don't need to address straight await). This issue is for a small subset of that (i.e. naming) that I think we should do before the current `pyodide` entry point is released in 0.21 as it will be more confusing to change an already existing command later.

> https://github.com/ryanking13/pyodide/pull/14 is a WIP job that I am working on for https://github.com/pyodide/pyodide/issues/1977.

Great, should we create a separate repo `pyodide/pyodide-cli` for it? I was thinking we could,
 1. create pyodide/pyodide-cli with the minimal package setup (not implementing all the actual commands), the `pyodide` entrypoint, and release it to PyPi via GHA.
 2. make `pyodide-build` depend on `pyodide-cli`. The way it would work is that CLI functions related to build would still be defined inside pyodide-build as for instance,
   **pyodide_build/cli.py**
   ```
   cli_commands =  ['command_1']

   def command_1(x: ...):
        ...
   ```
   but not register them with typer. Then inside pyodide-cli it would look at `pyodide_build.cli.cli_commands` and register all of the existing functions there as subcommand. Or any other plugin mechanism we could come up. That way other packages (e.g. pyodide-runner or something else in the future) would also be able to define `pyodide <something>` subcommand, without them having to be implemented in `pyodide-cli`.

WDYT? If you are OK with this I can create the  `pyodide/pyodide-cli` and let you put just the bare minimum setup from your PR there to setup the package (without all the subcommands). Then the plugin system could be implemented in follow up PRs.

**Comment by ryanking13** [comment]
> Great, should we create a separate repo `pyodide/pyodide-cli` for it?

I think it is not ready to be developed in a separate repository yet. It is highly intertwined with the Pyodide repository and I don't think I can unravel it in the near future.

> I think we should do before the current `pyodide` entry point is released in 0.21

Yeah, if we decided to use the name `pyodide` for the future CLI entry point, we'll need to rename the out-of-tree build entry point before releasing 0.21.0

**Comment by bollwyvl** [comment]
It's always worth considering bog-standard `entry_points`, either by reading the `console_scripts` group or defining a custom one, e.g. `pyodide.subcommand.v1`. Using this API internally is a great way to make sure that others can build on top of it without resorting to forks and hacks.

**Comment by rth** [comment]
Thanks, good point! entry_points is indeed probably the technical solution we are looking for. 

What I wanted to discuss in this issue is not so much the implementation but rather what the public CLI API should look like (and we need to decide this before doing anything about https://github.com/pyodide/pyodide/pull/2896). How we can achieve that is a later discussion.

For the public CLI API I was thinking there could be two possibilities.

### Option I
Each package can register a subcommand group (similarly to what jupyter does). So we would have for instance the `pyodide build` subcommand registered by pyodide-build which could have following sub-sub command (feel free to suggest better names)
 1. For out of tree builds I agree with @jobovy in https://github.com/pyodide/pyodide/pull/2896#issuecomment-1192735151 that it is likely to become the main way users interact with pyodide for building packages (or at least I hope it would). So maybe,
     - 1a: `pyodide build wheel <path>`
     
 2. For building the dependency graph current equivalent of buildall,
     - 2a. `pyodide build graph --packages <list of packages>`
     - 2b. `pyodide build tree --packages <list of packages>`. Though technically it's a graph, not a tree, as there is no single root package.
 4. Do we actually need a public equivalent `buildpkg`? This could be very well covered by a `--no-deps` option in the above command and is unrelated to the fact that we may have private commands to do this.
 
Similarly, we could have for instance `pyoodide <group-name>` defined in other packages (e.g. `pyodide pack`, `pyodide test`, etc)

#### Advantages

 - It's clear what package needs to be installed to get a given CLI endpoint.
 - Makes it easier to document since each subcommand group can be documented separately

#### Limitations
 - This forces one to have a package per subcommand group which is not always convenient. For instance, given Hood's latest exploratory work something like `pyodide venv` to create a separate venv for Pyodide in Node likely would be  nice. We are not going to create a package just for this functionality.  

## Option II

A package can register subcommand or subcommand groups without limitations or specific rules.

1. For out-of-tree builds, the above-proposed options are still valid, but we can add,
    - 1.b `pyodide build <package>`  if we want to make it easier to use. There could be some confusion with pyodide-build there, but I think it would go await once we deprecate the latter.
2. For in-tree buildall, in addition to the above option one could haven
    - 2.c `pyodide build-graph --packages`
    - 2.d `pyodide build-deps --packages`

#### Advantages

- Adds more flexibility for names

#### Limitations

- Can be a bit confusing which package needs to be installed to get which endpoint.


In any case for this release, the only thing we need to decide on is the general API mechanism (the option I or II or something else) + the name for the out of tree builds related to it https://github.com/pyodide/pyodide/pull/2896

Personally, I think I would be +1 for option II:  1b .

WDYT?

**Comment by hoodmane** [comment]
I think your II 1b sounds good. Maybe the idea is that we would have a separate PyPI package for the cli and then it could install what it needs on demand. For instance a `venv` command would have mostly node dependencies. Not sure if it makes sense to have a PyPI package that actually is a node package...

**Comment by ryanking13** [comment]
I'm also in favor of II 1b, and I like the idea of using `entry_points` of @bollwyvl.
