### ISSUE TITLE
Release 0.21

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2881]
I went through issues and tagged things for the 0.21 release https://github.com/pyodide/pyodide/milestone/11 

Mostly naming related subjects need to be discussed/addressed before the release IMO, since once we release they will be harder to change.

**Comment by hoodmane** [comment]
Are there any remaining blockers for this @rth @ryanking13 ?

**Comment by ryanking13** [comment]
I think #2893 was the last blocker for this.

**Comment by hoodmane** [comment]
Thanks guys! =)

**Comment by rth** [comment]
Thanks for making the release process better! It was definitely smoother than before (though I arrived towards the end for this one).

BTW the pre-built docker deployment failed again https://github.com/pyodide/pyodide/runs/7749123829 sight. I'm looking forward to dropping that once out-of-tree builds are a bit more used.

**Comment by ryanking13** [comment]
> BTW the pre-built docker deployment failed again https://github.com/pyodide/pyodide/runs/7749123829 sight. I'm looking forward to dropping that once out-of-tree builds are a bit more used.

Yes, pre built docker image is not very useful so I'm +1 for replacing it with out-of-tree build.
