### ISSUE TITLE
Problems evaluating code in console with nested brackets

### ISSUE THREAD

**Issue by wch** [pyodide/pyodide#2891]
## 🐛 Bug

Using the pyodide web console at https://pyodide.org/en/stable/console.html, evaluating this code results in odd behavior. It seems to think there's more input after `x`, until I interrupt it:

```py
x = [[[1]]]
x
```
<img width="316" alt="image" src="https://user-images.githubusercontent.com/86978/179804707-8f44993b-4ce5-4801-a134-c444e38165c1.png">

After I give it an interrupt and then type `x` again, it just prints out a single square bracket.

It correctly reports the object is a list and I can index into it, so I think Pyodide has the correct value internally. The result is not always printed correctly, though.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/86978/179805095-36043a81-e033-4473-a50a-6a5d95e5ed70.png">

This is with the current version of Pyodide deployed to the web console.

**Comment by ryanking13** [comment]
Thanks for the report @wch. I think this is fixed with https://github.com/pyodide/pyodide/pull/2517. You can check it in the latest console: https://pyodide.org/en/latest/console.html

Closing as resolved. Don't hesitate to reopen if you still experience the same behavior.

**Comment by wch** [comment]
Ah, thanks for the link to the latest console.

FWIW, I tried a similar pattern in the latest, and with four brackets it starts to have errors:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/86978/179869280-9eb69ac2-deec-406a-9236-0c2340d79c62.png">

**Comment by ryanking13** [comment]
Oops, yes... it looks like the double bracket is still not escaped correctly.

**Comment by ryanking13** [comment]
#2919 will fix this bug, thanks again for reporting this @wch!
