### ISSUE TITLE
https://pyodide.org/en/latest/console.html doesn't show latest `main` version

### ISSUE THREAD

**Issue by jobovy** [pyodide/pyodide#2911]
## 🐛 Bug

The https://pyodide.org/en/latest/console.html console is stuck at `v0.21.0a3`. I believe this is because the version wasn't bumped to the next 'dev' version after the `v0.21.0a3` release, so somebody probably needs to run
```
./tools/bump_version.py --new-version 0.21.0.dev0

```
Without `dev` in the version, the documentation's console uses the release:
https://github.com/pyodide/pyodide/blob/7231cab3ffc83f6221fafb7458f9b223d2a7c759/docs/conf.py#L20-L23

### To Reproduce

Go to https://pyodide.org/en/latest/console.html and load a package added since v0.21.0a3, e.g., `import rebound`

**Comment by ryanking13** [comment]
Thanks for the report @jobovy. Probably we should use `READTHEDOCS_VERSION` to check if we are building for a `latest` version.

**Comment by jobovy** [comment]
Thanks, it's working again now!
