### ISSUE TITLE
GitHub Sponsorship

### ISSUE THREAD

**Issue by samuelcolvin** [pyodide/pyodide#2917]
Would pyodide consider enabling github sponsorship?

I'd be keen to sponsor but to be totally honest I can't be bothered with the faff of signing up for Open Collective.

I suspect many others are in the same boat.

**Comment by rth** [comment]
Thanks for asking (and for your work on Pydantic)!

It's actually enabled https://github.com/sponsors/pyodide we just need to document it better. The funds end up in the Open Collective Pyodide account either way.

**Comment by samuelcolvin** [comment]
Done.
