### ISSUE TITLE
python-magic

### ISSUE THREAD

**Issue by eagleoflqj** [pyodide/pyodide#2922]
## 🐍 Package Request

- Package Name and Version : python-magic 0.4.27
- Package URL : https://github.com/ahupp/python-magic
- Package Dependencies that needs to be resolved first: libmagic

It's more of a question than a package request. This package needs a library `libmagic.so` and a binary database file `magic.mgc`. I've managed to build both of them, but I don't know how to put `magic.mgc` into a proper location.
`libmagic.so` hard-codes search paths of `magic.mgc`, but it can be patched. So where to put `magic.mgc` is flexible. I hope it can be bound with `python-magic` so that it can be loaded on demand.

**Comment by ryanking13** [comment]
> but I don't know how to put `magic.mgc` into a proper location.

If `magic.mgc` is used by libmagic.so, I think you can add it to the same location of libmagic.so. We currently install shared libraries to `/usr/lib` so you can load it from there.
