### ISSUE TITLE
'Future' object has no attribute 'then'

### ISSUE THREAD

**Issue by karray** [pyodide/pyodide#2923]
## 🐛 Bug

If I understand correctly, starting with version 0.17, Pyodide integrates the implementation of `await` for JsProxy. So when JS returns a `Promise`, it converts it to `Future` in Python, which allows us to use `await`.

Hoverer, the `Future` object has no attribute `then`, so it is no longer possible to build `then`/`catch` chains like in older versions.

### To Reproduce

```python
import js
js.fetch('http://karay.me/truepyxel/test.json').then(lambda resp: resp.json()).then(lambda data: data.msg).catch(lambda err: 'there were error: '+err.message)
```

### Environment

- Pyodide Version: 0.20
- Browser version: 103.0.5060.134

**Comment by hoodmane** [comment]
Yes we should add `then`, `catch`, and `finally_` methods to the `Future`.
