### ISSUE TITLE
[Discussion] Changing the default behavior of loading unvendored stdlib

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2940]
## Proposed refactoring or deprecation

- Related: #1542

We unvendors some stdlib packages in order to reduce the size of the main module.

- distutils
- tests
- ssl
- lzma (#2939)
- (maybe more in the future, e.g. sqlite3, unicodedata, ..., #1826)

The `pyodide.loadPyodide` API accepts `fullstdlib` parameter, which is currently true in default. What `fullstdlib` currently does is [load distutils package if true](https://github.com/pyodide/pyodide/blob/14708295cd1d2a38235e2dd3727ed7760e29eaa0/src/js/pyodide.ts#L319-L321). It does not affect loading other unvendored stdlibs like ssl, which I think is a bit confusing for users.

IMO not loading ssl and some other unvendored stdlibs are reasonable since the sizes of those packages are quite big.

```
960K    distutils.tar
840K    ssl-1.0.0.zip
```

So I think it would be great to
1. Change the default value of fullstdlib to “False”.
2. If fullstdlib is True, load all unvendored packages including distutils, ssl, lzma (except for `test` which is too big (~22MB) and mostly not used by users).
3. Add unvendored stdlibs to “always packages” when building.

WDYT?

**Comment by rth** [comment]
We should discuss this at https://discuss.python.org/c/webassembly/28. I wonder how scalable our current approach is and whether it wouldn't break people's assumptions about what the stdlib should contain (particularly now that Wasm is an officially supported CPython target).

**Comment by ryanking13** [comment]
> We should discuss this at https://discuss.python.org/c/webassembly/28. I wonder how scalable our current approach is and whether it wouldn't break people's assumptions about what the stdlib should contain (particularly now that Wasm is an officially supported CPython target).

Yes, I think you are right. Actually, I found that you have already opened a discussion last year about this: https://discuss.python.org/t/minifying-the-stdlib-in-pyodide/8414/6.

**Comment by ryanking13** [comment]
Opened a discussion here: https://discuss.python.org/t/unvendoring-some-of-stdlib-modules/18076

**Comment by ryanking13** [comment]
Back in this topic, my opinion is that we can start with not loading distutils by default (i.e. setting default value of fullstdlib to false), while unvendoring other packages can be discussed case by case later.

**Comment by rth** [comment]
Yes, agreed. It was good to get feedback from CPython devs. It sounded like there is no strong opposition to this idea but I agree that we should be restrained about the number of stdlib modules we unvendor otherwise user experience is going to be worse when installing dependencies.
