### ISSUE TITLE
Wrong Emscripten Version at Change Log 0.21.0

### ISSUE THREAD

**Issue by ymd-h** [pyodide/pyodide#2955]
## 📚 Documentation

Congratulations on v0.21.0 release!
This release is very helpful.

The [change log for version 0.21.0](https://pyodide.org/en/stable/project/changelog.html#version-0-21-0
) says,
> Emscripten was updated to Version 3.1.13

but perhaps Emscripetn 3.1.14 is used?
https://github.com/pyodide/pyodide/blob/0.21.0/Makefile.envs#L4

Another statement in [the blog post](https://blog.pyodide.org/posts/0.21-release/) also indicates using Emscripten 3.1.14.
> We have also updated micropip to be able to load binary wheels (which must have a filename ending in `-cp310-cp310-emscripten_3_1_14_wasm32.whl`)

It seems that [this PR](https://github.com/pyodide/pyodide/pull/2775) is overlooked.

You discussed ABI compatibility of Emscripten at [another issue](https://github.com/pyodide/pyodide/issues/2951), so this confusion might affect custom package builders.

**Comment by rth** [comment]
Good, point thanks! Would you be interested in opening a MR to fix it?

**Comment by ymd-h** [comment]
@rth 
Thank you for your quick feedback!

I made PR #2956

**Comment by hoodmane** [comment]
Closed by #2956. Thanks @ymd-h!
