### ISSUE TITLE
Safari 14 not working

### ISSUE THREAD

**Issue by alexmojaki** [pyodide/pyodide#2981]
## 🐛 Bug

When I open https://pyodide.org/en/stable/console.html in Safari 14.1 in Browserstack, it fails to load, and the console says `ReferenceError: Can't find variable: BigInt64Array`.

Based on https://pyodide.org/en/stable/usage/index.html, it seems Safari 14 is supposed to be supported.

I'm guessing this is related to https://github.com/pyodide/pyodide/pull/2643. It's not entirely clear, but it looks like continuing to support Safari 14 was the intention and the expected outcome.

**Comment by hoodmane** [comment]
I think we have to add flags `-sPOLYFILL -sMIN_SUPPORTED_SAFARI_VERSION=14000`.

**Comment by hoodmane** [comment]
It looks like the version of the emscripten patch we backported doesn't look at `POLYFILL` but the version that actually landed
https://github.com/emscripten-core/emscripten/pull/17103/files
does care about it.
