### ISSUE TITLE
Add support for passing PEP 517 config settings with pyodide build

### ISSUE THREAD

**Issue by ethanhs** [pyodide/pyodide#2985]
## 🚀 Feature

`pyodide build` currently relies on `pyprojectbuild`, which supports passing additional build time arguments to the isolated build via `--config-settings=...`. I would like to use these config settings for building a package for pyodide.

### Motivation

Currently there is no way (as far as I am aware) to pass build information to the isolated build that happens with PEP 517 with `pyodide build`. I currently need to fork the package I want to build to automatically build wheels. This will also generally help in enabling greater customization of the build, which will without be useful for packaging existing projects for WASM.

### Pitch

Add support for passing through a `--config-settings` flag to `pyprojectbuild`

### Alternatives

n/a

### Additional context

See the pypa/build docs about `--config-settings`: https://pypa-build.readthedocs.io/en/stable/#python--m-build---config-setting

PEP 517 config_settings: https://peps.python.org/pep-0517/#config-settings

**Comment by ryanking13** [comment]
I think you can use `build/backend-flags` flags.

For example, [numpy's meta.yaml file](https://github.com/pyodide/pyodide/blob/b485100b42a82878bb39d04ffa44675c93a19632/packages/numpy/meta.yaml#L15) has:

```yaml
build:
  backend-flags: --disable-optimization
```

**Comment by ethanhs** [comment]
Hm odd, I initially was confused by backend-flags not using `--` as a prefix, but I got that sorted. When I try to pass `--build-option` it does not work but passing `--global-option` does! Thanks for the help!
