### ISSUE TITLE
`pywasmcross` does not proxy `strip`

### ISSUE THREAD

**Issue by agoose77** [pyodide/pyodide#2991]
## 🐛 Bug

Calls to the `strip` executable invoke the GNU implementation rather than `emstrip`

## Proposed Fix

Shim `strip` in addition to `c++` etc.

### Environment

- Pyodide Version: 0.21.0
- Browser version: NA
- Any other relevant information:

**Comment by hoodmane** [comment]
This is probably a reasonable idea. Could you provide a bit more information on what you were doing when this problem came up?
