### ISSUE TITLE
Bug: sqlite3 does not depend on nltk and regex

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3001]
In 0.21.1 deployment,  when running `import sqlite3` in the REPL it would load  nltk and regex which is wrong.  

It looks like for sqlite3 `depends` and `imports` fields are switched, between the [repodata.json](https://cdn.jsdelivr.net/pyodide/v0.21.1/full/repodata.json) and the [meta.yaml](https://github.com/pyodide/pyodide/blob/main/packages/nltk/meta.yaml)
![image](https://user-images.githubusercontent.com/630936/185934857-c1c910ce-15a4-4426-982d-cb5de8582f87.png)

but then other packages seem to be fine.

This is serious enough to probably warrant a 0.21.2 release, as it adds an extra MB for apps that load sqlite3.

Version which reproduces: 0.20.0, 0.21.1 (and probably those in between)
Version which don't reproduce: dev

cc @ryanking13

**Comment by rth** [comment]
No actually the meta.yaml was just wrong previously https://github.com/pyodide/pyodide/blob/0.21.1/packages/nltk/meta.yaml

**Comment by hoodmane** [comment]
Looks like I added it in this commit
https://github.com/hoodmane/pyodide/commit/24e5f413c7a6125fbb3c770e1be3d76beb06120f
as part of #1637. Naturally I gave no additional explanation and as part of such a large pr it got no attention.

**Comment by rth** [comment]
Less critical but sharedlib-test import is also wrong
![image](https://user-images.githubusercontent.com/630936/185938370-48ef16b3-0488-4c90-999d-5b56d7e46ee6.png)

it's not specified in meta.yaml, so probably something wrong with the code logic.

It might be good to add a validation to the dependency tree that,
 1. import fields are valid imports (e.g. cannot contain "-")
 2. that they are unique (e.g. `sqlite3` import cannot be present in two packages).

**Comment by hoodmane** [comment]
Also mkpkg should substitute `-` for `_` in the imports field since this often is enough to give a correct result.

**Comment by rth** [comment]
> Looks like I added it in this commit

and I missed it during review. Well it's not that critical in a sense it only happens if users `import sqlite3` in runPythonAsync, and they might not realize it's happening. But since it's a core package and it downloads 1MB extra in this case, it might still be nice to fix.

BTW, I run into this while testing sqlite3 unvendoring and being on the wrong version. So the outcome was rather unexpected :)

**Comment by ryanking13** [comment]
We should really add a new key `top-level` in meta.yaml or something similar and should not use `test/imports` for calculating the top level import name. It's so easy to make a mistake...

**Comment by rth** [comment]
Closing as fixed.
