### ISSUE TITLE
Out-of-tree builds against the GSL

### ISSUE THREAD

**Issue by jobovy** [pyodide/pyodide#3002]
## 🚀 Feature

It would be great to be able to do out-of-tree builds of packages that depend on libraries such as the GSL, which are currently not included in the `xbuildenv`:

https://github.com/pyodide/pyodide/blob/fdf39f89efe0308ee091e884c151ce57fbe3168f/pyodide-build/pyodide_build/create_xbuildenv.py#L59-L64

### Motivation

I'm trying to setup an out-of-tree CI build of the latest version of `galpy` (see #2676), but it requires the GSL to build and this does not appear to be included in the `xbuildenv`. So the CI job fails:

https://github.com/jobovy/galpy/runs/7958109347?check_suite_focus=true#step:6:546

### Pitch

Perhaps it makes sense to have two out-of-tree `xbuildenv` environments: a small one like the current one and one that includes the full `WASM_LIBRARY_DIR` for people who need additional libraries. 180 MB of `WASM_LIBRARY_DIR` is not small, but easily cached in CI jobs.

### Alternatives

Just add the GSL to the `xbuildenv`.

**Comment by hoodmane** [comment]
This sounds reasonable.

**Comment by hoodmane** [comment]
Another possibility is that we could provide some way to build extra libraries in the xbuild environment using the Pyodide in-tree build system. That has flexibility advantages (what if your package needs some other static library we don't include?) but could be a bit complicated. Also, you may not want to build GSL in your CI all the time. Maybe it could be cached...

**Comment by jobovy** [comment]
If building those extra libraries would be fast, that would be okay. Could one imagine doing something like
```
pyodide build gsl
pyodide build my_package
```
? Maybe the first command would need some sort of ``--shared`` flag or something to indicate that it should install in the `xbuildenv`'s library directory, so the next command can find it to link against. Then presumably the result of the GSL built could be cached easily?

**Comment by hoodmane** [comment]
I think for now you could do this in an ad hoc manner like:
```sh
# install Emscripten
python -m pyodide_build install_xbuild_env
source path/to/emsdk/emsdk_env.sh

# Build gsl
wget https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz
unpack https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz into gsl
cd gsl
emconfigure ./configure \
    CFLAGS="-fPIC" \
    --prefix=`pwd`/xbuildenv/pyodide-root/packages/.libs/ \
    --disable-dependency-tracking \
    --disable-shared
emmake make -j 3
emmake make install

# Build galpy
cd ..
pyodide build
```
This isn't great because you have to know the path into the build environment, but it can work while we think about how we should go forward with this.

**Comment by hoodmane** [comment]
Actually that won't quite work.

**Comment by hoodmane** [comment]
I think this would actually work:
```
# install Emscripten
python -m pyodide_build install_xbuild_env
source path/to/emsdk/emsdk_env.sh

# Set up libs dir and pkg config
mkdir .libs
export PKG_CONFIG_PATH=`pwd`/.libs/lib/pkgconfig

# Build gsl
wget https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz
unpack https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz into gsl
cd gsl
emconfigure ./configure \
    CFLAGS="-fPIC" \
    --prefix=`pwd`/.libs/ \
    --disable-dependency-tracking \
    --disable-shared
emmake make -j 3
emmake make install

# Build galpy
cd ..
CFLAGS=`pkg-config --cflags-only-I --dont-define-prefix gsl` \
LDFLAGS=`LIBGSL_LIBRARY_PATH=$(pkg-config --libs-only-L --dont-define-prefix gsl)` \
pyodide build
```

**Comment by jobovy** [comment]
Okay, I tried this and it seems to have built in ~3min.: https://github.com/jobovy/galpy/actions/runs/3063192094/jobs/4944996224. I'll have to take a look at the artifact later to see whether the wheel is actually correct. Thanks!

**Comment by jobovy** [comment]
Okay, I tried out the wheel by loading it in the latest REPL and as far as I can tell, it seems to work fine. The run that actually produced the artifact is here: https://github.com/jobovy/galpy/actions/runs/3063231177

For reference, this is the edited script that I used (differences: ``unpack`` doesn't seem to work on GitHub actions and it's not necessary to source the ``emsdk_env.sh`` on GHA):
```
# Set up libs dir and pkg config
mkdir .libs
export LIBDIR=`pwd`/.libs
export PKG_CONFIG_PATH=`pwd`/.libs/lib/pkgconfig

# Build gsl
wget https://ftp.gnu.org/gnu/gsl/gsl-2.7.tar.gz
tar -xvzf gsl-2.7.tar.gz
cd gsl-2.7
emconfigure ./configure \
    CFLAGS="-fPIC" \
    --prefix=$LIBDIR \
    --disable-dependency-tracking \
    --disable-shared
emmake make -j 3
emmake make install

# Build galpy
cd ..
CFLAGS=`pkg-config --cflags-only-I --dont-define-prefix gsl` \
LDFLAGS=`pkg-config --libs-only-L --dont-define-prefix gsl` \
pyodide build
```

**Comment by jobovy** [comment]
I'll close this issue, because with this code it's easy to resolve the original issue. Also, I don't think in the end it should be `pyodide`'s responsibility to compile shared libraries, much as Python/pip don't do this for you either. But maybe this should be incorporated into the docs eventually if it's relevant to other people (as I suspect it will be).

**Comment by hoodmane** [comment]
Thanks @jobovy! This was a helpful discussion. After #3109 is merged we can add a section on static libraries.
