### ISSUE TITLE
Relative URLs in pyodide.loadPackage

### ISSUE THREAD

**Issue by flange-ipb** [pyodide/pyodide#3011]
## 🐛 Bug

The documentation states that [pyodide.loadPackage](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackage) supports relative URLs. I'm trying to load an out-of-tree wheel from my local webserver, but this doesn't seem to work out well.

### To Reproduce

```js
await pyodide.loadPackage("dist/igraph-0.9.11-cp310-cp310-emscripten_3_1_14_wasm32.whl");
```
or
```js
await pyodide.loadPackage("./dist/igraph-0.9.11-cp310-cp310-emscripten_3_1_14_wasm32.whl");
```
Pyodide tries to load the wheel from `https://cdn.jsdelivr.net/pyodide/v0.21.1/full/dist/igraph-0.9.11-cp310-cp310-emscripten_3_1_14_wasm32.whl`.

### Expected behavior

Load the wheel from the relative URL.

### Environment

- Pyodide Version: 0.21.1
- Browser version: Firefox ESR 91.12.0, Chromium 104.0.5112.101
- Any other relevant information:

**Comment by hoodmane** [comment]
Looking into this. Not clear that it ever worked. I'm trying to fix our test for it first.

**Comment by hoodmane** [comment]
The problem is in this function:
https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L125

**Comment by flange-ipb** [comment]
Very good, thanks! Works as expected.
