### ISSUE TITLE
Relation between pyodide.loadPackage and micropip is not clear

### ISSUE THREAD

**Issue by viblo** [pyodide/pyodide#3033]
## 📚 Documentation

It is not clear in the documentation what is javascript and what is python. This becomes very confusing when reading about how to import a package at https://pyodide.org/en/stable/usage/loading-packages.html 

The page starts with 

> [pyodide.loadPackage](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackage) for packages built with Pyodide, or
> [micropip.install](https://pyodide.org/en/stable/usage/api/micropip-api.html#micropip.install) for pure Python packages with wheels available on PyPI or from other URLs.

Then below its a note:
> [micropip](https://pyodide.org/en/stable/usage/api/micropip-api.html#module-micropip) can also be used to load packages built in Pyodide (in which case it relies on [pyodide.loadPackage](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackage)).

This becomes very confusing. The pyodide referenced here is a javascript package, while micropip is used from within python. If you are already in python repl you should use micropip to install both pure packages and non-pure wheels (as long as they target the right env). It gets extra confusing as its possible to `import pyodide` from the repl, but the imported module does not contain loadPackage.

**Comment by hoodmane** [comment]
Yep. For the record, you can import `loadPackage` via `from pyodide_js import loadPackage`. From JavaScript you can access the Python package as `pyodide.pyodide_py`. We've never figured out how to describe this situation particularly clearly in the docs.

**Comment by viblo** [comment]
Thanks 👍
