### ISSUE TITLE
Onnxruntime support

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [pyodide/pyodide#3038]
Hi, can you please add support for onnxruntime so that we can run our onnx models into the browser ?

**Comment by rth** [comment]
There is a [ONNX Runtime Web](https://github.com/microsoft/onnxruntime/tree/main/js/web#readme) that works in the browser, and among other things supports both CPU and GPU. That's a JS library but you can call it from Python using the type translations API Pyodide provides.

Closing, unless this  answer doesn't work for you (in which case don't hesitate to comment)
