### ISSUE TITLE
Add IbisData to the package lit

### ISSUE THREAD

**Issue by venkat-sneller** [pyodide/pyodide#3041]
## 🐍 Package Request

- Package Name and Version :ibis-framework
- Package URL :https://github.com/ibis-project/ibis/releases/download/3.1.0/ibis_framework-3.1.0-py3-none-any.whl
- Package Dependencies that needs to be resolved first:https://github.com/ibis-project/ibis/blob/master/requirements.txt

**Comment by rth** [comment]
Have you tried installing it with micropip? As far as I can tell,
```py
>>> import micropip
>>> await micropip.install("ibis-framework")
>>> import ibis
>>> ibis.__version__
'3.1.0'
```
works. You don't need all of these requirements but rather specific requirements for the [backend you need](https://github.com/ibis-project/ibis/blob/master/setup.py#L88). So far I think only sqlite and possibly dask backend would work. Others would likely require modifications of client libraries to run in the browser (and it's better to open separate issues about specific DB libraries).

Closing, but please don't hesitate to comment in this issue.
