### ISSUE TITLE
Add `psutil` package

### ISSUE THREAD

**Issue by michaelweinold** [pyodide/pyodide#3056]
## 🐍 Package Request

- Package Name and Version : psutil / latest
- Package URL : https://pypi.org/project/psutil
- Package Dependencies that needs to be resolved first: N/A (as per `conda-tree depends -t psutil`)

**Comment by tiran** [comment]
`psutil` won't be very useful on Pyodide. Emscripten platform does not support any process, resource, signals, or similar POSIX APIs. Browsers are also sandboxed. You won't be able to see or modify any processes on the host system.
