### ISSUE TITLE
Unvendor the matplotlib backends for WASM

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3058]
We currently have two matplotlib backends in the repo [here](https://github.com/pyodide/pyodide/tree/main/packages/matplotlib/src),
 - [`wasm` backend](https://github.com/pyodide/pyodide/blob/main/packages/matplotlib/src/wasm_backend.py) which from what I understand allows rendering Agg buffer (as static images) into an HTML canvas
 - [an interactive HTML5 canvas backend](https://github.com/pyodide/pyodide/blob/main/packages/matplotlib/src/html5_canvas_backend.py) developed by @madhur-tandon that was described in [this blog post](https://blog.pyodide.org/posts/canvas-renderer-matplotlib-in-pyodide/)

This is a bit related to what is done in https://github.com/ipython/matplotlib-inline for Ipython and Jupyter

Right now these backends are not very well documented or discoverable.

If there are no objections, I would propose moving them outside to a separate repo in the Pyodide org, so they are more easily discoverable and someone from the matplotlib team would be more aware that they exist cc @timhoffm Also this way they could be reused in other Python wasm distributions (e.g. emscripten-forge)

cc @martinRenou

xref: https://github.com/pyodide/pyodide/issues/2014

**Comment by hoodmane** [comment]
I'm happy to get this out of here. It's a bit far outside the scope of the rest of the repository. And it's quite complex.

What I would like to see done is to have a separation between the backend and the JavaScript interface so that it could be used to render from a webworker. Then the people who load the runtime can set it up the way they want it.

**Comment by rth** [comment]
The matplotlib backend used by Pyodide is now available as a standalone repo in https://github.com/pyodide/matplotlib-pyodide Though we still need to move tests and benchmarks there.

**Comment by martinRenou** [comment]
Super nice! Thanks for doing this :)
