### ISSUE TITLE
BUG: open_url works for binary files in the main thread

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3062]
I was talking with @DerThorsten about the fact that they are using  `XMLHttpRequest` to do sync requests for binary files in a webworker in https://github.com/emscripten-forge/requests-wasm-polyfill.

I tried it out in the main tread (essentially what we do in `pyodide.http.open_url`) and was surprised to see that it worked on the main thread for binary files,
```py
>>> from pyodide.http import open_url
>>> res = open_url("https://numpy.org/images/content_images/arlib/arrow.png")
>>> res
<_io.StringIO object at 0xf95a30>
>>> res.read()
'�PNG\r\n\x1a\n\x00...'
```
Both in Firefox 103.0.2 and Chrome 103.0.5060.114

So it's not very clear to me what is happening. I'm pretty sure it didn't work before, maybe there were some changes in the browser implementations?

While downloading large binary files in the main thread is certainly not a great idea, it would unblock https://github.com/pyodide/pyodide/issues/140 in a very easy fix, while we don't have something better.

**Comment by ryanking13** [comment]
It sounds very interesting. Although synchronous request in `XMLHttpRequest` is deprecated, I don't think it would be removed within a short period. So I think it would be fine to use `XMLHttpRequest` more.

**Comment by hoodmane** [comment]
> So it's not very clear to me what is happening. I'm pretty sure it didn't work before, maybe there were some changes in the browser implementations?

It's downloading it as a string. If the binary file is not valid utf8, changes will be made to the file. For example:
```
b'\x89P   N   G   \r  \n  \x1a\n  \x00\x00\x00' -- the correct start of a png
b'\xef\xbf\xbdP   N   G   \r  \n  \x1a\n  \x00' -- what you got
```
Notice that the single byte `\x89` is illegal utf8 (the first two bits are `10` so it claims to be a continuation byte but it is the first byte in the string). So it got transformed into the three-byte sequence `\xef\xbf\xbd` for the question mark character which is substituted for bytes that are illegal utf8.

So I am not sure that this is a good idea.

**Comment by rth** [comment]
Yes, I remember it now. You can download binary files but it errors if you try to set `responseType = "arraybuffer"` for binary data on the main thread.


@koenvo solved this with a hack using `overrideMimeType`

> This issue is solved in latest version of pyodide-http. I added an example of fetching binary data in the main thread here: [koenvo/pyodide-http@main/tests/pyscript.html](https://github.com/koenvo/pyodide-http/blob/main/tests/pyscript.html?rgh-link-date=2022-09-19T11%3A19%3A41Z) . This is solved here: [koenvo/pyodide-http@main/pyodide_http/_core.py#L47](https://github.com/koenvo/pyodide-http/blob/main/pyodide_http/_core.py?rgh-link-date=2022-09-19T11%3A19%3A41Z#L47)

Can you still retrieve the original MimeType in this case? 

> A proper way to solve fetching binary data in the main thread is by using Atomics.wait (I think). More info about this approach can be found here: https://github.com/koenvo/pyodide-http/issues/5

I don't think it's possible on the main thread unless WASM implements stack switching (or you use a webworker to fetch the data)

But yes, overall I'm all for this work being done by https://github.com/koenvo/pyodide-http, and closing this issue as answered.
