### ISSUE TITLE
Merge sharedlibrary and library meta.yaml flags

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3066]
As proposed in https://github.com/pyodide/pyodide/pull/3055#pullrequestreview-1094620159,

>  it would be better to have a single flag library: which can be static, shared, or False. Rather than two binary flags library and sharedlibrary. It's weird to have library=False for something that's a shared library.

**Comment by ryanking13** [comment]
Maybe we can rename it to `build/type` to support some special cases like unvendored cpython stdlibs, micropip, and test-only packages (fpcast-test):

- package: Normal python package
- static-library: Static library
- shared-library: Shared library
- cpython-stdlib: Unvendored cpython stdlibs
- ...
