### ISSUE TITLE
setting data to tradingview LightweightCharts js object throwing error ..

### ISSUE THREAD

**Issue by Rahulghuge94** [pyodide/pyodide#3069]
Can anyone tell me why im not able to set data to Lighteweigthchart object. it shows following error. i do tried proxy but nothing works.
![image](https://user-images.githubusercontent.com/16452687/188447691-c1270b8a-216e-4d17-b857-b5cf82321641.png)
screenshot shows the error it throwing.. it says t.Foreach is not a function.

incase required here is the link to the javascript library i'm trying to create the object from python.
https://github.com/tradingview/lightweight-charts

**Comment by ryanking13** [comment]
Could you give us a minimal reproducible code?

**Comment by Rahulghuge94** [comment]
thanks for giving reply. well the problem is solved now. i was actually try to set  wrong object. now the another problem is whenever i try to import the Lightweightcharts class from globalmodule js. it throws error. it unable to import the class/module.
but if i create the instance of that class in javascript and then import it works.
