### ISSUE TITLE
Calling `loadPyodide()` with `indexURL` results in error

### ISSUE THREAD

**Issue by wch** [pyodide/pyodide#3076]
## 🐛 Bug

When `loadPyodide()` is called with a value for `indexURL` that is not a complete URL (with a protocol), it results in an error.

I believe this was caused by #3013.

## To Reproduce

```js
await loadPyodide({ indexURL: "./" });
```

This produces this error:

```
pyodide.js:1 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at resolvePath (pyodide.js:1:7795)
    at loadPyodide (pyodide.js:1:12107)
    at async main (console.html:76:30)
```

In my particular use case, I'm not using  `"./"`, but a relative path, like `"./foo"`.

It _does_ work if you use:

```
await loadPyodide({ indexURL: "https://cdn.jsdelivr.net/pyodide/dev/full/" });
```

### Expected behavior

The docs for `indexURL` say:

> options.indexURL (string()) – The URL from which Pyodide will load the main Pyodide runtime and packages. Defaults to the url that pyodide is loaded from with the file name (pyodide.js or pyodide.mjs) removed. It is recommended that you leave this undefined, providing an incorrect value can cause broken behavior.

Based on this documentation, it's not entirely clear to me whether paths like `"./foo"` or `"/foo"` _should_ work, but I do know that they used to work.

### Environment

- Pyodide Version: 0.21.2
- Browser version: 104.0.5112.101

**Comment by hoodmane** [comment]
Thanks for the report. This was a pretty simple mistake but we need to add a test for it.
