### ISSUE TITLE
Missing source map in JavaScript package.

### ISSUE THREAD

**Issue by dlech** [pyodide/pyodide#3086]
## 🐛 Bug

When using Pyodide with Webpack + source-map-loader, I am seeing the following warning:

```
WARNING in ./node_modules/pyodide/pyodide.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/david/work/pybricks/pybricks-code/node_modules/pyodide/pyodide.mjs.map' file: Error: ENOENT: no such file or directory, open '/home/david/work/pybricks/pybricks-code/node_modules/pyodide/pyodide.mjs.map'
```

### To Reproduce

Check out this branch: https://github.com/dlech/pyodide-webpack/tree/source-map-loader

and follow the instructions in the readme.

### Expected behavior

Either the package should include the .map file or the code should not reference the .map file.

### Environment

- Pyodide Version: 0.21.2
- Browser version: N/A
- Any other relevant information:

### Additional context

The `pyodide` JavaScript only contains the following files (*.map is missing):

```
node_modules/pyodide/
├── console.html
├── distutils.tar
├── package.json
├── pyodide.asm.data
├── pyodide.asm.js
├── pyodide.asm.wasm
├── pyodide.d.ts
├── pyodide.js
├── pyodide.mjs
├── pyodide_py.tar
├── pyodide_tblib-1.7.1-py3-none-any.whl
├── README.md
└── repodata.json
```

**Comment by hoodmane** [comment]
Apparently they are included in v0.21.0 and v0.21.1 but not in v0.21.2.

**Comment by hoodmane** [comment]
Ah yes:
```
+      - run:
+          name: Remove source maps
+          command: |
+            # Source maps mess up calculateIndexURL if node is used with
+            # --enable-source-maps and are not otherwise needed. We'll keep them
+            # in the debug version.
+            rm dist/*.map
```
the source maps cause bugs when used with Jest or other packages with `--enable-source-maps` so I removed them. It's very difficult to please everyone.

**Comment by dlech** [comment]
Should we remove this line then?

https://github.com/pyodide/pyodide/blob/60714a9cf014ebf91cb9c3ac729954d26e93e523/src/js/rollup.config.js#L13

**Comment by hoodmane** [comment]
I want them for debugging purposes. I think I can fix both problems, because in node we should be able to look up the file path using `__filename` instead and hopefully source maps won't screw that up.
