### ISSUE TITLE
webpack complains about dynamic imports

### ISSUE THREAD

**Issue by dlech** [pyodide/pyodide#3087]
## 🐛 Bug

When using Pyodide with webpack I am seeing the following warnings:

```
WARNING in ./node_modules/pyodide/pyodide.mjs 231:56-67
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/pyodide/pyodide.mjs 236:10-21
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/pyodide/pyodide.mjs 243:98-140
Critical dependency: the request of a dependency is an expression
```

### To Reproduce

I haven't figured out a minimal way to reproduce this yet. 

### Expected behavior

The `pyodide` package should not trigger any webpack warnings.

### Environment

- Pyodide Version: 0.21.2
- Browser version: N/A
- Any other relevant information:

### Additional context

The relevant source code is:

https://github.com/pyodide/pyodide/blob/e2ce091b4c9953f06deca7a6c4f1b52ea716d53b/src/js/compat.ts#L177
https://github.com/pyodide/pyodide/blob/e2ce091b4c9953f06deca7a6c4f1b52ea716d53b/src/js/compat.ts#L188
https://github.com/pyodide/pyodide/blob/e2ce091b4c9953f06deca7a6c4f1b52ea716d53b/src/js/compat.ts#L216

The first of these did have `/* webpackIgnore: true */` but that was removed in #2468. I'm not sure if the comment would persist to the minified code that is distributed or not.

**Comment by hoodmane** [comment]
> I'm not sure if the comment would persist to the minified code that is distributed or not.

It does not. I looked into this but I didn't find any way to make a comment persist to the rollup output, if you can figure out how to do that it would probably be helpful.
