### ISSUE TITLE
Add a package - camelot

### ISSUE THREAD

**Issue by NehaP92** [pyodide/pyodide#3099]
Is it possible to add the camelot-py package to pyodide?

Seems like it has the pure python wheel but it still gives the "Couldn't find a pure Python 3 wheel for 'cryptography>=36.0.0'." error.
https://pypi.org/project/camelot-py/#files

**Comment by hoodmane** [comment]
Works in Pyodide >= 0.21.0:
```py
import micropip
await micropip.install("camelot-py")
```

**Comment by lukefullard** [comment]
I note that this does not work with the most recent version of camelot.
Version 0.11.0 works 
Version 1.0.0 Does not work
