### ISSUE TITLE
Strange pre-commit error

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3110]
Recently I've been getting the following error from pre-commit:
```sh
/home/hood/.cache/pre-commit/repow1xom7p_/py_env-3.10/lib/python3.10/site-packages/numpy/__init__.pyi:636: error:
Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
```
@henryiii do you have any idea why this happens or how to fix it?

**Comment by henryiii** [comment]
Looks like it's set to check in 3.7+ (or earlier) mode.

**Comment by henryiii** [comment]
Not sure where though - can check later.

**Comment by rth** [comment]
See https://github.com/python/mypy/issues/13627 there are some workaround there, and this will be fixed in the next release.

**Comment by henryiii** [comment]
Wow, yes that makes sense. So it’s tied to the patch version of python. You could specify that temporarily if you want.
