### ISSUE TITLE
Release 0.22.0a1

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3111]
I think it would be a good time to make a release after merging #3106 and #3109 so we can start using the virtual environments in CI for some packages.

**Comment by ryanking13** [comment]
Yes, it is a large feature so I'm +1 with releasing it as a 0.22.0. Since oot build and Pyodide virtual environments are mostly developed by you, I am in favor of releasing 0.22.0a1 if you think it is ready to be tested. Probably we can have a long alpha period for a bugfix.

**Comment by ryanking13** [comment]
I think it would be nice to change the out-of-tree entrypoint to use plugin interface (`pyodide-cli`) before releasing 0.22.0a1 though. There might be some minor issues in converting it to use a plugin interface which might change the CLI. (For example, we may want to reserve `pyodide build` subcommand for in-tree build #2879)

**Comment by hoodmane** [comment]
> nice to change the out-of-tree entrypoint to use plugin interface (pyodide-cli) before releasing 0.22.0a1 though

Sounds good.

> For example, we may want to reserve `pyodide build` subcommand name for in-tree build 

Well we already made a stable release with `pyodide build` as the way to build packages, so moving that would be a breaking change (though if we really wanted to it would be okay). As @jobovy pointed out this will make the most sense for the most users. A much smaller number of people are ever going to use `buildpkg` or `buildall` entry points.

**Comment by ryanking13** [comment]
> Well we already made a stable release with `pyodide build` as the way to build packages, so moving that would be a breaking change (though if we really wanted to it would be okay). As @jobovy pointed out this will make the most sense for the most users. A much smaller number of people are ever going to use `buildpkg` or `buildall` entry points.

Actually, I am +1 with `pyodide build` being a command for oot build. I just wanted to make sure that we are not going to change the name, so I can use other names in #2904

**Comment by rth** [comment]
> +1 with pyodide build being a command for oot build. I just wanted to make sure that we are not going to change the name

Yeah, from what I remember we said we are not going to change that name even after migration to pyodide-cli.

>  releasing it as a 0.22.0

Actually, yes  the changelog is rather long already so we could do this as a last Python 3.10 release before switching to 3.11. In any case though it might be good to release a 0.22.0a1 first, try it on a few projects, see if there are issues that needs fixing and once we are ready (and sure the interface is not going to change) go for 0.22.0. So maybe 0.22.0a1 now and 0.22.0 end of September? That would be almost two months between releases so not that far from our usual release cycle.

**Comment by hoodmane** [comment]
@ryanking13 do you still want to wait on releasing 0.22.0a1? If it's going to take a while to move the cli, I think we might as well proceed with a release. It's okay if going from 0.22.0a1 to 0.22.0a2 changes some stuff.

**Comment by ryanking13** [comment]
I think it is okay to make a alpha release if you want to get a fast feedback. Probably we need to fix #3113 before making a release anyway.

**Comment by hoodmane** [comment]
Yeah. The fastest way to deal with that would be to revert #3113 for now though.

**Comment by ryanking13** [comment]
Opened a PR with a fix. It worked locally to me (https://github.com/ryanking13/pyodide/actions/runs/3080795271) so I hope it work.

**Comment by alexmojaki** [comment]
It's working for me (https://github.com/alexmojaki/pyodide-worker-runner/pull/20)

**Comment by hoodmane** [comment]
Thanks @alexmojaki!
