### ISSUE TITLE
LightGBM Support Attempt

### ISSUE THREAD

**Issue by yzhliu** [pyodide/pyodide#3116]
## 🐍 Package Request

- Package Name and Version: lightgbm 3.3.2
- Package URL:
  * https://github.com/microsoft/LightGBM/tree/v3.3.2
  * https://files.pythonhosted.org/packages/8f/51/d272fa065be3be615d279be915705fa3824b86155e36c974cfb8d3ceec1e/lightgbm-3.3.2.tar.gz
- Package Dependencies that needs to be resolved first: N/A

## Attempts

I actually have done some work try to get it compiled, and it did. See https://github.com/yzhliu/pyodide/tree/lightgbm/packages/lightgbm for details. And it also imports successfully in the browser.

However when I tried to run the following script from [LightGBM tutorial](https://lightgbm.readthedocs.io/en/v3.3.2/Python-Intro.html), it runs into several “*RuntimeError: null function or function signature mismatch*” error in Chrome.

```python
import numpy as np
import lightgbm as lgb
data = np.random.rand(500, 10)  # 500 entities, each contains 10 features
label = np.random.randint(2, size=500)  # binary target
train_data = lgb.Dataset(data, label=label)
param = {'num_leaves': 31, 'objective': 'binary'}
param['metric'] = 'auc'
num_round = 10
bst = lgb.train(param, train_data, num_round)
```

### 1. Problematic support for std::function<std::vector<double>(int)> return type

It first failed at https://github.com/microsoft/LightGBM/blob/v3.3.2/src/c_api.cpp#L1110. It seems to be complaining about `std::vector<std::function<std::vector<double>(int)>>` return type. In addition, [the usage of template](https://github.com/microsoft/LightGBM/blob/v3.3.2/src/c_api.cpp#L2380) in std::function also seems to be problematic. Therefore I changed it to a class and it went through. See [the patch](https://github.com/yzhliu/pyodide/blob/lightgbm/packages/lightgbm/patches/0001-RowFunctionFromDenseMatricCB.patch) for details.

### 2. Template class and virtual method?

Then it fails at [ret→PushOneRow](https://github.com/microsoft/LightGBM/blob/v3.3.2/src/c_api.cpp#L1159). Digging deep, it is [Bin→Push](https://github.com/microsoft/LightGBM/blob/v3.3.2/include/LightGBM/feature_group.h#L211) causing the problem. I haven’t managed to resolve the issue, but it seems to me again is the [DenseBin](https://github.com/microsoft/LightGBM/blob/v3.3.2/src/io/dense_bin.hpp#L53), which is defined with template types, together with `Push` being an overridden function, that are causing the issue.

I’m seeking for suggestion whether (1) is expected, and how shall I fix (2)?

**Comment by yzhliu** [comment]
It turns out to be my environment setting issue. I used the master branch to compile lightgbm, while loaded it together with https://cdn.jsdelivr.net/pyodide/v0.21.0/full/pyodide.js. The mix-up must have caused incompatibility.

Please feel free to close the issue. Or I can keep updating in the thread for follow-up progress & questions.

**Comment by rth** [comment]
Thanks for the report and for investigating! Looking forward to having LightGBM available!
 
> Please feel free to close the issue

Maybe you can close it yourself, then re-open if needed? Because if I close it, I think you won't be able to re-open then.

**Comment by yzhliu** [comment]
> Maybe you can close it yourself, then re-open if needed? Because if I close it, I think you won't be able to re-open then.

@rth make sense. Thank you!
