### ISSUE TITLE
Pls add bcrypt package

### ISSUE THREAD

**Issue by skelsec** [pyodide/pyodide#3118]
Hello, I'm trying to use the "cryptography" package for SSH key decryption which requires the `bcrypt` module.  
You'll not believe me if I say that the latest version `4.0.0` requires: RUST. No problem, compilation works okay, runtime almost works except nothing loads after the error `bad export type for `_emscripten_get_now`: undefined`.  
Yes, the issue which is mentioned [here](https://blog.pyodide.org/posts/rust-pyo3-support-in-pyodide/)  
Not to worry, maybe the older version `3.2.2` without Rust would suffice: yeah, that one doesn't even compile because the header file which determines endianess fails as it doesn't have the definitions for webassembly.  
Please help!
## 🐍 Package Request

- Package Name and Version : bcrypt/4.0.0 (latest)
- Package URL : https://pypi.org/project/bcrypt/
- Package Dependencies that needs to be resolved first: None, only Rust

**Comment by hoodmane** [comment]
Can you basically just copy the cryptography `meta.yaml` recipe?

**Comment by skelsec** [comment]
I tried my best -which is not much when it comes to rust- and failed.

**Comment by hoodmane** [comment]
Okay well I'll try to look into this when I get a chance it's probably doable.
