### ISSUE TITLE
`ModuleNotFoundError` when python modules import packages

### ISSUE THREAD

**Issue by kolibril13** [pyodide/pyodide#3126]
## 🐛 Bug
When modules (e.g. `numpytest.py`) import other packages (e.g. `numpy` or `scipy`), Pyodide throws an ModuleNotFoundError.

### To Reproduce
This is from the [pyodide console](https://pyodide.org/en/stable/console.html):
```console
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, Sep 15 2022 23:28:12) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> filename = "numpytest.py"
code = """
print("Hello Numpy")
import numpy
print(f"{numpy.euler_gamma = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
68
>>> filename = "scipytest.py"
code = """
print("Hello Scipy")
import scipy
print(f"{scipy.pi = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
59
>>> from numpytest import *
Hello Numpy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/numpytest.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> from scipytest import *
Hello Scipy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/scipytest.py", line 3, in <module>
    import scipy
ModuleNotFoundError: No module named 'scipy'
>>> import scipy
>>> from scipytest import *
Hello Scipy
scipy.pi = 3.141592653589793
>>> 
>>> import numpy
>>> from numpytest import *
Hello Numpy
numpy.euler_gamma = 0.5772156649015329
>>> 
 
 ```

### Environment

- Pyodide Version: Latest https://pyodide.org/en/stable/console.html
- Browser version:Chrome 105.0.5195.125 (Official Build) (arm64)

### Additional context

The same problem causes a `ModuleNotFoundError` in JupyterLite https://github.com/jupyterlite/jupyterlite/issues/806.

It would be wonderful if this importing feature was possible. That would allow a whole range of already existing Jupyter notebook collections to run in JupyterLite without code adjustments.

**Comment by ryanking13** [comment]
You need to either call `await micropip.install("numpy")` in Python or `await pyodide.loadPackage("numpy")`. in JavaScript before importing numpy.

Note that in pyodide console, we inject `pyodide.loadPackage` before executing the code given by the user. But this doesn't happen when importing other files.

**Comment by kolibril13** [comment]
Hi @ryanking13, thank you for the quick reply!
I've now tried to include the await line into the module, and it gives a SyntaxError: 
```console
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, Sep 15 2022 23:28:12) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> filename = "numpytest.py"
code = """
print("Hello Numpy")
import pyodide
await micropip.install("numpy")
import numpy
print(f"{numpy.euler_gamma = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
115
>>> from numpytest import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/numpytest.py", line 4
    await micropip.install("numpy")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
>>> 
 
```
Would it be possible to implement a feature where modules are automatically checked for imports? If the modules contain imports, then the corresponding packages could be injected using `inject pyodide.loadPackage` automatically.

**Comment by ryanking13** [comment]
> SyntaxError: 'await' outside function

This error message is valid. Async functions need to be called in async function. Note that we allow top-level awaits, so you can
do this in console:

```
>>> await micropip.install("numpy")
>>> import numpytest
```

> Would it be possible to implement a feature where modules are automatically checked for imports? If the modules contain imports, then the corresponding packages could be injected using `inject pyodide.loadPackage` automatically.

That sounds like a nice feature :) It would be nice if you can open an issue with some implementation ideas/challenges. Maybe some of the jupyterlite folks will be interested in this too. Note that there was an similar but quite different idea of adding an import hook (https://github.com/pyodide/pyodide/issues/1917)

**Comment by kolibril13** [comment]
I've now made a feature request #3155 and therefore this issue can be closed.
