### ISSUE TITLE
pyodide does not have requests package

### ISSUE THREAD

**Issue by DavoodFadaee** [pyodide/pyodide#3158]
Hi,
 The pyodide does not have requests module.
is it possible to add it?

Thank you.

**Comment by ryanking13** [comment]
Supporting requests requires Synchronous IO, which is not easy task (See: https://github.com/pyodide/pyodide/issues/1503) for now.

Closing as a duplicate of #398. Don't hesitate to comment there is you have ideas to share.

**Comment by rth** [comment]
You can currently use https://github.com/koenvo/pyodide-http for requests.
