### ISSUE TITLE
Type safety with a @types/pyodide package ?

### ISSUE THREAD

**Issue by fcrozatier** [pyodide/pyodide#3164]
## 🚀 Feature

It would be great to have a lightweight @types/pyodide npm package to declare the pyodide API and add type safety to a typescript project.

### Motivation

There is the [pyodide](https://www.npmjs.com/package/pyodide) npm package with full typescript support which is great. But it is intended to load Pyodide in Node.js and is quite heavy (~17MB) when I just want type safety with the pyodide API.

### Pitch

Be able to use the pyodide api with type safety and autocompletion.

### Alternatives

You can install the pyodide npm package but it's quite heavy.

**Comment by rth** [comment]
Thanks for the suggestion!

Can one auto-generate such package from the existing npm package?  cc @mneil

**Comment by fcrozatier** [comment]
Yes you can extract the `pyodide.d.ts` of the existing package and rename it `index.d.ts` and that's basically it. 
The `package.json` is auto-generated:
https://github.com/DefinitelyTyped/DefinitelyTyped#packagejson
Also
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by mk0x9** [comment]
> But it is intended to load Pyodide in Node.js

You can use it in the browser too, if you don't want to rely on the external CDN.

> a lightweight @types/pyodide npm package

Instead of publishing it to definitely typed it would be much better & easier to publish it to npm, IMO. Updates in definitely typed would require code review from other contributors/maintainers of DT

**Comment by mneil** [comment]
Forgot about this thread! We don't need to publish to @types. A really simple fix would be simply define the types entrypoint that is already being distributed with pyodide.

In package.json we need to add
```
"types": "./pyodide.d.ts",
```

The utility of of the definitely typed repo is that:

 1. package maintainers don't publish types. The community can provide one
 2. you want to separate types for those who do and do not use TS*
 3. your type definitions file(s) are massive and you want to reduce the overall package size and splitting off types is a quick win

*Even javascript users benefit from type hints in modern IDEs so point 2 is not as big of a deal anymore.
