### ISSUE TITLE
Enable ripemd160 support in hashlib

### ISSUE THREAD

**Issue by giacomocaironi** [pyodide/pyodide#3198]
## 🚀 Feature

Enable ripemd160 support in hashlib

### Motivation

A library I am working with uses the ripemd160 function provided by hashlib. Right now I can't use it because OpenSSL, which hashlib relies upon, stopped enabling its support automatically as of last year. On any computer you can enable it manually modifying a config file, but with pyodide this is not possible (as far as I know)

### Pitch

I would like to have Pyodide modify its OpenSSL config to re-enable support for ripemd160

### Alternatives

I could monkey patch the hashlib.new function

**Comment by ryanking13** [comment]
Thanks for the report @giacomocaironi! We need to include `_hashlib` (a built-in module written in C that is used by hashlib) in Pyodide distribution to fix this. Since we already have openssl, it won't be hard to add `_hashlib`, though I think we need to unvendor it by default to reduce the size of initial download size.

**Comment by ryanking13** [comment]
You need to load `_hashlib` **before** importing `hashlib`. It is because it is [unvendored](https://pyodide.org/en/latest/usage/wasm-constraints.html#optional-modules) in order to reduce the initial download 
time.

Therefore, you need to do such as:

```py
>>> import pyodide_js
>>> await pyodide_js.loadPackage("_hashlib")
>>> import hashlib
>>> hashlib.new("ripemd160")
...
<ripemd160 _hashlib.HASH object @ 0xc7f430>
```

while this will not work:

```py
>>> import haslib
>>> hashlib.new("ripemd160")
...
ValueError: unsupported hash type ripemd160
```

**Comment by giacomocaironi** [comment]
Thank you very much, problem solved! I was loading ``_hashlib`` after importing ``micropip``, which in turn import ``hashlib``. I think hashlib in this case falls back to its python implementation, and this was the reason why ``ripemd160`` was still not available.
Should this be documented?

**Comment by ryanking13** [comment]
For those who will see this issue later, we will ship `_hashlib` with a name `hashlib` in Pyodide 0.22: #3349. So you need to load it via `micropip.install("hashlib")`.
