### ISSUE TITLE
Test failure regarding pytest 7.2.0 update

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3207]
Recent pytest 7.2.0 update dropped `py` dependency (https://github.com/pytest-dev/pytest/pull/10396). 
And it seems like quite a lot of `pytest-*` plugins were using `py` package without installing it explicitly.

This is causing some errors in our CI ([1](https://app.circleci.com/pipelines/github/pyodide/pyodide/4946/workflows/d638648a-91ad-423e-a87a-67cffb5f02c5/jobs/59266), [2](https://app.circleci.com/pipelines/github/pyodide/pyodide/4945/workflows/f94a6667-24e9-4fcd-8118-cfe933fcb98d/jobs/59226)).

A hotfix would be pinning pytest version < 7.2. But I guess plugin devs will soon make a release with a fix (`pytest-benchmark` already did), or we can ask them to add `py` as a dependency.

**Comment by The-Compiler** [comment]
FYI, I opened a PR against pytest-mypy-plugins visible in that first CI log: https://github.com/typeddjango/pytest-mypy-plugins/pull/106

As a workaround, you could also add `py` to your own dependencies temporarily, until the plugins are fixed.

**Comment by ryanking13** [comment]
Thanks a lot @The-Compiler!
