### ISSUE TITLE
idbfs not really write data to idb

### ISSUE THREAD

**Issue by mccoysc** [pyodide/pyodide#3208]
## 🐛 Bug

idbfs not really write data to idb

### To Reproduce
run pyodide in chrome: 

in js console:
pyodide.FS.mkdir("/mnt/")
pyodide.FS.mount(pyodide.FS.filesystem.IDBFS,{},"/mnt/")

run python code by pyodide,the py code as the follow:
f=open("/mnt/test.txt","w")
f.write("123456")
f.flush()
f.close()

and then,in chrome's idb data tab,you can't see any data for the file "test.txt".

and after i refresh the web page,the file "test.txt" disapeared.

### Environment

- Pyodide Version 0.21.2:
- Browser version chrome 106.0.5249.119:
- Any other relevant information:

**Comment by ryanking13** [comment]
IDBFS is an "async" file system, so you need to call `pyodide.FS.syncfs(false, callback_func)` to synchronize changes in the file system. See [Emscripten docs](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-idbfs) and [our test code](https://github.com/pyodide/pyodide/blob/main/src/tests/test_filesystem.py) for more information.

**Comment by hoodmane** [comment]
Maybe we could add an faq for this?

**Comment by ryanking13** [comment]
Yes, a FAQ entry would be nice.
