### ISSUE TITLE
Ability to run user's python code equivalent to using -OO option

### ISSUE THREAD

**Issue by nmstoker** [pyodide/pyodide#3211]
## 🚀 Feature

With the regular Python interpreter, you can call it with the flag -OO that optimises running the user's code by ignoring asserts and dropping docstring.

If this isn't wildly inappropriate for Pyodide (for some reason I've overlooked) could this be considered for implementation?

### Motivation

By intentionally skipping assetts code is saved from running and this can be both useful and would result in a speed up. Having an equivalent for Pyodide would make it somewhat consistent with the regular interpreter.

### Pitch

Seems like it's worth discussion at least 🙂

### Alternatives

Drop this suggestion if it just doesn't make sense or isn't much of a priority 

### Additional context

Documentation on the option is here:

https://docs.python.org/3/using/cmdline.html#cmdoption-OO

**Comment by hoodmane** [comment]
I think this should be possible in dev Pyodide by passing
`loadPyodide({args:["-OO"]})`. All arguments in the `args` list are passed
unchanged to the Python interpreter which can do what it likes with them.

**Comment by ryanking13** [comment]
Closing as resolved.
