### ISSUE TITLE
Docker: Chrome 107 doesn't have debian package

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3217]
## 🐛 Bug
Chrome `LATEST_RELEASE` is currently 107.0.5304.62, but the url https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_107.0.5304.62-1_amd64.deb is a 404.

### To Reproduce

Run `docker build .` in root directory.

### Workaround
Pass `--build-arg CHROME_VERSION=106`.

**Comment by ryanking13** [comment]
I assumed that if version X of chromedriver exists, then version X of chrome also exists, but sadly it seems that [it is not always true](https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_25.html).

> Chrome 107.0.5304.62 for Mac, 107.0.5304.68 for linux and 107.0.5304.62/63( Windows)  contains a number of fixes and improvements...

Probably we should parse the version of Chrome from https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions separately from chromedriver (sigh...)

**Comment by hoodmane** [comment]
@ryanking13 I'm having trouble with docker build again...

**Comment by hoodmane** [comment]
Temporarily fixed by hard coding `CHROME_DOWNLOAD_URL=" https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"`.

**Comment by ryanking13** [comment]
It seems like the chrome versionhistory API is broken (returning strange results):

- https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions

It only shows linux versions with <= 88

- https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions

while it shows windows versions correctly.

I think the chrome team will soon fix this, so let's wait for a few days and if the API is still broken, I'll try to find an alternative way to retrieve chrome versions...

**Comment by hoodmane** [comment]
Thanks!

**Comment by ryanking13** [comment]
It looks like the linux API endpoint now shows correct result.
