### ISSUE TITLE
Pyodide doesn't recognize changes in files using the Emscripten File System API.

### ISSUE THREAD

**Issue by nicobytes** [pyodide/pyodide#3231]
## 🐛 Bug

When I'm using  [pyodide.FS](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.FS) the method writeFile Pyodide doesn't recognize changes in files.

### To Reproduce

1. Create a file using FS.writeFile, like this:
```js
const content = `
def hello():
  return 'hello v1'
`;
pyodide.FS.writeFile('my_mod.py', content );
```
2. Check the content by FS.readFile
 ```js
const contentPy = pyodide.FS.readFile('my_mod.py');
const string = new TextDecoder().decode(contentPy);
console.log(string) // print content
```
3. Now, execute code by runPython.
```js
pyodide.runPython(`
    import my_mod
    print(my_mod.hello())
`);
```
4. Check stdout, show the result:
```sh
hello v1
```
Here all fine!

5. But, when I make any change in my_mod.py content with FS.writeFile **Pyodide doesn't recognize the changes**. For example:
```js
const newContent= `
def hello():
  return 'change'
`;
pyodide.FS.writeFile('my_mod.py', content );
pyodide.runPython(`
    import my_mod
    print(my_mod.hello())
`);
```
6. Pyodide shows in stdout the old version file, check stdout:
```sh
hello v1
hello v1
```

### Expected behavior

Pyodide should recognize changes in files using the Emscripten File System API.

### Environment

- Pyodide Version: 0.21.3

### Additional context

I create a demo in this [stackblitz project](https://js-qzw6ps.stackblitz.io) to explain the bug.

**Comment by hoodmane** [comment]
I don't think this is really a bug. The native Python interpreter behaves in the same way.

**Comment by nicobytes** [comment]
Hello @hoodmane thanks for the response, I really appreciate it, but in the local Python environment, it works like this, for example:

1. I have a `file.txt` with content
2. I read the file content with a Python script.
3. In the stdout shows the file content.
4. Now I make a change in the `file.txt`.
5. I read again the file content with the same Python script.
6. In stdout shows the file content with changes.

In the Pyodide case, when running the Python script for the first time, all is right, but when I try to read the content file for the second time with changes, Pyodide shows the content with the first version as if it were cached.

**Comment by hoodmane** [comment]
> 5. I read again the file content with the same Python script.

But you shut down and restarted Python between the two times you `import`ed the file. If instead you do:
```py
from pathlib import Path

def write_module(x):
    Path("module.py").write_text(f"x={x}")

write_module(2)
from module import x
assert x == 2
write_module(3)
from module import x
assert x == 2 # x is still 2
```
you get the same result. You can try various things like `importlib.invalidate_caches` and `del sys.modules["module"]` and `importlib.reload` but as far as I can tell I am unable to get it to see the new value of x.

**Comment by nicobytes** [comment]
Hello @hoodmane OK, I get it. It is clear that during runtime the content doesn't change; your example is clear, thanks for that.

In my mind, the `pyodide.runPython` executes again the code like run in shell `python file.py`, but not.

In my case, I'm working on implementing a little playground with education proposals like that:

![68747470733a2f2f692e696d6775722e636f6d2f324c754f5a57462e706e67](https://user-images.githubusercontent.com/7611944/200172755-38b2082b-a3a4-4498-9f26-39d903bd2f3a.png)

And load the files, and then execute `pyodide.runPython` with this code:

```py
import pytest
from pytest_jsonreport.plugin import JSONReport

def run_tests():
  plugin = JSONReport()
  pytest.main(["-v"], plugins=[plugin])
  return plugin.report

run_tests()
```

But when I try with multiple files, for example:

![Frame 1](https://user-images.githubusercontent.com/7611944/200172973-dc14315f-ce5d-4789-bcae-cfebf90df7e2.png)
![Frame 2](https://user-images.githubusercontent.com/7611944/200172979-3222e0bc-172c-46ed-88d2-65e6abadb273.png)

I use Monaco like Code Editor, but when I tried updating the files with FS, it just showed the old version. The unique solution is to load the entire environment again.

1. loadPyodide
2. loadPackage (pyTest and micropip)
3. Install the package `pytest-json-report` to read tests results
4. Write the files using pyodide.FS
5. Finnally run this code.

```py
import pytest
from pytest_jsonreport.plugin import JSONReport

def run_tests():
  plugin = JSONReport()
  pytest.main(["-v"], plugins=[plugin])
  return plugin.report

run_tests()
```

But for whatever change in the files, I have to do these 5 steps again. Do you have any suggestions?

**Comment by hoodmane** [comment]
Try this:

<details>
<summary>Details</summary>


```py
from importlib import import_module
from importlib.util import module_from_spec
from pathlib import Path
import shutil
import sys


def write_module(x):
    Path("module.py").write_text(f"x={x}")


def reload_module(name):
    module = import_module(name)
    shutil.rmtree("__pycache__", ignore_errors=True)
    m = module_from_spec(module.__spec__)
    m.__spec__.loader.exec_module(m)
    sys.modules[name] = m


write_module(2)
from module import x

assert x == 2


write_module(3)
reload_module("module")

from module import x

assert x == 3
```

</details>

**Comment by hoodmane** [comment]
This would probably be another good faq entry.

**Comment by nicobytes** [comment]
@hoodmane great!

I tried your approach, which works here [in my demo](https://js-qzw6ps.stackblitz.io) and now I have an idea for not running the 5 steps again.

The next week, I'll send a PR with improvements in the docs. 🙂
