### ISSUE TITLE
Specify non-python build requirements in meta.yaml

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3237]
### Motivation

Some packages require extra executables during the build. For example:

- scipy: gfortran, f2c
- cryptography: cargo
- libproj: sqlite3
- nlopt: swig

We are listing these requirements in our [docs](https://pyodide.org/en/stable/development/building-from-sources.html), but (I guess) most people don't need to build complete package sets locally, so it is not very useful for new people who want to build Pyodide locally (and it might make people freak out: "So many requirements to build!").

Actually, to build Pyodide with core packages (in Linux), we only need some [essential build tools + Python and Node.js](https://github.com/pyodide/pyodide/blob/af206d159cc127920b191e1bbfd75dfbef5f981d/.github/workflows/main.yml#L107).
Note that for now `make` fails [if `gfortran` or `f2c` not exists](https://github.com/pyodide/pyodide/blob/af206d159cc127920b191e1bbfd75dfbef5f981d/tools/dependency-check.sh#L43-L46), even if we don't build scipy.

So I think it would be nice to have a way to specify and check per-package requirements, instead of listing all of them in docs.

### Feature

Add `requirements/executable` key (open to other names), which specifies extra executables required to build a package.

During the build, it can be easily checked via `shutil.which("...")` and raise an error if those executables are unavailable.

### Alternatives

If adding a new key is not preferable, we can just use `which <executable>` inside `build/script` instead.

**Comment by hoodmane** [comment]
Sounds good to me.

**Comment by rth** [comment]
Conda solves this by not differentiating between python and non-python packages, and could install most of them (aside from cargo). But that would be very tied to conda then indeed.

+1 for the proposal, and we could then remove the optional requirements in https://pyodide.org/en/stable/development/building-from-sources.html#using-make which are partial and incomplete anyway. 

> During the build, it can be easily checked

It would be better if this check was done after the dependency tree is constructed as opposed to when the package is being built, for faster iteration. We don't want the build to be interrupted N times due of N missing executables, once with a single list of missing executables would be better.
