### ISSUE TITLE
Add rasterio to enable using movingpandas

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyodide/pyodide#3248]
## 🐍 Package Request

I would like to be able to install the latest version of [movingpandas](https://pypi.org/project/movingpandas/). See https://discourse.holoviz.org/t/try-out-panel-sharing/4549/5?u=marc for motivation.

I'm trying to install it in the [Pyodide REPL](https://pyodide.org/en/stable/console.html) via micropip. But it fails due to fiona and rasterio.

![image](https://user-images.githubusercontent.com/42288570/201507652-cb6c0451-45a1-43b5-b6a1-b659959c9829.png)

According to https://github.com/pyodide/pyodide/issues/3091 fiona should be supported. But it appears not to be?

**Comment by rth** [comment]
Hi @MarcSkovMadsen,

you would need to use the latest alpha release for this https://pyodide.org/en/0.22.0a3/console.html for now. We haven't yet done a stable version with it. 

The other issues was that alpha releases were not auto-deployed in the docs, but we should fix that https://github.com/pyodide/pyodide/issues/3250

**Comment by rth** [comment]
That's for fiona. As for rasterio, indeed it would still need to be packaged (possibly with some of [its dependencies](https://github.com/conda-forge/rasterio-feedstock/blob/main/recipe/meta.yaml#L33) we don't yet have)

**Comment by LukeAFullard** [comment]
+1

**Comment by MarcSkovMadsen** [comment]
Thanks it works.

Then I just have to figure out why the OSError is raised and if it can be fixed and by whom.

![image](https://github.com/user-attachments/assets/373c133f-50be-4895-89ce-76ad4c96ba3d)

**Comment by kjmalek** [comment]
Hi @MarcSkovMadsen, Unless you run a local build, rasterio won't be available until the next release. In addition to rasterio, movingpandas also relies on libspatialindex, which can't be installed via micropip. I'd recommend submitting a new issue requesting that specific package and taking a go at submitting a PR. Here is the conda-forge recipe for [libspatialindex](https://github.com/conda-forge/libspatialindex-feedstock/tree/main/recipe) for reference.
