### ISSUE TITLE
Add pyinstrument 4.4.x

### ISSUE THREAD

**Issue by bollwyvl** [pyodide/pyodide#3255]
## 🐍 Package Request

- Package Name and Version: `pyinstrument` / latest
- Package URL: https://github.com/joerick/pyinstrument
- Package Dependencies that needs to be resolved first: `[]`

## Notes

If even possible, it would be interesting to have `pyinstrument` available, as it is one of the few tools out there that does a good job of profiling `async` methods. Being able to profile, even with whatever overhead it adds, would still be meaningful for assessing the impact of other packages.

## References

- https://github.com/pyodide/micropip/issues/24#issuecomment-1314397063
- [conda-forge recipe](https://github.com/conda-forge/pyinstrument-feedstock/blob/main/recipe/meta.yaml)

**Comment by hoodmane** [comment]
Seems like it builds fine.

**Comment by bollwyvl** [comment]
:rofl: we need a `maintainerinstrument` for that absurd display of `async` development!
