### ISSUE TITLE
Update docker image for "pyodide/pyodide"

### ISSUE THREAD

**Issue by michael-dm** [pyodide/pyodide#3266]
Hello,

I just noticed that the last build for `pyodide/pyodide` image was 7 months ago for 20.0

Would you be able to make a more recent build ?

Thanks

**Comment by rth** [comment]
The pre-built docker image keeps failing to deploy on releases. With the addition of [out-of-tree builds](https://pyodide.org/en/stable/development/new-packages.html#building-python-wheels-out-of-tree) we are considering no longer supporting it. 

For your use case, out-of-tree build doesn't work?

**Comment by rth** [comment]
So a decision was taken to stop providing that image https://github.com/pyodide/pyodide/issues/3308. We need to mark it as deprecated on Docker Hub.
