### ISSUE TITLE
RFC Distribute bytecode compiled sources (.pyc)

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3269]
To summarize the discussion in https://github.com/pyodide/pyodide/issues/3050 and the associated PRs there is currently a proposal to start distributing bytecode (.pyc) files instead of the original source files (.py),
 - for the standard library  https://github.com/pyodide/pyodide/pull/3166 (which will additionally put them in a zip file)
 - for package wheels https://github.com/pyodide/pyodide/pull/3253

The goal of this issue is to get user feedback on this idea and see if there are any concerns about it. So please don't hesitate to comment. You can also vote with emoji :+1: (choice 1) and :-1: (choice 2).

### Advantages

This has the potential to significantly speed up the initial load time as Python no longer needs to bytecode compile source code and can run the interpreter on it directly. See benchmarks below for more detail.

### Disadvantages

The are two main limitations,
 1. the source code is no longer readable, so for instance, if you get an exception, you will no longer be able to open an in-browser text editor to read the source code in dependencies and investigate it
 2. In the exception tracebacks,
     - we lose the quoted source code (including the improved [Python 3.11 error location indicated with arrows ('^')](https://docs.python.org/3/tutorial/errors.html#syntax-errors)) (see [this example](https://discuss.python.org/t/wasm-unvendoring-some-of-stdlib-modules/18076/8))
     - in traceback of packages, we can no longer reliably indicate the absolute path and instead will likely use a relative path (cf [this discussion](https://discuss.python.org/t/proper-file-paths-to-show-in-exception-for-py-compiled-files/21108))

### Possibilities

There are several possible outcomes,
 1. this proposal is accepted, we only distribute .pyc files without associated source code (.py), since distributing both would increase download size even more
 2. the proposal is rejected and we continue distributing .py files only
 3. we make separate builds: one for .py source and one for .pyc. This will significantly increase our maintenance burden and it's unclear if it would happen (so this may be the same as 2, or it may happen).

### Benchmarks 

See [source](https://discuss.python.org/t/proper-file-paths-to-show-in-exception-for-py-compiled-files/21108/6) for more details,
![image](https://user-images.githubusercontent.com/630936/202668007-3b3bba86-dffa-4b35-b903-79c817511d38.png)

**Comment by casatir** [comment]
Hi,

Let me first congrats all devs for their amazing work ! In Basthon/Capytale, the traceback is really important since it is used to learn Python. Is it deployed somewhere in order to try and get a precise idea of what we loose and what we gain?

Thanks

**Comment by kikocorreoso** [comment]
Thanks for posting this and for all the hard work.

Initial load time improves due to no compilation but also due to file size reduction? I guess so. Do you have a rough number for the file size reduction? 10%, 20%, 30%,..., larger for .py Vs .pyc files?

For the third posibility, is it much maintenance burden? I see this as the best option for users but not for maintainers. If there are low hanging fruit issues involving this maybe others could help. I do not have much time this days but I could try to help.

**Comment by joemarshall** [comment]
I feel like this is enough of a win that it is worth doing. 

Once stack switching is implemented, one could return all the lovely tracebacks by streaming the code asynchronously when needed or something.

**Comment by rth** [comment]
Thanks for the feedback!

> In Basthon/Capytale, the traceback is really important since it is used to learn Python.

Yes, I imagine. For context, Basthon/Capytale is deployed in hight schools in France for teaching student Python as their first programming language.  To a lot of schools.

>  Is it deployed somewhere in order to try and get a precise idea of what we loose and what we gain?

Not currently, but let me do a branch merging those two PRs and deploy it somewhere, so you can try it.

> Initial load time improves due to no compilation but also due to file size reduction? 

In size on disk yes, .pyc are often smaller (not always but maybe I also didn't use the correct optim options in my tests). However, since we distribute gzip or brotli compressed files via the CDN, after the compression the size of downloaded files is very comparable. 

Thanks for offering help! We will try to tag more issues as ["help wanted"](https://github.com/pyodide/pyodide/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22) and ['good first issue'](https://github.com/pyodide/pyodide/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22).

Another comment is that the above benchmarks are with a local server and so with a minimal data transfer time.  They would be comparable with a CDN and a good internet connection. For a very slow internet connection though, the download time might still dominate and this will then have less impact on overall load time.

> For the third posibility, is it much maintenance burden?

We would need to evaluate the feasibility, but first I wanted to see if there was any need/interest from users in doing that.

> Once stack switching is implemented, one could return all the lovely tracebacks by streaming the code asynchronously when needed or something.

True, but it's still on a few year timescale, while the question is what do we do not to break user expectations now. 

It likely also depends on the use case: I would guess for teaching in university to students already familiar with Python, tracebacks verbosity matters less. While for @casatir 's use case, and students just learning Python it might be more critical.

**Comment by afbarbaro** [comment]
Thanks for posting this. The speedup is great, I'm for it.
Will there be a flag to control this? I can see myself wanting the slower (.py) version while I'm troubleshooting, debugging, and doing early prototype development, then switching to the faster (.pyc) for production. This is the sort of thing one does when working in javascript and using dev vs prod bundling.

**Comment by joemarshall** [comment]
Hey,

Stupid question on this, how much extra file size would distribution of pyc **and** .py files add? And if that was done, would it default to .pyc for loading modules with the same performance benefits?

Or alternatively, could we use browser storage to enable the default cache methods in python, so that source distributions for wheels could still be used, but on reloading the page the compiled version from storage would be used. So it would start up slow first time, but any future startups would use cached compiles 

For me the big thing is not so much that first time you visit the site the startup is slow, it is that it starts slow even on the tenth page on the site, or the tenth time you go there.

**Comment by rth** [comment]
> how much extra file size would distribution of pyc and .py files add? And if that was done, would it default to .pyc for loading modules with the same performance benefits?

Well I would say including both py and pyc would be between 100% more for pure python packages to maybe 20%-30% more for packages with lots of C extensions.  Just for the stdlib though it would add several MB I think which is not great. 

For some applications (e.g. teaching) users might not care much, but for others e.g. an app on an arbitrary website loaded on mobile that could be a deal breaker. Also as I mentioned all of the above assumes one has a good internet connection. If the connection is not good, the overall load time will be determined by the download size and so we can't increase that much.

**Comment by casatir** [comment]
Hi there,

We have investigate this and had some discussions with teachers and devs at Capytale.

Besides the excellent effort you provides with this feature, it seems we are far more interested by clean traceback than launching speedup. So solution 2 best fit our needs.

Thanks again.
Romain

**Comment by rth** [comment]
Thanks for the feedback! The poll on Twitter was also not entirely conclusive, most users prefer compiled sources but around 25% would still prefer .py even at the cost of slower load times.
![image](https://user-images.githubusercontent.com/630936/205244325-d72d8b2b-a699-42fc-8ef2-3420a5a2e209.png)

IMO for now, we could maybe try to have a build option to source compile or not, and then look at how difficult it would be to deploy both.

**Comment by joemarshall** [comment]
Hey, 

Looking at my idea above to cache the pyc files in browser cache for modules. I just did a quick timeit test, and it looks like it could potentially have decent speedups, check out how much faster the import goes after the call to `sys.dont_write_bytecode=False` in the pyodide console output below. 

What it would need doing is:
1) Setting `sys.pycache_prefix` to point to a known folder on the file system, and `sys.dont_write_bytecode` turning off.
2) Mounting something persistent (IDBFS or similar) at the cache prefix
3) Syncing this IDBFS cache either:
    a) when calls to python return to js.
    b) Or even better one could force generate the cache on package load so that we didn't have to rely on python returning to javascript to make the cache persistent.

It might however need messing around with timestamps etc. to make sure a)new versions of the module created new pyc files, and old versions of the module kept using the cache, but it would be a nice compromise. It would mean that first page load time wouldn't be improved, but once a module was loaded on a particular origin, any page from that same origin could use the cache and import quicker. 

>>> import scipy,timeit,importlib
>>> import scipy.optimize
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.9140000000000015
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.882599999
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.8754999999999988
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.873899999999999
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.8820000000000014
>>> import sys
>>> sys.dont_write_bytecode
True
>>> sys.dont_write_bytecode=False
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.45989999899999745
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.45009999999999906
>>> timeit.timeit('importlib.reload(scipy.optimize)',setup='import scipy.optimize,importlib',number=1000)
0.45729999899999996

**Comment by ryanking13** [comment]
> Looking at my idea above to cache the pyc files in browser cache for modules.

I think it is a good idea @joemarshall. Would you mind opening a separate issue for it though? The idea of distributing .pyc files can also enhance the first page load time, while your idea is about caching.

To say one more thing, I think it would be nice if we can make it (writing pyc codes into IDBFS and loading it next time) in the form of a plug-in rather than implementing it inside Pyodide, in order to reduce the complexity of Pyodide codebase. It would require some modification in the `loadPyodide` interface in that case to accept plug-ins as a parameter.
