### ISSUE TITLE
Add typed-ast

### ISSUE THREAD

**Issue by falkben** [pyodide/pyodide#3291]
## 🐍 Package Request

- Package Name and Version : typed-ast latest (1.5.4 currently)
- Package URL : https://github.com/python/typed_ast
- Package Dependencies that needs to be resolved first: `[]`

**Comment by rth** [comment]
From the docs,

> typed_ast will not be updated to support parsing Python 3.8 and newer. Instead, it is recommended to use the stdlib ast module there, which has been augmented to support extracting type comments and has limited support for parsing older versions of Python 3.

Python 3.7 end of life in 7 months, so I'm a bit hesitant to add a package that only works with outdated Python versions. What is your use case?

**Comment by falkben** [comment]
Ah, I did not realize. I was using 3.10. It is a dependency of `datamodel-code-generator`. Micropip reported several packages it couldn't find a wheel for and `typed-ast` was one of them. I was able to compile it myself so I can host it as well.

I'm a bit confused about how the typed-ast dependency is specified by poetry in there, but that's a separate issue for that project.
