### ISSUE TITLE
Remove `./run_docker --pre-built`?

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3308]
The command `./run_docker --pre-built` is mentioned in our docs [1](https://pyodide.org/en/stable/development/building-from-sources.html?highlight=pre-built#using-docker) [2](https://pyodide.org/en/stable/development/new-packages.html?highlight=pre-built#creating-the-meta-yaml-file), but actually, it is not working as expected.

The pyodide build artifacts inside the pre-built docker image are in `/src/pyodide`, but when we do `./run_docker --pre-built`, the host file system is mounted to `/src`, overriding the file system inside the container. So `./run_docker --pre-built` works almost just same as `./run_docker`.

For now, I think the correct way to use the pre-built docker image is like this:

```bash
mkdir dist
docker pull pyodide/pyodide:0.20.0
docker run  --it -v $(pwd)/dist:/src/pyodide/build pyodide/pyodide:0.20.0 /bin/bash
$ cd /src/pyodide
$ # Do something inside the docker image...
$ make && exit
# built artifacts are saved to ./dist
```

So I would like to discuss two things:

1. We have to either remove `--pre-built` flag, or fix it to work as expected.

2. If we decide to remove `--pre-built` flag, should we still build pre-built docker image? or should we stop providing the image and tell users to use`pyodide build` instead?

Related issues:

- https://github.com/pyodide/pyodide/discussions/3304
- https://github.com/pyodide/pyodide/issues/2705
- https://github.com/pyodide/pyodide/issues/3266

WDYT?

**Comment by rth** [comment]
I would be +1 to stop distributing the pre-built image altogether (the deployment CI was broken for the last few releases anyway) in favor of either out-of-tree build or using the `pyodide-env` image in CI with caching (we should maybe specifically mention how we use ccache).

**Comment by ryanking13** [comment]
@hoodmane WDYT?
