### ISSUE TITLE
ModuleNotFoundError after writing multiple files with FS.writeFile

### ISSUE THREAD

**Issue by antocuni** [pyodide/pyodide#3311]
## 🐛 Bug

This might be a duplicate of #737, but I'm opening a new issue because I'm seeing something very weird.
I'm using Pyodide  0.21.3.

### To Reproduce

Consider the following snippet (I run it in node, but I can reproduce the same behavior also in the browser):
```js
const { loadPyodide } = require("pyodide");

function busyWait(ms) {
    let start = new Date().valueOf();
    while( (new Date()).valueOf() - start < ms)
        ;
}

async function main() {
    let pyodide = await loadPyodide({
        indexURL: "./node_modules/pyodide",
    });

    console.log("Pyodide version: ", pyodide.version);

    let success = 0;
    let errors = 0;
    for(let i=0; i<100; i++) {
        // uncommenting EITHER of the following lines, it works reliably
        //pyodide.runPython('import importlib; importlib.invalidate_caches()');
        //busyWait(1000);

        pyodide.FS.writeFile(`bar${i}.py`, `x = ${i}`);
        try {
            pyodide.runPython(`import bar${i} as bar; print('OK ', bar.x)`);
            success++;
        }
        catch(e) {
            //console.log(e);
            console.log('ERR', i);
            errors++;
        }
    }
    console.log("success:", success);
    console.log("errors :", errors);
    console.log("error rate: ", (errors/(success+errors))*100, "%");
}

main();
```

The expected result is obviously to see all `OK` and 0% error rate, but what happens is that very often I get `ERR`.
I observed the following:
- if I uncomment the call to `invalidate_caches()`, it passes reliably
- if I uncomment `busyWait(1000)`, (i.e., 1 second) it passes reliably

The interesting part is what happens with lower values of `busyWait`:
- with `busyWait(500)`, it fails ~50% of the times
- with `busyWait(100)` it fails ~90% of the times
- with `busyWait(10)` it fails ~99% of the times

The following is just a guess, but I think that considering the above it's a reasonable explanation:
- somewhere there is a timestamp which is stored with a resolution of 1s
- if the "new" files are written "too early", importlib think that it is of the same epoch as the "old files/directories" and thus it thinks the cache is still valid
- if you wait long enough, the 1s timestamp gets a new value and importlib correctly notices that there is a "new" file

I am not sure whether this is a bug/"feature" of emscripten. I thought it's a good idea to open it here so that we can maybe discuss possible pyodide-specific mitigations and/or workarounds

**Comment by ryanking13** [comment]
> somewhere there is a timestamp which is stored with a resolution of 1s

AFAIK cpython updates the file cache [if mtime of the path has been changed](https://github.com/python/cpython/blob/a58ebcc701dd6c43630df941481475ff0f615a81/Lib/importlib/_bootstrap_external.py#L1534-L1540). So I guess cpython considers that the directory has not been changed if the file write happens multiple times in  < 1s.

> pyodide-specific mitigations and/or workarounds

Perhaps we can provide an API like `writePy` which calls `writeFile` and then calls `invalidate_caches()`. Though I think it is the mostly users' job to call `invalidate_caches()`  after writing files into the file system.

**Comment by hoodmane** [comment]
@ryanking13 I think the point is that this <1s behavior is not observed in native Python, so calling `invalidate_caches` is most likely a work around for a bug in the way that Emscripten FS handles time stamps.

**Comment by hoodmane** [comment]
Though now I'm getting what you are saying: the issue is that `st_mtime` only has a resolution of 1 second...

**Comment by hoodmane** [comment]
So in that case it would not be a Pyodide or Emscripten limitation but instead a consequence of the way that Python and posix file systems interact.

**Comment by hoodmane** [comment]
Ah but wait:

>               /* Since Linux 2.6, the kernel supports nanosecond
>                  precision for the following timestamp fields.
>                  For the details before Linux 2.6, see NOTES. */

https://man7.org/linux/man-pages/man2/lstat.2.html

So it could least in principle work at a finer time resolution?

**Comment by ryanking13** [comment]
> I think the point is that this <1s behavior is not observed in native Python

I was able to observe the similar result in native Python:

```py
import os
import time
import importlib

success = 0
error = 0
for i in range(1000):
    os.system(f"echo x=1 >> bar{i}.py")
    # importlib.invalidate_caches()
    try:
        __import__(f"bar{i}")
        success += 1
    except:
        error += 1

print(f"Success: {success}")
print(f"Error: {error}")

os.system("rm -rf __pycache__")
os.system("rm -rf bar*.py")
```

```
Success: 254
Error: 746
```

**Comment by hoodmane** [comment]
Looks to me like the relevant section of `posixmodule.c` is here:
https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L2378
and here:
https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L2308
It's confusing because it sure looks like it's trying to put a nanosecond resolution modification time into the result of `os.stat` but when I actually run it I only see second resolution...

**Comment by ryanking13** [comment]
> Looks to me like the relevant section of `posixmodule.c` is here: https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L2378 and here: https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L2308 It's confusing because it sure looks like it's trying to put a nanosecond resolution modification time into the result of `os.stat` but when I actually run it I only see second resolution...

Yeah, the [python docs says that it is available](https://docs.python.org/3/library/os.html#os.stat_result), but  I can't get nanosecond precision result in my machine neither.

**Comment by hoodmane** [comment]
Oh wait, `os.stat(p).st_atime_ns` is working for me on my native Python:

```py
>>> Path("a").write_text("a"); sleep(0.001); Path("b").write_text("b")
>>> os.stat("a").st_mtime_ns
1669942845668940251
>>> os.stat("b").st_mtime_ns
1669942845672940251
```

**Comment by ryanking13** [comment]
In Pyodide (dev console), it shows:

```py
>>> os.stat("ff").st_ctime_ns
1669943018000000000
```

**Comment by hoodmane** [comment]
In Pyodide:
```py
>>> sysconfig.get_config_vars()["HAVE_STAT_TV_NSEC"]
1
>>> sysconfig.get_config_vars()["HAVE_STAT_TV_NSEC2"]
0
```
so... `HAVE_STAT_TV_NSEC` being 1 sounds promising...

**Comment by hoodmane** [comment]
Aha! The problem is that Emscripten always sets `tv_nsec` to 0:
https://github.com/emscripten-core/emscripten/blob/main/src/library_syscall.js#L67
Emscripten uses `Date.getTime()` to generate times which has millisecond precision, so if we  patch it to fill in `tv_nsec` with `(getTime() % 1000) * 1000` then I think it might fix the problem.

**Comment by ryanking13** [comment]
> so... HAVE_STAT_TV_NSEC being 1 sounds promising...

Great! Thanks sound indeed promising.

BTW, even if we make `st_mtime_ns` available in Pyodide, I guess we have to convince CPython devs to use `st_mtime_ns` instead of `st_mtime` [here](https://github.com/python/cpython/blob/a58ebcc701dd6c43630df941481475ff0f615a81/Lib/importlib/_bootstrap_external.py#L1534-L1540)?

**Comment by hoodmane** [comment]
`st_mtime` may be a float though?

**Comment by ryanking13** [comment]
No it is in seconds: https://docs.python.org/3/library/os.html#os.stat_result.st_mtime

**Comment by hoodmane** [comment]
Hmm well we can patch that too.

**Comment by ryanking13** [comment]
> No it is in seconds: https://docs.python.org/3/library/os.html#os.stat_result.st_mtime

Oh wait, I think you are right, it is a float.

```
>>> os.stat("setup.cfg").st_ctime
1669941226.157467
>>> os.stat("setup.cfg").st_mtime
1669267082.0
>>> os.stat("setup.cfg").st_atime
1669941224.1814687```

**Comment by hoodmane** [comment]
Without patch:
```
success: 1
errors : 99
error rate:  99 %
```
With patch:
```
success: 100
errors : 0
error rate:  0 %
```

**Comment by ryanking13** [comment]
Great! So it was an emscripten precision issue not a cpython issue. I was wrong.

**Comment by antocuni** [comment]
I'm confused. If it's not a CPython issue, why does @ryanking13 pure python example fails?
I tried to put some sleeps and run it on my linux machine:
```python
import os
import time
import importlib

success = 0
error = 0
for i in range(1000):
    if (i % 100) == 0:
        print(i)
    os.system(f"echo x=1 >> bar{i}.py")
    #time.sleep(1e-3)   # 0% error
    #time.sleep(1e-6)   # 3.5% error
    #time.sleep(1e-9)    # 6.8% error

    # importlib.invalidate_caches()
    try:
        __import__(f"bar{i}")
        success += 1
    except:
        error += 1

error_rate = error/(error+success)
print(f"Success: {success}")
print(f"Error: {error}")
print(f"Error rate: {error_rate*100:.2f}%")

os.system("rm -rf __pycache__")
os.system("rm -rf bar*.py")
```

If the timestamp has nanosecond precision, the `time.sleep(1e-9)` should be enough to get 100% pass, but it seems not.

**Comment by ryanking13** [comment]
> I'm confused. If it's not a CPython issue, why does @ryanking13 pure python example fails?

```py
import os
import time
import importlib

success = 0
error = 0
for i in range(1000):
    if (i % 100) == 0:
        print(i)
    os.system(f"echo x=1 >> bar{i}.py")
    #time.sleep(1e-3)   # 0% error
    #time.sleep(1e-6)   # 3.5% error
    time.sleep(1e-9)    # 6.8% error

    # importlib.invalidate_caches()
    try:
        __import__(f"bar{i}")
        success += 1
    except:
        error += 1

error_rate = error/(error+success)
print(f"Success: {success}")
print(f"Error: {error}")
print(f"Error rate: {error_rate*100:.2f}%")

os.system("rm -rf __pycache__")

for i in range(1000):
    bar = f"bar{i}.py"
    bar_stat = os.stat(bar)
    print(f"{bar}: {bar_stat.st_mtime} / {bar_stat.st_mtime_ns}")
    
os.system("rm -rf bar*.py")
```

```
bar0.py: 1669977221.0698216 / 1669977221069821527
bar1.py: 1669977221.0698216 / 1669977221069821527
bar2.py: 1669977221.0738215 / 1669977221073821524
bar3.py: 1669977221.0738215 / 1669977221073821524
bar4.py: 1669977221.0738215 / 1669977221073821524
bar5.py: 1669977221.0738215 / 1669977221073821524
bar6.py: 1669977221.0778215 / 1669977221077821521
bar7.py: 1669977221.0778215 / 1669977221077821521
bar8.py: 1669977221.0778215 / 1669977221077821521
bar9.py: 1669977221.0778215 / 1669977221077821521
```

Hmm, I can observe that 4~5 files have same nanosec mtime.

**Comment by antocuni** [comment]
> Hmm, I can observe that 4~5 files have the same nanosec time. I'm not sure why this happens. Maybe `time.sleep` isn't trustworthy for nanosec? or maybe OS does some buffered file I/O?

right, I think that weird things are happening. For example, consider this:
```python
import os
import time
import importlib

def main():
    time_ns = time.time_ns

    success = 0
    error = 0
    for i in range(1000):
        if (i % 100) == 0:
            print(i)

        # busy wait for at least 10 nanosecond
        t = time_ns()
        while time_ns()-t < 10:
            pass

        os.system(f"echo x=1 >> bar{i}.py")

        # importlib.invalidate_caches()
        try:
            __import__(f"bar{i}")
            success += 1
        except:
            error += 1

    error_rate = error/(error+success)
    print(f"Success: {success}")
    print(f"Error: {error}")
    print(f"Error rate: {error_rate*100:.2f}%")

    os.system("rm -rf __pycache__")

    PREV = None
    for i in range(1000):
        bar = f"bar{i}.py"
        bar_stat = os.stat(bar)
        mtime_ns = bar_stat.st_mtime_ns
        if mtime_ns == PREV:
            print(f"{bar:10s}: {mtime_ns} EQUAL!")
        else:
            print(f"{bar:10s}: {mtime_ns}")
        PREV = mtime_ns

    os.system("rm -rf bar*.py")


main()
```

here I'm doing a busy wait for 10 nanoseconds, but I still see some timestamps which are equal 😱.

**Comment by hoodmane** [comment]
I think the resolution of the timer is strictly worse than 1 nanosecond. On my computer it seems to have a resolution of about 2 milliseconds, so if I either busywait or sleep for 2 milliseconds, the timestamps are consistently distinct but anything less than that and it's hit or miss.

**Comment by rth** [comment]
Yes, it looks like in the browser timers are precise at a few ms at best (cf this [blog post](https://incolumitas.com/2021/12/18/on-high-precision-javascript-timers/) for a good overview) to avoid timing attacks. It [could be improved](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision) to a few µs by setting cross-origin policy, but it's still nowhere near ns precision.

**Comment by hoodmane** [comment]
Yeah it seems that on our systems outside the browser the file system timestamps also only have a ~1ms resolution which is surprising.
