### ISSUE TITLE
REPL Copy-paste with spaces doesn't work

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3337]
In Firefox if one writes anything with spaces then tries to copy-paste the input to a standard Python REPL, one gets,
```
SyntaxError: invalid non-printable character U+00A0
```
this is because spaces are replaced by this character in Firefox as least.

In Pyodide REPL,
```py
>>> 1 + 1
```
Copy-pasting quoted in the host Python REPL,
```py
>>> '1 + 1'
'1\xa0+\xa01'
```
Likely due to https://github.com/jcubic/jquery.terminal/blob/b23a628283e12bd8996a3a2d8676cff6d1587a7a/__tests__/terminal.spec.js#L264 but unclear if it's due to a issue on they side (can't find anything in their repo) or a misconfiguration on our side. So might need to investigate more before reporting it upstream.

I'm pretty sure it worked OK before, so it might also be due to browser update, as currently even old Pyodide releases have this behavior.

**Comment by hoodmane** [comment]
For me when I copy it says:
```
'1\xc2\xa0+\xc2\xa01\xc2\xa0\nClipbard textarea for jQuery Terminal\n\xc2\xa0\n'
 ```
