### ISSUE TITLE
 Private reporting of a security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [pyodide/pyodide#3351]
Dear pyodide team,

I may have identified a security vulnerability in the codebase of the latest version of pyodide and I would like to report it privately. Could you please opt-in to the Github private reporting [feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

Kind consideration
@Sim4n6

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/207360629-3503a45d-c4c8-456e-9486-559f2b8a10cb.png)

**Comment by rth** [comment]
OK, thanks @Sim4n6 I enabled that option.

**Comment by Sim4n6** [comment]
perfect

**Comment by rth** [comment]
Looking forward to your report. Closing this issue for now, but don't hesitate to comment.
