### ISSUE TITLE
Wasm memory error when using scipy's lgmres

### ISSUE THREAD

**Issue by gabrielfougeron** [pyodide/pyodide#3357]
## 🐛 Bug

Scipy linear algebra methods lgmres gives a `RuntimeError: index out of bounds` when run in pyodide, and not in regular cpython

### To Reproduce

It was very hard for me to write down a small minimal working example because I did not find a small equation to solve where the problem did occur.
So I did the next best thing: I wrote a pytest using `@run_in_pyodide`, with relevant files in this zip file: [pytest.zip](https://github.com/pyodide/pyodide/files/10230304/pytest.zip)

Unzip the above file and cp into the folder.
Download pyodide 0.21.2 (or other ?) ==> https://github.com/pyodide/pyodide/releases/download/0.21.2/pyodide-build-0.21.2.tar.bz2 and unzip files in ./dist

I then called pytest as `pytest --dist-dir=./dist/ --runtime firefox  `

### Expected behavior

a` RuntimeError: index out of bounds` triggered by scipy's lgmres, with a horrible wasm call stack and a bung of memory addresses

### Environment

- Pyodide Version:  0.21.2 , but later versions will likely do the same
- Browser version: Mozilla Firefox 107.0 , but Chrome will trigger the same error
- Any other relevant information:

Please do let me if there is more info I can provide

**Comment by gabrielfougeron** [comment]
Yes, I can tell scipy is a tough nut to crack :-/

**Comment by lesteve** [comment]
@gabrielfougeron maybe you want to try with a recent Pyodide version? The issues we saw in #3203 seems to have been fixed for some unknown reaon in Pyodide 0.22.0.

**Comment by gabrielfougeron** [comment]
I'll do that as soon as I get back from vacations 😊👍

**Comment by gabrielfougeron** [comment]
Hey. I'm going through the list of open issues I created and I'm happy to announce this has indeed been fixed for a while. Big thanks to the pyodide team 😊.
