### ISSUE TITLE
PyQt5 5.15.7 https://pypi.org/project/PyQt5

### ISSUE THREAD

**Issue by pradeepkumar35** [pyodide/pyodide#3366]
## 🐍 Package Request

- Package Name and Version :
- Package URL :
- Package Dependencies that needs to be resolved first:

**Comment by rth** [comment]
There is an existing issue about this in https://github.com/pyodide/pyodide/issues/1933. And more recently @joemarshall was looking into this, but it would most likely be packages built separately from the main distribution https://github.com/pyodide/pyodide/issues/3336

Closing as a duplicate, but don't hesitate to comment on linked issues.
