### ISSUE TITLE
lapack larfg function signature mismatch

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3379]
### To Reproduce

Paste the code below in [Pyodide console (latest)](https://pyodide.org/en/latest/console.html) (same result with stable):

```py
import numpy as np
from scipy.linalg.lapack import get_lapack_funcs

a = np.arange(16).reshape(4, 4)
a = a.T.dot(a)

larfg, = get_lapack_funcs(['larfg'], dtype='float64')
alpha, x, tau = larfg(a.shape[0]-1, a[1, 0], a[2:, 0])
```

yields a Pyodide fatal error:
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RuntimeError: null function or function signature mismatch
```

With debug symbols, the stack-trace in the browser console is:
```
pyodide.asm.js:5767 RuntimeError: null function or function signature mismatch
    at f2py_rout__flapack_dlarfg (00677c62:0xcd642)
    at fortran_call (0003e3ba:0x6642)
    at method_call_trampoline (pyodide.asm.js:9750:33)
    at _PyObject_MakeTpCall (pyodide.asm.wasm:0x1309ec)
    at call_function (pyodide.asm.wasm:0x1ecb7f)
    at _PyEval_EvalFrameDefault (pyodide.asm.wasm:0x1e9dad)
    at _PyEval_Vector (pyodide.asm.wasm:0x1e4de9)
    at PyEval_EvalCode (pyodide.asm.wasm:0x1e41b5)
    at builtin_eval (pyodide.asm.wasm:0x1e1558)
    at cfunction_vectorcall_FASTCALL (pyodide.asm.wasm:0x16c465)
```

Debugging with Chromium it seems like the function is called with 6 parameters:
```
call_indirect (param i32 i32 i32 i32 i32 i32) (result i32)
```
but the function is defined with 5 parameters
```
(func $dlarfg_ (;646;) (export "dlarfg_") (param $var0 i32) (param $var1 i32) (param $var2 i32) (param $var3 i32) (param $var4 i32) (result i32)
```

I am not too sure why it is called with 6 parameters, there are 5 parameters in `cython_lapack_signatures.txt`:
```
scipy/linalg/cython_lapack_signatures.txt:void dlarfg(int *n, d *alpha, d *x, int *incx, d *tau)
```

The only place in scipy I could find with 6 parameters is in a `.pyf` file:
```
scipy/linalg/flapack_other.pyf.src:subroutine <prefix>larfg(n, alpha, x, incx, tau, lx)
```

### Expected behavior

No error.

### Environment

- Pyodide Version: both stable and latest
- Browser version: not relevant I think 
- Any other relevant information:

### Additional context

This is an error I saw while looking at scipy.linalg test suite issues: https://github.com/lesteve/scipy-tests-pyodide/pull/2

**Comment by hoodmane** [comment]
Thanks for the report @lesteve! I'm so glad you're looking into these things, it's a lot of work...

> The only place in scipy I could find with 6 parameters is in a .pyf file:
> ```
> scipy/linalg/flapack_other.pyf.src:subroutine <prefix>larfg(n, alpha, x, incx, tau, lx)
> ```

I think that has got to be the problem. Probably patching out the extra `lx` parameter in this declaration should fix the error?

**Comment by ilayn** [comment]
This is my fault. And a very bad one I did during compiler silencing in https://github.com/scipy/scipy/pull/8300 almost a decade ago. I'll see if we can reverse it.

**Comment by lesteve** [comment]
@ilayn thanks! I guess if it took 7 years to be uncovered it's probably not that important :wink:

Let us know if you have suggestions on how to fix it. In particular does removing the `lx` parameter in the `.pyf` as mentioned in https://github.com/pyodide/pyodide/issues/3379#issuecomment-1361513180 sound like a reasonable direction to you? I have to admit I know very little about `.pyf` and Fortran in general.

Note that Pyodide has already quite a [few patches for Scipy](https://github.com/pyodide/pyodide/tree/main/packages/scipy/patches) already, so adding one more even if a bit hacky, is definitely not that bad ...

**Comment by ilayn** [comment]
Yes removal should be fine I'll open a PR when I have the chance asap.
