### ISSUE TITLE
Code creates Pyodide fatal error rather than Python exception that can be caught

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3382]
## 🐛 Bug

Some exceptions (I am guessing which are thrown from Cython or compiled code) creates Pyodide fatal errors rather than Python exception which can be caught.

### To Reproduce

```py
import numpy as np
from scipy.spatial.distance import cdist

out = np.ones((2, 2))
arr = np.array([[1, 2]])

try:
    cdist(arr, arr, out=out)
except ValueError:
    print('exception caught')
```

This creates a Pyodide fatal error. With debug symbols the stack-trace looks like this:
```
CppException std::invalid_argument: Output array has incorrect shape.
    at convertCppException (http://localhost:8000/pyodide.asm.js:5740:16)
    at API.fatal_error (http://localhost:8000/pyodide.asm.js:5758:17)
    at Module.callPyObjectKwargs (http://localhost:8000/pyodide.asm.js:4425:17)
    at Module.callPyObject (http://localhost:8000/pyodide.asm.js:4440:25)
    at wrapper (http://localhost:8000/pyodide.asm.js:9248:27)
```

Another similar one:
```py
from scipy.sparse._sparsetools import test_throw_error
try:
    test_throw_error()
except MemoryError:
    print('caught exception')
```

The code for `test_throw_error` is written in C https://github.com/scipy/scipy/blob/e2bb12727dad4c7c575abda22b459aeb35962ab8/scipy/sparse/sparsetools/csr.h#L1698-L1701:
```C
inline int test_throw_error() {
    throw std::bad_alloc();
    return 1;
}
```

Another one from Cython code:

```py
from scipy.signal import lombscargle

try:
    lombscargle(x=[1], y=[1, 2], freqs=[1, 2, 3])
except ValueError:
    print('caught exception')
```

Stack-trace with debug symbols:
```
CppException (anonymous namespace)::pythonic::types::ValueError: std::exception
    at convertCppException (http://localhost:8000/pyodide.asm.js:5740:16)
    at API.fatal_error (http://localhost:8000/pyodide.asm.js:5758:17)
    at Module.callPyObjectKwargs (http://localhost:8000/pyodide.asm.js:4425:17)
    at Module.callPyObject (http://localhost:8000/pyodide.asm.js:4440:25)
    at wrapper (http://localhost:8000/pyodide.asm.js:9248:27)
```

The exception is raised in Cython code https://github.com/scipy/scipy/blob/e2bb12727dad4c7c575abda22b459aeb35962ab8/scipy/signal/_spectral.pyx#L55-L56

### Expected behavior

This should catch the exception and print `exception caught`

### Environment

- Pyodide Version: both stable and latest
- Browser version: not relevant
- Any other relevant information:

### Additional context

I saw this kind of issues a few times in scipy test suite tests. Typically they arise in tests that check that code is raising an exception.

**Comment by hoodmane** [comment]
Probably all that needs to be done is to add:
```yaml
  cxxflags: -fexceptions
  ldflags: -fexceptions
```
to the meta.yaml file.
