### ISSUE TITLE
Bundle pyarrow or fastparquet

### ISSUE THREAD

**Issue by kuatroka** [pyodide/pyodide#3386]
Problem

Currently there seems to be no way to read parquet files through pandas with read_pandas as the engine needs to be specified. It can be either fastparquet or pyarrow. I tried to install it with pip, micropip or piplite but I'm getting an error that none of these packages has wheels.

Proposed Solution

Please bundle one of these engines directly to pyodide so we can import not only .csv, but also the much lighter on RAM files like parquet. Thanks

**Comment by hoodmane** [comment]
See also #2933.

**Comment by rth** [comment]
Yes, it's been a long-standing request. They are just not very easy to build packages. See https://github.com/pyodide/pyodide/issues/2933 (pyarrow) and https://github.com/pyodide/pyodide/issues/3170 (fastparquet which seems easier). Closing as a duplicate but don't hesitate to comment in one of the linked issues.
