### ISSUE TITLE
Statsmodels package causing crash of Chrome when loaded in webworker

### ISSUE THREAD

**Issue by JuliusSkrisa** [pyodide/pyodide#3395]
## 🐛 Bug

Chrome webview is crashing when statsmodels package is loaded in webworker on Android.

### To Reproduce

1. Create webworker and Load pyodide and statsmodels package in your webapp
2. Run any python code in the webworker
3. Interact with the app
4. Chrome webview will crash randomly
(not crashing at all when statsmodels is not loaded) - seems like a memory leak or issue with threading

### Expected behavior

Should not crash

### Environment

- Pyodide Version: 0.21.3
- Browser version: Chrome 108.0.5359.128 on Android 12
- Any other relevant information: Not happening on Chrome on Windows

**Comment by JuliusSkrisa** [comment]
seems to be related to https://github.com/pyodide/pyodide/issues/537 but in my case statsmodels its updated to version 0.13.2

**Comment by agriyakhetarpal** [comment]
Both `statsmodels` and SciPy underneath it are in a relatively better position these days, @JuliusSkrisa, and the Pyodide version is quite old as well, so I'll close this for now. We can reopen it if you continue to face this issue. Thanks for reporting! :)
