### ISSUE TITLE
`pyodide build` passes build location as backend argument

### ISSUE THREAD

**Issue by agoose77** [pyodide/pyodide#3415]
I ran into this in our CI: the source directory is being passed as an arg, which ultimately is interpreted as a `config-setting` instead of setting the cwd. This breaks our PEP517 build backend that doesn't expect this argument. I think we just want `os.chdir` here?

https://github.com/pyodide/pyodide/blob/e90154f3e22354a6104ec9c8a3e2ca1baaa2b085/pyodide-build/pyodide_build/cli/build.py#L140

**Comment by ryanking13** [comment]
Thanks for the report @agoose77. It seems like we didn't have a test for this.

**Comment by agoose77** [comment]
Would it be possible to make a new release of `pyodide-build`? We won't be able to upgrade to 0.22 until https://github.com/pyodide/pyodide/commit/76581a7d28322b789ecfb6c9d82e136c78063d56 makes it into `main` :)
