### ISSUE TITLE
Using `scipy.linalg.lapack.get_lapack_funcs` fails to resolve some symbols

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3416]
## 🐛 Bug

Using `scipy.linalg.lapack.get_lapack_funcs` fails to resolve some symbols. I am seeing similar things for a few different symbols, see https://github.com/lesteve/scipy-tests-pyodide/pull/2 for more details.

### To Reproduce

```py
import numpy as np
from scipy.linalg.lapack import get_lapack_funcs

np.random.seed(42)
dtype = np.float32
matrix_size = (3, 4)
geqrfp = get_lapack_funcs(('geqrfp'), dtype=dtype)

A = np.random.rand(*matrix_size).astype(dtype)
qr_A, tau, info = geqrfp(A)
```

Stack-trace with debug symbols:
```
TypeError: Cannot read properties of undefined (reading 'apply')
    at stubs.<computed> (pyodide.asm.js:6741:33)
    at sgeqrfp_ (00677c62:0xd99f7)
    at f2py_rout__flapack_sgeqrfp (00677c62:0x350f2)
    at fortran_call (0003e3ba:0x6642)
    at method_call_trampoline (pyodide.asm.js:1436:82)
    at _PyObject_MakeTpCall (pyodide.asm.wasm:0x1313a1)
    at call_function (pyodide.asm.wasm:0x1ed535)
    at _PyEval_EvalFrameDefault (pyodide.asm.wasm:0x1ea763)
    at _PyEval_Vector (pyodide.asm.wasm:0x1e579f)
    at PyEval_EvalCode (pyodide.asm.wasm:0x1e4b6b)
```

The following code from `pyodide.asm.js` fails at the `resolved.apply` call since `resolved` is undefined:
```js
var proxyHandler = {
  'get': function(stubs, prop) {
    // symbols that should be local to this module
    switch (prop) {
      case '__memory_base':
        return memoryBase;
      case '__table_base':
        return tableBase;
    }
    if (prop in asmLibraryArg) {
      // No stub needed, symbol already exists in symbol table
      return asmLibraryArg[prop];
    }
    // Return a stub function that will resolve the symbol
    // when first called.
    if (!(prop in stubs)) {
      var resolved;
      stubs[prop] = function() {

        // prop = "sgeqr2p_" when it fails
        if (!resolved) resolved = resolveSymbol(prop);
        // The next line fails since resolved = undefined
        return resolved.apply(null, arguments);
      };
    }
    return stubs[prop];
  }
};
```

### Expected behavior

No error.

### Environment

- Pyodide Version: stable (0.22) and latest
- Browser version: not relevant
- Any other relevant information:

**Comment by rth** [comment]
Thanks for the report @lesteve !

So if we use the excellent auditwheel-emscipten by @ryanking13,
```bash
wget https://cdn.jsdelivr.net/pyodide/v0.22.0/full/CLAPACK-3.2.1.zip
unzip CLAPACK-3.2.1.zip
pyodide audit exports clapack_all.so | grep geqrf
```
in this case we get,
```
│   │   Export(name='sgeqrf_', kind=<ExternType.FUNC: 0>, index=256),
│   │   Export(name='dgeqrf_', kind=<ExternType.FUNC: 0>, index=559),
│   │   Export(name='cgeqrf_', kind=<ExternType.FUNC: 0>, index=868),
│   │   Export(name='zgeqrf_', kind=<ExternType.FUNC: 0>, index=1209),
```
so `geqrf` is there but not `geqrfp`. 

If I search http://www.netlib.org/clapack/clapack.tgz (which should be CLAPACK-3.2.1) that function is not there. While it's present in [LAPACK 3.11.0](https://netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational_ga5dc72a0f55ff4c08f1a3596f56e04aaa.html). So my guess is something about our hack of adding these missing functions [here](https://github.com/pyodide/pyodide/blob/6bca0c6ace7575cbadb8aa95b5660e8b9b05dc99/packages/scipy/meta.yaml#L67) doesn't work as expected.

**Comment by lesteve** [comment]
Good news, it seems like this one does not exist anymore in the #3331 branch. Maybe OpenBLAS has more symbols somehow.

**Comment by lesteve** [comment]
I tried in https://pyodide.org/en/latest/console.html and this has been fixed by using OpenBLAS.
