### ISSUE TITLE
Add package: protobuf

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#3424]
## 🐍 Package Request

- Package Name and Version : protobuf / latest
- Package URL : https://github.com/protocolbuffers/protobuf/tree/v21.12/python
- Package Dependencies that needs to be resolved first: None?

It seems like this already works "out of the box", but it's just that they haven't published a pypi package specifically for the pure python implementation? I think the `protobuf` pypi package is for their C++ implementation? I'm not sure why they wouldn't publish two separate packages, but maybe it's quite rare for people to use the pure python implementation, since it's significantly slower.

I built the whl and made a quick demo and it seems to work fine:

* built whl: https://github.com/josephrocca/protobuf-pyodide/raw/main/demo/protobuf-4.21.12-py2.py3-none-any.whl
* working demo: https://josephrocca.github.io/protobuf-pyodide/demo/
* repo: https://github.com/josephrocca/protobuf-pyodide

## Code I used to build it:

```bash
git clone --branch v21.12 https://github.com/protocolbuffers/protobuf
cd protobuf

# pyodide setup:
pip install pyodide-build
git clone https://github.com/emscripten-core/emsdk
cd emsdk
pyodide config get emscripten_version  # this line is needed due to: https://github.com/pyodide/pyodide/issues/3430
./emsdk install $(pyodide config get emscripten_version)
./emsdk activate $(pyodide config get emscripten_version)
source emsdk_env.sh
cd ../

# Install `protoc` binary - https://askubuntu.com/questions/1072683/how-can-i-install-protoc-on-ubuntu-16-04/1157801#1157801
# CAUTION: Must be same version as the protobuf repo being built!
wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
sudo unzip -o protoc-21.12-linux-x86_64.zip -d /usr/local bin/protoc
sudo unzip -o protoc-21.12-linux-x86_64.zip -d /usr/local 'include/*'

# install bazel:
npm install -g @bazel/bazelisk

# build
cd python
pyodide build

# create test file:
wget https://gist.githubusercontent.com/josephrocca/f9184834444be2515b264aca2c9e7fde/raw/cc25a18b1e4d9a71bd99c8343bd31bfd43116e85/addressbook.proto
protoc -I=. --python_out=. addressbook.proto
# now you have `addressbook_pb2.py` in the the current working directory
```

## Code from demo:
```html
<script src="https://cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.js"></script>
<script type="module">
  window.pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");

  let tokenizerJsonText = await fetch("./addressbook_pb2.py").then(r => r.text())
  pyodide.FS.writeFile("./addressbook_pb2.py", tokenizerJsonText, { encoding: "utf8" });

  console.log(await pyodide.runPythonAsync(`
    import sys
    print(sys.version)

    import micropip
    await micropip.install('./protobuf-4.21.12-py2.py3-none-any.whl')

    import addressbook_pb2
    person = addressbook_pb2.Person()
    person.id = 1234
    person.name = "Jane Doe"
    person.email = "jdoe@example.com"
    phone = person.phones.add()
    phone.number = "555-4321"
    phone.type = addressbook_pb2.Person.HOME

    print(person.name)
    print(person.IsInitialized())

    try:
      person.no_such_field = 1   # raises AttributeError
    except AttributeError:
      print("nice")

    try:
      person.id = "1234"  # raises TypeError
    except TypeError:
      print("cool")
  `));
</script>
```

 * `addressbook.proto`: https://github.com/josephrocca/protobuf-pyodide/blob/main/demo/addressbook.proto
 * `addressbook_pb2.py`: https://github.com/josephrocca/protobuf-pyodide/blob/main/demo/addressbook_pb2.py

**Comment by ryanking13** [comment]
Does protobuf guarantee interoperability between versions? I once tried to build protobuf separately when I build opencv-python, but I found that the latest protobuf is not compatible with opencv-python, so I ended up using [embedded protobuf](https://github.com/pyodide/pyodide/blob/a916ea0b3421580fa0b09784940bbb2769529d3e/packages/opencv-python/cmake/build_args.sh#L39) inside opencv-python. (I haven't used protobuf much, so I might be wrong)

Since (for now) Pyodide contains only a single version of each package, if a version of protobuf we build is not compatible with some versions used in other packages, it won't be very useful.

**Comment by josephrocca** [comment]
@ryanking13 I was actually about to to ask about this because I noticed that [`onnx`](https://github.com/pyodide/pyodide/issues/3427) depends on a specific (and rather old) version of `protobuf`. Do you know how long it'll be until Pyodide will be able to have multiple package versions? Maybe still far away because I'm guessing this would involve properly integrating with PyPI? (but then I guess we wouldn't be able to rely on all package authors to go back and publish Pyodide variants of their package for every version number?)

**Comment by ryanking13** [comment]
>  Do you know how long it'll be until Pyodide will be able to have multiple package versions? Maybe still far away because I'm guessing this would involve properly integrating with PyPI?

I'm not sure but I don't think integrating with PyPI would happen in the near future. So for now the option is to build the required version of packages in a separate repo using out-of-tree build and load it.

By the way, thanks for reporting issues in our out-of-tree build! We don't have comprehensive test suites yet so it is really helpful.

**Comment by bitsondatadev** [comment]
@ryanking13, it looks like this is done? Should it be closed?
