### ISSUE TITLE
import ffi * is broken for 22.0+ 

### ISSUE THREAD

**Issue by zrothberg** [pyodide/pyodide#3432]
## 🐛 Bug

Can no longer call `from pyodide.ffi import *`
Traceback
```
  File "/lib/python3.10/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 312, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
  File "/home/pyodide/launchapp.py", line 1, in <module>
    from pyodide.ffi import *
AttributeError: module 'pyodide.ffi' has no attribute 'IN_BROWSER
```

### To Reproduce

`from pyodide.ffi import *
`
### Environment

- Pyodide Version: v0.22.0 and dev 
- Browser version: Chrome

### Additional context
Not sure if IN_BROWSER is supposed to be available in that package or not. This is the [commit](https://github.com/pyodide/pyodide/pull/3298/files#diff-d66f085dfec63b0802ed32af9c70f0ac5dd1bcf599805afa45fce94599517d1e) that broke it. There probably needs to be some tests added to make sure the import * works for all the modules that are defining `__all__`. Not sure what the proper correction is to the current package structure though. _core doesnt define it in its all and I am unsure if that is the actual bug.

**Comment by rth** [comment]
Thanks for the report! Yes, `IS_BROWSER` is missing in `pyodide._core.__all__` hence this error.

Maybe let's revert [this `*` import here](https://github.com/pyodide/pyodide/pull/3298/files#diff-d66f085dfec63b0802ed32af9c70f0ac5dd1bcf599805afa45fce94599517d1eR4) it feels rather brittle. With an explicit import, this would not have happened.

**Comment by hoodmane** [comment]
I am a bit bothered by the very large amount of boilerplate needed to add a new symbol to ffi: before the update we needed to repeat the name in six different places in three different files. Maybe there is a better way to handle this...

**Comment by zrothberg** [comment]
Are they being used programmatically or statically? If programmatic there are a few workarounds. I'm assuming its for the docs and not for mypy reasons.

**Comment by hoodmane** [comment]
It's for both the docs and mypy. Getting mypy to understand what's going on is indeed the tricky part.

**Comment by ryanking13** [comment]
Do we actually need both `pyodide._core` and `pyodide.ffi`? I think _core just propagates all variables to  ffi and users don't use _core directly. So perhaps we can merge those into a single file `ffi`?
