### ISSUE TITLE
Github release file description lacking in docs for v0.22

### ISSUE THREAD

**Issue by viblo** [pyodide/pyodide#3433]
## 📚 Documentation

I noted that in the recently released 0.22 version of Pyodide the text for GitHub releases is wrong: https://pyodide.org/en/stable/usage/downloading-and-deploying.html#github-releases 

It seems that now there are two files, `pyodide-0.22.0.tar.bz2` and `pyodide-core-0.22.0.tar.bz2`, but Im not sure when I need which file. It would be great if it was written down. In addition, maybe the next section in the documentation would also need to be updated? (https://pyodide.org/en/stable/usage/downloading-and-deploying.html#serving-locally)

**Comment by hoodmane** [comment]
Thanks for the report, this should indeed be updated. `pyodide` has all packages, `pyodide-core` has the minimal set of packages needed to run the Pyodide core test suite. The `pyodide-core` distribution is intended primarily for use in node.
