### ISSUE TITLE
distutils.tar is missing in npm version 0.22.

### ISSUE THREAD

**Issue by niowniow** [pyodide/pyodide#3446]
### To Reproduce

install pyodide in a webpack project and build it

```
npm install pyodide@0.22
npx webpack
```

It shows the following error message
> ERROR in unable to locate '.../node_modules/pyodide/distutils.tar' glob

### Expected behavior

npx webpack successfully runs.

### Environment

- Pyodide Version: 0.22
- Any other relevant information:

``` 
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Packages:
    string-replace-loader: ^3.1.0 => 3.1.0 
    webpack: ^5.75.0 => 5.75.0 
    webpack-cli: ^5.0.1 => 5.0.1 
```

### Additional context
A workaround is to use the distutils.tar from version 0.21.3

**Comment by ryanking13** [comment]
Yes, the name of the archive has been changed to distutils-1.0.0.zip. Note that you probably won't need to bundle distutils unless you use it.
