### ISSUE TITLE
Add react-py to Related Projects

### ISSUE THREAD

**Issue by elilambnz** [pyodide/pyodide#3447]
I'm proposing to add the npm package `react-py` as a related project to the documentation. `react-py` is a library that allows for easy integration of Pyodide in React applications. It provides convenient hooks for running Python code within a React context, making it a valuable addition for users who want to use Python in their React projects.

Here is the link to the repo: https://github.com/elilambnz/react-py and here are some examples of how it can be used: https://elilambnz.github.io/react-py.

### project/related-projects

```
[react-py](https://github.com/elilambnz/react-py) is a library that allows for easy integration of Pyodide in React applications. It provides convenient hooks for running Python code.
```

**Comment by rth** [comment]
Yes, sure. Please open a PR.
