### ISSUE TITLE
console.html: no keyboard on Android Firefox

### ISSUE THREAD

**Issue by mentalisttraceur** [pyodide/pyodide#3449]
## 🐛 Bug

When I try to use [the console.html page](https://pyodide.org/en/stable/console.html) in Android Firefox, the on-screen keyboard does not come up (no matter how long I wait or where I click on the console).

I'm guessing that the console HTML is not being marked as a text input in the most universal/standard way. If so, then this might also be an accessibility issue. If not, then maybe this is a Firefox issue. (I'll try to dig into this more when I have time.)

### To Reproduce

Open https://pyodide.org/en/stable/console.html on Android in Firefox.

### Expected behavior

Keyboard pops open just as it does on Chromium browsers.

### Environment

- Pyodide Version: any
- Browser version: Firefox on Android (any version that I've tried)

### Additional Context

Since almost all mobile browsers nowadays are based on Chromium/WebKit (and last I checked on iOS alternative browsers were *required* to use the built-in engine), Firefox on Android is one of the only ways to notice this.

**Comment by ryanking13** [comment]
Thanks for the report @mentalisttraceur! It seems like there was an issue in [JQuery Terminal](https://github.com/jcubic/jquery.terminal/issues/846) that we use, and updating the version would hopefully fix it.

**Comment by alexbodn** [comment]
it happens to me in Chrome for Android.
the keyboard tries to show, but it appears it cannot reduce the full screen taken by the terminal.

**Comment by hoodmane** [comment]
Yeah I have the same problem I think in both Android Chrome and Firefox.
