### ISSUE TITLE
Pandas produces recursion errors

### ISSUE THREAD

**Issue by ErikPartridge** [pyodide/pyodide#346]
When computing the rolling averages on a concatenated data set in pandas, pyodide appears to encounter errors of excessive recursion.

On Firefox the issue is: `InternalError: too much recursion`

On Chrome the issue presents as: `RangeError: Maximum call stack size exceeded`

I have confirmed this on the staging version of Iodide, running Pyodide 0.8.2: https://definitely-staging.iodide.io/notebooks/21/

In this case, I would expect pandas to not encounter a recursion issue. Interestingly, if the dataset is not concatenated this is not an issue. Additionally, if the data set is concatenated, but the mean is computed instead of the rolling mean, there is no issue as well.

**Comment by letmaik** [comment]
I see the same issue with https://github.com/baverman/flameprof.

Initially I was getting `RecursionError: maximum recursion depth exceeded` from Python, so I tried increasing the limit to the one from my desktop Python: `sys.setrecursionlimit(1000)`. With that, I get the error mentioned by @ErikPartridge.

**Comment by hoodmane** [comment]
Related: #821

**Comment by ryanking13** [comment]
This issue has been resolved by #2019. Closing.
