### ISSUE TITLE
Extras are being loaded, despite not being requested afaict

### ISSUE THREAD

**Issue by DavidMulder0** [pyodide/pyodide#3478]
## 🐛 Bug

```
const pyodide = await loadPyodide();
await pyodide.loadPackage("micropip");
const micropip = pyodide.pyimport("micropip");
await micropip.install('lxml');
```

Results in loading `beautifulsoup4, soupsieve, cssselect, html5lib, webencodings, six` as well.

Looking manually at https://pypi.org/pypi/lxml/json I see

```
requires_dist: [ 
  "cssselect (>=0.7) ; extra == 'cssselect'",
  "html5lib ; extra == 'html5'",
  "BeautifulSoup4 ; extra == 'htmlsoup'",
  "Cython (>=0.29.7) ; extra == 'source'"
]
```

which I understand to mean that those dependencies should only be installed if requested.

### Expected behavior

For extras not to be loaded unless specified.

### Environment

- Pyodide Version: v0.22.0

### Additional context

For that matter, no matter what I try the `Deps=False` option on `micropip.install` doesn't seem to stop installing the dependencies either (formats I tried were from js `micropip.install('lxml', false, false);` and `await micropip.install('lxml', {deps: false);` and from python `await micropip.install('lxml', deps=False)`). Only working solution I found is directly loading the wheel file (`await pyodide.loadPackage("https://cdn.jsdelivr.net/pyodide/v0.22.0/full/lxml-4.9.2-cp310-cp310-emscripten_3_1_27_wasm32.whl")`)

**Comment by hoodmane** [comment]
Thanks for the report. Pyodide's lock file system doesn't support extra requires. We should probably just remove these from the requirements file.
