### ISSUE TITLE
Issue in building rust-based packages in parallel

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3565]
We are having some issue when building multiple rust-based packages in parallel.

For example, see: https://app.circleci.com/pipelines/github/pyodide/pyodide/5328/workflows/a0ced892-ac1a-4519-984c-d98a84fabe29/jobs/66900

It is expected behavior since `rustup` was not designed for concurrent use (https://github.com/rust-lang/rustup/issues/988).

Some possible workarounds that I can think of are:

1. Add some logic to not build rust-baed packages in parallel
2. Create a fresh local rust build environment everytime when building rust-based package. I found a Python package called [rustenv](https://github.com/chriskuehl/rustenv), which is designed for that purpose. It is a ~150LoC script, which basically installs rust every time from `https://sh.rustup.rs` into a local directory.

I slightly prefer option 1, as we don't have to be responsible for installing build requirements. But I have no strong opinion.

**Comment by rth** [comment]
+1 for option 1 as well.
