### ISSUE TITLE
Allow lightweight building of pyodide-lock.json

### ISSUE THREAD

**Issue by bollwyvl** [pyodide/pyodide#3573]
## 🚀 Feature

Add a python library and CLI to generate a pyodide-compatible `repodata.json`.

### Motivation

On [JupyterLite](https://github.com/jupyterlite/jupyterlite/pull/978), I would like to allow site builders to generate `repodata.json` about arbitrary wheels. This would ease some complexity, as pre-indexed wheels could plug into the lovely auto-install-on-import feature.

At present, generating a Warehouse-like JSON blob is handled by the lightweight, and dependency-less, `pkginfo`.

Pulling in the full `pyodide-build` toolchain for this bit of functionality feels _really_ heavy... and straight up isn't going to happen inside a running `pyodide` runtime... which I'm keen to achieve in the not-too-distant future.

### Pitch

Separate out the [functions](https://github.com/pyodide/pyodide/blob/0.22.1/pyodide-build/pyodide_build/buildall.py#L548
) required to build a `repodata.json`.

Consumed as a library, this would ideally have a minimum of dependencies, and _really_ ideally just `stdlib`, and offer a convenience method that even handled I/O with stdlib:

```py
from pyodide_index import write_repodata_json
write_repodata_json("path/to/wheels/folder/")
```

As a CLI, mimicking `conda index`:

```bash
$> pyodide-index path/to/wheels/folder
Wrote 200 packages to path/to/wheels/folder/repodata.json
```

Ideally, this would _not_ incur the increasingly-deep `typer -> world+dog` toolchain, and instead just use `argparse`. Indeed, while the above _references_ some `pydantic.BaseModels`, the actual runtime types probably _aren't_ required.

### Alternatives

A less complex path would be to leave more of the data extraction to downstreams, but give them a way to test the behavior:

- make everything that goes into `repodata.json` a `pydantic.BaseModel`
  - most of the [outputs are `Any`](https://github.com/pyodide/pyodide/blob/2fb9440e91709fb84f73ff48dd7e36d911f9c838/pyodide-build/pyodide_build/buildall.py#L614) right now
- use pydantic's `.schema_json` to create a portable, versioned, annotated, but crucially _static_, `repodata.schema.json`
- publish this scheme somewhere predictable
  - even if just inside the published `.whl`
    - but ideally at a well-known location on the documentation site, perhaps annotated with [sphinx-jsonschema](https://sphinx-jsonschema.readthedocs.io)

An additional advantage of this approach would be the [typescript types](https://github.com/pyodide/pyodide/blob/2fb9440e91709fb84f73ff48dd7e36d911f9c838/src/js/load-package.ts#L101) could be generated from the schema, with a single source of truth for documentation, bound checking, etc.

### Additional context

As always, thanks so much for `pyodide` ! :heart:

In the near term, we'll probably vendor the few methods and validate them against `pyodide-cli`, but wanted to put some of the ideas while working with this out there.

**Comment by ryanking13** [comment]
Thanks for the idea @bollwyvl. I think we can start with defining the specification of `repodata.json`  format with pydantic and probably also generate docs from it.

**Comment by bollwyvl** [comment]
> with pydantic and probably also generate docs from it

Yay, _any_ schema/typings/docs is better than... `Any`!

`pydantic` is a fine path, as long as it doesn't require installing `cmake` to get to the current schema :laughing: .

One observed implementation detail that is actually _extremely_ convenient for my use case: the `file_name` can actually be an absolute URL, and it will be resolved properly, irrespective of the location of the  `repodata.json`. I feel like this is a good property to document, test, and maintain with e.g. `"format": "uri"`.

It would also be _lovely_ to tighten up the `packages` keys and `depends` items as being valid PEP 503 names, if possible... I've had to start applying that _everywhere_ as we try to run more arbitrary stuff.

`imports` is harder... I don't know of a spec for it, and _technically_ a package can make invalid names (e.g. `-`) that are `__import__`able.

**Comment by rth** [comment]
> Add a python library and CLI to generate a pyodide-compatible repodata.json.

Yes, I agree completely. I also run into this use case recently. 

I started a simple pydantic specification for the `pyodide-lock.json` (previously `repodata.json`) in https://github.com/rth/pyodide-utils. I couldn't find an existing package where it would be good to add this but I'm open to suggestions for the location (and also the package name). I can move it under this org once the name and location is validated.

I agree we need some lightweight tools to manipulate `repodata.json` without installing pyodide-build and all of it's requirements.  For the CLI, it could be directly added to pyodide-cli and depend on `pyodide-utils` (or a better-named package) not sure.

How did you see this @ryanking13 @hoodmane ?

**Comment by rth** [comment]
Similarly, some of the code that can be re-used between pyodide-build, auditwheel-emscripten and pyodide-pack could be moved to this library.   For instance, other functionality that could be useful for all of those could be,
 - a function that detects if a .so is a WASM file (https://github.com/pyodide/pyodide/pull/3927#issuecomment-1599511454)
 - a way to re-compute sha256 sums in `pyodide-lock.josn` once the wheels are modified in any way

**Comment by bollwyvl** [comment]
Yep, no update from my side: resolving this seems to be blocking even working around it on my `jupyterlite-pyodide-kernel` PR.

> pyodide-cli

Again, even _that_ is probably too heavy for my tastes, and have seen packages pin really hard on `typer` which make composing them complex... though there's no reason this package couldn't advertise the `pyodide-cli` entry_point, which _shouldn't_ trigger the hard dependency. But it really would be useful for this feature to not drag in any more than it must... even if that means writing a little stdlib `argparse`.

> simple pydantic specification

... and again, `pydantic` is... fine... but about to go through some heartache with a major version and `rust` build chain changes, and inevitably someone will end up on the wrong side of the compatibility window. Similarly `jsonschema`, which has started replacing some of _its_ plumbing with `rust`, but in a more modular fashion... but it's going to be bumpy.

All that being said, I think the advantage to dumb schema are still quite siginificant, even if it (and maybe a dataclass/namedtuple scaffold) is generated at _publishing time_ from `pydantic` models, as schema-based validation can be made opt-in.

> the package name

Well, if generates `pyodide-lock.json`, then... maybe `pyodide-lock`, which is also in line with [conda-lock](https://github.com/conda/conda-lock). Note that _that_ repo shows some of the issues that feature- and dependency creep can have on an otherwise simple mission: it supports about 10 input file formats, just as many metadata sources, a couple output file formats, installing multiple package managers, and vendors another couple... I would again plead for keeping the pyodide version as simple-as-is-snake-humanly possible, ideally only python 3.8+ (or, int a pinch, 3.10+) stdlib and `packaging` or whatever is required to handle all the edge cases of the evils that will be stuffed into wheels.

**Comment by ryanking13** [comment]
Yeah, I'm +1 with moving some features of pyodide-build to other packages like pyodide-pack, pyodide-utils, pyodide-lock. auditwheel-emscripten, etc, so it they can be reused in other projects.

> Again, even that is probably too heavy for my tastes, and have seen packages pin really hard on typer which make composing them complex

Probably we can make `pyodide-cli` an optional dependency of `pyodide-utils`, so it can be installed with `pip install pyodide-utils[cli]`.

**Comment by rth** [comment]
Thanks, everyone for your feedback!

In the end, naming wise I went for https://github.com/pyodide/pyodide-lock as it's indeed a more specific name than `pyodide-utils`. I have opened several follow up issues,
 - Generate JSON Schema for `pyodide-lock.json`  (https://github.com/pyodide/pyodide-lock/issues/3)
 - Design CLI API for `pyodide lock` (https://github.com/pyodide/pyodide-lock/issues/4)
 - pyodide-lock.json with absolute URLs (https://github.com/pyodide/pyodide/issues/3943)
 - Download pyodide-lock.json with results of micropip.freeze() (https://github.com/pyodide/micropip/issues/68)

I'm going to close this issue, let's continue the discussion there in more details.
