### ISSUE TITLE
Pyodide Fails to Build on MacOS

### ISSUE THREAD

**Issue by Grey41** [pyodide/pyodide#3595]
A TypeScript error is raised when I try to build natively.

I am using a Silicon - ARM - processor to compile Pyodide. Although the Docker build compiles successfully, it takes a very long time. When I try to compile natively instead, I get the following output:

```
./src/js/pyodide.ts → dist/pyodide.mjs...
[!] (plugin Typescript) TS1134: Variable declaration expected.
src/js/pyproxy.gen.ts (57:13)

57 declare var (1 << 8): number;
               ~
```

How can I fix this?

**Comment by hoodmane** [comment]
Make sure the sed on your path is gnu sed not apple sed

**Comment by Grey41** [comment]
Thank you! After installing `gnu-sed` with Homebrew, I needed to configure the PATH.

```
PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"
```

Now it works.

**Comment by hoodmane** [comment]
I'm thinking we should add a building with m1 section to the docs mentioning that you need gnu sed and gnu patch and you need Rosetta since node 14 can't be built for arm.

**Comment by rth** [comment]
The first part is already indicated in https://pyodide.org/en/stable/development/building-from-sources.html#using-make if one clicks on the MacOS tab. But yes our how-to-build docs is  still a bit complex, it took me a minute to find it even though I knew it was somewhere in the docs.

**Comment by Grey41** [comment]
Yes, it was mentioned in the docs after all. I'm still having problems though. It seems like they have moved the system headers in `/Library/Developer/CommandLineTools`. I also had to install extra packages like `wget` and `pkg-config`, but they are already listed in the [Dockerfile](https://github.com/pyodide/pyodide/blob/main/Dockerfile).

By the way, there's a spelling mistake on the [Building from sources](https://pyodide.org/en/stable/development/building-from-sources.html#using-make) page - it should be `automake` not `automaker`.

**Comment by ryanking13** [comment]
Perhaps we should use GNU / BSD compatible syntax
