### ISSUE TITLE
Upgrade `packaging` to v23.0

### ISSUE THREAD

**Issue by arpitnath** [pyodide/pyodide#3596]
Pyodide currently utilizes version 21.3 of the Python Packaging library for packaging Python modules. However, the library's latest version, 23.0, has been released by PyPA/Packaging. Upgrading to this version will improve compatibility with other Python packages that have already adopted v22 or above, allowing Pyodide to better integrate with the broader Python ecosystem.

**Comment by rth** [comment]
@ryanking13 just made a release of micropip which would allow us to use latest `packaging` version https://github.com/pyodide/micropip/pull/53

@arpitnath Would you be interested in making a PR updating the packaging version (and also the version micropip)?

**Comment by arpitnath** [comment]
Sure @rth 
Have raised a PR for the same: https://github.com/pyodide/pyodide/pull/3605

**Comment by ryanking13** [comment]
Closing as resolved by #3605. Thanks again @arpitnath!
