### ISSUE TITLE
Navigation for documentation site isn't responsive between 959px and 768px

### ISSUE THREAD

**Issue by LadyBluenotes** [pyodide/pyodide#3603]
## 🐛 Bug

When the navbar is below 970px the primary side bar does not expand. When toggling secondary sidebar, entire screen is greyed out so finding it is difficult.

### To Reproduce

Using screen sizes between ~970 and 768px.

### Expected behaviour

Should follow suit of navbars under 768px.

**Comment by ryanking13** [comment]
Thanks for the report @LadyBluenotes! I think there was an issue in one of our doc dependencies.
I rebuilt the stable version docs and the issue seems resolved. Please don't hesitate to comment if you still experience the same issue.
