### ISSUE TITLE
update cryptography to >=39

### ISSUE THREAD

**Issue by zalmane** [pyodide/pyodide#3610]
Cryptography 38 now has a security advisory:
```
pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8.1-39.0.0 are vulnerable to a security issue. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20221213.txt and https://www.openssl.org/news/secadv/20230207.txt.
```

## 🐍 Package Request

- Package Name and Version :
- cryptography >39.0.0

What is the plan to upgrade cryptography 38 to >39?

**Comment by hoodmane** [comment]
Well we usually bump package versions before making a release. Probably we should add wasm32-emscripten to cryptography CI so that you can get a newer wheel from them.

**Comment by ryanking13** [comment]
Note that we don't statically link OpenSSL to cryptography. Anyway, we need to update our OpenSSL to 1.1.1t.

**Comment by spicy-sauce** [comment]
I see that cryptography is updated in the packages with version 39.0.2:
https://github.com/pyodide/pyodide/blob/main/packages/cryptography/meta.yaml

But I'm getting thid:
ValueError: Can't find a pure Python 3 wheel for 'cryptography>=39.0.1'.

Is it related to this issue or is it something else?
I also went over this:
https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package

I see that this package does not contain the `py3-none-any.whl` in its `download files` tab, so I wonder how was it delivered in `pyodide` then? Am I missing something? 

Thanks!

**Comment by ryanking13** [comment]
@spicy-sauce Which version of Pyodide are you using? We updated cryptography version to 39.0.2 at Pyodide 0.23.0.

**Comment by hoodmane** [comment]
I guess we can close this issue as completed by #3685 while we're at it.

**Comment by spicy-sauce** [comment]
> @spicy-sauce Which version of Pyodide are you using? We updated cryptography version to 39.0.2 at Pyodide 0.23.0.

I'm using pyodide 0.24.0 and saw that cryptography was updated to this version but still getting the error I shared, any idea?

**Comment by ryanking13** [comment]
@spicy-sauce Hmm, that's strange. Could you provide the code to reproduce the bug?

**Comment by spicy-sauce** [comment]
> @spicy-sauce Hmm, that's strange. Could you provide the code to reproduce the bug?

```javascript
  useEffect(() => {
    const run = async () => {
      // const out = await runScript(scriptText);
      pyodide = await window.loadPyodide();
      await pyodide.loadPackage("micropip");
      const micropip = await pyodide.pyimport("micropip");
      await micropip.install("setuptools");
      await micropip.install("datayoga_core==1.94.0");
      await micropip.install("jsonschema");
      await micropip.install("sqlite3");
      pyodide.runPython(`
      import sys
      def reformat_exception():
          return str(sys.last_value)
      `);
      pyReformatException.current = pyodide.globals.get("reformat_exception");

      // Get datayoga_core version
      dyVersion.current = await pyodide.runPython(`
          import pkg_resources
          pkg_resources.get_distribution("datayoga_core").version
      `);

      pyTransform.current = await pyodide.runPythonAsync(dyCode);
      setIsLoading(false);
      showValue();
    };
    run();

    const storedJobEditorValue = localStorage.getItem("jobEditorValue");
    if (storedJobEditorValue) setJobEditorValue(storedJobEditorValue);

    const dataJobEditorValue = localStorage.getItem("dataEditorValue");
    if (dataJobEditorValue) setDataEditorValue(dataJobEditorValue);
  }, []);
```

**Comment by ryanking13** [comment]
Sorry but I can't reproduce the error in Pyodide 0.24.0 console.

What happens if you do

```python
await micropip.install("cryptography")
import cryptography
print(cryptography.__version__)
```
?

**Comment by spicy-sauce** [comment]
I'm getting 38.0.4 while I would expect to get 39.0.2

**Comment by spicy-sauce** [comment]
Yes, that was the issue, my bad, thanks for your assistance.
