### ISSUE TITLE
`Array.from` in Python Causes Syntax Error

### ISSUE THREAD

**Issue by JeffersGlass** [pyodide/pyodide#3615]
## 🐛 Bug

The [Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) static method (alternative constructor) throws a syntax error when used in Python.

### To Reproduce

The following code throws a SyntaxError: 

```python
<script>
  async function main() {
    let pyodide = await loadPyodide();
    pyodide.runPython(`
      from js import Array
      a = Array.from([1,2,3])
      print(a)
      `);
  };
  main();
</script>
```
```
...
 File "/lib/python3.10/_pyodide/_base.py", line 144, in _parse_and_compile_gen
 mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
  File "<exec>", line 3
    a = Array.from([1,2,3])
              ^^^^
SyntaxError: invalid syntax
```

However, the following code works:
```python
<script>
  async function main() {
    let pyodide = await loadPyodide();
    const generator = pyodide.runPython(`
      from js import Array
      fromFunc = getattr(Array, 'from')
      b = fromFunc([4,5,6])
      print(b)
      `);
  };
  main();
</script>
```

### Expected behavior

This behavior is, in a way, consistent with Python, where directly setting to or accessing the `from` attribute of an object is also a syntax error, but you can create one with `setattr` and `getattr` (or similar):

```python
class A():
        ...

#SyntaxError
A.from = lambda: print("Whoops") 

#Works
setattr(A, 'from', lambda : print("from() was called!"))
getattr(A, 'from')()
```

But it's unfortunate that the simple Array.from() method is made more cumbersome to use by the Python keyword. As for the solution? I don't know - could be something like detecting properties on JS objects that are Python keywords, and creating an additional property for them? (`_from`?). Or maybe just highlighting the issue of JS objects with properties that are Python keywords is enough.

Forgive me if that is already documented somewhere, I couldn't find a specific reference to it.

### Environment

- Pyodide Version 0.22.1
- Browser version Chrome Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by rth** [comment]
As you mentioned, `from` is a [reserved keyword](https://stackoverflow.com/a/22864250/1791279) in Python and cannot be used as a method name. I'm not convinced about changing Python parsing rules, even if it is possible (and it [sounds rather difficult](https://stackoverflow.com/a/64397374/1791279)), to have better JS FFI integration.

We had a related discussion before, I believe without any conclusion. Remapping `from` to `_from` also creates its own problems and nonstandard behavior: for instance,  a JS object can very well contain both `_from` and `from` attributes/methods, and the list of restricted keywords is rather long. 

So maybe using `getattr` is still the best possible outcome, even if it's slightly more verbose.

But in any case, yes, we should add this to the FAQ and to the type translations page.

**Comment by hoodmane** [comment]
I think there is something we should do here: let's make a set of reserved keywords and add the following logic to the `getattr` impl:
```py
if not js_hasattr(obj, key) && key.endswith("_") && key in reserved_keywords:
   return getattr(obj, key[:-1])
```

**Comment by hoodmane** [comment]
We already remap `finally_` to `finally`. We don't even need to add all of them, we can just put in new ones as the need arises.

**Comment by rth** [comment]
Indeed, that sounds familiar but after quickly looking I couldn't find any docs about it )

I'm not opposed to doing that as long as we are confident it would have no weird side effects or inconsistent behavior.

 Did we document this somewhere for `finally` as it would be a bit of a double exception: 
 - rule: method names are the same in JS and Py
 - exception: except for reserved keywords to which we add a trailing `_` in Python
 - exception to the exception: except if the method corresponding to the keywords with a trailing `_` already exists.
 
 Also,
 - what would happen if we call `create_proxy` on such an object in JS, does it mean that creating a proxy in JS would also effectively create this alias even in JS
 - does it mean that in Python there are method names not in `__dir__` or do we change `__dir__` also ?
 - what would happen if one calls `delattr(obj, finally)`? It would produce an attribute error even though the method actually exist? Is this a reasonable behavior for Python?

**Comment by hoodmane** [comment]
I edited numbers into your reply so that I can respond to it.

1. Calling `create_proxy` on a `JsProxy` isn't recommended because it creates a triple proxy which is probably never what you want. But yes.
2. We should change `__dir__` too.
3. Yes, we can do it statically for all things that have static types. In the case of `Array.from` there would be a typeshed for `Array.from_`. We can't typeshed `Array.from` anyways.
4. `delattr(x, "finally_")` has the same logic: if it has a `finally_` attribute, delete that. If no `finally_` attr, check for a `finally` attr if present delete it. Otherwise attribute error.
5. The JavaScript parser is more robust so it doesn't have this problem.

**Comment by rth** [comment]
OK sounds good then.
