### ISSUE TITLE
CircleCI fails to checkout repo on main branch

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3623]
Works fine on branches / prs. Because of this our latest console hasn't been updated since February 20th.

**Comment by rth** [comment]
OK, I manually added yet another SSH key and it builds now on main. Or at least that error isn't there anymore.

**Comment by ryanking13** [comment]
Thanks, Roman! I still don't understand why it failed...

**Comment by rth** [comment]
No idea what was happening either. There is one remaining test failure https://github.com/pyodide/pyodide/pull/3590#issuecomment-1453171028 but otherwise it looks good.

**Comment by hoodmane** [comment]
We're also getting the following failure a lot:
```
src/tests/test_typeconversions.py:590: in test_wrong_way_track_proxies
    to_js(x, pyproxies=Object.new())
E   SystemError: error return without exception set
```
