### ISSUE TITLE
Customizing python_stdlib.zip

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3632]
Now that the stdlib is in python_stdlib.zip with https://github.com/pyodide/pyodide/pull/3582 (thanks again @ryanking13 !) the question is what could be the API to customize this file. 

For instance, in pydide-pack I would like to be able to customize what is put into the stdlib after repacking. There are several options,
 1. have a link to the stdlib in the `repodata.json`: it makes sense, but is problematic if one want to customize this without re-deploying a separate `repodata.json`
 2. have an option in `loadPyodide` with an optional URL to the stdlib. Either a) extending `fullStdLib: bool | str` to support URLs or b) adding yet another parameter there
 

WDYT?

**Comment by ryanking13** [comment]
I like option 2, so people can provide their custom version of stdlibs. Some people might even want to put all third-party packages they use into a zipfile.

I was thinking of providing a compiled version of stdlib (e.g. python_stdlib_pyc.zip), and adding a parameter in `loadPyodide` to select which version of stdlib to use. But if we are going for option 2, then probably we won't need to add an extra parameter.
