### ISSUE TITLE
Deploy of pyodide-py 0.22.1 failed

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3643]
@rth @ryanking13 looks like some sort of permissions error?
https://github.com/pyodide/pyodide/actions/runs/4009744299/jobs/6885453512

**Comment by hoodmane** [comment]
Also, I seem to have never accepted the invitation to join the pyodide-py project on pypi, so @rth if you could resend would apprecaite.

**Comment by rth** [comment]
> like some sort of permissions error?

Normally we are now using per PyPI project tokens, so it looks like it used a token for a different PyPI project and that failed.  We might need to update [the docs](https://github.com/pyodide/internal/blob/main/credential-management.md#pypi). Or maybe we should re-evalute that, but anyway we shouldn't use dev token that allows to access to all PyPI projects one has access to as if one such token is compromised everything would be.

> could resend would appreciate.

Yes, resent the invites for pyodide-py, pyodide-cli and micropip.

**Comment by ryanking13** [comment]
I think we forgot to backport https://github.com/pyodide/pyodide/pull/3412 when making 0.22.1 release.
