### ISSUE TITLE
 0.23 release

### ISSUE THREAD

**Issue by joemarshall** [pyodide/pyodide#3666]
It would be nice to have a release with python 3.11

What's the current status of this - are there any blockers still?

**Comment by hoodmane** [comment]
We had a discussion about this and decided that we will release 0.23.0 after we merge #3508 and #3544, hopefully next week.

**Comment by rth** [comment]
@hoodmane any chance you would have the bandwidth for a review of https://github.com/pyodide/pyodide/pull/3701 and/or https://github.com/pyodide/pyodide/pull/3702. They should be both relatively straightforward.

I can do the rest of the release process.
