### ISSUE TITLE
DOCS Suggestion: Add a link to GitHub

### ISSUE THREAD

**Issue by subwaymatch** [pyodide/pyodide#3686]
### 📌 Summary

Most documentation sites have a link to their GitHub repositories. I believe the [Pyodide Docs site](https://pyodide.readthedocs.io/) doesn't have a GitHub link in an easily detectable place. Adding a link to the GitHub repository in the site header will improve the developer experience. 😀

### 🖼 Screenshots

**Current**: No link to GitHub

![image](https://user-images.githubusercontent.com/1064036/227098342-01ac593b-77f7-4fbf-a7c3-02e7e7d1338d.png)

**Suggested Change**: add a GitHub link

![image](https://user-images.githubusercontent.com/1064036/227097610-a2142280-65c2-438e-be75-aa00a16b80f4.png)

### 💻 Sample Code

I was looking to find the relevant template file to edit so that I can add the link and submit a PR, but I wasn't able to locate the file. If you let me know which file to edit, I will submit a PR. If the template is hosted on [https://readthedocs.org/](https://readthedocs.org/) and can't be edited on this repository, I will just leave this as a suggestion here. Below is a sample snippet to add the link using the same set of icons as the other ones in the header.

**Before**: No GitHub link/icon

```html
<div class="article-header-buttons">
    <button onclick="toggleFullScreen()" class="btn btn-sm" data-bs-placement="bottom" data-bs-toggle="tooltip" aria-label="Fullscreen mode" data-bs-original-title="Fullscreen mode">
        <span class="btn__icon-container">
            <i class="fas fa-expand"></i>
        </span>
    </button>
    <!-- CODE TRUNCATED FOR SIMPLICITY -->
</div>
```

**After**: Use FontAwesome's GitHub icon to match the styles of other icons

```html
<div class="article-header-buttons">
    <!-- USING FONT AWESOME'S GITHUB ICON -->
    <a class="btn btn-sm" href="https://github.com/pyodide/pyodide/" title="Pyodide GitHub Link">
        <span class="btn__icon-container">
            <i class="fa-brands fa-github"></i>
        </span>
    </a>
    
    <button onclick="toggleFullScreen()" class="btn btn-sm" data-bs-placement="bottom" data-bs-toggle="tooltip" aria-label="Fullscreen mode" data-bs-original-title="Fullscreen mode">
        <span class="btn__icon-container">
            <i class="fas fa-expand"></i>
        </span>
    </button>
    <!-- CODE TRUNCATED FOR SIMPLICITY -->
</div>
```

**Comment by ryanking13** [comment]
Sounds good to me. It seems like sphinx-book-theme that we use [has an option](https://sphinx-book-theme.readthedocs.io/en/latest/components/source-files.html) for that. Could you open a PR?

**Comment by subwaymatch** [comment]
@ryanking13 Thank you for the pointer! I've created a PR.
