### ISSUE TITLE
CDN wheel compression not applied

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3687]
> OK, so the uploaded wheels are indeed uncompressed but so far the MIME type returned by the CDN is still octet-stream and the compression is not applied. I need to look into it.

_Originally posted by @rth in https://github.com/pyodide/pyodide/issues/3667#issuecomment-1477760076_
            
I'm opening this to make sure we don't forget this before releasing 0.23.0

**Comment by rth** [comment]
So indeed the content-type is not correctly applied,
```
aws s3api head-object --bucket pyodide[..] --key dev/full/numpy-1.24.2-cp311-cp311-emscripten_3_1_32_wasm32.whl
{
    "AcceptRanges": "bytes",
    "LastModified": "Fri, 24 Mar 2023 05:45:42 GMT",
    "ContentLength": 3012139,
    "ETag": "\"ee0cd032415368b5ee863b2bcb9166f2\"",
    "CacheControl": "max-age=3600, public",
    "ContentEncoding": "gzip",
    "ContentType": "binary/octet-stream",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```
Maybe there was I was misusing multiple includes/excludes in the AWS CLI command. Will try to fix it later today.

**Comment by rth** [comment]
I confirm that it works as expected now.
