### ISSUE TITLE
cmake FindBoost unable to find Boost in pyodide build

### ISSUE THREAD

**Issue by tomjakubowski** [pyodide/pyodide#3689]
## 🐛 Bug

I'm working adding Pyodide support to a Python module which uses cmake and Boost. On my machine :tm:, `pyodide build`, fails in cmake at `find_package(Boost REQUIRED)`, where the pypa build (`python -m build --wheel` succeeds. 

### To Reproduce

Small repo which reproduces the problem as minimally as I could: https://github.com/tomjakubowski/pybind11_cmake_example

* on the [pyodide](https://github.com/tomjakubowski/pybind11_cmake_example/tree/pyodide) branch, both `python -m build --wheel` and `pyodide build` succeed 

* on [pyodide-boost-broken](https://github.com/tomjakubowski/pybind11_cmake_example/compare/pyodide-boost-broken), with a call to `find_package(Boost REQUIRED)` added to CMakeLists.txt, the pypa build succeeds, but the pyodide build fails due to not finding Boost:

```
CMake Error at .venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  .venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  .venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
  CMakeLists.txt:5 (find_package)
```

### Expected behavior

I'd expect the pyodide build to succeed because the pypa native wheel build does 

### Environment

- pyodide-build         0.22.1, pyodide-cli           0.2.3
- Environment: macOS, Boost installed to /opt/homebrew (NB: setting BOOST_ROOT, BOOST_INCLUDE_DIR, etc. to a hard-coded value doesn't fix the issue)

**Comment by ryanking13** [comment]
You need to:

1. build WASM version of libboost
2. set [`CMAKE_FIND_ROOT_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH.html) to point to the location of the directory that libboost is installed, so that `find_package` can search the library.

**Comment by agriyakhetarpal** [comment]
This issue has been open for a while, and we have some packages that use Boost being built both in-tree and out-of-tree which work successfully. The newer versions of `pyodide build` should work better and the instructions posted by Gyeongjae above are sufficient. So, I'll close this issue for now. Thanks for reporting!
