### ISSUE TITLE
Fix test_js_stackframes[firefox] / reapply esbuild

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3706]
Opening an issue to not forget to fix ` test_js_stackframes[firefox]` following  https://github.com/pyodide/pyodide/pull/3679

For now, I'm going to xfail it, as I'm not sure what is the best fix for it and it makes CI in other PRs fail.

Before that PR  in the result of the test (before applying `normalize_tb`) we had,
```
(Pdb) for row in res[: len(frames)]: print(row)
['<exec>', 'e']
['http://127.0.0.1:42119/test.html', 'd4']
['http://127.0.0.1:42119/test.html', 'd3']
['http://127.0.0.1:42119/test.html', 'd2']
['http://127.0.0.1:42119/test.html', 'd1']
['http://127.0.0.1:42119/pyodide.asm.js', 'runPython']
['/lib/python311.zip/_pyodide/_base.py', 'eval_code']
['/lib/python311.zip/_pyodide/_base.py', 'run']
['<exec>', '<module>']
['<exec>', 'c2']
['<exec>', 'c1']
['http://127.0.0.1:42119/test.html', 'b']
['http://127.0.0.1:42119/pyodide.asm.js', 'pyimport']
['/lib/python311.zip/importlib/__init__.py', 'import_module']
```
after the PR we have,
```
['<exec>', 'e']
['/lib/python311.zip/_pyodide/_base.py', 'eval_code']
['/lib/python311.zip/_pyodide/_base.py', 'run']
['<exec>', '<module>']
['<exec>', 'c2']
['<exec>', 'c1']
['/lib/python311.zip/importlib/__init__.py', 'import_module']
['<frozen importlib._bootstrap>', '_gcd_import']
['<frozen importlib._bootstrap>', '_find_and_load']
['<frozen importlib._bootstrap>', '_find_and_load_unlocked']
```

so it's rather similar but shifted a bit and we might need to adapt `normalize_tb` to make it match to the expected output. However, I'm a bit concerned that `pyodide.asm.js` is no longer in the traceback  (which was rather useful for debugging). Any ideas why or how to re-enable it? Because it looks like it is present in Chrome still.  And BTW we xfail that test for safari. 

cc @hoodmane  @WebReflection

**Comment by hoodmane** [comment]
Yeah we also don't want the frozen importlib bootstrap frames...

**Comment by WebReflection** [comment]
@rth I am afraid I am not sure what is that test about but if something is missing and it was desirable I suggest to revert that PR and find out what should be done to have all the things in it. If by *eslint* you meant *esbuild* I think I've compared the final bundle size and looked very similar in size, I'd be surprise if the `asm` is fully gone, as opposite of being embedded within the module differently ... but you two know better than me here.

**Comment by hoodmane** [comment]
Well in particular remember that in chrome the stack frame _didn't_ change, only in firefox. So it's something a bit weird.

**Comment by rth** [comment]
Reverted in https://github.com/pyodide/pyodide/commit/bce105bd6901a54e50100de400bd6ba49158bd78 for now. We can look into it once the release is done.

**Comment by rth** [comment]
Resolved in https://github.com/pyodide/pyodide/pull/3720
