### ISSUE TITLE
Broken pyodide build /abs/path/to/module in 0.23.0

### ISSUE THREAD

**Issue by szabolcsdombi** [pyodide/pyodide#3722]
## 🐛 Bug

My build pipeline started failing after upgrading to 0.23.0.
It complains about the `PYODIDE_EMSCRIPTEN_VERSION` env variable if the cwd is different from the `[SOURCE_LOCATION]` argument.

I used to build my extensions with an absolute path to them:

```
pyodide build /abs/path/to/module
```

If the cwd is changed to `/abs/path/to/module` then the Key error for the `PYODIDE_EMSCRIPTEN_VERSION` is not longer present. And the very same command (with the abs path in the arguments) is executed, the build passes.

Here is the stack trace:

```
#0 0.664 │ /usr/local/lib/python3.11/site-packages/pyodide_build/common.py:199 in       │
#0 0.664 │ get_make_flag                                                                │
#0 0.664 │                                                                              │
#0 0.664 │   196 │   │   SIDE_MODULE_CFLAGS                                             │
#0 0.664 │   197 │   │   SIDE_MODULE_CXXFLAGS                                           │
#0 0.664 │   198 │   """                                                                │
#0 0.664 │ ❱ 199 │   return get_make_environment_vars()[name]                           │
#0 0.664 │   200                                                                        │
#0 0.664 │   201                                                                        │
#0 0.664 │   202 def get_pyversion() -> str:                                            │
#0 0.664 ╰──────────────────────────────────────────────────────────────────────────────╯
#0 0.664 KeyError: 'PYODIDE_EMSCRIPTEN_VERSION'
```

### To Reproduce

Uncomment the `WORKDIR /zengl/` to get the same build passing.

```Dockerfile
FROM python:3.11.2
RUN python3 -m pip install pyodide-build==0.23.0
RUN git clone https://github.com/emscripten-core/emsdk.git &&\
    /emsdk/emsdk install `pyodide config get emscripten_version` &&\
    /emsdk/emsdk activate `pyodide config get emscripten_version`

RUN wget -q https://f003.backblazeb2.com/file/zengl-data/examples/web-example-assets.tar.gz

RUN git clone https://github.com/szabolcsdombi/zengl /zengl
# WORKDIR /zengl/
RUN echo 'source /emsdk/emsdk_env.sh && pyodide build /zengl/' | bash
```

### Expected behavior

the CWD should not affect the lookup of the env variables.
the CWD should not affect the build when an absolute path is given.

### Environment

- Pyodide Version 0.23.0
- Browser version not relevant
- Any other relevant information:
- pyodide-build==0.23.0
- emscripten_version 3.1.32

Build environment: Docker official Python 3.11.2 image

**Comment by rth** [comment]
Thanks for the report. Yes, sounds indeed like a regression.

**Comment by hoodmane** [comment]
I think this is now the desired behavior because out of tree builds are preferred. @ryanking13 intentionally changed this in #3544. If you want to use in tree Pyodide to build packages outside of the source tree you should set `PYODIDE_ROOT` explicitly. Otherwise you should `pip install pyodide-build` and use out of tree builds.

**Comment by hoodmane** [comment]
Actually I take it back this isn't reasonable as an expected behavior @ryanking13 because they explicitly installed `pyodide-build` in tree. We need to detect where they installed the package from not where their package lives in the file tree. I think this is a job for `importlib.metadata`.

**Comment by ryanking13** [comment]
Hmm, this is strange. I think PYODIDE_ROOT is correctly set because if it is not set correctly, then `get_make_environment_vars()` should fail since it can't find Makefile.envs.

Then the problem is that `get_make_environment_vars()` isn't setting the environment variables correctly for some reason...

**Comment by ryanking13** [comment]
Oh, okay. I thought that subprocess.run would raise an exception when it gets a non-zero return code, but it doesn't. Then definitely PYODIDE_ROOT is not set correctly.

**Comment by szabolcsdombi** [comment]
The original [Dockerfile](https://github.com/szabolcsdombi/zengl/blob/5e443429d3706bb95a423cb9b1591bbca335b94d/examples/webgl/Dockerfile) is a bit more complicated. Then the simplified example above.

I am linking it here because I removed the `echo 'source ...' | bash` weird looking line from it.
It just looked odd and I tought it might actually contribute to the issue, but it did not.

In my current dockerfile I set the ENV manually. Fixed all the versions explicitly. And the same problem persists.
In my case if I remove the leading cd `/path/to..../` parts the build fails.

**Comment by szabolcsdombi** [comment]
I have tried to set the `PYODIDE_EMSCRIPTEN_VERSION` env variable and it has no effect on the problem.
I cannot set the `PYODIDE_ROOT` as I have pip installed the `pyodide-build==0.23.0` and did not clone pyodide itself into the image.

**Comment by szabolcsdombi** [comment]
Thank you for fixing this, it works perfectly.

A tiny bit of side effect I have noticed is the location of the dist folder: [the diff exmplains it the best](https://github.com/szabolcsdombi/zengl/commit/b3007cb96ce9639e5cb550361770b41e65a10df7#diff-e8884ce66bf0a9fb6610c92072289ad121c0fb3ef563f03df1f86cb6ec7b03cbR19-R20)

For comparsion:

`python -m pip wheel /zengl/` creates no dist folder, places the .whl file in the `pwd`.
`python -m build /zengl/` creates a dist folder within /zengl/ and places the .whl in it.
`python -m pyodide build /zengl/` created a dist folder in the `pwd` and places the .whl in it.

For me the pyodide's way seems to be the best, but I felt it a good idea to report it as it may be an unwanted difference from the pypa build package.

**Comment by hoodmane** [comment]
> I felt it a good idea to report it as it may be an unwanted difference from the pypa build package.

Indeed it is interesting that that is different... Note that we also added a new `--output-directory` argument.
