### ISSUE TITLE
Error building pandas - pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''

### ISSUE THREAD

**Issue by tomjakubowski** [pyodide/pyodide#3738]
## 🐛 Bug

I'm building pandas in-tree as a runtime dependency of another project which I've added as an in-tree build. pandas isn't building and I'm not sure why.

I'm running: `pyodide build-recipes pandas`

And the error is:

```
  File
"/private/var/folders/7s/_xzlm3jd5xd7ln_h91tbwc340000gn/T/build-env-c9l4on1l/lib/python3.11/s
ite-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```

### To Reproduce

I have had some trouble consistently getting a pyodide build environment stood up on my laptop. So this may be a "doesn't work on my machine" problem.

I ran these commands, roughly:

```
pyenv local 3.11.2
python --version
source ./pyodide_env.sh
export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
pip install -r requirements.txt
make
pip install -e pyodide-build
pyodide build-recipes pandas
```

### Expected behavior

pandas should build

### Environment

- Pyodide Version ed05037a82a4b1343ecaa5450a5b13bb81840e3f
- Browser version N/A
- Build environment: macOS 13.0

**Comment by tomjakubowski** [comment]
Here's a full build log

[pandas_build_log.txt](https://github.com/pyodide/pyodide/files/11153683/pandas_build_log.txt)

**Comment by ryanking13** [comment]
Thanks for the report. At first glance, it looks like an issue related to setuptools + packaging update. Recently packaging dropped support for legacy versions that do not follow PEP440 (https://github.com/pypa/setuptools/issues/3772). But I am not sure why the same error does not happen in our CI then.

Could you please try pinning setuptools version here and see what happens?

https://github.com/pyodide/pyodide/blob/ed05037a82a4b1343ecaa5450a5b13bb81840e3f/pyodide-build/pyodide_build/pypabuild.py#L78-L82

```
    pinned_reqs = {
        # Remove this when mypy releases a new version
        # https://github.com/python/mypy/pull/14788
        "setuptools": "setuptools==65.7.0",
        "types-setuptools": "types-setuptools<67.4.0.2",
    }
```

**Comment by tomjakubowski** [comment]
Yeah, the fact that it's not failing in CI makes me think the problem might be with me :-). I've made that change, and did a `pip install -e ./pyodide-build` and still seeing the same error.

Noticed this line from the pyodide-build logs after that change:

```
* Installing packages in isolated environment... (Cython>=0.29.32,<3, setuptools>=51.0.0, wheel)
```

Should updating pinned_reqs change the version constraint on setuptools when installed in that step?

**Comment by ryanking13** [comment]
> Should updating pinned_reqs change the version constraint on setuptools when installed in that step?

Yes, `pinned_reqs` will overwrite the version constraint on setuptools. Hmm, then the problem might not be setuptools.

What happens if you build pandas natively, using [this tar archive](https://github.com/pyodide/pyodide/blob/a038ac17d53458097386fd9393ee5202ac4ce193/packages/pandas/meta.yaml#L9) + `python -m build`?

**Comment by tomjakubowski** [comment]
side note, I threw out my previous build environment (based on pyenv/Homebrew; it was flaky in really weird ways) and rebuilt it using conda:

```
conda env create -f environment.yml
conda activate pyodide-env
```

With that environment activated, when I run `pyodide-build build-recipe pandas`, I'm still seeing the same error.

With that same environment activated, I am able to build pandas natively from that tarball.

An odd thing to me is that the version string in the error message is the empty string, `''`; in pypa/setuptools#3772 that isn't the case (it's a different string also not compliant with PEP440).

```
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by ryanking13** [comment]
> With that same environment activated, I am able to build pandas natively from that tarball.

Okay, thanks for the check.

> An odd thing to me is that the version string in the error message is the empty string, ''; in https://github.com/pypa/setuptools/issues/3772 that isn't the case (it's a different string also not compliant with PEP440).

Pandas 1.5.3 depends on [`versioneer`](https://github.com/pandas-dev/pandas/blob/2e218d10984e9919f0296931d92ea851c6a6faf5/setup.py#L663) to parse the version, so maybe we can check what happens inside [versioneer.py](https://github.com/pandas-dev/pandas/blob/v1.5.3/versioneer.py). Though it has> 1500 LoC...

**Comment by tomjakubowski** [comment]
Update: the version parsing error is coming out of here, parsing an empty string value for `MACOSX_DEPLOYMENT_TARGET`. https://github.com/pandas-dev/pandas/blob/v1.5.3/setup.py#L357

```
        current_system = platform.mac_ver()[0]
        python_target = get_config_vars().get(
            "MACOSX_DEPLOYMENT_TARGET", current_system
        )
        target_macos_version = "10.9"
        parsed_macos_version = parse_version(target_macos_version)
        if (
            parse_version(str(python_target)) < parsed_macos_version
```

I ran again with some debug prints of the reprs of `get_config_vars()`, `current_system` and `python_target`, along with `sys.version` and `sys.executable`:

```
{ ...
 'MACOSX_DEPLOYMENT_TARGET': ''
... }
current_system='13.0'
python_target=''
python executable=/private/var/folders/7s/_xzlm3jd5xd7ln_h91tbwc340000gn/T/build-env-emfsr2yd/bin/python
python version=3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ]
```

So it seems the sysconfig var `MACOSX_DEPLOYMENT_TARGET` is being set to the empty string. What I don't understand is, if I run that same `sys.executable` in a shell, and then `import sysconfig; sysconfig.get_config_var("MACOSX_DEPLOYMENT_TARGET")`. I get `'11.0'`; my understanding is `sysconfig` is baked in at compile time, so not sure how this could be changing between invocations of the compiler (unless that `sys.executable` is a lie?)

**Comment by ryanking13** [comment]
Thanks for the investigation @tomjakubowski!

>  my understanding is sysconfig is baked in at compile time, so not sure how this could be changing between invocations of the compiler

We overwrite [sysconfig file during the build](https://github.com/pyodide/pyodide/blob/412e0824312b40c01eb201c1b79cfc13164af4de/pyodide-build/pyodide_build/pypabuild.py#L44-L50) for cross-compilation. So the MACOSX_DEPLOYMENT_TARGET variable can have different values when running `pyodide build-recipes`.

I think setting a `MACOSX_DEPLOYMENT_TARGET` environment variable manually  would work then, though we would need some fundamental ways to fix these kind of sysconfig issues for the macOS build.

**Comment by tomjakubowski** [comment]
Awesome, thanks for the tip. As a workaround I've added a cross-script in pandas/meta.yaml to set that environment variable to the same as it is in the host python. The pandas build recipe passes now 🎉 

```
  cross-script: |
    pwd
    echo "pandas cross-script"
    export MACOSX_DEPLOYMENT_TARGET=11.0
```

As to why that's being set to the empty string seemingly when pyodide's python interpreter runs to build pandas, I'm not really sure

**Comment by thadk** [comment]
Should this be a PR? It also had been blocking my build of pandas on macOS on `0.23.4` .

> cross-script: |
>     pwd
>     echo "pandas cross-script"
>     export MACOSX_DEPLOYMENT_TARGET=11.0

**Comment by agriyakhetarpal** [comment]
Hi, I'm assuming that this shouldn't be a problem anymore, since `pandas` now uses the Meson build system + meson-python for its build backend and builds both in-tree and out-of-tree in CI. Please feel free to report any further issues with packages that are troublesome to compile, we appreciate you taking the time to have reported this!
