### ISSUE TITLE
TypeError when reusing namespaces stored in Javascript object

### ISSUE THREAD

**Issue by pawamoy** [pyodide/pyodide#3743]
## 🐛 Bug

I'm trying to manage namespaces (called sessions in my code). I identify different namespaces with different names, and store them in a global Javascript object. As instructed by [the docs](https://pyodide.org/en/stable/usage/faq.html#how-can-i-execute-code-in-a-custom-namespace), I use `pyodide.globals.get("dict")();` to instantiate a namespace.

```js
var _sessions = {};

function getSession(name, pyodide) {
    if (!(name in _sessions)) {
        _sessions[name] = pyodide.globals.get("dict")();
    }
    return _sessions[name];
}
```

Then I run this to execute Python code in a given namespace:

```js
result = await pyodide.runPythonAsync(code, { globals: getSession(session_name, pyodide) });
// session_name being a string
```

Yet I'm getting this error:

```python
PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: globals must be a real dict; try eval(expr, {}, mapping)
```

I'm a Python dev so please forgive my Javascript :sweat_smile: 

### To Reproduce

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/pyodide/v0.23.0/full/pyodide.js"></script>
<h3>session a, block 1</h3>
<pre><code id="output-a1">output 1</code></pre>
<h3>session a, block 2</h3>
<pre><code id="output-a2">output 2</code></pre>
<h3>session b, block 1</h3>
<pre><code id="output-b1">output 1</code></pre>
<h3>session b, block 2</h3>
<pre><code id="output-b2">output 2</code></pre>

<script>
var _sessions = {};

function getSession(name, pyodide, output) {
    if (!(name in _sessions)) {
        output.innerHTML += "creating " + name + "\n";
        _sessions[name] = pyodide.globals.get("dict")();
    } else {
        output.innerHTML += name + " already existed\n";
    }
    return _sessions[name];
}

async function repro(output, session) {
    output.innerHTML = "loading pyodide\n";
    let result, pyodide = await loadPyodide();
    output.innerHTML += "pyodide loaded, running code\n";
    try {
        result = await pyodide.runPythonAsync('"hello"', { globals: getSession(session, pyodide, output) });
        output.innerHTML += "result: " + result;
    } catch(error) {
        output.innerHTML += "error: " + error;
    }
}

document.addEventListener("DOMContentLoaded", function (event) {
    repro(document.getElementById("output-a1"), "session-a");
    repro(document.getElementById("output-a2"), "session-a");
    repro(document.getElementById("output-b1"), "session-b");
    repro(document.getElementById("output-b2"), "session-b");
});
</script>
```

Result in a browser:

```
session a, block 1

loading pyodide
pyodide loaded, running code
creating session-a
result: hello

session a, block 2

loading pyodide
pyodide loaded, running code
session-a already existed
error: PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: globals must be a real dict; try eval(expr, {}, mapping)

session b, block 1

loading pyodide
pyodide loaded, running code
creating session-b
result: hello

session b, block 2

loading pyodide
pyodide loaded, running code
session-b already existed
error: PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: globals must be a real dict; try eval(expr, {}, mapping)
```

### Expected behavior

No TypeError :slightly_smiling_face: 

### Environment

- Pyodide Version: 0.23.0
- Browser version: Firefox 111.0.1
- Any other relevant information: /

### Additional context

/

**Comment by pawamoy** [comment]
Maybe there's another way for me to have multiple editors "bound" to the same namespace?

**Comment by hoodmane** [comment]
Thanks for the report @pawamoy! At a quick glance, your code looks right to me . I'll try it out soon.

**Comment by pawamoy** [comment]
Worth noting: given a session, the first pyodide block works, then the next ones using the same sessions throw this type error.

**Comment by hoodmane** [comment]
Could you provide a MWE? Your "reproduction" is very complicated.

**Comment by pawamoy** [comment]
@hoodmane thanks for your help. I've updated the repro in the issue body. I've stripped useless contents. Hopefully this is more readable. I've added just a bit of CSS to make the editor visible by default.

**Comment by hoodmane** [comment]
If I'm seeing the up to date reproduction, it's still 116 lines long. Is ace.js needed for the reproduction? Can you get rid of the buttons and just hard code what they do into JavaScript logic? The css doesn't look needed for the error? Remove everything unless it makes the error go away.

**Comment by pawamoy** [comment]
Updated again, thanks for your patience :slightly_smiling_face:

**Comment by hoodmane** [comment]
Okay well it's still not quite what I'd call a MWE but it's getting closer =). I think the following is more or less a MWE: 

```js
var _sessions = {};

function getSession(name, pyodide) {
    if (!(name in _sessions)) {
        _sessions[name] = pyodide.globals.get("dict")();
    }
    return _sessions[name];
}

async function repro() {
    console.log("loading pyodide");
    let result, pyodide = await loadPyodide();
    console.log("pyodide loaded, running code");
    try {
        result = await pyodide.runPythonAsync('"hello"', { globals: getSession("session-a", pyodide) });
        console.log("result: " + result);
    } catch(error) {
        console.warn(error);
    }
}
await repro();
await repro();
```
The problem is you load a new instance of Pyodide each time. Try the following instead:

```js
var loadPyodidePromise = loadPyodide();
var _sessions = {};

function getSession(name, pyodide) {
    if (!(name in _sessions)) {
        _sessions[name] = pyodide.globals.get("dict")();
    }
    return _sessions[name];
}

async function repro() {
    console.log("loading pyodide");
    let result, pyodide = await loadPyodidePromise;
    console.log("pyodide loaded, running code");
    try {
        result = await pyodide.runPythonAsync('"hello"', { globals: getSession("session-a", pyodide) });
        console.log("result: " + result);
    } catch(error) {
        console.warn(error);
    }
}
await repro();
await repro();
```

If you run your code against Pyodide 0.21.3 you actually segfault the interpreter:
```
Podide has suffered a fatal error. Please report this to the Pyodide maintainers.
RuntimeError: memory access out of bounds
```
as of v0.22.0 we are more careful and you don't get a segfault but it also doesn't work the way you expect.

**Comment by pawamoy** [comment]
Thanks! Yeah I was wondering about loading Pyodide just once per session. Once per page is even better. I do wonder though what will happen if the instance's stdout changes while it is still running code. I guess it's not really an issue for my use-case anyway. Thanks again @hoodmane! I'll leave this open since that doesn't address the actual TypeError issue (but feel free to close).

**Comment by hoodmane** [comment]
Well the `TypeError` here is correct. If you did the corresponding thing with a native Python you would get a segfault instead of a `TypeError`. The error message could be more detailed, but it's not obvious how to make it more detailed.

>  if the instance's stdout changes while it is still running code

If you call `pyodide.setStdout` while async tasks are queued, it will affect those tasks. I'm not sure how concerning this is though...

**Comment by pawamoy** [comment]
> Well the TypeError here is correct. If you did the corresponding thing with a native Python you would get a segfault instead of a TypeError. The error message could be more detailed, but it's not obvious how to make it more detailed.

I'm not sure to understand why it would segfault. It's perfectly possible to `exec` or `eval` Python code in a native interpreter while reusing dictionaries as globals.

> I'm not sure how concerning this is though...

Not really concerning indeed, at least for my use-case where users will probably not run many things at once, but rather one after the other :slightly_smiling_face:

**Comment by hoodmane** [comment]
> I'm not sure to understand why it would segfault. It's perfectly possible to exec or eval Python code in a native interpreter while reusing dictionaries as globals.

The segfault comes from starting up two different Python interpreters and then using a pointer to a dictionary from the first with the second.

**Comment by pawamoy** [comment]
Oh OK, that makes sense indeed. Thanks for your time!

**Comment by hoodmane** [comment]
You're welcome. Please don't hesitate to open further discussions / issues if you have any more questions!
