### ISSUE TITLE
scikit-build>=0.17.0 breaks opencv-python build

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3753]
## 🐛 Bug

opencv-python build fails with following error message.

```
"/tmp/build-env-2lp7wspf/lib/python3.11/site-packages/skbuild/setuptools_wrap.py
", line 424, in setup                                                           
    raise ValueError(msg)                                                       
ValueError: CMAKE_INSTALL_PREFIX may not be passed via cmake_args to setup. 
```

which is caused by https://github.com/scikit-build/scikit-build/pull/872.

We set `CMAKE_INSTALL_PREFIX` here:

https://github.com/pyodide/pyodide/blob/873ca14986829a9059d7b9150928b70c94fa7fbf/packages/opencv-python/cmake/build_args.sh#L91

@henryiii Do you have some suggestion about handling this error?

**Comment by henryiii** [comment]
a) Is it needed? Generally it shouldn't be required and breaks things to set it (which is why it is filtered out of CMAKE_ARGS, IIRC)?
b) CMAKE_ARGS is supposed to be allowed - only setting it by a non-generic method produces an error.

**Comment by henryiii** [comment]
Ahh, it's here: https://github.com/opencv/opencv-python/blob/6b73d90fc3e50ba6858926d299b49f0228e19d68/setup.py#L254 - that's pulling `CMAKE_ARGS` into `cmake_args`, without the filtering scikit-build does.

**Comment by henryiii** [comment]
Could you verify that removing this line is safe? It really shouldn't be needed, I hope...

**Comment by ryanking13** [comment]
> Could you verify that removing this line is safe? It really shouldn't be needed, I hope...

I can confirm that removing that line works :)
