### ISSUE TITLE
xxHash

### ISSUE THREAD

**Issue by syvlabs** [pyodide/pyodide#3757]
## 🐍 Package Request

- Package Name and Version: xxHash
- Package URL: https://pypi.org/project/xxhash/
- Package Dependencies that needs to be resolved first: None, it just needs the C file in https://github.com/Cyan4973/xxHash

Thanks so much!

**Comment by syvlabs** [comment]
Note: I've tried building this out of tree, but I get stuck at:

```
AssertionError: would build wheel with unsupported tag ('cp311', 'cp310', 'emscripten_3_1_27_wasm32')
```

**Comment by hoodmane** [comment]
There's some issues regarding the setup for out of tree builds that need to be ironed out. It looks to me like that error comes from using a host Python 3.11 to build a package for Python 3.10.
