### ISSUE TITLE
Upload top-of-tree xbuildenv to S3

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3759]
When testing pyodide-build out-of-tree build feature, I often need to manually download xbuildenv.

```sh
pip install "git+https://github.com/pyodide/pyodide/@main#subdirectory=pyodide-build"
pyodide xbuildenv install --download --url "<xbuildenv_url>"
pyodide build
```

For now, we don't upload top-of-tree xbuildenv anywhere, so I use circle CI build artifacts. For example: [here](https://github.com/ryanking13/pyodide-recipes-mirror/blob/8c5bb491ca4c43059f9eb31b9fb92764c215cba8/.github/workflows/build.yml#L36-L37).

So I think it would be useful to upload top-of-tree xbuildenv archive, so we can download it from fixed URL.
Maybe into `https://cdn.jsdelivr.net/pyodide/dev/xbuildenv.zip` or `https://cdn.jsdelivr.net/pyodide/dev/xbuildenv/xbuildenv.zip`?

**Comment by rth** [comment]
Sounds good to me. We did setup another"cache" S3 bucket initially, more for experimentation where we can also upload things. But the main bucket in the dev folder probably makes more sense in this case.
