### ISSUE TITLE
No logs when erroring on build package

### ISSUE THREAD

**Issue by pfebrer** [pyodide/pyodide#3770]
I'm trying to build a package with Cyhton sources with the "in tree" approach.

When running 

```
pyodide build-recipes sisl --install
```

I get

```
The following packages are already built: boost-cpp, distutils, hashlib, libf2c, liblzma, lzma, micropip, numpy, openblas, openssl, packaging, pydecimal, pydoc_data, pyparsing,  
scipy, setuptools, sqlite3, ssl, test, and tqdm                                                                                                                                   
Building the following packages: sisl                                                                                                                                             
[1/1] (thread 1) building sisl ⠙                                                            
Building packages... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1   0% Time elapsed: 0:00:09Error building sisl. Printing build logs.                                                                                                                                         
ERROR: No build log found.                                                                                                                                                        
ERROR: cancelling buildall                                                                                                                                                        
[1/1] (thread 1) building sisl ⠹                                                            
Building packages... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/1   0% Time elapsed: 0:00:09
```

Therefore, I have no clue what's wrong. When does an error without build logs happen? Can I get some more verbose output in some way? Thanks!

I'm running this on the Docker container, after succesfully building all packages, even an old version of the package I'm trying to build.

**Comment by hoodmane** [comment]
If you use the old `pyodide-build buildpkg packages/sisl/meta.yaml` then that is more verbose. I think it is getting removed though.

**Comment by pfebrer** [comment]
Thank you! That helped! I was able to spot the error, although now I have another one :sweat_smile: 

It's strange because with `pyodide-build buildpkg` I am seeing that `scikit-build` is already building the sources with `cmake`, but if I run `pyodide build-recipes` i get no logs.

**Comment by hoodmane** [comment]
@ryanking13 what's the equivalent of `build-pkg` in the new cli?

**Comment by ryanking13** [comment]
> @ryanking13 what's the equivalent of buildpkg in the new cli?

You can try:

```
pyodide build-recipes sisl --no-deps
```

**Comment by pfebrer** [comment]
Nice, that works. Thanks!

**Comment by hoodmane** [comment]
I'm not sure this issue should be closed though. Even without `--no-deps` it should probably store the build log to a file. Also, isn't it kind of illogical that `--no-deps` makes it print to stdout? You would think we would handle that with a verbosity flag which would be directly discoverable.

**Comment by pfebrer** [comment]
Yes, I definitely agree that a verbosity flag would be nice and it is very strange that `--no-deps` writes logs that otherwise are not written.

I closed it because the workaround was enough for me. Feel free to open again :)

**Comment by ryanking13** [comment]
Yes, the behavior of `--no-deps` is not very straightforward, as it actually calls a different API. When making `build-recipes` CLI, I tried to reuse existing APIs (buildall and buildpkg) as much as possible so for now the behavior is not very ideal. I think we need to find a way to merge these two APIs for consistency.

Anyway, I think the point of this issue is not about that, so I think we can discuss it in a separate issue.
