### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython' when using pyodide build 

### ISSUE THREAD

**Issue by gabrielfougeron** [pyodide/pyodide#3774]
## 🐛 Bug

When trying out the new pyodide 0.23.1, I get a "ModuleNotFoundError: No module named 'Cython' " error when building.

This is especially surprizing (to me) because cython is a dependency of my project.

### Environment

pyodide_build 0.23.1
emsdk 3.1.32
python 3.11.3

**Comment by ryanking13** [comment]
Could you please show us the pyproject.toml file of your project? Does it specify Cython as a build dependency?

We hard-coded [Cython as a build depencency in <0.23.0, but not anymore](https://github.com/pyodide/pyodide/blob/5ef5622414f0fe8ab8c54694e04ab1b13939b7d4/pyodide-build/pyodide_build/pypabuild.py#L71-L81).

**Comment by gabrielfougeron** [comment]
Worked perfectly, thank you very much!
