### ISSUE TITLE
urllib unknown url error

### ISSUE THREAD

**Issue by joshbernsteint** [pyodide/pyodide#3775]
## 🐛 Bug

Whenever I try to open a URL, no matter how it is encoded, I get this error:

`urllib.error.URLError: <urlopen error unknown url type: https>`

This seems to be a problem with just Pyodide, as I am unable to recreate it on my local python machine.
### To Reproduce

```
let temp = await loadPyodide();
await temp.pyimport("urllib.request");
temp.runPython('
import urllib.request as requester


link = "www.youtube.com/watch?v=-loDklmrbd0&list=PLvAOrbuuPJrRn3EWE7QCu27-ygrW0jnYQ"
link = parser.quote(link)

requester.urlopen(link)
print("All good")
');
```

### Expected behavior

"All good"

### Environment

- Pyodide Version: 0.23.1
- Browser version: Edge 112.0.1722.46 
- Any other relevant information:

I'm using the hosted distribution of pyodide

**Comment by hoodmane** [comment]
Yes you can't use sockets. You may want to try `pyfetch`:
https://pyodide.org/en/stable/usage/api/python-api/http.html#module-pyodide.http

**Comment by hoodmane** [comment]
See here:

>               Networking in Python does not work, since it relies on low-level networking primitives (socket) that aren't allowed in the browser sandbox.
> 
> "Supporting the Web API" means supporting the APIs that Javascript provides to do things on a web page.
> 
> Like you say, the best way forward for now is to use Javascript to perform the networking, and then pass it along to Python.
> 
> We might be able to provide emulation of the high-level networking interfaces in Python on top of the Javascript API, but that work has not been done.

_Originally posted by @mdboom in https://github.com/pyodide/pyodide/issues/375#issuecomment-481364649_

**Comment by hoodmane** [comment]
If you have any followup questions, don't hesitate to ask though. You may also be interested in 
https://github.com/bartbroere/pyodide-requests

**Comment by joshbernsteint** [comment]
thank you!
