### ISSUE TITLE
Change `repodata.json` name to something else?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3788]
I am told by conda people that repodata.json is supposed to be the input to a solver. Our repodata.json is a lock file which is the output of a solver. This is a misleading name clash. We will need to spend a lot of time explaining to conda people that this file isn't what they expect to be. Can we rename it?

**Comment by hoodmane** [comment]
@katietz

**Comment by rth** [comment]
In the default mode, I would say it's still the input to a solver, it's just that given that Pyodide is a distribution ( with a single version for each package) dependency resolution is trivial. In terms of contents, it's  taking `meta.yaml` and copying them to this file, so same as conda as far as I understand?

Though yes, if one starts to generate a `repodata.json` for a specific application, then it really starts to look like a lock file.  Is there anything like a repodata.json but used for lock files in the conda ecosystem?

**Comment by hoodmane** [comment]
But 1. we guarantee existence and uniqueness of "solutions" and 2. we guarantee that the solution is found in linear time in the solution size. The solver is in fact trivial. What we actually have is more like a virtual environment that we lazily load packages from as they are needed. We will only load exactly one version of each package. Kai was suggesting adding multiple versions and I said I valued a lot the speed, the existence and the uniqueness which are all properties we lose. But this is proof that we are not similar to conda repodata.json.

Real solvers handle multiple versions of each package and version constraints on dependencies. There may be any number of solutions, 0, one, or many. The time to find the solution is potentially exponential in the solution size. 

As a useless theoretical aside, I think solving is NP hard and probably also co NP hard -- the decision problem is "does there exist a subset of packages and versions such that for every package in the set and for every dependency of that package, the constraint is satisfied". This sounds to me like Sigma Pi in the polynomial time hierarchy, so that it is conjecturally strictly harder than NP complete (it's possible of course that P = NP or that P != NP but NP = CoNP, and in either case it wouldn't be any harder). I'm curious whether it could be Sigma Pi complete. Have to ask my complexity theory friends.
