### ISSUE TITLE
Allow specifying output directory in pyodide build with -o or --outdir

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3806]
I added the capability to specify output directory in pyodide build with `--output-directory`. But here `pypa/build` accepts either `--outdir` or `-o`. We should accept these as ways to specify the output directory for consistency

**Comment by rth** [comment]
Can't we use the same parameter name as pypa/build? Or would that be a backward compatible change now? Maybe with a deprecation cycle..

**Comment by hoodmane** [comment]
I would say:
1. Add "correct" pypa/build names in addition to the "incorrect" one I used
2. remove "incorrect" name after a few versions

But we could remove it sooner if you strongly prefer. It just would make cibuildwheel have to have some version logic to decide which flags to pass.

**Comment by rth** [comment]
It's certainly not urgent, as long as keep a single correct flag in the end. So a deprecation then removal after a few versions sounds good.
