### ISSUE TITLE
Port Open CV

### ISSUE THREAD

**Issue by frastlin** [pyodide/pyodide#381]
Hello,
It was not clear in the readme or docs where to see all the packages that have been ported, but I would love to see [Open CV](https://pypi.org/project/opencv-python/)
ported.
Open CV is already a C based distribution and there are [efforts to port it to the browser.](https://docs.opencv.org/3.4/d4/da1/tutorial_js_setup.html)
Along with [Tensorflow](https://www.tensorflow.org/js) and the already ported NumPy package, these will allow for much of the real-time image-based machine-learning projects.

**Comment by mdboom** [comment]
You can see the list of packages [here](https://github.com/iodide-project/pyodide/tree/master/packages).

I agree, OpenCV would be a great package to have!

**Comment by 124bit** [comment]
yes, python opencv really lacks in pyodide (even having opencv.js)

**Comment by jordanhart** [comment]
@124bit, could you describe your knowledge around lack of support for python opencv with opencv.js?

**Comment by hoodmane** [comment]
> I need to check the performance of this transfer to think about moving forward with this.

Simplest is to make all buffers in Python and then use `getBuffer`. No data is moved with `getBuffer`, you can just alter the Python buffer in place, so there should be no performance implication.

> if Pyodide contributors tackle updating scipy and compiling opencv it will be a definite victory

We would definitely like to do that. Unfortunately so far nobody has time. Anyone who wants this to happen sooner is very welcome to give it a try! (Though from what I understand, upgrading scipy is going to be time consuming difficult work.)

**Comment by 124bit** [comment]
> Simplest is to make all buffers in Python and then use getBuffer. No data is moved with getBuffer, you can just alter the Python buffer in place, so there should be no performance implication

Got it! The possibilities that it potentially opens are exciting.
