### ISSUE TITLE
Package Request | Langchain

### ISSUE THREAD

**Issue by RyvrImmersive** [pyodide/pyodide#3825]
File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 6, in <module>
ModuleNotFoundError: No module named 'langchain'

## 🐍 Package Request

- Package Name and Version :
- Package URL :
- Package Dependencies that needs to be resolved first:

**Comment by rth** [comment]
Please see the discussion in https://github.com/pyodide/pyodide/issues/3711#issuecomment-1488727738 Closing as a won't fix due to reasons outlined there. Though, don't hesitate to work on packaging some of the dependencies if you are interested (and commenting in the linked issue).
