### ISSUE TITLE
DTale Data exploration package

### ISSUE THREAD

**Issue by NguyeHe4** [pyodide/pyodide#3841]
I'm looking for a way to use Dtale on an Angular js application along with other Python packages. I am looking at pyodide as the package to enable this. I have tried to use micropip to install dtale, but there are dependencies that cannot be installed. Has anyone enabled Dtale on Pyodide and can show me how to do it? Thanks in advance.

## 🐍 Package Request

- Package Name and Version : dtale/latest
- Package URL : 
- Package Dependencies that needs to be resolved first: kaleido, dash-daq, dash-colorscales, lz4; python_version > "3.6"

**Comment by rth** [comment]
@NguyeHe4 You should open an issue about it in the Dtale repo. This would require replacing the flask server they use by something that can run in the browser. For instance, https://github.com/travisdoesmath/sippycup tries to do that. 

In any case, this requires significant development in Dtale and is not something we would do on the Pyodide side.
