### ISSUE TITLE
Make pyodide.loadPackage return list of packages that are loaded

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3843]
I think it would be nice if pyodide.loadPackage returns list of packages that are loaded, so that downstream packages that use it (micropip) can know what packages are loaded.

- Related: https://github.com/pyodide/micropip/pull/60

**Comment by ryanking13** [comment]
@RulerOfCakes are you interested in implementing this issue?

**Comment by RulerOfCakes** [comment]
Thank you for the detailed explanation! I've opened #4306 based on your description.
