### ISSUE TITLE
Uninitialised memory returned by Py_BuildValue string  conversions

### ISSUE THREAD

**Issue by hyanwong** [pyodide/pyodide#3846]
## 🐛 Bug

`Py_BuildValue("s#", ***)` and `Py_BuildValue("y#", ***)` both return strings that include memory outside the original input string

### To Reproduce

I am unsure how to compile C modules for testing to provide a MWE. However, this was encountered using the `tskit` library packaged as part of the `msprime` library which is available in pyodide. The behaviour which triggers this is

```python
Welcome to the Pyodide terminal emulator 🐍
Python 3.11.3 (main, May  9 2023 00:39:35) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>> ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/tskit/genotypes.py", line 151, in alleles
    return self._ll_variant.alleles
           ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
>>> 
```

The issue is caused by this line used by the python C API function:

https://github.com/tskit-dev/tskit/blob/be7d84f7a014c679c9e303aa7a8145b440f73bd3/python/_tskitmodule.c#L581

We have extensively investigated this and are confident that it is a bug in the pyodide implementation rather than in the `tskit` library. See https://github.com/tskit-dev/tskit/issues/2737#issuecomment-1537149359. Moreover, this function works after the 3rd time of use (see https://github.com/tskit-dev/tskit/issues/2737#issuecomment-1537432615)

Apologies for not providing a smaller MWE. I would be happy to do so if someone could point to instructions on how to test the Python C API within pyodide (specifically the `Py_BuildValue` function). 

### Expected behavior

Only the pre-defined C string should be returned to python, rather than parts of uninitialised memory.

### Environment

Tried on https://pyodide.org/en/latest/console.html

- Pyodide Version: 0.24.0.dev0
- Browser version: 113.0.5672.63 (Official Build) (x86_64)
- Any other relevant information: Also seen on Pyodide 0.23.2. See https://github.com/tskit-dev/tskit/issues/2737#issuecomment-1540047080 for a sure way to trigger the bug.

**Comment by hoodmane** [comment]
Well the problem is certainly not with `Py_BuildValue` with these format args in general:
```js
l_ptr = pyodide.runPython(`l = []; id(l)`)
fmt_ptr = pyodide._module.stringToNewUTF8("s#");
str_ptr = pyodide._module.stringToNewUTF8("hello there!");
varargs_ptr = pyodide._module.stackAlloc(8);
pyodide._module.HEAP32[varargs_ptr/4] = str_ptr;
pyodide._module.HEAP32[varargs_ptr/4 + 1] = 10;
pystr_ptr = pyodide._module.__Py_BuildValue_SizeT(fmt_ptr, varargs_ptr);
if(pystr_ptr === 0){
    pyodide._module._pythonexc2js();
}
pyodide._module._PyList_Append(l_ptr, pystr_ptr);
pyodide.runPython("print(l)")
```
prints ['hello ther'] just as expected.

**Comment by hyanwong** [comment]
Thank you @hoodmane. This is really helpful. I didn't realise you could dump and extract raw bytes into the stack like that. I will try to use that to work up a MWE. It could well be the 64 vs 32 bit pointer thing.

**Comment by hoodmane** [comment]
It's also possible that memory is corrupted somewhere ahead of this function call and that for whatever reason you only see the problem here. One important thing to remember is that a lot of things like de-referencing NULL that would normally be segfaults just run without problem in webassembly. So sometimes it's pretty hard to tell when the error actually occurred vs where you see the first symptom of the problem...

**Comment by benjeffery** [comment]
We've traced this to an incorrect type being passed to `Py_BuildValue`, as this function is variadic we didn't get a comile warning. Interestingly this wasn't caught by our 32bit CI tests.

This issue can be closed, many thanks for the helpful comments.
