### ISSUE TITLE
Proxied JS method.apply(context, list) fail while method(*list) doesn't

### ISSUE THREAD

**Issue by WebReflection** [pyodide/pyodide#3849]
## 🐛 Bug

While working on [this PyScript issue](https://github.com/pyscript/pyscript/pull/1459) I've noticed that `context.method.apply(context, list)` doesn't work while `context.method(*list)` does.

I don't mind using the latter as that's also more Pythonic but that might surprise JS developers using Pyodide proxies that mimic JS APIs.

### To Reproduce

```python
import js
classList = js.document.body.classList
classList.add.apply(classList, ["a", "b"])
```

### Expected behavior

The method should be invoked with *n* arguments as by JS specs.

### Environment

- Pyodide Version: latest
- Browser version: any
- Any other relevant information: nope

### Additional context

Happy to have it as won't fix but at least there's a related issue that explain the *gotcha*.

**Comment by hoodmane** [comment]
Unraveling this a bit:
1.
```js
function a(...params) {
    console.log(params);
}
pyodide.runPython(`
from js import a
a.apply(None, [7, 6, 5])
`)
```
prints `[undefined, undefined, undefined]`.

2.
```js
function a(...params) {
    console.log(params);
}
let l = pyodide.runPython(`[7, 6, 5]`)
a.apply(null, l);
```
also prints `[undefined, undefined, undefined]`.


Per the tc39 spec, [`apply`](https://tc39.es/ecma262/#sec-function.prototype.apply) uses [`CreateListFromArrayLike`](https://tc39.es/ecma262/#sec-createlistfromarraylike) to generate the argument list. The relevant snippet of `CreateListFromArrayLike` is:

> 5. Let index be 0.
> 6. Repeat, while index < len,
> 
>     a. Let indexName be ! [ToString](https://tc39.es/ecma262/#sec-tostring)([𝔽](https://tc39.es/ecma262/#%F0%9D%94%BD)(index)).
>     b. Let next be ? [Get](https://tc39.es/ecma262/#sec-get-o-p)(obj, indexName).
>     c. If elementTypes does not contain [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(next), throw a TypeError exception.
>     d. Append next to list.
>     e. Set index to index + 1.


Focusing in on this step 6b, we see the problem:
```js
let l = pyodide.runPython(`[7, 6, 5]`);
console.log(l[0]); // undefined
```
Oops, `l[0]` should probably give `7`, not undefined.

**Comment by WebReflection** [comment]
Not sure if proxy related but indexes in the get (or has) are always passed as strings, even for proxied arrays

**Comment by hoodmane** [comment]
I have a fix on a local branch, but I've gotten distracted implementing other `Array.prototype` methods on PyProxies...

**Comment by WebReflection** [comment]
on a quick look that looks way cleaner / better at handling arrays +1
