### ISSUE TITLE
xbuildenv should have a version number in the folder name

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3851]
There have been numerous issues with mixing up xbuildenvs from two different versions of Pyodide. We should put the version number in the folder name so we don't get confused.

**Comment by agriyakhetarpal** [comment]
The xbuildenv folders are now embedding the version number in the folder name, so we can close this issue now. Thanks!

**Comment by hoodmane** [comment]
Next maybe we should put these in the xdg-cache directory. I have so many redundant xbuildenv folders on my computer.
