### ISSUE TITLE
Deno test works with released Pyodide instead of development Pyodide

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3860]
## 🐛 Bug

Apparently I didn't read #3810 carefully enough because it seems to test against Pyodide 0.23.1 instead of against the current main branch:
`import pyodideModule from "npm:pyodide@0.23.1/pyodide.js";`

@rajsite

**Comment by rajsite** [comment]
> it seems to test against Pyodide 0.23.1 instead of against the current main branch

@hoodmane that shouldn't be the case. See the following comment: https://github.com/pyodide/pyodide/pull/3810#issuecomment-1531644786

Specifically:
> 1. Populate the local node_modules from npm (with a flag telling deno to make a local node_modules directory)
> 2. Copy the contents of the build dist folder into node_modules/pyodide (so the npm fetched contents are replaced with local files):

**Comment by hoodmane** [comment]
Sorry should have reread the PR history. Would you mind adding a comment explaining what it does?

**Comment by hoodmane** [comment]
I spent some time today trying to get Deno to work with the command line runner. It seems to be a lot harder to get it to work if you do `import {loadPyodide} from "relative/path/to/pyodide.mjs"`...

**Comment by hoodmane** [comment]
I guess I can add the comment.

**Comment by rajsite** [comment]
> I guess I can add the comment.

I'm on it 👍

**Comment by hoodmane** [comment]
Thanks!

**Comment by hoodmane** [comment]
@rajsite Do you know if Deno has actually compatible versions of `openFileSync` and `readSync`, etc? I'm currently having some trouble getting the nodefs to work with deno...

**Comment by rajsite** [comment]
> @rajsite Do you know if Deno has actually compatible versions of `openFileSync` and `readSync`, etc? I'm currently having some trouble getting the nodefs to work with deno...

Deno is using an emulation layer for the `node:` apis and it has restrictions (the doc describes specifically how to leverage the above apis): https://deno.com/manual@v1.33.3/node/node_specifiers

If you are trying to get esm scripts to work my opinion would be to come at it from the direction of not using `node:` apis.
Deno's `node:` and `npm:` support are intended just as compatibility layers (why the npm package + commonjs work kinda worked out of the box).

For first class esm Deno support the scripts should come from the mindset of browser apis + Deno namespace apis for outside browser behavior (read files, open sockets, etc). But that's just 2 cents.

**Comment by hoodmane** [comment]
Right. Well I'm just trying to get anything to work at all =)

The specific code I'm looking at is here:
https://github.com/emscripten-core/emscripten/blob/main/src/library_nodefs.js#L241-L299
Probably I should just be a bit more patient and do a more careful rewrite. Currently I've made ad-hoc changes to `open` to make it work like:
```js
            const buf = buffer.subarray(offset, offset + length);
            Deno.seek(stream.nfd.rid, position, Deno.SeekMode.Start);
            return Deno.readSync(
              stream.nfd.rid,
              buf
            );
```

But this seems to be... not right. It reads files correctly more often than not but sometimes corrupts them. I've run into bugs like this before with node so it's not unique to deno or anything. But yeah seems like there is some work. @sbc100 would you be interested in a `library_denofs`?

**Comment by hoodmane** [comment]
@rajsite do you understand what 
```
TypeError: Loading unprepared module: npm:ws, imported from:
```
means? I get it when I try to `await import("npm:ws")`.

**Comment by hoodmane** [comment]
I am getting it to work with pretty minimal changes. The biggest gotcha seems to be that `fs.writeFileSync` is exactly compatible with the normal one but `fs.readFileSync` has to be called like:
```js
fs.readSync(stream.nfd, buffer.subarray(offset, offset + length), {position});
```
Surely it's a bug that `readFileSync` and `writeFileSync` have completely different APIs??

Here's my current patch:

```patch
 mergeInto(LibraryManager.library, {
   $NODEFS__deps: ['$FS', '$PATH', '$ERRNO_CODES', '$mmapAlloc'],
-  $NODEFS__postset: 'if (ENVIRONMENT_IS_NODE) { NODEFS.staticInit(); }',
+  $NODEFS__postset: 'NODEFS.staticInit();',
   $NODEFS: {
     isWindows: false,
     staticInit: () => {
       NODEFS.isWindows = !!process.platform.match(/^win/);
-      var flags = process.binding("constants");
-      // Node.js 4 compatibility: it has no namespaces for constants
-      if (flags["fs"]) {
-        flags = flags["fs"];
-      }
+      const flags = require("node:fs").constants;
       NODEFS.flagsForNodeMap = {
         "{{{ cDefs.O_APPEND }}}": flags["O_APPEND"],
         "{{{ cDefs.O_CREAT }}}": flags["O_CREAT"],
@@ -99,6 +95,9 @@ mergeInto(LibraryManager.library, {
       if (flags) {
         throw new FS.ErrnoError({{{ cDefs.EINVAL }}});
       }
+      if (newFlags === 0) {
+        newFlags = NODEFS.flagsForNodeMap["O_RDONLY"];
+      }
       return newFlags;
     },
     node_ops: {
@@ -264,14 +263,14 @@ mergeInto(LibraryManager.library, {
         // Node.js < 6 compatibility: node errors on 0 length reads
         if (length === 0) return 0;
         try {
-          return fs.readSync(stream.nfd, Buffer.from(buffer.buffer), offset, length, position);
+          return fs.readSync(stream.nfd, buffer.subarray(offset, offset + length), {position});
         } catch (e) {
           throw new FS.ErrnoError(NODEFS.convertNodeCode(e));
         }
       },
       write: (stream, buffer, offset, length, position) => {
         try {
-          return fs.writeSync(stream.nfd, Buffer.from(buffer.buffer), offset, length, position);
+          return fs.writeSync(stream.nfd, buffer, offset, length, position);
         } catch (e) {
           throw new FS.ErrnoError(NODEFS.convertNodeCode(e));
         }
```

and:
```
test/test_core.py::core2g::test_fs_nodefs_cloexec_0 PASSED
test/test_core.py::core2g::test_fs_nodefs_home PASSED
test/test_core.py::core2g::test_fs_nodefs_nofollow PASSED
test/test_core.py::core2g::test_fs_nodefs_readdir PASSED
test/test_core.py::core2g::test_fs_nodefs_rw_0 PASSED
```
(I hacked `RunnerCore.run_js` to test against deno)
