### ISSUE TITLE
Dealing with the requests dependency

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3876]
So with monekypatching in [`pyodide-http`](https://github.com/koenvo/pyodide-http), requests should work. However, the question remains how we should deal with packages that have a mandatory dependency on requests.

There could be several options,

1. Try to make `requests` optional in the package, at least so that imports wouldn't fail if requests is not installed. Then letting users install `pyodide-http` and `requests` dependencies themselves.
2. Physically add `requests` to our dependency tree. So far we have been reluctant to do this since it won't work with either `pyodide-http` or some comparable workarounds. This would be probably the most straightforward solution, but for instance as far as I understand JupyterLite doesn't use `pyodide-http`  in a webworker, so we need to be sure it's not breaking their approach. cc @bollwyvl
3. Same as 2 but depending on the PyPI package, instead of re-packaging the pure python wheel on our side. This functionality is not yet supported.

**Comment by bollwyvl** [comment]
jupyterlite-pyodide-kernel _only_ runs in a WebWorker, but _sometimes_
doesn't have ServiceWorker, if that helps clarify things.
