### ISSUE TITLE
Support JSPI

### ISSUE THREAD

**Issue by jimmywarting** [pyodide/pyodide#3878]
### Pitch

I saw demo about using native file system access and using file system handles. this is pretty awesome, but yea as you mention they are unfortunately async. but if you would compile it [JSPI ](https://v8.dev/blog/jspi) then you could suspend the assembly code and wait for the read/write operation to complete. and then resume the python code.

**Comment by rth** [comment]
As mentioned in other issue, @hoodmane is working on it in https://github.com/pyodide/pyodide/pull/3210

**Comment by agriyakhetarpal** [comment]
JSPI should be more or less supported now, as the linked PR above has been merged. Thanks!
