### ISSUE TITLE
Loading packages from Pyodide's ES6 module throws error: 'Unknown error occurred while trying to verify integrity'

### ISSUE THREAD

**Issue by jeyabbalas** [pyodide/pyodide#3887]
## 🐛 Bug

I am developing an ES6 module library that depends upon Pyodide. I import Pyodide from the CDN link to the ESM: https://cdn.jsdelivr.net/npm/pyodide@0.23.2/+esm. 

### To Reproduce

```javascript
const pyodide = await (await import('https://cdn.jsdelivr.net/npm/pyodide@0.23.2/+esm')).loadPyodide({indexURL: 'https://cdn.jsdelivr.net/npm/pyodide@0.23.2/'});
await pyodide.loadPackage('micropip');
```

I am able to reproduce this error on ObservableHQ (to see error, please open console on Chrome Dev tools): https://observablehq.com/d/0b35cae6486ce7fa

ObservableHQ uses a web worker to run all scripts. The problem also exists if I run the code in the main thread. Pyodide loaded through `require()` works fine but I want to build an ES6 library that depends upon Pyodide.

### Expected behavior

Similar to the Pyodide package obtained via the browser script tag loading, `micropip` should install without errors.

### Environment

- Pyodide Version: 0.23.2
- Browser version: 113.0.5672.126 (Official Build) (x86_64)

**Comment by ryanking13** [comment]
> indexURL: 'https://cdn.jsdelivr.net/npm/pyodide@0.23.2/

the pyodide NPM package contain only JS files and it does not contain wheels, so you need to use the following indexURL instead: `
https://cdn.jsdelivr.net/pyodide/v0.23.2/full`.

**Comment by jeyabbalas** [comment]
Indeed that solved the problem. Thank you so much!

**Comment by hoodmane** [comment]
what happens when you don't pass any index url? Does it also fail?

**Comment by jeyabbalas** [comment]
Yes, I had first tried running it without passing an index URL. I received the error below:

```sh
Uncaught TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:3000/app/.cache/npm/pyodide@0.23.2/pyodide.asm.js
GET http://127.0.0.1:3000/app/.cache/npm/pyodide@0.23.2/python_stdlib.zip 404 (Not Found)
Uncaught (in promise) Error: Failed to load 'http://127.0.0.1:3000/app/.cache/npm/pyodide@0.23.2/python_stdlib.zip': request failed.
```

Passing `{indexURL: 'https://cdn.jsdelivr.net/npm/pyodide@0.23.2/'}` seemed to have removed the error so I did not think much of it.

I think I see what you are getting at. I never pass the index URL while using `require()`. So, it seems to default to the correct folder. Does `python_stdlib.zip` exist both at `https://cdn.jsdelivr.net/npm/pyodide@0.23.2/` and `https://cdn.jsdelivr.net/pyodide/v0.23.2/full` but the wheels only exist in the latter?

**Comment by hoodmane** [comment]
> Does python_stdlib.zip exist at both but the wheels only exist in the latter?

Yeah that's right. In node it's supposed to lazily download the wheels and cache them in the `node_modules` directory the first time you use them.

**Comment by jeyabbalas** [comment]
Ah I see! I did not use `npm` to install Pyodide into my ES6 library. I was loading it directly from the ESM CDN URL. Was this an unexpected behavior on my part?
