### ISSUE TITLE
weired not defined variable- Uncaught (in promise) ReferenceError: output_folder is not defined

### ISSUE THREAD

**Issue by wanghaisheng** [pyodide/pyodide#3898]
## 🐛 Bug

https://github.com/wanghaisheng/video-publish-metadata-gpt/blob/gh-pages/index.html

line 167
```
    # Save the result image with the video_id as the filename
    video_id = row['video_id']
    output_folder = './output'
    if not os.path.exists(output_folder):
        os.mkdir(output_folder)
    result_image_path = f'${{ output_folder }}/${{ video_id }}.jpg'
    result_image.save(result_image_path)
```

![image](https://github.com/pyodide/pyodide/assets/2363295/6ff4056f-88f9-48a8-a217-b29672db03c9)

`

### Environment

- Pyodide Version:
- Browser version:
- Any other relevant information:

**Comment by hoodmane** [comment]
`${{ output_folder }}` is a JavaScript template string, but there is no JS variable called `output_folder` in the scope.

**Comment by wanghaisheng** [comment]
sorry for that. I use chatgpt convert python code to pyodide,
let me debug a little by mysel
