### ISSUE TITLE
Cannot pass the pyodide object because of cyclic dependency

### ISSUE THREAD

**Issue by rheanV** [pyodide/pyodide#3900]
## 🐛 Bug

Loaded the pyodide library in a web-worker. Cannot pass that object back to the main thread because of cyclic dependency in the object

### To Reproduce

Loaded the pyodide library using the loadPyodide method in a web worker. Eg: pyodideRuntime = await loadPyodide({
        stdout: console.log,
        stderr: console.log,
        fullStdLib: false,
      });
Cannot pass "pyodideRuntime" object back to the main thread, or convert it to string.
### Expected behavior

Be able to pass the pyodide object back to the main thread.

**Comment by hoodmane** [comment]
You won't be able to do this. You may be interested in [Comlink](https://github.com/GoogleChromeLabs/comlink) which helps with this.
