### ISSUE TITLE
invalidate_caches does not refresh the import when file has been changed on the disk

### ISSUE THREAD

**Issue by tomitrescak** [pyodide/pyodide#3912]
## 🐛 Bug

I have a multi-tab environemnt where I save the files to the virtual drive of pyodide. The `invalidate_caches` works for the first time when the file has been saved to the virtual drive. Unfortunately, when the file is changed and written to the virtual drive with a different content it does not refresh,

### To Reproduce

```python
import importlib
from pathlib import Path
Path("mymodule.py").write_text("""\
def hello():
  print("hello world!")
"""
)
importlib.invalidate_caches() # Make sure Python notices the new .py file
from mymodule import hello
hello() # <-- ALL GOOD!


Path("mymodule.py").write_text("""\ 
def hello(): 
  print("hola mundo!") 
""" 
) 
importlib.invalidate_caches() # Make sure Python notices the new .py file 
from mymodule import hello 
hello() # <-- ERROR prints "hello world"
```

### Expected behavior

the second call of `hello()` should print `hola mundo!`

### Environment

- Pyodide Version 0.23.2
- Browser version: Chrome, latest
- Any other relevant information:

**Comment by hoodmane** [comment]
This isn't a bug in Pyodide because you'll get the same behavior in native Python.

**Comment by tomitrescak** [comment]
Yup, and just to help the noobie the solution is to use the following method to delete it from the cache between saves:

```
import sys
del sys.modules['mymodule']
```

so the full solution would be:

```python

import importlib 
from pathlib import Path 
import time
import sys

del sys.modules['mymodule']
 
Path("mymodule.py").write_text("""\
def hello(): 
  print("hello world!") 
""" 
) 
# importlib.invalidate_caches() # Make sure Python notices the new .py file 
from mymodule import hello 
hello() 

del sys.modules['mymodule']

with open("mymodule.py", "w") as f:
     f.write("""\
def hello():  
  print("hola mundo!")  
""" )

# importlib.invalidate_caches()
from mymodule import hello  
hello()  # <-- 🕺 yea baby! "hola mundo!"
```

**Comment by hoodmane** [comment]
It's hit or miss for me whether `del sys.modukes['mymodule']` works. Which is strange. A bunch of other people report it working for them, but when I tried the code with `del sys.modukes['mymodule']` I saw `hello world` twice. Otherwise I would have suggested it. No idea why other people see it working but I don't...

**Comment by tomitrescak** [comment]
That’s not good ;( I will have to test it thoroughly then :/

**Comment by hoodmane** [comment]
I just tried your code out both in Pyodide and with native Python 3.11 on linux and both ways it worked. So hopefully I just messed up something silly when I tried it before.
