### ISSUE TITLE
getattr(Array, 'from') raises AttributeError

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyodide/pyodide#3921]
## 🐛 Bug

The example in [How can I access JavaScript objects/attributes in Python if their names are Python keywords?](https://pyodide.org/en/stable/usage/faq.html#how-can-i-access-javascript-objects-attributes-in-python-if-their-names-are-python-keywords) raises `AttributeError: from`

### To Reproduce

```html
<!doctype html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        console.log(pyodide.runPython(`
            import sys
            sys.version
        `));
        pyodide.runPython(`
from js import Array
fromFunc = getattr(Array, 'from')
print(fromFunc([1,2,3]))
		`);
      }
      main();
    </script>
  </body>
</html>
```

![image](https://github.com/pyodide/pyodide/assets/42288570/f34b43bd-827f-43a4-8808-c5a9db7b7d5a)

### Expected behavior

No exception raised and I can use the `fromFunc`.

### Environment

- Pyodide Version: 0.23.2
- Browser version: Edge Version 114.0.1823.41 (Official build) (64-bit)

### Additional context

I'm trying to use PIXI.js and would like to be able to use its `PIXI.Sprite.from` method.

### Workaround

Downgrade to 0.21.2 (random choice). Then it works

![image](https://github.com/pyodide/pyodide/assets/42288570/118930ea-5901-45a4-870c-18fe20d7430c)

0.22.1 is the latest version of Pyodide I can get this working with.

**Comment by ryanking13** [comment]
Thanks for the report @MarcSkovMadsen.

We changed how we handle reserved keywords in https://github.com/pyodide/pyodide/pull/3617, so you need to append the underscore now:

```python
from js import Array

Array.from_
getattr(Array, "from_")
```

We need to update the document.

**Comment by hoodmane** [comment]
Huh I wonder why we don't make `getattr(Array, "from")` work too...

**Comment by ryanking13** [comment]
> Huh I wonder why we don't make getattr(Array, "from") work too...

**Comment by hoodmane** [comment]
We should probably release an 0.23.3 with a fix for this.
