### ISSUE TITLE
Python Callables are not instanceof Function

### ISSUE THREAD

**Issue by JeffersGlass** [pyodide/pyodide#3924]
## 🐛 Bug

Using the `instanceof` operator on PyProxy's of Python Functions (or other Callables) returns False.

### To Reproduce

All of the following result in `false`:

```js
const pyFunc_0 = pyodide.runPython(`
    lambda: print("zero")
`);

const pyFunc_1 = pyodide.runPython(`
    from pyodide.ffi import create_proxy
    create_proxy(lambda: print("one"))
`);

const pyFunc_2 = pyodide.runPython(`
    def foo():
        print("two")
    foo
`)

const pyFunc_3 = pyodide.runPython(`
    class A():
        def a(self):
            print("three") # method from class
    A.a
`)

const pyFunc_4 = pyodide.runPython(`
    class A():
        def a(self):
            print("four") # method from instance
    A().a
`)

const pyCallable_5 = pyodide.runPython(`
    class B():
        def __call__(self):
            print("five (B as a callable instance)")

    b = B()
    b
`)

console.log(pyFunc_0 instanceof Function);
console.log(pyFunc_1 instanceof Function);
console.log(pyFunc_2 instanceof Function)
console.log(pyFunc_3 instanceof Function)
console.log(pyFunc_4 instanceof Function)
console.log(pyCallable_5 instanceof Function)

// Call all the things, to verify they really are callable
pyFunc_0()
pyFunc_1()
pyFunc_2()
pyFunc_3('a')
pyFunc_4()
pyCallable_5()
```

### Expected behavior

I'd expect Python callables (or at least functions/lambdas) make `instanceof Function` true.

### Environment

- This the case in Pyodide:
  -  0.23
  -  0.22
  -  0.21
  -  0.20 (*with the previous import of `create_proxy` from just the `pyodide` module)
  -  0.19 (*with the indexURL supplied to `loadPyodide`)
  - *That's as far as I got; in 0.18 and earlier, this code throws a fatal error: `TypeError: Module._run_python_simple_inner is not a function`

**Comment by hoodmane** [comment]
Thanks for another great bug report @JeffersGlass!

**Comment by WebReflection** [comment]
it looks like [PyProxyHandlers](https://github.com/pyodide/pyodide/blob/main/src/core/pyproxy.ts#L2030-L2121) misses the `getPrototypeOf` *trap* which could return `Function.prototype` if the received target is `typeof 'function'` while returning `Object.getPrototypeOf(target)` in other cases (or any other primitive).

```js
const handlers = {
  getPrototypeOf(target) {
    return typeof target === 'function' ?
      Function.prototype :
      Object.getPrototypeOf(target);
  }
};

// example
const target = function () {};
Object.setPrototypeOf(target, {});
target instanceof Function; // false

new Proxy(target, handlers) instanceof Function; // true
```

**Comment by hoodmane** [comment]
But then `new Proxy(target, handlers) instanceof PyProxy;` would be false. Is there any reason that using a `getPrototypeOf` trap is better than the approach I'm using of calling `setPrototypeOf` on the target? What are the performance implications of the `getPrototypeOf` trap?

**Comment by WebReflection** [comment]
when proxies are around, performance implications are usually easily answered as *worse than no proxies* but here the issue is that functions are not recognized as such in the wild so libraries will fail if `instanceof Function` check is used (for whatever reason). In any case, `etPrototypeOf` is as fast as `__proto__` access, not a big deal, it's like accessing any property, the `setPrototypeOf` is actually slower, but here it doesn't matter that much, as long as the code works as expected.

The `instanceof PyProxy` looks like an internal implementation detail, the `instanceof Function` instead looks like a user-land code that should "just work".
