### ISSUE TITLE
pyodide - requests module is not available

### ISSUE THREAD

**Issue by andresn** [pyodide/pyodide#398]
Any chance you'll add this? I'm looking to bring in data from Google Sheets.

```
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 3, in <module>
ModuleNotFoundError: No module named 'requests'
```

**Comment by hamilton** [comment]
@andresn FYI I moved this over to the Pyodide repository ~

**Comment by kwmiebach** [comment]
If the requests module is not available, is there any other way to fetch data over http in pyodide?

**Comment by gijswobben** [comment]
How about something like this:

```
import json
from js import window

print(
    window.fetch("https://jsonplaceholder.typicode.com/todos/1")
    .then(lambda response: response.text())
    .then(lambda data: print(json.dumps(json.loads(data), indent=4)))
)
```

**Comment by preetiverma525** [comment]
Is there any way to use the post api in pyodide

**Comment by rth** [comment]
> is there any other way to fetch data over http in pyodide?

Yes, with [`pyodide.open_url`](https://pyodide.readthedocs.io/en/latest/python-api/pyodide.open_url.html#pyodide-open-url) or using Web APIs directly e.g. with `window.fetch` (as mentioned above) or XMLHttpRequest (see `open_url` [implementation](https://github.com/iodide-project/pyodide/blob/8c22c98a43e228c213f3f1dd7eae79ac88da4e90/src/pyodide.py#L14))

> Is there any way to use the post api in pyodide

Similarly you [can make POST API calls](https://stackoverflow.com/a/64789621/1791279) with `XMLHttpRequest`  (ref https://github.com/iodide-project/pyodide/issues/797)

**Comment by Perzan** [comment]
Maybe a requests implementation could be made on top of these. Any thoughts?

**Comment by hoodmane** [comment]
@Perzan the main issue is that the `requests` is synchronous whereas `fetch` is asynchronous. It is possible to make synchronous calls with `XMLHttpRequest`, but it can't support very many options and is not very efficient. 

I think `requests` relies on `Lib/http.client.py` which relies on `Lib/sockets.py` which relies on `socketmodule.c` which needs `<sys/socket.h>`. Emscripten provides `<sys/socket.h>` support but if we used this, then the http requests would only work if we used them with a custom server that accepts web socket connections (or proxied all requests through such a server that could forward the requests as true http requests). So that wouldn't be ideal.

So the best approach is to port `http.client` and not support anything that relies directly on sockets, in other words this issue will be resolved by #140.

**Comment by henryiii** [comment]
It seems both this methods do not handle redirects (with very unhelpful errors):

```python
>>> import pyodide

>>> inp = pyodide.open_url("https://git.io/JJYDE")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 41, in open_url
    req.send(None)
  File "[native code]", line 0, in send
JsException: NetworkError:  A network error occurred.

>>> inp = await pyodide.http.pyfetch("https://git.io/JJYDE")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 233, in pyfetch
    url, await _jsfetch(url, to_js(kwargs, dict_converter=Object.fromEntries))
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
TypeError: exceptions must derive from BaseException
```

Replacing with the redirected URL works.

**Comment by rth** [comment]
Yes, thanks. I think we should add a redirect='follow' default argument and pass it to JS fetch.

**Comment by hoodmane** [comment]
But there is something to be fixed in our error handling system for async functions, since:
```js
async function f(){
    g();
}
function g(){
    throw new Error("hi!");
}
pyodide.runPythonAsync(`
from js import f
await f()
`);
```
also shows no js stack frames even though the error thrown has frames from f and g.

**Comment by hoodmane** [comment]
Ohhh Safari... Presumably the `BaseException` thing means that we aren't feature detecting errors correctly on Safari.

**Comment by pquentin** [comment]
urllib3 2.2.0 supports Pyodide: https://urllib3.readthedocs.io/en/stable/reference/contrib/emscripten.html. Which means requests supports it too.

**Comment by ryanking13** [comment]
Yes, closing as resolved now. If you have issues with using requests in the future, please open a new issue rather than commenting further on this issue. This will make it easier for us to track the issue.
