### ISSUE TITLE
[feature request] Binary downloads support for pyodide.open_url

### ISSUE THREAD

**Issue by vadimkantorov** [pyodide/pyodide#400]
**text is updated**

Proposal: a sync (and maybe async in future) extension of `pyodide.open_url` to support byte array / BytesIO return type. For small dynamic downloads even the sync version would be useful.

The bytes magic Iodide feature request is tracked in https://github.com/iodide-project/iodide/issues/1786

**Comment by vadimkantorov** [comment]
An example of hacks for Blob->memoryview:
https://alpha.iodide.io/notebooks/1336/?revision=10235

What also worked for me:
```
%% js
(async () => {dt = await new Response(electionsData).arrayBuffer()})();
%% py
from js import dt
import io, zipfile
z = zipfile.ZipFile(io.BytesIO(dt))
```

**Comment by vadimkantorov** [comment]
A correction: the method with FileReader works, but for some reason my method with the `new Response(...).arrayBuffer()` does not

**Comment by vadimkantorov** [comment]
Tracked in https://github.com/iodide-project/iodide/issues/1686 on iodide side

**Comment by hamilton** [comment]
Thanks for the issue @vadimkantorov. I'm realizing  iodide-project/iodide#1686 was fixed with a recent PR but I didn't update the docs accordingly, so I'm going to close 1686 and file a new issue to update the docs. You can try on the `master` branch (not deployed to alpha.iodide.io yet):

```
%% fetch
arrayBuffer: data = files/test.bin
```

**Comment by vadimkantorov** [comment]
Should pyodide still extend open_url to support a pure python solution?

**Comment by hamilton** [comment]
Probably. @mdboom any thoughts there?

**Comment by mdboom** [comment]
The tricky bit is that the browser requires that binary data is fetch asynchronously, and `open_url` is intended to be easy-to-use from Python and synchronous.  However, with the support for the `async` keyword that's growing in #245, we could probably make the async call convenient enough.

**Comment by vadimkantorov** [comment]
I think feature parity of `pyodide.*` analog of the fetch block is quite needed because it can be dynamic, e.g. the user may want to provide the URL's to their custom data files. And if it can support parallel execution (via async/await and some Promise.all python's analog), the better.

**Comment by vadimkantorov** [comment]
@hamilton A suggestion: a nightly.iodide.io version with the latest deployed version (for faster try-outs and feedbacks)

**Comment by mdboom** [comment]
We already have `definitely-staging.iodide.io` that tracks master of Iodide.  Doing the same for Pyodide is a bit trickier given its size, but there are plans to track pyodide master there eventually as well.

**Comment by arogozhnikov** [comment]
ehm, what are my options these days? I'm trying to download image from web and use pythonic tools, but I'm stuck at this  issue

**Comment by arogozhnikov** [comment]
like, I'm ready to use anything just to get binary blob from the web, but I see no options besides open_url which breaks binary blob by some inobvious transforms

**Comment by hoodmane** [comment]
It's not possible to do a synchronous download of a `Blob`, in fact most of the options for `XMLHttpRequest` are disabled when it is done synchronously. Instead you should use the `fetch` API:
```py
from js import fetch
import numpy as np
response = await fetch("https://raw.githubusercontent.com/pyodide/pyodide/main/docs/_static/img/pyodide-logo-readme.png");
js_buffer = await response.arrayBuffer()
py_buffer = js_buffer.to_py()
np.frombuffer(py_buffer, dtype=np.uint8)
```
Here the data is downloaded into an `ArrayBuffer` and then must be copied into the wasm heap (by `js_buffer.to_py()`).

**Comment by hoodmane** [comment]
The `js_buffer` also has an `assign_to` API if you want to write into an existing buffer:

```
js_buffer.assign_to(my_buffer[:js_buffer.byteLength])
```
Here `my_buffer` can be anything that implements the Python buffer protocol and has a size of at least `js_buffer.byteLength` bytes.

**Comment by arogozhnikov** [comment]
thank you @hoodmane I've tried your suggestion and it works, more precisely
await fetch -> response.arrayBuffer -> to_py -> np.frombuffer -> to_bytes -> BytesIO -> PIL.Image.Open 

looks a bit mad for 'get an image' task, but this works

**Comment by hoodmane** [comment]
You can skip the `numpy` steps and just do:
`await fetch -> response.arrayBuffer -> to_py -> BytesIO -> PIL.Image.Open`

```python
await pyodide.loadPackage("pillow")
await pyodide.runPythonAsync(`
from js import fetch
from io import BytesIO
import PIL.Image
response = await fetch("https://raw.githubusercontent.com/pyodide/pyodide/main/docs/_static/img/pyodide-logo-readme.png");
js_buffer = await response.arrayBuffer()
img = PIL.Image.open(BytesIO(js_buffer.to_py()))
`)
```

**Comment by hoodmane** [comment]
It would be good to eventually add convenience methods for stuff like this, but I've been focused on making sure things are actually possible. I don't know enough about peoples' use cases yet too. Contributions of convenience methods would be welcome though.

**Comment by hoodmane** [comment]
I am going to close this. I would really rather deprecate `open_url` than add features to it. Synchronous `XMLHttpRequest` doesn't support features like this. If it did, this would be an easy fix...

**Comment by gitkwr** [comment]
Hi, I'm trying to load xlsx files here and this code doesn't appear to work. I did use micropip to load openpyxl, and pd.read_excel('filename.xlsx') works when I manually place a valid xlsx file in the memory (such that os.listdir() will list that xlsx file) - so I know that openpyxl is correctly loaded and working. Here is the code for xls that does work:
```
response = await fetch('${fileUrl}')
js_buffer = await response.arrayBuffer()
excel_data = pd.ExcelFile(BytesIO(js_buffer.to_py()))
dFrame = excel_data.parse(excel_data.sheet_names[-1])
```
