### ISSUE TITLE
WebpackIgnore comments disappear when using esbuild instead of rollup

### ISSUE THREAD

**Issue by Kol96** [pyodide/pyodide#4004]
### To Reproduce

webpackIgnore comments disappear  from the development JavaScript bundle
bad case: https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js
good case: https://cdn.jsdelivr.net/npm/pyodide@0.23.4/pyodide.js

### Expected behavior

keep webpackIgnore comments
`await import(/* webpackIgnore: true */url)`

### Environment

- Pyodide Version: latest
- Browser version:
- Any other relevant information:

**Comment by rth** [comment]
Are you using [`pyodide-webpack-plugin`](https://github.com/pyodide/pyodide-webpack-plugin)? That's the recommended way of using webpack with Pyodide cc @mneil 

But otherwise yes, sounds like a bug, thanks for the report.

**Comment by Kol96** [comment]
> 



> Are you using [`pyodide-webpack-plugin`](https://github.com/pyodide/pyodide-webpack-plugin)? That's the recommended way of using webpack with Pyodide cc @mneil
> 
> But otherwise yes, sounds like a bug, thanks for the report.

It seems that using string-replace-loader in webpack can solve my problem, I ultimately opted for directly importing pyodide.js using cdn.
`import(/* webpackIgnore: true */ "https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js");`

By the way, esbuild may not be able to solve this problem according to this [issue](https://github.com/evanw/esbuild/issues/221)

**Comment by hoodmane** [comment]
We can probably fix this with the legal comments option in esbuild by setting legalComments "inline", writing `/*! webpackIgnore: true */` and then using sed to remove the exclamation point.

**Comment by Kol96** [comment]
> We can probably fix this with the legal comments option in esbuild by setting legalComments "inline", writing `/*! webpackIgnore: true */` and then using sed to remove the exclamation point.

It didn't work, legal comments only works on the top of the file. Maybe just match `import(` and replace it with `import(/* webpackIgnore: true */ ` after esbuild done.

From esbuild doc:
Note that "statement-level" for JS and "rule-level" for CSS means the comment must appear in a context where multiple statements or rules are allowed such as in the top-level scope or in a statement or rule block. So comments inside expressions or at the declaration level are not considered legal comments.

**Comment by hoodmane** [comment]
> Or leave it to webpack plugin, casue there are more than one bundlers, pyodide cannot be adapted for each tools.

Yes downstream handling it is ideal...
