### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by jonashaag** [pyodide/pyodide#4016]
## 🐛 Bug

When I load a specific Pyodide wheel I've built I'm getting this:

```
Pyodide has suffered a fatal error. Please report this to the Pyod
ide maintainers.
The cause of the fatal error was:
RangeError: Array buffer allocation failed
Look in the browser console for more details.
```

Full error in the screenshot below

### To Reproduce

Install my wheel, I'm happy to share but it's almost 200 MB

### Expected behavior

Should not crash

### Environment

- Pyodide Version: 0.23.4
- Browser version: Latest Safari or Edge on macOS
- Any other relevant information:

### Additional context

<img width="1011" alt="Screenshot 2023-07-25 at 21 38 14" src="https://github.com/pyodide/pyodide/assets/175722/d9bea2cd-87c5-4323-ba58-75c811be025c">

**Comment by ryanking13** [comment]
Thanks for the report @jonashaag! Could you share your wheel so we can reproduce it?

**Comment by jonashaag** [comment]
Does this work? https://easyupload.io/vx367j

```
MD5 (dist/polars-0.18.8-cp38-abi3-emscripten_3_1_32_wasm32.whl) = 094dcadf5e41812058691cb02e692a18
```

**Comment by jonashaag** [comment]
I think that's just the size of the `.so`... maybe I can bring it under 2 GB

**Comment by jonashaag** [comment]
Here's a smaller one, this fails with another exception: https://easyupload.io/4886sw

```
MD5 (target/wheels/polars-0.18.8-cp38-abi3-emscripten_3_1_32_wasm32.whl) = efc989e2f899058abffb88cee9703b6b
```

**Comment by ryanking13** [comment]
I get the same error in Chrome (Array buffer allocation failed). In firefox, I get the following error message:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 603, in install
    await gather(*wheel_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 246, in install
    await self.load_libraries(target)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 237, in load_libraries
    await gather(*map(lambda dynlib: loadDynlib(dynlib, False), dynlibs))
pyodide.ffi.JsException: CompileError: wasm validation error: at offset 0: module too big
```

I am not sure if there is something possible on the Pyodide side... if the size of a WASM module exceeds the browser limitation.

> I think that's just the size of the .so

I think a `.so` file with ~2GB is not very normal, regarding that the size of the same `.so` file in the manylinux wheel is only ~50MB. Could you please explain to us why it is so big? Maybe we can discuss how to make the size smaller, or how to split a single big WASM module into several modules.

**Comment by hoodmane** [comment]
> Does the decompressed .whl file need to be smaller than 2 GiB?

I think the browser returns OOM on attempt to allocate **any** buffer of size greater than 2 gigabytes. So yes if any step exceeds that, you'll probably be in trouble.
