### ISSUE TITLE
List of pyodide client implementations

### ISSUE THREAD

**Issue by gnestor** [pyodide/pyodide#403]
Eventually, it would be great to have an _awesome-pyodide_ repo to compile pyodide implementations, examples, language plugins, etc.

In the meantime, we can start collecting client/front-end implementations here:

* Iodide: https://alpha.iodide.io/notebooks/300/
* Observable: https://observablehq.com/@gnestor/exploring-reactive-pyodide-in-observable
* jyve-pyodide (Jupyter kernel): https://github.com/deathbeds/jyve/pull/27

**Comment by PythonLinks** [comment]
So I created such a catalogue of links. 
https://pythonlinks.info/python-links
It currently has 8 links.  When it grows a little larger, I will add a new category.  A basic principal in human factors is that there should be no more than about 7 items in any category.  So it is a tree, a tazonomy of links. 

It has a much better user interface than the awesome lists on Github. 

If you want to contribute content, I invite you to sign up on the web site.  When I return from PyCon USA, I will give you write permission.  

Next up I want to link to all the articles about PyOdide.  I also want to do a review of the examples on the server.  Create a taxonomy of Iodide noteooks.  BUt that is a lot harder to figure out which are the good ones and which are the bad ones. 

Does anyone want to help?

You may also like my maps of Python companies.  
Here is an example. 
https://PythonLinks.info/warsaw. 

If you want I can also create a global map of companies using PyOdide. Generally peole find these maps very interesting.

**Comment by mdboom** [comment]
@PythonLinks: Thanks.  It's always helpful -- both for people and for search engines -- to build these kinds of indices.

Can you please forgive one super nitpick comment: "PyOdide" -> "Pyodide"?

I think long term, we'll probably want to maintain a canonical index to some of these resources in the pyodide docs (or a related github repo) as well.

**Comment by shi-yan** [comment]
I'd like to show you https://epiphany.pub/ , this is a site I'm working on and is still at an early stage. 

Inspired by http://distill.pub, my goal is to create a tech blogging platform that allows interactive content, a mixture of medium.com and jupyter notebook.

Thank you very much for pyodide, I was able to add support for python!

**Comment by SimonBiggs** [comment]
@gnestor here is another, very alpha, just beginning, web app using pyodide:

https://app.pymedphys.com

...certainly quite rough at the moment. But working on it :).

**Comment by rth** [comment]
The list of Pyodide client implementations can be found in https://pyodide.org/en/stable/project/related-projects.html . Feel free to add to that list.
