### ISSUE TITLE
Package request for pydeseq2

### ISSUE THREAD

**Issue by IvanRatushnyy** [pyodide/pyodide#4031]
## 🐍 Package Request

- Package Name and Version : **pydeseq2, 0.4.0**
- Package URL : **https://pypi.org/project/pydeseq2/**
- Package Dependencies that needs to be resolved first: **update [matplotlib](https://pypi.org/project/matplotlib/) version to 3.6.2 or above**

**Comment by rth** [comment]
Indeed matplotlib needs to be updated, but I don't know if they really need that recent version of matplotlib as [that comment](https://github.com/owkin/PyDESeq2/blob/290d067c047a66ef3a6ff62820caec9a7d4b0534/setup.py#L37) says.

You can manually install its dependencies and ignore that version requirements with something like,
```py
>>> import micropip
>>> # manually install dependencies
>>> await micropip.install(['matplotlib']) # and possibly other needed packages
>>> await micropip.install(['pydeseq2', keep_going=True, deps=False)
>>> import pydeseq2
>>> pydeseq2
<module 'pydeseq2' from '/lib/python3.11/site-packages/pydeseq2/__init__.py'>
```

this might need a bit more tinkering to use the package, but in any case, it's a pure Python package with a wheel that is uploaded on PyPI, so there is no need to package it in Pyodide. Closing this issue, but don't hesitate to comment further.
