### ISSUE TITLE
Add mounted directory to sys.path

### ISSUE THREAD

**Issue by Duncanr-glitch** [pyodide/pyodide#4045]
## 🚀 Feature

When mounting a local file directory that contains a local python module, it would be nice to have that newly mounted directory added sys.path -- either automatically or with an option to add it:

My directory has this file structure:
-repo
  --modules (local python module) 

``` 
let mountDir = "/pkg";
pyodide.FS.mkdir(mountDir);
pyodide.FS.mount(pyodide.FS.filesystems.NODEFS, { root: "." }, mountDir);
```
Above is the code I used to mount the directory (no problem there), and then I wanted to import from my modules module, I had to first add "/pkg" to sys.path:

```
pyodide.runPython(`
import sys
sys.path.append("/pkg")
`)
```

and then importing my modules like normal worked perfectly.

I was also working in a Node environment, so that's why I was holding my python files with my JS code

### Motivation

Adding a mounted directory to python path for imports automatically reduces the amount of boilerplate and confusion when trying to import local modules.

### Pitch

Automatically add any  mounted directory to path for python imports.

### Alternatives

At least add an option for adding to path with the mounted directory if its determined that automatically adding the directory to path shouldn't be either the default  or only behavior.

**Comment by ryanking13** [comment]
Thanks for opening the issue @Duncanr-glitch.

I agree that it might reduce the amount of boilerplate code, but I don't think there is confusion about the current behavior. I think it's more confusing if mounting a folder has the side effect of modifying sys.path, people might mount a folder for various reasons. I also think it is natural for Python devs to modify sys.path manually when they need to import modules from somewhere else. So I am sorry but I am -1 for this suggestion.

**Comment by hoodmane** [comment]
Agreed I am also against this. It is perfectly clear to do

```js
pyodide.FS.mount(mountDir, ...);
const pysys = pyodide.pyimport("sys");
pysys.path.append(mountDir);
```
or whatever. There are plenty of reasons for mounting directories where you don't necessarily want them on the path...
