### ISSUE TITLE
Linker error when building large shared library

### ISSUE THREAD

**Issue by julian-smith-artifex-com** [pyodide/pyodide#4048]
## 🐛 Bug

I am seeing many occurrencies of errors like below, when linking a large shared library:

```
[wasm-validator error in function 30] unexpected false: Bulk memory operations require bulk memory [--enable-bulk-memory], on 
(memory.copy
 (local.tee $4
  (call $1412
   (local.get $0)
   (i32.add
    (local.tee $5
     (call $fimport$14
      (local.get $3)
     )
    )
    (i32.const 2)
   )
  )
 )
 (local.get $3)
 (local.get $5)
)
```

The link command is:
```
/tmp/tmp_hnrr5zs/cc --enable-bulk-memory -Wl,--gc-sections -Wl,-s -o libmupdf.so [many .o files] -lm -shared -sSIDE_MODULE
```
Note that the link command already contains the recommended `--enable-bulk-memory`.

Interestingly the link command seems to succeed, despite returning non-zero to the shell:

* The failing link command does actually create a new `libmupdf.so`.
* A second build skips the link stage because `libmupdf.so` is newer than any of its prerequisites.
* The second build ends up producing a wheel that seems to work in a Pyodide browser console.
* I haven't tested the wheel very much, so it's possible that some functionality is broken due to the linker errors.

### To Reproduce

It's difficult to give a simple reproducer because i'm building MuPDF (a PDF C library) into a shared library then building PyMuPDF (a Python extension module for manipulations PDF documents, that uses MuPDF) and the MuPDF shared library into a Python wheel.

I'm hoping that someone will understand the error messages and suggest things i can try. If not, i'll put together something that will reproduce my build.

### Expected behavior

The link command should not show error messages, and should succeed.

### Environment

- Pyodide Version:
  https://github.com/emscripten-core/emsdk.git c2260b4f28f53b411 "3.1.42 (#1238)"

- Browser version:
  Firefox 114.0.2 64-bit on OpenBSD 7.3.

- Any other relevant information:

### Additional context

This issue is following on from #4019.

**Comment by ryanking13** [comment]
Thanks for the report. I am not sure but I think what happens is:

1. A shared library is built with build memory option correctly, as it contains `memory.copy` operation. (You can probably use [wasm2wat](https://webassembly.github.io/wabt/demo/wasm2wat/) to double-check).
2. The optimization step which happens after building a shared library (`wasm-opt`) does validation on the shared library. But `--enable-bulk-memory` option is not passed to `wasm-opt`, so it fails as it thinks the system does not support bulk memory.

I am not sure why the flag is not propagated to wasm-opt. Could you try the following approaches?

- add `-mbulk-memory` flag
- add `-Wl,--enable-bulk-memory` flag
- add `-Wl,-sBINARYEN_EXTRA_PASSES="--enable-bulk-memory"` flag

**Comment by hoodmane** [comment]
If you can find a small reproduction, this would potentially make a good Emscripten bug report. @sbc100 are you aware of any issues like this?

**Comment by julian-smith-artifex-com** [comment]
Thanks everyone for the various responses.

> I am not sure why the flag is not propagated to wasm-opt. Could you try the following approaches?
> 
>     * add `-mbulk-memory` flag

This appears to have no effect.

>     * add `-Wl,--enable-bulk-memory` flag
>     * add `-Wl,-sBINARYEN_EXTRA_PASSES="--enable-bulk-memory"` flag

These result in:
```
wasm-ld: error: unknown argument: --enable-bulk-memory
wasm-ld: error: unknown argument: -sBINARYEN_EXTRA_PASSES=--enable-bulk-memory
```

> This is a known issue with the clang / wasm-opt integration: [llvm/llvm-project#55781](https://github.com/llvm/llvm-project/issues/55781)

So i guess this is what's going on.

I've managed to get my build to work by moving  `emsdk/upstream/bin/wasm-opt` to `wasm-opt-0` and creating a new `wasm-opt` that defers to `wasm-opt-0` if run with `--version`, but otherwise does nothing.

Obviously this is a horrible hack, so it would be great if [llvm/llvm-project#55781](https://github.com/llvm/llvm-project/issues/55781) could be fixed properly.

Thanks again.

**Comment by hoodmane** [comment]
I guess I'll close this as an upstream bug then (unless anyone objects).
