### ISSUE TITLE
Including pyodide-http update in release

### ISSUE THREAD

**Issue by wragge** [pyodide/pyodide#4068]
## 🐍 Package Request

The [pull request](https://github.com/pyodide/pyodide/pull/3937) to update pyodide-http to version 0.2.1 was merged a couple of months ago but didn't make it in to the 0.23.4 release. I was just wondering if there was a problem, or when it might be included. Thanks!

**Comment by ryanking13** [comment]
For minor releases, we often cherrypick only bug fixes, so your PR was not included in 0.23.4, and it will be included in 0.24.0.

Regarding 0.24.0 release, most Pyodide core devs were busy with other things for a few months, so we were not releasing a new version, but I think we need to release it soon.

**Comment by hoodmane** [comment]
Yeah I think we should make a release when #4035 is merged.
