### ISSUE TITLE
Release 0.24.0 

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#4084]
__TODO__

- [x] Merge PRs with [0.24.0 milestone](https://github.com/pyodide/pyodide/milestone/16)
- [x] Release note
- [x] Update packages #4088 
  - micropip 0.4.0
- [x] #4116
- [x] Enable disabled packages #4088 
  - wordcloud

**Comment by hoodmane** [comment]
I started on the release notes.

**Comment by michaelweinold** [comment]
Really looking forward to 0.24.0 - any chance this will drop before the end of the week 🤩

**Comment by hoodmane** [comment]
I hope so. We only have to finish the release notes, but I've had a migraine for a few days and haven't been able to do much work on it.

**Comment by ryanking13** [comment]
> but I've had a migraine for a few days and haven't been able to do much work on it.

I hope you feel better soon!
