### ISSUE TITLE
Cannot install pyodide-cli

### ISSUE THREAD

**Issue by shubh3ai** [pyodide/pyodide#4115]
## 🐛 Bug

I am following the documentation from the [page](https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-packages-out-of-tree) to integrate my own C++ library with Pyodide. 
On trying to install with the command `pip install pyodide-build` and then checking the pyodide version using `pyodide config get emscripten_version`. I get the error `pyodide: command not found`. 

This probably that pyodide does not install CLI by default. I tried to install the CLI using `pip install pyodide-cli` which threw an error that no matching distribution found. 
### To Reproduce
`pip install pyodide-build && pyodide config get emscripten_version`

Type:

### Expected behavior

Ideally the cli should be automatically installed or `pip install pyodide-cli` should work.
### Environment

- Pyodide Version: 0.19.1
- Browser version: NA
- Any other relevant information:

**Comment by ryanking13** [comment]
> Pyodide Version: 0.19.1

Pyodide CLI has been introduced from Pyodide 0.22.0. Could you please use a newer version of Pyodide (I recommend using the latest version of Pyodide)? Also building packages out-of-tree is not supported in Pyodide < 0.22.0.

**Comment by simoncozens** [comment]
I just hit this same problem, and the answer was "upgrade Python". If you're on Python 3.9, you'll get pyodide-build 0.19.1 when you install from pip because newer pyodide-build versions require >=3.10.
