### ISSUE TITLE
pyodide.http.open_url response error

### ISSUE THREAD

**Issue by niuniudd** [pyodide/pyodide#4119]
### To Reproduce
run my code In this websit：
https://[pyodide.org/en/stable/console.html](https://pyodide.org/en/stable/console.html)
```
import pyodide.http
print(pyodide.http.open_url('https://www.baidu.com/').read())
```
output：
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python311.zip/pyodide/http.py", line 45, in open_url
    req.send()
pyodide.ffi.JsException: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load '
https://www.baidu.com/'.
```

### Environment

- Pyodide Version:
- Browser version:
- Any other relevant information:

**Comment by ryanking13** [comment]
This is because `https://www.baidu.com` does not include CORS headers in its response.

See: https://github.com/pyodide/pyodide/issues/2659#issuecomment-1145339210
