### ISSUE TITLE
XSS issues in pyodide

### ISSUE THREAD

**Issue by bugzpodder** [pyodide/pyodide#4120]
## 🚀 Feature

I want to run pyodide in a sandboxed environment.  Previous discussion !959 cc @hoodmane 

### Motivation

Currently pyodide allows arbitrary js execution via `pyodide.code.run_js` and `js.document`.
js could be unregistered by `unregisterJsModule` functionality (I think).  but `pyodide.code.run_js` still allows user to execute js code via eval.

This is usually not an issue for static js code controlled by the owner of a site.  However it becomes an issue when we allow one user to execute python code that a different user authored.  In js land, a similar analogy would that static script tags on a site would not be a problem, but as soon as we allow a user to write arbitrary script tags for another user we have an issue!

### Pitch

Allow option to disable run_js

**Comment by hoodmane** [comment]
Have you thought about using the no-unsafe-eval content security protocol? We can discuss things like this but it's easy to give people the illusion of creating isolation and it's hard to actually do it.

**Comment by bugzpodder** [comment]
https://github.com/pyodide/pyodide/blob/f438a8daec5f2a0b2730d99203835073c28e606b/src/py/pyodide/_run_js.py#L4
Ok looks like run_js invokes js, so if I unregisterJsModule(js) it should just work.  I will close out after verifying.

**Comment by bugzpodder** [comment]
@hoodmane looks like unregisterJSModule("js") doesn't work.  I will close this and open a bug request.

**Comment by hoodmane** [comment]
Have you thought about using the no-unsafe-eval content security protocol? We can discuss things like this but it's easy to give people the illusion of creating isolation and it's hard to actually do it.

**Comment by hoodmane** [comment]
You can pass a different globals object to `loadPyodide`.
