### ISSUE TITLE
Force canvas redraw

### ISSUE THREAD

**Issue by void4** [pyodide/pyodide#414]
A canvas only seems to display the graphics when the python execution has stopped. Is it possible to force a redraw in a long running function?

**Comment by mdboom** [comment]
By default, Pyodide runs on the main worker thread, so blocks the canvas updating.  You could move it to a WebWorker, but there, you would not have access to the DOM and Canvas APIs.

I think you would have to break up the Python work into smaller chunks from which you return control to the main thread to make this happen.  Calling the chunk from a `timeout` handler should be sufficient.

**Comment by rth** [comment]
Closing as answered.
