### ISSUE TITLE
[Discussion] Drop support for Node versions that passed endoflife

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#4148]
## Proposal

Drop support for Node < 18 from the next Pyodide major release (0.25.0)

## Background

The endoflife of [Node.js 14 and 16 passed a few days ago](https://nodejs.dev/en/about/releases/). We just finished a major release, so I think this is a good time to talk about Node version support.

![image](https://github.com/pyodide/pyodide/assets/24893111/47e79d74-8362-493c-9ff5-49d3d5c7004d)

Here are the things that are currently associated with Node.js versions in Pyodide.

- The documentation mentions [how to run Pyodide in Node.js < 0.18](https://pyodide.org/en/stable/usage/index.html#node-js-versions-0-17)
- We have some compat codes for older Node versions
  - https://github.com/pyodide/pyodide/pull/4100#discussion_r1308449699
  -[compat.ts](https://github.com/pyodide/pyodide/blob/e2c2884e7a9afd90b23849220ee578bd2d523458/src/js/compat.ts#L40)
- JSPI requires Node >= 20
- The Docker image used for Pyodide CI uses Node 20

### Benefits from dropping Node < 18 support

- No more `node-fetch`.
- No more `--experimental-wasm-bigint` flags
- Better `MessageChannel` support (https://github.com/pyodide/pyodide/issues/4006)
- Some useful methods like [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)

### Drawbacks

- People who were using Node.js < 18 with Pyodide won't like it.

## Migration plan

- Mention minimal Node.js version support in docs
- Remove compat codes for old  Node.js versions
  - pytest-pyodide?

WDYT?

**Comment by rth** [comment]
+1 thanks for checking. If it's now deprecated, then I agree it makes sense to drop it. And also I think the type of users who use node, are more able to change the version, as opposed to some browser end users who aren't.

We could set [MIN_NODE_VERSION](https://github.com/emscripten-core/emscripten/blob/0be5b609412d5b07f8157528df8e5088dae84858/src/settings.js#L1818) in Emscripten accordingly then.
