### ISSUE TITLE
matplotlib breaks in v0.24.0

### ISSUE THREAD

**Issue by WebReflection** [pyodide/pyodide#4153]
## 🐛 Bug

In an attempt to update [polyscript](https://github.com/pyscript/polyscript/pull/38) to this latest version of Pyodide, I've smoke-tested our long working [matplotlib example](https://github.com/pyscript/polyscript/blob/main/test/matplot.html) and saw this on screen:

![Screenshot from 2023-09-18 14-27-31](https://github.com/pyodide/pyodide/assets/85749/0ba0ce87-517e-4d2b-adf2-1496b3c403cf)

### To Reproduce

  * grab [polyscript](https://github.com/pyscript/polyscript)
  * enter the folder then checkout `pyodide-update` branch
  * `npm i` followed by `npm run build` and finally `npm run server`
  * visit the localhost url and try any *matplot* example you like (they are all the same)
  * see the error ... fee free to change the version via absolute URL or local file [in here](https://github.com/pyscript/polyscript/blob/main/test/matplot.html#L12) as `version="http://localhost..."` then refresh for better debugging
  * feel free to use `NO_MIN npm run build` if you think something is wrong to the library (although the same example works by using previous version)

### Expected behavior

A page with an image once everything is done ... I just see a lot of errors instead with 0.24

### Environment

- Pyodide Version: 0.24.0
- Browser version: latest Chrome
- Any other relevant information: I can create a plain example if needed ... just let me know

**Comment by bugzpodder** [comment]
@WebReflection matplotlib works fine when loaded directly.  see this example:
https://pyscript.com/@bugzpodder/pyodide-matplotlib/latest

I have not tested polyscript.

Also packages in loadPyodide calls [loadPackages](https://github.com/pyodide/pyodide/blob/e2c2884e7a9afd90b23849220ee578bd2d523458/src/js/load-package.ts#L64) which is different from micropip.install.

**Comment by bugzpodder** [comment]
the error you see is caused by `triang = tri.Triangulation(x, y)` in your code

**Comment by WebReflection** [comment]
@bugzpodder so the issue is that 0.24.0 uses a new version of matplotlib that in turns fails with the previous code? I think that's still unexpected for users as there was no deprecation warning to date and that code works just fine with 0.23.4 but thanks for investigating this!

**Comment by rth** [comment]
No so the version of matplotlib is still [3.5.2](https://pyodide.org/en/0.24.0/usage/packages-in-pyodide.html) in both releases. I can confirm that it's a regression in v0.24.0.  Thanks for the minimal example @bugzpodder !

Most likely due to the Emscripten update. As far as I understand that symbol should be defined [there](https://emscripten.org/docs/porting/setjmp-longjmp.html) and enabled by default.

> 1: Default support, depending on the exception mode. wasm if -fwasm-exception is used, emscripten otherwise.


I have a feeling it's due to https://github.com/emscripten-core/emscripten/pull/19004 so we may need to set `SUPPORT_LONGJMP=wasm` though I'm not sure if we can have that without enabling exception handling (so it may need https://github.com/pyodide/pyodide/pull/3817 which will only be included in the next release).

**Comment by ryanking13** [comment]
Hmm, this is strange... we didn't enable wasm-exception in the Pyodide main branch so it is not clear why the symbol mismatches

**Comment by hoodmane** [comment]
I thought we had a test for `setjmp`/`longjmp` but apparently we don't, only `cpp-exceptions-test`.

**Comment by hoodmane** [comment]
wait actually we do have one, `set_jmp_func` in `cpp-exceptions-test`. Strange.

**Comment by hoodmane** [comment]
There seems to be a problem caused by `-flto`.

**Comment by hoodmane** [comment]
Opened an upstream bug report:
https://github.com/emscripten-core/emscripten/issues/20308
