### ISSUE TITLE
[feature request] Eval Python code from URL

### ISSUE THREAD

**Issue by vadimkantorov** [pyodide/pyodide#417]
When a notebook showcases some code in a GitHub repo (e.g. some data vis is in the notebook, and data-loading logic is a normal Python file/module in a GitHub repo), it would be nice to allow running code from URL. Running code from a GitHub repo/gist should be possible through https://raw.githubusercontent.com/ or GitHub API. I think both are CORS-compatible.

There are several ways of implementing this feature:
1. A new overload for `pyodide.eval_code` (and having the user format the rawgithub url)
2. A special overload for GitHub repos / gists: `pyodide.run_code_from_github` that would accept GitHub-specific path, similar to nbviewer
3. A new magic that would do code include (again, it may be GitHub-specific or not)

**Comment by vadimkantorov** [comment]
Currently a workaround is to use `pyodide.eval_code(pyodide.open_url('https://raw.github.com/...'))`, so it's not a blocker, just something to keep in mind as a very common usecase

**Comment by vadimkantorov** [comment]
I am not sure about a good design for this features. At least there are two common scenarios: 1) importing a python module from a repos / gist (may entail downloading and eval'ing other files) 2) eval'ing a singe file from a repo / gist. Implementing (1) would be much trickier without cloning a repo (maybe can be done via some import hook)

**Comment by vadimkantorov** [comment]
Thought about it more, and one way could be having `micropip` support installation from a GitHub repo / gist (like the real pip can).

**Comment by rth** [comment]
I'm wondering about the security implications of this. Granted it's running in a sandbox, but still running arbitrary code from "the internet" that could potentially change without warning sounds not that safe. For single files, maybe at least check the checksum of the content, and for git repos only allow using a particular commit?

> e.g. micropip.install_from_git('git://git@github.com:githubusername/githubrepo.git')

Maybe rather `micropip.install_from_url('https://github.com/<username>/<repo>/archive/<commit-hash>.zip')`, assuming there is a `requirements.txt` file in that repo, to avoid dealing with git?

**Comment by vadimkantorov** [comment]
Security concerns are valid. One intermediate way could be introducing a magic that allows insecure URL, but asks the user for an explicit consent at the beginning of notebook execution. Though iirc both Rust and Go allow importing from a github url without a specific commit hash - worth checking out their security considerations.

https urls are also fine! normal pip supports them too, my only concern here was consistency with pip syntax.

**Comment by pannous** [comment]
since this is(will be) a very common usecase you could simplify it to
```
%%fetch
pip: <package>
py: <url>
py: github:<username>/<repo>
```

**Comment by pannous** [comment]
Since you have control over python you can hook into `import` and automagically do micropip in the background!
```python
import transcrypt # all that's needed
```

**Comment by mauricelam** [comment]
I needed this in my project and implemented the module_loader similar to what's describe above.

https://github.com/mauricelam/pyodide-built/blob/gh-pages/module_loader.py

Right now I just patched it on top of a built version of Pyodide because I don't have Pyodide source checked out.

I can create a pull request if you are interested.

**Comment by ryanking13** [comment]
From Pyodide 0.19.0, [we provide several ways to load external Python files from URL](https://pyodide.org/en/stable/usage/loading-custom-python-code.html), and it's still OK to use `pyodide.runPython(pyodide.open_url('https://raw.github.com/...'))`.
