### ISSUE TITLE
Cannot find module 'https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js'

### ISSUE THREAD

**Issue by BiTronicsDev** [pyodide/pyodide#4174]
Hi all. I have the following problem: I'm trying to use pyodide in a react. I installed the package using npm install, and imported the loadPyodide function from it. I have this code:
```
const pyodide = await loadPyodide({
             indexURL: "https://cdn.jsdelivr.net/pyodide/v0.24.0/full/",
             fullStdLib: true,
             stdin: window.prompt,
             stdout: (text) => {
                 if (text !== "Python initialization complete") {
                     setResult(prevState => prevState + text + "\n")
                 }
             },
             stderr: (text) => {
                 setResult(prevState => prevState + text + "\n")
             }
         });
```
However I get an error:
```
Cannot find module 'https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js'
     at http://localhost:3000/static/js/bundle.js:277779:11
     at async loadScript (http://localhost:3000/static/js/bundle.js:317327:43)
     at async loadPyodide (http://localhost:3000/static/js/bundle.js:317657:5)
     at async loadPython (http://localhost:3000/static/js/bundle.js:41685:21)
     at async run (http://localhost:3000/static/js/bundle.js:41761:24)
```
How can you solve it? I would appreciate your answer.

**Comment by ryanking13** [comment]
Thanks for the report @BiTronicsDev. It is strange that the module tries to load Pyodide from the `dev` branch, not the `v0.24.0` version you provided...

Could you share us a full and minimum code that we can reproduce?

**Comment by tylfin** [comment]
I have the same issue when I try to upgrade to v0.24.*, using indexURL in the same manner:

https://github.com/tylfin/restructedpyjs/blob/186bf34ba5212c74d0825799a6ce156e58fdfc3a/src/restructedpyjs.js#L19-L24

The error stack I'm getting looks like:

```
Uncaught (in promise) Error: Cannot find module 'https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js'
    ./node_modules/pyodide lazy recursive/t/< lazy strict namespace object:5
    promise callback*t lazy strict namespace object:4
    ...
```

**Comment by rth** [comment]
Possibly related to https://github.com/pyodide/pyodide/pull/3967

>  installed the package using npm install, and imported the loadPyodide function from it

If you installed it via npm, `indexURL` is expected to be a local folder, I think. Or just don't pass that parameter, and it will use the version you installed. The default is to take artifacts from the `node_modules` which has all files necessary to load Pyodide. We should update the readme of the npm package.

Same comment for @tylfin, removing the `indexURL` argument from your code should  fix it.

**Comment by rth** [comment]
> indexURL is expected to be a local folder

Though from a user perspective, it doesn't make sense not to be able to use remote indexURL in node.  It sounds like a bug.

**Comment by tylfin** [comment]
Hmm, removing the option gives the same module error:

```
Uncaught (in promise) Error: Cannot find module 'http://localhost:8000/node_modules/pyodide/pyodide.asm.js'
    ./node_modules/pyodide lazy recursive/t/< lazy strict namespace object:5
    promise callback*t lazy strict namespace object:4
```

**Comment by esromerog** [comment]
I am having the same issue, downgraded to pyodide@0.23.4 and it works flawlessly now, but it does seem like the indexURL is broken in the current implementation. If using the latest version is strictly necessary, I think a possible solution is to add it to the project's public folder and link it there.
