### ISSUE TITLE
API Normalize package names in pyodide-lock.json

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#4182]
In https://github.com/pyodide/pyodide-lock/pull/20#issuecomment-1735331697 we discussed that it would be good to normalize the package names. This was also supported by @bollwyvl's comment in https://github.com/pyodide/pyodide-lock/pull/18#discussion_r1336556106 and also what the [PEP 691](https://peps.python.org/pep-0691/) for Simple JSON API recommends. 

In the case of pyodide, I imagine that would mean doing,

```py
packages: {
    <normalized_name>: {
              name : <normalized_name>
              depends: [<normalized_names>]
     }
}
```
so we would be repeating the normalized name twice once as the dict key, and the second time as the inner name field. 

This however means that if say we do `micropip.install('scikit-learn')` (or if it's pulled as a dependency) in the logs we would see `installing scikit_learn` which I personally find strange. Unless we de-normalize the name somehow when displaying (at least replacing `_` with `-`).

For the input `meta.yaml` this souldn't change anything, and we would only normalize the output name.

cc @ryanking13 @joemarshall

**Comment by ryanking13** [comment]
```
packages: {
    <normalized_name>: {
              name : <original_name>
              depends: [<normalized_names>]
     }
}
```

Actually, I was thinking like this, so that a package can be queried using normalized name, but we can still get the original name of a package from the value.

**Comment by rth** [comment]
I would be happy with this, and I was thinking about this as well.  Would the above work for you @bollwyvl, which means we can still remove normalization in https://github.com/pyodide/pyodide-lock/pull/18#discussion_r1332985361?

**Comment by bollwyvl** [comment]
Sure, keeping the verbatim `name` sounds good, along with some human-readable text to this effect that makes it all the way into the schema.

It turns out _dict keyed by strings matching {pattern}_, and even _list of strings matching {pattern}_  is... non-trivial with either major version of pydantic.
