### ISSUE TITLE
Paho MQTT package request

### ISSUE THREAD

**Issue by gpeyton** [pyodide/pyodide#4195]
## 🐍 Package Request

Requesting Paho MQTT.

- Package Name and Version : paho-mqtt 1.6.1
- Package URL: [https://pypi.org/project/paho-mqtt/](https://pypi.org/project/paho-mqtt/)
- Python Wheel: [https://www.piwheels.org/project/paho-mqtt/](https://www.piwheels.org/project/paho-mqtt/)
- Package Dependencies that needs to be resolved first: [https://github.com/eclipse/paho.mqtt.python/blob/master/requirements.txt](https://github.com/eclipse/paho.mqtt.python/blob/master/requirements.txt)

Please see related [question](https://github.com/pyodide/pyodide/discussions/4194) relating to `pyodide_js`

**Comment by rth** [comment]
All of these are pure Python packages, and can be installed with [micropip](https://github.com/pyodide/micropip) from PyPI. There is no packaging needed. See my answer to your other linked question. Closing, but don't hesitate to comment, if you have questions.
