### ISSUE TITLE
Emscripten.cmake missing from pyodide-build wheel

### ISSUE THREAD

**Issue by ntamas** [pyodide/pyodide#4216]
## 🐛 Bug

It seems like `Emscripten.cmake` is not bundled with `pyodide-build` wheels any more (since version 0.24.0) and I wonder whether this is a bug or an intended change. (I haven't found anything in the changelog). We were relying on the presence of the toolchain file over there in https://github.com/igraph/python-igraph/ to build a wasm wheel in CI and it is not working any more.

### To Reproduce

See, e.g., https://github.com/igraph/python-igraph/actions/runs/6459502630/job/17535393423

### Expected behavior

`pyodide-build` wheels should keep on bundling `Emscripten.cmake` so we can simply `pip install pyodide-build` in CI and then build `python-igraph`'s wasm wheels as before.

### Environment

- Pyodide Version: 0.24.1
- Browser version: not applicable

**Comment by rth** [comment]
Thanks for the report. Change due to https://github.com/pyodide/pyodide/pull/3934 @ryanking13 would know more about it.

**Comment by ntamas** [comment]
Thanks for the feedback! In the meanwhile, we worked around the issue by adding the missing file during the CI build like this:

https://github.com/igraph/python-igraph/commit/e7903df985a81e166866ea1eeb91d191bfc83136#diff-5a273ce7e6a1e1cb40e78fcc5f3ea2a1175ffe117d9768b33ca4cafec1e460f1

I'm pretty sure that the change was not intentional, though, as `pyodide-build` still keeps on looking for the toolchain file while setting up the environment (and it even overrides `CMAKE_TOOLCHAIN_FILE` from the external environment so I cannot overrule `pyodide-build`'s decision): https://github.com/pyodide/pyodide/blob/main/pyodide-build/pyodide_build/build_env.py#L172

**Comment by ryanking13** [comment]
Oh... thanks for catching this. It was totally not intentional.

> (and it even overrides CMAKE_TOOLCHAIN_FILE from the external environment so I cannot overrule pyodide-build's decision)

I think we need to fix this too, so that if a user provides CMAKE_TOOLCHAIN_FILE, it should not be overridden.
