### ISSUE TITLE
Fail to resolve `node-fetch` when importing `pyodide`

### ISSUE THREAD

**Issue by suhdonghwi** [pyodide/pyodide#4244]
## 🐛 Bug

Since `v0.24.0`, importing `pyodide` fails to build with an error "failed to resolve import `node-fetch`..."

```
[vite]: Rollup failed to resolve import "node-fetch" from "/workspaces/sandbox/node_modules/pyodide/pyodide.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "node-fetch" from "/workspaces/sandbox/node_modules/pyodide/pyodide.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48205:27)
    at onwarn (file:///workspaces/sandbox/node_modules/@vitejs/plugin-react-swc/index.mjs:197:9)
    at onRollupWarning (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48234:9)
    at onwarn (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:47965:13)
    at file:///workspaces/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:24090:13
    at Object.logger [as onLog] (file:///workspaces/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:25762:9)
    at ModuleLoader.handleInvalidResolvedId (file:///workspaces/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:24676:26)
    at ModuleLoader.resolveDynamicImport (file:///workspaces/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:24734:58)
    at async file:///workspaces/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:24621:32
error Command failed with exit code 1.
```

### To Reproduce

Here is a reproduction sandbox: https://codesandbox.io/p/sandbox/youthful-fast-r52vp8

### Expected behavior

`pyodide` should be imported without an error. Prior to `v0.24.0` it worked fine.

### Environment

- Pyodide Version: `0.24.0` and `0.24.1`
- Browser version: n/a, fails to build in the first place
- Any other relevant information: I am using `vite`. Maybe this is related to recent migration from `rollup` to `esbuild`?

**Comment by hoodmane** [comment]
It is indeed a bit curious why this is a problem in 0.24.0 but not in 0.23.4.

> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`

You should do that. `node-fetch` is not used except in node <= 16.

**Comment by suhdonghwi** [comment]
I tried setting `build.rollupOptions.external` but unfortunately it did not work.

Nonetheless, it functions as expected when pyodide is imported in a non-webworker file. I believe this issue may be associated with Vite and Rollup. Thank you for your response!

**Comment by m-oezokyay** [comment]
I ran into the same issue with Angular 16.2.12. A downgrade to 0.23.4 fixed it. I have no idea what's going on, but this problem might affect more people.

**Comment by yongrenjie** [comment]
For me, downgrading to pyodide 0.23.4 worked, but I needed `scikit-learn 1.3.1` for the project I'm on so I had to stick with 0.24.0. I'm using Vite + Svelte + TypeScript.

The solution for me was adapted from https://github.com/vitejs/vite/discussions/9330:

 - run `npm i --save-dev isomorphic-fetch`
 - add the following to `vite.config.ts` (or the equivalent):

```ts
export default defineConfig({
    ...,
    resolve: {
        alias: {
            'node-fetch': 'isomorphic-fetch',
        },
    },
   ...
```

**Comment by suhdonghwi** [comment]
In my case externalizing `node-fetch` worked, but it required some non-trivial workaround:

1. Externalize `node-fetch` from webworker build using the following config:

```js
export default defineConfig({
  worker: {
    format: "es",
    rollupOptions: {
      external: ["node-fetch"],
    },
  },
})
```

2. Externalize `node-fetch` from regular bundling, however `defineConfig({ rollupOptions: /* ... */ })` [does not work in the dev server](https://github.com/vitejs/vite/issues/6582). I ended up using third-party plugin called [vite-plugin-externalize-dependencies](https://github.com/MilanKovacic/vite-plugin-externalize-dependencies).
