### ISSUE TITLE
Package Request - tiktoken v0.5.1

### ISSUE THREAD

**Issue by psymbio** [pyodide/pyodide#4245]
## 🐍 Package Request

- tiktoken 0.5.1
- https://github.com/openai/tiktoken/
- Package Dependencies that needs to be resolved first:
```
dependencies = ["regex>=2022.1.18", "requests>=2.26.0"]
optional-dependencies = {blobfile = ["blobfile>=2"]}
```

I've tried to make a wheel https://github.com/psymbio/tiktoken_rust_wasm/blob/main/packages/build_emscripten/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl and look at the [README](https://github.com/psymbio/tiktoken_rust_wasm/blob/main/README.md) for steps to create the wheel but I get this error: `ImportError: Can't connect to HTTPS URL because the SSL module is not available.` because the `requests` library needs to be figured out (https://github.com/pyodide/pyodide/issues/398), I'm open to hacky-patches but would like to know how to deal with it.

**Comment by psymbio** [comment]
Sorry for the late response, you can probably recreate the issue using the steps defined here: https://github.com/psymbio/tiktoken_rust_wasm but the gist is that I've made a small change to the tiktoken library in this [file](https://github.com/openai/tiktoken/blob/main/tiktoken/load.py) I've added:

```python
import micropip
await micropip.install("pyodide-http")
import pyodide_http
pyodide_http.patch_all()
import requests
```

but get the following error when hosting this [index file](https://github.com/psymbio/tiktoken_rust_wasm/blob/main/index.html):

```javascript
File "<frozen importlib._bootstrap>", line 1209, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1181, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1152, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 1, in <module>
    from tiktoken.load import data_gym_to_mergeable_bpe_ranks, load_tiktoken_bpe
  File "/lib/python3.11/site-packages/tiktoken/load.py", line 11
    await micropip.install("pyodide-http")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
```

If I remove the await it shows me this error:

```javascript
ModuleNotFoundError: The module 'pyodide-http' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("pyodide-http") in Python, or
  await pyodide.loadPackage("pyodide-http") in JavaScript
```

I feel like I don't completely understand how the library works, should be calling these import elsewhere.

Thanks in advance.

**Comment by ryanking13** [comment]
As the error message mentions, micropip.install is an asynchronous function and must be executed inside an async context.

For instance, I would modify [index.html](https://github.com/psymbio/tiktoken_rust_wasm/blob/8fae5a33b873e013f7b1dfe8ebc07078c6de9b86/index.html) in your [tiktoken_rust_wasm](https://github.com/psymbio/tiktoken_rust_wasm) like this.

```js
    async function main() {
        let pyodide = await loadPyodide();
        await pyodide.loadPackage("micropip");
        const micropip = pyodide.pyimport("micropip");
        await micropip.install("packages/build_emscripten_pyodide_http_2/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl");
        await micropip.install("pyodide-http");
        pyodide.runPython("import pyodide_http; pyodide_http.patch_all()")
        let pythonCode = await (await fetch("tiktoken_test.py")).text(); 
        console.log(pyodide.runPython(pythonCode));
     }
```
