### ISSUE TITLE
Missing pyodide.mjs in the latest REPL

### ISSUE THREAD

**Issue by szabolcsdombi** [pyodide/pyodide#4246]
The dev build is missing the `pyodide.mjs` file.

more precisely https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.mjs is HTTP 404

```
console.html:258 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.mjs
```

It only happens in the latest REPL. (https://pyodide.org/en/latest/console.html)

It worked two days ago.
Yesterday broke at some time, I expected it to be temporary.
It is still present so I am reporting it.

Feel free to close it if not important.

**Comment by hoodmane** [comment]
Thanks for the report @szabolcsdombi. This has been happening intermittently for a while. Sometimes the latest deploy drops `pyodide.mjs` usually it doesn't... It's pretty annoying so it would be helpful if one of us looked into it and fixed it.
