### ISSUE TITLE
Issue with stdin and empty strings using Node.js

### ISSUE THREAD

**Issue by jsbass** [pyodide/pyodide#4258]
## 🐛 Bug

This bug only occurs in the NPM version. I can't replicate this in a browser.
When using a custom stdin callback, if an empty string is returned, an EOFError is thrown. An empty string seems to be acting the same as null or undefined. I tried changing autoEOF to false but that didn't have an effect.

### To Reproduce

Make a new node project and put the following code in the the index.js
```javascript
const { loadPyodide } = require("pyodide");

const testStdin = async (arr) => {
    const py = await loadPyodide();
    let idx = 0;
    py.setStdin({
        stdin: () => {
            return arr[idx++];
        }
    });
    py.runPython(`
        a = input()
        b = input()
        c = input()
        print(a)
        print(b)
        print(c)
    `);
}

testStdin(['asdf', 'qwer', '']).then(console.log).catch(console.error)
```
- An EOFError is thrown

This code works correctly if the last item in the array is not empty

### Expected behavior

Expected to see the value of c be assigned ""

### Environment

- Pyodide Version: 0.24.0
- Node version: 20.5.0
- Any other relevant information:

**Comment by ryanking13** [comment]
Thanks for the report! I was able to reproduce it in our latest console in our chrome browser:

![image](https://github.com/pyodide/pyodide/assets/24893111/3014abad-6e39-4cde-ac87-1bc435f20e9c)

**Comment by ryanking13** [comment]
https://github.com/pyodide/pyodide/blob/9c498a8d4f80f30837b47c5bb8e3d3c9e777884f/src/js/streams.ts#L570-L572

The problem seems to be here, where undefined is returned because the empty string is a falsy value. @hoodmane What would be the intended behavior here?
