### ISSUE TITLE
Pyodide 0.25 release planning

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4301]
I think just counting JSPI and the hiwire refactor, we already have a fair amount of code for Pyodide 0.25 so it would be good to make a release soon.

Thoughts @ryanking13 @rth? I'm thinking about making an alpha pretty soon in any case.

**Comment by hoodmane** [comment]
I'd also like to add a release artifact that includes the static archives:
* libffi.a
* libhiwire.a
* libpyodide.a
* libpython3.11.a 
and the associated headers, at least the Python ones. Since at this point it's both possible and useful to link your own slimmer version, potentially with fewer statically linked libraries, dynamic linking disabled, dead code elimination enabled, etc. Or with some custom static library linked in or something.

**Comment by ryanking13** [comment]
I finished merging PRs I added 0.25.0 milestone flag. Are there any other features we'd like to see included in 0.25? Otherwise I am +1 with releasing 0.25.

**Comment by ryanking13** [comment]
Probably we should handle this one before making a release...

- https://github.com/pyodide/pyodide/issues/4378

**Comment by lesteve** [comment]
I guess this one can be closed?
