### ISSUE TITLE
Jive = Jupyter Lab + Pyodide

### ISSUE THREAD

**Issue by PythonLinks** [pyodide/pyodide#431]
I think that the biggest demand for Pyodide is to use it with Jupyter notebooks.  (or Labs). As one important Jupyter user writes:

>I agree, it will be amazing. Especially when Python Jupyter widgets can run without a server... That will be awesome..

It turns out that there is software to allow Jupyter Kernels to run in the browser.  Jyve was posted here a few weeks ago, but without an explanation of what it is or why it is important. 

https://github.com/deathbeds/jyve

The bad news is that Jyve does not yet support Pyodide kernels.  But do not loose hope. “There is another.”  There is a Jyve fork with a basic Pyodide kernel.  But it does not load numpy.  It is written by the “important user” I mentioned above. 

Here is the repository.
https://github.com/SimonBiggs/jyve

And here is the critical code.
https://github.com/SimonBiggs/jyve/tree/scriptedforms/packages/jyve-kyrnel-pyodide-unsafe

if you are interested in what it does, there is really good documentation on the messaging api in Jupyter.
https://jupyter-client.readthedocs.io/en/stable/messaging.html

You can do a git diff to see the changes from the previous version. 

I suspect that for someone who knows Typescript and Pyodide and Jupyter Lab, it would not take long to figure out how to make this all work.   That would hugely increase the demand for Pyodide. 

In the meantime, I am learning more about all of these technologies.  Any advice on how to get all of this to work together would be most appreciated.  What else should I read?

**Comment by rth** [comment]
Jive was indeed very precursory but currently most of the developments is likely to happen in https://github.com/jupyterlite/jupyterlite and [basthon](https://framagit.org/casatir/basthon-kernel)
