### ISSUE TITLE
Add random package

### ISSUE THREAD

**Issue by TomoBossi** [pyodide/pyodide#4312]
## 🐍 Package Request

- random/latest
- Package URL: https://github.com/python/cpython/blob/3.12/Lib/random.py

Sorry if I'm missing something.

**Comment by ryanking13** [comment]
random is a buildin python library and you should be able to use it. Do you have any problems using it?

**Comment by TomoBossi** [comment]
My mistake, I was getting an error when doing `await pyodide.loadPackage("random");` and didn't try just importing the module from the Python code without loading it first :)
