### ISSUE TITLE
How to make Python code run in a non-blocking

### ISSUE THREAD

**Issue by SimonBiggs** [pyodide/pyodide#435]
Here is an example application I am building:

https://5ce247b0a143cd0008536e0c--app-pymedphys.netlify.com/

If you follow the instructions to download the two files, append them to the application, and then press `Process Files` you'll note that the whole Javascript interface freezes during the processing.

Is there a way I can write my Python code, or my Javascript code that will make it so that the `pyodide.runPython` call won't freeze up the interface?

Thank you in advance!

**Comment by PythonLinks** [comment]
Hi simon. Good to see you active here as well as on Jyve.  Your HTML Pyodide example was very helpful to me.  

I think that you are on the right track.   There are a number of people with Python software and applications which they want to run in the browser

But  you are also one of the early adopters.  


If anyone has Pyodide in production, I would love to see a link.  The 60 students I am teaching today and this weekend would love to hear about it. 

If you do not mind, I will link to your examples  from PythonLinks.info/pyodide.

**Comment by PythonLinks** [comment]
My advice to my students is to do all the file downloading stuff in Javascript. 

What you want is XML http request

/www.w3schools.com/xml/xml_http.asp

It can download the two files at the same time.  Then you can pass the data to Python in whichever order you wish.  
Quite easy to do, unless I am missing something.  Are you okay giving Python the files one at a time.  Or do you want to pass in both files at the same time?

**Comment by PythonLinks** [comment]
Sorry.  I read your web site more carefully. 
What you want is web workers. 
https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_webworker.md

And your browse and upload buttons did not work for me on Chrome, Mac OS X.

**Comment by SimonBiggs** [comment]
> Sorry. I read your web site more carefully.
> What you want is web workers.
> [/docs/using_pyodide_from_webworker.md@`master`](https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_webworker.md) [](/iodide-project/pyodide/blob/HEAD@{2019-05-20T07:00:45Z}/docs/using_pyodide_from_webworker.md)
> 
> And your browse and upload buttons did not work for me on Chrome, Mac OS X.

Thanks, https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_webworker.md is very helpful! :)

I'll have to work out a way to get around the following:

> Since web workers are each in their own virtual machine, you also cannot share globals between a web worker and your main thread.

**Comment by SimonBiggs** [comment]
> If you do not mind, I will link to your examples from PythonLinks.info/pyodide.

I don't mind at all :)

**Comment by SimonBiggs** [comment]
It would be best to link to the master version:

https://app.pymedphys.com

**Comment by PythonLinks** [comment]
So I linked to it here. 
https://pythonlinks.info/the-first-pyodide-application
The text is a bit flippant.  You are welcome to send me a better version. 
The question everyone wants to know is which libraries are you using, and 
what do you think of Pyodide.  A quote from an existing user.

**Comment by SimonBiggs** [comment]
> The question everyone wants to know is which libraries are you using

To achieve which bits?

**Comment by SimonBiggs** [comment]
> what do you think of Pyodide

It's awesome :) Can expand further once I fix this issue I'm trying to solve :).

**Comment by PythonLinks** [comment]
They want to know which libraries are on the publicly facing web sites. 

If you are using more internally, then say so. 

Awesome is good.  If you bring it down to a specific story of how you are using it, that is good. 
And of course a statment on its reliability, usability and problems. 

But fix your bug first.  We are all watching you.

**Comment by SimonBiggs** [comment]
* Application
  * https://blueprintjs.com/ for the application widgets
  * RxJS to handle state
* Docs
  * Customised readthedocs theme
  * Things like graphviz + pymedphys_monomanage to create https://docs.pymedphys.com/developer/dependencies.html

**Comment by SimonBiggs** [comment]
At the moment, the biggest thing I need to improve is the feedback loop. It takes too long to change a python file and get it into the browser. Need to think of a way to hook the emscripten live filesystem up with the local machine for development iteration.

I believe there is a library using nodejs that can achieve that. It would be worthwhile me refocusing on improving the development workflow.

**Comment by SimonBiggs** [comment]
@PythonLinks, thought you might be interested. Haven't fixed the blocking yet, but there has been some drastic improvements to the application.

Head on over to https://app.pymedphys.com/ and press `Ctrl + F5` to force clear your cache for that site.

:)

**Comment by rth** [comment]
Closing, as there isn't really much we can do about long-running calculations between either using a webworker or make threading work #237 .

I'm doing a clean up of older issues, don't hesitate to open new ones if needed.
