### ISSUE TITLE
Boost tar ball URL no longer valid

### ISSUE THREAD

**Issue by eth42** [pyodide/pyodide#4367]
## 🐛 Bug

The URL ([https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz](https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz)) for the boost-cpp tar ball specified in `packages/boost-cpp/meta.yaml` appears to no longer be valid, i.e. the URL provides a tar ball, but the SHA256 does not match the one specified in the meta.yaml. The error appears not to be cosmetic, since changing the SHA256 to match the file's checksum results in downstream errors. Also, manually updating the SHA256 to "whatever that unknown file is" is of course potentially unsafe.

### To Reproduce

`pyodide build-recipes boost-cpp --install`

### Expected behavior

Successful build of boost-cpp

### Environment

- Pyodide Version: 0.23.4 (bad SHA256 affects all newer versions as well)
- Browser version: Irrelevant
- Commit hash of Pyodide git repository: 25b404e92af175383b0736a8663ab95e8516ad3e
- Build environment: Dockerfile (Docker version 24.0.6) with target system `debian:bookworm`

### Additional context

<details><summary>Terminal log (bad SHA256)</summary>
<pre>
122.9 Error building boost-cpp. Printing build logs.                                  
122.9 [2024-01-08 16:14:06] Failed building package boost-cpp in 1.3 seconds.         
122.9 Traceback (most recent call last):                                              
122.9   File "<frozen runpy>", line 198, in _run_module_as_main                       
122.9   File "<frozen runpy>", line 88, in _run_code                                  
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/__main__.py", line 53, in      
122.9 <module>                                                                        
122.9     main()                                                                      
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/__main__.py", line 47, in main 
122.9     args.func(args)                                                             
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 985, in main
122.9     build_package(args.package[0], build_args, args.force_rebuild,              
122.9 args.continue_)                                                                 
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 881, in     
122.9 build_package                                                                   
122.9     _build_package_inner(                                                       
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 756, in     
122.9 _build_package_inner                                                            
122.9     prepare_source(build_dir, srcpath, source_metadata, clear_only=clear_only)  
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 280, in     
122.9 prepare_source                                                                  
122.9     download_and_extract(buildpath, srcpath, src_metadata)                      
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 222, in     
122.9 download_and_extract                                                            
122.9     check_checksum(tarballpath, src_metadata)                                   
122.9   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 151, in     
122.9 check_checksum                                                                  
122.9     raise ValueError(                                                           
122.9 ValueError: Invalid sha256 checksum:                                            
122.9 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff !=             
122.9 4b2136f98bdd1f5857f1c3dea9ac2018effe65286cf251534b6ae20cc45e1847 (expected)     
122.9                                                                                 
122.9 ERROR: cancelling buildall                                                      
122.9 [3/25] (thread 1) failed boost-cpp in 1s 
</pre>
</details>

<details><summary>Terminal log (manually fixed SHA256)</summary>
<pre>
216.3 Error building boost-cpp. Printing build logs.                                  
216.3 [2024-01-08 17:15:55] Failed building package boost-cpp in 1.4 seconds.         
216.3 Traceback (most recent call last):                                              
216.3   File "<frozen runpy>", line 198, in _run_module_as_main                       
216.3   File "<frozen runpy>", line 88, in _run_code                                  
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/__main__.py", line 53, in      
216.3 <module>                                                                        
216.3     main()                                                                      
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/__main__.py", line 47, in main 
216.3     args.func(args)                                                             
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 985, in main
216.3     build_package(args.package[0], build_args, args.force_rebuild,              
216.3 args.continue_)                                                                 
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 881, in     
216.3 build_package                                                                   
216.3     _build_package_inner(                                                       
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 756, in     
216.3 _build_package_inner                                                            
216.3     prepare_source(build_dir, srcpath, source_metadata, clear_only=clear_only)  
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 280, in     
216.3 prepare_source                                                                  
216.3     download_and_extract(buildpath, srcpath, src_metadata)                      
216.3   File "/srv/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 233, in     
216.3 download_and_extract                                                            
216.3     shutil.unpack_archive(tarballpath, buildpath)                               
216.3   File "/usr/local/lib/python3.11/shutil.py", line 1312, in unpack_archive      
216.3     raise ReadError("Unknown archive format '{0}'".format(filename))            
216.3 shutil.ReadError: Unknown archive format                                        
216.3 '/srv/pyodide/packages/boost-cpp/build/boostorg'                                
216.3                                                                                 
216.3 ERROR: cancelling buildall                                                      
216.3 [3/25] (thread 1) failed boost-cpp in 1s   
</pre>
</details>

**Comment by ryanking13** [comment]
Thanks. It seems like the sha256 checksum has been changed for some reason.

**Comment by ryanking13** [comment]
Hmm, the sha256sum seems okay in the latest commit (https://github.com/pyodide/pyodide/commit/f1498a2747d5dc968dad2d872181d9cad2d80a48), and it looks also okay when I downloaded the tarball manually. So, the boost fileserver may be unstable for a while.

I'll close this as resolved for now, but I'll re-open if this happens again.

**Comment by eth42** [comment]
Fetched the file from the URL again and the checksums now match. It appears the file on jfrog was unstable for a while. Thanks for looking into it and sorry for bothering with an out-of-scope issue.

**Comment by ryanking13** [comment]
No worries. It was a totally valid issue.
