### ISSUE TITLE
Can't use alpha version: TypeError: WebAssembly.Function.type is not a function

### ISSUE THREAD

**Issue by kor0p** [pyodide/pyodide#4378]
## 🐛 Bug

I'm trying to use latest (alpha) versions of Pyodide (0.25.0a1 or above)
I was curious about stack switching with syncify() API
And when package is loaded and trying to install wasm code, the next error is raised:
```
wasm instantiation failed!
TypeError: WebAssembly.Function.type is not a function
```
![Screenshot from 2024-01-14 23-49-00](https://github.com/pyodide/pyodide/assets/32600554/aca60d19-d91c-4c02-bf4c-aa0f12bf568e)

### To Reproduce

Just visit [console](https://pyodide.org/en/latest/console.html) on dev build

### Expected behavior

It should work, isn't it? 🙃

### Environment

- Pyodide Version: 0.25.0a1, 0.25.0a2 or dev
- Browser version: Version 120.0.6099.199 (Official Build) (64-bit)

### Additional context

I found some discussion about similar code [here](https://github.com/WebAssembly/js-promise-integration/issues/25)
And the solution is to make next change:
```js
                const type = WebAssembly.Function.type(wasm_func);
```
to
```js
                const type = wasm_func.type();
```

On screenshot above I tried this in debugger and it seems to work :)

**Comment by hoodmane** [comment]
Thanks for the report @kor0p!
Indeed they seem to have changed this from Chrome 119 to Chrome 120. Of course, it only reproduces if you turn on `Experimental WebAssembly JavaScript Promise Integration (JSPI)` in `chrome://flags`. I'd want to keep JSPI support for node v20 so we'll have to feature detect this and choose the appropriate way to get the type of a wasm function.

**Comment by kor0p** [comment]
@hoodmane 
Thanks for quick answer
Yes, I have enabled this flag to test JSPI, so I disabled it and still can reproduce the bug [here](https://pyodide.org/en/latest/console.html) :cry: 

![Screenshot from 2024-01-15 09-42-13](https://github.com/pyodide/pyodide/assets/32600554/adbe319d-8d72-4ebf-80e5-b13312b4277d)

**Comment by kor0p** [comment]
@hoodmane Thanks a lot!
Now I can try JSPI feature as expected!
So, I went to [original PR](https://github.com/pyodide/pyodide/pull/3210/files#diff-eb3996fa8b246ff8e9a0ed92aa07dcbaecdc83744b0018613b87a3b494da99ff) to find some examples on it (tests should be great examples, isn't it?)
And there is no tests for explicit Python PyodideFuture usage. But it works the same way, and it's great news, that we finally can syncify() it!
Here is draft for such test:
```python
@pytest.mark.xfail_browsers(safari="No JSPI on Safari", firefox="No JSPI on firefox")
def test_syncify_error(selenium):
    selenium.run_js(
        """
        await pyodide.runPythonSyncifying(`
            import asyncio

            async def test():
                await asyncio.sleep(0.1)
                return 7

            task = asyncio.create_task(test())
            assert task.syncify() == 7
            del test, task
        `);
        """
    )
```

**Comment by hoodmane** [comment]
Thanks for the test @kor0p. If you make a PR adding that to the test suite I'll merge it.
