### ISSUE TITLE
nh3

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyodide/pyodide#4381]
## 🐍 Package Request

- nh3/ latest
- https://github.com/messense/nh3

## Motivation

https://github.com/holoviz/panel/issues/6206

**Comment by kor0p** [comment]
@MarcSkovMadsen
You can create issue in hn3 repository to ask them to publish [pure wheel](https://pyodide.org/en/stable/usage/loading-packages.html#installing-wheels-from-arbitrary-urls). After that micropip will be able to install package from pypi (direcrly or as dependency for other package)

**Comment by MarcSkovMadsen** [comment]
Thanks. I thought that was not possible as it has rust bindings?

**Comment by hoodmane** [comment]
I opened PR #4387 doing  this.
