### ISSUE TITLE
Incorrect content type for JSDelivr wheels

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4383]
This is probably not very important but our wheels are served with 
```
Content-Type: application/wasm
```
this is not correct, I think it should be `application/zip`. @rth

**Comment by ryanking13** [comment]
We need to fix this line:

https://github.com/pyodide/pyodide/blob/d44293f3c39358fefe67e3d1184baf4e63800705/tools/deploy_s3.py#L133-L134

**Comment by ryanking13** [comment]
Probably it is intentional, but I am not sure.

https://github.com/pyodide/pyodide/blob/d44293f3c39358fefe67e3d1184baf4e63800705/tools/tests/test_deploy_s3.py#L148-L152

**Comment by hoodmane** [comment]
> for better CDN compression

Thanks @ryanking13. It's a bit mysterious -- why does setting the content type of zip files to `application/wasm` instead of `application/zip` improve cdn compression?

**Comment by rth** [comment]
Basically we want to give the CDN an uncompressed tarball/zip and let it brotli compress it. That's a hack to achieve that as far as I remember.

If you we do keep the zip MIME type, then it's not re-compressed by the CDN and zip / DEFLATE is worse compression than brotli. Brotli on top of DEFLATE is also worse.

To add to the confusion, we produce zip files with no compression inside, that we gzip compress before uploading to S3 with the `ContentEncoding="gzip"` header, just to save space and S3 <-> CDN bandwidth. They are then served to the CDN, which recompresses them with the best possible `ContentEncoding` (brotli or gzip)

**Comment by rth** [comment]
But yes, I should add more comments to that script :)

**Comment by ryanking13** [comment]
> If you we do keep the zip MIME type, then it's not re-compressed by the CDN and zip / DEFLATE is worse compression than brotli. Brotli on top of DEFLATE is also worse.

I see. I didn't know that brotli compression is not applied when content type is zip.

**Comment by rth** [comment]
> So it works equally well to give it any non-zip content type? What about application/octet-stream

I don't think it would work with octet-stream. We are relying on default CDN compression settings that generally follow the logic of compress what is known to be well compressible. wasm compresses well, but byte stream generally doesn't and can be large, so I guess, they don't waste CPU resources doing that. 

Here are for instance [fastly defaults](https://docs.fastly.com/en/guides/enabling-automatic-compression) (but I think wasm probably also included there). For any given CDN it's configurable, but probably not in the case of a multi-CDN setup with JSdelivr.

In out case, `application/wasm` is not that far off, as we are shipping uncompressed zip which can contain wasm code for C extensions.

**Comment by hoodmane** [comment]
Thanks for the explanations!
