### ISSUE TITLE
`ffi` from JavaScript

### ISSUE THREAD

**Issue by seanpk** [pyodide/pyodide#4386]
## 🐛 Bug

The `package.json` file in the published npm version (`v0.23.4` and `v0.24.1` - I've tried them both), does not include `ffi` in its list of exports.

From javascript:
```
 $ node tmp/pyodide-ffi-test.js 
node:internal/modules/esm/resolve:294
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './ffi' is not defined by "exports" in /workspaces/28th-ces/ephemeris/node_modules/pyodide/package.json imported from /workspaces/28th-ces/ephemeris/tmp/pyodide-ffi-test.js
    at exportsNotFound (node:internal/modules/esm/resolve:294:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:9)
    at packageResolve (node:internal/modules/esm/resolve:827:14)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.10.0
```

I don't use TypeScript, so I can't say what's supposed to work there. But if I edit the `node_modules/pyodide/package.json` file and add `"./ffi": "./ffi.d.ts",` to the `"exports"` block, I just get an error about the file extension, i.e.:
```
$ node tmp/pyodide-ffi-test.js 
node:internal/modules/esm/get_format:160
  throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
        ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /workspaces/28th-ces/ephemeris/node_modules/pyodide/ffi.d.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:141:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:409:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:45) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v20.10.0
```

### To Reproduce

Having installed the `pyodide` npm package:
```javascript
import { PyProxy } from 'pyodide/ffi'

console.log({} instanceof PyProxy)
```

An alternate attempt is this:

```javascript
import { ffi } from 'pyodide'

console.log({} instanceof PyProxy)
```
But that results in this output:
```
$ node tmp/pyodide-ffi-test.js 
file:///workspaces/28th-ces/ephemeris/tmp/pyodide-ffi-test.js:3
import { ffi } from 'pyodide'
         ^^^
SyntaxError: The requested module 'pyodide' does not provide an export named 'ffi'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

Do: `node ./reproduce.js`

### Expected behavior

I ought to be able to follow the documentation and have it work in my JavaScript code. [`isPyProxy` is deprecated](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.isPyProxy), and the proposed solution (at link and in the below image) doesn't work.
![image](https://github.com/pyodide/pyodide/assets/5642399/66518b56-b782-4aa8-8b8d-9c475b16cf07)

### Environment

- Pyodide Version: `v0.23.4` and `v0.24.1`
- Browser version: npm/node (ultimately in the browser too)

### Additional context

Related PR: #3523

**Comment by hoodmane** [comment]
I think this is the intended behavior, though it may be a bit unexpected. Perhaps we ought to clarify somewhere...

You have to do as follows:
```
import { loadPyodide } from 'pyodide';

```js
const pyodide = await loadPyodide();
const PyProxy = pyodide.ffi.PyProxy;
```
This is because it's possible to start up multiple Python interpreters and `PyProxy` is instanced to the intepreter:
```js
const py1 = await loadPyodide();
const py2 = await loadPyodide();
const py1dict = py1.runPython("{}");
const py2dict = py2.runPython("{}");
console.log(py1dict instanceof py1.ffi.PyProxy); // true
console.log(py1dict instanceof py2.ffi.PyProxy); // false
console.log(py2dict instanceof py1.ffi.PyProxy); // false
console.log(py2dict instanceof py2.ffi.PyProxy); // true
```
ES6 imports are global to the program so they can't be instanced like this.

**Comment by ryanking13** [comment]
That's strange. I think we support those syntaxes, we have a test for it:

https://github.com/pyodide/pyodide/blob/main/src/test-js/index.test-d.ts#L4-L18

**Comment by hoodmane** [comment]
It's a bit confusing I agree:

* `src/test-js` is a folder for typescript type tests... we might think about renaming it to make this clear
* the test there is running on the source files in `src/js` not the generated files in `dist`
* inside of the `src/js` folder it is possible to do an ES6 import for ffi but we bundle them together at build time so it's not actually possible to do it with the functional version of Pyodide.

**Comment by seanpk** [comment]
[This is very helpful](https://github.com/pyodide/pyodide/issues/4386#issuecomment-1894701619) to know. It will be good to switch from `isPyProxy` - it looks like it ought not be an issue.

It would still be nice to import just the types to get editor type support too. Right now I do:
```javascript
/** @typedef { import('pyodide').PyProxy } PyProxy */
```
But it would be better to have:
```javascript
/** @typedef { import('pyodide/ffi').PyProxy } PyProxy */
```

**Comment by hoodmane** [comment]
> it would be better to have: ...

Hmm indeed. It seems to me that you can get it in either of those two ways? If you import it from `pyodide` it says:
```
@deprecated — Use `import type { PyProxy } from "pyodide/ffi"` instead
```
So I think this is working as intended, though it might be helpful if we could also tell people where to locate the actual object `PyProxy` as opposed to the type.

**Comment by seanpk** [comment]
Coming back around to this: with #4256, it is possible to do the JSDock typedef:
```javascript
/** @typedef { import('pyodide/ffi').PyProxy } PyProxy */
```

Looks like I Just need to upgrade to `v0.25.0`

**Comment by hoodmane** [comment]
Thanks @seanpk!
