### ISSUE TITLE
[feature request] mount virtual filesystem if running in node.js

### ISSUE THREAD

**Issue by teonbrooks** [pyodide/pyodide#439]
One feature I would like to have would be the ability to write files to disk in pyodide when using it in node.js. the project i'm working on is built using electron and this would solve one of its use cases. @mdboom mentioned that this would be possible and I just stumbled upon [this](https://github.com/emscripten-core/emscripten/blob/master/tests/fs/test_nodefs_rw.c). I'm pretty new to using node.js so I am guessing it needs two things:
-  identify if you are in a node context
- specify a mount point (maybe default user folder?)

**Comment by rth** [comment]
We include NODEFS by default since https://github.com/pyodide/pyodide/pull/1596, so then it's a matter of mounting a folder as needed via `pyodide.FS` using emscripten's [FS API](https://emscripten.org/docs/api_reference/Filesystem-API.html#nodefs).
