### ISSUE TITLE
'npm install pyodide' results in Error (Can't resolve 'node-fetch' ...)

### ISSUE THREAD

**Issue by Hephaistos7** [pyodide/pyodide#4411]
## 🐛 Bug

The following 5 Warnings and 1 Error occur when installing and running pyodide through 'npm install pyodide':

./node_modules/pyodide/pyodide.js:19:39-46 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/pyodide/pyodide.js:22:37-44 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/pyodide/pyodide.js:381:19-28 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.js:392:42-51 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.js:407:125-156 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.js:299:127-147 - Error: Module not found: Error: Can't resolve 'node-fetch' in '...\node_modules\pyodide'

Upon removing the line in the code marked with a '#1', the following 3 Warnings and 1 Error still appear (notice that now they come from pyodide.mjs instead of pyodide.js):

./node_modules/pyodide/pyodide.mjs:362:17-26 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.mjs:373:40-49 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.mjs:388:123-154 - Warning: Critical dependency: the request of a dependency is an expression
./node_modules/pyodide/pyodide.mjs:280:125-145 - Error: Module not found: Error: Can't resolve 'node-fetch' in '...\node_modules\pyodide'

I do not really know how to interpret the line numbers, (.../pyodide.js:19:39-46) since pyodide.js, when opened, has only a total of 14 lines of code.

Also, it was my understanding that the module 'node-fetch' is not required to run Pyodide. That being said, upon getting it through (npm install node-fetch), a whole lot of other errors show up (which I'd be happy to share as well if need be). Those errors starting with '<e> [webpack-dev-middleware] HookWebpackError: ENOENT: no such file or directory, scandir
<e>     at makeWebpackError (...\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\HookWebpackError.js:48:9)ne@4.0.0 dev'

### To Reproduce

- Have an angular project.
- npm install (for the dependencies)
- npm install pyodide

then put the lines:
`import { loadPyodide } from 'pyodide';`
and
`const { loadPyodide } = require("pyodide"); // #1
	async function hello() {
		let pyodide = await loadPyodide();
		return pyodide.runPythonAsync("1+1");
		return pyodide.runPython("1+2");
	}
	hello().then((result) => {
		console.log("Python says:", result);
	});`
into your code. For me, I put them into a component, that has a function which executes when I press a button on the website.

Lastly, use 'npm run dev' to setup the environment. The Warnings & Error should appear.

### Expected behavior

I expected 'npm run dev' to compile successfully and the above test code to run then. The compilation already failed.

### Environment

- Pyodide Version 0.25.0 and 0.24.1 (tried with both, same problem)
- Browser version Firefox (121.0.1 (64-bit)); also tried with Opera on a different pc
- Any other relevant information:
Tried it with Firefox on Windows, and with Opera on Linux. Same problem.

### Additional context

When using the CDN way, everything works fine. But that is not what I want, since the contents of my website need to able to be deployed for offline usage. That's why I need to install pyodide via npm.
This means, the following executes fine without problems:
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        console.log(pyodide.runPython("1 + 2"));
      }
      main();
    </script>
  </body>
</html>

This is weird to me, because supposedly, pyodide.js from the CDN and from 'npm install pyodide' should be identical.

I'd be happy to provide further information if need be.
I'll be thankful for any advice on how to fix this and I apologize if somehow, the issue isn't originating from pyodide.

**Comment by ryanking13** [comment]
Pyodide does not require node-fetch when native fetch (available from Node v18) is available. But if the native fetch is not available. It tries to load node-fetch dynamically.

https://github.com/pyodide/pyodide/blob/a14d34fb1be4b0aed869be71b3d5b3b2d9c22790/src/js/compat.ts#L42-L48

The problem you are experiencing is caused by webpack. When Webpack bundles the project, it analyses all dynamic imports in the project and tries to embed them into a single file. So that's why you are getting `Can't resolve 'node-fetch'`.

__How to fix__

You need to tell webpack not to munge those import statements. You can use [pyodide-webpack-plugin](https://github.com/pyodide/pyodide-webpack-plugin/blob/9112d85cfe45325d43b73301a10c1202f1570f78/README.md?plain=1#L100-L119), or follow what that plugin does.

**Comment by hoodmane** [comment]
> does not require node-fetch when native fetch (available from Node v18)

> Node.js < 18 is no longer officially supported

Should we drop this?

**Comment by Hephaistos7** [comment]
I'd like to post my fix to this issue once I get it.
The hint to the plugin was helpful, but I still have to figure out how to handle my webpack implementation.
It wasn't as simple as installing the plugin and following the instructions of the link provided by @ryanking13 .

@hoodmane that was exactly what I was referring to when I wrote that node-fetch was not required. I tried both on node version 18 and 20. So I was confused why node-fetch suddenly posed on issue.

It would be kinda cool if a user could just 'npm install pyodide @pyodide/webpack-plugin' and then have a working pyodide.
Maybe this helps getting there.

**Comment by Hephaistos7** [comment]
So, I still come up short, even with the webpack-plugin.
Installed it with `npm install --save-dev pyodide @pyodide/webpack-plugin`.

I put the following lines in my code (tried multiple places: in main.ts, in service files and components):
```
import { PyodideInterface, loadPyodide, version } from 'pyodide'; // instead of this, I also tried const {loadPyodide} = require("pyodide");
import { PyodidePlugin } from '@pyodide/webpack-plugin';
console.log("startExecution right here")
	async function hello() {
		let pyodide = await loadPyodide();
		return pyodide.runPythonAsync("1+1");
	}
	hello().then((result) => {
		console.log("Python says:", result);
	});
	console.log("startExecution left here")
```
	
Just like that, I still get the error message: 

> ./node_modules/pyodide/pyodide.js:308:83-310:19 - Error: Module not found: Error: Can't resolve 'node-fetch' in 'B:\Librairies\Documents\AAA Bonsai Documents\xlogoonline\xlogoonline\node_modules\pyodide'

Now, when I put the line module.exports = {plugins: [new PyodidePlugin()]}; in my code as follows
```
...
import * as skulpt from 'skulpt';
import { Skulpt, SkulptError, TPyParserAttrs } from 'app/interface';
import { PyodideInterface, loadPyodide, version } from 'pyodide';
import { PyodidePlugin } from '@pyodide/webpack-plugin';

const STDLIB_FILES: Record<string, string> = files.files;

module.exports = {
  plugins: [new PyodidePlugin()],
};
...
```
I still get the following errors:

> <e> [webpack-dev-middleware] HookWebpackError: ENOENT: no such file or directory, scandir
> <e>     at makeWebpackError (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\HookWebpackError.js:48:9)


We also tried instead of putting the module.exports code to the other code, to put it in our 'custom-webpack.config.js' (as recommended by [https://github.com/pyodide/pyodide-webpack-plugin/tree/main](url)
These are the full contents of that file:
const { PyodidePlugin } = require("@pyodide/webpack-plugin");

module.exports = {
  resolve: {
    fallback: {
      // "assert": require.resolve("assert/"),
      "fs": false
    }
  },
  plugins: [new PyodidePlugin()],
}

which results in a TypeError:

> \ Generating browser application bundles (phase: setup)...B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\webpack\lib\NormalModule.js:227
>                         throw new TypeError(
>                               ^
> 
> TypeError: The 'compilation' argument must be an instance of Compilation
>     at NormalModule.getCompilationHooks (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\webpack\lib\NormalModule.js:227:10)
>     at B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\@pyodide\webpack-plugin\plugin.js:201:69
>     at Hook.eval [as call] (eval at create (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:230:1)
>     at Hook.CALL_DELEGATE [as _call] (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\tapable\lib\Hook.js:14:14)
>     at Compiler.newCompilation (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1109:26)
>     at B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1153:29
>     at eval (eval at create (B:\Librairies\Documents\xlogoonline\xlogoonline\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
> 
> Node.js v18.16.0


So now we are at a loss as to what to do to integrate Pyodide in our angular project.
Tbh, I do not understand webpack enough to figure out how to solve this.

**Comment by hoodmane** [comment]
@mneil could you take a look at this and see if you can suggest something?

**Comment by mneil** [comment]
```javascript
import { PyodideInterface, loadPyodide, version } from 'pyodide'; // instead of this, I also tried const {loadPyodide} = require("pyodide");
import { PyodidePlugin } from '@pyodide/webpack-plugin';
console.log("startExecution right here")
	async function hello() {
		let pyodide = await loadPyodide();
		return pyodide.runPythonAsync("1+1");
	}
	hello().then((result) => {
		console.log("Python says:", result);
	});
	console.log("startExecution left here")
...
```

This is incorrect usage of the plugin. I would expect it to continue to throw the same error.

The plugin `import { PyodidePlugin } from '@pyodide/webpack-plugin';` needs to be imported into your webpack configuration - not in your main application.

If you are using a specific build tool or framework that does not have a webpack config in the root of your project, then you will need to refer to that framework's documentation on how to add additional plugins to your config.

- Pyodide plugin getting started https://github.com/pyodide/pyodide-webpack-plugin?tab=readme-ov-file#getting-started
- Webpack plugin configuration https://webpack.js.org/configuration/plugins/

@ryanking13 and @hoodmane I think this error is normal / expected behavior when compiling with webpack using common configuration options. Webpack parses javascript with [acorn](https://github.com/acornjs/acorn), has its own compile context, and requires [shimming](https://webpack.js.org/guides/shimming/) globals. 

I do not know if you can drop support for node-fetch yet or not. Node 18 fetch was still experimental, and I know from usage that it does not handle fetching local files at all. I'm not sure if pyodide uses that feature of node-fetch or not? [Node fetch release announcement](https://nodejs.org/en/blog/announcements/v18-release-announce)

**Comment by hoodmane** [comment]
Thanks @mneil!

> I do not know if you can drop support for node-fetch yet or not. Node 18 fetch was still experimental, and I know from usage that it does not handle fetching local files at all. I'm not sure if pyodide uses that feature of node-fetch or not?

I appreciate the warning. We are already using `fetch` if it's available and only falling back to `node-fetch`. So if there was a regression when we moved from node 16 + node-fetch to node 18 + fetch, it's one that didn't have test coverage. Though I think some of the node bugs we hit probably were related to this...

**Comment by Hephaistos7** [comment]
Thanks @mneil , you confirmed that we were on the right track.

So, I got it working.
The problem is indeed webpack related. Webpack seems to get installed multiple times with some plugins. So I deleted webpack from the "@angular-devkit/build-angular" module and called "npm dedupe" to flatten webpack modules (only rly worked after I did both, simply deduping didn't solve it).
I guess that different solutions work as well, maybe updating all the webpack instances to the same version or pointing all dependencies to the same webpack.

I am trying to help others in suggesting that you could look into adding to the documentation from [https://pyodide.org/en/stable/usage/index.html](url) or [.](https://www.npmjs.com/package/pyodide) the link to the pyodide-webpack-plugin and also providing a note that webpack might cause trouble when multiple versions are present inside subfolders of node_modules:
I'm guessing that webpack is used a lot in projects.
Might save other people a lot of troubleshooting.

Thanks guys!

**Comment by jsuryakt** [comment]
I have this issue with the new esbuild system in angular which uses esbuild+vite, ofc it is solved by installing "node-fetch" explicitly.
