### ISSUE TITLE
tiktoken 0.5.2 (emscripten version issue)

### ISSUE THREAD

**Issue by psymbio** [pyodide/pyodide#4418]
## 🐍 Package Request

- Package Name and Version : tiktoken 0.5.2
- Package URL : https://github.com/openai/tiktoken
- Package Dependencies that needs to be resolved first: None

Hi, I'm trying to use the following steps to build the package myself:
```bash
git clone https://github.com/pyodide/pyodide && cd pyodide
./run_docker
make

sudo apt update
sudo apt install curl -y

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env
rustup toolchain install nightly
rustup target add --toolchain nightly wasm32-unknown-emscripten
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

pip install -U maturin
pip install ./pyodide-build

rm -rf emsdk
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk/
./emsdk install 3.1.46
./emsdk activate 3.1.46
source "/src/emsdk/emsdk_env.sh"

cd ..
git clone https://github.com/psymbio/tiktoken_wasm
cd tiktoken_wasm

pip install --upgrade pip
pip install setuptools_rust pyodide-http
sudo apt-get install pkg-config libssl-dev
pip install -e .
cd ..
sudo apt-get install vim -y
vim tiktoken_test.py

cd tiktoken_wasm
rustup default nightly
pyodide build
```

However, I get this error: `ValueError: Wheel was built with Emscripten v3.1.46 but Pyodide was built with Emscripten v3.1.45`

Emscripten won't allow me to build with 3.1.45 and the current version of Pydodide won't run the wheel compiled with v3.1.46.

**Comment by ryanking13** [comment]
> Emscripten won't allow me to build with 3.1.45 and the current version of Pydodide won't run the wheel compiled with v3.1.46.

It is intentional. Currently we force the version of emscripten used to build Pyodide to be the same as the version used to build the package. This is because emscripten does not guarantee compatibility between versions.

You can get the emscripten version used in specific version for Pyodide by

```sh
pyodide config get emscripten_version
```

and you can use it like:

```
./emsdk install $(pyodide config get emscripten_version)
```

one more thing to say is I recommend you use `pyodide-build` from pypi, not cloning from GitHub, unless if you are building latest Pyodide by yourself.

**Comment by psymbio** [comment]
I've made the following edits:

```bash
...
pip install pyodide-build
...
./emsdk install $(pyodide config get emscripten_version)
./emsdk activate $(pyodide config get emscripten_version)
```

But even this results in the emscripten version to be 3.1.52 and results in the following error: `ValueError: Wheel was built with Emscripten v3.1.52 but Pyodide was built with Emscripten v3.1.45`.

**Comment by ryanking13** [comment]
Could you check if there is `.pyodide-xbuildenv` directory in the directory, and remove it if there is? Probably the artifact from the old pyodide-build version is remaining and it is causing an error.

**Comment by psymbio** [comment]
Not able to locate this - is there any particular directory I should be looking in?

![image](https://github.com/pyodide/pyodide/assets/46052244/b06dc92f-c2da-47ec-89f0-5fcaecfd25c7)

**Comment by ryanking13** [comment]
> Not able to locate this - is there any particular directory I should be looking in?

The directory where you run the pyodide build command, probably the root directory of the `tiktoken_wasm` repository.
The picture you attached appears to be the pyodide repository not `tiktoken_wasm`.

**Comment by psymbio** [comment]
Couldn't find anything in `tiktoken_wasm` as well:
![image](https://github.com/pyodide/pyodide/assets/46052244/431c3b2b-7616-43d8-8515-24c02d7d1ffa)

**Comment by ryanking13** [comment]
> But even this results in the emscripten version to be 3.1.52 and results in the following error: ValueError: Wheel was built with Emscripten v3.1.52 but Pyodide was built with Emscripten v3.1.45.

Which Pyodide version are you using when testing the built wheel?

Pyodide 0.25.0 is built with Emscripten 3.1.52 while Pyodide 0.24.X is built with Emscripten 3.1.45. So if you were using Pyodide 0.24.X, could you try Pyodide 0.25.0?

**Comment by psymbio** [comment]
Hi,

Tried with 0.25.0 but that didn't work out - so I tried pyodide 0.24.1 and the build works.

Working code:
```python
import micropip
await micropip.install('https://raw.githubusercontent.com/psymbio/pyodide_wheels/main/tiktoken/tiktoken-0.5.2-cp311-cp311-emscripten_3_1_45_wasm32.whl', keep_going=True)
```

Thanks for your support!
