### ISSUE TITLE
an error in CoolProp generates a fatal error in Pyodide

### ISSUE THREAD

**Issue by dvd101x** [pyodide/pyodide#4451]
## 🐛 Bug

Getting an error or warning in CoolProp crashes pyodide with a fatal error

### To Reproduce
Run the following code in Pyodide REPL
```py
from CoolProp.CoolProp import PropsSI
PropsSI('T','P',101325,'Q',0,'Water')    # yields 373.1242958476844
PropsSI('T','P',101325,'Q',0,'Walter')   # should yield an error
```
The CoolProp error causes a fatal error in Pyodide
```text
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
CppException CoolProp::CoolPropError<(CoolProp::CoolPropBaseError::ErrCode)4>: key [Walter] was not found in string_to_index_map in JSONFluidLibrary
Look in the browser console for more details.
```
### Expected behavior

Running the example code should generate an error in CoolProp as it does in Python (not crash Pyodide with a fatal error)

```
ValueError: Initialize failed for backend: "?", fluid: "Walter" fractions "[ 1.0000000000 ]"; error: key [Walter] was not found in string_to_index_map in JSONFluidLibrary : PropsSI("T","P",101325,"Q",0,"Walter")
```

### Environment

- Pyodide Version: 0.25.0
- Browser version: Firefox 122.0
- Any other relevant information:

### Additional context

First discussed here:
- https://github.com/CoolProp/CoolProp/discussions/2302#discussioncomment-7333820
- https://github.com/mgreminger/EngineeringPaper.xyz/discussions/204#discussioncomment-8308871

**Comment by hoodmane** [comment]
I think it is built with aborting exceptions. To fix, add
```yaml
build:
  cxxflags: -fexceptions
  ldflags: -fexceptions
```
to `meta.yaml`.

**Comment by dvd101x** [comment]
Thank you very much, Hood!

I did manage to run it (with a github-codespaces setup) and it avoids the fatal error.

It is very promising! how would you like to proceed with your solution?

If it's ok with you, I could make a PR stating it's your solution or however suits you best.

Thanks again
