### ISSUE TITLE
Zengl 2.4.0 import fails

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4501]
Zengl 2.4.0 fails with:
```py
ModuleNotFoundError: No module named '_zengl_js'
```
@szabolcsdombi

**Comment by szabolcsdombi** [comment]
Hey, will look into this soon.

**Comment by ryanking13** [comment]
Closing as resolved by https://github.com/pyodide/pyodide/pull/4509, Thanks again @szabolcsdombi!

**Comment by szabolcsdombi** [comment]
Thank you!
