### ISSUE TITLE
`ImportError.name` not set for included packages?

### ISSUE THREAD

**Issue by Zac-HD** [pyodide/pyodide#4511]
[`ImportError.name` should be a string](https://docs.python.org/3/library/exceptions.html#ImportError) naming the module which could not be imported.  For example, the following should print `err.name='numpy'` (assuming Numpy is not installed locally or loaded into pyodide).

```python
try:
    # try with `numpy`, `numpy.badsubmodule`, `wheelofcheese`
    import numpy
except ImportError as err:
    print(f"{err.name=}")
```

However with pyodide 0.25.0 and Chrome 121.0.6167.161, I get `err.name=None`, which has led me to [an AST-based workaround to `micropip.install()` whatever was missing](https://github.com/Zac-HD/Zac-HD.github.io/blob/9fbf07cc181955a2dbc8122ca7a67a283fa28a53/ghostwriter/hydemo.py#L90-L95).  I haven't looked into it much further, but thought I'd report it since this might be pretty easy to fix if you know where to look 🙂

**Comment by hoodmane** [comment]
Thanks for the report. Looks like this bug has been around since August 17, 2022 added in this PR: https://github.com/pyodide/pyodide/pull/2973. Funnily enough I think it was fixed on the main branch three days ago by: https://github.com/pyodide/pyodide/pull/4484

**Comment by Zac-HD** [comment]
Nice!  Always fun to see people using `.add_note()`, too 😁

**Comment by hoodmane** [comment]
Oh yeah I forgot you wrote the pep for `add_note`. Thanks for it, it's a fantastic API.
