### ISSUE TITLE
pyodide.isPyProxy no longer defined

### ISSUE THREAD

**Issue by cfry** [pyodide/pyodide#4530]
## 🐛 Bug

pyodide.isPyProxy was defined in piodide 0.23 but is not in 0.25.0 
The only reference to isPyProxy in the change log is that it was added
well before 0.23

### To Reproduce
In JavaScript, eval:
pyodide.isPyProxy

### Expected behavior

a function is returned

### Environment

- Pyodide Version:
- Browser version:
- Running on MacOS

**Comment by hoodmane** [comment]
Well in 0.23 and 0.24, it prints the warning message:
```
pyodide.asm.js:9 pyodide.isPyProxy() is deprecated. Use `instanceof pyodide.ffi.PyProxy` instead.
```
So that is what you are supposed to do. It was marked as deprecated in #3523 and removed in #4342. You can look in those PRs to see the relevant changelog entries.

**Comment by cfry** [comment]
Just what I was looking for. Thank you!
Unfortunately they took out that helpful error message
in 0.25

**Comment by seanpk** [comment]
> `instanceof pyodide.ffi.PyProxy`

how do I do this from JavaScript? I cannot import types and only types are exposed from `pyodide/ffi`, and I do not have a `.ffi` property on my pyodide import

it looks like I can workaround this with:
```javascript
insanceof pyodide._api.isPyProxy(object)
```

but I know that's not recommended

**Comment by hoodmane** [comment]
> I know that's not recommended

You can do that if you want, it's just a "private api" meaning that it may disappear or change arbitrarily without notice between versions. Or it may not.

But why not use the public interface by doing:
```js
object instanceof loadedPyodide.ffi.PyProxy
```
