### ISSUE TITLE
Meson deprecation warning in `pyodide-build`: `pkgconfig` entry is deprecated and should be replaced by `pkg-config`

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide#4540]
## 🐛 Bug

While trying to build and test the PyWavelets package in CI, I'm currently experiencing this Deprecation warning from the Meson build system: https://github.com/agriyakhetarpal/pywt/actions/runs/8003758318/job/21859733890#step:7:21

### To reproduce

It is difficult to produce a very _minimal_ MWE, but the workflow file for the above run is available. This seems to be coming from here:

https://github.com/pyodide/pyodide/blob/1bbebf32929ee73684b084797ec600c35a42165e/pyodide-build/pyodide_build/tools/emscripten.meson.cross#L1-L4

### Expected behavior

Should be `pkg-config = 'pkg-config'`, instead of the current `pkgconfig = 'pkg-config'`

### Environment

- `pyodide-build` version: 0.25.0
- `meson-python` version: 0.15.0
- Browser version: N/A

### Additional context

I can try to fix this in a small PR, would appreciate pointers on how to verify if the change actually removes the warning or if I'm looking at the wrong place!

**Comment by hoodmane** [comment]
Thanks for the report @agriyakhetarpal! I can reproduce it. Your fix does seem to work. A PR would be welcome.
