### ISSUE TITLE
loadPyodide with indexURL tries to load stackframe.js from current url

### ISSUE THREAD

**Issue by simerlec** [pyodide/pyodide#4577]
## 🐛 Bug

Hello 👋 

I'm using pyodide (v0.25.0) in my NextJS project and have the following setup

- Copied the necessary files into the public folder
![image](https://github.com/pyodide/pyodide/assets/5793380/85213f54-c04a-4bda-a99c-746a9c198f7b)

- Used the [pyodide-webpack-plugin](https://github.com/pyodide/pyodide-webpack-plugin) to take care of the unsupported loader issues.
![image](https://github.com/pyodide/pyodide/assets/5793380/6ccdfac7-b420-445d-bc7b-e0fc77daf82b)

- loaded pyodide from the public folder (used a custom hook for it)
```javascript
export const usePyodide = () => {
  const [pyodide, setPyodide] = useState<any>(null);

  useEffect(() => {
    const initializePyodide = async () => {
      const pyodide = await loadPyodide({
        indexURL: `/pyodide`,
      });
      await pyodide.loadPackage('micropip');
      const micropip = pyodide.pyimport('micropip');
      await micropip.install('black');
      setPyodide(pyodide);
    };

    initializePyodide();
  }, []);

  return pyodide;
};
```

On run I'm getting this stacktrace.js error
![image](https://github.com/pyodide/pyodide/assets/5793380/92cde716-69ee-4702-9398-83a3db04ba78)

which is caused because it's trying to find it under the current full path which is `/web/build`. It cannot find it there ofc, so it's getting back the 404 page which it cannot parse, resulting in the exception.

![image](https://github.com/pyodide/pyodide/assets/5793380/72b2030f-ebfc-4e1f-b78b-4bfe8a17d40c)

The behaviour is completely clear to me but I'm not sure what I can do about it 🤔 I was under the impression that by setting the `indexURL` in the `loadPyodide` function I can tell pyodide where it can find all required files. And weirdly enough that also seems to be the case since the functionality itself is not broken? I can run python code just fine. In production this error is just 
"ignored" (printed to console but not breaking) but in dev mode it's more disruptive (see the error message screenshot).

### Expected behavior

Pyodide loading without the stacktrace.js error

### Environment

- Pyodide Version: 0.25.0
- Browser version: any browser
- Any other relevant information: NextJS

Any help would be appreciated.

Thank you and kind regards

**Comment by simerlec** [comment]
I believe it's related to https://github.com/microsoft/monaco-editor/issues/4384 and I can reproduce this issue as you can see in this [stackblitz](https://stackblitz.com/edit/stackblitz-starters-o5amwl?description=The%20React%20framework%20for%20production&file=pages%2Findex.tsx&title=Next.js%20Starter)

**Comment by ryanking13** [comment]
Thanks for the report, @simerlec. It looks like `stackframe.js` is related to the third-party library [`error-stack-parser`](https://www.npmjs.com/package/error-stack-parser) we use, but I am not sure how it is messed up when combined with Next.js or monaco editor... I think that some of the optimization logic used by bundlers doesn't fit well with Pyodide or `error-stack-parser`, but I am not very sure.

**Comment by Witzko** [comment]
Same issue arises when combining Pyodide with Vite and Monaco. Does not break the execution in dev mode though.

**Comment by itrcz** [comment]
same issue, monaco + vite too

**Comment by hoodmane** [comment]
Thanks @itrcz that's very helpful. Can we repro the bug in a plain webpage by defining `define.amd`? I think I can just use `sed` to replace `define.amd` with `false` and it would fix the problem.
