### ISSUE TITLE
Package request: Altair

### ISSUE THREAD

**Issue by joelostblom** [pyodide/pyodide#4579]
## 🐍 Package Request

- Package Name and Version: altair / latest (5.2)
- Package URL: https://pypi.org/project/altair/
- Package Dependencies that needs to be resolved first: None, [all the required dependencies](https://github.com/altair-viz/altair/blob/e58e8cbac613bf7babbd51d1798ec5da4b7d4fbb/pyproject.toml#L17-L27) are already listed at https://pyodide.org/en/stable/usage/packages-in-pyodide.html

Altair is a package for creating interactive data visualizations via a declarative syntax. Although the package is pure python and installable via micropip, it would be convenient to have it included in the base pyodide image (the wheel size is about 1MB). I'm a co-maintainer and happy to support with anything that is needed from the altair side of things to add it to the base pyodide image.

**Comment by hoodmane** [comment]
PR welcome!

**Comment by joelostblom** [comment]
Thanks for being open to a PR @hoodmane! I had a go using [the docs instructions](https://pyodide.org/en/stable/development/new-packages.html) and the package seems to build fine (I used the docker container), but I'm getting stuck at the step where I'm asked to open `localhost:<port>/console.html`. It seems like that file does not exist within the `dist/` directory. I tried serving the dist directory both from within docker and outside, and also to copy over the file manually. When I copy the file manually I get stuck at the spinning wheel that loads the terminal, and the browser console (both firefox and chromium) show the following error:

```
Uncaught (in promise) TypeError: The specifier “{{ PYODIDE_BASE_URL }}pyodide.mjs” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

Any idea of what is going on here and how I can run the console locally to test if the package built properly?

---

I can load https://pyodide.org/en/stable/console.html fine and it seems like the package built without issues:

![image](https://github.com/pyodide/pyodide/assets/4560057/8e939fb0-3852-4421-a2ed-cfadbd9401a6)

**Comment by hoodmane** [comment]
> It seems like that file does not exist

Try `make dist/console.html`

**Comment by joelostblom** [comment]
Thanks! It seems like I had to run `make all` in the end; I couldn't get it to work with just `all-but-packages` even when building `dist/console.html` separately. I added a note about this in the docs in https://github.com/pyodide/pyodide/pull/4581 and a PR for the altair package in https://github.com/pyodide/pyodide/pull/4580
