### ISSUE TITLE
Pyodide Error in Node.js v20+: `node-fetch` Resolution Failure

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4584]
## 🐛 Bug

pyodide is using `node-fetch` in node>=20

### To Reproduce

Start a devContainer in GitHub CodeSpace for [this repo](https://github.com/CNSeniorious000/pyodide-issue-node-fetch), which is a minimal vite + vanilla ts startup project.

### Expected behavior

After installing dependencies, run `npm run dev` or `vite`, and you will see errors like this:

```md

  VITE v5.1.4  ready in 198 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

✘ [ERROR] Could not resolve "node-fetch"

    node_modules/pyodide/pyodide.mjs:9:1352:
      9 │ ...q=(await import("url")).default,L=await import("fs/promises"),globalThis.fetch?_=fetch:(console.warn(pe),_=(await import("node-fetch")).default),V=(await import("vm")).default,P=await import("path"),A=P.sep,typeof E<"u"))return;let t=await import("fs"),e...
        ╵                                                                                                                             ~~~~~~~~~~~~

  You can mark the path "node-fetch" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle
  this failure at run-time instead of bundle-time.

```

### Environment

- Pyodide Version `^0.25.0`
- Browser version `Edge`
- Any other relevant information: StackBlitz uses node:18 so I recommend using devContainer to reproduce this error.

### Additional context

I know `pyodide` fallback to `node-fetch` if `globalThis.fetch` not found. Installing `node-fetch` can solve this, but I think I shouldn't do it because `node>=20` has builttin `fetch` already.

**Comment by hoodmane** [comment]
Thanks for the report @CNSeniorious000. We have several other recent reports about node-fetch, but I am not sure that this is a duplicate. I believe @mneil said that node-fetch has features that are still missing from the builtin fetch in node v20 so there is reason not to delete it yet. Is that right @mneil? Do you think we should be doing anything differently here?

**Comment by mneil** [comment]
Node fetch does have some differences (or did IIRC) but none of them impacting the use in pyodide. Node-fetch was already removed https://github.com/pyodide/pyodide/pull/4417 about a month ago. But it doesn't look like this has been released yet (as of v0.25.0).

I think the issue of not finding the module is because node-fetch was marked external and not also set as a dependency in package.json for pyodide. Releasing the change (if it's not already released) in 4417 should resolve the issue for everyone going forward.

**Comment by hoodmane** [comment]
Indeed #4417 didn't go into main. Good to know the problem will be resolved in the next release.

**Comment by ryanking13** [comment]
We dropped node-fetch fallback in Pyodide 0.26.0, so I believe this will not happen anymore.
