### ISSUE TITLE
Shim pandas to allow `pd.read_csv(url)` to work without URL error

### ISSUE THREAD

**Issue by coatless** [pyodide/pyodide#4585]
## 🐛 Bug

We cannot retrieve and load data in single a Pandas `pd.read_csv()` function call. Instead, we get `urllib.error.URLError` (error message below). 

<details>
<summary>

`urllib.error.URLError: <urlopen error unknown url type: https>`

</summary>

```py
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 363, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
         ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/io/common.py", line 265, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

</details>

### To Reproduce

Open [Pyodide REPL](https://pyodide.org/en/stable/console.html) and type:

```py
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
```

### Expected behavior

CSV would download onto the VFS like normal as it uses the HTTPS protocol. 

### Environment

- Pyodide Version: 0.25.0
- Browser version: Version 122.0.6261.69 (Official Build) (arm64)
- Any other relevant information:

### Additional context

This seems to be a problem that has been raised explicitly with: 

https://github.com/pyodide/pyodide/issues/375

There seems also to be a package that ships with base Pyodide that automatically shims the functions:

https://github.com/koenvo/pyodide-http

```python
# 1. Install this package
import micropip
await micropip.install('pyodide-http')

# 2. Patch requests
import pyodide_http
pyodide_http.patch_all()  # Patch all libraries
```

I'm partial to adopting the `pyodide-http` approach as it reduces the friction between moving from a local copy of Python to a Pyodide version. However, I did see that the [`pyodide.http` module](https://pyodide.org/en/stable/usage/api/python-api/http.html#module-pyodide.http) with [`open_url()`](https://pyodide.org/en/stable/usage/api/python-api/http.html#pyodide.http.open_url) and [`pyfetch()`](https://pyodide.org/en/stable/usage/api/python-api/http.html#pyodide.http.pyfetch) exists. I'm wondering why these functions are not setup to be replacements for common URL operations.

**Comment by coatless** [comment]
Notes to my future self or someone else who stumbles upon this thread:

- The problem is a lack of sockets or TLS APIs for Emscripten/WASI causing the usual `urllib3` behavior to fail when querying URLs.
- The creator of `urllib3` mentioned initial support for Python's WASM backend in `urllib3` version 2 in: https://sethmlarson.dev/urllib3-is-fundraising-for-http2-support#support-for-webassembly-and-emscripten
- The [PR urllib3/urllib3#3195](https://github.com/urllib3/urllib3/pull/3195) with native support landed on Nov 25, 2023 and was part of the [`urllib3` 2.2.0 release](https://github.com/urllib3/urllib3/releases/tag/2.2.0) on Jan 30, 2024.
- This PR uses JS `fetch`/XHR under the hood instead of using `urllib3` to get around the sockets hiccup.
- As it stands, pyodide version 0.25.0 ships with [`urllib3` 2.1.0](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) as part of the default configuration. So, we cannot get the benefits until a later version of `pyodide` is available with an updated base default.
- Our current workaround is then to use [`pyodide-http`](https://github.com/koenvo/pyodide-http), which provides  `pyodide_http.patch_all()` function to patch `requests` and `urllib3` requests.

So, using: 

```python
import pyodide_http
pyodide_http.patch_all()  # Patch all libraries
```

This gives us a nice shim for the time being.

**Comment by hoodmane** [comment]
> Notes to my future self

Thanks @coatless!

**Comment by rplopes** [comment]
Thank you for those notes @coatless.

To add to that context, as of today, the latest pyodide version is 0.27.0, which includes [urllib3 2.2.3](https://github.com/pyodide/pyodide/blob/d27f6684ea948741e0137056fb06b7832f0f6525/packages/urllib3/meta.yaml#L2). However, the error still remains when reproducing the code exampel above.

**Comment by ryanking13** [comment]
@rplopes 

Yes, Pandas uses builtin `urllib` not `urllib3` so the error still remains. Instead of reading the CSV file from the URL directly, you can download the csv file with `urllib3` or `fetch` or any other methods first then read from the file system.

**Comment by agriyakhetarpal** [comment]
Would it make sense to monkeypatch `urllib` so that it runs `urllib3` if called, say, through `pyodide-http`? I don't know to what extent the difference in the public API for both is, or if `urllib`'s is a subset of `urllib3`s.
