### ISSUE TITLE
please add numpy_financial

### ISSUE THREAD

**Issue by ndor** [pyodide/pyodide#4599]
## 🐍 Package Request

- Package Name and Version : numpy-financial
- Package URL : https://numpy.org/numpy-financial/
- Package Dependencies that needs to be resolved first: numba

Thank you guys! 
you rock!

**Comment by gabrielfougeron** [comment]
This may take a while because of numba. cf https://github.com/pyodide/pyodide/issues/621

**Comment by ryanking13** [comment]
Numba doesn't seem like a dependency of numpy-financial, and numpy-financial is a pure Python package that can be installed with `micropip.install`. Could you try installing it with micropip?

**Comment by ryanking13** [comment]
Closing as resolved. But please don't hesitate to reopen if you have any issues.
