### ISSUE TITLE
Hosting all pyodide files and packages

### ISSUE THREAD

**Issue by jappyjan** [pyodide/pyodide#4600]
I would like to host all the files I need to run my python script (pyodide engine, pip packages, etc) on my own server but I'm struggling to get this working.

My current approach is to set the indexURL to a directory hosted by my server in which I place all files that have been downloaded from cdn, and also use full urls to the pip wheels hosted in the same directory when using micropip/package install commands, but when I do this I get a sha256 digest error.

Can you please point me in the right direction to how to do this properly?

**Comment by rth** [comment]
That's a reasonable approach. You can run `micropip.freeze()` to get an updated `pyodide-lock.json` including your custom wheels. 
 You shouldn't be getting sha256 digest errors. Can you check the sha256sum of the failing files and compare it against the values written in `pyodide-lock.json`. You can always change sha256 checksums there, but it shouldn't be necessary unless the files are somehow modified.

**Comment by jappyjan** [comment]
so jus for clearification:

1. run without custom cdn
2. run .freeze and store lockfile in cusotm cdn 
3. download .whl files for all used packages (also dependencies of dependencies?)
4. set indexURL and (if name is not pyodide-lock.json) lockFileURL to custom "cdn"

install packages as usual but use a full url to .whl file instead of just the name
(do i now also have to install the sub dependencies manually ? )
