### ISSUE TITLE
Empscripten Version Mismatch: Packages built with Emscipten 1.52.1 (current builder config) is incompatible with Pyodide 0.25.0.

### ISSUE THREAD

**Issue by type9** [pyodide/pyodide#4635]
## 🐛 Bug

Started by building my own pyodide-package.

When loading it with the most recent stable release of pyodide it refuses to load because 0.25.0 was built with emiscripten `1.46.1` and the most recent package is emiscripten `1.52.1`. When reading through issues here the maintainers note that 0.25.0 uses escripten `1.52.1` but packages built with that versions are refused due to pyodide's supposed use of `1.46.1`.

Current workaround has been to use latest experimental version of pyodide @0.26.0a4

### To Reproduce

Build you own Pyodide package using pyodide-builder's most recent version.

loading method
```ts
const loadPackages = async (pyodide: PyodideInterface, packages: string[]) => {
	await pyodide.loadPackage("micropip")
	const micropip = await pyodide.pyimport("micropip")
	await micropip.install(packages, true)
	console.log("Successfully insalled packages")
}
```

pyodide served through origin. version 0.25.0
```ts
export const PYODIDE_INDEX_URL = "/pyodide/"
```

### Expected behavior

Package should load since supposedly the versions match, despite the error message.
Maybe I misread the issues but supposedly 1.52.1 should work with 0.25.0.

### Environment

- Pyodide Version:
- Browser version:

**Comment by ryanking13** [comment]
> When reading through issues here the maintainers note that 0.25.0 uses escripten 1.52.1 but packages built with that versions are refused due to pyodide's supposed use of 1.46.1.

Pyodide 0.25.0 is built with Emscripten `3.1.46`. I'm wondering if I wrote the wrong version information in another issue, where did you see that?

**Comment by type9** [comment]
hmm it's also possible I misread. As long as its intentional I'll close off this thread.
