### ISSUE TITLE
`.toJs()` of a `dict` gets empty map/object

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4636]
## 🐛 Bug

- Converting a python `dict` to a js map/object is ok.
- Convertinig an instance of a subclass of `dict` to a js map/object is ok too.
- But Converting an instance of a subclass of both `dict` and `ChainMap` to a js map/object gets an empty map/object

### To Reproduce

First, make a JavaScript function to show what it gets:

```py
>>> from pyodide.code import run_js
>>> j = run_js("""(d) => JSON.stringify(d.toJs({ dict_converter: Object.fromEntries }))""")
>>> j({"a": "b"})
'{"a": "b"}'
```

Then we make a subclass `D` to extend `dict`, its converting works fine:

```py
>>> class D(dict):
...     pass
...
>>> j(D({"a": "b"}))
'{"a":"b"}'
```

But this fails:

```py
>>> from collections import ChainMap
>>> class D(ChainMap, dict):
...     pass
...
>>> j(D({"a": "b"}))
'{}'
```

Plus, I found that the mro matters:

```py
>>> class D(dict, ChainMap):  # here we change the order of base classes
...     pass
...
>>> j(D({"a": "b"}))
'{"a":"b"}'
```

But it should not be like this. I noticed the `dict_converter` receives an iterator of `[key, value]`, isn't it comes from the `.items()` method?

The `D` instances above do have a right `.items()` method but why the result is empty? So I believe this is a bug. I haven't find related information in the document yet.

### Expected behavior

```py
>>> from collections import ChainMap
>>> class D(ChainMap, dict):
...     pass
...
>>> j(D({"a": "b"}))  # this shouldn't returns '{}'
'{"a":"b"}'
```

### Environment

- Pyodide Version `0.25.0`
- Browser version `Edge 122.0.2365.92`

**Comment by hoodmane** [comment]
We iterate over the dictionary with `PyDict_Next`. Apparently `PyDict_Next` sees the `ChainMap, dict` as being empty whereas it sees the `dict, ChainMap` correctly. It seems like the best way to handle this is indeed to use the `.items()` method, at least unless `PyDict_CheckExact` returns true (it requires a bit of extra code to do this). It would also be possible to convert anything that considers itself a Map as a followup...
