### ISSUE TITLE
Allow importing Python files from a URL

### ISSUE THREAD

**Issue by mdboom** [pyodide/pyodide#469]
It would be nice to make this work:

```
module = pyodide.import_url("http://iodide-project.github.io/pyodide/module.py")
```

**Comment by vadimkantorov** [comment]
we had some discussion with @rth about a related feature in https://github.com/iodide-project/pyodide/issues/417

**Comment by ryanking13** [comment]
From Pyodide 0.19.0, [we provide several ways to load external Python files from URL](https://pyodide.org/en/stable/usage/loading-custom-python-code.html), and it's OK to use `pyodide.runPython(pyodide.open_url('https://raw.github.com/...'))`. Closing.

**Comment by pannous** [comment]
since this is such a fundamental and important feature you might want to wrap it into one central function
`pyodide.import(...)`

**Comment by ryanking13** [comment]
> since this is such a fundamental and important feature you might want to wrap it into one central function `pyodide.import(...)`

Yeah, feel free to reopen (or open a new issue) if you want to discuss with us having a convenient wrapper for running Python codes directly from URL.
