### ISSUE TITLE
Release 0.26.0

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4713]
It's about time to release v0.26.0. I'd like to include memory snapshots, I think the bindings #4699 can wait.
@ryanking13 anything you want to get in?

- [x] enable xgboost

**Comment by hoodmane** [comment]
I would like to add it as public but marked experimental.

**Comment by ryanking13** [comment]
>  I would like to add it as public but marked experimental.

Sounds good!

**Comment by hoodmane** [comment]
I think we can go ahead and release with what we have. I guess we should draw up some release notes.

**Comment by ryanking13** [comment]
Good! Let's make a release before PyCon, if possible.

**Comment by hoodmane** [comment]
Two problems:
1. docs didn't deploy
2. [Update cross-build metadata file](https://github.com/pyodide/pyodide/actions/workflows/update_cross_build_releases.yml) failed

I can fix docs.

**Comment by agriyakhetarpal** [comment]
I checked and both the workflow and the `tools/update_cross_build_releases.py` seem okay to me, it worked locally with an environment variable. So the only reasonable explanation is that the environment variable did not percolate to the steps after it.

**Comment by agriyakhetarpal** [comment]
Found the error: it should have been

```yaml
echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
```

i.e., missing an extra `>` character

**Comment by agriyakhetarpal** [comment]
Never mind – https://github.com/pyodide/pyodide/pull/4808 fixed it already

**Comment by hoodmane** [comment]
Okay I fixed the docs.

**Comment by ryanking13** [comment]
Thanks for finishing the release!

> [Update cross-build metadata file](https://github.com/pyodide/pyodide/actions/workflows/update_cross_build_releases.yml) failed

I'll update the metadata file manually. It is not yet used, so it is not an big issue.
