### ISSUE TITLE
loadPackage() not to access the file system if the cache already exists

### ISSUE THREAD

**Issue by whitphx** [pyodide/pyodide#4736]
## 🚀 Feature

`pyodide.loadPackage()` should not access the file system with `nodeFsPromisesMod.mkdir` when not necessary, or the cache dir already exists.
It can be done automatically, or by providing an option to skip the file system access.

### Motivation

`loadPackage()` [calls `nodeFsPromisesMod.mkdir` any time](https://github.com/pyodide/pyodide/blob/c4a6964429fe4904c33a6a6b5771b173bf4ee9f8/src/js/load-package.ts#L261-L263) to ensure the directory exists.
However, it causes an error if the file system is read-only even when the directory and the cached packages already exist.
My actual use case is to ship Pyodide in an Electron app with the downloaded package files. In this case, the bundled files are visible to the Node process of the Electron app via `fs` module but not writable as they are packaged in an [ASAR archive](https://www.electronjs.org/docs/latest/tutorial/asar-archives) and [the archive is read-only](https://www.electronjs.org/docs/latest/tutorial/asar-archives#archives-are-read-only). It's https://github.com/whitphx/stlite/issues/831#issuecomment-2081755934.

### Pitch

* One option is to call `mkdir` only when the cache directory does not exist.
* Another is to add an option to skip the file system access, e.g. `loadPackage(packageName, { skipDownload: true })`.

**Comment by hoodmane** [comment]
> One option is to call mkdir only when the cache directory does not exist.

This sounds good. PR welcome.

**Comment by ryanking13** [comment]
Sounds good to me too. Actually, this behavior was problematic in Deno too: https://github.com/pyodide/pyodide/issues/4624.
