### ISSUE TITLE
cvxpy-base 1.4.3

### ISSUE THREAD

**Issue by pablormier** [pyodide/pyodide#4740]
CVXPY is a modelling library for disciplined convex programming. It supports the HIGHs solver available in Scipy to solve LP and MIP problems, which makes this lib very interesting for interactive learning on the browser. They've recently released a cvxpy base package that does not require additional dependencies.

## 🐍 Package Request

- Package Name and Version cvxpy-base 1.4.3
- Package URL : https://pypi.org/project/cvxpy-base/
- Package Dependencies that needs to be resolved first: pybind11, scipy, numpy

The package uses C extensions

Related: https://github.com/pyodide/pyodide/issues/3083

**Comment by pablormier** [comment]
I successfully build the cvxpy-base package and tested it with Python 3.11
[cvxpy_base-1.4.3-cp311-cp311-emscripten_3_1_46_wasm32.zip](https://github.com/pyodide/pyodide/files/15210948/cvxpy_base-1.4.3-cp311-cp311-emscripten_3_1_46_wasm32.zip)

![image](https://github.com/pyodide/pyodide/assets/1433810/436948b7-fa1a-4630-ab56-cc0ac354d92f)

**Comment by ryanking13** [comment]
This is already resolved by https://github.com/pyodide/pyodide/pull/4587. You will be able to use it in next pyodide release.
