### ISSUE TITLE
html5_canvas_backend no longer works.

### ISSUE THREAD

**Issue by kasajian** [pyodide/pyodide#4745]
## 🐛 Bug

Check out this jsfiddle: 
https://jsfiddle.net/gh/get/library/pure/pyodide/pyodide-blog/contents/demos/canvas-renderer-matplotlib/demo-1/

It uses version v0.20.0
v0.21.3 will work.
Starting with version 0.22, it stopped working
The latest version, 0.25.1, doesn't work.

You get error:
ModuleNotFoundError: No module named 'matplotlib.backends.html5_canvas_backend'

**Comment by ryanking13** [comment]
Closing as answered in matplotlib-pyodide https://github.com/pyodide/matplotlib-pyodide/issues/58#issuecomment-2099806613
