### ISSUE TITLE
`make` in docker container `pyodide/pyodide-env` fails with `could not create work tree dir 'emsdk'`

### ISSUE THREAD

**Issue by goulashsoup** [pyodide/pyodide#4753]
## 🐛 Bug

`make` not working in docker container `pyodide/pyodide-env`:

```
@e8b479cd0979:/src$ make
[2024-05-10 20:55:07] Building emsdk...
make -C emsdk
make[1]: Entering directory '/src/emsdk'
if [ -d emsdk ]; then rm -rf emsdk; fi
git clone --depth 1 https://github.com/emscripten-core/emsdk.git
fatal: could not create work tree dir 'emsdk': Permission denied
make[1]: *** [Makefile:8: emsdk/.complete] Error 128
make[1]: Leaving directory '/src/emsdk'
make: *** [Makefile:313: emsdk/emsdk/.complete] Error 2
```

### To Reproduce

Probably prune docker images first, run `./run_docker` and then when the container is in interactive terminal, run `make` inside the container.

### Expected behavior

Build successful.

### Environment

- Pyodide Version: 0.25.1
- Browser version: -

- Commit hash of Pyodide git repository: 3d127ea24931d18b3a4710bcf43f81db2efebe67 and afe7215c06ec9cb5a4d145c4e28dd974038852bc
- Build environment: Ubuntu 23.10 LTS, Docker Desktop on Linux 4.30.0

**Comment by hoodmane** [comment]
Maybe try `./run_docker --root`?

**Comment by goulashsoup** [comment]
@hoodmane Thanks, that worked, but the docs don't state that I need root: https://pyodide.org/en/stable/development/building-from-sources.html

**Comment by goulashsoup** [comment]
Added a PR for `--root` option in the docs.

**Comment by goulashsoup** [comment]
@hoodmane If I should not use `--root` what permissions should I set before executing `./run_docker`.

**Comment by goulashsoup** [comment]
> there is something specific to the way permissions are working on your machine that is breaking it without it.

It's a "normal" Ubuntu, no custom changes regarding permissions made actually...

I think it more likely that, when you checked in on a Linux, that you changed some permission once, and forgot about them writing the documentation.

**Comment by hoodmane** [comment]
Well I develop primarily on linux (Ubuntu 22.04.3) and I think most of the main contributors use linux as well. Though I stopped using the docker container a while ago. I think linux is actually the only OS that is at least vaguely well supported. Windows works via WSL and Mac development sometimes is more broken and other times less broken.

When you run `run_docker` without root, it tries to set up a user inside the container that matches the user outside of the container. If the checkout is owned by your user, this should mean the in-container user has the permission to write to emsdk. My best guesses are:

1. for some reason when you cloned the repo it was owned by a different user and maybe you're in a group that has write permissions or something. but that group info isn't copied into the container for some reason
2. the run_docker script's code to copy your user into the docker image somehow screwed up and so it sees the inside-docker user as distinct from the outside-docker user and lacks permission.

This is the relevant part of the script:
https://github.com/pyodide/pyodide/blob/main/run_docker?plain=1#L118-L128

**Comment by goulashsoup** [comment]
> for some reason when you cloned the repo it was owned by a different user and maybe you're in a group that has write permissions or something.

That could be the case, as I cloned the repo with "PyCharm > File > Project from Version Control...".

I had to check if works without `--root` if I clone the repo via terminal.

But I would still like to keep the `--root` note in the docs, as it is nice to know this options exist...

**Comment by hoodmane** [comment]
Agreed. I guess I'll close this then.
