### ISSUE TITLE
STATUS_BREAKPOINT on Microsoft Edge

### ISSUE THREAD

**Issue by njzjz** [pyodide/pyodide#4774]
## 🐛 Bug

When visiting pyodide applications using Microsoft Edge, I got `STATUS_BREAKPOINT` error.

### To Reproduce

Use Microsoft Edge 125.0.2535.51 to visit https://pyodide.org/en/stable/console.html. It also doesn't work using InPrivate mode.

![image](https://github.com/pyodide/pyodide/assets/9496702/ecc67c03-e7e4-4664-bbf2-5cc0acfa0067)

### Expected behavior

No errors, like the behavior in Google Chrome 125.0.6422.61.

### Environment

- Pyodide Version:  0.25.1
- Browser version: Edge 125.0.2535.51
- Any other relevant information:

### Additional context

Not sure whether it is a bug in Microsoft Edge or Pyodide.

**Comment by ryanking13** [comment]
Hmm, I cannot reproduce it in my Windows 10 + Microsoft Edge 124.0.2478.105. If someone can reproduce it it would be helpful for us to debug.

**Comment by njzjz** [comment]
Close, as I don't think it can be reproduced anymore.
