### ISSUE TITLE
`crc32c`

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide#4787]
## 🐍 Package Request

- Package Name and Version : `crc32c`, version 2.4
- Package URL : https://pypi.org/project/crc32c/, https://github.com/ICRAR/crc32c
- Package Dependencies that needs to be resolved first: [none](https://github.com/ICRAR/crc32c/blob/master/setup.py) – this is a package written in C with Python bindings.

## 📝 Additional context

xref: https://github.com/zarr-developers/zarr-python/pull/1903, i.e., this is a required dependency of the upcoming version 3 for Zarr at the time of writing.

**Comment by agriyakhetarpal** [comment]
I would be happy to try this out!

**Comment by agriyakhetarpal** [comment]
I see that SSE2 instructions are used, they will probably need to be disabled in some way...

**Comment by agriyakhetarpal** [comment]
With the `pyodide build-recipes crc32c --install` command:

`[8/13] (thread 8) built crc32c in 24s` 🎉

I will be adding a few tests from their test suite now to confirm that the basic functionality for the package works. Their license is the LGPL-2.1, though. Would that be all right or should I write a faction of the tests entirely by myself?

**Comment by hoodmane** [comment]
I don't think it matters because we aren't mixing it into our logic or running it at runtime. But we don't need all the tests either.
