### ISSUE TITLE
pyodide build should read settings from pyproject.toml

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4799]
> Could pyodide build read from tool.pyodide.build in pyproject.toml, by the way, perhaps? At least the exports setting might be useful there!

Said @henryiii https://github.com/pypa/cibuildwheel/pull/1456#issuecomment-2132064435

This is a great idea cc @ryanking13.

**Comment by ryanking13** [comment]
Yes, that's what I was planning to put here:

https://github.com/pyodide/pyodide/blob/81e4d200dbdf74fdaffa7d59c544c8e5e56c96d2/pyodide-build/pyodide_build/config.py#L92-L94

We should probably use `tool.pyodide_build`, as we are using `tool.pyodide` to detect whether we are in an in-tree build (or change the logic of detecting in-tree build).

@RulerOfCakes Are you interested in working on this?

**Comment by hoodmane** [comment]
Especially now that the public command is called `pyodide` I think that should be the public key and we should use something else internally.

**Comment by hoodmane** [comment]
@henryiii was complaining that `pip install pyodide` doesn't install the Pyodide cli and `pip install pyodide-cli` is also useless. We need to do some work on the ux of out of tree builds, particularly the install step.

**Comment by ryanking13** [comment]
> We need to do some work on the ux of out of tree builds, particularly the install step.

Yeah, I agree that there are a lot of pyodide-* tools, which can be confusing.

But even if most people are interested in pyodide-build, it's not the only pyodide tool, so I'm not sure how best to name it.

Maybe we can add all `pyodide-*` packages as a dependency of `pyodide` so that if users install `pip install pyodide`, then all pyodide tools become available.

**Comment by ryanking13** [comment]
@RulerOfCakes thanks! Here are some information that will help you do this task:

0.

What we want is to let people specify some pyodide-build configs in `pyproject.toml` file. For instance,

```toml
[tool.pyodide.build]
meson_cross_file = "path/to/meson.cross"
```

1.

We have a fixed set of variables that are used in pyodide-build:

https://github.com/pyodide/pyodide/blob/81e4d200dbdf74fdaffa7d59c544c8e5e56c96d2/pyodide-build/pyodide_build/config.py#L109-L111

but not all of them should be able to be overridden by the config file. For now, we don't distinguish between them properly (it's a TODO and you can work on it as a followup if you are interested). So I think we make a separate list of variables that are "overridable by config file". I think we can start with a very small set of variables like "side_module_cflags", "side_module_ldflags",  "rust_toolchain", "meson_cross_file" that people might be interested in overriding it.

2.

python has a toml parser in its stdlib. We are using it here: https://github.com/pyodide/pyodide/blob/e3f518d1d3aab8c6222e15c12f332ca810974250/pyodide-build/pyodide_build/build_env.py#L94

**Comment by henryiii** [comment]
I'd love to see the ones from the initial issue supported.

If `side_module_cflags` and `side_module_ldflags` are equivalent to setting LDFLAGS and CFLAGS, that's fine (though why not cxxflags?), but the other important one is the `exports` setting, which may need to be set to `whole_archive`.

I don't really see much info on SIDE_MODULE_CFLAGS, so can't tell what it's used for.

**Comment by henryiii** [comment]
Ahh, I found where it's being used, SIDE_MODULE_*FLAGS is fine, but the cxx one should be included.

**Comment by hoodmane** [comment]
I don't think it makes a whole lot of sense to call the public flag `SIDE_MODULE_*FLAGS` it should be just called `*FLAGS`. The `SIDE_MODULE_` prefix is a detail internal to Pyodide's build setup which we shouldn't leak into out of tree package builds.

**Comment by ryanking13** [comment]
> I don't think it makes a whole lot of sense to call the public flag `SIDE_MODULE_*FLAGS` it should be just called `*FLAGS`. The `SIDE_MODULE_` prefix is a detail internal to Pyodide's build setup which we shouldn't leak into out of tree package builds.

Sounds reasonable to me.
