### ISSUE TITLE
issue using pygame-ce

### ISSUE THREAD

**Issue by Vandivier** [pyodide/pyodide#4805]
## 🐛 Bug

My Chrome devtools stated "Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers."

### To Reproduce

1. Here is [the literal commit reference](https://github.com/Vandivier/arias-tale-tcg-python/commit/b063ff91e305d0943a82001544ad9973c986417b) under error
2. build the code with `python build.py`
3. drag `dist/index.html` into a browser
4. view dev tools

note that:
1. I'm using Python 3.11.3
2. `pyodide/dev/full/pyodide.js` points to `v0.26.0.dev0` at the time of bug reporting

### Expected behavior

The Python code runs without error and I am able to see a populated canvas for at least a basic initial load UI

**Comment by hoodmane** [comment]
Can you give the full traceback? Also, what happens if instead of `dev` you use `0.26.0a6`? `dev` is intrinsically a bit unstable, sometimes we commit something to main that breaks things.

**Comment by hoodmane** [comment]
Also, try running it with the debug build so that the traceback has more information.

**Comment by Vandivier** [comment]
i'm importing via CDN.
`<script src="https://cdn.jsdelivr.net/pyodide/0.26.0a6/full/pyodide.js"></script>`
yields
```
loadPyodide is not defined
    at main (index.html:61:27)
```

looks like
"the specified key does not exist" on
https://cdn.jsdelivr.net/pyodide/0.26.0a6/full/pyodide.js

i'll use the debug build later today

**Comment by Vandivier** [comment]
ran into the same issue if i `<script src="https://cdn.jsdelivr.net/pyodide/dev/debug/pyodide.asm.js"></script>`
but i can successfully `<script src="https://cdn.jsdelivr.net/pyodide/dev/debug/pyodide.js"></script>` and the stack talks about *.asm.js anyway. few error blocks:

<img width="646" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/1a3bb3ed-c179-4242-9d8e-2bdf50046cbc">


<img width="646" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/eabb0899-52c6-4c40-97e8-f9eedecffbb1">


<img width="612" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/d33d486d-8eb2-4262-8224-183661b00317">

<img width="612" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/22cc580c-077f-441b-b63b-45b6f3659dca">


I'll add the text form momentarily. couldn't get it on my clipboard correctly so i'll have GPT transcribe the images

**Comment by ryanking13** [comment]
> there can only be one canvas attached to pyodide at a time

Yes, that's a limitation of SDL emscripten as far as I know ([https://github.com/emscripten-core/emscripten/issues/2271, https://github.com/emscripten-core/emscripten/issues/19407](https://github.com/libsdl-org/SDL/issues/5260))

**Comment by Vandivier** [comment]
after setting canvas as recommended and upgrading to stable, i no longer get the previous error! actually I don't see any error at all!

but, the game still doesn't appear to load. the web page seems to hang and not paint the canvas. even the dom is not described in dev tools:

<img width="1083" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/a1db83b0-05b4-42d9-9554-2a420fed67e9">



Commit ref: [5be3ce8](https://github.com/Vandivier/arias-tale-tcg-python/commit/5be3ce844603c63a922f76146f69c6d3333607be)

**Comment by ryanking13** [comment]
1. In css, display attribute for the canvas is set to none.

```
canvas {
  display: none;
}
```

2. `runPython` blocks the main thread, so if there is an infinite loop inside the python code, the browser UI will freeze.

So, instead, you need to use `runPythonAsync` and use async functions.

```
# pythonScript
async def main():
    ....
    while running:
        do_something()
        await asyncio.sleep(...)

await main()
########

pyodide.runPythonAsync(pythonScript);
```

Note that clock.tick will not work as it relies on `SDL_Delay` and it doesn't work in the main thread (https://github.com/emscripten-core/emscripten/blob/223d61ee19964b7b58a29be77d81d465032361c9/src/library_sdl.js#L1725-L1729), so you need to use asyncio.sleep instead.

**Comment by Vandivier** [comment]
incremental progress! the thread is unblocked and the canvas is painted, but I can't play a game because of a pk issue and in particular, every keydown generates another error instance:

<img width="1275" alt="image" src="https://github.com/pyodide/pyodide/assets/5559355/f1d9ee98-e08c-4f3f-b3d2-e6ddf9ec8382">

**Comment by Vandivier** [comment]
here's the latest commit associated w the dynamic linking error + pic above, it also includes trying on v26.1 (tried .0 and .1)
https://github.com/Vandivier/arias-tale-tcg-python/commit/a53de25e26b0ebe68832acc79d241c86939f01c6

**Comment by ryanking13** [comment]
Thanks for the report. I can reproduce the error. It seems like how libSDL handles the keyboard input was changed a bit around [2.25~2.26](https://github.com/libsdl-org/SDL/commit/92215481146f9225a458e9a09abb85a33b52d9ff), and emscripten did update the libSDL version from [2.24 to 2.26 in 3.1.54 release](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3154---021524) so I guess that is the reason for the error.

I think the workaround would be linking `libhtml5` to the Pyodide main module. Let me see if I can fix it.
