### ISSUE TITLE
rasterio: Add package request

### ISSUE THREAD

**Issue by lukefullard** [pyodide/pyodide#4839]
## 🐍 Package Request

- Package Name and Version : [rasterio](https://github.com/rasterio/rasterio) 1.3.10
- Package URL -->: https://github.com/rasterio/rasterio
- Package Dependencies that needs to be resolved first: None that I am aware of

This package is widely used in geospatial loading of clipped raster images and is a dependency in many geospatial packages.
It is not pure python as it uses cython for some of the base code.

**Comment by hoodmane** [comment]
Looks easy enough to add indeed. PR welcome.
