### ISSUE TITLE
Pandas is sending DeprecationWarning in 0.26.0

### ISSUE THREAD

**Issue by tazzben** [pyodide/pyodide#4840]
## 🐛 Bug

Pyodide is resulting in Pandas sending out a depreciation warning:

```
<exec>:5: DeprecationWarning: 
[Error] Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
...
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
```

Presumably, Pandas was updated in the latest release to a version that wants Pyarrow. 

### To Reproduce

Load Pyodide with Pandas

### Expected behavior

No warning

### Environment

- Pyodide Version: 0.26.0
- Browser version: Safari

**Comment by ryanking13** [comment]
We don't support pyarrow yet #2933.
