### ISSUE TITLE
memoize in loadDynlibsFromPackage has no effect

### ISSUE THREAD

**Issue by maartenbreddels** [pyodide/pyodide#4847]
Hi,

I was looking at this line:
 * https://github.com/pyodide/pyodide/blame/807250e8d22aa92213f9ad3e20648f109d079582/src/js/dynload.ts#L161

And it seems to have no effect, because the memorize creates a closure every time the function gets called. I guess it should move to the global namespace. I don't know if this is relevant for performance.

**Comment by hoodmane** [comment]
Thanks for the report. cc @ryanking13.

**Comment by ryanking13** [comment]
> creates a closure every time the function

That's intended. I want the memorize affect only in the function scope and get freed after the function call. readfile is called multiple times in that function.

We probably need to improve the JS test to test the performance improvement with memoize though.

**Comment by hoodmane** [comment]
Maybe we could add a comment here, since I've been confused by this too.

**Comment by ryanking13** [comment]
> Maybe we could add a comment here, since I've been confused by this too.

Yeah, I'll add more comments.

**Comment by maartenbreddels** [comment]
> That's intended. I want the memorize affect only in the function scope and get freed after the function call. readfile is called multiple times in that function.

Ok, sorry for the noise then. I was looking through the code to learn how this all works, and I care about the performance of pyodide, so I hoped to have found an improvement :)

Love pyodide, keep up the good work 👍

**Comment by hoodmane** [comment]
No I appreciate this @maartenbreddels  I didn't understand this code either. Please feel free to open more issues like this if you have questions about the code base they are generally very helpful.
