### ISSUE TITLE
micropip.install('colour') fails with `'str' object has no attribute 'name'`

### ISSUE THREAD

**Issue by eulertour** [pyodide/pyodide#486]
This is easy to verify at https://alpha.iodide.io/notebooks/300/. The error is the same as in #413, so it's bound to be related to the way colour handles its dependencies.

**Comment by joostvanzwieten** [comment]
With the latest release (0.14.0) it should work.

**Comment by rth** [comment]
Can confirm it's no longer an issue in 0.18.0
