### ISSUE TITLE
Imports in the REPL cause infinite recursion error (0.26.1)

### ISSUE THREAD

**Issue by szabolcsdombi** [pyodide/pyodide#4860]
## 🐛 Bug

On the latest stable version, using the live [REPL](https://pyodide.org/en/stable/console.html)

```
Welcome to the Pyodide 0.26.1 terminal emulator 🐍
Python 3.12.1 (main, Jun  7 2024 22:40:30) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import something
```
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RangeError: Maximum call stack size exceeded
Look in the browser console for more details.
```

### To Reproduce

Type `import sys` or any other import statement into the REPL

### Expected behavior

no recursion error

### Environment

- Pyodide Version import something:
- Browser version 125.0.6422.142:
- Any other relevant information:

**Comment by szabolcsdombi** [comment]
Should be trivial to reproduce, however here are some console screenshots just in case.

![image](https://github.com/pyodide/pyodide/assets/11232402/bb96f8fe-6c6b-4dfd-bbb9-b92df384556d)
![image](https://github.com/pyodide/pyodide/assets/11232402/9296e1df-271c-47b2-b7eb-25399f4ebf79)

**Comment by szabolcsdombi** [comment]
i also suspected a local issue then i managed to reproduce it on my phone as well.

**Comment by szabolcsdombi** [comment]
works on an iPad

**Comment by szabolcsdombi** [comment]
works on my ubuntu 24.04, chrome 125.0.6422.141

**Comment by szabolcsdombi** [comment]
I can consistently reproduce it on my window 11 laptop and my android phone. (even in incognito)
None of my friends can reproduce it.
This bug has to do something with async.

![image](https://github.com/pyodide/pyodide/assets/11232402/fbf72cf0-731e-44be-b51a-c8bd2d9912af)

**Comment by szabolcsdombi** [comment]
Running anything causes the same error, even an empty line triggers it.
If I change the `jspiSupported` flag to `false` everything works as expected.

```js
pyodide._module.jspiSupported = false
```

or, the following helps as well:

```js
pyodide._module.callPyObjectMaybePromising = pyodide._module.callPyObject
```

Some more findings:

There are two different PyObjects scheduled by `scheduleCallback` with delay=0.
After the two `scheduleCallback` calls, the first of them calls to `callPyObjectMaybePromising` triggering the error.

**Comment by szabolcsdombi** [comment]
[0.25.1](https://pyodide.org/en/0.25.1/console.html) detects `pyodide._module.jspiSupported` as `false` because `"Suspender" in WebAssembly` is also `false`.

**Comment by ryanking13** [comment]
I see. Thanks for the check. Probably something is malfunctioning when JSPI is enabled.

**Comment by szabolcsdombi** [comment]
I think I might be part of an A/B testing, because the very same chrome.exe with a --user-data-dir= flag set does not produce the error unless I log in with my account.

**Comment by szabolcsdombi** [comment]
Everything works fine with 0.26.2 thank you for fixong this!
