### ISSUE TITLE
PyProxy seems to have strange behavior in `0.26.1`

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4861]
## 🐛 Bug

The description is a bit complicated, I recommend jump into the [stackblitz reproduction](https://stackblitz.com/edit/pyodide-issue-demo?file=src%2FMain.svelte).

I am using pyodide in a few complicated code-gen like usage, which need to exec dynamic python code from JavaScript. These code works well from pyodide `0.25.0` to `0.26.0`, but broke in `0.26.1`. The error message is strange and I can't find why. I looked into the diff between tag 0.26.0 and 0.26.1 but failed to tell which change caused this.

After simplifying, here is the minimal reproduceable example.

First, I execute code in a `ChainMap` for not polluting the global namespace, sounds reasonable, right? Since `eval`'s `globals` must be a `dict`, I mixined `ChainMap` with `dict`:

```py
class ChainMap(ChainMap, dict): ...
```

And I define a pair of function like this:

```py
async def f():
    return a  # not defined, but will be provided directly through the gloabls

async def g(context: dict[str, Any]):  # accept a readonly globals namespace
    return await eval(f.__code__, ChainMap({}, context))
```

Apparently, running `g({"a": 123})` should returns `123`. And I wraps this in `runPythonAsync` to get the PyProxy of this function. Then I create another function using the same approach.

<details><summary>complete code (can be directly paste into pyodide demo web console)</summary>
<p>

```ts
pyodide.setDebug(false); // modify this to get a different error message

pyodide.runPython(`
  import collections

  class ChainMap(collections.ChainMap, dict):
      """ to support layered eval context """
`);

async function child(context) {
  const func = await pyodide.runPythonAsync(`

      async def f():
          return a  # shoud be in global

      async def g(context: dict):
          assert isinstance(context, dict)
          return await eval(f.__code__, ChainMap({}, context))

      g
  `);
  return func(pyodide.toPy(context));
}

async function parent(context) {
  const func = await pyodide.runPythonAsync(`

      async def f():
          return await child(locals())

      async def g(context: dict):
          assert isinstance(context, dict)
          return await eval(f.__code__, ChainMap({}, context))

      g
  `);
  return await func(pyodide.toPy(context));
}

const context = { parent, child, a: 123 };

await parent(context) // the result should be `123`, but it raised a strange error
```

</p>
</details>

### To Reproduce

Since the use case is a little bit complicated, a minimal reproduction may still be a little bit long. So I made a dedicated [stackblitz reproduction](https://stackblitz.com/edit/pyodide-issue-demo?file=src%2FMain.svelte), which is a responsive application(when you change the code, the result will update too).

Open the link and you may see a red traceback (the loading process should be fast, normally in 1 minute). But if Ctrl+C kill the process and run:

```sh
pnpm i pyodide@0.26.0 && pnpm dev
```

The result should became a green `123`. This indicates that at least the same code is runnable in pyodide `0.26.0`

### Expected behavior

A green `123` instead of red traceback.

### Environment

- Pyodide Version: `0.26.1`
- Browser version: `Edge 125.0.2535.92`
- Any other relevant information:

### Additional context

Besides using `0.26.0`, I found that simply change all the async function to sync will solve this. (displaying a green 123) I am really confused. Already investing on this for a few days.

**Comment by hoodmane** [comment]
Thanks for the report @CNSeniorious000. Sounds really weird. We should bisect this since there's only a few commits in 0.26.1.

**Comment by CNSeniorious000** [comment]
Good idea. I did the bisect and found that this is introduced in c4afd17ea6098a5b7b3686d233e9343ac65d632a, related to #4837

**Comment by hoodmane** [comment]
Thanks @CNSeniorious000 I'll look into it soon.

**Comment by hoodmane** [comment]
This is quite weird. Changing one line of your reproducer to:
```js
const context = { parent, child, a: 123, __builtins__: pyodide.pyimport("builtins") };
```
fixes it. But I'm not at all sure why, or what is happening here. I've reduced it to:
```js
const func = await pyodide.runPythonAsync(`
  import collections

  class ChainMap(collections.ChainMap, dict):
      pass
  
  def g(child):
      return eval("child()", ChainMap({}, {"child": child}))

  g
`);

await func(async () => {});
```
This should just return `undefined` but instead it raises an error.

**Comment by hoodmane** [comment]
Okay found a fix but it's completely mystifying.
