### ISSUE TITLE
Regression in 0.26.* - exit() crashes pyodide (and generates a different exception)

### ISSUE THREAD

**Issue by thisismypassport** [pyodide/pyodide#4864]
## 🐛 Bug

In 0.26.* - exit() - instead of raising a PythonError of type SystemExit as before - seems to raise a different unexpected ExitStatus object.
Furthermore (and more importantly), pyodide crashes shortly afterwards.
("Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.")

### To Reproduce

You can see the crash by just executing "exit()" in https://pyodide.org/en/stable/console.html

(And if you catch the exception in javascript and console.log it - you will see it's no longer a PythonError as in 0.25.0)

### Expected behavior

exit() should raise a PythonError of type SystemExit, which should not prevent pyodide from running again in the future.

### Environment

- Pyodide Version: 0.26.0 & 1:
- Browser version: Multiple :

**Comment by ryanking13** [comment]
Thanks for the report. This looks like a regression.

**Comment by hoodmane** [comment]
This is due to #4567. I didn't read the documentation for `PyErr_Print` carefully enough:

> Print a standard traceback to sys.stderr and clear the error indicator. Unless the error is a SystemExit, in that case no traceback is printed and the Python process will exit with the error code specified by the SystemExit instance.

https://docs.python.org/3/c-api/exceptions.html#c.PyErr_PrintEx

It seems that the easiest solution is to set the `PyConfig->inspect` flag which opts us out of this behavior:
```C
int
_Py_HandleSystemExit(int *exitcode_p)
{
    int inspect = _Py_GetConfig()->inspect;
    if (inspect) {
        /* Don't exit if -i flag was given. This flag is set to 0
         * when entering interactive mode for inspecting. */
        return 0;
    }
```
https://github.com/python/cpython/blob/v3.12.1/Python/pythonrun.c?plain=1#L687-L695
