### ISSUE TITLE
The JSPI feature in Chrome has undergone changes. Are there any plans for subsequent compatibility updates to address this situation?

### ISSUE THREAD

**Issue by Kol96** [pyodide/pyodide#4883]
## 🚀 Feature

Support for stack switching using the WebAssembly.Suspender API.

### Motivation

The new API(WebAseembly.Suspending) will be live during the remainder of the origin trial — available with Chrome M126.
The previous API(WebAseembly.Suspender) will also be available during the origin trial; however, it is planned to be retired shortly after Chrome M128.

### Additional context

https://v8.dev/blog/jspi-newapi

**Comment by hoodmane** [comment]
Yes I am planning to update Pyodide to use the new API...
