### ISSUE TITLE
`loadPackagesFromImports` in `PyodideConsole.runcode` isn't locked

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4899]
## 🐛 Bug

`Console.runcode` is locked, so it acts like a normal synchronous python console. The only difference `PyodideConsole.runcode` made is calling `loadPackagesFromImports` before running `super().runcode`.

But `loadPackagesFromImports` is not locked, so it may cause confusing behaviors:

### To Reproduce

```py
from pyodide.console import PyodideConsole
c = PyodideConsole()

c.push("import numpy as np")
c.push("np")
```

### Expected behavior

```
<ConsoleFuture pending>
<ConsoleFuture finished exception=NameError("name 'np' is not defined")>
```

### Environment

- Pyodide Version: 0.26.1
- Browser: Edge
- Any other relevant information:

### Additional context

`Console.runcode` is locked:

https://github.com/pyodide/pyodide/blob/9f49030ef511296574885720282887bea6c6fd54/src/py/pyodide/console.py#L384-L394

While `PyodideConsole.runcode` is not:

https://github.com/pyodide/pyodide/blob/9f49030ef511296574885720282887bea6c6fd54/src/py/pyodide/console.py#L492-L507

**Comment by ryanking13** [comment]
Thanks for the report @CNSeniorious000! I guess then we should lock the total block including `loadPackgesFromImports`?

I think splitting `Console.runcode` such as:

```py
class Console:
  def runcode(...):
      with self._acquire_lock():
          self._run_code()
```

then changing `PyodideConsole.runcode` accordingly:

```py
class PyodideConsole(Console):
  def runcode(...):
    with self._acquire_lock():
        await loadPackagesFromImports()
        super()._runcode()
```

would do the job.

**Comment by CNSeniorious000** [comment]
Yeah this is a good approach. But I was thinking that, since `run_code` is a standalone method, and usually the whole method is locked, why not implement a `_run_code` (or `run_code_inner` I am not sure about the naming) that is just returns `run_code` with a lock? Like this:

```
class Console:
    async def run_code(...):
        ...  ＃ don't use the lock
    async def _run_code(...):
        async with self._lock:
            return await self.run_code(...)
    def run_source(...):
        ...
        return ensure_future(self._run_code(...))

class PyodideConsole(Console):
    async def run_code(...):
        ...  ＃ don't need to change
```

That is, lock behavior is moved into a `_run_code` method, instead of inside `run_code`. This way will make `Console` easier to be derived.

---

Another approach I was thinking is that

**Comment by ryanking13** [comment]
> That is, lock behavior is moved into a _runcode method, instead of inside runcode. This way will make Console easier to inherit.

Sounds good to me. It would be nice if the naming of `_runcode` was a bit more explicit, so that it's clear from the name that it holds a lock.

> Then use it to decorate any method needs to be locked. Like runcode.

For now, we don't have other places that use the lock, so I think we are okay with the current approach. I think `with lock:` is very straightforward, and adopting a decorator doesn't make it more clearer.
