### ISSUE TITLE
pypdf: PDF library

### ISSUE THREAD

**Issue by JohannesMaierhofer** [pyodide/pyodide#4900]
## 🐍 Package Request

**Package Name and Version:** pypdf
**Package URL:** https://github.com/py-pdf/pypdf
**Package Dependencies that need to be resolved first:** None that I am aware of

This package is widely used for manipulating and processing PDF files and is a dependency in many PDF-related projects.

**Comment by ryanking13** [comment]
pypdf is a pure Python package, so you can install it with `micropip.install("pypdf")`. Closing as resolved, but don't hesitate to comment more if you have any issues.
