### ISSUE TITLE
`<console>` is hard-coded, causing traceback disappear when filename specified

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4901]
## 🐛 Bug

Traceback unexpectedly truncated:

[![stackblitz screenshot](https://github.com/pyodide/pyodide/assets/74518716/9d248e83-bef9-4d12-be45-70dffb594de7)](https://stackblitz.com/edit/pyodide-issue-demo-4jndzt?file=src%2Fmain.py)

### To Reproduce

[stackblitz interactive reproduction](https://stackblitz.com/edit/pyodide-issue-demo-4jndzt?file=src%2Fmain.py)

<details><summary><code>main.py</code> (runnable in pyodide repl too)</summary>
<p>

```py
from contextlib import suppress

from pyodide.console import Console

c = Console()  # default filename is `<console>`

future = c.push("assert False")

with suppress(Exception):
    await future

right_traceback = future.formatted_error

c = Console(filename="whatever_else")

future = c.push("assert False")

with suppress(Exception):
    await future

wrong_traceback = future.formatted_error

[
    right_traceback,
    wrong_traceback,
]

```

</p>
</details>

### Environment

- Pyodide Version: 0.26.1
- Browser version: Edge
- Any other relevant information:

### Additional context

https://github.com/pyodide/pyodide/blob/9f49030ef511296574885720282887bea6c6fd54/src/py/pyodide/console.py#L406-L417

`<console>` hard-coded here

**Comment by CNSeniorious000** [comment]
About why I need to set the `filename` parameter, it's because I want the related source to be printed in the traceback.

The problem is, `linecache` have a weird behavior:

It treats special filenams as non-files:

https://github.com/python/cpython/blob/e6543daf12051e9c660a5c0437683e8d2706a3c7/Lib/linecache.py#L95-L96

But here, it treats special filenames as non-lazycachable:

https://github.com/python/cpython/blob/e6543daf12051e9c660a5c0437683e8d2706a3c7/Lib/linecache.py#L174-L175

So filenames like `<exec>` and `<console>` can never have native tracebacks. This is upsetting. We can only set it to another value to have a useful traceback.

**Comment by ryanking13** [comment]
Thanks for the report and proposal, @CNSeniorious000! I am +1 for enhancing the Console module as you suggest. The reason we have a console module is to implement [a simple browser console](https://pyodide.org/en/stable/console.html), so we're not dealing with a lot of complex use cases. So I agree with most of the improvements, as long as it doesn't make the console too complicated.

**Comment by CNSeniorious000** [comment]
I see. I understand pyodide's console implementation should just be like python's default CLI console. So if I add the linecache patch and tempfile logic to it, it will make it not that native. (For example, in python cli, the line number is reset every eval and there is no source lines in the traceback). There is no need to vendor an ipython into pyodide.console
