### ISSUE TITLE
pymupdf: A high performance Python library

### ISSUE THREAD

**Issue by JohannesMaierhofer** [pyodide/pyodide#4903]
🐍 Package Request

Package Name and Version: pymupdf
Package URL: https://github.com/pymupdf/PyMuPDF
Package Dependencies that need to be resolved first: None that I am aware of

This package is widely used for manipulating and processing PDF files and is a dependency in many PDF-related projects.

**Comment by ryanking13** [comment]
There is a duplicate issue (#4903), so I'll close this one.
