### ISSUE TITLE
Is it possible to bypass the version check?

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4906]
## 🚀 Feature

Can we provide a `ignoreVersionCheck` option to bypass this?

https://github.com/pyodide/pyodide/blob/cf41eafe1665ecc4e0682ab43aa271a32b719127/src/js/pyodide.ts#L260-L267

### Motivation

I am making a stackblitz reproduction template for #4895, if I can bootstrap another version of pyodide with the same version of pyodide(npm), it could be easier.

In another way, there are use cases that we need to have a preview of nightly build of pyodide-core, which don't have a compatible npm package. So I think we can provide a way to manually ignore the version check here.

Using options field is an approach. I think using environment variables is reasonable too.

### Pitch

If `ignoreVersionCheck === true`, don't throw this error, and `console.warn` it perhaps.

### Alternatives

If `env.IGNORE_VERSION_CHECK`, don't throw this error, and `console.warn` it perhaps.

### Additional context

I think this check is because different version of pyodide may have different bootstrap patterns. So using a wrong pyodide npm package to bootstrap another version of pyodide core will have unexpected behaviors. But since we don't have a nightly release for every commit, this proposal may be an easiest approach.

**Comment by hoodmane** [comment]
Sure, pr welcome.
