### ISSUE TITLE
`stack-data`'s dependency map is wrong

### ISSUE THREAD

**Issue by CNSeniorious000** [pyodide/pyodide#4909]
## 🐛 Bug

`stack-data` is directly dependent on `pure-eval`, `executing` and `asttokens`. But the `requirements` field in [`meta.yaml`](https://github.com/pyodide/pyodide/blob/5fb36a458be37270efecdc9638202a13b62d28f8/packages/stack_data/meta.yaml) is empty.

### To Reproduce

```py
import stack_data
```

### Expected behavior

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
    import stack_data
  File "/lib/python3.12/site-packages/stack_data/__init__.py", line 1, in <module>
    from .core import Source, FrameInfo, markers_from_ranges, Options, LINE_GAP, Line, Variable, RangeInLine, \
  File "/lib/python3.12/site-packages/stack_data/core.py", line 15, in <module>
    import executing
ModuleNotFoundError: No module named 'executing'
```

### Environment

- Pyodide Version: 0.26.1
- Browser version: Microsoft Edge 126.0.2592.81
- Any other relevant information:

**Comment by ryanking13** [comment]
Thanks for finding this out! I believe we do some basic import tests for all packages, so it's strange that this was not catched in CI.

**Comment by hoodmane** [comment]
Well it doesn't have a test/imports section:
```yaml
test:
  imports:
    - stack_data
```

**Comment by CNSeniorious000** [comment]
Only 33/267 packages has `test/imports` key. Why don't just test every `package/top-level` keys? Or `test/imports` can defaults to `package/top-level`?

**Comment by hoodmane** [comment]
Sounds pretty reasonable.

**Comment by CNSeniorious000** [comment]
https://github.com/pyodide/pyodide/blob/9428c6f69e997c59a094538c7638d3e8ebb66284/packages/_tests/test_packages_common.py#L89-L97

It seems we already have this logic 🤔

**Comment by ryanking13** [comment]
It's because the name of the `stack-data` package is misconfigured in meta.yaml file. It should be `stack-data` not `stack_data`, which made our test bypass that package. There seem to be other packages that have the same issue as well, like `smart_open` and `python_solvespace`. I guess we need some test for it.
