### ISSUE TITLE
Add a `--force` option to the `pyodide skeleton pypi` CLI to allow updating recipes for packages with patches

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide#4927]
## 🚀 Feature

This issue proposes adding a `--force` command-line argument to the `pyodide skeleton pypi` command-line interface to enable recipe maintainers to update packages at their own risk, even if they contain patches or other restrictive behaviour. Of course, the option will be disabled by default, but users wanting to use it can opt for it.

### Motivation

Manually updating the packages with `patches:` in their recipe is (slightly) cumbersome, and the command-line interface provides users with benefits that can be extracted here for all packages regardless of whether they contain patches for now.

### Pitch

1. Update the logic in `pyodide-build/pyodide_build/mkpkg.py`, more specifically, `mkpkg.update_package()`, and
2. Update the Typer CLI in `pyodide-build/pyodide_build/skeleton.py` to incorporate a new argument

### Additional context

This came up while I was updating many packages locally that contain patches and is thus just a personal pain point for now. I'm happy to receive opinions from others about the usability of this feature – from a programming perspective, it won't take much work to add! If others agree, I can assign myself to this.

**Comment by hoodmane** [comment]
I'm pretty sure we already have this?

**Comment by agriyakhetarpal** [comment]
I think we do, indeed. I just noticed it's called `--update-patched`, which I didn't find in the documentation, but `--help` had it. Sorry for the noise, @hoodmane!

**Comment by hoodmane** [comment]
No worries. Perfectly reasonable question/request, feel free to open as many issues like this as you like
