### ISSUE TITLE
pandas data frame causes scroll bar in the rep

### ISSUE THREAD

**Issue by hamilton** [pyodide/pyodide#493]
I'm not sure if this is Pyodide or Iodide error, but I noticed that using `df.head()` does not cause scroll bars to pop up in the rep container, while `df` does.

```
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
```

Plain old `df` looks like

![Screen Shot 2019-07-26 at 1 37 58 PM](https://user-images.githubusercontent.com/95735/61980183-cff8c900-afaa-11e9-8d7d-3538782ffc3e.png)

Would be happy to move this to the Iodide repo but figured I'd flag it here first just in case.

**Comment by rth** [comment]
Closing as since we removed the Iodide specific code from Pyodide, this rendering issue would likely have to be fixed on the Iodide side.
