### ISSUE TITLE
Contents of Release Files could be explained

### ISSUE THREAD

**Issue by Hephaistos7** [pyodide/pyodide#4942]
## 📚 Documentation

So I downloaded the latest release:  _pyodide-0.26.1.tar.bz2_ . But this Issue is relevant for all releases.

Inside of a release, I expect to find all the necessary files for running Pyodide, and all the wheels to run libraries like NumPy, Matplotlib and many more.

What I don't understand is:
- why are there html-files, like _test.html_ or _console.html_?
- why do some wheels have tests.tar-files, like _gsw-tests.tar_?
- why are some packages zipped, like _hashlib-1.0.0.zip_?
- why is there a font folder?
- why are there JS-files like _webworker.js_, that are more meant for testing than really using Pyodide?
- why is there a _package.json_, as this is not a npm-Package?
- and what do the .metadata files do?

I don't understand what most of these do and why they need to be in a release.

**My use case**:
So, I use Pyodide in my project and recently switched from loading from the CDN to including the release in my project. This allows me to build an offline-version that doesn't need to load e.g. NumPy from the internet.
In using  _pyodide-0.26.1.tar.bz2_ for this purpose, I feel like I include a lot of clutter into my project. So I manually have to delete all the files that don't do anything for my project.

Should there maybe be a release that does not include any test-files?

Greetings,
Jeff

PS: absolutely love the project!

**Comment by hoodmane** [comment]
Would indeed make sense to explain the files. Have you looked at [pyodide-core-0.26.1.tar.bz2](https://github.com/pyodide/pyodide/releases/download/0.26.1/pyodide-core-0.26.1.tar.bz2)?

**Comment by Hephaistos7** [comment]
So here is an overview of my understanding:

 **pyodide-core-0.26.1.tar.bz2** contains the following files:
 - pyodide.asm.js
 - pyodide.asm.wasm
 - pyodide.js
 - pyodide.mjs
 - python_stdlib.zip
 - package.json
 - pyodide-lock.json
 
pyodide-0.26.1.tar.bz2 contains these file tpyes on top of that:
- fonts folder
- snapshot.bin
- python file
- 3 html-files
- module_webworker_dev.js
- webworker.js
- webworker_dev.js
- makesnap.mjs
- pyodide.js.map
- pyodide.mjs.map
- 227 metadata files of python wheels
- 63 *-tests.tar files of various python packages
- ffi.d.ts
- pyodide.d.ts
- 227 python wheels for wasm
- 18 zip archives

**Comment by hoodmane** [comment]
@Hephaistos7 Yeah I would say everything in your summary is right except for `pyodide-lock.json`. I agree we could reasoanbly include the `.d.ts` files in the core release and drop some others entirely. We don't have a good way to distinguish between "tools used for testing" and "artifacts intended for distribution" in our current build system.

**Comment by Hephaistos7** [comment]
That is lovely! I'll edit my list to match yours.
And hopefully when this is done, it can be included somewhere in the documentation :) That would be work well done and time well spent in my opinion

**Comment by hoodmane** [comment]
@Hephaistos7 would you mind opening a PR adding this information? Perhaps here would be a good place:
https://pyodide.org/en/stable/usage/downloading-and-deploying.html#github-releases

**Comment by Hephaistos7** [comment]
@hoodmane I will

**Comment by Hephaistos7** [comment]
I created a PR #4946 
Considering the upcoming changes to the contents of the release, we should consider adapting the documentation.
Probably worth to keep file explanations to the documentation of the correct pyodide version, e.g. Pyodide 0.23 might contain different files than 0.26. It looks like 0.27 might come with less files in the release as well.

I'd be willing to adapt this if you like the documentation. Just give me feedback if you please.

**Comment by hoodmane** [comment]
Resolved by #4945.
