### ISSUE TITLE
The REPL is down

### ISSUE THREAD

**Issue by kc97ble** [pyodide/pyodide#4964]
## 🐛 Bug

The REPL is down.

### To Reproduce

Visit https://pyodide.org/en/stable/console.html
<img width="714" alt="image" src="https://github.com/user-attachments/assets/9610816c-f57e-4138-a07c-0726a06b8411">

### Expected behavior

The website is up (just like yesterday).

### Environment

N/A

### Additional context

The issue is likely due to error 404 when fetching this URL: https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.mjs

-----

_PS: Thank you so much for the project. An online REPL is so convenient to teach Python to newbies._

**Comment by hoodmane** [comment]
It looks like the problem is that the new test
```
packages/duckdb/test_duckdb.py::test_duckdb_with_pandas[firefox]
```
timed out, preventing the deploy from finishing:
https://app.circleci.com/pipelines/github/pyodide/pyodide/7578/workflows/403d102b-8063-48c2-a32c-bcede2efee93/jobs/108413

We haven't ever made the deploy quite correct -- ideally, all deployment steps should be triggered by the circleci `deploy-release` job, but some of the steps are done by github actions and so if there is a test failure then the circleci deploy is blocked but the github actions deploy steps are not and you get problems like this.

cc @ryanking13 @agriyakhetarpal

**Comment by hoodmane** [comment]
Thanks for the report @kc97ble!

**Comment by agriyakhetarpal** [comment]
> We haven't ever made the deploy quite correct -- ideally, all deployment steps should be triggered by the circleci deploy-release job, but some of the steps are done by github actions and so if there is a test failure then the circleci deploy is blocked but the github actions deploy steps are not and you get problems like this.

Thanks for the ping, @hoodmane! As far as I know, there wouldn't be a reliable way to communicate the success/failure of workflow runs between two different CI providers. I know of a way to do it: redirecting artifacts between them, but it will need to be neat enough.

**Comment by hoodmane** [comment]
I think it should be possible by making the gha job be a `workflow_dispatch` job, and then dispatching to it from circleci.

**Comment by hoodmane** [comment]
Anyways on the third try, `duckdb_with_pandas[firefox]` passed so soon we should get a correct deploy.

**Comment by agriyakhetarpal** [comment]
That works as well. We might need a PAT to be set up with the appropriate permissions so that the CircleCI job can trigger it.

**Comment by hoodmane** [comment]
I think @ryanking13 and I discussed this before but were too lazy to actually do it...

**Comment by agriyakhetarpal** [comment]
Sure – I can take a look at this soon enough and ping you both as necessary :) If I have a solution, I'll put together a PR.

**Comment by hoodmane** [comment]
Okay, now the release is complete and the repl is working again. Thanks again for the report @kc97ble.

**Comment by ryanking13** [comment]
I think we need to update the dependency graph for the deploy job too. It is strange that the test job is the dependency of a release. I think it should deploy after the build, regardless of whether the tests succeed or fail.

**Comment by hoodmane** [comment]
Well I have at least once tried to deploy something that was actually broken. But I guess if you deploy a broken 0.26.2 you can ditch that tag and immediately release 0.26.3. But I think running tests before releasing is a reasonable and common practice?

**Comment by ryanking13** [comment]
> But I think running tests before releasing is a reasonable and common practice?

Right, but I think we need to rethink the scope of the tests we need to cover. Is it just the core test suite or all package tests? We'll probably need to revisit this later after we unvender packages.

**Comment by hoodmane** [comment]
Makes sense. I would be fine with just waiting for core tests.
