### ISSUE TITLE
Store at least status code in HttpStatusError ? 

### ISSUE THREAD

**Issue by Carreau** [pyodide/pyodide#4973]
## 🚀 Feature

Since #4846, HttpError are their own Exceptions (before it was a blank OSError). It would be nice to also store the status code in the exception, or as requests does it the full corresponding response.

### Motivation

In micropip, id like to raise_for_status deep in high level code, and if possible catch 404 on higher level, but not other error. Like not a 500 or a 403. This currently requires parsing the HttpError message.

### Pitch

```diff
class HttpStatusError(OSError):
    def __init__(self, status: int, status_text: str, url: str) -> None:
+       self.status = status
+       self.status_text = status_text
+       self.url = urls
        if 400 <= status < 500:
            super().__init__(f"{status} Client Error: {status_text} for url: {url}")
        elif 500 <= status < 600:
            super().__init__(f"{status} Server Error: {status_text} for url: {url}")
```

### Alternatives

Requests also store the full request:

```diff
class HttpStatusError(OSError):
    def __init__(self, status: int, status_text: str, url: str, *, req=None) -> None:
+       self.req = req
        if 400 <= status < 500:
            super().__init__(f"{status} Client Error: {status_text} for url: {url}")
        elif 500 <= status < 600:
            super().__init__(f"{status} Server Error: {status_text} for url: {url}")
```

Or, have a custom class:

```
class NotFoundError(HttpStatusError):
   ...
```

And a factory that returns the right exception, but that seem painful to code and use.

**Comment by Carreau** [comment]
Note that at the same time HttpStatusError does not call __init__ of OSError if the status code is not between 400 and 599... I looks like it should unconditionally call `super().__init__` even if not passing parameters, or `assert False` if None of the branches are followed.

**Comment by hoodmane** [comment]
Patch looks sensible to me. PR welcome.

**Comment by Carreau** [comment]
Thanks !
