### ISSUE TITLE
how to fix CORS when loading local wheel file

### ISSUE THREAD

**Issue by pplmx** [pyodide/pyodide#4977]
Hi, 

I want to load `local whl` at the same directory of the html file, but it throws CORS, how to fix it?

```js
await micropip.install("./my_wasm-0.0.1-py3-none-any.whl");
```

```txt
ValueError: Can't fetch wheel from './my_wasm-0.0.1-py3-none-any.whl'. One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS). Check if the server is sending the correct 'Access-Control-Allow-Origin' header.

```

_Originally posted by @pplmx in https://github.com/pyodide/pyodide/discussions/4344#discussioncomment-10199086_

**Comment by ryanking13** [comment]
How did you serve the wheel? Note that the browser cannot access the local filesystem, the way the browser access the local file is,

1. Run a server that serves files.
2. Access those files through the server.

If you are doing that, you will be able to update the server to send CORS headers. For instance: https://stackoverflow.com/questions/21956683/enable-access-control-on-simple-http-server

**Comment by pplmx** [comment]
> Note that the browser cannot access the local filesystem

Ok, thanks, I got it.
