### ISSUE TITLE
import module after loadPackage

### ISSUE THREAD

**Issue by alexandrupaler** [pyodide/pyodide#500]
I am using `pyodide.loadPackage('https://github.com/quantumresource/zxQentiana/blob/master/githubiofiles/pyqentiana.js')`. It loads and works. 

Afterwards, `from pyqentiana.cube_to_physical import Qentiana` says
> ModuleNotFoundError: No module named 'pyqentiana'

PS: In order to get loadPimport numpy as npackage working I had to first 
`%% py`
`import numpy as np`

**Comment by alexandrupaler** [comment]
I solved this issue by

1. Before calling loadPackage I manually inserted the dependencies  with `pyodide._module.packages.dependencies["pyqentiana"] = []`
2. Used [this stackoverflow answer ](https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github)to load raw JS from github
3. called loadPackage

**Comment by matham** [comment]
I'd like to do something like that for sharing some packages to test before making a PR here so was interested in something like that. However, when compiling a python package it creates a `package.js` and `package.data`. How did you load the `package.data`?

**Comment by alexandrupaler** [comment]
The package.data gets loaded from the package.js. You need to load the JS, and that takes care of the data.

**Comment by matham** [comment]
I still can't seem to be able to load a package from e.g. github. I think I followed your instructions exactly, but it's not being imported. I tried to do it with your example package, can you take a look and let me know if this is what you did:

```
%% fetch
js: https://pyodide.cdn.iodide.io/pyodide.js
%%js
pyodide._module.packages.dependencies["pyqentiana"] = []
pyodide.loadPackage('https://cdn.jsdelivr.net/gh/quantumresource/zxQentiana/githubiofiles/pyqentiana.js')
%%py
import pyqentiana
```
And I run it on https://alpha.iodide.io/notebooks/300/. But it actually fails. In the log it says `Loading failed for the <script> with source “https://cdn.jsdelivr.net/gh/quantumresource/zxQentiana/githubiofiles/pyqentiana.js”.`.

Am I misunderstanding something?

**Comment by alexandrupaler** [comment]
I created the following notebook as an example where I am loading my pyodide modules from external https://alpha.iodide.io/notebooks/2880/

**Comment by matham** [comment]
Thank you. 

After trying it and it didn't initially work, I realized my ad-blocker was blocking requests to github. So now it's working.

**Comment by kevinlu1248** [comment]
I'm facing a similar issue of running 

`
import micropip
await micropip.install('./wheels/pyahocorasick-1.4.2-cp38-cp38-linux_x86_64.whl')
import ahocorasick
`

where "/wheels/pyahocorasick-1.4.2-cp38-cp38-linux_x86_64.whl" is a manually compiled wheel of `pyahocorasick` using `pip wheel`, but I'm getting `ModuleNotFoundError`. Any ideas on fixing this?

**Comment by hoodmane** [comment]
This issue is out of date @kevinlu1248 so I am closing it and moving your question over to #1683.
