### ISSUE TITLE
Update the scikit-learn version from 1.4.2 to latest (i.e. 1.5.1)

### ISSUE THREAD

**Issue by ogrisel** [pyodide/pyodide#5014]
## 🐍 Package Upgrade Request

- scikit-learn 1.5.1 (latest at the time of writing).
- https://pypi.org/project/scikit-learn/

scikit-learn 1.4.2 is already part of pyiodide. I don't think the dependencies have changed.

**Comment by agriyakhetarpal** [comment]
Hi, thanks for opening this issue, @ogrisel! I had upgraded `scikit-learn` to version 1.5.1 in #4925, but that PR isn't going in any time soon, so a separate PR to upgrade `scikit-learn` would be welcome.
