### ISSUE TITLE
"Python config failure: Python is 64-bit, chosen compiler is 32-bit" when using pybind11 2.13

### ISSUE THREAD

**Issue by hzhangxyz** [pyodide/pyodide#5054]
## 🐛 Bug

I am using pyodide - scikit-build-core - pybind11 to compile my package, but when pybind11 updated to 2.13, error occur (It works fine in pybind11 2.12)

### To Reproduce

With the following three files, following the guide at https://pyodide.org/en/stable/development/building-and-testing-packages.html , we can successfully build the example module, however, compiling fail if we update pybind11 from 2.12.0 to 2.13.0.

pyproject.toml
```
[build-system]
requires = ["scikit-build-core==0.10.5", "ninja==1.11.1.1", "pybind11==2.12.0"]
build-backend = "scikit_build_core.build"

[project]
name = "PyTAT"
version = "0.0.1"

[tool.scikit-build]
experimental = true
cmake.verbose = true
sdist.exclude = ["*"]
sdist.include = [
  "/CMakeLists.txt",
  "/pyproject.toml",
  "/main.cpp",
]
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.8)
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.14" CACHE STRING "Minimum OS X deployment version")
project(PyTAT LANGUAGES CXX)

find_package(pybind11 REQUIRED)
pybind11_add_module(PyTAT main.cpp)
```

main.cpp
```
#include <pybind11/pybind11.h>

int add(int i, int j) {
    return i + j;
}

PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; // optional module docstring

    m.def("add", &add, "A function that adds two numbers");
}
```

### Expected behavior

Successfully compiling

### Environment

- Pyodide Version: 0.26.2
- Python Version: 3.12.5

**Comment by agriyakhetarpal** [comment]
Hi, @hzhangxyz! We had noticed the same problem with `iminuit` recently (see #4767). Could you try setting `PYBIND11_FINDPYTHON` `ON` before `pybind11_add_module()` in your `CMakeLists.txt` file and see if that works?

**Comment by agriyakhetarpal** [comment]
It's strange that it works with 2.12, though, and fails with 2.13. cc: @henryiii who would know better about Emscripten support for `pybind11`.

**Comment by hzhangxyz** [comment]
> Hi, @hzhangxyz! We had noticed the same problem with `iminuit` recently (see #4767). Could you try setting `PYBIND11_FINDPYTHON` `ON` before `pybind11_add_module()` in your `CMakeLists.txt` file and see if that works?

@agriyakhetarpal Hello, I do not know why but after adding `set(PYBIND11_FINDPYTHON ON)`, the package compiled successfully. Thanks.
