### ISSUE TITLE
How to read/write files to local file system in pyodide

### ISSUE THREAD

**Issue by YalinLi0312** [pyodide/pyodide#5071]
### Discussed in https://github.com/pyodide/pyodide/discussions/5070

<div type='discussions-op-text'>

<sup>Originally posted by **YalinLi0312** September 11, 2024</sup>
I'm following this sample to mount a file system in Node.js, but the changes can't be found in local file system. 
```
let mountDir = "/mnt";
pyodide.FS.mkdirTree(mountDir);
pyodide.FS.mount(pyodide.FS.filesystems.NODEFS, { root: "." }, mountDir);
pyodide.runPython("import os; print(os.listdir('/mnt'))");
// ==> The list of files in the Node working directory
```
Is it possible to persist file changes to local file system?</div>

**Comment by ryanking13** [comment]
Yes you can and your sample code should work.

```js
import { loadPyodide } from "pyodide";

const pyodide = await loadPyodide();
let mountDir = "/mnt";
pyodide.FS.mkdirTree(mountDir);
pyodide.FS.mount(pyodide.FS.filesystems.NODEFS, { root: "." }, mountDir);
pyodide.runPython(`
    import os
    import pathlib
    pathlib.Path("/mnt/test.txt").touch()
    print(os.listdir('/mnt'))
`);
```

This code works will persist the `test.txt` in the local file system.

**Comment by YalinLi0312** [comment]
Thanks @ryanking13 , the sample code works! 
Another question: instead of persisting on file level, is it possible to persist changes under a folder?

**Comment by ryanking13** [comment]
> Another question: instead of persisting on file level, is it possible to persist changes under a folder?

Yes. As you are mounting the local file system, anything happens in that mounted directory will persist.

**Comment by YalinLi0312** [comment]
@ryanking13 thanks for your support, it works now.
