### ISSUE TITLE
`pyodide.code.find_imports` suboptimal for submodule packages

### ISSUE THREAD

**Issue by juntyr** [pyodide/pyodide#5075]
## 🐛 Bug

`pyodide.code.find_imports("import earthkit.maps")` will return `["earthkit"]`, the correct output in general. However, the earthkit package family consists of several packages where e.g. `earthkit-maps` provides the `earthkit.maps` module (there is also a top-level package that re-exports all child packages under the expected submodules).

In my custom Pyodide build that includes the `earthkit` packages, `earthkit-map`'s `meta.yaml` file declares

```yaml
top-level:
    - earthkit.maps
```

i.e. Pyodide knows that this package provides this specific import.

Would it be possible for `pyodide.code.find_imports` to consult the index of pre-built packages, and if one provides a submodule, only import this package instead of the top-level one (which then imports all child packages even when only one is needed)?

### To Reproduce

Go to https://lab.climet.eu/lab/index.html, create a new notebook, and use
```python
# cell 1
import pyodide
print(pyodide.code.find_imports("import earthkit.maps"))

# cell 2
# The install works correct in only installing what is needed
%pip install earthkit.maps

# cell 3
# The import, for which JupyterLite consults pyodide.code.find_imports, now triggers extra installs
import earthkit.maps
```

### Environment

- Pyodide Version: a [patched](https://github.com/climet-eu/lab/blob/main/patches/pyodide.patch) version of https://github.com/pyodide/pyodide/tree/6621b6bca72ed2cc4e9e66ed24783cce0e8dd907

**Comment by ryanking13** [comment]
Thanks for the report @juntyr. The behavior of `find_imports` has been changed in https://github.com/pyodide/pyodide/pull/5039, and it will now return all child import paths.

```
>>> pyodide.code.find_imports("import earthkit.maps")
['earthkit', 'earthkit.maps']
```

> Would it be possible for pyodide.code.find_imports to consult the index of pre-built packages, and if one provides a submodule, only import this package instead of the top-level one (which then imports all child packages even when only one is needed)?

`pyodide.loadPackagesFromImports`(https://github.com/pyodide/pyodide/blob/5a2a0c7d3e7aeee6855abe81f54d6ef6677f4862/src/js/api.ts#L205-L237) works in that way.

**Comment by juntyr** [comment]
Thanks for your reply! 

> ```
> >>> pyodide.code.find_imports("import earthkit.maps")
> ['earthkit', 'earthkit.maps']
> ```

If this is the new result, wouldn't it still load both the top-level package (which also loads all child-packages), and now newly also explicitly the requested child package?

From what I understand, `import a.b` does not imply `import a`, and so importing `earthkit`, while not wrong per se, is overkill in this case.

What I was imagining is that when an `import a.b.c` occurs, it would first check if `a.b.c` is in `API._import_name_to_package_name` and if so only return `a.b.c` as a needed import, if not try for `a.b`, and finally if that isn't in `API._import_name_to_package_name` then try to import `a`. That way, a package proving the import `a.b` specifically would not require loading `a`, but a package where only `a` is provided would still import `a` for `a.b` as before.

I think this would need to happen within `pyodide.code.find_imports` since `loadPackagesFromImports` just tries to import all items that `find_import` provides.

**Comment by ryanking13** [comment]
Hmm, yeah, I agree that it is not optimal for namespace packages. It would be nice to have a better way to handle that, but I don't want to introduce a too complex way to fix that. `pyodide.code.find_imports`, and `loadPackagesFromImports` were introduced to make it easier for people to use the Python console without having to manually install packages in the early period of Pyodide, but I think it's better for people to manage their own package installations.

> I think this would need to happen within pyodide.code.find_imports since loadPackagesFromImports just tries to import all items that find_import provides.

That might work, but I want to leave `find_imports` a pure function that does not rely on the lock file.

**Comment by juntyr** [comment]
> That might work, but I want to leave `find_imports` a pure function that does not rely on the lock file.

I think doing it later wouldn't work since `loadPackagesFromImports` cannot distinguish between `import a` having been explicitly requested by the code writer or being a byproduct of `import a.b`. One way around would be a literal-only mode for `pyodide.code.find_imports` that only returns the import paths as specified, which could then be compared to the normal results to find which imports should only be used as fallbacks.

**Comment by ryanking13** [comment]
What I was thinking of exposing the content of the lock file to users so users can write a custom (and better) version of find_imports or loadPackagesFromImports.

**Comment by juntyr** [comment]
> What I was thinking of exposing the content of the lock file to users so users can write a custom (and better) version of find_imports or loadPackagesFromImports.

That would work as well :)

**Comment by ryanking13** [comment]
#5412 is merged and you will be able to access the lockflie object by `pyodide.lockfile` in the next release.

**Comment by juntyr** [comment]
> [#5412](https://github.com/pyodide/pyodide/pull/5412) is merged and you will be able to access the lockflie object by `pyodide.lockfile` in the next release.

Thanks @ryanking13! Could `API._import_name_to_package_name` also be exposed, or should I just recompute it using `lockfile`?

**Comment by ryanking13** [comment]
> Thanks @ryanking13! Could API._import_name_to_package_name also be exposed, or should I just recompute it using lockfile?

For now, I think you can recompute it from the lockfile.
