### ISSUE TITLE
File changes event listener like `FS.trackingDelegate`

### ISSUE THREAD

**Issue by whitphx** [pyodide/pyodide#5076]
## 🚀 Feature

JS event listener/callback to detect the changes on the Emscripten virtual file system.
For that purpose, [`FS.trackingDelegate`](https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.trackingDelegate%5Bcallback%20name%5D) should be available though `pyodide.FS`, but it is not as of 0.26.2.

```
> pyodide.FS.trackingDelegate
undefined
> pyodide.FS.trackingDelegate['onWriteToFile'] = function(path, bytesWritten) {
...     console.log('Wrote to file "' + path + '" with ' + bytesWritten + ' bytes written');
... };
Uncaught TypeError: Cannot set properties of undefined (setting 'onWriteToFile')
> pyodide.version
'0.26.2'
```

Providing `pyodide.FS.trackingDelegate` is straightforward, and if it's not possible for some reason, it's also helpful to provide any alternative way to do the likes.

### Motivation

I want to make it possible for the JS code to detect the file changes on the file system done by the Python code so that the JS code can read the files reacting to the changes.

**Comment by hoodmane** [comment]
This apparently requires `-sFS_DEBUG` and it sounds like enabling it may have performance implications even if it's not used.

**Comment by hoodmane** [comment]
This apparently requires `-sFS_DEBUG` and it sounds like enabling it may have performance implications even if it's not used.

**Comment by hoodmane** [comment]
But maybe the only implications are code size.

**Comment by hoodmane** [comment]
This apparently requires `-sFS_DEBUG` and it sounds like enabling it may have performance implications even if it's not used.

**Comment by hoodmane** [comment]
But maybe the only implications are code size.

**Comment by hoodmane** [comment]
But maybe the only implications are code size.

**Comment by ryanking13** [comment]
Yeah, it seems `-sFS_DEBUG` only adds some `if` blocks inside the `library_fs.js`, so it might not affect performance or the file size very much.

**Comment by hoodmane** [comment]
I guess we should try enabling it and seeing if there's a measurable regression on filesystem benchmarks, if not then why not include it.
