### ISSUE TITLE
Wrong conversion from np.int64 to JavaScript

### ISSUE THREAD

**Issue by luiscastro193** [pyodide/pyodide#5084]
## 🐛 Bug

Calling toJs on a PyProxy with np.int64 returns weird results.

### To Reproduce

import numpy as np
from pyodide.ffi import to_js
to_js(np.int64(1))

### Expected behavior

np.int64(1) is converted to 1

### Environment

- Pyodide Version: Pyodide 0.26.2 and Pyodide dev (from https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js)
- Browser version: Latest Firefox and latest Chrome
- Any other relevant information:

**Comment by luiscastro193** [comment]
By the way, it would be nice if pd.NA converted to NaN as it happens with np.nan

**Comment by luiscastro193** [comment]
As a workaround, I am using Pandas's to_json (which actually treats all missing values as null)

**Comment by hoodmane** [comment]
Thanks for the report. Another related bug is the following:
```js
await pyodide.loadPackage("numpy");
pyodide.runPython(`
import numpy as np
from pyodide.ffi import to_js
to_js(np.array([1,2,3], dtype=np.int64))
`);
```
which raises:
```py
SystemError: <built-in function to_js> returned NULL without setting an exception
```
