### ISSUE TITLE
Running under wasmer: Error while importing "env"."capture_stderr": unknown import.

### ISSUE THREAD

**Issue by Spitfire1900** [pyodide/pyodide#5090]
## 🐛 Bug
When running pyodide under wasmer I get the error `Error while importing "env"."capture_stderr": unknown import.`

### To Reproduce

Download wasmer 4.3.0-beta.1
Download pyodide-0.26.2.tar.bz2

Run `wasmer pyodide.asm.wasm`

### Expected behavior

Python REPL appears

### Environment

- Pyodide Version: 0.26.2
- Wasmer version: 4.3.0-beta.1
- OS version: Ubuntu 22.04.5 LTS
- Architecture: x64

### Additional context

[stdout.txt](https://github.com/user-attachments/files/17171808/stdout.txt)

**Comment by ryanking13** [comment]
You can't run Pyodide in Wasmer because Pyodide relies highly on Emscripten and the browser environment.
