### ISSUE TITLE
IPython magic syntax

### ISSUE THREAD

**Issue by mdboom** [pyodide/pyodide#51]
I'm not 100% sold we *want* to make this work, but we should at least have a placeholder for discussion.

Many of the standard magics don't work in this context, but I think the real point is whether supporting the ones that do (`timeit`, for example) should be done through magics or some other more standard Python mechanism.

**Comment by rth** [comment]
Would packaging IPython and sending magic commands to,
```py
import IPython.ipapi 
ip = IPython.ipapi.get() 
ip.magic(<some command>
```
work as a workaround? IPython has some some fairly specialized code e.g. for [timeit](https://github.com/ipython/ipython/blob/a827978d9a03f3edb8cc1c8bc5524287d354c87a/IPython/core/magics/execution.py#L138), the other possibility could be to vendor that, maybe?

**Comment by rth** [comment]
In the end I think this would likely make more sense to implement in the final notebook environment instead of in Pyodide core. Closing to keep a limited scope, particularly given the we haven't had users requests about it.
