### ISSUE TITLE
if __name__ == '__main__' not working with overwriting globals

### ISSUE THREAD

**Issue by kkoomen** [pyodide/pyodide#5113]
## 🐛 Bug

When the code contains `if __name__ == '__main__'` but when executed with

```
const globals = pyodide.globals.get('dict')();

pyodide.runPython(code, {
        globals,
        locals: globals
})
```

there's no output for any code that is inside the if-name-is-main block. When simply running the code via `pyodide.runPython(code)` it works. But in our application, it is crucial that the globals and locals are reset, so we need both these to be reset, but also allow that the user can use the if-name-is-main block.

It seems that inside the `globals` passed into the `runPython` is clearing something that is required for the if-name-is-main block.

### To Reproduce

```html
<!doctype html>
<html>

<head>
  <script src="https://cdn.jsdelivr.net/pyodide/v0.25.1/full/pyodide.js"></script>
</head>

<body>
  <script>
    loadPyodide().then((pyodide) => {
      const globals = pyodide.globals.get('dict')();

      const output = pyodide.runPython([
        'if __name__ == "__main__":',
        '    print("hello")'
      ].join('\n'), {
        globals,
        locals: globals
      });
    })
  </script>
</body>

</html>
```

### Expected behavior

The if-name-is-main block should be able to be used while also clearing the globals.

### Environment

Pyodide Version 0.25.1

**Comment by hoodmane** [comment]
This is the expected behavior. Try:
```
python -c 'print(eval("__name__", {}))'
```
it prints `'builtins'`, so `__name__ == "__main__"` is `False`. If you want `__name__` to be `"__main__"`, try `globals.set("__name__", "__main__")`.

**Comment by kkoomen** [comment]
@hoodmane Ah, makes sense yes, thanks!
