### ISSUE TITLE
Upgrade web worker example to use module type worker rather than classic type worker

### ISSUE THREAD

**Issue by castedo** [pyodide/pyodide#5119]
The documentation current shows how to create a classic type web worker:

https://pyodide.org/en/stable/usage/webworker.html

At some point it probably should be upgraded to show using a ES module type worker. I have an example working at https://gitlab.com/castedo/pyodide-worker-example/, specifically the files 

- https://gitlab.com/castedo/pyodide-worker-example/-/blob/main/webworker.mjs
- https://gitlab.com/castedo/pyodide-worker-example/-/blob/main/worker_facade.mjs

I don't have enough front-end programming experience to know whether it is too early to be recommending modules for this. So far it seems to be working well for me. And it is 2024.

I'm happy to create a PR to update the docs.

As an optional extra bonus, I can also change the simple API py-worker.js example to be the "drop stale IO" example of `worker_facade.mjs`. This drop-stale-IO facade seems like a simpler API to me, but I'm biased. I'm curious what y'all think. The consumer is https://gitlab.com/castedo/pyodide-worker-example/-/blob/main/main.mjs

**Comment by hoodmane** [comment]
Funny thing I just opened this PR a few days ago: 
https://github.com/pyodide/pyodide/pull/5114

**Comment by castedo** [comment]
@hoodmane Nice! Adding `type: "module"` was my main suggestion, so I'll close this. The merge you just did looks much better.

Using the "drop stale IO messages" model of: 

https://gitlab.com/castedo/pyodide-worker-example/-/blob/d317ef431c0e742339810b619c3626b726b275ec/worker_facade.mjs

as a simpler documentation example is a minor matter, and debatable and subjective .... and I'm obviously biased. :grinning:
