### ISSUE TITLE
Pyodide module's page is not up-to-date.

### ISSUE THREAD

**Issue by kimo** [pyodide/pyodide#5138]
## 📚 Documentation

in this url https://pyodide.org/en/stable/usage/packages-in-pyodide.html

**For example, this page lists duckdb where as duckdb-pyodide is the right one.** 

Thank you.

fyi. @laffra @kssd

**Comment by hoodmane** [comment]
We don't include any package called `duckdb-pyodide` but we do include duckdb: 
https://github.com/pyodide/pyodide/blob/0.26.3/packages/duckdb/meta.yaml
So I think the documentation is right.

**Comment by laffra** [comment]
I think the intent was to say that package "duckdb" does not appear to work well in PyScript. We see errors in PySheets. We also discovered https://github.com/duckdb/duckdb-pyodide?tab=readme-ov-file. Is this package included in PyOdide as "duckdb"?

**Comment by laffra** [comment]
![Screenshot 2024-10-27 225212](https://github.com/user-attachments/assets/01968df5-7035-4e59-b3b6-4cd8710907ad)

**Comment by laffra** [comment]
The error shown in the screenshot made us wonder if "duckdb" actually works on pyodide...

**Comment by laffra** [comment]
Simplyfying the example shows that DuckDB does work, it just does not work well with httpfs.

![image](https://github.com/user-attachments/assets/9d6094f5-de8b-43ee-8850-e16460c346ce)

**Comment by laffra** [comment]
httpfs is also not working well on pyscript.com

![image](https://github.com/user-attachments/assets/1e4f3095-2e0f-490d-a172-86b1239dce43)

**Comment by laffra** [comment]
I did find a workaround, so we can close this issue, I think.

![image](https://github.com/user-attachments/assets/9a039a6b-b900-4d48-bedf-f9841b3296b2)

**Comment by ryanking13** [comment]
I don't know how `httpfs` internally works, but if it relies on sockets, it will not work as we don't support sockets.

**Comment by laffra** [comment]
Okay, I am trying to use PyPi to download the extension now and getting closer to why the duckdb package entry in PyOdide is actually a problem. It is an old version. Currently, PyOdide include v1.0.0.

https://pypi.org/project/duckdb-extension-httpfs/#history shows that the first version supported there is v1.0.1.

Can we bump the version for duckdb to 1.1.1 (the latest)?

**Comment by laffra** [comment]
I request an update to duckdb from 1.0.0 to a more recent version, such as 1.1.1
See: https://github.com/pyodide/pyodide/issues/5139

**Comment by hoodmane** [comment]
It was updated to 1.1.0 on the main branch:
https://github.com/pyodide/pyodide/pull/5078
So when we release 0.27.0 it will come with DuckDB 1.1.0. The main thing we're waiting on for releasing 0.27.0 is [the Numpy v2.0 update](https://github.com/pyodide/pyodide/pull/4925), but it's not clear when that will be done...
