### ISSUE TITLE
Package request: Update DuckDB to 1.1.1 (the latest)

### ISSUE THREAD

**Issue by laffra** [pyodide/pyodide#5139]
## 🐍 Package Request

- duckdb is already included in pyodide as version 1.0.0
- to install extensions, such as httpfs, you add package "duckdb-extensions" from pypi
- that package has frozen dependencies, which currently point to duckdb 1.1.1
 
See a PyScript app that shows the version compatibility problem:
https://pyscript.com/@laffra/duckdb-with-extensions/latest?files=main.py

**Comment by agriyakhetarpal** [comment]
Hi, @laffra! DuckDB has been updated to version 1.1.2 in #5142, which should become a part of a release shortly (#5064).
