### ISSUE TITLE
pyodide.loadedPackages returns array(0)

### ISSUE THREAD

**Issue by PythonLinks** [pyodide/pyodide#519]
Using your recommended server: 
https://alpha.iodide.io/notebooks/300/
I do the following commands, one at a time, waiting for them to complete. 

import numpy
from js import pyodide
pyodide.loadedPackages

I get 
Array(0)

I expect to get 
["numpy"]

I hope that helps.

**Comment by hoodmane** [comment]
@rth this can be closed since `loadedPackages` has been removed from the public API.

**Comment by hoodmane** [comment]
Nevermind that's wrong sorry.

**Comment by hoodmane** [comment]
But this can be closed anyways since the bug is gone now.

**Comment by dalcde** [comment]
It is now an object

**Comment by rth** [comment]
This works as expected with explicit type conversion,
```py
>>> from js import pyodide as pyodide_js
>>> pyodide_js.loadedPackages.to_py()
{'numpy': 'default channel'}
```
