### ISSUE TITLE
scipy.optimize.fmin lacks the optional argument "initial_simplex"

### ISSUE THREAD

**Issue by tttom** [pyodide/pyodide#522]
Hi all,

It appears that `scipy.optimize.fmin` doesn't recognize the initial_simplex argument. This optional input argument is documented [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html).

Specifically, I call the fmin function as:
`## py`
`import scipy.optimize`
`scipy.optimize.fmin(lambda x: x**2, 0.0, initial_simplex=[[0.0], [1.0]])`
on [https://alpha.iodide.io/tryit](https://alpha.iodide.io/tryit)

I am a bit surprised that something this specific is not implemented while nearly everything else runs perfectly fine with pyodine. Am I missing something? If not, does anybody know where the issue lies?

Thanks,

Tom

**Comment by rth** [comment]
We are unfortunately using a somewhat outdated version of scipy 0.17, so the right documentation for that function would be https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.optimize.fmin.html

Updating scipy would be good, but it would require some effort and working around Fortran issues https://github.com/iodide-project/pyodide/issues/184

**Comment by tttom** [comment]
Thanks for the quick answer!

**Comment by rth** [comment]
This should be resolved in the next release with https://github.com/pyodide/pyodide/pull/2065
