### ISSUE TITLE
New package request pi-heif

### ISSUE THREAD

**Issue by airen1986** [pyodide/pyodide#5242]
Important Note: I am using some package with has downstream dependency on pi-hief, on further investigation I found it is exactly pillow-hief with same maintainers and same git repository. As I cannot change upstream package, can we include pillow-hief as well?

## 🐍 Package Request

- Package Name and Version: pi-heif 0.21.0
- Package URL : https://pypi.org/project/pi-heif/
- Package Dependencies that needs to be resolved first: pillow-heif

## Checklists

- [Y] I have tried to install the package using `micropip.install(...)` and encountered the issue.
- [N] I have read the [documentation](https://pyodide.org/en/stable/development/building-and-testing-packages.html) and tried building the package myself.

**Comment by ryanking13** [comment]
Sounds god. PR welcome.
