### ISSUE TITLE
Link with SDL: cannot link with libSDL2.a (but can link with library_sdl.js) 

### ISSUE THREAD

**Issue by pthom** [pyodide/pyodide#5248]
## 🐛 Bug

A module which links with SDL will link with library_sdl.js but not libSDL2.a 

* Attempting to use functions which are defined in library_sdl.js works (such as as `SDL_Init`)
* Attempting to use functions which are defined in libSDL2.a fails (such as as `SDL_SetHint`)

More details:
* A call to SDL_Init() works : it is defined in emsdk/emsdk/upstream/emscripten/src/library_sdl.js
* A call to SDL_SetHint() does not work : it is defined in ./emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a
* emsdk/.../wasm32-emscripten/libSDL2.a is compiled without -fPIC and not suitable for a manual forced link
* I think that emscripten can provide alternative versions in emsdk/.../wasm32-emscripten/pic or wasm32-emscripten/lto, but they are not present in pyodide (although wasm32-emscripten/lto/libSDL2.a was available in a past version of pyodide)

### To Reproduce

Create a package "daft_lib" in packages:
```
packages/daft_lib/
├── daft_lib_src
│   ├── CMakeLists.txt
│   ├── daft_lib.cpp
│   └── pyproject.toml
└── meta.yaml
```

**daft_lib_src/daft_lib.cpp**
```cpp
#include <SDL.h>
#include <stdio.h>

void dummy_sdl_call()
{
    printf("About to call SDL_init\n");
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) != 0)
        fprintf(stderr, "Error: %s\n", SDL_GetError());

    printf("About to call SDL_SetHint\n");
    SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
    printf("After SDL_SetHint\n");
}

#include <nanobind/nanobind.h>
NB_MODULE(daft_lib, m) {
    m.def("dummy_sdl_call", &dummy_sdl_call);
}
```

**meta.yaml**
```
package:
  name: daft_lib
  version: 0.0.1
  top-level:
    - daft_lib
source:
  path: daft_lib_src
```

**pyproject.toml**
```
[build-system]
requires = ["scikit-build-core>=0.3.3", "nanobind"]
build-backend = "scikit_build_core.build"
[project]
name = "daft_lib"
version = "0.0.1"
description="daft-lib"
requires-python = ">=3.7"
[tool.scikit-build]
wheel.expand-macos-universal-tags = true
wheel.packages = ["src/python_bindings/daft_lib"]
cmake.verbose = true
logging.level = "INFO"
```

**CMakeLists.txt**
```cmake
cmake_minimum_required(VERSION 3.15...3.27)
project(daft_lib VERSION "0.0.1")
set(CMAKE_CXX_STANDARD 20)

macro(litgen_find_python)
    # cf https://nanobind.readthedocs.io/en/latest/building.html
    if (CMAKE_VERSION VERSION_LESS 3.18)
        set(DEV_MODULE Development)
    else()
        set(DEV_MODULE Development.Module)
    endif()
    find_package(Python 3.8 COMPONENTS Interpreter ${DEV_MODULE} REQUIRED)
endmacro()

macro(litgen_find_nanobind)
    litgen_find_python()
    # Detect the installed nanobind package and import it into CMake
    execute_process(
        COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
        OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE nanobind_ROOT)
    find_package(nanobind CONFIG REQUIRED)
    if (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
        set(CMAKE_BUILD_TYPE Release CACHE STRING "Choose the type of build." FORCE)
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
    endif()
endmacro()

# Main
litgen_find_python()
litgen_find_nanobind()
nanobind_add_module(daft_lib daft_lib.cpp)

# Attempt to link SDL2 "a la cmake": this has no effect within pyodide / emscripten
find_package(SDL2 REQUIRED)
target_link_libraries(daft_lib PUBLIC SDL2::SDL2 SDL2::SDL2main)
target_compile_options(daft_lib PUBLIC "-sUSE_SDL=2")

# Link with SDL the emscripten way
target_compile_options(daft_lib PUBLIC "-sUSE_SDL=2")
target_link_options(daft_lib PUBLIC "-sUSE_SDL=2")

# Manually link libSDL2.a: this will fail because libSDL2.a is compiled without -fPIC
# set(ems_lib_path ${EMSCRIPTEN_SYSROOT}/lib/wasm32-emscripten/)
# target_link_directories(daft_lib PUBLIC ${ems_lib_path})
# target_link_libraries(daft_lib PUBLIC SDL2)

install(TARGETS daft_lib DESTINATION .)
```

### Expected behavior

Use the module with this javascript code:

```js
    console.log('About to run SDL code.');
    pythonCode = `
    import daft_lib
    print(dir(daft_lib))
    daft_lib.dummy_sdl_call()
    `
    await pyodide.runPythonAsync(pythonCode);
    console.log('Pyodide SDL code executed successfully.');
```

This should log "Pyodide SDL code executed successfully.".

However, I get this error in the console log:

```
About to run SDL code. [pyodide_loader.js:4:13](http://localhost:8005/js/pyodide_loader.js)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add', 'dummy_sdl_call'] [pyodide.asm.js:10:98674](http://localhost:8005/pyodide_dist/pyodide.asm.js)
About to call SDL_init [pyodide.asm.js:10:98674](http://localhost:8005/pyodide_dist/pyodide.asm.js)
About to call SDL_SetHint [pyodide.asm.js:10:98674](http://localhost:8005/pyodide_dist/pyodide.asm.js)
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers. [pyodide.asm.js:10:48512](http://localhost:8005/pyodide_dist/pyodide.asm.js)
The cause of the fatal error was: [pyodide.asm.js:10:48612](http://localhost:8005/pyodide_dist/pyodide.asm.js)
Error: Dynamic linking error: cannot resolve symbol SDL_SetHint
    prop pyodide.asm.js:10
    _PyEM_TrampolineCall_JS pyodide.asm.js:10
...
```

### Environment

- Pyodide Version: latest version (e54b220cf46aaa60b1ba57a6e620191824540df0), dec 4th 2024
- Browser version: it does not depend on the browser
- Build environment: ubuntu 24.04 with Conda

### Additional context

This issue is related to [this other issue](https://github.com/pyodide/pyodide/discussions/4707).
At this time, I was advised to link manually against SDL2 by adding these lines inside meta.yaml
```
build:
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
    -lSDL2
``` 

it does not work anymore (the path WASM_LIBRARY_DIR is likely not correct).

Attempting to link libSDL2.a manually in CMake like this:

```cmake
# Manually link libSDL2.a: this will fail because libSDL2.a is compiled without -fPIC
set(ems_lib_path ${EMSCRIPTEN_SYSROOT}/lib/wasm32-emscripten/)
target_link_directories(daft_lib PUBLIC ${ems_lib_path})
target_link_libraries(daft_lib PUBLIC SDL2)
```

Will fail at link time, with this message:
```
[13/13] : && /tmp/tmpltv8z0mj/c++ -fPIC -O3 -DNDEBUG  -Wl,-s -sUSE_SDL=2 -sMAX_WEBGL_VERSION=2 -sMIN_WEBGL_VERSION=2 -Wl,--gc-sections -shared  -o daft_lib.cpython-312-wasm32-emscripten.so CMakeFiles/daft_lib.dir/daft_lib.cpp.o -L/home/pascal/dvp/_Bundle/_Pyodide/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten libnanobind-static.a  -lSDL2  -sUSE_SDL=2 && :
FAILED: daft_lib.cpython-312-wasm32-emscripten.so 
: && /tmp/tmpltv8z0mj/c++ -fPIC -O3 -DNDEBUG  -Wl,-s -sUSE_SDL=2 -sMAX_WEBGL_VERSION=2 -sMIN_WEBGL_VERSION=2 -Wl,--gc-sections -shared  -o daft_lib.cpython-312-wasm32-emscripten.so CMakeFiles/daft_lib.dir/daft_lib.cpp.o -L/home/pascal/dvp/_Bundle/_Pyodide/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten libnanobind-static.a  -lSDL2  -sUSE_SDL=2 && :
wasm-ld: error: /home/pascal/dvp/_Bundle/_Pyodide/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a(SDL.c.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol `SDL_SubsystemRefCount`; recompile with -fPIC
wasm-ld: error: /home/pascal/dvp/_Bundle/_Pyodide/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a(SDL.c.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol `SDL_SubsystemRefCount`; recompile with -fPIC
wasm-ld: error: /home/pascal/dvp/_Bundle/_Pyodide/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a(SDL.c.o): relocation R_WASM_MEMORY_ADDR_LEB cannot be used against symbol `SDL_SubsystemRefCount`; recompile with -fPIC
```

Sometime in the past, the emsdk provided by pyodide did include another libSDL2.a, inside `${EMSCRIPTEN_SYSROOT}/lib/wasm32-emscripten/lto`. By chance, this version was compiled with `-fPIC`. It is not here anymore.

For example, with a version dating from apr 2024, I had those:

```
find old_pyodide_apr2024 -name "libSDL2.a" 
old_pyodide_apr2024/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libSDL2.a
old_pyodide_apr2024/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libSDL2.a
old_pyodide_apr2024/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a
```

Note: manually linking with the old "wasm32-emscripten/pic/libSDL2.a" seems to work, although it is a bit worrying to use it.

**Comment by pthom** [comment]
Hello @ryanking13, would you have a little time to look at this? Your previous solution greatly helped me in the past, but it does not work anymore. Thanks!

**Comment by pthom** [comment]
I found a temporary workaround by building SDL2 myself from the version inside pyodide's emsdk:

```bash
export SDL_PIC_INSTALL_DIR=some/folder/
cd emsdk/emsdk/upstream/emscripten/cache/ports/sdl2/SDL-release-2.28.4"
chmod +x ./configure
emconfigure ./configure --host=wasm32-unknown-emscripten --disable-pthreads --disable-assembly --disable-cpuinfo --prefix="$SDL_PIC_INSTALL_DIR" CFLAGS="-fPIC -sUSE_SDL=0 -O3" CXXFLAGS="-fPIC -sUSE_SDL=0 -O3"
emmake make -j"$(nproc)"
emmake make install
```

and then link manually with $SDL_PIC_INSTALL_DIR/lib/libSDL2.a

**Comment by ryanking13** [comment]
Thanks for the report @pthom. Sometimes `-fPIC` flags are not passed when building Emscripten ports or side modules for some reason.

Could you try adding `-s RELOCATABLE=1` in the compile/link flags and see if it works? (e.g. [Pillow meta.yaml](https://github.com/pyodide/pyodide/blob/0065e612cfc8908b46d89c3320f24db4d7baeaff/packages/Pillow/meta.yaml#L14) ). It affects how Emscripten [grabs the library directory](https://github.com/emscripten-core/emscripten/blob/c08204e56de44a66763ed58c161622850b1da91a/tools/cache.py#L125-L126) and how [they are complied](https://github.com/emscripten-core/emscripten/blob/c08204e56de44a66763ed58c161622850b1da91a/emcc.py#L397-L398)

**Comment by ryanking13** [comment]
Thanks for the investigation. 

> May be the flags used by emscripten during its compilation are a bit different.

Yes, it can be different from Emscripten as Emscripten builds the library [from the source file directly](https://github.com/emscripten-core/emscripten/blob/d87c1ac5ca4aa91f23e27a908f929733fe73cee8/tools/ports/sdl2.py) without utilizing the build systems that each library provides.

But I am unsure why it leads to the `bad export type` error. Could you try comparing the symbols of two `libsdl2.a` files, using the `emnm` tool that emscripten provides?

**Comment by pthom** [comment]
> But I am unsure why it leads to the bad export type error. Could you try comparing the symbols of two libsdl2.a files, using the emnm tool that emscripten provides?


The attached file below 
[nm_sdl.zip](https://github.com/user-attachments/files/18072912/nm_sdl.zip)


contains:
```
nm_sdl
├── with_address                               # original nm outputs
│   ├── nm_ems_fpic_libsdl2.txt.     # emscripten fpic/libSDL2.a
│   ├── nm_ems_libsdl2.txt.             # Standard emscripten libSDL2.a
│   └── nm_my_libsdl2.txt.              # my own compilation
└── no_address                            # nm outputs with addresses replaced by "adress" 
    ├── nm_ems_fpic_libsdl2.txt. # to facilitate comparison
    ├── nm_ems_libsdl2.txt
    └── nm_my_libsdl2.txt
```

no_address/nm_ems_libsdl2.txt and no_address/nm_ems_fpc_libsdl2.txt are quite close.
However, the result of my compilation is quite different. I will need to adjust it to be able to have more info.

Thanks for pointing out emscripten build script. I will to to add tooling to get it to be more informative about what it does.

**Comment by pthom** [comment]
Hello again @ryanking13 

I'm sorry, I was mistaken in my previous answers...

It is difficult to keep track of the state when building within pyodide, given all the caches (in emscripten and pyodide), and I lost track.

Here is the status I now have:

- I *cannot reproduce the `SDL_VIRTUAL_JoystickDriver` link* issue (sorry for this, this was an error on my side)

However, I still have an issue:

* ***Adding `-sRELOCATABLE` is not enough to convince emscripten to build a relocatable version of SDL** 

emscripten will not compile it, probably because the python module I am building is a side library.

Actually the best way I found to convince emscripten to produce it is **to create a fake app** that links to SDL, e.g:
```bash
# Activate emscripten
source emsdk/emsdk/emsdk_env.sh
# Build a fake app with relocatable flags
echo 'int main() {}' | emcc -x c -sUSE_SDL=2 -sRELOCATABLE=1  - -o output.js && rm output.js

# and then
ls -al ./emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/
total 17892
drwxrwxr-x 2 pascal pascal    4096 déc.  10 13:55 .
drwxrwxr-x 3 pascal pascal    4096 déc.  10 13:56 ..
-rw-rw-r-- 1 pascal pascal   24288 déc.  10 13:55 libal.a
-rw-rw-r-- 1 pascal pascal 1451974 déc.  10 13:55 libc++abi-debug-noexcept.a
-rw-rw-r-- 1 pascal pascal 3432374 déc.  10 13:55 libc-debug.a
-rw-rw-r-- 1 pascal pascal 8519186 déc.  10 13:55 libc++-noexcept.a
-rw-rw-r-- 1 pascal pascal  513432 déc.  10 13:55 libcompiler_rt.a
-rw-rw-r-- 1 pascal pascal   69588 déc.  10 13:55 libdlmalloc.a
-rw-rw-r-- 1 pascal pascal   51940 déc.  10 13:55 libGL-getprocaddr.a
-rw-rw-r-- 1 pascal pascal   56742 déc.  10 13:55 libhtml5.a
-rw-rw-r-- 1 pascal pascal    1664 déc.  10 13:55 libnoexit.a
-rw-rw-r-- 1 pascal pascal 4076024 déc.  10 13:55 libSDL2.a
-rw-rw-r-- 1 pascal pascal   69320 déc.  10 13:55 libsockets.a
-rw-rw-r-- 1 pascal pascal   29474 déc.  10 13:55 libstubs-debug.a
```

(This time, I did a full test after after running `make clean` everywhere, and recreating the conda environment)

**Comment by ryanking13** [comment]
@pthom 

> probably because the python module I am building is a side library.

You are right, when building a main module with `-sUSE_...` flags, it will build the target ports, but when building a side library, it sometimes does not. I think there was an open issue about it in this repository with the code pointer, but I don't remember the exact issue number.

However, when a port is already built, passing the `-sUSE...` flag will link it anyway, so building a fake app before building an actual package worked in your case, I guess.

One better way to build the port explicitly is to use a `embuilder` tool that emscripten provides. We are using it in several recipes e.g. in [pygame recipe](https://github.com/pyodide/pyodide/blob/0065e612cfc8908b46d89c3320f24db4d7baeaff/packages/pygame-ce/meta.yaml#L15)

```
embuilder build sdl2 --pic
```

**Comment by pthom** [comment]
@ryanking13 

Thanks a lot! I added this to metal.yaml

```yaml
build:
  script: |
    embuilder build sdl2 --pic
```

and then linked ${EMSCRIPTEN_SYSROOT}/lib/wasm32-emscripten/pic/libSDL2.a

And it works!

Please feel free to close this issue, or leave it opened If you want to keep it as reminder about the original link issue.

Cheers!

**Comment by ryanking13** [comment]
Thanks for the confirmation! Let me close this issue as resolved then.
