### ISSUE TITLE
Add stub for the _ssl module

### ISSUE THREAD

**Issue by filips123** [pyodide/pyodide#529]
Can you provide support for `ssl` module? Right now, when `ssl` is imported, it throws an error:

```
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 2, in <module>
  File "/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

_hiwire_throw_error (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:38602)
https://pyodide.cdn.iodide.io/pyodide.asm.wasm:wasm-function[356]:0xfba87::
https://pyodide.cdn.iodide.io/pyodide.asm.wasm:wasm-function[383]:0xfd738::
pyodide/Module.__runPython (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:2027266)
_runpython_init_js/Module._runPythonInternal (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:42817)
internal (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:43382)
_runpython_init_js/Module.runPythonAsync (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:43857)
```

**Comment by mdboom** [comment]
What's the use case?  It's unlikely that the underlying network code will work anyway since there is no low-level networking available in browsers.  If you just need to fetch from an `https` URL, you can use the browser's `fetch` API.

**Comment by filips123** [comment]
@mdboom Some packages rely on `ssl` module so they will fail because of import error. And it is not always just in network-related packages. Some packages are importing `ssl` in a top-level module which will cause fail even if the package has not network-related submodules.

**Comment by mdboom** [comment]
Ah.  Maybe then we can provide a stub for `_ssl` that just makes the import pass.

**Comment by filips123** [comment]
@mdboom This should be enough but it would be still nice to support whole `ssl` module (but maybe later in the future).

**Comment by danyx23** [comment]
Yeah SSL stubbing would be great - I would like to use a library that makes a request using the requests library to an https endpoint and that fails atm

**Comment by smkm** [comment]
> Yeah SSL stubbing would be great - I would like to use a library that makes a request using the requests library to an https endpoint and that fails atm

I'm confused about this. Does this mean that `request` or `urllib3` modules can be used or should I still program my python code to do `from js import fetch`?

**Comment by rth** [comment]
>  Does this mean that request or urllib3 modules can be used or should I still program my python code to do from js import fetch?

No urllib3 / requests will in any case not work in pyodide due to WASM environment limitations. Using JS for network calls is the way to go. This issue is just about avoiding import errors in packages (when using functionality unrelated to network calls or ssl).

**Comment by andeplane** [comment]
What if I use a package that uses `requests`, so simply switching to JS fetch isn't really feasable? Is there a workaround for this?

**Comment by rth** [comment]
> Should be possible to create a requests package that has the same API, but different implementation under the hood maybe?

I think, there is a partial re-implementation of requests by @casatir  in Basthon [here](https://framagit.org/basthon/basthon-kernel/-/tree/master/packages/kernel-python3/src/modules/requests). However the main limitation is that the browser doesn't allow to fetch binary files synchronously. Until we find a solution for #1503  that is.

Otherwise there will be a [`pyodide.http.pyfetch`](https://pyodide.org/en/latest/usage/api/python-api.html?highlight=pyfetch#pyodide.http.pyfetch) in the next release, but it's async.

**Comment by jobovy** [comment]
+1 on the stub. Without it
```
import astropy.io.fits
```
fails and that's a common import in astronomy packages because FITS files are so common (even if most of the module runs fine without FITS).

**Comment by matthewfeickert** [comment]
+1 on this as well. :+1: 

Similarly to @jobovy's example, `pyhf` uses `requests` in our [`pyhf.contrib.utils.download`](https://pyhf.readthedocs.io/en/v0.6.3/_generated/pyhf.contrib.utils.download.html) API which is used to pull published statistical models from [HEPData](https://www.hepdata.net/). As we use these models in a lot of our demos and to highlight use cases in our documentation, it would be useful to be able to run some full demos in `pyodide` (as we show a bit here: https://github.com/scikit-hep/pyhf/issues/1775).

(`pyodide` is super amazing though, so thanks very much for everyone's efforts to give us such a tool!)

**Comment by hoodmane** [comment]
This was resolved by #2263.

**Comment by hoodmane** [comment]
Note though that ssl passes only 46/168 tests, anything that tries to touch a socket just returns an ENOSYS or similar.

**Comment by matthewfeickert** [comment]
> This was resolved by #2263.

Oh wow! Thanks so much for addressing this @hoodmane! This will be great to have in future releases of `pyodide` (hopefully in `v0.19.2`?).

**Comment by hoodmane** [comment]
We most likely won't do a v0.19.2 release because #2027 and #2133 changed so much of our system that it is pretty hard to backport anything after that. Hopefully we'll make a v0.20 release some time in April.

**Comment by ryanking13** [comment]
`ssl` module is unvendored by default (See: [Pyodide Python compatibility](https://pyodide.org/en/stable/usage/wasm-constraints.html#optional-modules)), so you need to load it via `await pyodide.loadPackage("ssl")`.

However, even if you load ssl module, you will not be able to use it to send HTTPS request since [socket is not available in Pyodide](https://github.com/pyodide/pyodide/issues/140).
It seems like gov-uk-back-holidays package uses requests library. So probably you can check [pyodide-http](https://github.com/koenvo/pyodide-http).
