### ISSUE TITLE
 A new PyOdide Application, and a list of PyOdide applications. 

### ISSUE THREAD

**Issue by PythonLinks** [pyodide/pyodide#546]
I have been teaching classes on Python in the browser, based on PyOdide and soon Transcrypt.  So I built a Python  editor in the browser using the AceEditor, but it did not have syntax checking.  So now on every keystroke, I compile the code, and flag errors.  You can play with the PyOdide-based Python editor here:
https://demo.forestwiki.com/HtmlContentTypes/python.py/acedemo

I then added this application  to my collection of PyOdide applications. 
https://pythonlinks.info/pyodide-web-sites

If you have a running PyOdide application, let us add it to the list. 
lozinski@PythonLinks.info

**Comment by phorward** [comment]
Hello @PythonLinks, I've created a pyodide-app-stub project located at https://github.com/mausbrand/pyodide-app-stub that uses our html5 widget library in combination with Pyodide. Feel free to use or link to it.

**Comment by rth** [comment]
Thanks! We now have a [documentation page](https://pyodide.org/en/latest/project/related-projects.html) on related projects so feel free to make a PR there.
