### ISSUE TITLE
Matplotlib is very slow

### ISSUE THREAD

**Issue by shi-yan** [pyodide/pyodide#547]
this page takes 30 seconds to load, which hurts user experience.

https://epiphany.pub/@shi-yan/python-test

I suspected this was due to large packages. But it turned out that only numpy and matplotlib are large and they take less than 2 seconds to load. The execution of pyodide takes 15 seconds. 

Is there a way to speed up this process?

**Comment by rth** [comment]
See related discussion in https://github.com/pyodide/pyodide/issues/1365 . Closing as a duplicated. Don't hesitate to comment in the linked issue.
