### ISSUE TITLE
Calculation errors involving numpy int64s

### ISSUE THREAD

**Issue by felixlawrence** [pyodide/pyodide#556]
I get incorrect answers out of scipy when I give the input as a `np.int64`.

### What I Did

```
%% py
import scipy.stats as st
import numpy as np

st.beta(
    np.int64(2969),
    np.int64(1438)
).ppf([0.05, 0.95])
```

### What I Expected

```Float64Array(2)[0.662040319585152, 0.6852718992213929]```

### What Happened 

```Float64Array(2)[8.3210077774, 0.6852718992213929]```

(Note that the first element here is actually 8.32e-308, per #2439 )

### Fuller example illustrating the problem

```
%% py

import scipy.stats as st
import numpy as np

%% py

# First element of return value is wrong

st.beta(
    np.int64(2969),
    np.int64(1438)
).ppf([0.05, 0.95])

%% py

# Correct

st.beta(
    2969,
    1438
).ppf([0.05, 0.95])

%% py

# Correct

st.beta(
    np.int64(2969),
    np.int64(1438)
).ppf(0.05)
```

**Comment by rth** [comment]
The return value of the above code snippet in the 0.20.0 REPL is now correct. 
So I believe this was fixed with latest scipy fixes and updates.
