### ISSUE TITLE
[QUESTION] Why only printing the last evaluation ?

### ISSUE THREAD

**Issue by scheung38** [pyodide/pyodide#559]
Within the Notebook why it is only printing out the last eval?

1 + 1
1 + 2

I only get 3 and not

2
3

**Comment by rth** [comment]
I think this was fixed in the latest versions of the Pyodide REPL,
```
>>> 1+1; 1+2
2
3
```
Iodide is no longer actively maintained so there is not much we can do about that.

**Comment by hoodmane** [comment]
I'm actually confused about why it prints both 2 and 3 in that example. That isn't what I expect to happen at all, the behavior I intended was to just print 3...

**Comment by rth** [comment]
I'm also a bit confused about it, but I checked with a regular Python REPL and that's what it does as well.

**Comment by hoodmane** [comment]
Good call, I guess it is okay if it's a side effect of successfully imitating the regular REPL.
