### ISSUE TITLE
[QUESTION] which display format to use?

### ISSUE THREAD

**Issue by scheung38** [pyodide/pyodide#560]
Following one of the Coursera using Jupyter notebook to display a fractional formula 

$$ R_{t,t+1} = \frac{P_{t+1}-P_{t}}{P_{t}} $$

what format should be used?

<img width="942" alt="Screenshot 2019-11-17 at 13 16 44" src="https://user-images.githubusercontent.com/1273014/69007944-89095780-093c-11ea-8064-e51d55ca13e2.png">
should display as:
<img width="876" alt="Screenshot 2019-11-17 at 13 17 31" src="https://user-images.githubusercontent.com/1273014/69007952-a9391680-093c-11ea-8cb2-959e9e4fc903.png">

**Comment by rth** [comment]
It's probably a question for iodide not pyodide.
