### ISSUE TITLE
Compilation on MacOS 10.15 Catalina?

### ISSUE THREAD

**Issue by alexeyignatiev** [pyodide/pyodide#572]
Hi there.

I am trying to compile Pyodide on MacOS Catalina and the process fails with the following traceback:

```
Traceback (most recent call last):
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/Python-3.7.0/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make[2]: *** [install] Error 1
make[1]: *** [/Users/aign/Projects/extern/pyodide/cpython/build/3.7.0/host/bin/python3] Error 2
make: *** [cpython/installs/python-3.7.0/lib/python3.7] Error 2
```

My understanding is that the compiler fails to find the right headers (in this case the headers of `zlib`) even though they are installed, and thus fails to compile some of the components, e.g. `zlib`. If I am not mistaken, it is because the headers cannot be found in `/`. I wonder if there is a solution to this issue on Catalina? If yes, any help would be really appreciated.

**Comment by wlach** [comment]
I have not yet upgraded my system to Catalina, but probably will soon. The current set of instructions might need some modifications might point you in the right direction though?

https://github.com/iodide-project/pyodide#building-from-source

**Comment by alexeyignatiev** [comment]
Well, not really, but thanks for replying! The point about the system libraries seems out of date now. Catalina does not offer a solution similar to `sudo installer -pkg ...`.

Is there a way to specify additional include and library directories, which could be used when building Pyodide?

**Comment by wlach** [comment]
> Is there a way to specify additional include and library directories, which could be used when building Pyodide?

Not that I know of, but hardcoding some things into the build system is ok if it solves the problem.

The PR where I added support for mojave may be helpful here:

https://github.com/iodide-project/pyodide/pull/541/files

**Comment by alexeyignatiev** [comment]
Thank you. I tried to add `` `brew --prefix zlib`/include`` to `HOSTPYTHON_CPPFLAGS` and `` `brew --prefix zlib`/lib`` to `HOSTPYTHON_LDFLAGS` in `cpython/Makefile` similar to what was done there for `openssl`. But it did not help. I still get the same error.

**Comment by wlach** [comment]
> Thank you. I tried to add `` `brew --prefix zlib`/include `` to `HOSTPYTHON_CPPFLAGS` and `` `brew --prefix zlib`/lib `` to `HOSTPYTHON_LDFLAGS` in `cpython/Makefile` similar to what was done there for `openssl`. But it did not help. I still get the same error.

It looks like the error you're seeing is a runtime issue rather than a link time one (i.e. the version of python that we've built can't find zlib for some reason). Unfortunately I'm not sure offhand how to resolve it -- if I were debugging this, I would probably try to just build a copy of python standalone and try to use it, since it doesn't seem to have anything to do with pyodide per se (at least from what I can tell from your error). @mdboom may have additional ideas when he's available.

**Comment by alexeyignatiev** [comment]
Following your suggestion, I downloaded and managed to compile Python 3.8.0 from the official website. It is hard for me to understand though. It says that it was built successfully but then it complains about some missing modules:
```

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_hashlib              _ssl                  ossaudiodev
spwd
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd
time


Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381
```
Well, at least it did not complain about `zlib`.

**Comment by rth** [comment]
Closing as many things changed since 2019. Currently for building on MacOS I would recommend using conda / conda-forge (see [documentation](https://pyodide.org/en/latest/development/building-from-sources.html#using-make))
