### ISSUE TITLE
External package index

### ISSUE THREAD

**Issue by filips123** [pyodide/pyodide#575]
Currently, if you want to use Python package with C code, you need to contribute it to this repository so it will be built and usable from Pyodide.

Because number of packages included in Pyodide is currently low, and Iodide is mainly built for "scientific stack", this is currently OK. But in the future, you may want to use Pyodide for more general web development, so only scientific packages won't be enough. Contributions all of those packages to this repository wouldn't make sense, as they won't be scientific and would just make mess.

Instead, it would be good to support external package index, where users could easily contribute packages, not only scientific, which would then be usable from Pyodide. Another feature that would be good is Python wheels targeted for Pyodide directly on normal PyPI, but as Pyodide is currently experimental, his would need to wait some time.

**Comment by rth** [comment]
> Instead, it would be good to support external package index, where users could easily contribute packages, not only scientific, which would then be usable from Pyodide.

Absolutely. I think you can already change manually the URL for the package index [here](https://github.com/iodide-project/pyodide/blob/master/src/pyodide.js#L9). Adding some mechanism to handle multiple packages indexes (or channels in conda language) could be useful.  Don't hesitate to contribute if you see ways to improve the current situation.

Also somewhat related to earlier discussion in https://github.com/iodide-project/pyodide/issues/121   

> Another feature that would be good is Python wheels targeted for Pyodide directly on normal PyPI, but as Pyodide is currently experimental, his would need to wait some time.

Indeed.

**Comment by rth** [comment]
This is now being addressed in https://github.com/pyodide/micropip/issues/7 and https://github.com/pyodide/micropip/issues/62
