### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by guettli** [pyodide/pyodide#576]
I would love to see Python running in the webbrowser. I just don't like Javascript.

Unfortunately I there are reasons why I can't contribute code.

But I would like to donate, if this helps you.

Is there a way to help you by donating money?

**Comment by rth** [comment]
Thanks for asking @guettli ! We now accept donations via the Open Source Collective at the following link https://opencollective.com/pyodide

**Comment by guettli** [comment]
thank you every much. For my particular use-case, I found my way to develop modern web applications: [htmx.org](//htmx.org), which means I donate there.
