### ISSUE TITLE
What is the best way to pass a Python object from backend to pyodide, or is it even possible?

### ISSUE THREAD

**Issue by laike9m** [pyodide/pyodide#581]
Say I want to serve a frontend page that's running pyodide, while the backend is in Python. Is it possible to pass a Python object from backend to the pyodide runtime?

**Comment by filips123** [comment]
It depends what objects do you want to pass.

You could probably just use JSON or maybe Python `pickle` module if it works with Pyodide.

**Comment by rth** [comment]
> Is it possible to pass a Python object from backend to the pyodide runtime?

Yes, it seems to work for simple cases, e.g. on my laptop (python 3.7),
```py
>>> import pickle
>>> x = {'a': 2}
>>> pickle.dumps(x)
b'\x80\x03}q\x00X\x01\x00\x00\x00aq\x01K\x02s.'
```
and then in pyodide CLI (dev version, python 3.8.2)
```py
Welcome to the Pyodide terminal emulator 🐍
>>> 
>>> import pickle
>>> x = pickle.loads(b'\x80\x03}q\x00X\x01\x00\x00\x00aq\x01K\x02s.')
>>> type(x)
<class 'dict'>
>>> x['a']
2
```

however pickle is generally not portable, and it may fail for arbitrary objects. Maybe we should create a FAQ and add this question there.
