### ISSUE TITLE
Lists imported from javascript not working quite as expected

### ISSUE THREAD

**Issue by wlach** [pyodide/pyodide#591]
I'd expect lists imported from javascript to have the same semantics as lists built natively in python, but this seems not to be the case: for example, you can't use python's auto-slicing syntax like `foo[1:2]`. This confused me for an hour the other day when I was trying to use difflib. Example notebook:

https://definitely-staging.iodide.io/notebooks/243/

**Comment by rth** [comment]
This was fixed in the latest version, with the new type translation API,
**JS**
```js
var x = [2, 3, 4];
```
**Py**
```py
>>> from js import x
>>> type(x)
<class 'pyodide.JsProxy'>
>>> x_py = x.to_py()
>>> type(x_py)
<class 'list'>
>>> x_py[:1]
[1]
```
