### ISSUE TITLE
Trying to create a pyodide package: emscripten fails with wrong python bits

### ISSUE THREAD

**Issue by Hiisi5** [pyodide/pyodide#596]
Hello. Maybe it is a wrong place to ask (i.e. it is not an issue), so I apologize in advance. I was trying to follow [the documentation](https://pyodide.readthedocs.io/en/latest/new_packages.html) to build a package that includes C++. I was able to compile the package in question (the name of which I would prefer to keep private for work-related issues) natively. Then I have modified setup.py to include the following:
```
os.environ["CC"] = "emcc"
os.environ["CXX"] = "em++"
```
However when running `$ python setup.py build -v` I'm getting the following errors:
```
In file included from /mnt/data_2/DataC/miniconda3/include/python3.7m/Python.h:63:
/mnt/data_2/DataC/miniconda3/include/python3.7m/pyport.h:699:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
```
What am I doing wrong? What is the proper way of building a python package for emscripten?

**Comment by rth** [comment]
Sorry for lack of response. I'm not sure what exactly was wrong at the time, but both the emscripten and Python versions changed a lot since this issue was opened so it would probably be worth re-trying with current versions.
