### ISSUE TITLE
Solve baseURL filled by the makefile

### ISSUE THREAD

**Issue by tinmarino** [pyodide/pyodide#597]
I don't know at priory where the language pack will.

But shouldn't it be next to `pydide_dev.js` ?

https://github.com/iodide-project/pyodide/blob/c3ac3d3357bd9a4ecd14b7c59a215de341b4c9eb/src/pyodide.js#L9

```javascript
  var scripts = document.getElementsByTagName('script');
  var index = scripts.length - 1;
  var myScript = scripts[index];
  baseURL = myScript.src
```

Just a long way to say `baseURL` <- url of the javascript file currently executing.

Which solves this problem for me (in Firefox of course, I wouldn't dare ;)

```ŧext
The script from “https://tinmarino.github.io/pyodide.asm.data.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. console.html
Loading failed for the <script> with source “https://tinmarino.github.io/pyodide.asm.data.js”. console.html:1:1
TypeError: Response has unsupported MIME type
```

Also, scipy is 160Mb long, maybe a good idea to divide it (so I can host it on github which file limit is 100Mb.

All that said:

```text
 a88888b.                                                dP            
d8'   `88                                                88            
88        .d8888b. 88d888b. .d8888b. 88d888b. .d8888b. d8888P .d8888b. 
88        88'  `88 88'  `88 88'  `88 88'  `88 88'  `88   88   Y8ooooo. 
Y8.   .88 88.  .88 88    88 88.  .88 88       88.  .88   88         88 
 Y88888P' `88888P' dP    dP `8888P88 dP       `88888P8   dP   `88888P' 
                                 .88                                   
                             d8888P                                    
```

For the wonderful job you did: it works like a charm.

**Comment by tinmarino** [comment]
My version as example of storage only hosted https://tinmarino.github.io/app/python/pyodide/console.html

Sorry for not making a PR: I copied like a newbye the build v0.14.3

**Comment by rth** [comment]
Thanks for the report. I think this was addressed once we  removed `pydide_dev.js` and added a mandatory `loadPyodide({ indexURL : ..})` parameter.
