### ISSUE TITLE
Create a PyPi package for pyodide_build

### ISSUE THREAD

**Issue by gatesn** [pyodide/pyodide#604]
Similar to https://github.com/iodide-project/pyodide/issues/328

Would make it easier to generate additional packages for Pyodide without building the entire toolchain.

**Comment by rth** [comment]
> Would make it easier to generate additional packages for Pyodide without building the entire toolchain.

At this stage, I'm not sure that having pyodide_build on PyPi would help much. One would still need to build emsdk and cpython, and the main Makefile is still building some of the C dependencies required by packages (though https://github.com/iodide-project/pyodide/issues/713 might help with that).
