### ISSUE TITLE
Excluding large submodules of unit tests from build

### ISSUE THREAD

**Issue by machow** [pyodide/pyodide#617]
Hey! I noticed recently that pandas' unit tests seem to be included in the pyodide build. For the version used in pyodide (v0.23.4), this folder is 24M out of the total 30M that make up the package.

I wonder if this is contributing to pandas slow load time? 

I'm tinkering with the build right now, but wanted to check--Is there a quick way in pyodide to remove them? It looks like right now, the process involves downloading packages from a url (specified in packages/<package_name>/meta.yml).

**edit: testing excluding unit tests in pandas setup.py, and releasing in github fork here https://github.com/machow/pandas/releases/tag/0.23.4**

Here's what I get for pandas file sizes

```
du -sh pandas/*

8.0K	pandas/__init__.py
1.5M	pandas/_libs
 16K	pandas/_version.py
 12K	pandas/api
 56K	pandas/compat
4.0K	pandas/computation
8.0K	pandas/conftest.py
3.2M	pandas/core
8.0K	pandas/errors
4.0K	pandas/formats
1.0M	pandas/io
4.0K	pandas/json.py
4.0K	pandas/lib.py
4.0K	pandas/parser.py
232K	pandas/plotting
4.0K	pandas/testing.py
 24M	pandas/tests            # <--- unit tests
8.0K	pandas/tools
124K	pandas/tseries
4.0K	pandas/tslib.py
8.0K	pandas/types
172K	pandas/util

**Comment by machow** [comment]
Okay--after doing a little bit of testing, I noticed that the bulk of the final `pandas.data` file seems to be made up of its c code. Removing the tests dropped the final size from about 15M to 12M.

Not bad, but a little less than I had (naively) expected 😅.

**Comment by rth** [comment]
Thanks for investigating! Yes, there is potentially some small saving to be gained there, but most of the size is from C extensions I think. Also if we don't include tests, we won't be able to run them in WASM to know to what extent the package we built is actually working.

**Comment by machow** [comment]
Thanks for your quick reply! I'm looking at CircleCI, and it seems that the pandas unit tests aren't run. It looks like that when pyodide runs CI for a tagged branch, it runs a set of pyodide-specific tests. Do you know if they're run somewhere else (still trying to get the lay of the land, so could likely be missing something)?

e.g.

https://circleci.com/gh/iodide-project/pyodide/5255

**Comment by rth** [comment]
No they are not run as part of CI as that would take too long (also note some of those may fail). Users can run them though in pyodide with e.g. `pytest.main(['--pyarg', 'pandas'])`. Maybe we should document that better.

We could have a build option to remove test folders. Note that pandas it's one folder, but in other packages there are multiple tests folders.

**Comment by machow** [comment]
Ah, thanks for the pointer! It does seem like it could be a bit tricky to reliably remove test folders. Maybe something in `meta.yaml` that allows specifying folders / files to exclude?

In any event, it definitely has much less of an impact than I originally thought.

Thanks again for your help--the build for pyodide has been really clear and simple to modify! I think I saw a PR for updating pandas, and AFAICT it was pretty straightforward to do. I may check out that issue, and try out running the tests for pandas there :).

**Comment by rth** [comment]
> Maybe something in meta.yaml that allows specifying folders / files to exclude?

Yes, that would be great. See related discussion in https://github.com/iodide-project/pyodide/issues/653 

I think we could add en entry to `meta.yaml` for removing irrelevant files. And have some mechanism for optionally removing tests (e.g. searching for `test|tests` folders) enabled with a `PYODIDE_STRIP_PACKAGE_TESTS` env variable. That way we can still build a distribution with or without tests without modifying each individual `meta.yaml`.

This affects a lot of packages, not just pandas. For instance,
```
$ find numpy -iname "test?" -exec du -sh {} \;
4,0K    numpy/compat/tests
1,6M    numpy/core/tests
56K     numpy/distutils/tests
212K    numpy/f2py/tests
20K     numpy/fft/tests
704K    numpy/lib/tests
88K     numpy/linalg/tests
336K    numpy/ma/tests
56K     numpy/matrixlib/tests
152K    numpy/polynomial/tests
496K    numpy/random/tests
68K     numpy/testing/tests
48K     numpy/tests
```
Would you be interested looking into it?

**Comment by rth** [comment]
> This affects a lot of packages, not just pandas. 

This is likely the easiest way to significantly reduce package size. See https://github.com/iodide-project/pyodide/issues/646#issuecomment-649124358 for more details.

Ideally what we would want is to move all tests into a separate module loadable in pyodide. For instance, we could extract
```
package/tests/...
package/core/test/...
```
as
```
package_tests/..
package_tests/core/tests/..
```
and then package `package_tests` (using [package_file](https://github.com/iodide-project/pyodide/blob/bc3ffaae427e35b9ecd9a6216fadad031a363a47/pyodide_build/buildpkg.py#L173) function) as a separate package. This would allow reduce the size of `package` while still being able to run it's unit tests.
In an ideal world tests would always use absolute imports and could have a fully independent test module, but I'm not sure how true that is in practice. If it turns out to be difficult, removing tests with an optional flag could be acceptable too.
