### ISSUE TITLE
custom code / libraries

### ISSUE THREAD

**Issue by pannous** [pyodide/pyodide#623]
I once saw a tutorial for how to import custom code / libraries but can't find it anymore.  
If you could add/link the description for the import mechanism in the readme.md#getting-started that would be great.

(something similar to https://github.com/iodide-project/pyodide/pull/489)

**Comment by hlecuanda** [comment]
i'm not sure if you mean importing libraries as in `pip install foo-library`  or was it another "low level" kinda enchantment like #489 ?

maybe this:
https://pyodide.readthedocs.io/en/latest/pypi.html

```py
def do_work(*args):
  import snowballstemmer
  stemmer = snowballstemmer.stemmer('english')
  stemmer.stemWords('go goes going gone'.split())

import micropip
micropip.install('snowballstemmer').then(do_work)
```

**Comment by jcaesar** [comment]
@pannous Did you perhaps mean https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#loading-packages ?
(That documentation conveniently leaves out how to build packages to put them to custom paths they could be loaded from… Just building them together with all the others and then stealing them from the build directory doesn't seem to do the trick.)

**Comment by rth** [comment]
Closing as answered.

**Comment by pannous** [comment]
Updating broken links:

https://pyodide.org/en/stable/new_packages.html

https://pyodide.org/en/latest/usage/loading-packages.html

**Comment by hoodmane** [comment]
Thanks @pannous!
