### ISSUE TITLE
__name__ not '__main__' (but 'builtins')

### ISSUE THREAD

**Issue by grandrew** [pyodide/pyodide#629]
`__name__` global variable on main module incorrectly states that it is `builtins` while in reality it is `__main__` 

simple check:

```python
a = 1
import sys
sys.modules[__name__].a # error
sys.modules["__main__"].a # works
```

**Comment by rth** [comment]
Thanks! PR would be welcome to address this. I'm not really sure where this is defined.

**Comment by ryanking13** [comment]
![image](https://user-images.githubusercontent.com/24893111/150507842-e001ca5d-eae9-411c-8389-f8616d1ae7e7.png)

In the latest release of Pyodide (0.19.0), it looks like we are not having this issue anymore. I'll mark this as resolved, feel free to reopen if you are still having this issue.

**Comment by hoodmane** [comment]
This was resolved by https://github.com/pyodide/pyodide/pull/1905
