### ISSUE TITLE
Cannot catch pyodide.open_url not found exceptions

### ISSUE THREAD

**Issue by mauricelam** [pyodide/pyodide#636]
I am trying to use pyodide.open_url, and hit an issue when doing do. If the URL I am requesting is not found, the javascript side throws an exception, but I cannot catch it from the Python side. In fact, when that happens, the entire runPython call seems to exit on the javascript side.

```js
try {
pyodide.runPython(`
import pyodide
try:
  pyodide.open_url("http://doesnotexist.abcdef")
finally:
  print("This is not printed out")
print("This is not printed out either")
`)
} catch (e) {
  console.log('Javascript can catch the exception though', e);
}
```

![Screen Shot 2020-04-14 at 8 09 12 PM](https://user-images.githubusercontent.com/1264702/79294849-073a3d80-7e8c-11ea-8cf8-d0bdf47196e3.png)

More generally, I think any exceptions throw by code `import js` is not available on the Python side and leads to confusing behavior.

BTW this project is really cool! Thanks for all the hard work!

**Comment by rth** [comment]
This is now fixed, thanks to @hoodmane's work on the FFI. The example,
```py
try:
  pyodide.open_url("http://doesnotexist.abcdef/")
except Exception as err:
  print('Exception raised')
  print(type(err).__name__, err)
finally:
  print("This is printed out")
...
Exception raised
JsException NetworkError: A network error occurred.
This is printed out
```
works as expected.  Closing. Thanks for the report.
