### ISSUE TITLE
Stop including builds for pure python packages in favor of micropip

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#643]
I think it might make sense to stop including builds for pure python packages in this repo, in favor of using micropip to install them from PyPi. This would have the effect that,
 - users get latest updated version as when it's published on PyPi, without requiring additional maintenance effort for pyodide (the handling of versions in micropip might need improvement)
 - CI is slightly faster
 - package maintainers are motivated to publish universal wheels (at least if they want their package to work in pyodide)
 - generally it seems more sustainable long term.

I would also be in favor of reviewing currently listed packages and remove those that are pure python and are not required by an existing dependency with C extensions.

**Comment by teonbrooks** [comment]
@rth, is there a way to easily build a package for local deployment? the last time I tried it wasn't successful...my current use case, I have mne-python included in the supported packages and I am happy to remove it to save on CI build, however, I need the assets built from CI for a project I'm working on. Is it straightforward for local build?

**Comment by rth** [comment]
Hi @teonbrooks , for MNE you are right! For some reason I though that it used C-extensions. Since it already has a pure python wheel on PyPi (https://pypi.org/project/mne/#files), if we remove it, you will be able to just run,
```
micropip.install('mne')
```
and it should work by downloading from PyPi. The build doesn't take long,
```
rg -i building /tmp/build.txt | grep mne
[2020-07-11 12:22:51] Building package mne...
[2020-07-11 12:23:05] done building package mne in 13.9 s.
```
but it would save some work for you as you then won't need to update the version in pyodide (for instance now it's 2 versions behind). Also I noticed that occasionally the import of mne fails (likely due to the size of scipy in pyodide), so not having those false positives in the CI help.

To test that it's working as expected, you could try to pass the full URL already now,
```
micropip.install('https://files.pythonhosted.org/packages/92/ab/9b79f927b599da515335afb4b666a7bb336930a6d8345e7b483a9980a9c1/mne-0.20.7-py3-none-any.whl')
```

**Comment by rth** [comment]
@teonbrooks  After more investigation, there is a bug that prevents installing a package from PyPi if it's included in pyodide https://github.com/iodide-project/pyodide/issues/725 which makes it a bit harder to demo this.

Locally, installing mne from pypi works for mne>0.19.0 as for earlier versions there aren't pure python wheels on PyPi. However there is an issue at import time I think due to the fact that scipy version needs updating,

<details>

```py
>>> import micropip
>>> micropip.install('mne==0.19.0')
Installed scipy, numpy, mne
>>> import mne
/lib/python3.8/site-packages/numpy/ma/core.py:4467: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.shape is ():
/lib/python3.8/site-packages/scipy/linalg/special_matrices.py:845: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if kind is 'lower':
/lib/python3.8/site-packages/scipy/linalg/special_matrices.py:847: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif kind is 'upper':
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide.py", line 43, in eval_code
    exec(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/site-packages/mne/__init__.py", line 22, in <module>
    from .utils import (set_log_level, set_log_file, verbose, set_config,
  File "/lib/python3.8/site-packages/mne/utils/__init__.py", line 24, in <module>
    from .fetching import _fetch_file, _url_to_local_path
  File "/lib/python3.8/site-packages/mne/utils/fetching.py", line 14, in <module>
    from .numerics import hashfunc
  File "/lib/python3.8/site-packages/mne/utils/numerics.py", line 24, in <module>
    from .linalg import _svd_lwork, _repeated_svd, dgemm, zgemm
  File "/lib/python3.8/site-packages/mne/utils/linalg.py", line 44, in <module>
    dgesvd, dgesvd_lwork = linalg.get_lapack_funcs(('gesvd', 'gesvd_lwork'), (_d,))
  File "/lib/python3.8/site-packages/scipy/linalg/lapack.py", line 442, in get_lapack_funcs
    return _get_funcs(names, arrays, dtype,
  File "/lib/python3.8/site-packages/scipy/linalg/blas.py", line 256, in _get_funcs
    raise ValueError(
ValueError: LAPACK function dgesvd could not be found
```
</details>

Building the python wheel locally with `python setup.py bdist_wheel` and loading it from localhost also work, however MNE doesn't seem to have the v0.18.2 tag on Github and with v0.18.1 there is a `multiprocessing` import which makes the package import fail:

<details>

```py
>>> import micropip
>>> micropip.install('scipy')  # dependencies need to be installed manually in this case,
Installed scipy
>>> micropip.install('http://127.0.0.1:8000/mne-0.18.1-py3-none-any.whl')
Installed scipy, mne
>>> import mne
/lib/python3.8/site-packages/numpy/ma/core.py:4467: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.shape is ():
/lib/python3.8/site-packages/scipy/linalg/special_matrices.py:845: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if kind is 'lower':
/lib/python3.8/site-packages/scipy/linalg/special_matrices.py:847: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif kind is 'upper':
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide.py", line 43, in eval_code
    exec(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/site-packages/mne/__init__.py", line 117, in <module>
    from . import realtime
  File "/lib/python3.8/site-packages/mne/realtime/__init__.py", line 14, in <module>
    from .mock_lsl_stream import MockLSLStream
  File "/lib/python3.8/site-packages/mne/realtime/mock_lsl_stream.py", line 5, in <module>
    from multiprocessing import Process
ModuleNotFoundError: No module named 'multiprocessing'
```
</details>

Overall using MNE directly from PyPi or another URL should work, it's just necessary to have a version which will not use scipy/multiprocessing imports that failed in my attempts above. The CDN URL v0.15.0 will also keep working even if MNE is removed for v0.16+..

**Comment by teonbrooks** [comment]
sorry, i should clarify, I've been using the `.js` and `.data` from the wasm build within a electron desktop app to use mne alongside the js environment. is there to build just those explicitly without having to build the whole pyodide?

**Comment by rth** [comment]
>  I've been using the .js and .data from the wasm build within a electron desktop app

How do you load them there? Using `pyodide.loadPackage` or in some other way? I imagine you still need to load dependencies (e.g. numpy, scipy) in any case?

**Comment by rth** [comment]
That's what we are mostly doing now except for intermediary dependencies. Closing.
