### ISSUE TITLE
Use pyodide dev from CircleCI artifacts

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#648]
So each commit on master builds and stores the packages in CircleCI artifacts, e.g.

https://circleci.com/gh/iodide-project/pyodide/5623#artifacts/containers/0
which produces for instance,
https://5623-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/test.html

If we could use that, this means that we would get nightly builds for free as anyone could use the latest pyodide version from master.

Currently loading that `test.html` files produces,
```
CompileError: wasm validation error: at offset 0: failed to match magic number 
pyodide_dev.js line 337 > WebAssembly.compile:337
```
here,
https://github.com/iodide-project/pyodide/blob/c9fd3e1d572354113ca57351a09c09c872ba0f56/src/pyodide.js#L337

This doesn't seem to a MIME problem, which was the previous issue https://github.com/iodide-project/pyodide/issues/174 and was fixed in https://github.com/iodide-project/pyodide/pull/628. This might need more investigation to understand what's wrong exactly.

cc @jcaesar

**Comment by rth** [comment]
So essentially, `languagePluginUrl` needed to be set properly and then one has to use a CORS proxy to resolve cross-origin restrictions.

For instance, the following should work to get the latest pyodide version from master,
```html
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <script type="text/javascript">
       window.languagePluginUrl = 'https://yacdn.org/serve/https://5623-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/';

  </script>
  <script type="text/javascript" src="https://5623-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/pyodide_dev.js"></script>
  <script type="text/javascript">
    languagePluginLoader.then(function () {

        pythonCode = `
	    import sys
	    print(sys.version)
        `
        languagePluginLoader.then(() => {
          pyodide.runPython(pythonCode);
        })
  
    });
  </script>
</body>
</html>
```

where 
 - `5623-122663163-gh.circle-artifacts.com` is the hostname that one can find by looking in the "Artifacts" CircleCI tab of a particular commit.
 - `https://yacdn.org/serve/` is a CORS proxy prefix (see https://ovsoinc.github.io/yacdn.org/ for more details). For some reason I haven't managed to make `https://cors-anywhere.herokuapp.com/` that we use in micropip work. Of course using a third party proxy can have security concerns.

Would anyone be interested in making a PR to document this?

**Comment by jcaesar** [comment]
(Unsure what was going on with the magic number mismatch. The file wasn't actually being received and the server supplied some error document instead, I guess?)

Didn't CircleCI recently introduce a rule that build artefacts get deleted after 30 days? Would you have to regularly hit https://circleci.com/api/v1.1/project/github/iodide-project/pyodide to check for new nightlies? Or is this just intended for quick "Hey, look at what my cool PR can do" one-off kind of demos?
It might be better to get CircleCI to automatically create pre-releases on github for each commit…

**Comment by rth** [comment]
> (Unsure what was going on with the magic number mismatch. The file wasn't actually being received and the server supplied some error document instead, I guess?)

It was indeed an issue with the `languagePluginUrl` setup, resolved now.

> Didn't CircleCI recently introduce a rule that build artefacts get deleted after 30 days?

Good point, so yes this would not work as a permanent location for packages. Still it's nice to be able to experimentally run the latest version from master of a particular branch (assuming commits happen more often that every 30days :))

Thanks for mentioning their API, they have an endpoint to get the latest artifact on a branch
https://circleci.com/api/v1.1/project/github/iodide-project/pyodide/latest/artifacts?branch=master&filter=successful
but right now it shows those from the benchmark job (which is indeed the latest to generate artifacts). We might want to re-publish build artifacts in this job as well if we want to use it.

It would be nice to document this somehow maybe under contributing section of the doc.

> It might be better to get CircleCI to automatically create pre-releases on github for each commit…

Yes, I agree we could publish pre-releases from time to time  e.g. once a month (not sure there are enough commits on master to do this more frequently, and also to avoid cluttering history). We could use a cron job https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow to do it.
