### ISSUE TITLE
Binary wheels for pyodide?

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#655]
There was earlier discussion about this in https://github.com/iodide-project/pyodide/issues/38 and https://github.com/iodide-project/pyodide/issues/344 but I think it could be useful to have a separate issue to discuss what binary wheels for pyodide could look like.

Python wheels are basically just zip files with the package contents, see [PEP 427](https://www.python.org/dev/peps/pep-0427/). We are currently already supporting pure python wheels.

We could also consider trying to build wheels for packages that have C extensions. I'm not exactly sure what would be necessary on the technical side to make it work, and run the wasm binary through the compiler when the modules are loaded. That would require more investigation, and it could be a blocker, but I imagine it could be made to work. 

For instance a numpy wheel could be,
```
 numpy-1.4.0-py37-pyodide015-wasm.whl
```
where the latter two parts are the binary ABI and the platform.

**Advantages**
 - wheels have already a clear spec, deal with ABI compatibility and are natural for python users.
 - I think they could be distributed through PyPi (or any other 
warehouse / PyPi index). If the platform tag is not supported now, I wouldn't likely be too difficult to support it.
 - Because it's just a zip file, it should be relatively easy to repackage a set of wheels into one or strip unused parts for a given project (without dealing with emscripten side of things at all).
 - They might make package building a bit more sustainable, because we would have to deal less with it in pyodide, and users can do it and distribute results independently.
 - One file per package to download instead of two (`.js` + `.data`).
 
**Disadvantages**
 - it puts stronger constraints on ABI compatibility, meaning that we cannot make releases every other month that breaks compatibility (or in particular update emscripten). That's certainly not ideal, and we considered it a blocker in the past, https://github.com/iodide-project/pyodide/issues/344 but we do have to start to deal with it at some point in any case probably.
 - in particular, it likely means we cannot make releases too often. For the situation with PyPy wheels https://github.com/antocuni/pypy-wheels is a relevant reference.
 - related to the previous point, it makes re-generation of a full distribution more difficult, as one has lots of distinct packages.
 - I'm not sure that a zip format is ideal for the web, but at the same time we do need some container to distributes multiple files in a python package.

Again I'm not saying that we should migrate to using wheels, but it could be interesting to consider what would be necessary to make it work.

**Comment by hzhangxyz** [comment]
I close (#1971). To avoid nobody finds this, I post an empty comment here.

**Comment by hoodmane** [comment]
I got it to build wheels by changing the following in pywasmcross:
https://github.com/pyodide/pyodide/blob/075116857f68e06259da39cae4ee10742ea8123c/pyodide-build/pyodide_build/pywasmcross.py#L422
```diff
     commands = [
         sys.executable,
         "setup.py",
-        "install",
+        "bdist_wheel",
         "--skip-build",
-        "--prefix=install",
-        "--old-and-unmanageable",
     ]
```
It crashes inside of `package_files` but then there is a wheel in `packages/<pkg_name>/build/<pkg_name>/dist` (with incorrect platform tag `linux_x86_64`. I copied this into `build`, downloaded it, and unpacked it with `micropip.micropip._extract_wheel` (which just extracts it as a zip file into `WHEEL_BASE` directory).

On import, it works correctly if the `.so` files are small enough. If they are too large, then import on main thread will throw because it's not allowed to synchronously instantiate large wasm modules on the main thread. It should be possible to apply preload plugins to get the info into `Module.preloadedWasm`. We have to be careful about this because it happens asynchronously. We don't want someone to try to import the package between when the files are unpacked and when the wasm is instantiated, because that would raise weird errors. Probably the best idea is to first unpack into a temp directory, then preload any wasm, then when preloading is done, move into the `site-packages` directory. But then we also need to make sure to fix up any paths in the `Module.preloadedWasm` index.

**Comment by rth** [comment]
Nice that it works with minimal changes!

It could be interesting to make the build system optionally produce wheels.  Maybe something like,
```
PYODIDE_PACKAGE_FMT='wheel' PYODIDE_PACKAGES='numpy' make
```
As a side note, I really don't like the CLI user experience with `make`, I would have very much preferred,
```
pyodide build --output-format wheel numpy
```
but currently, that would mean wrapping make into another subprocess call.

> It should be possible to apply preload plugins to get the info into Module.preloadedWasm. We have to be careful about this because it happens asynchronously

yes, I imagine we should be able to do the equivalent of what [we do in loadPackage](https://github.com/pyodide/pyodide/blob/263309102d8158d82d051d0f3d4bbf7a4505c52a/src/pyodide.js#L318) about it, but for micropip

**Comment by rth** [comment]
An issue with wheels, is that they are only for Python packages not shared C libraries. So for instance in the case of BLAS which we load as a separate package, numpy and scipy would bundle it inside each of their wheels for x86-64. For us, that would clearly make things more complex. If we don't do it, that would mean you still need Pyodide packages for shared C libraries and maybe it's OK.

**Comment by hzhangxyz** [comment]
I agree, Currently `make` style build is not so beautiful

> As a side note, I really don't like the CLI user experience with `make`, I would have very much preferred,
> 
> ```
> pyodide build --output-format wheel numpy
> ```

Could it be a possibility that we could build package inside package folder? because in linux/windows, we build packages in this way. e.g: `python xxx/pyodide_build/setup_wrapper.py ./setup.py bdist_whell`, which allows users to execute commands in `meta.yaml` manually.

**Comment by hoodmane** [comment]
> As a side note, I really don't like the CLI user experience with `make`, I would have very much preferred,
> ```
> pyodide build --output-format wheel numpy
> ```

Yeah the current system sucks. I spent a lot of time being confused about this when I first tried to use the build system.

> but currently, that would mean wrapping make into another subprocess call.

Maybe worth it for improved user experience, though when trying to understand what the code does having all those nested subprocess calls can be a bit mind warping.

> I imagine we should be able to do the equivalent of what we do in loadPackage about it, but for micropip

I think it's actually simpler -- we just need to run the preload plugin, I don't think we need to modify it in this case. Not sure.

**Comment by rth** [comment]
Returning on the subject, right now uploading such wheels to PyPi is unsupported. 
```
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
Binary wheel 'pyodide_test_wheel-2.2.0-cp39-pyodide18-emscripten_wasm32.whl' 
has an unsupported platform tag 'emscripten_wasm32'.
````
Opened https://github.com/pypa/warehouse/issues/10416 to see what would be necessary to support it.

**Comment by hoodmane** [comment]
We need further investigation into ABIs related to fp casting anyways. We eventually need some sort of ABI tagging.
I think it would be sufficient for our future needs to have an ABI tag of the form `major.minor` where the `major` tag has to exact match and the `minor` number is forwards compatible but not backwards compatible. So e.g., a package of ABI `2.2` could be used on a Pyodide with ABI version `2.5` but not on a Pyodide with ABI `2.1` (package ABI has to be behind Pyodide ABI) or `3.0` (major version must match exactly).

**Comment by rth** [comment]
> We eventually need some sort of ABI tagging.

Yes, that's something we need to carefully define. It might be good to read the manylinux PEPs to see what are the relevant things to keep in mind for wheels. Though in our case it's likely in large part dependent on Emscrpten ABI compatibility guarantee, which is non-existant ..
> https://emscripten.org/docs/introducing_emscripten/release_notes.html
> Note that there is *no* ABI compatibility guarantee between versions - the ABI
may change, so that we can keep improving and optimizing it.

Though likely they don't break the ABI that often, at least for the things we would use.
