### ISSUE TITLE
issue with import the another python file.

### ISSUE THREAD

**Issue by preetiverma525** [pyodide/pyodide#675]
Hi ,

I am having issue with  import the another python file.

Ex - python_config.py 

data = {
"Table_ID": 'ftyi',
"Record_RID" : '3',
"Initiative Title" : '6',
"Status" : '7',
"Progress" : '8'
}

another file --- python.py 

i need to import the python_config inside the python.py  
i am using below code.

import python_config 

but i am getting below error.

![image](https://user-images.githubusercontent.com/59359938/83172068-a8c3d880-a134-11ea-88ae-b835cea27e95.png)

**Comment by rth** [comment]
What is the `config_data` module? Is it your module or a module in one of the dependencies?

In terms or python imports, pyodide does nothing special. So you just need to be sure the module you are trying to import is in the `sys.path` (or installed via `micropip`).

**Comment by preetiverma525** [comment]
Hi Roman,

config_data.py file has data in dictionary where define the parameter only.

  config_data.py

data = {
"Table_ID": 'bgty',
"Record_RID" : '3',
"Initiative Title" : '6',
"Status" : '7',
"Progress" : '8'
}
main_python_file.py

i used the data inside the  main_python_file.py

i used----  from  config_data import * or from config_data import data or
import config_data

all are not working

when i tried with micropip.install('config_data') its also not working.

**Comment by preetiverma525** [comment]
Hi Roman,

I have used   below code to install the
pyodide.loadPackage(['matplotlib','pandas','micropip']).then(() => {
         pyodide.runPython(pythonText);
         pyodide.runPython(`plt.show()`)
          document.getElementById("textfield").innerText =
pyodide.globals.df;


and used import micropip in the python file.

import micropip
micropip.install(' python_config  ') ---- anther python file which i used
to import the data in main python file
import python_config

but i am getting below error.

[image: image.png]

could you please help me



print('hello')




         });

**Comment by rth** [comment]
You can't use `micropip` on a python file (unless it's a Python wheel?). I would suggest you use the REPL (`console.html` file) to find the location of your `python_config` file (e.g. using `os.listdir` etc) then add it to sys.path to make the import work.

**Comment by preetiverma525** [comment]
can you please  elaborate more as i am implementing the pyodide one tool
where i created one htm page  and  2 python file and from html i am calling
python file.

please see below code.

<!doctype html>
<meta charset="utf-8">
<html>
<head>
    <title>Demo</title>
    <script src="https://pyodide.cdn.iodide.io/pyodide.js"></script>
    <script src="
https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>
</body>
<script  type="text/javascript">
      $(document).ready(function(){
pythonText="";
$.ajaxSetup({async:false});
docURL="?a=dbpage&pageName=python_pyodide_data_conf.py";  /// my python
file
$.get(docURL,function(data){
pythonText=data;
});
alert(pythonText);

languagePluginLoader.then(() => {
          console.log(pyodide.runPython('import sys\nsys.version'));

         pyodide.loadPackage(['matplotlib','pandas','micropip']).then(() =>
{
         pyodide.runPython(pythonText);
         document.getElementById("figure").src = pyodide.globals.img;


         });
        });
 });

</script>
<div id="heading" style="font-size:30px;" align="middle"></div>
<div id="textfield"></div>
<div><img id="figure" align="middle" /></div>
</html>

html page name -- Pyodide_data_conf.html
 first python file name ---python_pyodide_data_conf.py
second python file name --python_config.py

all the file inside the tool so from tool how can i use  import the another
python file do i give the complet page url ?

if you have code so can you please share as i am stuck in the middle.

**Comment by rth** [comment]
@preetiverma525 See https://github.com/iodide-project/pyodide/issues/679#issuecomment-637504864 for a more complete answer. There is currently no example for doing this as far as I know but we should add it.

**Comment by preetiverma525** [comment]
okay

Why pyodide is too slow on chrome.?

**Comment by phorward** [comment]
@preetiverma525 please check out our [pyodide-app-stub](https://github.com/mausbrand/pyodide-app-stub) project, I think this is exactly what you are looking for.

**Comment by Puneet-Bajaj-IITM** [comment]
> You can't use `micropip` on a python file (unless it's a Python wheel?). I would suggest you use the REPL (`console.html` file) to find the location of your `python_config` file (e.g. using `os.listdir` etc) then add it to sys.path to make the import work.

hi sir
I used this and have added my file buy i am getting a issue

--------------- mymodule.py------------------

def hello():
    print("famu is here")
    return "ubaid is here"

----------------app. py----------------------------

from mymodule import hello

a = hello()
print(a)

--------------------console----------------------
ubaid is here

I dont get output of print statement from inside the hello function

But when i use 
import mymodule

I get both in output

Please help me with this

**Comment by agriyakhetarpal** [comment]
Hi @Puneet-Bajaj-IITM, your function `hello` when called using `hello()` and assigned to a variable `a` will just print what is in the `return` statement of the function. The `print` and the `return` statements work differently in Python, `print` will just display things to the console which won't be captured, while `return` will be what the function will either display to the console or pass to what is calling it, in this case, `a`.

This is because `print()` writes to the standard output stream, which is typically buffered. When the `return` statement is encountered, the function exits immediately without flushing the buffer, so the output is never displayed if you don't capture it.

For further reading, here are some resources for you:

- Python's official tutorial on modules: https://docs.python.org/3/tutorial/modules.html
- https://docs.python.org/3/reference/simple_stmts.html#return
- https://realpython.com/python-return-statement/

**Comment by agriyakhetarpal** [comment]
Since this is more than four years old at this point, and is not directly related to Pyodide's functionality but more about how Python imports/files/modules work, I think we can close this for now. Tools that use Pyodide such as JupyterLite offer such functionality where one can import methods from and work with multiple files.
