### ISSUE TITLE
TypeError: resolveSymbol(...) is undefined when using scipy

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#677]
When using the following examples with scipy on master,
```py
>>> import scipy.stats as sps
>>> sps.linregress([0, 1, 2, 3], [3, 3, 2, 5])
TypeError: resolveSymbol(...) is undefined
```
the above error is raised. This earlier produces another error as reported in https://github.com/iodide-project/pyodide/issues/507#issuecomment-633517293 that was likely fixed by updating to emscripten 1.38.31.

It's not clear from the error message which symbol is undefined.

**Comment by matham** [comment]
Hmm, it seems this is actually still the original issue. In the [PR](https://github.com/emscripten-core/emscripten/pull/8431/files#diff-6d4bb79610683d9749d2cbb62e708d88L444-R481) that I thought they "fixed" the issue, it seems they simply changed the code so the error is slightly different, but it's still the same cause (whatever that is).

**Comment by hoodmane** [comment]
I'm pretty sure this is resolved now.
