### ISSUE TITLE
Running package test suites

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#69]
In the case of numpy, for instance, [`test_numpy.py`](https://github.com/iodide-project/pyodide/blob/master/test/test_numpy.py) looks very succinct. Is there any   information about how much of the numpy internal test suite passes? (Even if it can't be run at each build due to run times..)

Actually, what would be necessary to run the test suite (assuming it uses Pytest) of a Python package from pyodide?

**Comment by mdboom** [comment]
The Python core is already being tested in this way (using stdlib `unittest`, not anything fancier).  That certainly could (and should) be adapted to run the package test suites as well.

The biggest annoyance with the core test suite was the number of tests that fire off subprocesses to do their work (which obviously can't be done in WebAssembly).

**Comment by rth** [comment]
Looking at `test_python.py:pytest_generate_tests` as far as I understand currently a list of test modules is created with `make_test_list.py`, then each is executed with `selenium.run("test.libregrtest.main([<module_path>])")`.

For projects that use pytest, such approach would be problematic because we would need to parse the per package `conftest.py` etc. I wonder if the simplest approach might be to run pytest collection & evaluation inside selenium. For instance, to run numpy tests, one could do,
```py
def test_numpy_suite(selenium):
   selenium.load_package('pytest')
   selenium.run("import pytest;"
                 "pytest.main(['--pyargs', 'numpy'])")
```

I'm hoping this might also be faster than calling `selenium.run` for each included test as well.

Opened a PR to package pytest in https://github.com/iodide-project/pyodide/pull/95

I'm not sure yet, whether this nested use of pytest might be problematic.

**Comment by mdboom** [comment]
It would be great to run the whole test suite like this, but it would be nice to somehow turn each test in the internal testing to a test at the pyodide test level.  I don't know if that's possible.  At a minimum, we'll want it to display progress to the console as it goes or tools like Circle-CI will assume it's dead and kill it.

**Comment by rth** [comment]
> It would be great to run the whole test suite like this, but it would be nice to somehow turn each test in the internal testing to a test at the pyodide test level.

I wonder if it's possible to use or adapt pytest-xdist for this. For instance, one could imaging running an pytest inside WASM environment, that would communicate with pytest run from the host system: unless I'm mistaken may not be that different from remote/distributed testing.

**Comment by mdboom** [comment]
That seems like a promising approach, but I know nothing about any of the details... :)

**Comment by rth** [comment]
The full output of the numpy 1.15.1 test suite can be found below,
 - using Firefox 64.0a1: [numpy-test-suite-firefox-1.log](https://github.com/iodide-project/pyodide/files/2374869/numpy-test-suite-firefox-1.log)
 - using Chrome 2.41.578700: [numpy-test-suite-chrome-1.log](https://github.com/iodide-project/pyodide/files/2374868/numpy-test-suite-chrome-1.log)

because of https://github.com/iodide-project/pyodide/issues/158 that kills the interpreter without ability to recover, I was not able to run the test suite fully in one time, instead a setup where tests were collected in one selenium instance, and then a new selenium instance was used for each test file. Essentially this is similar to how CPython tests used to work (except that is supports all the pytest related fixtures etc).

The (somewhat convoluted) pytest setup used to produce these results can be found below,
<details>

```py
import re
import pytest
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

from conftest import FirefoxWrapper

package_name = 'numpy'
chunk_size = 1  # number of test files to run within a selenium instance
n_chunks = 114  # number of chunks to run all the tests
                # if too large the remaining ones will be skipped


@pytest.fixture(scope='module')
def collect_files():
    selenium = FirefoxWrapper()
    selenium.load_package(['pytest', 'nose'])
    selenium.load_package(package_name)
    selenium.run(
            f"""
             from pathlib import Path
             import {package_name}
             import pytest
             import os

             base_dir = Path({package_name}.__file__).parent
             """)
    base_dir = selenium.run("str(base_dir)")

    output = selenium.run(
            """
            import io
            import contextlib

            fh = io.StringIO()
            with contextlib.redirect_stdout(fh):
                pytest.main(['--continue-on-collection-errors',
                             '--collect-only', '-q',
                             base_dir])
            fh.getvalue()  # return collected test nodes
            """)

    selenium.driver.quit()

    with open(f'{package_name}-test-suite.log', 'wt') as fh:
        fh.write(output)
        fh.write('\n'*3)

        # from the raw stdout filter out elements that look like test nodes
        test_nodes = [path for path in output.splitlines()
                      if re.match('^[\w:/\.]+$', path) and 'test' in path]
        test_files = list(sorted(
            set(path.split('::')[0] for path in test_nodes)))

        fh.write(f'Collected {len(test_nodes)} tests, in {len(test_files)} files')  # noqa
        fh.write('\n')

    return base_dir, test_files


@pytest.mark.parametrize('n_chunk', range(n_chunks))
def test_run_testsuite(selenium_standalone, collect_files, n_chunk):
    from pathlib import Path

    base_dir, test_files = collect_files

    selenium = selenium_standalone
    selenium.load_package('pytest')
    selenium.load_package('nose')
    selenium.load_package(package_name)

    if chunk_size*n_chunk > len(test_files):
        pytest.skip('All tests run')

    with open(f'{package_name}-test-suite.log', 'at') as fh:
        print(f'running n_chunk={n_chunk}')

        # convert test nodes to file paths
        test_files_slice = test_files[
                        n_chunk*chunk_size:(n_chunk+1)*chunk_size]

        test_files_str = ', '.join(
                "'{}'".format(str(Path(base_dir) / path))
                for path in test_files_slice)

        fh.write(f'Running chunk={n_chunk}\n')
        fh.write(f'Tested files: {test_files_str}')
        try:
            output = selenium.run(
                f"""
                 import io
                 import contextlib
                 import pytest

                 fh = io.StringIO()
                 with contextlib.redirect_stdout(fh):
                      pytest.main(['--continue-on-collection-errors', '-v',
                                  {test_files_str}])
                 fh.getvalue()  # return test results
                 """)
            fh.write(output)
        except:
            fh.write('Exception raised')
            fh.write(selenium.logs)
        n_chunk += 1
```

</details>

Overall similarly to previous results, the output is quite promising. Below are the most recurrent themes (I opened a separate issues for some of these),
 - all tests related to `numpy.f2py` currently fails, but they don't makes sens in pyodide and we should skip them.
 - RuntimeError: float unrepresentable in integer range (cf https://github.com/iodide-project/pyodide/issues/158): this is a blocker, that currently prevents me from running the test suite in one call as it makes the interpreter crash.
 - Issues with errors/warnings not raised when they should be: https://github.com/iodide-project/pyodide/issues/156
 - Issues with numerical precision in floats: https://github.com/iodide-project/pyodide/issues/157
 - Issues with complex dtypes: https://github.com/iodide-project/pyodide/issues/159
 - and there are tests that could not be collected due to an import of `multiprocessing`, `mmap` or `ctypes`: a more general solution might be provided in https://github.com/iodide-project/pyodide/issues/144

Overall the results are looking fairly good though.

**Comment by rth** [comment]
> I wonder if it's possible to use or adapt pytest-xdist for this

FWIW, asked a question about it at https://github.com/pytest-dev/pytest-xdist/issues/336: there doesn't seem to be too much enthusiasm about it so far.

I think a blocker there is to have some way to communicate between the CPython in WASM, and CPython in the terminal, for instance as part of the [execnet](https://codespeak.net/execnet/) package they use in the backend. At the very least it might require having some (web)socket or comparable functionality working. Probably a fun project, but likely a bit out of scope.

**Comment by rth** [comment]
We now have lots of CI resources from GH Actions and Azure Pipelines. What we could do is to setup a manually triggered job to run package test suites, then open new issues for failures.

**Comment by agriyakhetarpal** [comment]
In other words, @rgommers and I are working on improving out-of-tree builds for a lot of the Scientific Python packages now, so if this is still meant to be kept open for a while then I can remember to post updates here to track things.

**Comment by ryanking13** [comment]
Yes, we already do simple package testing, and since our goal is not to do full package testing within the Pyodide repository, so I think we can close this issue.

Thanks for improving out-of-tree build support for scientific packages @agriyakhetarpal!
