### ISSUE TITLE
Python-object is not garbage collected when used with EventListener

### ISSUE THREAD

**Issue by phorward** [pyodide/pyodide#693]
Hi!

I have a special case here regarding garbage collection in combination with JavaScript's addEventListener and removeEventListener functions.

1. Creating an instance of a class, associating it with a DOM element and removing it again works - the object is entirely freed.
2. Creating an instance of a class, associating it with a DOM element, attaching an event to it and detaching it immediately after still holds a reference to it the object, even if it is explicitly removed with `del`

I guess, that the problem here is in JavaScript, which still holds a reference and this is normal with JavaScript. But I'm quite unsure, and would like to ask for further investigation, eventually its really a bug.

Test case is this Python script. Attached is [bug.txt](https://github.com/iodide-project/pyodide/files/4834270/bug.txt)
 to be renamed bug.html, which can be copied into the `build/` folder and directly be executed.

```python
from js import document
import weakref, gc

print("start")

class TestWrapper:
    def __init__(self):
        super().__init__()
        self.div = document.createElement("div")

    def testCallback(self, event):
        print("Got Event")

    def attach(self):
        print("attach")
        self.div.addEventListener("click", self.testCallback)

    def detach(self):
        print("detach")
        self.div.removeEventListener("click", self.testCallback)

    def __del__(self):
        print("I am removed")

print("---111---")

div = TestWrapper()
rw = weakref.ref(div)
gc.collect()
print("1 Weakref resolves to: %s" % rw())
del div
gc.collect()
print("1 Weakref after dropped reference resolves to: %s" % rw())  # << this is None, as expected!

print("---222---")

div = TestWrapper()
rw = weakref.ref(div)
div.attach()
del div
gc.collect()
print("2 Weakref to Wrapper-Class with active event listener: %s" % rw())
rw().detach()
gc.collect()
print("2 Weakref to Wrapper-Class with removed event listener: %s" % rw())  # << At least this should be None
```

The logging output in the JavaScript console is this:
```
Python initialization complete
start
---111---
1 Weakref resolves to: <TestWrapper object at 0x9a8a60>
I am removed
1 Weakref after dropped reference resolves to: None
---222---
attach
2 Weakref to Wrapper-Class with active event listener: <TestWrapper object at 0x9a8a60>
detach
2 Weakref to Wrapper-Class with removed event listener: <TestWrapper object at 0x9a8a60>
```

It can be reproduced both in Firefox 77.0.1 and Chromium Version 83.0.4103.97

**Comment by rth** [comment]
Hmm, interesting. We are currently [skipping weakref unit tests](https://github.com/iodide-project/pyodide/blob/2f2ed8fc261ad9a054bdf0692b13cccc64843834/test/python_tests.txt#L516) due to threading, but maybe some other things are not working there.

**Comment by phorward** [comment]
Hi, 
I think this is a huger problem, because it is not that solvable so easily. The JavaScript world collides here with the Python-world, because it handles garbage collection differently and there is no event triggered when an object is really freed.

During my examination of this bug, I found out that the reference counter is always incremented each time python2js is called and the object test yield in a PyProxy. The PyProxy is internally re-used if it already exists, so there _is_ only one reference on it. This will be fixed with #708. 

Pull request #707 introduces a key recycling for hiwire - this must not be necessary, but I think it is useful and should increase the total runtime of a Pyodide-based site that is used for a longer time without reload.

For now, these pull requests don't fix the problem, but they slightly improve Pyodide's object referencing in general.
Together with a coworker, we came to result that the only way to handle this might be to perform reference counting stuff in case specific JavaScript functions like addEventListener, removeEventListener, setTimeout and setInterval are triggered. But I will do further considerations on this. There might also be a solution when using the upcoming [JavaScript WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) feature, but this required a further loop that needs to be invoked at runtime to clean-up removed objects.

**Comment by phorward** [comment]
Here's another test.html I used for debugging and experiments.

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <script src="./pyodide_dev.js"></script>
  </head>
  <body>
    <script>
      function jstest(p) {
        console.log("jstest", p);
        try {
          p()
        } catch(e) {
          console.log("jstest is not callable!");
          console.exception(e);
        }
      }

      languagePluginLoader.then(() => {
        pyodide.runPython(`
import sys, weakref, gc
from js import jstest, document
#jstest(42);

def pytest(*args, **kwargs):
  print("pytest", args, kwargs)

ref = weakref.ref(pytest)

jstest(pytest)
print(sys.getrefcount(ref()))

document.addEventListener("click", pytest)
#document.removeEventListener("click", pytest)

print(sys.getrefcount(ref()))

del pytest
gc.collect()
print(ref())
`)
      });
    </script>
  </body>
</html>```

**Comment by hoodmane** [comment]
Doesn't [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) do exactly what we want? It's supported on modern versions of chrome, firefox, and edge too. Should be easy to feature gate this too, in any browser without `FinalizationRegistry` we can just fall back to leaking python objects referenced from javascript.

**Comment by rth** [comment]
Closing as resolved in https://github.com/pyodide/pyodide/pull/1306. Please comment if it's not the case.
