### ISSUE TITLE
Restart pyodide and clear user defined variables

### ISSUE THREAD

**Issue by therealadityashankar** [pyodide/pyodide#703]
Hey !

I'm currently using pyodide to build a project and realized that pyodide uses only one interpreter throughout its lifetime

a really neat option would be to be able to do `pyodide.reset()` that clears any new variables, the implementation would be really simple as all you'd have to do is clear globals()

**Comment by rth** [comment]
Ipython has something [similar](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-reset). We could try to implement it, but I'm not sure it's as simple as clearning globals. Global namespace does start with some objects so we need to preserve those.

For instance, Pyodide CLI at init starts with,
```
>>> print(list(globals()))
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__annotations__', '__builtins__', '__build_class__', '__import__', 'abs', 'all', 'any', 'ascii', 'bin', 'brea
kpoint', 'callable', 'chr', 'compile', 'delattr', 'dir', 'divmod', 'eval', 'exec', 'format', 'getattr', 'globals', 'hasattr', 'hash', 'hex', 'id', 'input', 'isinstance', 'issu
bclass', 'iter', 'len', 'locals', 'max', 'min', 'next', 'oct', 'ord', 'pow', 'print', 'repr', 'round', 'setattr', 'sorted', 'sum', 'vars', 'None', 'Ellipsis', 'NotImplemented'
, 'False', 'True', 'bool', 'memoryview', 'bytearray', 'bytes', 'classmethod', 'complex', 'dict', 'enumerate', 'filter', 'float', 'frozenset', 'property', 'int', 'list', 'map',
 'object', 'range', 'reversed', 'set', 'slice', 'staticmethod', 'str', 'super', 'tuple', 'type', 'zip', '__debug__', 'BaseException', 'Exception', 'TypeError', 'StopAsyncItera
tion', 'StopIteration', 'GeneratorExit', 'SystemExit', 'KeyboardInterrupt', 'ImportError', 'ModuleNotFoundError', 'OSError', 'EnvironmentError', 'IOError', 'EOFError', 'Runtim
eError', 'RecursionError', 'NotImplementedError', 'NameError', 'UnboundLocalError', 'AttributeError', 'SyntaxError', 'IndentationError', 'TabError', 'LookupError', 'IndexError
', 'KeyError', 'ValueError', 'UnicodeError', 'UnicodeEncodeError', 'UnicodeDecodeError', 'UnicodeTranslateError', 'AssertionError', 'ArithmeticError', 'FloatingPointError', 'O
verflowError', 'ZeroDivisionError', 'SystemError', 'ReferenceError', 'MemoryError', 'BufferError', 'Warning', 'UserWarning', 'DeprecationWarning', 'PendingDeprecationWarning',
 'SyntaxWarning', 'RuntimeWarning', 'FutureWarning', 'ImportWarning', 'UnicodeWarning', 'BytesWarning', 'ResourceWarning', 'ConnectionError', 'BlockingIOError', 'BrokenPipeErr
or', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionRefusedError', 'ConnectionResetError', 'FileExistsError', 'FileNotFoundError', 'IsADirectoryError', 'NotADirecto
ryError', 'InterruptedError', 'PermissionError', 'ProcessLookupError', 'TimeoutError', 'open', 'quit', 'exit', 'copyright', 'credits', 'license', 'help', 'sys', 'io', 'code', 
'term', 'pyodide', 'Console', '_c'
```
while a regular python interpreter starts with,
```
>>> print(list(globals()))
 ['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__annotations__', '__builtins__']
```

I'm not sure why all builtins are pyodide globals but that's not the case for a regular interpreter.

Would you be interested in investigating and proposing a PR @therealadityashankar?

**Comment by therealadityashankar** [comment]
@rth is it okay if I modify `pyodide/src/pyodide.js` instead of its C++ bindings, cause I suck at c++

I realized I'd need some additional functionality, so I'd modify it to have variable "namespaces" instead, I'd do this by continuously modifying `globals()` to change the variables it composes of,

I'll totally propose a PR, if the above is okay

**Comment by therealadityashankar** [comment]
also, is there a pyodide chat group ?

**Comment by phorward** [comment]
hi, there is a Gitter group here: https://gitter.im/iodide-project/iodide

**Comment by rth** [comment]
> I'd modify it to have variable "namespaces" instead, I'd do this by continuously modifying globals() to change the variables it composes of, so it can behave as if there are multiple python interpreters instead on 1 interpreter, even though everything is running in one python interpreter

Reseting globals with a standalone function in `src/pyodide.py` would be fine, but that sounds more complicated and less standard. I'm not sure that we would be able to accept it in pyodide (though you can certainly do it in your application).

**Comment by rth** [comment]
I think the best approach would be to either,
 - keep track of user defined variables in `pyodide._user_ns` dict, similarly to what IPython is doing with [`shell.user_ns`](https://github.com/ipython/ipython/blob/3587f5bb6c8570e7bbb06cf5f7e3bc9b9467355a/IPython/core/magics/namespace.py#L555) (though I have not looked in detail how they do it, and whether it would be possible for us)
 - or store the initial list of variables in `globals()` at pyodide init, then remove all variables added by the user during the reset.

That would be a start. Next we could try to also reset `sys.modules` and `sys.path` to the initial state, so that imports needs to be done again.

cc @casatir

**Comment by therealadityashankar** [comment]
closing this issue, as the answer by @rth is satisfactory for me, and is exactly how I implemented it in my project https://github.com/vanillawc/wc-code

**Comment by seanyeh** [comment]
I've been following this issue for a while - Is this a feature that could eventually be added to pyodide? If so, maybe we should keep this issue open. I will also take a look at the suggested approach when I get the chance

**Comment by hoodmane** [comment]
I think this issue should be reopened as well.

**Comment by hoodmane** [comment]
One option would be to restart the entire python interpreter with `Py_FinalizeEx()` and `Py_InitializeEx()`. The docs about `Py_FinalizeEx` suggest that this approach may leak some memory (but we already leak tons of memory so...).

**Comment by hoodmane** [comment]
In the prerelease (to be version 0.17) you can also just do 
```
let dict = pyodide.pyimport("dict");
pyodide.runPython(code, dict());
``` 
directly to prevent variable definitions from persisting.

**Comment by rth** [comment]
Closing as anwered.
> However, if the code changes values stored in modules, those changes will persist.

Yes, changes in modules may persist (unless you somehow track those changes and revert them). The only way to fully reinitialize the runtime is to load a new Pyodide instance, but that's much more costly.

**Comment by Waf1leCodes** [comment]
I just run a simple python script that removes all the global variables. It works for me although I haven't tested it much.

pyodi```
de.runPython(`\
for variable in dir():
    if variable[0:2] != "__":
        del globals()[variable]

del variable
`
```

**Comment by whitequark** [comment]
I think this should be:

```
let dict = pyodide.globals.get('dict');
pyodide.runPython(code, dict());
```
