### ISSUE TITLE
TST Test failures with firefox 71+

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#716]
While investigating https://github.com/iodide-project/pyodide/pull/622 tests seems to work for firefox 70 and earlier, but fail for 71 with "maximum recursion depth exceeded" error for several tests, e.g.
```
ERROR: test_extended_arg (test.test_compile.TestSpecifics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lib/python3.7/test/test_compile.py", line 128, in test_extended_arg
    exec(code, g)
RecursionError: maximum recursion depth exceeded during compilation
```
(full log in https://app.circleci.com/pipelines/github/iodide-project/pyodide/155/workflows/7834847f-a815-4300-b716-3f0dd5b28b99/jobs/6467/steps)

This also happened some time ago in Chrome (https://github.com/iodide-project/pyodide/issues/108). Maybe it's a matter of some default settings changing in Firefox, and there might be some workaround. For instance increasing [`TOTAL_STACK` value in emscripten](https://github.com/emscripten-core/emscripten/blob/49029d44cbef0f535fcd48445300808c7efbdb10/src/settings.js#L113) could be worth a try.

To reproduce this, build cpython within the docker container e.g.
```
PYODIDE_PACKAGES="micropip" make
```
then run,
```
pytest -k firefox tests/test_core_python.py
```
and verify that it passes.
Update firefox with instructions in https://github.com/iodide-project/pyodide/blob/bcc4f6b521e65d4a52984dbb9ae9c7eb3c1d76c2/Dockerfile#L18-L21 and the same test would fail.

**Comment by sylvain-ri** [comment]
Small input, just ran the core tests `pytest -k firefox src/tests/test_core_python.py`

> To reproduce this, build cpython within the docker container e.g.
> 
> ```
> PYODIDE_PACKAGES="micropip" make
> ```
> 
> then run,
> 
> ```
> pytest -k firefox tests/test_core_python.py
> ```

```
======================================================================= test session starts ========================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /src/sylvain-pyodide, configfile: setup.cfg
plugins: forked-1.3.0, asyncio-0.15.1, xdist-2.3.0, rerunfailures-10.1, hypothesis-6.14.2, cov-2.12.1, httpserver-1.0.0, instafail-0.4.2
collected 1581 items / 1054 deselected / 527 selected

src/tests/test_core_python.py x.x.x........xxxxxxxxxxxx.xxsxxx.xxxx.x..x..x.............x.x.................................xx......x.xx.........x..x....... [ 23%]
.....xx.xx..x.....x.........xx...........x....x..x.....x.x........x.x...x.x......x......sx.x.x...xx.....................x.........x....x..s................. [ 53%]
....x.x..xx....xx...xx.x.....x............x..x...x...xx.....x.xx..x.xxx.sx........xx.x.xx.x.x.xx...xxx.x...ss....x.x..x.....x.x....x...x.........x...x.xx..x [ 83%]
.xx.xxxxx.................x................x....sxx..........xxxx.x.x.........x..........                                                                    [100%]

========================================================================= warnings summary =========================================================================
src/tests/test_core_python.py::test_cpython_core[test___all__-firefox]
  /usr/local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py:182: DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg
    RemoteWebDriver.__init__(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================= 392 passed, 7 skipped, 1054 deselected, 128 xfailed, 1 warning in 386.29s (0:06:26) ========================================
```

**Comment by hoodmane** [comment]
That looks like it succeeded -- 392 pass, 128 xfail. @rth I think this issue should be closed?

**Comment by rth** [comment]
Sure. Thanks for investigating @sylvain-ri !
