### ISSUE TITLE
ctypes support

### ISSUE THREAD

**Issue by lambertwx** [pyodide/pyodide#728]
Is there a plan to enable the `ctypes` library in pyodide?  I'd like to use it to call from my pyodide python code into a WebAssembly.  Alternatively, is there some other mechanism I can use to call into a WebAssembly?

Here's why I ask.  I am trying to get shapely, a popular Python package for computational geometry, running in the pyodide environment.  It is a wrapper around the C GEOS library.  I'm able to compile GEOS to a WebAssembly, and to load the shapely package into pyodide.  However, shapely uses the ctypes library when it calls the GEOS functions, and pyodide doesn't seem to support ctypes, so I get runtime errors.  

E.g., if I give pyodide the line `from ctypes import pointer, c_size_t, c_char_p, c_void_p`, I get a `ModuleNotFoundError: No module named 'ctypes'`

The specific pieces of ctypes that shapely uses are byref, cast, c_byte, c_double, c_int, c_uint, c_char_p, c_size_t, c_void_p, pointer, py_object, CDLL, cdll, CFUNCTYPE, POINTER, find_library.  So, most of it!

Any guidance, or pointers to other packages that have done similar things, would be appreciated!

**Comment by rth** [comment]
Yes, currently we [remove the `ctypes` module](https://github.com/iodide-project/pyodide/blob/f2c92ad43112366951530fe63c48bf6969a89070/cpython/remove_modules.txt#L2) as it's not supported.

@pmp-p Has managed to make it work in [micropython-ports-wasm](https://github.com/pmp-p/micropython-ports-wasm) so it should be possible. As far as I understand CPython uses the [system libffi on Linux](https://github.com/python/cpython/blob/f501db2b93a9d3d840b6fb38d6bdda8bcc400d4a/Doc/whatsnew/3.6.rst#deprecated-build-options), so the first step could be to take a libffi version patched for WASM, add it to pyodide and try to build CPython with it.

**Comment by pmp-p** [comment]
@rth problem is callbacks are not implemented so it's not currently not possible to link the whole ctypes modules "as is" with -lffi, but it would just need patching and removing missing references to cpython ( difficult to upstream ) or add more stubs to @brion's work with appropriate logging either via https://github.com/pmp-p/wapy/tree/wapy-wipdonotuse/ports/wapy-wasm/mod/ffi or https://github.com/brion/libffi/tree/emscripten-work

on wapy you can see PySDL2 loading/running via a subset of cpython ctypes/struct emulation ( select upysdl2.py tab on https://pmp-p.github.io/wapy/minide/  )

**Comment by lambertwx** [comment]
Thanks for the info.  I'll take a look!

**Comment by pmp-p** [comment]
https://github.com/python/cpython/pull/20451
+
https://github.com/pmp-p/pydk/blob/master/sources.wasm/libffi-3.3/libffi-3.3-emscripten.diff

looks good for 3.9.1 wasm ( I did not test for pyodide build yet )

**Comment by rth** [comment]
Thanks for the information @pmp-p, looks very promising!

**Comment by megapro17** [comment]
I'm also faced absence of ctypes when tried to run youtube-dl... hope it will be avaliable soon

**Comment by hoodmane** [comment]
According to @pmp-p, it might be easier to get ctypes support in Python 3.9. Upgrade to Python 3.9 is basically ready #1637 so if that's true then there is hope that we can get this working.

**Comment by hoodmane** [comment]
Well it seems like it will take some effort to get ctypes working. The main issue is libffi. There seems to be a libffi port for emscripten, but it hasn't been added to the official emscripten ports yet.

The emscripten issue about this is here:
emscripten-core/emscripten#11066

The libffi port is here:
https://gist.github.com/kleisauke/acfa1c09522705efa5eb0541d2d00887

**Comment by hoodmane** [comment]
Update: the libffi wasm port is missing support for closures. In particular ctypes needs implementations for `ffi_closure_alloc`, `ffi_closure_free`, and `ffi_prep_closure_loc` which the current libffi emscripten port is missing
