### ISSUE TITLE
Native file system API

### ISSUE THREAD

**Issue by SimonBiggs** [pyodide/pyodide#738]
The following two items were raised over at jyve:

* https://github.com/deathbeds/jyve/issues/47
* https://github.com/deathbeds/jyve/issues/46

Potentially it might be worth building these into pyodide for package installation and/or local file system access.

It looks like it'll be waiting upon emscripten to pick it up:

https://github.com/emscripten-core/emscripten/issues/10017

**Comment by rth** [comment]
@hoodmane has a WIP solution for this using Chrome FileSystem API and  https://github.com/hoodmane/synclink in  https://github.com/hoodmane/worker-pyodide-console/tree/nativefs

**Comment by ryanking13** [comment]
Probably https://github.com/emscripten-core/emscripten/pull/16804 will make things easier (at least for chrome users).

**Comment by ryanking13** [comment]
This was resolved by #2987

**Comment by westurner** [comment]
Thanks @ryanking13 ?

- [ ] DOC: how is this distinct from "Acessing local files"
https://jupyterlite.readthedocs.io/en/stable/howto/content/filesystem-access.html

Does this solvr for jupyterlab-git in WASM in JupyterLite?

And then also what about BusyBox ash, bash, or zsh filesystem access for
Terminals in JupyterLite?
