### ISSUE TITLE
problem with sending bytes to javascript

### ISSUE THREAD

**Issue by gowhari** [pyodide/pyodide#749]
Is there any restriction on sending bytes from python to javascript?

```javascript
pyodide.runPython('bytes([10])')
> Uint8ClampedArray [10]
pyodide.runPython('bytes([10, 11])')
> Uint8ClampedArray(2) [24, 0]
pyodide.runPython('bytes([10, 11, 12])')
> Uint8ClampedArray(3) [24, 0, 0]
pyodide.runPython('bytes([10, 11, 12, 13])')
> Uint8ClampedArray(4) [10, 11, 12, 13]

pyodide.runPython('b"A"')
> Uint8ClampedArray [65]
pyodide.runPython('b"AB"')
> Uint8ClampedArray(2) [24, 0]
pyodide.runPython('b"ABC"')
> Uint8ClampedArray(3) [24, 0, 0]
pyodide.runPython('b"ABCD"')
> Uint8ClampedArray(4) [65, 66, 67, 68]
```

What's `[24, 0]`?

It's different for different lengths:

```javascript
pyodide.runPython("b'0' * 4")
Uint8ClampedArray(4) [48, 48, 48, 48]
pyodide.runPython("b'0' * 100")
Uint8ClampedArray(100) [48, 48, 48, 48, 48, 48, 48, 48, 48, 48, ...
pyodide.runPython("b'0' * 200")
Uint8ClampedArray(200) [48, 48, 48, 48, 48, 48, 48, 48, 48, 48, ...
pyodide.runPython("b'0' * 300")
Uint8ClampedArray(300) [88, 51, 157, 0, 0, 0, 0, 0, 48, 48, 48, ...
```

It's `[88, 51, 157, 0, 0, 0, 0, 0,` this time.

Seems that there is no problem from javascript to python:

```javascript
f = pyodide.runPython(`
def f(x):
    print([x, x.tobytes()])
    return x
f
`)
> Proxy {$$: {…}, length: 0, name: "target", arguments: null, caller: null, …}
f(new Uint8Array([0]))
> pyodide.asm.js:8 [<memory at 0xa7d308>, b'\x00']
> Uint8Array [0]
f(new Uint8Array([0, 1]))
> pyodide.asm.js:8 [<memory at 0xa7d308>, b'\x00\x01']
> Uint8Array(2) [0, 1]
f(new Uint8Array([0, 1, 2]))
> pyodide.asm.js:8 [<memory at 0xa7d308>, b'\x00\x01\x02']
> Uint8Array(3) [0, 1, 2]
f(new Uint8Array([0, 1, 2, 3]))
> pyodide.asm.js:8 [<memory at 0xa7d308>, b'\x00\x01\x02\x03']
> Uint8Array(4) [0, 1, 2, 3]

```

I tested on this version:

```
pyodide.version(): "0.15.0"
pyodide.runPython('sys.version'): "3.7.4 (default, May 20 2020, 19:25:33) [Clang 6.0.1 ]"
Chrome 83
Firefox 76
```

**Comment by rth** [comment]
Thanks for the report! I can reproduce. For instance `b"AB"` produces indeed,
  - `Uint8ClampedArray [ 24, 0 ]` with v0.15.0 (Python 3.7) 
  - `Uint8ClampedArray [ 0, 8 ]` on master (Python 3.8) 

That doesn't look right. That pattern depending on the input length is also quite strange. There is a test that checks this conversion [here](https://github.com/iodide-project/pyodide/blob/e7dde959b8a6666a257f4d04e0a828c038b7416c/test/test_python.py#L35). It would be good to add another one with your `b"AB"` example.

The conversion should go though [_python2js_bytes](https://github.com/iodide-project/pyodide/blob/e7dde959b8a6666a257f4d04e0a828c038b7416c/src/python2js.c#L153) and then [hiwire_bytes](https://github.com/iodide-project/pyodide/blob/76efcaccf7cb0f478ed1f17fd36cd79f3370980e/src/hiwire.c#L87). I don't see any evident issues that could produce this result there, but it would be certainly worth investigating in more detail.

**Comment by gowhari** [comment]
Assigning the value to a variable changes this behavior. Not a fix, but may help to find the issue.

```javascript
pyodide.runPython('b"ABC"')
Uint8ClampedArray(3) [24, 0, 0]
pyodide.runPython('x = b"ABC"; x')
Uint8ClampedArray(3) [65, 66, 67]
```

**Comment by onursehitoglu** [comment]
I hit the same bug and tried couple of things.
I assigned the result into Javascript variable and run other Python scripts. The content of the `Uint8ClampedArray` changed. 

I believe it may be related to garbage collector. When it is not assigned to a variable, Python reclaims its memory.

**Comment by hoodmane** [comment]
> I believe it may be related to garbage collector. When it is not assigned to a variable, Python reclaims its memory.

This is exactly right. See #1221 and #1376 which are closely related. #1376 will resolve this.
