### ISSUE TITLE
Closing of matplotlib figures

### ISSUE THREAD

**Issue by joseph-long** [pyodide/pyodide#754]
If I call `plt.figure()` in a python cell, and execute it more than once, it creates a second (3rd, Nth..) figure. If I use `plt.clf()` I can draw into the same figure, but I'd like to be able to close / remove a figure from the rendered view and refresh it when re-executing.

Example notebook: https://alpha.iodide.io/notebooks/5414/

To reproduce: Run the notebook, then click in the last cell and shift-enter.

What happens: a new figure (Figure 2) is appended

What I expected to happen: output from this cell's last run replaced with re-rendered figure

**Comment by rth** [comment]
I think this is specific to the notebook implementation, so there is not much we can do this on the Pyodide end. 
Closing (but don't hesitate to comment on this issue).
