### ISSUE TITLE
`input()` call opens multiple browser input dialogs in Firefox

### ISSUE THREAD

**Issue by albertas** [pyodide/pyodide#757]
**Expected behaviour**
Only one input dialog is shown for each `input()` call, when its executed using the `pyodide.runPythonAsync` function. 

**Actual behaviour**
Infinite number of input popups is shown, till `cancel` is pressed in one of them.

**Versions**
Firefox 79.0
pyodide 0.15.0

**Comment by albertas** [comment]
Managed to fix this behavior by adding this code:

```
<script>
function input_fixed(text) {
    return prompt(text);
};

languagePluginLoader.then(() => {
  pyodide.runPythonAsync(`
from js import input_fixed
input = input_fixed
__builtins__.input = input_fixed
`);
});
</script>
```

**Comment by hoodmane** [comment]
Closing this in favor of #758.
