### ISSUE TITLE
META: Migrate to a conda compatible packages.json

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#791]
Currently pyodide has a very simple [packages.json](https://pyodide-cdn2.iodide.io/v0.15.0/full/packages.json), and it would be helpful to add additional useful information (package versions, checksums, file sizes, python and emscripten versions, date of the build, etc).

Conda has a fairly well defined [`repodata.json`](https://docs.conda.io/projects/conda-build/en/latest/concepts/generating-index.html#repodata-json)  (see e.g. another example [here](https://repo.anaconda.com/pkgs/pro/osx-64/repodata.json)) and I would propose to just use that format as much as possible.

This has the advantage of an already existing standard. Also when one day conda package managers (e.g. [mamba](https://github.com/mamba-org/mamba/)) are available in WebAssembly it might be possible to adapt them for dependency resolution of pyodide packages. cc @wolfv @SylvainCorlay

Currently the differences I see with the way conda packages work are,
 - pyodide packages are not necessarily compatible between releases, so for now there is 1 `packages.json` per pyoidide release (which also explains why the very simple dependency resolution that ignores versions is mostly sufficient)
 - there are 2 files (.js, .data) per package instead of 1, so we would probably need to use `sha256_data` and `sha256_js` keys

Also users can install [pure python wheels from PyPi](https://pyodide.readthedocs.io/en/latest/loading_packages.html#micropip) which poses its own challenges for dependency resolution.  

This would a small step in the direction of a better integration with conda-forge (https://github.com/iodide-project/pyodide/issues/38)

**Comment by wolfv** [comment]
Hi @rth!

This is a super-exciting topic for me. I would love to experiment with micromamba compiled to webassembly, and also with conda-webassembly packages. I think we could have a cross-compiling toolchain on conda-forge, and eventually produce webassembly outputs from conda-forge.

Do you guys have an idea what it would take? I guess the first step would be to make emscripten available on conda-forge?

**Comment by wolfv** [comment]
it looks like binaryen (albeit an older version) is already on conda-forge:

- https://github.com/conda-forge/binaryen-feedstock
- https://anaconda.org/conda-forge/binaryen/

**Comment by wolfv** [comment]
@jakirkham ping on this, since you were interested in the conda-side as well.

**Comment by rth** [comment]
Hi @wolfv, good to hear from you! I opened https://github.com/iodide-project/pyodide/issues/795 for a more general discussion of this topic, to keep this issue more specifically about the `packages.json` format..

**Comment by rth** [comment]
There was some progress on this, in particular now that sha256 checksums were added by @amitsaha  in #2455 . Still, the global structure of the json is a bit different,
**conda**
```json
{
  "packages": {
    "package-0.1.0-py37_0.tar.bz2": {
```
**Pyodide**
```json
{"packages": {
     "asciitree": {
       ...
       "file_name": "asciitree-0.3.3-py3-none-any.whl",
```
just because this makes indexing by package name more convenient for us. Otherwise, it means one has to parse the full json in JS and manually construct an index from it. There are also other differences (e.g. import names field in Pyodide) due to extra requirements we have. 
So overall it's never going to match 100% the conda repodata.json, and for now, I would close this.

If someone does try to use Pyodide's packages.json e.g. in mamba and runs into issues, then we can certainly re-open and see what we can do to make it work. Otherwise, this is a bit too abstract and without a practical impact on users.
