### ISSUE TITLE
Standard library 'import audioop' does not work when calling from Javascript

### ISSUE THREAD

**Issue by abolger** [pyodide/pyodide#801]
I am new to this project and it looks awesome, but I can't import the 'audioop' library, which is part of the python standard library. As a result, the following code line fails: 
`import audioop`

with error: 
"ModuleNotFoundError: No module named 'audioop'"

Here's a minimal modified HTML example showing the problem that can be pasted into a Code Pen and run. Select a file to run the code. Python successfully loads and runs, and micropip is imported correctly, but an attempt to import the standard audioop library results in a traceback

```
<!DOCTYPE html>
<html>

<head>
    <script type="text/javascript">
        window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
    </script>
    <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
</head>

<body>

 
  <!-- The `multiple` attribute lets users select multiple files. -->
<input type="file" id="file-selector" multiple>
<script type="text/javascript">
    function stringifyFiles(jsFileList) {
        let myArray = [];

        // manually create a new file obj for each File in the FileList
        for (var i = 0; i < jsFileList.length; i++) {

            let file = {
                'lastMod': jsFileList[i].lastModified,
                'lastModDate': jsFileList[i].lastModifiedDate,
                'name': jsFileList[i].name,
                'size': jsFileList[i].size,
                'type': jsFileList[i].type,
            }

            //add the file obj to your array
            myArray.push(file)
        }
        return JSON.stringify(myArray);
    }

  const fileSelector = document.getElementById('file-selector');
  fileSelector.addEventListener('change', (event) => {
    const fileList = event.target.files;
    console.log(fileList);
     const data = stringifyFiles(fileList)
      languagePluginLoader.then(async function () {
          await pyodide.loadPackage(['pandas', 'micropip'])
            .then(() => {
              pyodide.runPython(`
                
                import micropip
                import audioop
                
                
               `)
              
          });
      });
  });
</script>

</body>
```

P.S. The only documentation I can find on Pyodide implies this is a bug and that the whole Python standard library should be supported. If this is not true and I am asking a newbie question or don't understand the limitations of Pyodide, can someone please point me at the list of which standard libraries are and aren't supported?

**Comment by rth** [comment]
Thanks for the report. Audioop is apparently not included with default CPython build options (cf see https://github.com/python/cpython/blob/85a8a19134bf3f84e0c1504c2a5cd97aa255a63b/Modules/Setup#L230).

A PR to add it to https://github.com/iodide-project/pyodide/blob/master/cpython/Setup.local would be welcome. We would be able to to merge it assuming it doesn't increase the stdlib size too much.

**Comment by abolger** [comment]
Great! I will look into what it would take to do this and test it but I will try and build it and submit a PR in the next week if it is a feasible task.

**Comment by ijc8** [comment]
Hey, I ran into this issue recently while attempting to use the `wave` module (to generate a base64 string for an `<audio>` element), which depends on `audioop`. I plan to take a stab at including `audioop` as described above, but in the meantime I'll share this workaround, in case anyone else is trying to use the `wave` module in pyodide and doesn't actually need `audioop` itself:

```python
# HACK: Prevent `wave` import from failing due to lack of `audioop`.
import sys, types
audioop = types.ModuleType('audioop')
sys.modules['audioop'] = audioop
audioop.byteswap = lambda data, width: data
```
(This assumes that your wav data is already little-endian; if not, you may need to do an actual byteswap using e.g. [the array module](https://docs.python.org/3/library/array.html#array.array.byteswap) or reimplementing [`audioop.byteswap`](https://github.com/python/cpython/blob/8ab5b7eecaa1a1a249afbd3bf8358ce2b12e4713/Modules/audioop.c#L1223).)
