### ISSUE TITLE
'oakland' demo never loads

### ISSUE THREAD

**Issue by drscotthawley** [pyodide/pyodide#812]
The [Oakland demo](https://alpha.iodide.io/notebooks/1663/?viewMode=report) referred to on the project page takes not just 1 minute to load, but seemingly an infinite amount of time. 

JavaScript console shows the error to be:
```
Uncaught ReferenceError: require is not defined
    <anonymous> blob:https://alpha.iodide.app/acf21882-8008-4bdf-b756-39495f2802db:8

```
This occurs when using Firefox, Brave, and Chrome browsers on Ubuntu 20.10

**Comment by rth** [comment]
Unfortunately we are no longer supporting iodide (or at least not in this repo). Closing sorry.
