### ISSUE TITLE
Explain how to build C-based library

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#814]
Continuing the efforts in #809 , it would be helpful to have a clear explanation of what it takes to build a C-based library to be loaded by CDN-pyodide. It seems to me that the only thing one has to recompile is binaryen (can we provide a precompiled binary for download)? The other patches affect lz4 compression and main modules, not side modules. The cpython stuff has to be around, but I think we only need the headers, so no compilation is needed.

Ultimately, it would be very helpful if downstream users don't have to recompile all of emscripten, cpython and pyodide.

**Comment by rth** [comment]
Going in the direction of https://github.com/iodide-project/pyodide/pull/830 etc is very useful. But I'm less certain about distributing our version of binaryen (architecture dependent binary) and some parts CPython, as that would add to our maintenance burden.

With the latest changes the time to build emsdk + Cpython + C libraries is probably around 10min (or less when enabling make parallelism). This would be reduced once we start building C libraries (and in particular CLAPACK) with the regular Python build system (https://github.com/iodide-project/pyodide/issues/713).

The pre-built docker container with this minimal install is 3.8GB which is indeed not that small, but when used in CI (e.g. CircleCI) the image will be cached, so it should be fairly fast to use.

In the less immediate future, I would like to try using conda-forge more https://github.com/iodide-project/pyodide/issues/795. For instance, [emscripten](https://github.com/conda-forge/emscripten-feedstock/) and most of the other things in emsdk were packaged. Once that works, that would remove the need for using emsdk (assuming we update to the emscripten version used there, and have some way to deal with patches), a conda env with the right dependencies might be enough. We could probably also negotiate to have our patched version of binaryen maybe on less standard channel, and possibly create a pyodide-feedstock on conda-forge if we need more build tools.

**Comment by dalcde** [comment]
In git master of binaryen, num_params is a runtime parameter, so there
is no need for any patching: https://github.com/WebAssembly/binaryen/pull/3411

**Comment by rth** [comment]
@dalcde Do we still need any action on this or ca,n it be closed?

**Comment by dalcde** [comment]
I think this is blocked on running unpatched emscripten. Once we have
that building C-based packages would be much easier for end users.

**Comment by rth** [comment]
I think there has been a lot of documentation improvement in this area. Closing.
