### ISSUE TITLE
Use correct python cross-compilation terminology

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#832]
What we call `host` and `target` is what python calls `build` and `host`. In particular, `host` has the completely opposite meaning.

**Comment by rth** [comment]
I would say it's an issue with CPython terminology.

Host/target is fairly standard,

> In GCC world, every host/target combination ...

in Rust, https://rust-lang.github.io/rustup/cross-compilation.html

> When you first install a toolchain, rustup installs only the standard library for your *host* platform - that is, the architecture and operating system you are presently running. To compile to other platforms you must install other *target* platforms.

I also feel it's much easier to understand that build and host as well. Closing.
