### ISSUE TITLE
Cannot build regex package locally

### ISSUE THREAD

**Issue by oneearedrabbit** [pyodide/pyodide#884]
After the recent changes (I think the last time I built Pyodide was two weeks ago or so), I cannot compile `regex` package anymore. It's hard to tell whether it's a local configuration issue or something else (since CircleCI build passes). Hopefully, you can provide some guidance how to troubleshoot it, I'm happy to help as much as I can.

I ran `clean make-all` prior the compilation and then `make`. I'm running it on Linux/Ubuntu. Error log is below:
```
shared:ERROR: /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.wasm: No such file or directory ("/usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.wasm" was expected to be an input file, based on the commandline arguments provided)
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/<...>/projects/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.bc
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/<...>/projects/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c regex_3/_regex_unicode.c -o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.bc
emcc -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.wasm -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccDw1dmZ.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -shared -z relro -o build/lib.linux-x86_64-3.8/regex/_regex.cpython-38-x86_64-linux-gnu.wasm /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.bc /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.bc -L/lib/x86_64-linux-gnu -L/lib/../lib -O1 -Bsymbolic-functions -Bsymbolic-functions -z relro -Bsymbolic-functions -z relro build/temp.linux-x86_64-3.8/regex_3/_regex.bc build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.bc -lgcc --push-state --as-needed -lgcc_s --pop-state -lpthread -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.bc /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.bc
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/<...>/projects/pyodide/pyodide_build/__main__.py", line 34, in <module>
    main()
  File "/home/<...>/projects/pyodide/pyodide_build/__main__.py", line 28, in main
    args.func(args)
  File "/home/<...>/projects/pyodide/pyodide_build/buildpkg.py", line 314, in main
    build_package(path, args)
  File "/home/<...>/projects/pyodide/pyodide_build/buildpkg.py", line 254, in build_package
    compile(path, srcpath, pkg, args)
  File "/home/<...>/projects/pyodide/pyodide_build/buildpkg.py", line 145, in compile
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' ', '--ldflags', "-O2 -s BINARYEN_METHOD='native-wasm' -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE='clamp' --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ", '--target', '/home/<...>/projects/pyodide/cpython/installs/python-3.8.2', '--install-dir', '/home/<...>/projects/pyodide/packages/.artifacts']' returned non-zero exit status 1.

```

**Comment by oneearedrabbit** [comment]
I'll try to build it against recent commits to figure out what's changed.

**Comment by rth** [comment]
Do you are building it outside of docker, right? You could try `git clean -xfd` to remove files not tracked by git, **after making sure you don't have uncommited work** . There have been a lot of changes in the build setup last few weeks and I'm not sure `make clean-all` would remove everything during this migration.

If that still doesn't work, try to build in a conda env (last comment in https://github.com/iodide-project/pyodide/pull/830). One major change is that you need a host python for 3.8.x following https://github.com/iodide-project/pyodide/pull/830 .

**Comment by kirill-exos** [comment]
Thanks, I'll try later today and will report back.

**Comment by oneearedrabbit** [comment]
It's still failing after `git clean`. Since this is a vanilla Ubuntu it comes with Python2 and Python3 by default, although I doubt it causing the issue. `python3 -V` says `Python 3.8.5`.

I'll go ahead and test conda env now.

**Comment by oneearedrabbit** [comment]
Conda setup does help, I'll close this ticket out. Thank you!

I still don't understand what's causing this issue in the first place with a native python, but I don't think it worth the time to investigate. We can add setup instructions to README or docs/ for the future reference.

**Comment by pmp-p** [comment]
Please don't close unfixed issues, github CI uses Python 3.8.5 and problem is still there.
```
emcc: error: elf_x86_64: No such file or directory ("elf_x86_64" was expected to be an input file, based on the commandline arguments provided)
```
i suspect most of  thoseproblems are because the host python is built with gcc while pywasmcross replays sequence for clang. ( my system 3.8.5 is clang built and i can achieve full pyodide build )

**Comment by rth** [comment]
@pmp-p Could you please provide more information (which package failed, what was the compilation command etc)?

**Comment by pmp-p** [comment]
once removed the -Wl,-Bsymbolic-functions parameters  https://github.com/pmp-p/pyodide/blob/808e9ea483b2d7fef45a3dd408e76eddaea96ac2/build-system-3.8.diff#L159 i got that repartition
i'm sure it's because of gcc/host-3.8.5 and ubuntu tweaks,  because on my desktop with clang/host-3.8.5 couple they all pass.
```
CLEAN="\
 kiwisolver setuptools glpk jedi cloudpickle docutils pytest mpmath\
 bleach zarr python-sat Pygments attrs webencodings html5lib joblib\
 libiconv libxml libxslt xlrd asciitree beautifulsoup4\
 packaging cssselect pluggy msgpack more-itertools pyparsing decorator\
 CLAPACK toolz uncertainties atomicwrites nose cycler soupsieve sympy\
"

FAIL="\
 pandas traits nlopt Jinja2 autograd matplotlib networkx lxml nltk yt cytoolz\
 biopython regex numpy pillow imageio patsy MarkupSafe pyodide-interrupts\
 numcodecs freesasa statsmodels swiglpk optlang mne scipy\
 pywavelets scikit-learn scikit-image astropy\
"
```

I guess the call failing has to do with some lto optimisations specific to gcc/ubuntu see  https://github.com/pmp-p/pyodide/runs/2045718446?check_suite_focus=true#step:4:5401

**Comment by rth** [comment]
> once removed the -Wl,-Bsymbolic-functions parameters https://github.com/pmp-p/pyodide/blob/808e9ea483b2d7fef45a3dd408e76eddaea96ac2/build-system-3.8.diff#L159 i got that repartition

OK, great! Could you send a PR for that fix?

What was the issue you encountered with https://github.com/iodide-project/pyodide/pull/1287?

**Comment by rth** [comment]
Closing as there were a lot of changes to the build system since 2020. If there are still issues probably better to open a new issue.
