### ISSUE TITLE
Question: How do I compile with debug symbols?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#889]
I'm debugging adjustments to the C code, and when I get low level errors I see long stack traces mostly full of stuff like: `pyodide.asm.wasm:wasm-function[10685]:0x88aa26`. Is there a way to compile with debug symbols so that I can see what more of these functions are?

**Comment by hoodmane** [comment]
I guess the right thing to do is to link with `-s ASSERTIONS=2`. This should be added to the `Makefile` as an option. How do I add an option to `make`?

**Comment by rth** [comment]
Yes, `ASSERTIONS=2` help, though even with it I have sometimes run into obscure errors.

You can add it [here](https://github.com/iodide-project/pyodide/blob/master/Makefile#L34) for Cpython and type extensions and [here](https://github.com/iodide-project/pyodide/blob/4ae245855db57bb230f93b3a7f32ae27a92f5bf5/pyodide_build/common.py#L18) for packages. I don't think we need an extra mechanism to enable it, it's easy enough to add those (or other emscripten debugging options) when needed.

**Comment by hoodmane** [comment]
Can we add this to the building from sources section of the docs then?

**Comment by hoodmane** [comment]
It's currently not that easily discoverable (though presumably it's standard if you know about C...)

**Comment by rth** [comment]
We can add a link to https://emscripten.org/docs/porting/Debugging.html with mentions where these flags need to be changed in pyodide.

**Comment by hoodmane** [comment]
Oh great. I don't know why I didn't think to look at the emcc docs.

**Comment by rth** [comment]
https://pyodide.org/en/latest/development/debugging.html#interactive-debugging thanks to you own PR :)
