### ISSUE TITLE
CI should build and deploy docs

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#904]
We don't currently build the docs in the CI. I think we should.

**Comment by rth** [comment]
Yes, we should. I think there is a possible integration service with readthedocs that shows status in CI, but getting RDT access permissions would likely take some time (mdboom is the only maintainer for the RTD project at the moment). So for now building the docs in a separate CircleCI job might be enough.

**Comment by hoodmane** [comment]
Yeah, it'd be very convenient to automatically deploy the current development version docs, but it'd already be a big improvement just to know that they build correctly.

**Comment by rth** [comment]
Fixed with Readthedocs integration.
