### ISSUE TITLE
"use strict" as much as possible (particularly in EM_JS)

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#911]
The javascript generated by Emscripten is by default not in strict mode. Strict mode javascript generates errors earlier and makes bugs easier to find and fix. We should `"use strict"` as much as possible.

**Comment by rth** [comment]
+1. https://github.com/iodide-project/pyodide/pull/792 might help, at least for `pyodide.js`file

**Comment by hoodmane** [comment]
Done in EM_JS quite a while ago. For the remaining cases I'm closing this in favor of #1477.
