### ISSUE TITLE
FeatureRequest: delete or unmount special package .

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [pyodide/pyodide#961]
ref to #960 #959 

have any building way to bannd some import ? example about the `micropip` or the `pyodide` ? 

bannd package import or unload it after import.

Example , we can add a callback to filter and approve the import ? or add a function to list now loaded package and unload some of it ?

**Comment by dalcde** [comment]
I think in the long run, we ought to unbundle these packages from the main pyodide js/data, and load them as normal packages at start time. Users can then customize the load script themselves.

**Comment by Lyoko-Jeremie** [comment]
@dalcde you are right ! this is the right way.

**Comment by hoodmane** [comment]
Possible to prevent loading `micropip` and most packages by blocking network requests. Not possible to block loading `js`, `pyodide_js`, or `pyodide` without significant design work.
