### ISSUE TITLE
Allow objects to specify how they should be converted

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#964]
I propose that if a python object implements a `__tojs__()` method, we use that to convert it to python. If a javascript object implements `__topy__()` we use that to convert it to javascript.

For this to work well, we ought to expose `pyproxy`, `jsproxy`, and various explicit conversion functions to the implementer, at least if they are willing to work in C (some APIs may make less sense to expose in js / python?).

**Comment by Lyoko-Jeremie** [comment]
this is a good idea, now i covert the python error message or other thing from WebWorker to postMessage to Main thread is use `postMessage({message: JSON.parse(JSON.stringify(thingResultFromPython))})` to do it , otherwise a error will throw and say the thingResultFromPython object cannot be clone.

**Comment by oeway** [comment]
This would be a very useful feature to have! In fact I have been proposing along these lines in [another thread](https://github.com/iodide-project/pyodide/issues/267#issuecomment-446173475)(already in 2018).

There I propose to have a intermediate representation of data types and split the process into encoding and decoding.

Could you elaborate on your idea about providing `__tojs__` and `__topy__`. Specifically, `__tojs__` for example, this will be a python function, how would you tell js to make an object?

**Comment by hoodmane** [comment]
> Specifically, __tojs__ for example, this will be a python function, how would you tell js to make an object?

I think this will take some design effort. I am working on the C type conversions code right now so I know what the C code could look like. Not all of these things are possible in python / js without support. I think the right approach is to have a `pyodide.conversions` module with utilities to help with this. 

The main reason it is currently impossible to implement `__tojs__` in python is that the C code uses hiwire ids for everything and currently there is no way to hold a hiwire id in Python. We need to make a `JsId` class which is an opaque hiwire id. Then `__tojs__` would be required return a hiwire id. The `pyodide.conversions` module would then have various converters that return `JsId`. 

The `JsId` object should have various conversion methods `to_py`, `to_py_shallow`, `to_py_deep`, possibly others. In the long run, all accesses to js objects should first create a `JsId` and then call `JsId.to_py`. A `JsProxy` should wrap a `JsId` and have a field to extract the id. All the operations on `JsProxy` should be implemented instead `JsId` and then the `JsProxy` operations should do `proxy.id.some_op().to_py()`.

**Comment by hoodmane** [comment]
I'm planning to almost completely rewrite the type conversions system and make one mega PR in attempt to fix everything. The current design is pretty deficient.

**Comment by hoodmane** [comment]
> a intermediate representation of data types 

This is an interesting idea, presumably it would allow more code sharing between py2js and js2py conversions.

**Comment by oeway** [comment]
> The main reason it is currently impossible to implement `__tojs__` in python is that the C code uses hiwire ids for everything and currently there is no way to hold a hiwire id in Python. We need to make a `JsId` class which is an opaque hiwire id. Then `__tojs__` would be required return a hiwire id. The `pyodide.conversions` module would then have various converters that return `JsId`.
> 
> The `JsId` object should have various conversion methods `to_py`, `to_py_shallow`, `to_py_deep`, possibly others. In the long run, all accesses to js objects should first create a `JsId` and then call `JsId.to_py()`. A `JsProxy` should wrap a `JsId` and have a field to extract the id. All the operations on `JsProxy` should be implemented instead `JsId` and then the `JsProxy` operations should do `proxy.id.some_op().to_py()`.

I am not familiar with the hiwire system in pyodide, but from what you described, it sounds like a lot of work indeed. I am also wondering how easy/hard would it be to support a new type for the user. Let's say if I want convert numpy array to tensor in tensorflow.js and the opposite. With the new `pyodide.conversions` module, how would the `__tojs__` and `__topy__` look like?

> This is an interesting idea, presumably it would allow more code sharing between py2js and js2py conversions. I'm not sure whether it is necessary though, it might just make things more complicated.

I am not in a good position to judge whether it will be more complicated than the approach you proposed, but it will certainly provide more flexibility, and potentially easier for the user to support new types.

The idea of an intermediate representation is to use a minimal set of primitive types ( which can be easily converted between js and python) to represent other types. I feel like this can be complementary to the low level type conversion you are proposing. I mean, the `pyodide.conversions` module can handles primitive types, on top of that we can build intermediate representation for user's own classes/types. For example, if we want to do the tensorflow.js tensor and numpy array conversion, we can do the following:
 1) during initialization, the user can register their own codec by implementing `encoder` and `decoder` function for a specific type. In Python, call `pyodide.registerCodec('numpy-array', np.ndarray, encoder, decoder)` , in JS. call `pyodide.registerCodec('tfjs-tensor', tf.Tensor, encoder, decoder)`
 2) Now to use it, In python, when we do `from js import myTensor`. In JS, pyodide will find the `tfjs-tensor` codec by testing `myTensor instanceof tf.Tensor` is true, then call the `encoder` function to convert myTensor into something like {'type': 'numpy-array', 'dtype': 'uint16', 'shape': [10,14,6], 'bytes': myTensor.bytes()}, this represented object will then be passed into Python, based on the `type` key, it matches the `numpy-array` codec and apply its `decoder` function which will then construct a numpy array based on the represented object. Finally, we will then get a numpy array object in Python.

**Comment by hoodmane** [comment]
> Let's say if I want convert numpy array to tensor in tensorflow.js and the opposite. With the new pyodide.conversions module, how would the __tojs__ and __topy__ look like?

This seems like it could be a good example to use as a test case for any proposed design of an api. Unfortunately, I am completely unfamiliar with `numpy` and with `tensorflow.js`. 
There is already conversion code for `memoryview` <==> `TypedArray` in pyodide. So probably most of the work to do that already exists in the codebase before I got to it. It's just an issue of exposing enough for you to say what to do. 

I don't like the idea of `pyodide.registerCodec` I think we should use `tojs` and `topy` methods like I said. This makes the logic for the converter simpler. I think testing whether an object is supported by a particular converter is tricky. Not sure though.

Also, we should distinguish between `copy_to_py` / `copy_to_js` and `to_py` / `to_js`. When using `to_py` / `to_js` the output should share memory with the input.


Maybe it would be a good idea for you to try implementing this conversion in C yourself, then you'll have a better idea of what needs to be done. I can help with that, but first you'd need to be able to build pyodide from source. The python `memoryview` to `TypedArray` direction happens in [python2js_buffer.c](https://github.com/iodide-project/pyodide/blob/master/src/type_conversion/python2js_buffer.c), the whole file is obviously relevant. Note that this direction is a copy unless the `TypedArray` was on the wasm stack. 
The conversion in the other direction is much simpler, I suppose because the `memoryview` has more info in it than the `TypedArray`. The whole py2js conversion is in [`JsProxy_GetBuffer`](https://github.com/iodide-project/pyodide/blob/master/src/type_conversion/jsproxy.c#L289).

Can you pass `tensorflow.js` custom `TypedArray` backing / allocators? Then you could just ask it to malloc memory on the CPython wasm heap to begin with. Or most likely `tensorflow.js` is a separate wasm module with a separate heap? Then both directions will need a copy...

**Comment by oeway** [comment]
> This seems like it could be a good example to use as a test case for any proposed design of an api. Unfortunately, I am completely unfamiliar with numpy and with tensorflow.js.

They are basically n-dimensional array which can be represented with `memoryview` + shape (an list, e.g.: [10, 20, 3]) + data type (a string, `uint16`). Also see [here](https://github.com/iodide-project/pyodide/issues/267#issuecomment-446173475). 

> I don't like the idea of pyodide.registerCodec I think we should use tojs and topy methods like I said. This makes the logic for the converter simpler. I think testing whether an object is supported by a particular converter is tricky. Not sure though.

There are pros and cons, a big disadvantage of the `tojs` and `topy` approach is that you need to modify the object which can be too "invasive" for third-party libraries. Tensor in tensorflow.js for example, it's an already made js library, how would you provide the `topy` method for all the Tensor object? By monkey patching? With `reigsterCodec`, we can leave all the object untouched.

> Also, we should distinguish between copy_to_py / copy_to_js and to_py / to_js. When using to_py / to_js the output should share memory with the input.

Why not do shallow copy or share memory by default, just behaves like when you assign one object to another in python or js, then if one want to make a copy, use `copy.deepcopy` in python or equivalent way in js?

> Maybe it would be a good idea for you to try implementing this conversion in C yourself, then you'll have a better idea of what needs to be done. I can help with that, but first you'd need to be able to build pyodide from source. The python memoryview to TypedArray direction happens in python2js_buffer.c, the whole file is obviously relevant. Note that this direction is a copy unless the TypedArray was on the wasm stack.

Although I have very limited experience with writing C module for Python, I can certainly try that. However, maybe I didn't get fully what you have in mind, isn't the idea to support writing `tojs` and `topy` in js and python? Why we need to dig into the C code? I imagine it will be too hard to be adopted for supporting new types.

**Comment by hoodmane** [comment]
Closed because it is not clear how to design this or that it is needed. If use cases arise, we can come back to it later.
