### ISSUE TITLE
jsfunc decorator?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#973]
Here's a funny idea:

```python
import inspect
from js import Function
from functools import wraps
def jsfunc(func):
    argspec = inspect.getargspec(func)
    code = inspect.getdoc(func)
    return Function.new(argspec.args, code)

@jsfunc
def test(a, b, c):
   """
   try {
      throw Error("I am in Javascript!");
   } catch(e){
      console.log(e);
   }
   return new Array(1, 2, 3, ...arguments);
   """
test(7, 0 ,2)
```
Returns `[1, 2, 3, 7, 0, 2, Proxy]`. Not sure how the proxy creeps in there, maybe our implementation of `JsProxy.__call__` is messed up. 

It does not work as a closure of course. As is you can't reference any of the variables from the enclosing python scope. You could do something like wrap it in a javascript closure and pass in a function `$` and then do name lookup like `$("a")` or `$.a`.

**Comment by dalcde** [comment]
I quite like the idea, as long as you get the extra arguments out of
the way...

**Comment by hoodmane** [comment]
One question is how we should do actual docstrings for this. Maybe if it starts with a js comment we can use that?
Annoyingly it doesn't seem possible to get the ast for dynamically defined functions in any reasonable way. I can raise a runtime warning if the disassembly doesn't look like the disassembly for `def f(*args, **kwargs): return None`
```asm
  3           0 LOAD_CONST               1 (None)
              2 RETURN_VALUE
```

**Comment by hoodmane** [comment]
I opened #974 for the argument issue.

**Comment by oeway** [comment]
This is a very cool feature to have, especially when the user can define their own type conversions as discussed in https://github.com/iodide-project/pyodide/issues/964.

**Comment by hoodmane** [comment]
See also #510.

**Comment by rth** [comment]
Do we still want this @hoodmane ? Also https://github.com/pyodide/pyodide/pull/2426 looks to be going in this direction.

**Comment by ryanking13** [comment]
Closing as we decided to use FFI Instead (#1179)
