### ISSUE TITLE
Specify supported browsers

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#982]
Having a clear list of supported browser gives a concrete policy for what javascript/webassembly features we can use.

**Comment by hoodmane** [comment]
The de facto state of things is we only support the browsers that we run selenium on.

**Comment by rth** [comment]
There is some hope for WebKit based browsers as well (https://github.com/iodide-project/pyodide/issues/989), for instance, Safari. I think package loading was working fine there before https://github.com/iodide-project/pyodide/pull/600
