### ISSUE TITLE
Including PsychoPy in the packages directory

### ISSUE THREAD

**Issue by mdctleo** [pyodide/pyodide#986]
Hello,

A number of psychology researchers that I have worked with use [PsychoPy](https://github.com/psychopy/psychopy) to bring their experiments online. The demand has increased due to COVID-19 which prevents in-person experiments. 

PsychoPy brings experiments online by translating Python code into Javascript, which sometimes run into issues and most researchers that I have worked with are only comfortable with working in Python. I am wondering if a library like PsychoPy can be included to the Pyodide project / is within the scope of the Pyodide project.

Thank you for the help!

**Comment by hoodmane** [comment]
As far as I can tell, PsychoPy is a pure python package so this should be easy.

**Comment by hoodmane** [comment]
See:
https://pyodide.readthedocs.io/en/latest/loading_packages.html

**Comment by dalcde** [comment]
>As far as I can tell, PsychoPy is a pure python package so this should be easy.

On the other hand, PsychoPy has a *lot* of dependencies

**Comment by rth** [comment]
> On the other hand, PsychoPy has a *lot* of dependencies

Yes, and [some of those](https://github.com/psychopy/psychopy/blob/cc666628d9d52a85557947635a6a336bed609c02/setup.cfg#L31) do not make sense/or will not work in the context of pyodide:  glfw (wont work due to ctypes), pyopengl (likely as well), pyqt5 (packaging Qt is a lots of work), requests (#140 ) etc

**Comment by hoodmane** [comment]
So can we close this with wont-fix / wont-implement?

**Comment by rth** [comment]
Well if someone is interested in trying to make it work by disabling all those dependencies it could still be worth investigating..

**Comment by hoodmane** [comment]
The first question is what features `PsychoPy` implements on it's own: perhaps it would be better to support the dependencies that we can support and direct `PsychoPy` users to use the dependencies directly? I suppose that's the first step in any case.

**Comment by hoodmane** [comment]
Looks like there is insufficient interest in implementing this for now so I'm closing that. We can reopen if someone wants to implement it in the future.
