### ISSUE TITLE
Make pyodide package files keep track of target pyodide version

### ISSUE THREAD

**Issue by dalcde** [pyodide/pyodide#990]
In the past we attempted to use PYODIDE_PACKAGE_ABI to ensure people don't accidentally load packages compiled for a different ABI. However, we never really updated the number, so in practice it is not effective. This required a custom version of `file_packager.py`, so it was removed in #991.

The solve the original issue, we can consider requiring the js files to include the intended pyodide version, e.g. `numpy-pyodide0.16.1.js`. This would mean that the "abi version" would automatically update with releases

**Comment by rth** [comment]
+1 to do it, the version in the package name sounds like a good solution as well.

**Comment by hoodmane** [comment]
We can do this as a followup to #2027.

**Comment by rth** [comment]
Right now emscripten version is used to track ABI version in wheel, but we may indeed switch to the pyodide version in the future. In any case, currently there is no action needed on this so closing this issue.
